pub(super) const BACKEND_SURFACES: &[(&str, &str, &str)] = &[
    (
        "AdmittedRecoveryFilesystemMedia::complete_recovery_queue_binding",
        "worth-store-physical-backend/recovery-media/admitted",
        "phase-7",
    ),
    (
        "execute_recovery_cleanup_removal",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "BackendRecoveryArtifactExpectation",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "BackendRecoveryArtifactExpectation::artifact",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "BackendRecoveryArtifactExpectation::byte_count",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "BackendRecoveryArtifactExpectation::digest",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "BackendRecoveryArtifactExpectation::new",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "BackendCompletedRecoveryCleanupRemoval",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "BackendCompletedRecoveryCleanupRemoval::admission",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "BackendCompletedRecoveryCleanupRemoval::artifact",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "BackendCompletedRecoveryCleanupRemoval::operation",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "BackendCompletedRecoveryCleanupRemoval::physical",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "BackendCompletedRecoveryCleanupRemoval::queue",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "BackendCompletedRecoveryCleanupRemoval::revalidation",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "BackendDeniedRecoveryCleanupRemoval",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "BackendDeniedRecoveryCleanupRemoval::admission",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "BackendDeniedRecoveryCleanupRemoval::artifact",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "BackendDeniedRecoveryCleanupRemoval::cause",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "BackendDeniedRecoveryCleanupRemoval::failure",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "BackendDeniedRecoveryCleanupRemoval::queue",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "BackendDeniedRecoveryCleanupRemoval::revalidation",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "BackendIndeterminateRecoveryCleanupRemoval",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "BackendIndeterminateRecoveryCleanupRemoval::admission",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "BackendIndeterminateRecoveryCleanupRemoval::artifact",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "BackendIndeterminateRecoveryCleanupRemoval::failure",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "BackendIndeterminateRecoveryCleanupRemoval::operation",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "BackendIndeterminateRecoveryCleanupRemoval::physical",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "BackendIndeterminateRecoveryCleanupRemoval::queue",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "BackendIndeterminateRecoveryCleanupRemoval::revalidation",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "BackendRecoveryCleanupArtifactRevalidationDenial",
        "worth-store-physical-backend/recovery-media/cleanup/revalidation",
        "phase-7",
    ),
    (
        "BackendRecoveryCleanupArtifactRevalidationProgress",
        "worth-store-physical-backend/recovery-media/cleanup/revalidation",
        "phase-7",
    ),
    (
        "BackendRecoveryCleanupArtifactRevalidationProgress::bytes_read",
        "worth-store-physical-backend/recovery-media/cleanup/revalidation",
        "phase-7",
    ),
    (
        "BackendRecoveryCleanupArtifactRevalidationProgress::reads_attempted",
        "worth-store-physical-backend/recovery-media/cleanup/revalidation",
        "phase-7",
    ),
    (
        "BackendRecoveryCleanupArtifactRevalidationProgress::reads_completed",
        "worth-store-physical-backend/recovery-media/cleanup/revalidation",
        "phase-7",
    ),
    (
        "BackendRecoveryCleanupRemovalDenialCause",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "BackendRecoveryCleanupRemovalDenialCause::failure",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "BackendRecoveryCleanupRemovalOutcome",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "BackendRecoveryCleanupRemovalRequest",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "BackendRecoveryCleanupRemovalRequest::admission",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "BackendRecoveryCleanupRemovalRequest::artifact",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "BackendRecoveryCleanupRemovalRequest::artifact_bytes",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "BackendRecoveryCleanupRemovalRequest::artifact_digest",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "BackendRecoveryCleanupRemovalRequest::checkpoint",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "BackendRecoveryCleanupRemovalRequest::checkpoint_bytes",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "BackendRecoveryCleanupRemovalRequest::checkpoint_digest",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "BackendRecoveryCleanupRemovalRequest::cleanup_plan",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "BackendRecoveryCleanupRemovalRequest::new",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "BackendRecoveryCleanupRemovalRequest::session",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "BackendRecoveryCleanupRemovalRequest::store",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "VerifiedCheckpointStream::encoded_digest",
        "worth-store-physical-format/checkpoint/inspection",
        "phase-7",
    ),
    (
        "ArtifactTreeFailure::recovery_denial",
        "worth-store-physical-backend/filesystem-media/artifact-tree/failure",
        "phase-7",
    ),
    (
        "ArtifactTreeFailure::recovery_io",
        "worth-store-physical-backend/filesystem-media/artifact-tree/failure",
        "phase-7",
    ),
    (
        "MediaOperationIdentity::from_recovery_effect",
        "worth-store-physical-backend/filesystem-media/owner-local-identity",
        "phase-7",
    ),
];
