pub(super) const BACKEND_SURFACES: &[(&str, &str, &str)] = &[
    (
        "AdmittedRecoveryFilesystemMedia::remove_recovery_wal_artifact_scheduled",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "CompletedScheduledRecoveryCleanupRemoval",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "CompletedScheduledRecoveryCleanupRemoval::coordinate",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "CompletedScheduledRecoveryCleanupRemoval::physical",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "CompletedScheduledRecoveryCleanupRemoval::queue",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "DeniedScheduledRecoveryCleanupRemoval",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "DeniedScheduledRecoveryCleanupRemoval::coordinate",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "DeniedScheduledRecoveryCleanupRemoval::failure",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "DeniedScheduledRecoveryCleanupRemoval::queue",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "IndeterminateScheduledRecoveryCleanupRemoval",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "IndeterminateScheduledRecoveryCleanupRemoval::coordinate",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "IndeterminateScheduledRecoveryCleanupRemoval::physical",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "IndeterminateScheduledRecoveryCleanupRemoval::queue",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "RecoveryCleanupRemovalOutcome",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "RecoveryWalArtifactCoordinate",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "RecoveryWalArtifactCoordinate::generation",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "RecoveryWalArtifactCoordinate::new",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
    (
        "RecoveryWalArtifactCoordinate::segment",
        "worth-store-physical-backend/recovery-media/cleanup",
        "phase-7",
    ),
];
