pub(super) const MEDIA_EFFECT_SURFACES: &[(&str, &str, &str)] = &[
    (
        "CompletedRecoveryCleanupPhysicalRemoval",
        "worth-store/media-ownership/recovery-cleanup/effect",
        "phase-7",
    ),
    (
        "CompletedRecoveryCleanupPhysicalRemoval::admission",
        "worth-store/media-ownership/recovery-cleanup/effect",
        "phase-7",
    ),
    (
        "CompletedRecoveryCleanupPhysicalRemoval::artifact",
        "worth-store/media-ownership/recovery-cleanup/effect",
        "phase-7",
    ),
    (
        "CompletedRecoveryCleanupPhysicalRemoval::operation",
        "worth-store/media-ownership/recovery-cleanup/effect",
        "phase-7",
    ),
    (
        "CompletedRecoveryCleanupPhysicalRemoval::queue",
        "worth-store/media-ownership/recovery-cleanup/effect",
        "phase-7",
    ),
    (
        "CompletedRecoveryCleanupPhysicalRemoval::revalidation",
        "worth-store/media-ownership/recovery-cleanup/effect",
        "phase-7",
    ),
    (
        "DeniedRecoveryCleanupPhysicalRemoval",
        "worth-store/media-ownership/recovery-cleanup/effect",
        "phase-7",
    ),
    (
        "DeniedRecoveryCleanupPhysicalRemoval::admission",
        "worth-store/media-ownership/recovery-cleanup/effect",
        "phase-7",
    ),
    (
        "DeniedRecoveryCleanupPhysicalRemoval::artifact",
        "worth-store/media-ownership/recovery-cleanup/effect",
        "phase-7",
    ),
    (
        "DeniedRecoveryCleanupPhysicalRemoval::cause",
        "worth-store/media-ownership/recovery-cleanup/effect",
        "phase-7",
    ),
    (
        "DeniedRecoveryCleanupPhysicalRemoval::failure",
        "worth-store/media-ownership/recovery-cleanup/effect",
        "phase-7",
    ),
    (
        "DeniedRecoveryCleanupPhysicalRemoval::queue",
        "worth-store/media-ownership/recovery-cleanup/effect",
        "phase-7",
    ),
    (
        "DeniedRecoveryCleanupPhysicalRemoval::revalidation",
        "worth-store/media-ownership/recovery-cleanup/effect",
        "phase-7",
    ),
    (
        "IndeterminateRecoveryCleanupPhysicalRemoval",
        "worth-store/media-ownership/recovery-cleanup/effect",
        "phase-7",
    ),
    (
        "IndeterminateRecoveryCleanupPhysicalRemoval::admission",
        "worth-store/media-ownership/recovery-cleanup/effect",
        "phase-7",
    ),
    (
        "IndeterminateRecoveryCleanupPhysicalRemoval::artifact",
        "worth-store/media-ownership/recovery-cleanup/effect",
        "phase-7",
    ),
    (
        "IndeterminateRecoveryCleanupPhysicalRemoval::failure",
        "worth-store/media-ownership/recovery-cleanup/effect",
        "phase-7",
    ),
    (
        "IndeterminateRecoveryCleanupPhysicalRemoval::operation",
        "worth-store/media-ownership/recovery-cleanup/effect",
        "phase-7",
    ),
    (
        "IndeterminateRecoveryCleanupPhysicalRemoval::queue",
        "worth-store/media-ownership/recovery-cleanup/effect",
        "phase-7",
    ),
    (
        "IndeterminateRecoveryCleanupPhysicalRemoval::revalidation",
        "worth-store/media-ownership/recovery-cleanup/effect",
        "phase-7",
    ),
    (
        "RecoveryCleanupArtifactRevalidationDenial",
        "worth-store/media-ownership/recovery-cleanup/revalidation",
        "phase-7",
    ),
    (
        "RecoveryCleanupArtifactRevalidationProgress",
        "worth-store/media-ownership/recovery-cleanup/revalidation",
        "phase-7",
    ),
    (
        "RecoveryCleanupArtifactRevalidationProgress::bytes_read",
        "worth-store/media-ownership/recovery-cleanup/revalidation",
        "phase-7",
    ),
    (
        "RecoveryCleanupArtifactRevalidationProgress::reads_attempted",
        "worth-store/media-ownership/recovery-cleanup/revalidation",
        "phase-7",
    ),
    (
        "RecoveryCleanupArtifactRevalidationProgress::reads_completed",
        "worth-store/media-ownership/recovery-cleanup/revalidation",
        "phase-7",
    ),
    (
        "RecoveryCleanupRemovalDenialCause",
        "worth-store/media-ownership/recovery-cleanup/effect",
        "phase-7",
    ),
    (
        "RecoveryCleanupRemovalDenialCause::failure",
        "worth-store/media-ownership/recovery-cleanup/effect",
        "phase-7",
    ),
    (
        "RecoveryCleanupRemovalOutcome",
        "worth-store/media-ownership/recovery-cleanup/effect",
        "phase-7",
    ),
];
