pub(super) const RUNTIME_SURFACES: &[(&str, &str, &str)] = &[
    (
        "PerformedRecoveryCleanupRemoval",
        "cleanup/performed_removal",
        "phase-7",
    ),
    (
        "PerformedRecoveryCleanupRemoval::occurrence",
        "cleanup/performed_removal",
        "phase-7",
    ),
    (
        "PhysicalRecoveryCleanupCancellation",
        "cleanup/cancellation",
        "phase-7",
    ),
    (
        "RecoveredPhysicalRuntimeHandoff::cleanup_posture",
        "handoff/recovered",
        "phase-7",
    ),
    (
        "RecoveryBaseImagePlan::source_artifacts",
        "progression/planned/basis",
        "phase-7",
    ),
    (
        "RecoveryCleanupCounters",
        "handoff/cleanup_posture",
        "phase-7",
    ),
    (
        "RecoveryCleanupDeferralEvidence",
        "handoff/cleanup_posture",
        "phase-7",
    ),
    (
        "RecoveryCleanupDeferralEvidence::target",
        "handoff/cleanup_posture",
        "phase-7",
    ),
    (
        "RecoveryCleanupDeferralReason",
        "cleanup/disposition",
        "phase-7",
    ),
    (
        "RecoveryCleanupDisposition",
        "cleanup/disposition",
        "phase-7",
    ),
    (
        "RecoveryCleanupDisposition::byte_count",
        "cleanup/disposition",
        "phase-7",
    ),
    (
        "RecoveryCleanupDisposition::kind",
        "cleanup/disposition",
        "phase-7",
    ),
    (
        "RecoveryCleanupDisposition::target",
        "cleanup/disposition",
        "phase-7",
    ),
    (
        "RecoveryCleanupDisposition::wal_range",
        "cleanup/disposition",
        "phase-7",
    ),
    (
        "RecoveryCleanupDispositionKind",
        "cleanup/disposition",
        "phase-7",
    ),
    ("RecoveryCleanupTarget", "cleanup/disposition", "phase-7"),
    (
        "RecoveryCleanupEligibility",
        "cleanup/eligibility",
        "phase-7",
    ),
    (
        "RecoveryCleanupEligibility::artifact",
        "cleanup/eligibility",
        "phase-7",
    ),
    (
        "RecoveryCleanupEligibility::byte_count",
        "cleanup/eligibility",
        "phase-7",
    ),
    (
        "RecoveryCleanupEligibility::range",
        "cleanup/eligibility",
        "phase-7",
    ),
    (
        "RecoveryCleanupEvidence",
        "handoff/cleanup_posture",
        "phase-7",
    ),
    (
        "RecoveryCleanupEvidence::counters",
        "handoff/cleanup_posture",
        "phase-7",
    ),
    (
        "RecoveryCleanupEvidence::deferrals",
        "handoff/cleanup_posture",
        "phase-7",
    ),
    (
        "RecoveryCleanupEvidence::dispositions",
        "handoff/cleanup_posture",
        "phase-7",
    ),
    (
        "RecoveryCleanupEvidence::freshness_samples",
        "handoff/cleanup_posture",
        "phase-7",
    ),
    (
        "RecoveryCleanupEvidence::performed_removals",
        "handoff/cleanup_posture",
        "phase-7",
    ),
    (
        "RecoveryCleanupEvidence::plan_identity",
        "handoff/cleanup_posture",
        "phase-7",
    ),
    (
        "RecoveryCleanupEvidence::published_generation",
        "handoff/cleanup_posture",
        "phase-7",
    ),
    (
        "RecoveryCleanupPosture",
        "handoff/cleanup_posture",
        "phase-7",
    ),
    (
        "RecoveryCleanupPosture::evidence",
        "handoff/cleanup_posture",
        "phase-7",
    ),
    (
        "RecoveryCleanupPosture::is_deferred",
        "handoff/cleanup_posture",
        "phase-7",
    ),
    (
        "ReopenedPhysicalRecovery::cleanup_cancellation_after_removal",
        "progression/reopened",
        "phase-7",
    ),
    (
        "ReopenedPhysicalRecovery::cleanup_cancellation_before_first",
        "progression/reopened",
        "phase-7",
    ),
    (
        "ReopenedPhysicalRecovery::finish_with_cleanup_cancellation",
        "progression/reopened",
        "phase-7",
    ),
];
