pub(super) const STORE_SURFACES: &[(&str, &str, &str)] = &[
    (
        "CompletedPhysicalRecoveryCleanupFreshnessRead",
        "worth-store/recovery-coordination/cleanup/freshness",
        "phase-7",
    ),
    (
        "CompletedPhysicalRecoveryCleanupFreshnessRead::physical",
        "worth-store/recovery-coordination/cleanup/freshness",
        "phase-7",
    ),
    (
        "CompletedPhysicalRecoveryCleanupFreshnessRead::selector",
        "worth-store/recovery-coordination/cleanup/freshness",
        "phase-7",
    ),
    (
        "CompletedPhysicalRecoveryCleanupFreshnessRead::signal",
        "worth-store/recovery-coordination/cleanup/freshness",
        "phase-7",
    ),
    (
        "CompletedPhysicalRecoveryCleanupFreshnessRead::work",
        "worth-store/recovery-coordination/cleanup/freshness",
        "phase-7",
    ),
    (
        "CompletedPhysicalRecoveryCleanupRemoval",
        "worth-store/recovery-coordination/cleanup/removal",
        "phase-7",
    ),
    (
        "CompletedPhysicalRecoveryCleanupRemoval::into_performed",
        "worth-store/recovery-coordination/cleanup/removal",
        "phase-7",
    ),
    (
        "CompletedPhysicalRecoveryCleanupRemoval::performed",
        "worth-store/recovery-coordination/cleanup/removal",
        "phase-7",
    ),
    (
        "CompletedPhysicalRecoveryCleanupRemoval::revalidation",
        "worth-store/recovery-coordination/cleanup/removal",
        "phase-7",
    ),
    (
        "PhysicalRecoveryCleanupAdmissionDenial",
        "worth-store/recovery-coordination/cleanup/admission/denial",
        "phase-7",
    ),
    (
        "PhysicalRecoveryCleanupAdmissionDenial::cancellation_recorded",
        "worth-store/recovery-coordination/cleanup/admission/denial",
        "phase-7",
    ),
    (
        "PhysicalRecoveryCleanupAdmissionDenial::kind",
        "worth-store/recovery-coordination/cleanup/admission/denial",
        "phase-7",
    ),
    (
        "PhysicalRecoveryCleanupAdmissionDenial::scheduler_deferred",
        "worth-store/recovery-coordination/cleanup/admission/denial",
        "phase-7",
    ),
    (
        "PhysicalRecoveryCleanupAdmissionDenial::submission_recorded",
        "worth-store/recovery-coordination/cleanup/admission/denial",
        "phase-7",
    ),
    (
        "PhysicalRecoveryCleanupAdmissionDenialKind",
        "worth-store/recovery-coordination/cleanup/admission/denial",
        "phase-7",
    ),
    (
        "PhysicalRecoveryCleanupCommandStage",
        "worth-store/recovery-coordination/cleanup",
        "phase-7",
    ),
    (
        "PhysicalRecoveryCleanupFreshnessReadDenial",
        "worth-store/recovery-coordination/cleanup/freshness",
        "phase-7",
    ),
    (
        "PhysicalRecoveryCleanupFreshnessReadDenial::completed",
        "worth-store/recovery-coordination/cleanup/freshness",
        "phase-7",
    ),
    (
        "PhysicalRecoveryCleanupFreshnessReadDenial::denied",
        "worth-store/recovery-coordination/cleanup/freshness",
        "phase-7",
    ),
    (
        "PhysicalRecoveryCleanupFreshnessReadDenial::kind",
        "worth-store/recovery-coordination/cleanup/freshness",
        "phase-7",
    ),
    (
        "PhysicalRecoveryCleanupFreshnessReadDenial::progress",
        "worth-store/recovery-coordination/cleanup/freshness",
        "phase-7",
    ),
    (
        "PhysicalRecoveryCleanupFreshnessReadDenialKind",
        "worth-store/recovery-coordination/cleanup/freshness",
        "phase-7",
    ),
    (
        "PhysicalRecoveryCleanupFreshnessReadOutcome",
        "worth-store/recovery-coordination/cleanup/freshness",
        "phase-7",
    ),
    (
        "PhysicalRecoveryCleanupFreshnessReadProgress",
        "worth-store/recovery-coordination/cleanup/freshness",
        "phase-7",
    ),
    (
        "PhysicalRecoveryCleanupFreshnessReadProgress::scheduler",
        "worth-store/recovery-coordination/cleanup/freshness",
        "phase-7",
    ),
    (
        "PhysicalRecoveryCleanupFreshnessReadProgress::signal",
        "worth-store/recovery-coordination/cleanup/freshness",
        "phase-7",
    ),
    (
        "PhysicalRecoveryCleanupFreshnessReadProgress::work",
        "worth-store/recovery-coordination/cleanup/freshness",
        "phase-7",
    ),
    (
        "PhysicalRecoveryCleanupRemovalCommand",
        "worth-store/recovery-coordination/cleanup/removal",
        "phase-7",
    ),
    (
        "PhysicalRecoveryCleanupRemovalDenial",
        "worth-store/recovery-coordination/cleanup/removal",
        "phase-7",
    ),
    (
        "PhysicalRecoveryCleanupRemovalDenial::kind",
        "worth-store/recovery-coordination/cleanup/removal",
        "phase-7",
    ),
    (
        "PhysicalRecoveryCleanupRemovalDenial::physical",
        "worth-store/recovery-coordination/cleanup/removal",
        "phase-7",
    ),
    (
        "PhysicalRecoveryCleanupRemovalDenial::scheduler",
        "worth-store/recovery-coordination/cleanup/removal",
        "phase-7",
    ),
    (
        "PhysicalRecoveryCleanupRemovalDenial::signal",
        "worth-store/recovery-coordination/cleanup/removal",
        "phase-7",
    ),
    (
        "PhysicalRecoveryCleanupRemovalDenial::work",
        "worth-store/recovery-coordination/cleanup/removal",
        "phase-7",
    ),
    (
        "PhysicalRecoveryCleanupRemovalDenialKind",
        "worth-store/recovery-coordination/cleanup/removal",
        "phase-7",
    ),
    (
        "PhysicalRecoveryCleanupRemovalIndeterminate",
        "worth-store/recovery-coordination/cleanup/removal",
        "phase-7",
    ),
    (
        "PhysicalRecoveryCleanupRemovalIndeterminate::revalidation",
        "worth-store/recovery-coordination/cleanup/removal",
        "phase-7",
    ),
    (
        "PhysicalRecoveryCleanupRemovalOutcome",
        "worth-store/recovery-coordination/cleanup/removal",
        "phase-7",
    ),
    (
        "PhysicalRecoveryCoordination::execute_cleanup_removal",
        "worth-store/recovery-coordination/cleanup",
        "phase-7",
    ),
    (
        "PhysicalRecoveryFreshnessPort::sample_cleanup",
        "worth-store/recovery-freshness/port",
        "phase-7",
    ),
    (
        "RecoveryCleanupRemovalAction",
        "worth-store/recovery-coordination/effect/cleanup",
        "phase-7",
    ),
    (
        "RecoveryCleanupRemovalOccurrence",
        "worth-store/recovery-coordination/effect/cleanup",
        "phase-7",
    ),
    (
        "RecoveryCleanupRemovalOccurrence::artifact",
        "worth-store/recovery-coordination/effect/cleanup",
        "phase-7",
    ),
    (
        "RecoveryCleanupRemovalOccurrence::byte_count",
        "worth-store/recovery-coordination/effect/cleanup",
        "phase-7",
    ),
    (
        "RecoveryCleanupRemovalOccurrence::checkpoint",
        "worth-store/recovery-coordination/effect/cleanup",
        "phase-7",
    ),
    (
        "RecoveryCleanupRemovalOccurrence::lsn_range",
        "worth-store/recovery-coordination/effect/cleanup",
        "phase-7",
    ),
    (
        "RecoveryCleanupRemovalOccurrence::physical",
        "worth-store/recovery-coordination/effect/cleanup",
        "phase-7",
    ),
    (
        "RecoveryCleanupRemovalOccurrence::plan",
        "worth-store/recovery-coordination/effect/cleanup",
        "phase-7",
    ),
    (
        "RecoveryCleanupRemovalOccurrence::published_generation",
        "worth-store/recovery-coordination/effect/cleanup",
        "phase-7",
    ),
    (
        "RecoveryCleanupRemovalOccurrence::scheduler",
        "worth-store/recovery-coordination/effect/cleanup",
        "phase-7",
    ),
    (
        "RecoveryCleanupRemovalOccurrence::session",
        "worth-store/recovery-coordination/effect/cleanup",
        "phase-7",
    ),
    (
        "RecoveryCleanupRemovalOccurrence::signal",
        "worth-store/recovery-coordination/effect/cleanup",
        "phase-7",
    ),
    (
        "RecoveryCleanupRemovalOccurrence::work",
        "worth-store/recovery-coordination/effect/cleanup",
        "phase-7",
    ),
    (
        "StoreRecoveryCleanupFreshnessAdmission",
        "worth-store/recovery-freshness/cleanup",
        "phase-7",
    ),
    (
        "StoreRecoveryCleanupFreshnessAdmission::into_parts",
        "worth-store/recovery-freshness/cleanup",
        "phase-7",
    ),
    (
        "StoreRecoveryCleanupFreshnessAdmission::sample",
        "worth-store/recovery-freshness/cleanup",
        "phase-7",
    ),
    (
        "StoreRecoveryCleanupFreshnessDenial",
        "worth-store/recovery-freshness/cleanup",
        "phase-7",
    ),
    (
        "StoreRecoveryCleanupFreshnessFailure",
        "worth-store/recovery-freshness/cleanup",
        "phase-7",
    ),
    (
        "StoreRecoveryCleanupFreshnessFailure::denial",
        "worth-store/recovery-freshness/cleanup",
        "phase-7",
    ),
    (
        "StoreRecoveryCleanupFreshnessFailure::binding",
        "worth-store/recovery-freshness/cleanup",
        "phase-7",
    ),
    (
        "StoreRecoveryCleanupFreshnessFailure::read",
        "worth-store/recovery-freshness/cleanup",
        "phase-7",
    ),
    (
        "StoreRecoveryCleanupFreshnessSample",
        "worth-store/recovery-freshness/cleanup",
        "phase-7",
    ),
    (
        "StoreRecoveryCleanupFreshnessSample::cleanup_plan_identity",
        "worth-store/recovery-freshness/cleanup",
        "phase-7",
    ),
    (
        "StoreRecoveryCleanupFreshnessSample::observed_published_generation",
        "worth-store/recovery-freshness/cleanup",
        "phase-7",
    ),
    (
        "StoreRecoveryCleanupFreshnessSample::policy_identity",
        "worth-store/recovery-freshness/cleanup",
        "phase-7",
    ),
    (
        "StoreRecoveryCleanupFreshnessSample::sealed_publication_basis",
        "worth-store/recovery-freshness/cleanup",
        "phase-7",
    ),
    (
        "StoreRecoveryCleanupFreshnessSample::selector_read_operation",
        "worth-store/recovery-freshness/cleanup",
        "phase-7",
    ),
    (
        "StoreRecoveryCleanupFreshnessSample::signal",
        "worth-store/recovery-freshness/cleanup",
        "phase-7",
    ),
    (
        "StoreRecoveryCleanupFreshnessSample::store_identity",
        "worth-store/recovery-freshness/cleanup",
        "phase-7",
    ),
    (
        "StoreRecoveryCleanupFreshnessSample::work",
        "worth-store/recovery-freshness/cleanup",
        "phase-7",
    ),
];
