pub(super) const STORE_CLEANUP_LIFECYCLE_SURFACES: &[(&str, &str, &str)] = &[
    (
        "ClosedPhysicalRecoveryCleanup",
        "worth-store/recovery-coordination/cleanup/close",
        "phase-7",
    ),
    (
        "ClosedPhysicalRecoveryCleanup::authority_plan_identity",
        "worth-store/recovery-coordination/cleanup/close",
        "phase-7",
    ),
    (
        "ClosedPhysicalRecoveryCleanup::descriptive_plan_identity",
        "worth-store/recovery-coordination/cleanup/close",
        "phase-7",
    ),
    (
        "ClosedPhysicalRecoveryCleanup::live_media_handle_delta",
        "worth-store/recovery-coordination/cleanup/close",
        "phase-7",
    ),
    (
        "PhysicalRecoveryCoordination::defer_cleanup",
        "worth-store/recovery-coordination/cleanup",
        "phase-7",
    ),
    (
        "StoreRecoveryCleanupPlan::close",
        "worth-store/recovery-freshness/cleanup/plan",
        "phase-7",
    ),
    (
        "StoreRecoveryCleanupPlanAdmissionFailure",
        "worth-store/recovery-freshness/cleanup/plan",
        "phase-7",
    ),
    (
        "StoreRecoveryCleanupPlanAdmissionFailure::failure",
        "worth-store/recovery-freshness/cleanup/plan",
        "phase-7",
    ),
    (
        "StoreRecoveryCleanupPlanAdmissionFailure::into_parts",
        "worth-store/recovery-freshness/cleanup/plan",
        "phase-7",
    ),
];
