pub(super) const WAL_SURFACES: &[(&str, &str, &str)] = &[
    (
        "VerifiedWalArtifact",
        "worth-store-wal/artifact-store/segment-inventory/segment-inspection/owned-artifact",
        "phase-7",
    ),
    (
        "VerifiedWalArtifact::frames",
        "worth-store-wal/artifact-store/segment-inventory/segment-inspection/owned-artifact",
        "phase-7",
    ),
    (
        "VerifiedWalArtifact::inspection",
        "worth-store-wal/artifact-store/segment-inventory/segment-inspection/owned-artifact",
        "phase-7",
    ),
    (
        "VerifiedWalSegment::to_owned_artifact",
        "worth-store-wal/artifact-store/segment-inventory/segment-inspection/owned-artifact",
        "phase-7",
    ),
    (
        "artifact_store::VerifiedWalArtifact",
        "worth-store-wal/artifact-store/segment-inventory/segment-inspection/owned-artifact",
        "phase-7",
    ),
    (
        "artifact_store::VerifiedWalArtifact::frames",
        "worth-store-wal/artifact-store/segment-inventory/segment-inspection/owned-artifact",
        "phase-7",
    ),
    (
        "artifact_store::VerifiedWalArtifact::inspection",
        "worth-store-wal/artifact-store/segment-inventory/segment-inspection/owned-artifact",
        "phase-7",
    ),
    (
        "artifact_store::VerifiedWalSegment::to_owned_artifact",
        "worth-store-wal/artifact-store/segment-inventory/segment-inspection/owned-artifact",
        "phase-7",
    ),
];
