//! Compatibility module paths for in-crate imports during lane topology migration.

pub use super::activation::activation_staging as activation_staging;
pub use super::activation::atomic_plan_swap as atomic_plan_swap;
pub use super::activation::frame_activation_gate as frame_activation_gate;
pub use super::execution::canvas_spatial_lane as canvas_spatial_lane;
pub use super::execution::handle_allocation as handle_allocation;
pub use super::execution::lane_admission as lane_admission;
pub use super::execution::lane_frame_cost_certification as lane_frame_cost_certification;
pub use super::execution::lane_meaning_parity as lane_meaning_parity;
pub use super::execution::ordinary_lane as ordinary_lane;
pub use super::execution::realtime_overlay_lane as realtime_overlay_lane;
pub use super::execution::reload_counter_boundary as reload_counter_boundary;
pub use super::execution::steady_frame_counter_boundary as steady_frame_counter_boundary;
pub use super::execution::virtualized_data_lane as virtualized_data_lane;
pub use super::host_observation::diagnostics as diagnostics;
pub use super::host_observation::diagnostics_projection as diagnostics_projection;
pub use super::host_observation::identity_state_query_certification as identity_state_query_certification;
pub use super::host_observation::reload_failure as reload_failure;
pub use super::host_observation::reload_storm_certification as reload_storm_certification;
pub use super::planning::allocation_planning as allocation_planning;
pub use super::planning::execution_plan_input as execution_plan_input;
pub use super::planning::plan_equivalence as plan_equivalence;
pub use super::planning::plan_inspection as plan_inspection;
pub use super::planning::plan_topology as plan_topology;
pub use super::replacement::admission as admission;
pub use super::replacement::candidate as candidate;
pub use super::replacement::equivalence as equivalence;
pub use super::replacement::file_rust_replacement_parity as file_rust_replacement_parity;
pub use super::replacement::impact as impact;
pub use super::replacement::matching as matching;
pub use super::replacement::narrowing as narrowing;
pub use super::replacement::query_binding as query_binding;
pub use super::replacement::query_live_rebind as query_live_rebind;
pub use super::replacement::reconciliation as reconciliation;
pub use super::replacement::state_inventory as state_inventory;
pub use super::replacement;