//! Feature catalog — the single source of truth for all supported features.
//!
//! DOMAIN: Defines which feature types the kernel supports via the
//! `feature_catalog!` macro. Adding a new feature = adding one line here.
//!
//! INVARIANTS:
//! - `FeatureKind` is exhaustively generated by the macro
//! - `execute_via_pipeline` dispatches to `FeaturePipeline::execute`

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

use forge_core::envelope::OperationResult;
use forge_core::KernelError;
use forge_signal::facade::NodeId;

use crate::configuration::facade::KernelConfig;
use crate::engine::facade::{FeatureOutput, FeaturePipeline};

/// Generates the `FeatureKind` enum and its `execute_via_pipeline` dispatch.
///
/// # Adding a new feature
///
/// 1. Create your feature struct + `Feature` impl in its own directory
/// 2. Add one line to the `feature_catalog!` invocation below
/// 3. Done — the macro generates the enum variant and dispatch arm.
macro_rules! feature_catalog {
    ($($variant:ident($type:ty)),* $(,)?) => {
        /// Variant-specific feature data. No shared identity here — just the
        /// type-specific parameters. Identity (name, dependencies) lives on
        /// [`NativeFeature`](super::native_feature::NativeFeature).
        #[derive(Debug, Clone, Serialize, Deserialize)]
        pub enum FeatureKind {
            $($variant($type)),*
        }

        impl FeatureKind {
            /// Execute this feature kind through the pipeline.
            ///
            /// Each variant delegates to `FeaturePipeline::execute` with its
            /// concrete `Feature` impl — the macro generates the match arms.
            pub fn execute_via_pipeline(
                &self,
                inputs: &HashMap<NodeId, FeatureOutput>,
                session_config: &KernelConfig,
            ) -> Result<OperationResult<FeatureOutput>, KernelError> {
                match self {
                    $(FeatureKind::$variant(f) => FeaturePipeline::execute(f, inputs, session_config)),*
                }
            }
        }
    };
}

// ── THE CATALOG ──────────────────────────────────────────────────────────────
//
// This is the only thing that changes when adding a feature.
// One line per feature kind:

feature_catalog! {
    MakePrimitive(crate::primitives::MakePrimitiveFeature),
    Boolean(crate::operations::boolean::BooleanFeature),
}
