/// Provider-independent checkpoints required by the Milestone 13 handoff.
#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
pub enum WorthQueryCertificationJourneyCheckpoint {
    OperationResolution,
    Installation,
    SingleRootEntry,
    GraphParticipation,
    MultiDomainBinding,
    MultiGraphBinding,
    WorkflowProgression,
    Reexecution,
    Replay,
    Reversal,
    Publication,
    Lineage,
    Promotion,
    Support,
    Execution,
    Consumption,
    NativeAccess,
    DependencyImpact,
    Sharing,
    Lease,
    Compatibility,
    Invalidation,
    CollectionWindow,
    CollectionPatch,
}

impl WorthQueryCertificationJourneyCheckpoint {
    pub const ALL: [Self; 24] = [
        Self::OperationResolution,
        Self::Installation,
        Self::SingleRootEntry,
        Self::GraphParticipation,
        Self::MultiDomainBinding,
        Self::MultiGraphBinding,
        Self::WorkflowProgression,
        Self::Reexecution,
        Self::Replay,
        Self::Reversal,
        Self::Publication,
        Self::Lineage,
        Self::Promotion,
        Self::Support,
        Self::Execution,
        Self::Consumption,
        Self::NativeAccess,
        Self::DependencyImpact,
        Self::Sharing,
        Self::Lease,
        Self::Compatibility,
        Self::Invalidation,
        Self::CollectionWindow,
        Self::CollectionPatch,
    ];
}
