from __future__ import annotations

LOAD_RUN_AUTHORITY_NODE_ID = "load_run_authority"
LOWER_PHASE_PROGRAM_NODE_ID = "lower_phase_program"
SELECT_ROLE_SESSION_NODE_ID = "select_role_session"
MATERIALIZE_TURN_ASSEMBLY_PROMPT_NODE_ID = "materialize_turn_assembly_prompt"
MATERIALIZE_PHASE_ASSET_PROMPT_NODE_ID = "materialize_phase_asset_prompt"
EXECUTE_ROLE_TURN_NODE_ID = "execute_role_turn"
CLASSIFY_TURN_OUTCOME_NODE_ID = "classify_turn_outcome"
ROUTE_OUTCOME_REPAIR_OR_RECOVERY_NODE_ID = "route_outcome_repair_or_recovery"
APPEND_RUNNER_EVENT_NODE_ID = "append_runner_event"
PUBLISH_PROJECTION_NODE_ID = "publish_projection"
EVALUATE_ESCALATION_NODE_ID = "evaluate_escalation"
ROUTE_NEXT_STEP_NODE_ID = "route_next_step"

GRAPH_NODE_IDS = (
    LOAD_RUN_AUTHORITY_NODE_ID,
    LOWER_PHASE_PROGRAM_NODE_ID,
    SELECT_ROLE_SESSION_NODE_ID,
    MATERIALIZE_TURN_ASSEMBLY_PROMPT_NODE_ID,
    MATERIALIZE_PHASE_ASSET_PROMPT_NODE_ID,
    EXECUTE_ROLE_TURN_NODE_ID,
    CLASSIFY_TURN_OUTCOME_NODE_ID,
    ROUTE_OUTCOME_REPAIR_OR_RECOVERY_NODE_ID,
    APPEND_RUNNER_EVENT_NODE_ID,
    PUBLISH_PROJECTION_NODE_ID,
    EVALUATE_ESCALATION_NODE_ID,
    ROUTE_NEXT_STEP_NODE_ID,
)

PROMPT_MATERIALIZATION_NODE_IDS = (
    MATERIALIZE_TURN_ASSEMBLY_PROMPT_NODE_ID,
    MATERIALIZE_PHASE_ASSET_PROMPT_NODE_ID,
)
