mod helpers;
mod key_registry;
mod patch_buffer;
mod runtime;
#[cfg(test)]
mod tests;

pub(crate) use runtime::RuntimeObservationRegistry;
pub use runtime::{branch_state_proof_report, canonical_digest};
#[allow(unused_imports)]
pub use runtime::{
    lowered_strategy_bundle_digest, merge_lineage_digest, merge_plan_proof_report,
    merge_result_proof_report, replay_artifact_proof_report, replay_parity_proof_report,
    runtime_proof_report, temporal_certification_builder, temporal_certification_bundle,
    temporal_certification_bundle_parity_report, temporal_certification_record,
    temporal_replay_parity_report, AdvisoryRecord, ArtifactMergeAction, ArtifactMergeComparable,
    AspectMergeDecisionOutcome, AspectMergePolicy, AspectMergePolicyBinding,
    AspectMergePolicyDescriptor, AspectMergePolicyId, AspectMergePolicyName,
    AspectMergePolicyRegistration, AspectMergePolicySelectionBasis, AspectMergePolicyVersion,
    BatchChangeSession, BoundedJournalSegment, BranchConflictResolutionPlan, BranchMergeBase,
    BranchMergeConflictEvidence, BranchMergeConflictKind, BranchMergeConflictRecord,
    BranchMergeConflictSummary, BranchMergeCounters, BranchMergeDeletionFailureEvidence,
    BranchMergeDivergence, BranchMergeExecutionSummary, BranchMergeFailureEvidence,
    BranchMergeFailureKind, BranchMergeIdentityFailureEvidence, BranchMergeKind, BranchMergePlan,
    BranchMergeReconciliationPolicy, BranchMergeRequest, BranchMergeResolutionRequirement,
    BranchMergeResult, BranchMergeStrategy, BranchMutationJournalSlice, BranchMutationLedger,
    BranchStateDenseGridProofBasis, BranchStateProofBasis, BranchStateProofReport,
    CheckpointBoundary, CheckpointRecord, CommittedObservationEventSummary,
    ConflictIsolationGranularity, ConflictIsolationPolicyDescriptor, ConflictIsolationPolicyId,
    ConflictIsolationPolicyName, ConflictIsolationPolicyRegistration,
    ConflictIsolationPolicyVersion, ConflictIsolationSelectionBasis, ConflictMergePolicy,
    ConflictPolicyDescriptor, ConflictPolicyId, ConflictPolicyName, ConflictPolicyRegistration,
    ConflictPolicySelectionBasis, ConflictPolicyVersion, ConflictResolutionRecord,
    ConflictResolutionStrategy, ConservativeOverlapExpansion, DecisionDetail, DecisionLog,
    DecisionRecord, DecisionSummary, DefinedComputation, DefinedKeyedComputation,
    DeletionMergePolicy, DeletionPolicyDescriptor, DeletionPolicyId, DeletionPolicyName,
    DeletionPolicyRegistration, DeletionPolicySelectionBasis, DeletionPolicyVersion,
    DependencyFingerprint, DependencyIndexRebuildProof, DependencyRemapRecord,
    DuplicateAspectMergePolicyRegistration, DuplicateConflictIsolationPolicyRegistration,
    DuplicateConflictPolicyRegistration, DuplicateDeletionPolicyRegistration,
    DuplicateIdentityMatcherRegistration, DuplicateMergeBaseStrategyRegistration,
    DuplicateMergeStrategyRegistration, DuplicateSourceOnlyPolicyRegistration, EvaluationSummary,
    ExistingTargetMergePolicy, FrozenAspectMergePolicyRegistry, FrozenConflictIsolationRegistry,
    FrozenConflictPolicyRegistry, FrozenDeletionPolicyRegistry, FrozenIdentityMatcherRegistry,
    FrozenMergeBaseStrategyRegistry, FrozenMergeStrategyRegistry, FrozenSourceOnlyPolicyRegistry,
    IdentityCorrespondenceBasis, IdentityCorrespondenceRecord, IdentityCorrespondenceStatus,
    IdentityMatchPolicy, IdentityMatcherDescriptor, IdentityMatcherId, IdentityMatcherName,
    IdentityMatcherRegistration, IdentityMatcherSelectionBasis, IdentityMatcherVersion,
    IntegrityMarkers, JournalSegment, LoweredAspectMergeDecisionPlan,
    LoweredAspectMergeDecisionRecord, LoweredConflictIsolationPlan, LoweredConflictIsolationRecord,
    LoweredDeletionPolicyPlan, LoweredIdentityCorrespondencePlan, LoweredMergeBasePlan,
    LoweredMergePlan, MatchingObserverSet, MergeBaseSelectionBasis, MergeBaseSelectionPolicy,
    MergeBaseStrategyDescriptor, MergeBaseStrategyId, MergeBaseStrategyName,
    MergeBaseStrategyRegistration, MergeBaseStrategyVersion, MergeBoundaryWitness,
    MergeBoundaryWitnessKind, MergeDecisionBasis, MergeNodeMap, MergePlanProofReport,
    MergeResultProofReport, MergeStrategyDescriptor, MergeStrategyId, MergeStrategyName,
    MergeStrategyRegistration, MergeStrategySelectionBasis, MergeStrategyVersion,
    MergeSupportRebuildProof, MergeTouchedNodeSet, MergedArtifactRecord, NodeMergeInputState,
    NodeMergePlan, NodeReconciliationDecision, NodeReconciliationShape, ObservationBoundaryOutcome,
    ObservationBoundarySummary, ObservationDeliveryMode, ObservationHandle, ObservationHandleId,
    ObservationListener, ObservationNotice, ObservationPolicy, ObservationReadContext,
    ObservationRegistrySummary, ObservationTrigger, ObservedNodeSet, ObserverId,
    PlannedMergeCandidateSet, PlannedRuntimeMerge, ProofMinimalOverlapBasis, Recipe,
    ReconstructabilityProof, ReconstructabilityRecord, ReplayArtifactProofInput,
    ReplayArtifactProofReport, ReplayMismatchClass, ReplayParityProofReport,
    ReplaySuffixRebuildProof, RequiredDerivedRebuildSet, RuntimeExecutionRequest, RuntimeHistory,
    RuntimeMaterializer, RuntimeMerge, RuntimeObserver, RuntimeProofReport,
    SelectedMergeSemanticsBundle, SignalRuntime, SignalRuntimeBuilder, SignalRuntimeConfig,
    SignalTransaction, SourceNodeAdoptionPlanCore, SourceOnlyMergePolicy,
    SourceOnlyPolicyDescriptor, SourceOnlyPolicyId, SourceOnlyPolicyName,
    SourceOnlyPolicyRegistration, SourceOnlyPolicySelectionBasis, SourceOnlyPolicyVersion,
    StructuralMergeCandidateRecord, StructuralMergeJournalSlice, TemporalCertificationBuilder,
    TemporalCertificationBundle, TemporalCertificationBundleMismatchClass,
    TemporalCertificationBundleParityReport, TemporalCertificationFailure,
    TemporalCertificationFamily, TemporalCertificationRecord, TemporalCertificationSummary,
    TemporalEligibilityFact, TemporalReconstructabilityArtifact, TemporalReplayMismatchClass,
    TemporalReplayParityReport, TemporalStateRebuildProof, TemporalTransactionEvidence,
    TransactionExecutionRequest, TransactionOutcome, TransactionReplayEntry, TransactionResult,
    TransactionTiming, BRANCH_STATE_PROOF_BASIS_VERSION, MERGE_PROOF_SCHEMA_VERSION,
    REQUIRED_TEMPORAL_CERTIFICATION_FAMILIES, TEMPORAL_CERTIFICATION_BUNDLE_PARITY_SCHEMA_VERSION,
    TEMPORAL_CERTIFICATION_BUNDLE_SCHEMA_VERSION, TEMPORAL_REPLAY_PARITY_SCHEMA_VERSION,
};
