#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum GeometryPublicSurface {
    GeometryTargetIdentity,
    SpatialAnchorSelection,
    PrimitiveBinding,
    PrimitiveAnchorBinding,
    PrimitiveRebinding,
    TopologyNeighborhoodReplacement,
    PlanarPredicateAuthority,
    PlanarPrecisionCertification,
    PlanarLocalFrameCertificate,
    ProjectPointToCertifiedPlane2D,
    CertifiedSegmentSegment2D,
    CertifiedPolygonWinding2D,
    CertifiedSignedArea2D,
    CoplanarOverlapContractExtractor,
    PlanarContractBundleValidator,
    PredicateCertificateConsumptionValidator,
    PlanarStructuralIdentity,
    PlanarMotionPosture,
    PlanarTopologyContractCompleteness,
    RetainedPlanarFacts,
    ProjectionConsumedPlanarFacts,
    PlanarRecoveryPosture,
    PlanarDiagnosticBundle,
    PlanarLocalRebuildParity,
    PlanarCleanFailBoundary,
    PlanarBooleanReadinessWorkload,
    ToleranceAndPrecisionCertification,
    HistoricalGeometryInspection,
    BranchLocalGeometryInspection,
    GeometryReplayParity,
    GeometryRecoveryAction,
    GeometryProjectionConsumption,
}

impl GeometryPublicSurface {
    pub const fn all() -> [Self; 32] {
        [
            Self::GeometryTargetIdentity,
            Self::SpatialAnchorSelection,
            Self::PrimitiveBinding,
            Self::PrimitiveAnchorBinding,
            Self::PrimitiveRebinding,
            Self::TopologyNeighborhoodReplacement,
            Self::PlanarPredicateAuthority,
            Self::PlanarPrecisionCertification,
            Self::PlanarLocalFrameCertificate,
            Self::ProjectPointToCertifiedPlane2D,
            Self::CertifiedSegmentSegment2D,
            Self::CertifiedPolygonWinding2D,
            Self::CertifiedSignedArea2D,
            Self::CoplanarOverlapContractExtractor,
            Self::PlanarContractBundleValidator,
            Self::PredicateCertificateConsumptionValidator,
            Self::PlanarStructuralIdentity,
            Self::PlanarMotionPosture,
            Self::PlanarTopologyContractCompleteness,
            Self::RetainedPlanarFacts,
            Self::ProjectionConsumedPlanarFacts,
            Self::PlanarRecoveryPosture,
            Self::PlanarDiagnosticBundle,
            Self::PlanarLocalRebuildParity,
            Self::PlanarCleanFailBoundary,
            Self::PlanarBooleanReadinessWorkload,
            Self::ToleranceAndPrecisionCertification,
            Self::HistoricalGeometryInspection,
            Self::BranchLocalGeometryInspection,
            Self::GeometryReplayParity,
            Self::GeometryRecoveryAction,
            Self::GeometryProjectionConsumption,
        ]
    }

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::GeometryTargetIdentity => "GeometryTargetIdentity",
            Self::SpatialAnchorSelection => "SpatialAnchorSelection",
            Self::PrimitiveBinding => "PrimitiveBinding",
            Self::PrimitiveAnchorBinding => "PrimitiveAnchorBinding",
            Self::PrimitiveRebinding => "PrimitiveRebinding",
            Self::TopologyNeighborhoodReplacement => "TopologyNeighborhoodReplacement",
            Self::PlanarPredicateAuthority => "PlanarPredicateAuthority",
            Self::PlanarPrecisionCertification => "PlanarPrecisionCertification",
            Self::PlanarLocalFrameCertificate => "PlanarLocalFrameCertificate",
            Self::ProjectPointToCertifiedPlane2D => "ProjectPointToCertifiedPlane2D",
            Self::CertifiedSegmentSegment2D => "CertifiedSegmentSegment2D",
            Self::CertifiedPolygonWinding2D => "CertifiedPolygonWinding2D",
            Self::CertifiedSignedArea2D => "CertifiedSignedArea2D",
            Self::CoplanarOverlapContractExtractor => "CoplanarOverlapContractExtractor",
            Self::PlanarContractBundleValidator => "PlanarContractBundleValidator",
            Self::PredicateCertificateConsumptionValidator => {
                "PredicateCertificateConsumptionValidator"
            }
            Self::PlanarStructuralIdentity => "PlanarStructuralIdentity",
            Self::PlanarMotionPosture => "PlanarMotionPosture",
            Self::PlanarTopologyContractCompleteness => "PlanarTopologyContractCompleteness",
            Self::RetainedPlanarFacts => "RetainedPlanarFacts",
            Self::ProjectionConsumedPlanarFacts => "ProjectionConsumedPlanarFacts",
            Self::PlanarRecoveryPosture => "PlanarRecoveryPosture",
            Self::PlanarDiagnosticBundle => "PlanarDiagnosticBundle",
            Self::PlanarLocalRebuildParity => "PlanarLocalRebuildParity",
            Self::PlanarCleanFailBoundary => "PlanarCleanFailBoundary",
            Self::PlanarBooleanReadinessWorkload => "PlanarBooleanReadinessWorkload",
            Self::ToleranceAndPrecisionCertification => "ToleranceAndPrecisionCertification",
            Self::HistoricalGeometryInspection => "HistoricalGeometryInspection",
            Self::BranchLocalGeometryInspection => "BranchLocalGeometryInspection",
            Self::GeometryReplayParity => "GeometryReplayParity",
            Self::GeometryRecoveryAction => "GeometryRecoveryAction",
            Self::GeometryProjectionConsumption => "GeometryProjectionConsumption",
        }
    }
}
