use super::super::ArtifactFamilyInventoryRow;
use super::row::{row, EVIDENCE_ONLY, NONE, OFFLINE_ONLY, TERMINAL_ONLY};
use worth_store_contracts::{
    ArtifactFamilyAccessLane as Lane, ArtifactFamilyAuthorityClass as Authority,
    ArtifactFamilyLifecycleClass as Lifecycle, DurableArtifactFamilyId as Family,
    DurableArtifactMigrationPosture as Migration, DurableArtifactOwningBoundary as Owner,
    DurableArtifactRebuildPosture as Rebuild,
};

pub(super) const REPAIR_ROWS: &[ArtifactFamilyInventoryRow] = &[row(
    Family::RepairRecord,
    Authority::Diagnostic,
    Lifecycle::RecoveryState,
    Lane::MaintenancePath,
    Owner::WorthStoreOperations,
    Rebuild::PartialRebuildOnly,
    Migration::VersionedReadmission,
    EVIDENCE_ONLY,
)];

pub(super) const TRANSFER_ROWS: &[ArtifactFamilyInventoryRow] = &[
    row(
        Family::ExportBundle,
        Authority::Terminal,
        Lifecycle::TransferBoundary,
        Lane::TerminalPath,
        Owner::WorthStoreOperations,
        Rebuild::NoRebuild,
        Migration::OfflineImportOnly,
        TERMINAL_ONLY,
    ),
    row(
        Family::ImportBundle,
        Authority::Authoritative,
        Lifecycle::TransferBoundary,
        Lane::MaintenancePath,
        Owner::WorthStoreOperations,
        Rebuild::NoRebuild,
        Migration::OfflineImportOnly,
        OFFLINE_ONLY,
    ),
    row(
        Family::CapsuleArtifact,
        Authority::Terminal,
        Lifecycle::TransferBoundary,
        Lane::TerminalPath,
        Owner::WorthStoreOperations,
        Rebuild::NoRebuild,
        Migration::OfflineImportOnly,
        TERMINAL_ONLY,
    ),
];

pub(super) const PUBLICATION_ROWS: &[ArtifactFamilyInventoryRow] = &[
    row(
        Family::PublicationWalIntent,
        Authority::Authoritative,
        Lifecycle::CoreState,
        Lane::HotPath,
        Owner::WorthStoreOperations,
        Rebuild::ReplayRebuildable,
        Migration::RollbackCapable,
        NONE,
    ),
    row(
        Family::PublicationWalCanonicalResult,
        Authority::Authoritative,
        Lifecycle::CoreState,
        Lane::HotPath,
        Owner::WorthStoreOperations,
        Rebuild::ReplayRebuildable,
        Migration::RollbackCapable,
        NONE,
    ),
    row(
        Family::PublicationWalPublicationProgress,
        Authority::Authoritative,
        Lifecycle::CoreState,
        Lane::HotPath,
        Owner::WorthStoreOperations,
        Rebuild::ReplayRebuildable,
        Migration::RollbackCapable,
        NONE,
    ),
    row(
        Family::PublicationAuthoritativeCommitAppendUnit,
        Authority::Authoritative,
        Lifecycle::CoreState,
        Lane::HotPath,
        Owner::WorthStoreOperations,
        Rebuild::ReplayRebuildable,
        Migration::RollbackCapable,
        NONE,
    ),
    row(
        Family::PublicationBranchHeadPublication,
        Authority::Authoritative,
        Lifecycle::CoreState,
        Lane::HotPath,
        Owner::WorthStoreOperations,
        Rebuild::ReplayRebuildable,
        Migration::RollbackCapable,
        NONE,
    ),
    row(
        Family::PublicationAcknowledgmentEligibility,
        Authority::Authoritative,
        Lifecycle::OperationalSupport,
        Lane::HotPath,
        Owner::WorthStoreOperations,
        Rebuild::ReplayRebuildable,
        Migration::RollbackCapable,
        NONE,
    ),
    row(
        Family::PublicationSnapshotBasis,
        Authority::Authoritative,
        Lifecycle::CoreState,
        Lane::MaintenancePath,
        Owner::WorthStoreOperations,
        Rebuild::ReplayRebuildable,
        Migration::RollbackCapable,
        NONE,
    ),
    row(
        Family::PublicationSnapshotImage,
        Authority::Authoritative,
        Lifecycle::CoreState,
        Lane::MaintenancePath,
        Owner::WorthStoreOperations,
        Rebuild::ReplayRebuildable,
        Migration::RollbackCapable,
        NONE,
    ),
];
