#[test]
fn intent_admission_dx_boundaries_hold() {
    let t = trybuild::TestCases::new();
    t.pass("tests/ui/intent_admission/golden/intent_admission_common_path_golden_transcript_compiles.rs");
    t.pass("tests/ui/intent_admission/golden/intent_admission_advanced_path_golden_transcript_compiles.rs");
    t.pass("tests/ui/intent_admission/golden/intent_admission_consumer_lane_golden_transcript_compiles.rs");
    t.compile_fail(
        "tests/ui/intent_admission/authoring/runtime_intent_admission_review_constructor_private.rs",
    );
    t.compile_fail(
        "tests/ui/intent_admission/authoring/admitted_runtime_intent_constructor_private.rs",
    );
    t.compile_fail("tests/ui/intent_admission/authoring/raw_request_cannot_mint_admitted_plan.rs");
    t.compile_fail(
        "tests/ui/intent_admission/inventory/family/family_inventory_row_constructor_private.rs",
    );
    t.compile_fail(
        "tests/ui/intent_admission/inventory/family/family_inventory_constructor_private.rs",
    );
    t.compile_fail(
        "tests/ui/intent_admission/inventory/support/support_row_constructor_private.rs",
    );
    t.compile_fail(
        "tests/ui/intent_admission/inventory/support/support_matrix_constructor_private.rs",
    );
    t.compile_fail(
        "tests/ui/intent_admission/inventory/coverage/coverage_row_constructor_private.rs",
    );
    t.compile_fail(
        "tests/ui/intent_admission/inventory/coverage/coverage_inventory_constructor_private.rs",
    );
    t.compile_fail(
        "tests/ui/intent_admission/execution/authoritative/authoritative_plan_constructor_private.rs",
    );
    t.compile_fail("tests/ui/intent_admission/execution/effect/effect_plan_constructor_private.rs");
    t.compile_fail(
        "tests/ui/intent_admission/execution/authoritative/authoritative_handoff_constructor_private.rs",
    );
    t.compile_fail(
        "tests/ui/intent_admission/execution/effect/effect_handoff_constructor_private.rs",
    );
    t.compile_fail(
        "tests/ui/intent_admission/execution/authoritative/authoritative_execution_binding_constructor_private.rs",
    );
    t.compile_fail(
        "tests/ui/intent_admission/execution/effect/effect_execution_binding_constructor_private.rs",
    );
    t.compile_fail("tests/ui/intent_admission/outcomes/advisory_decision_constructor_private.rs");
    t.compile_fail("tests/ui/intent_admission/outcomes/violation_decision_constructor_private.rs");
    t.compile_fail("tests/ui/intent_admission/outcomes/advisory_stop_constructor_private.rs");
    t.compile_fail("tests/ui/intent_admission/outcomes/violation_stop_constructor_private.rs");
    t.compile_fail("tests/ui/intent_admission/trace/decision_trace_row_constructor_private.rs");
    t.compile_fail(
        "tests/ui/intent_admission/trace/decision_trace_envelope_constructor_private.rs",
    );
    t.compile_fail(
        "tests/ui/intent_admission/consumer/intent_consumer_inspection_constructor_private.rs",
    );
    t.compile_fail(
        "tests/ui/intent_admission/certification/intent_admission_certification_bundle_constructor_private.rs",
    );
    t.compile_fail(
        "tests/ui/intent_admission/certification/intent_admission_public_boundary_audit_constructor_private.rs",
    );
    t.compile_fail(
        "tests/ui/intent_admission/certification/intent_admission_proof_shape_audit_constructor_private.rs",
    );
    t.compile_fail(
        "tests/ui/intent_admission/certification/intent_admission_topology_audit_constructor_private.rs",
    );
    t.compile_fail(
        "tests/ui/intent_admission/certification/intent_admission_certification_output_constructor_private.rs",
    );
    t.compile_fail(
        "tests/ui/intent_admission/certification/intent_admission_oracle_report_constructor_private.rs",
    );
    t.compile_fail(
        "tests/ui/intent_admission/certification/intent_admission_legacy_parity_report_constructor_private.rs",
    );
    t.compile_fail(
        "tests/ui/intent_admission/certification/intent_admission_support_traceability_report_constructor_private.rs",
    );
    t.compile_fail(
        "tests/ui/intent_admission/certification/intent_admission_slope_report_constructor_private.rs",
    );
    t.compile_fail(
        "tests/ui/intent_admission/certification/intent_admission_representative_output_report_constructor_private.rs",
    );
    t.compile_fail(
        "tests/ui/intent_admission/certification/intent_admission_representative_family_report_constructor_private.rs",
    );
    t.compile_fail(
        "tests/ui/intent_admission/certification/intent_admission_doc_example_report_constructor_private.rs",
    );
    t.compile_fail(
        "tests/ui/intent_admission/certification/intent_admission_seeded_certification_report_constructor_private.rs",
    );
}
