#[test]
fn projection_consumption_compile_fail_boundaries_hold() {
    let t = trybuild::TestCases::new();
    t.pass("tests/ui/projection_consumption/golden/projection_consumption_common_read_golden_path_compiles.rs");
    t.pass("tests/ui/projection_consumption/golden/projection_consumption_common_write_golden_path_compiles.rs");
    t.pass(
        "tests/ui/projection_consumption/golden/projection_consumption_common_query_context_golden_path_compiles.rs",
    );
    t.pass("tests/ui/projection_consumption/golden/projection_consumption_advanced_path_golden_transcript_compiles.rs");
    t.compile_fail("tests/ui/projection_consumption/construction/projection_consumption_authoring_surface_constructor_private.rs");
    t.compile_fail(
        "tests/ui/projection_consumption/construction/projection_consumption_contract_constructor_private.rs",
    );
    t.compile_fail(
        "tests/ui/projection_consumption/boundaries/projection_consumption_contract_has_no_generic_extract.rs",
    );
    t.compile_fail(
        "tests/ui/projection_consumption/construction/projection_consumption_certification_bundle_constructor_private.rs",
    );
    t.compile_fail(
        "tests/ui/projection_consumption/construction/projection_consumption_declaration_constructor_private.rs",
    );
    t.compile_fail("tests/ui/projection_consumption/construction/projection_consumption_eligibility_artifacts_constructor_private.rs");
    t.compile_fail(
        "tests/ui/projection_consumption/construction/projection_consumption_envelope_constructor_private.rs",
    );
    t.compile_fail(
        "tests/ui/projection_consumption/construction/projection_consumption_fact_set_constructor_private.rs",
    );
    t.compile_fail("tests/ui/projection_consumption/boundaries/projection_consumption_non_admitted_cannot_bind_contract.rs");
    t.compile_fail(
        "tests/ui/projection_consumption/construction/projection_consumption_receipt_constructor_private.rs",
    );
    t.compile_fail(
        "tests/ui/projection_consumption/boundaries/projection_consumption_raw_source_has_no_consumed_fact_accessors.rs",
    );
    t.compile_fail("tests/ui/projection_consumption/construction/projection_consumption_support_artifacts_constructor_private.rs");
}
