const SOURCE_FILES: &[&str] = &[
    "_docs/worth-store/physical-reconstruction-c7-durable-publication-join.md",
    "_docs/worth-store/physical-reconstruction-c7-phase-6-checkpoint-plan.md",
    "_docs/worth-store/physical-reconstruction-c7-public-api.csv",
    "_docs/worth-store/physical-reconstruction-c7-removal-ledger.csv",
    "_docs/worth-store/physical-wal-append.md",
    "workspaces/worth-store/crates/worth-store/src/physical_runtime/durability/checkpoint/capture/publication_cutover.rs",
    "workspaces/worth-store/crates/worth-store/src/physical_runtime/durability/checkpoint/outcome.rs",
    "workspaces/worth-store/crates/worth-store/src/physical_runtime/durability/checkpoint/publication.rs",
    "workspaces/worth-store/crates/worth-store/src/physical_runtime/durability/wal/checkpoint_cutover.rs",
    "workspaces/worth-store/crates/worth-store/src/physical_runtime/durability/wal/observation.rs",
    "workspaces/worth-store/crates/worth-store/src/physical_runtime/durability/wal/runtime_owner.rs",
    "workspaces/worth-store/crates/worth-store/src/physical_runtime/instance/construction/record_serving.rs",
    "workspaces/worth-store/crates/worth-store/src/physical_runtime/instance/executor.rs",
    "workspaces/worth-store/crates/worth-store/src/physical_runtime/instance/executor/wal_reclamation.rs",
    "workspaces/worth-store/crates/worth-store/src/physical_runtime/instance/scheduler_admission/reclamation.rs",
    "workspaces/worth-store/crates/worth-store/src/physical_runtime/record_serving/work_semantics/durability/wal_reclamation_basis.rs",
    "workspaces/worth-store/crates/worth-store/src/physical_runtime/record_serving/work_semantics/mod.rs",
    "workspaces/worth-store/crates/worth-store/src/physical_runtime/work/declaration/effect_contract.rs",
    "workspaces/worth-store/crates/worth-store/src/physical_runtime/work/declaration/resource_demand.rs",
    "workspaces/worth-store/crates/worth-store/src/physical_runtime/work/declaration/wal_reclamation_scope.rs",
    "workspaces/worth-store/crates/worth-store/src/physical_runtime/work/execution/command/reclamation.rs",
    "workspaces/worth-store/crates/worth-store/src/physical_runtime/work/execution/outcome/wal_reclamation.rs",
    "workspaces/worth-store/crates/worth-store/src/physical_runtime/work/execution/settlement/classification/wal_reclamation.rs",
    "workspaces/worth-store/crates/worth-store/src/physical_runtime/work/profile/capability.rs",
    "workspaces/worth-store/crates/worth-store/src/physical_runtime/work/profile/identity.rs",
    "workspaces/worth-store/crates/worth-store/src/physical_runtime/work/recovery/locator.rs",
    "workspaces/worth-store/crates/worth-store/src/physical_runtime/work/recovery/locator/codec.rs",
    "workspaces/worth-store/crates/worth-store/src/physical_runtime/work/recovery/locator/codec/tests.rs",
    "workspaces/worth-store/crates/worth-store/src/physical_runtime/work/request.rs",
    "workspaces/worth-store/crates/worth-store/src/physical_runtime/work/scheduler_demand.rs",
    "workspaces/worth-store/crates/worth-store/tests/physical_record_journeys/durability_admission.rs",
    "workspaces/worth-store/crates/worth-store/tests/physical_record_journeys/durability_admission/checkpoint_retained_wal_tail.rs",
    "workspaces/worth-store/crates/worth-store/tests/physical_record_journeys/durability_admission/checkpoint_wal_reclamation.rs",
    "workspaces/worth-store/tools/store-test-runner/src/durable_publication_boundary_gate/closure_ledger/phase_six.rs",
    "workspaces/worth-store/tools/store-test-runner/src/durable_publication_boundary_gate/closure_ledger/source_identity.rs",
    "workspaces/worth-store/tools/store-test-runner/src/durable_publication_boundary_gate/closure_ledger/source_identity/phase_six_reclamation.rs",
    "workspaces/worth-store/tools/store-test-runner/src/durable_publication_boundary_gate/contract/checkpoint_retained_wal_tail.rs",
    "workspaces/worth-store/tools/store-test-runner/src/durable_publication_boundary_gate/contract/mod.rs",
    "workspaces/worth-store/tools/store-test-runner/src/durable_publication_boundary_gate/contract/wal_reclamation.rs",
    "workspaces/worth-store/tools/store-test-runner/src/durable_publication_boundary_gate/inventory/mod.rs",
    "workspaces/worth-store/tools/store-test-runner/src/durable_publication_boundary_gate/public_api/facade_reachability/phase_six.rs",
    "workspaces/worth-store/tools/store-test-runner/src/durable_publication_boundary_gate/public_api/locked_surfaces.rs",
    "workspaces/worth-store/tools/store-test-runner/src/physical_work_evidence/labels.rs",
];

const SOURCE_TREES: &[&str] = &[
    "workspaces/worth-store/crates/worth-store/src/physical_runtime/durability/wal/reclamation",
    "workspaces/worth-store/crates/worth-store/src/physical_runtime/durability/wal/inventory",
    "workspaces/worth-store/crates/worth-store/tests/physical_record_journeys/durability_admission/independent_wal_oracle",
];

pub(super) fn source_identity() -> Result<String, String> {
    super::source_identity("P6 reclamation", SOURCE_FILES, SOURCE_TREES, &[])
}
