use crate::runtime::{WorthUiProjectionFamily, WorthUiRuntimeFactFamily};

use super::{
    inventory::{row, row_with_preservation, WorthUiSemanticSliceDescriptor},
    WorthUiSemanticMeaningClass, WorthUiSemanticSliceConsumers, WorthUiSemanticSliceFactMapping,
    WorthUiSemanticSliceId, WorthUiSemanticSliceOwner,
};

const CONTENT_SLOT_ASSIGNMENT_FACTS: &[WorthUiRuntimeFactFamily] = &[
    WorthUiRuntimeFactFamily::PageContentSlot,
    WorthUiRuntimeFactFamily::ContentMount,
];
const DROPDOWN_CONSUMERS: &[WorthUiProjectionFamily] = &[WorthUiProjectionFamily::Dropdown];
const HEADER_THEME_CONSUMERS: &[WorthUiProjectionFamily] = &[
    WorthUiProjectionFamily::HeaderTheme,
    WorthUiProjectionFamily::HeaderFrame,
];
const HEADER_APPEARANCE_CONSUMERS: &[WorthUiProjectionFamily] = &[
    WorthUiProjectionFamily::HeaderAppearance,
    WorthUiProjectionFamily::HeaderFrame,
    WorthUiProjectionFamily::Dropdown,
];
const APPEARANCE_RECIPE_CONSUMERS: &[WorthUiProjectionFamily] = &[];
const HEADER_MENU_CONSUMERS: &[WorthUiProjectionFamily] = &[
    WorthUiProjectionFamily::HeaderMenu,
    WorthUiProjectionFamily::HeaderFrame,
    WorthUiProjectionFamily::Dropdown,
];
const PAGE_HOST_CONSUMERS: &[WorthUiProjectionFamily] = &[WorthUiProjectionFamily::PageHost];
const PRIMITIVE_PROOF_CONSUMERS: &[WorthUiProjectionFamily] =
    &[WorthUiProjectionFamily::PrimitiveProof];
const QUERY_PROJECTION_CONSUMERS: &[WorthUiProjectionFamily] =
    &[WorthUiProjectionFamily::QueryProjectionConsumption];
const LIVE_VIEW_EXPRESSION_CONSUMERS: &[WorthUiProjectionFamily] =
    &[WorthUiProjectionFamily::LiveViewExpression];
const NO_PROJECTION_CONSUMERS: &[WorthUiProjectionFamily] = &[];
const VIEWPORT_BOUNDARY_FACTS: &[WorthUiRuntimeFactFamily] = &[
    WorthUiRuntimeFactFamily::ViewportBoundary,
    WorthUiRuntimeFactFamily::ClipBoundary,
    WorthUiRuntimeFactFamily::ScrollRestoration,
    WorthUiRuntimeFactFamily::ViewportEventParticipation,
];

macro_rules! query_exact_preservation_row {
    ($slice:ident, $fact:ident) => {
        row_with_preservation(
            WorthUiSemanticSliceId::$slice,
            WorthUiSemanticSliceOwner::QueryAuthority,
            WorthUiSemanticMeaningClass::ProductMeaning,
            WorthUiSemanticSliceFactMapping::Exact(WorthUiRuntimeFactFamily::$fact),
            WorthUiSemanticSliceConsumers::new(QUERY_PROJECTION_CONSUMERS),
            true,
        )
    };
}

macro_rules! query_gap_preservation_row {
    ($slice:ident) => {
        row_with_preservation(
            WorthUiSemanticSliceId::$slice,
            WorthUiSemanticSliceOwner::QueryAuthority,
            WorthUiSemanticMeaningClass::ProductMeaning,
            WorthUiSemanticSliceFactMapping::Gap,
            WorthUiSemanticSliceConsumers::new(QUERY_PROJECTION_CONSUMERS),
            true,
        )
    };
}

pub(super) static SEMANTIC_SLICE_INVENTORY: &[WorthUiSemanticSliceDescriptor] = &[
    row(
        WorthUiSemanticSliceId::ThemeTokenValue,
        WorthUiSemanticSliceOwner::CapabilityAuthority,
        WorthUiSemanticMeaningClass::ProductMeaning,
        WorthUiSemanticSliceFactMapping::Exact(WorthUiRuntimeFactFamily::ThemeToken),
        WorthUiSemanticSliceConsumers::new(HEADER_THEME_CONSUMERS),
    ),
    row(
        WorthUiSemanticSliceId::AppearanceField,
        WorthUiSemanticSliceOwner::CapabilityAuthority,
        WorthUiSemanticMeaningClass::ProductMeaning,
        WorthUiSemanticSliceFactMapping::Exact(WorthUiRuntimeFactFamily::Appearance),
        WorthUiSemanticSliceConsumers::new(HEADER_APPEARANCE_CONSUMERS),
    ),
    row(
        WorthUiSemanticSliceId::AppearanceRecipe,
        WorthUiSemanticSliceOwner::AuthoredSource,
        WorthUiSemanticMeaningClass::ProductMeaning,
        WorthUiSemanticSliceFactMapping::Exact(WorthUiRuntimeFactFamily::AppearanceRecipe),
        WorthUiSemanticSliceConsumers::new(APPEARANCE_RECIPE_CONSUMERS),
    ),
    row(
        WorthUiSemanticSliceId::DensityField,
        WorthUiSemanticSliceOwner::CapabilityAuthority,
        WorthUiSemanticMeaningClass::ProductMeaning,
        WorthUiSemanticSliceFactMapping::Exact(WorthUiRuntimeFactFamily::DensityToken),
        WorthUiSemanticSliceConsumers::new(HEADER_APPEARANCE_CONSUMERS),
    ),
    row(
        WorthUiSemanticSliceId::CommandDeclaration,
        WorthUiSemanticSliceOwner::CapabilityAuthority,
        WorthUiSemanticMeaningClass::ProductMeaning,
        WorthUiSemanticSliceFactMapping::Exact(WorthUiRuntimeFactFamily::Command),
        WorthUiSemanticSliceConsumers::new(HEADER_MENU_CONSUMERS),
    ),
    row(
        WorthUiSemanticSliceId::CommandProjectionSelectionMode,
        WorthUiSemanticSliceOwner::CapabilityAuthority,
        WorthUiSemanticMeaningClass::ProductMeaning,
        WorthUiSemanticSliceFactMapping::Exact(WorthUiRuntimeFactFamily::InteractionPolicy),
        WorthUiSemanticSliceConsumers::new(HEADER_MENU_CONSUMERS),
    ),
    row(
        WorthUiSemanticSliceId::DropdownSelectedState,
        WorthUiSemanticSliceOwner::RuntimeInteractionState,
        WorthUiSemanticMeaningClass::ProductMeaning,
        WorthUiSemanticSliceFactMapping::Exact(WorthUiRuntimeFactFamily::DropdownSelectionState),
        WorthUiSemanticSliceConsumers::new(DROPDOWN_CONSUMERS),
    ),
    row(
        WorthUiSemanticSliceId::LayoutTopology,
        WorthUiSemanticSliceOwner::AuthoredSource,
        WorthUiSemanticMeaningClass::ProductMeaning,
        WorthUiSemanticSliceFactMapping::Exact(WorthUiRuntimeFactFamily::LayoutTopology),
        WorthUiSemanticSliceConsumers::new(PAGE_HOST_CONSUMERS),
    ),
    row(
        WorthUiSemanticSliceId::LayoutGapRule,
        WorthUiSemanticSliceOwner::AuthoredSource,
        WorthUiSemanticMeaningClass::ProductMeaning,
        WorthUiSemanticSliceFactMapping::Exact(WorthUiRuntimeFactFamily::LayoutGap),
        WorthUiSemanticSliceConsumers::new(PAGE_HOST_CONSUMERS),
    ),
    row(
        WorthUiSemanticSliceId::LayoutPaddingRule,
        WorthUiSemanticSliceOwner::AuthoredSource,
        WorthUiSemanticMeaningClass::ProductMeaning,
        WorthUiSemanticSliceFactMapping::Exact(WorthUiRuntimeFactFamily::LayoutPadding),
        WorthUiSemanticSliceConsumers::new(PAGE_HOST_CONSUMERS),
    ),
    row(
        WorthUiSemanticSliceId::ShellSlotAssignment,
        WorthUiSemanticSliceOwner::AuthoredSource,
        WorthUiSemanticMeaningClass::ProductMeaning,
        WorthUiSemanticSliceFactMapping::Exact(WorthUiRuntimeFactFamily::ShellSlotAssignment),
        WorthUiSemanticSliceConsumers::new(NO_PROJECTION_CONSUMERS),
    ),
    row(
        WorthUiSemanticSliceId::ContentSlotAssignment,
        WorthUiSemanticSliceOwner::AuthoredSource,
        WorthUiSemanticMeaningClass::ProductMeaning,
        WorthUiSemanticSliceFactMapping::Composite(CONTENT_SLOT_ASSIGNMENT_FACTS),
        WorthUiSemanticSliceConsumers::new(PAGE_HOST_CONSUMERS),
    ),
    row(
        WorthUiSemanticSliceId::PageTemplateDeclaration,
        WorthUiSemanticSliceOwner::AuthoredSource,
        WorthUiSemanticMeaningClass::ProductMeaning,
        WorthUiSemanticSliceFactMapping::Exact(WorthUiRuntimeFactFamily::PageTemplate),
        WorthUiSemanticSliceConsumers::new(PAGE_HOST_CONSUMERS),
    ),
    row(
        WorthUiSemanticSliceId::PageInstanceDeclaration,
        WorthUiSemanticSliceOwner::AuthoredSource,
        WorthUiSemanticMeaningClass::ProductMeaning,
        WorthUiSemanticSliceFactMapping::Exact(WorthUiRuntimeFactFamily::PageInstance),
        WorthUiSemanticSliceConsumers::new(PAGE_HOST_CONSUMERS),
    ),
    row(
        WorthUiSemanticSliceId::PageTemplateBinding,
        WorthUiSemanticSliceOwner::AuthoredSource,
        WorthUiSemanticMeaningClass::ProductMeaning,
        WorthUiSemanticSliceFactMapping::Exact(
            WorthUiRuntimeFactFamily::PageInstanceTemplateBinding,
        ),
        WorthUiSemanticSliceConsumers::new(PAGE_HOST_CONSUMERS),
    ),
    row(
        WorthUiSemanticSliceId::SurfaceMountTarget,
        WorthUiSemanticSliceOwner::AuthoredSource,
        WorthUiSemanticMeaningClass::ProductMeaning,
        WorthUiSemanticSliceFactMapping::Exact(WorthUiRuntimeFactFamily::SurfaceMount),
        WorthUiSemanticSliceConsumers::new(PAGE_HOST_CONSUMERS),
    ),
    row(
        WorthUiSemanticSliceId::RegisteredComponentCapability,
        WorthUiSemanticSliceOwner::CapabilityAuthority,
        WorthUiSemanticMeaningClass::ProductMeaning,
        WorthUiSemanticSliceFactMapping::Exact(WorthUiRuntimeFactFamily::Component),
        WorthUiSemanticSliceConsumers::new(HEADER_MENU_CONSUMERS),
    ),
    row(
        WorthUiSemanticSliceId::AuthoredMountComponentSelection,
        WorthUiSemanticSliceOwner::AuthoredSource,
        WorthUiSemanticMeaningClass::ProductMeaning,
        WorthUiSemanticSliceFactMapping::Exact(
            WorthUiRuntimeFactFamily::AuthoredMountComponentSelection,
        ),
        WorthUiSemanticSliceConsumers::new(PAGE_HOST_CONSUMERS),
    ),
    row(
        WorthUiSemanticSliceId::AuthoredSurfaceInstanceProps,
        WorthUiSemanticSliceOwner::AuthoredSource,
        WorthUiSemanticMeaningClass::ProductMeaning,
        WorthUiSemanticSliceFactMapping::Exact(WorthUiRuntimeFactFamily::AuthoredSurfaceProps),
        WorthUiSemanticSliceConsumers::new(PAGE_HOST_CONSUMERS),
    ),
    row(
        WorthUiSemanticSliceId::PrimitiveConstruction,
        WorthUiSemanticSliceOwner::CompiledPlatformAuthority,
        WorthUiSemanticMeaningClass::ProductMeaning,
        WorthUiSemanticSliceFactMapping::Exact(WorthUiRuntimeFactFamily::PrimitiveConstruction),
        WorthUiSemanticSliceConsumers::new(PRIMITIVE_PROOF_CONSUMERS),
    ),
    row(
        WorthUiSemanticSliceId::PrimitiveContent,
        WorthUiSemanticSliceOwner::AuthoredSource,
        WorthUiSemanticMeaningClass::ProductMeaning,
        WorthUiSemanticSliceFactMapping::Exact(WorthUiRuntimeFactFamily::PrimitiveContent),
        WorthUiSemanticSliceConsumers::new(PRIMITIVE_PROOF_CONSUMERS),
    ),
    row(
        WorthUiSemanticSliceId::PrimitiveContainer,
        WorthUiSemanticSliceOwner::AuthoredSource,
        WorthUiSemanticMeaningClass::ProductMeaning,
        WorthUiSemanticSliceFactMapping::Exact(WorthUiRuntimeFactFamily::PrimitiveContainer),
        WorthUiSemanticSliceConsumers::new(PRIMITIVE_PROOF_CONSUMERS),
    ),
    row(
        WorthUiSemanticSliceId::PrimitiveMeasurement,
        WorthUiSemanticSliceOwner::AuthoredSource,
        WorthUiSemanticMeaningClass::ProductMeaning,
        WorthUiSemanticSliceFactMapping::Exact(WorthUiRuntimeFactFamily::PrimitiveMeasurement),
        WorthUiSemanticSliceConsumers::new(PRIMITIVE_PROOF_CONSUMERS),
    ),
    row(
        WorthUiSemanticSliceId::PrimitiveAppearance,
        WorthUiSemanticSliceOwner::AuthoredSource,
        WorthUiSemanticMeaningClass::ProductMeaning,
        WorthUiSemanticSliceFactMapping::Exact(WorthUiRuntimeFactFamily::PrimitiveAppearance),
        WorthUiSemanticSliceConsumers::new(PRIMITIVE_PROOF_CONSUMERS),
    ),
    row(
        WorthUiSemanticSliceId::PrimitiveAppearanceState,
        WorthUiSemanticSliceOwner::AuthoredSource,
        WorthUiSemanticMeaningClass::ProductMeaning,
        WorthUiSemanticSliceFactMapping::Exact(WorthUiRuntimeFactFamily::PrimitiveAppearanceState),
        WorthUiSemanticSliceConsumers::new(PRIMITIVE_PROOF_CONSUMERS),
    ),
    row(
        WorthUiSemanticSliceId::PrimitiveInteraction,
        WorthUiSemanticSliceOwner::AuthoredSource,
        WorthUiSemanticMeaningClass::ProductMeaning,
        WorthUiSemanticSliceFactMapping::Exact(WorthUiRuntimeFactFamily::PrimitiveInteraction),
        WorthUiSemanticSliceConsumers::new(PRIMITIVE_PROOF_CONSUMERS),
    ),
    row(
        WorthUiSemanticSliceId::PrimitiveMotion,
        WorthUiSemanticSliceOwner::AuthoredSource,
        WorthUiSemanticMeaningClass::ProductMeaning,
        WorthUiSemanticSliceFactMapping::Exact(WorthUiRuntimeFactFamily::PrimitiveMotion),
        WorthUiSemanticSliceConsumers::new(PRIMITIVE_PROOF_CONSUMERS),
    ),
    row(
        WorthUiSemanticSliceId::PrimitiveFlowLayout,
        WorthUiSemanticSliceOwner::AuthoredSource,
        WorthUiSemanticMeaningClass::ProductMeaning,
        WorthUiSemanticSliceFactMapping::Exact(WorthUiRuntimeFactFamily::PrimitiveFlowLayout),
        WorthUiSemanticSliceConsumers::new(PRIMITIVE_PROOF_CONSUMERS),
    ),
    row(
        WorthUiSemanticSliceId::PrimitiveEventGeometry,
        WorthUiSemanticSliceOwner::AuthoredSource,
        WorthUiSemanticMeaningClass::ProductMeaning,
        WorthUiSemanticSliceFactMapping::Exact(WorthUiRuntimeFactFamily::PrimitiveEventGeometry),
        WorthUiSemanticSliceConsumers::new(PRIMITIVE_PROOF_CONSUMERS),
    ),
    row(
        WorthUiSemanticSliceId::ViewportBoundary,
        WorthUiSemanticSliceOwner::AuthoredSource,
        WorthUiSemanticMeaningClass::ProductMeaning,
        WorthUiSemanticSliceFactMapping::Composite(VIEWPORT_BOUNDARY_FACTS),
        WorthUiSemanticSliceConsumers::new(NO_PROJECTION_CONSUMERS),
    ),
    row(
        WorthUiSemanticSliceId::UserIntentTargetBinding,
        WorthUiSemanticSliceOwner::CompiledPlatformAuthority,
        WorthUiSemanticMeaningClass::ProductMeaning,
        WorthUiSemanticSliceFactMapping::Exact(WorthUiRuntimeFactFamily::UserIntentTargetBinding),
        WorthUiSemanticSliceConsumers::new(PRIMITIVE_PROOF_CONSUMERS),
    ),
    row(
        WorthUiSemanticSliceId::ActionPosture,
        WorthUiSemanticSliceOwner::CapabilityAuthority,
        WorthUiSemanticMeaningClass::ProductMeaning,
        WorthUiSemanticSliceFactMapping::Exact(WorthUiRuntimeFactFamily::ActionPosture),
        WorthUiSemanticSliceConsumers::new(NO_PROJECTION_CONSUMERS),
    ),
    row(
        WorthUiSemanticSliceId::DurableStateFamily,
        WorthUiSemanticSliceOwner::DurableRuntimeState,
        WorthUiSemanticMeaningClass::ProductMeaning,
        WorthUiSemanticSliceFactMapping::Exact(WorthUiRuntimeFactFamily::DurableStateFamily),
        WorthUiSemanticSliceConsumers::new(NO_PROJECTION_CONSUMERS),
    ),
    row(
        WorthUiSemanticSliceId::AuthoredQueryBindingShape,
        WorthUiSemanticSliceOwner::AuthoredSource,
        WorthUiSemanticMeaningClass::ProductMeaning,
        WorthUiSemanticSliceFactMapping::Exact(WorthUiRuntimeFactFamily::AuthoredQueryBindingShape),
        WorthUiSemanticSliceConsumers::new(QUERY_PROJECTION_CONSUMERS),
    ),
    query_exact_preservation_row!(QueryBindingIdentity, QueryBinding),
    query_exact_preservation_row!(QueryLiveViewBinding, LiveViewBinding),
    query_gap_preservation_row!(QueryBindingPreservationPosture),
    query_gap_preservation_row!(QueryBindingRebindPosture),
    query_gap_preservation_row!(QueryBindingRetirementPosture),
    query_exact_preservation_row!(QueryResultPosture, QueryResultPosture),
    query_exact_preservation_row!(QueryProjectionFact, QueryProjectionFact),
    query_exact_preservation_row!(QueryStateSnapshot, QueryStateSnapshot),
    query_exact_preservation_row!(QueryEffectPosture, QueryEffectPosture),
    query_exact_preservation_row!(QueryRecoveryPosture, QueryRecoveryPosture),
    query_exact_preservation_row!(QueryInspectionTarget, QueryInspectionTarget),
    row(
        WorthUiSemanticSliceId::ExpressionDeclaration,
        WorthUiSemanticSliceOwner::AuthoredSource,
        WorthUiSemanticMeaningClass::ProductMeaning,
        WorthUiSemanticSliceFactMapping::Exact(
            WorthUiRuntimeFactFamily::LiveViewExpressionDeclaration,
        ),
        WorthUiSemanticSliceConsumers::new(LIVE_VIEW_EXPRESSION_CONSUMERS),
    ),
    row(
        WorthUiSemanticSliceId::ExpressionProjection,
        WorthUiSemanticSliceOwner::RuntimeInteractionState,
        WorthUiSemanticMeaningClass::ProductMeaning,
        WorthUiSemanticSliceFactMapping::Exact(
            WorthUiRuntimeFactFamily::LiveViewExpressionProjection,
        ),
        WorthUiSemanticSliceConsumers::new(LIVE_VIEW_EXPRESSION_CONSUMERS),
    ),
    row(
        WorthUiSemanticSliceId::ExpressionOutput,
        WorthUiSemanticSliceOwner::RuntimeInteractionState,
        WorthUiSemanticMeaningClass::ProductMeaning,
        WorthUiSemanticSliceFactMapping::Exact(WorthUiRuntimeFactFamily::LiveViewExpressionOutput),
        WorthUiSemanticSliceConsumers::new(LIVE_VIEW_EXPRESSION_CONSUMERS),
    ),
    row(
        WorthUiSemanticSliceId::HostMeasurementObservation,
        WorthUiSemanticSliceOwner::RuntimeInteractionState,
        WorthUiSemanticMeaningClass::ProductMeaning,
        WorthUiSemanticSliceFactMapping::Exact(
            WorthUiRuntimeFactFamily::HostMeasurementObservation,
        ),
        WorthUiSemanticSliceConsumers::new(NO_PROJECTION_CONSUMERS),
    ),
    row_with_preservation(
        WorthUiSemanticSliceId::VirtualizedDataFrameTarget,
        WorthUiSemanticSliceOwner::QueryAuthority,
        WorthUiSemanticMeaningClass::ProductMeaning,
        WorthUiSemanticSliceFactMapping::Exact(WorthUiRuntimeFactFamily::VirtualizedDataFrame),
        WorthUiSemanticSliceConsumers::new(QUERY_PROJECTION_CONSUMERS),
        true,
    ),
    row(
        WorthUiSemanticSliceId::NewRustComponentImplementation,
        WorthUiSemanticSliceOwner::CompiledPlatformAuthority,
        WorthUiSemanticMeaningClass::PlatformMeaning,
        WorthUiSemanticSliceFactMapping::Gap,
        WorthUiSemanticSliceConsumers::new(NO_PROJECTION_CONSUMERS),
    ),
    row(
        WorthUiSemanticSliceId::NewCapabilityFamilyDefinition,
        WorthUiSemanticSliceOwner::CompiledPlatformAuthority,
        WorthUiSemanticMeaningClass::PlatformMeaning,
        WorthUiSemanticSliceFactMapping::Gap,
        WorthUiSemanticSliceConsumers::new(NO_PROJECTION_CONSUMERS),
    ),
    row(
        WorthUiSemanticSliceId::RuntimeSubsystemBehavior,
        WorthUiSemanticSliceOwner::CompiledPlatformAuthority,
        WorthUiSemanticMeaningClass::PlatformMeaning,
        WorthUiSemanticSliceFactMapping::Gap,
        WorthUiSemanticSliceConsumers::new(NO_PROJECTION_CONSUMERS),
    ),
];
