use crate::data::resource::ResourceBoundaryKind;
use crate::facade::*;
use crate::tests::async_node_nightmare_support::milestone_d_combined_workload;
use crate::tests::async_node_restore_lineage_nightmare_support::milestone_d_restore_lineage_nightmare_workload;

fn explanation_without_ephemeral_execution_ids(
    summary: Option<&ExplanationSummary>,
) -> Option<ExplanationSummary> {
    summary.cloned().map(|mut summary| {
        summary.execution_record_id = None;
        summary.semantic_segment_id = None;
        summary
    })
}

#[test]
fn async_node_nightmare_workload_preserves_combined_capability_truth_across_restore() {
    let workload = milestone_d_combined_workload();

    assert_eq!(
        workload
            .attachment_equivalence_before_restore
            .performance()
            .boundary(),
        ResourceBoundaryKind::AsyncNodeCapabilityEquivalence
    );
    assert_eq!(
        workload
            .attachment_equivalence_after_restore
            .performance()
            .boundary(),
        ResourceBoundaryKind::AsyncNodeCapabilityEquivalence
    );
    assert_eq!(
        workload
            .attachment_equivalence_before_restore
            .lifecycle_digest(),
        workload
            .attachment_equivalence_after_restore
            .lifecycle_digest()
    );
    assert_eq!(
        workload
            .attachment_equivalence_before_restore
            .output_continuity_digest(),
        workload
            .attachment_equivalence_after_restore
            .output_continuity_digest()
    );
    assert_eq!(
        workload
            .attachment_equivalence_before_restore
            .observation_digest(),
        workload
            .attachment_equivalence_after_restore
            .observation_digest()
    );
    assert_eq!(
        workload
            .attachment_equivalence_before_restore
            .explanation_availability(),
        workload
            .attachment_equivalence_after_restore
            .explanation_availability()
    );
    assert!(
        workload
            .attachment_equivalence_after_restore
            .explanation_digest()
            .is_some(),
        "restored capability equivalence should still carry explanation lineage"
    );
    assert!(workload
        .attachment_equivalence_after_restore
        .historical_parity_report()
        .branch_restore_report()
        .is_some());

    assert_eq!(
        workload.gate_state_before_restore.gate_digest(),
        workload.gate_state_after_restore.gate_digest()
    );
    assert_eq!(
        workload
            .gate_state_before_restore
            .active_request_handle()
            .map(|handle| (handle.request_id(), handle.generation())),
        workload
            .gate_state_after_restore
            .active_request_handle()
            .map(|handle| (handle.request_id(), handle.generation()))
    );
    assert_eq!(
        workload
            .gate_historical_before_restore
            .replay_reconstruction()
            .replay_digest(),
        workload
            .gate_historical_after_restore
            .replay_reconstruction()
            .replay_digest()
    );
    assert_eq!(
        workload
            .gate_historical_before_restore
            .observation_batch_report()
            .map(|report| report.performance()),
        workload
            .gate_historical_after_restore
            .observation_batch_report()
            .map(|report| report.performance())
    );

    assert_eq!(
        workload.aspect_keyed_historical.family(),
        workload.aspect_keyed_equivalence.family()
    );
    assert_eq!(
        workload.aspect_keyed_historical.key(),
        workload.aspect_keyed_equivalence.key()
    );
    assert_eq!(
        workload.aspect_keyed_historical.node(),
        workload.aspect_keyed_equivalence.node()
    );
    assert_eq!(
        workload
            .aspect_keyed_equivalence
            .equivalence_report()
            .bundle_digest(),
        workload
            .aspect_keyed_historical
            .historical_parity_report()
            .bundle_digest()
    );

    assert_eq!(
        workload.hierarchy_replay_before_restore.replay_digest(),
        workload.hierarchy_replay_after_restore.replay_digest()
    );
    assert_ne!(
        workload.hierarchy_replay_after_cancellation.replay_digest(),
        workload.hierarchy_replay_after_restore.replay_digest()
    );
    assert_eq!(
        workload.hierarchy_cancellation.replay_digest(),
        workload.hierarchy_replay_after_cancellation.replay_digest()
    );
    assert_eq!(
        workload
            .hierarchy_historical_after_cancellation
            .hierarchy_replay_summary()
            .replay_digest(),
        workload.hierarchy_replay_after_cancellation.replay_digest()
    );
    assert_eq!(
        workload
            .hierarchy_historical_after_restore
            .hierarchy_replay_summary()
            .replay_digest(),
        workload.hierarchy_replay_after_restore.replay_digest()
    );
    assert_eq!(
        workload
            .hierarchy_historical_after_restore
            .historical_parity_report()
            .replay_reconstruction()
            .replay_digest(),
        workload
            .hierarchy_historical_before_restore
            .historical_parity_report()
            .replay_reconstruction()
            .replay_digest()
    );
    assert_ne!(
        workload
            .hierarchy_historical_after_restore
            .historical_parity_report()
            .replay_reconstruction()
            .replay_digest(),
        workload
            .hierarchy_historical_after_cancellation
            .historical_parity_report()
            .replay_reconstruction()
            .replay_digest()
    );
}

#[test]
fn async_node_nightmare_restore_lineage_keeps_hierarchy_honest_and_rebinds_keyed_explanations() {
    let workload = milestone_d_restore_lineage_nightmare_workload();

    assert_eq!(
        workload
            .baseline_hierarchy_historical
            .performance()
            .boundary(),
        ResourceBoundaryKind::AsyncNodeHierarchyHistoricalParity
    );
    assert_eq!(
        workload
            .restored_hierarchy_historical
            .performance()
            .boundary(),
        ResourceBoundaryKind::AsyncNodeHierarchyHistoricalParity
    );
    assert_eq!(
        workload
            .baseline_hierarchy_historical
            .hierarchy_replay_summary()
            .replay_digest(),
        workload
            .restored_hierarchy_historical
            .hierarchy_replay_summary()
            .replay_digest()
    );
    assert_eq!(
        workload
            .baseline_hierarchy_historical
            .historical_parity_report()
            .replay_reconstruction()
            .replay_digest(),
        workload
            .restored_hierarchy_historical
            .historical_parity_report()
            .replay_reconstruction()
            .replay_digest()
    );
    assert_eq!(
        workload
            .baseline_hierarchy_historical
            .historical_parity_report()
            .explanation_availability(),
        workload
            .restored_hierarchy_historical
            .historical_parity_report()
            .explanation_availability()
    );
    assert_eq!(
        explanation_without_ephemeral_execution_ids(
            workload
                .baseline_hierarchy_historical
                .historical_parity_report()
                .explanation_summary(),
        ),
        explanation_without_ephemeral_execution_ids(
            workload
                .restored_hierarchy_historical
                .historical_parity_report()
                .explanation_summary(),
        )
    );
    assert_ne!(
        workload
            .drifted_hierarchy_historical
            .hierarchy_replay_summary()
            .replay_digest(),
        workload
            .restored_hierarchy_historical
            .hierarchy_replay_summary()
            .replay_digest()
    );

    assert_eq!(
        workload.stale_keyed_historical_denial.denial_class(),
        AsyncKeyedNodeHistoricalParityDenialClass::HistoricalParityDenied
    );
    assert_eq!(
        workload
            .stale_keyed_historical_denial
            .historical_parity_denial()
            .expect("stale keyed denial should preserve inner historical cause")
            .denial_class(),
        AsyncNodeHistoricalParityDenialClass::UndeclaredCapability
    );
    assert_eq!(
        workload.stale_keyed_equivalence_denial.denial_class(),
        AsyncKeyedNodeCapabilityEquivalenceDenialClass::CapabilityEquivalenceDenied
    );
    assert_eq!(
        workload
            .stale_keyed_equivalence_denial
            .capability_equivalence_denial()
            .expect("stale keyed equivalence should preserve inner equivalence cause")
            .denial_class(),
        AsyncNodeCapabilityEquivalenceDenialClass::HistoricalParityDenied
    );
    assert_eq!(
        workload
            .stale_keyed_equivalence_denial
            .capability_equivalence_denial()
            .expect("stale keyed equivalence should preserve inner equivalence cause")
            .historical_parity_denial()
            .expect("stale keyed equivalence should preserve inner historical cause")
            .denial_class(),
        AsyncNodeHistoricalParityDenialClass::UndeclaredCapability
    );

    assert_eq!(
        workload.baseline_keyed_historical.family(),
        workload.rebound_keyed_historical.family()
    );
    assert_eq!(
        workload.baseline_keyed_historical.key(),
        workload.rebound_keyed_historical.key()
    );
    assert_eq!(
        workload.baseline_keyed_historical.node(),
        workload.rebound_keyed_historical.node()
    );
    assert_eq!(
        workload
            .baseline_keyed_historical
            .historical_parity_report()
            .explanation_availability(),
        workload
            .rebound_keyed_historical
            .historical_parity_report()
            .explanation_availability()
    );
    assert_eq!(
        workload
            .baseline_keyed_historical
            .historical_parity_report()
            .explanation_summary(),
        workload
            .rebound_keyed_historical
            .historical_parity_report()
            .explanation_summary()
    );
    assert_ne!(
        workload
            .baseline_keyed_historical
            .historical_parity_report()
            .payload_contract_digest(),
        workload
            .rebound_keyed_historical
            .historical_parity_report()
            .payload_contract_digest()
    );
    assert_ne!(
        workload
            .baseline_keyed_equivalence
            .equivalence_report()
            .capability_declaration_digest(),
        workload
            .rebound_keyed_equivalence
            .equivalence_report()
            .capability_declaration_digest()
    );
    assert_eq!(
        workload.old_binding_new_handle_denial.denial_class(),
        AsyncKeyedNodeHistoricalParityDenialClass::BindingHandleDigestMismatch
    );
    assert_eq!(
        workload.old_declaration_new_lineage_denial.denial_class(),
        AsyncKeyedNodeCapabilityEquivalenceDenialClass::CapabilityEquivalenceDenied
    );
    assert_eq!(
        workload
            .old_declaration_new_lineage_denial
            .capability_equivalence_denial()
            .expect("old declaration denial should preserve the inner equivalence cause")
            .denial_class(),
        AsyncNodeCapabilityEquivalenceDenialClass::HandleDeclarationDigestMismatch
    );
}
