use super::declared_input_role::ReplayUndoDeclaredInputRole;
use super::declared_input_role_set::ReplayUndoDeclaredInputRoleSet;
use super::declared_source::ReplayUndoDeclaredSource;
use super::declared_source_catalog::ReplayUndoDeclaredSourceCatalog;
use super::declared_source_identity::ReplayUndoDeclaredSourceIdentity;
use super::declared_source_kind::ReplayUndoDeclaredSourceKind;

pub fn current_replay_undo_declared_source_catalog() -> ReplayUndoDeclaredSourceCatalog {
    ReplayUndoDeclaredSourceCatalog::new(vec![
        ReplayUndoDeclaredSource::new(
            ReplayUndoDeclaredSourceIdentity::KernelWorthWorkloadRetainedReplay,
            "crates/worth-kernel/src/workload_composition/worth_workload.rs",
            ReplayUndoDeclaredSourceKind::PublicType,
            ReplayUndoDeclaredInputRoleSet::new(&[
                ReplayUndoDeclaredInputRole::RetainedReplayWorkloadReceipt,
            ]),
            ReplayUndoDeclaredInputRoleSet::new(&[]),
        ),
        ReplayUndoDeclaredSource::new(
            ReplayUndoDeclaredSourceIdentity::KernelWorthWorkloadDiagnostics,
            "crates/worth-kernel/src/workload_composition/worth_workload.rs",
            ReplayUndoDeclaredSourceKind::PublicType,
            ReplayUndoDeclaredInputRoleSet::new(&[]),
            ReplayUndoDeclaredInputRoleSet::new(&[
                ReplayUndoDeclaredInputRole::DiagnosticsWorkloadReceipt,
            ]),
        ),
        ReplayUndoDeclaredSource::new(
            ReplayUndoDeclaredSourceIdentity::KernelLookupConsumedWorkloadComposition,
            "crates/worth-kernel/src/workload_composition/worth_workload/lookup_consumed_workload/mod.rs",
            ReplayUndoDeclaredSourceKind::CompositionWrapper,
            ReplayUndoDeclaredInputRoleSet::new(&[
                ReplayUndoDeclaredInputRole::LookupConsumedWorkloadHandoff,
            ]),
            ReplayUndoDeclaredInputRoleSet::new(&[
                ReplayUndoDeclaredInputRole::StageIndexIdentity,
            ]),
        ),
        ReplayUndoDeclaredSource::new(
            ReplayUndoDeclaredSourceIdentity::KernelBooleanSplitReplayUndoBoundaryAdmission,
            "crates/worth-kernel/src/workload_composition/worth_workload/replay_undo_boundary/boolean_split_boundary_admission.rs",
            ReplayUndoDeclaredSourceKind::PublicFunction,
            ReplayUndoDeclaredInputRoleSet::new(&[
                ReplayUndoDeclaredInputRole::LookupConsumedWorkloadHandoff,
            ]),
            ReplayUndoDeclaredInputRoleSet::new(&[
                ReplayUndoDeclaredInputRole::StageIndexIdentity,
            ]),
        ),
        ReplayUndoDeclaredSource::new(
            ReplayUndoDeclaredSourceIdentity::SpatialEvidenceLookupConsumedWorkloadHandoff,
            "crates/worth-spatial/src/facade/evidence_lookup_workload_cutover/mod.rs",
            ReplayUndoDeclaredSourceKind::PublicType,
            ReplayUndoDeclaredInputRoleSet::new(&[
                ReplayUndoDeclaredInputRole::EvidenceLookupExecutionReceipt,
            ]),
            ReplayUndoDeclaredInputRoleSet::new(&[
                ReplayUndoDeclaredInputRole::EvidenceLookupCoveredFamilyIdentities,
            ]),
        ),
        ReplayUndoDeclaredSource::new(
            ReplayUndoDeclaredSourceIdentity::SpatialEvidenceLookupPublicCloseout,
            "crates/worth-spatial/src/facade/planner_owned_routing/public_closeout_route.rs",
            ReplayUndoDeclaredSourceKind::PublicFunction,
            ReplayUndoDeclaredInputRoleSet::new(&[
                ReplayUndoDeclaredInputRole::EvidenceLookupPublicCloseout,
            ]),
            ReplayUndoDeclaredInputRoleSet::new(&[
                ReplayUndoDeclaredInputRole::MilestoneTwelveSeed,
            ]),
        ),
        ReplayUndoDeclaredSource::new(
            ReplayUndoDeclaredSourceIdentity::SpatialEvidenceLookupPublicCloseoutAssemblyInput,
            "crates/worth-spatial/src/facade/planner_owned_routing/public_closeout_route.rs",
            ReplayUndoDeclaredSourceKind::PublicFunction,
            ReplayUndoDeclaredInputRoleSet::new(&[
                ReplayUndoDeclaredInputRole::EvidenceLookupPublicCloseoutAssemblyInput,
            ]),
            ReplayUndoDeclaredInputRoleSet::new(&[
                ReplayUndoDeclaredInputRole::SourceFirewallReport,
            ]),
        ),
        ReplayUndoDeclaredSource::new(
            ReplayUndoDeclaredSourceIdentity::TopologyDerivedInvalidationSelectedPlan,
            "crates/worth-topo/src/derived_invalidation_selected_plan/mod.rs",
            ReplayUndoDeclaredSourceKind::PublicType,
            ReplayUndoDeclaredInputRoleSet::new(&[
                ReplayUndoDeclaredInputRole::InvalidationSelectedPlan,
            ]),
            ReplayUndoDeclaredInputRoleSet::new(&[]),
        ),
        ReplayUndoDeclaredSource::new(
            ReplayUndoDeclaredSourceIdentity::TopologyDerivedInvalidationExecutionReceipt,
            "crates/worth-topo/src/derived_invalidation_execution/mod.rs",
            ReplayUndoDeclaredSourceKind::PublicType,
            ReplayUndoDeclaredInputRoleSet::new(&[
                ReplayUndoDeclaredInputRole::InvalidationExecutionReceipt,
            ]),
            ReplayUndoDeclaredInputRoleSet::new(&[
                ReplayUndoDeclaredInputRole::InvalidationDiagnosticProjection,
            ]),
        ),
        ReplayUndoDeclaredSource::new(
            ReplayUndoDeclaredSourceIdentity::TopologyDerivedInvalidationMilestoneElevenSeed,
            "crates/worth-topo/src/derived_invalidation_milestone_ten_closeout/mod.rs",
            ReplayUndoDeclaredSourceKind::PublicType,
            ReplayUndoDeclaredInputRoleSet::new(&[
                ReplayUndoDeclaredInputRole::InvalidationMilestoneElevenSeed,
            ]),
            ReplayUndoDeclaredInputRoleSet::new(&[
                ReplayUndoDeclaredInputRole::InvalidationLookupReadiness,
            ]),
        ),
        ReplayUndoDeclaredSource::new(
            ReplayUndoDeclaredSourceIdentity::TopologyDerivedInvalidationMilestoneElevenProductReceiptRef,
            "crates/worth-topo/src/derived_invalidation_milestone_ten_closeout/mod.rs",
            ReplayUndoDeclaredSourceKind::PublicType,
            ReplayUndoDeclaredInputRoleSet::new(&[
                ReplayUndoDeclaredInputRole::InvalidationProductReceiptRef,
            ]),
            ReplayUndoDeclaredInputRoleSet::new(&[
                ReplayUndoDeclaredInputRole::InvalidationQueryReceiptDigest,
            ]),
        ),
    ])
}
