use super::types::{
    WorthGraphAuthorityAction as Action, WorthGraphAuthorityDeletionLedgerRow as DeletionRow,
    WorthGraphAuthorityDeletionTarget as Target,
    WorthGraphAuthorityDiscoveryRecord as DiscoveryRow,
    WorthGraphAuthorityDiscoverySource as Source, WorthGraphAuthorityInventoryRow as InventoryRow,
    WorthGraphAuthorityOwner as Owner, WorthGraphAuthorityRootFamily as Family,
    WorthGraphAuthorityRowClass as Class, WorthGraphAuthoritySourceScope as SourceScope,
    WorthLowerAuthorityPromotionCase as PromotionCase,
    WorthLowerAuthorityPromotionGuardPlan as GuardPlan,
};

pub fn current_worth_graph_authority_inventory() -> Vec<InventoryRow> {
    vec![
        inventory("topology.operator-catalog", "crates/worth-topo/src/topology_operators/adoption", source_set(13, 0xfe1afd26f8eda362), Owner::Topology, Class::RootAuthority, Target::None, Source::Compiler, Action::Keep, "operator catalog adoption/residue/proof is a discovery root only", "Phase 3 keeps catalog lowering as Query adoption/status and denies promotion to execution proof"),
        inventory("topology.edge-split-blueprint", "crates/worth-topo/src/topology_operators/edge_split_blueprint", source_set(14, 0xe8eab6a95f8bfa6c), Owner::Topology, Class::Residue, Target::BlueprintProofObligation, Source::Compiler, Action::Residue, "edge-split blueprint rows are capped milestone split posture, not public graph authority", "raw proof-obligation vocabulary is crate-private; public facade exposes classification and Query surface posture only"),
        inventory("topology.loop-reconstruction-blueprint", "crates/worth-topo/src/topology_operators/loop_reconstruction_blueprint", source_set(17, 0x7413e3bb2b443936), Owner::Topology, Class::Residue, Target::BlueprintProofObligation, Source::Compiler, Action::Residue, "loop-reconstruction blueprint rows are capped milestone loop posture, not public graph authority", "raw proof-obligation vocabulary is crate-private; public facade exposes classification and Query surface posture only"),
        inventory("topology.query-native-boundary", "crates/worth-topo/src/construction/query_native_boundary", source_set(20, 0xef14b5b3a5deb893), Owner::Topology, Class::RootAuthority, Target::HandoffOnlyHelper, Source::Compiler, Action::Collapse, "query-native admission/handoff/compose execution surfaces identify topology authority edges", "Phase 3 replaces handoff-only helpers with execution-derived graph authority proof"),
        inventory("spatial.query-adoption", "crates/worth-spatial/src/query_adoption", source_set(6, 0x771425099ab01ea9), Owner::Spatial, Class::RootAuthority, Target::DuplicateSupportReport, Source::SearchSeed, Action::Collapse, "spatial adoption rows are discovery seeds, not graph authority proofs", "Phase 3 routes surviving facts through evidence-stage authorities"),
        inventory("spatial.evidence-ledger", "crates/worth-spatial/src/workload_platform/evidence_ledger", source_set(26, 0xb2047d0d7d38c3d4), Owner::Spatial, Class::RootAuthority, Target::StringStageLink, Source::PublicFacade, Action::Collapse, "evidence ledger, stage index, and stage links are the typed spatial evidence authority root", "Phase 3 pins stage-index consumption and deletes string-link promotion"),
        inventory("kernel.query-adoption", "crates/worth-kernel/src/query_adoption", source_set(18, 0xa6f634100c99340d), Owner::Kernel, Class::DuplicateSupport, Target::CompatibilityReport, Source::SearchSeed, Action::Delete, "kernel query adoption compatibility reports are deletion targets, not graph authority proof", "Phase 4 replaces compatibility reports with canonical authority gate rows"),
        inventory("kernel.query-authority", "crates/worth-kernel/src/construction/query_authority", source_set(9, 0xdcfede5fe5d66b1d), Owner::Kernel, Class::RootAuthority, Target::LocalSupportPinWrapper, Source::Compiler, Action::Keep, "query authority request/receipt/summary is a kernel authority root", "Phase 4 promotes only typed authority receipts"),
        inventory("kernel.graph-obligation-adoption", "crates/worth-kernel/src/construction/graph_obligation_adoption", source_set(7, 0x73eab3cf938cb245), Owner::Kernel, Class::RootAuthority, Target::BlueprintProofObligation, Source::Compiler, Action::Collapse, "selector and execution matrices expose graph-obligation family roots", "Phase 4 separates adoption selector proof from executed graph obligation proof"),
        inventory("kernel.phase-chain", "crates/worth-kernel/src/construction/phase_chain", source_set(24, 0x473e569a90399988), Owner::Kernel, Class::RootAuthority, Target::HandoffOnlyHelper, Source::Compiler, Action::Collapse, "admitted scaffold/result surfaces locate phase-chain authority transitions", "Phase 4 denies raw handoff and admitted-intent promotion"),
        inventory("kernel.result-surface", "crates/worth-kernel/src/construction/result_surface", source_set(8, 0xf85a4e3b81e3d425), Owner::Kernel, Class::RootAuthority, Target::HandoffOnlyHelper, Source::Compiler, Action::Collapse, "construction result surfaces expose where prepared results can be mistaken for executed graph authority", "Phase 4 routes result surfaces through executed authority evidence"),
        inventory("kernel.workload-composition", "crates/worth-kernel/src/workload_composition", source_set(96, 0x5585b7b60c788315), Owner::Kernel, Class::RootAuthority, Target::CopiedEvidenceRows, Source::Compiler, Action::Collapse, "workload evidence, split, and loop handoffs are composition roots only", "Phase 4 keeps split/loop authority typed by final digest family"),
        inventory("forge-query.consumer-kit", "crates/forge-query/src", source_set(2697, 0xf8f7b622c8742016), Owner::ForgeQuery, Class::RootAuthority, Target::None, Source::PublicFacade, Action::Keep, "Consumer Kit and Graph Touch facade are the query-graph authority boundary", "Phase 4 consumes authority through forge-query types only"),
    ]
}

pub fn current_worth_graph_authority_deletion_ledger() -> Vec<DeletionRow> {
    vec![
        deletion(
            "delete.duplicate-support-report",
            "crates/worth-spatial/src/query_adoption",
            Owner::Spatial,
            Target::DuplicateSupportReport,
            Action::Collapse,
            "replace duplicate support reports with the evidence-stage index",
            "WorkloadEvidenceStageIndexProduct remains the distinct authority",
            "",
            "",
            "",
            "",
        ),
        deletion(
            "delete.local-support-pin",
            "crates/worth-kernel/src/construction/query_authority",
            Owner::Kernel,
            Target::LocalSupportPinWrapper,
            Action::Keep,
            "keep only where query-authority receipt construction proves distinct authority",
            "authority receipt and support summary are separate kernel root proofs",
            "",
            "",
            "",
            "",
        ),
        deletion(
            "delete.blueprint-proof-obligation",
            "crates/worth-kernel/src/construction/graph_obligation_adoption",
            Owner::Kernel,
            Target::BlueprintProofObligation,
            Action::Collapse,
            "replace adoption blueprint rows with executed obligation proof rows",
            "selector and execution matrices remain discovery inputs",
            "",
            "",
            "",
            "",
        ),
        deletion(
            "delete.ceremony-audit",
            "crates/worth-topo/src/topology_operators/adoption",
            Owner::Topology,
            Target::CeremonyAudit,
            Action::Delete,
            "delete ceremony-only audits after root classification is pinned",
            "operator catalog lowers to Query descriptor, registration, support pin, selection proof, and residue manifest",
            "",
            "",
            "",
            "",
        ),
        deletion(
            "residue.edge-split-blueprint-proof-obligation",
            "crates/worth-topo/src/topology_operators/edge_split_blueprint",
            Owner::Topology,
            Target::BlueprintProofObligation,
            Action::Residue,
            "retain only capped edge-split milestone posture rows behind crate-private proof-obligation vocabulary",
            "public facade exposes classification/query-surface posture; Query owns graph authority execution proof",
            "worth-topo",
            "Milestone 7.3 edge-split blueprint posture only; no public proof-obligation enum or external row constructor",
            "worth-query-graph-authority-hardening phase 3",
            "replace with Query Consumer Kit executed graph-obligation proof when split topology execution is admitted",
        ),
        deletion(
            "residue.loop-reconstruction-blueprint-proof-obligation",
            "crates/worth-topo/src/topology_operators/loop_reconstruction_blueprint",
            Owner::Topology,
            Target::BlueprintProofObligation,
            Action::Residue,
            "retain only capped loop-reconstruction milestone posture rows behind crate-private proof-obligation vocabulary",
            "public facade exposes classification/query-surface posture; Query owns graph authority execution proof",
            "worth-topo",
            "Milestone 7.4 loop-reconstruction blueprint posture only; no public proof-obligation enum or external row constructor",
            "worth-query-graph-authority-hardening phase 3",
            "replace with Query Consumer Kit executed graph-obligation proof when loop topology execution is admitted",
        ),
        deletion(
            "delete.handoff-only-helper",
            "crates/worth-topo/src/construction/query_native_boundary",
            Owner::Topology,
            Target::HandoffOnlyHelper,
            Action::Collapse,
            "replace handoff-only result helpers with typed compose-execution authority",
            "TopologyPrimitiveConstructionBirthGraphAuthorityProof is derived only from Query-backed compose execution",
            "",
            "",
            "",
            "",
        ),
        deletion(
            "delete.raw-evidence-scan",
            "crates/worth-spatial/src/query_adoption",
            Owner::Spatial,
            Target::RawEvidenceScan,
            Action::Collapse,
            "replace raw scans with evidence-stage index lookups",
            "",
            "",
            "",
            "",
            "",
        ),
        deletion(
            "delete.copied-evidence-rows",
            "crates/worth-kernel/src/workload_composition",
            Owner::Kernel,
            Target::CopiedEvidenceRows,
            Action::Collapse,
            "collapse copied evidence rows into workload composition handoff receipts",
            "",
            "",
            "",
            "",
            "",
        ),
        deletion(
            "delete.string-stage-link",
            "crates/worth-spatial/src/workload_platform/evidence_ledger/stage_links",
            Owner::Spatial,
            Target::StringStageLink,
            Action::Collapse,
            "replace string-prefix links with typed stage-link rows",
            "",
            "",
            "",
            "",
            "",
        ),
        deletion(
            "delete.synthetic-fixture",
            "crates/worth-kernel/src/certification/public_facade_contracts",
            Owner::Kernel,
            Target::SyntheticFixture,
            Action::Collapse,
            "move synthetic graph authority fixtures behind certification-only boundaries",
            "",
            "",
            "",
            "",
            "",
        ),
        deletion(
            "delete.compatibility-report",
            "crates/worth-kernel/src/query_adoption",
            Owner::Kernel,
            Target::CompatibilityReport,
            Action::Delete,
            "remove compatibility report once new authority gate passes",
            "",
            "",
            "",
            "",
            "",
        ),
        deletion(
            "residue.manifest",
            "_docs/worth/worth-query-graph-authority-hardening-gate.md",
            Owner::Kernel,
            Target::ResidueManifest,
            Action::Residue,
            "certified residue manifest exists until all phased cleanup rows close",
            "",
            "cross-crate",
            "one manifest row per explicit residue class",
            "phase-1",
            "all deletion ledger rows reach Delete or Collapse",
        ),
    ]
}

pub fn current_worth_graph_authority_discovery_records() -> Vec<DiscoveryRow> {
    vec![
        discovery(
            Family::TopologyOperatorCatalog,
            Owner::Topology,
            "topology_operators/adoption::{catalog,proof,residue}",
            "break catalog support exports",
            "callers using operator adoption proof as graph proof fail",
            "typed topology operator authority inventory row",
        ),
        discovery(
            Family::TopologyQueryNativeBoundary,
            Owner::Topology,
            "construction/query_native_boundary::{admission,handoff,compose_execution}",
            "break admitted handoff helper exports",
            "raw handoff and scaffold shortcuts fail",
            "compose-execution authority result",
        ),
        discovery(
            Family::SpatialQueryAdoption,
            Owner::Spatial,
            "query_adoption::{consumer_kit,evidence_reports,support_projection}",
            "break support projection promotion",
            "spatial adoption rows cannot certify graph authority",
            "evidence-stage authority projection",
        ),
        discovery(
            Family::SpatialEvidenceStageIndex,
            Owner::Spatial,
            "workload_platform/evidence_ledger/stage_index",
            "break raw stage scans",
            "raw evidence rows cannot replace stage index",
            "WorkloadEvidenceStageIndexProduct",
        ),
        discovery(
            Family::KernelQueryAuthority,
            Owner::Kernel,
            "construction/query_authority",
            "break support summary promotion",
            "support summary cannot satisfy query authority receipt",
            "query authority receipt/request boundary",
        ),
        discovery(
            Family::KernelGraphObligationAdoption,
            Owner::Kernel,
            "construction/graph_obligation_adoption::{selector_matrix,family_execution_matrix}",
            "break adoption selector proof promotion",
            "crate adoption proof cannot satisfy graph obligation proof",
            "executed graph obligation proof row",
        ),
        discovery(
            Family::KernelPhaseChain,
            Owner::Kernel,
            "construction/phase_chain",
            "break admitted scaffold/result helper promotion",
            "admitted intent and raw scaffold helpers fail",
            "typed phase-chain authority handoff",
        ),
        discovery(
            Family::WorkloadCompositionHandoffs,
            Owner::Kernel,
            "workload_composition",
            "break split digest promotion to loop digest",
            "split-only digest cannot satisfy loop authority",
            "family-specific workload authority digest",
        ),
        discovery(
            Family::ForgeQueryConsumerKit,
            Owner::ForgeQuery,
            "forge-query Consumer Kit and Graph Touch facade",
            "break raw graph touch facade bypass",
            "raw lower-authority touch cannot cross consumer kit",
            "forge-query graph authority facade",
        ),
    ]
}

pub fn current_worth_lower_authority_promotion_guard_plan() -> Vec<GuardPlan> {
    vec![
        guard(PromotionCase::SupportReportNotGraphAuthority, "query_adoption support report", "query graph authority receipt", "src/certification/public_facade_contracts/compile_fail/worth_graph_authority/support_report_not_graph_authority.rs"),
        guard(PromotionCase::CrateAdoptionNotGraphObligationProof, "crate-level adoption proof", "executed graph obligation proof", "src/certification/public_facade_contracts/compile_fail/worth_graph_authority/adoption_not_graph_obligation.rs"),
        guard(PromotionCase::HandoffNotExecutedBirth, "admitted handoff", "executed birth/compose authority", "src/certification/public_facade_contracts/compile_fail/worth_graph_authority/handoff_not_executed_birth.rs"),
        guard(PromotionCase::RawEvidenceNotStageIndex, "raw evidence row", "WorkloadEvidenceStageIndexProduct", "src/certification/public_facade_contracts/compile_fail/worth_graph_authority/raw_evidence_not_stage_index.rs"),
        guard(PromotionCase::StringPrefixNotTypedStageLink, "string-prefix stage link", "typed stage-link authority row", "src/certification/public_facade_contracts/compile_fail/worth_graph_authority/string_prefix_not_stage_link.rs"),
        guard(PromotionCase::SplitDigestNotLoopDigest, "split digest", "loop authority digest", "src/certification/public_facade_contracts/compile_fail/worth_graph_authority/split_digest_not_loop_digest.rs"),
        guard(PromotionCase::SyntheticFixtureNotProductionProof, "synthetic graph authority fixture", "production graph authority proof", "src/certification/public_facade_contracts/compile_fail/worth_graph_authority/synthetic_fixture_not_production.rs"),
        guard(PromotionCase::ResidueLiteralNotCertifiedManifest, "residue literal", "certified residue manifest row", "src/certification/public_facade_contracts/compile_fail/worth_graph_authority/residue_literal_not_manifest.rs"),
    ]
}

fn inventory(
    source_id: &'static str,
    source_path: &'static str,
    source_scope: SourceScope,
    owner: Owner,
    row_class: Class,
    deletion_target: Target,
    discovery_source: Source,
    action: Action,
    authority_claim: &'static str,
    replacement_or_blocker: &'static str,
) -> InventoryRow {
    InventoryRow {
        source_id,
        source_path,
        source_scope,
        owner,
        row_class,
        deletion_target,
        discovery_source,
        action,
        authority_claim,
        replacement_or_blocker,
        qa_evidence: "phase-1 scoreboard validation",
    }
}

fn source_set(expected_sources: usize, manifest_digest: u64) -> SourceScope {
    SourceScope::AuditedSourceSet {
        expected_sources,
        manifest_digest,
    }
}

fn deletion(
    target_id: &'static str,
    source_path: &'static str,
    owner: Owner,
    deletion_target: Target,
    action: Action,
    replacement_or_blocker: &'static str,
    distinct_authority_proof: &'static str,
    residue_owner: &'static str,
    residue_cap: &'static str,
    introduced_phase: &'static str,
    removal_trigger: &'static str,
) -> DeletionRow {
    DeletionRow {
        target_id,
        source_path,
        owner,
        deletion_target,
        action,
        replacement_or_blocker,
        distinct_authority_proof,
        residue_owner,
        residue_cap,
        introduced_phase,
        removal_trigger,
        qa_evidence: "phase-1 deletion ledger validation",
    }
}

fn discovery(
    root_family: Family,
    owner: Owner,
    root_surface: &'static str,
    intentional_break: &'static str,
    downstream_compile_failures: &'static str,
    final_enforced_api: &'static str,
) -> DiscoveryRow {
    DiscoveryRow {
        root_family,
        owner,
        root_surface,
        intentional_break,
        downstream_compile_failures,
        final_enforced_api,
        qa_evidence: "phase-1 root discovery coverage",
    }
}

fn guard(
    promotion_case: PromotionCase,
    lower_authority_surface: &'static str,
    required_authority_type: &'static str,
    planned_compile_fail_path: &'static str,
) -> GuardPlan {
    GuardPlan {
        promotion_case,
        lower_authority_surface,
        required_authority_type,
        planned_compile_fail_path,
        enforcement_stage: "planned phase-2-to-4 compile-fail contract",
        qa_evidence: "phase-1 lower-authority promotion plan",
    }
}
