use super::touched_graph_static_authority::current_worth_touched_graph_static_authority_inventory_rows;
use super::touched_graph_types::{
    WorthTouchedGraphAuthorityDeletionLedgerRow, WorthTouchedGraphAuthorityDisposition as Action,
    WorthTouchedGraphAuthorityInventoryCategory as Category,
    WorthTouchedGraphAuthorityInventoryRow,
};

pub(crate) const NO_ORDINARY_PUBLIC_FACADE: &str = "no-ordinary-public-facade";
pub(crate) const SEALED_FROM_ORDINARY_FACADE: &str = "sealed-from-ordinary-facade";
pub(crate) const CERTIFICATION_ONLY_PUBLIC_FACADE: &str = "certification-only-public-facade";
pub(crate) const CAPPED_RESIDUE_PUBLIC_FACADE: &str = "capped-residue-public-facade";

pub fn current_worth_touched_graph_authority_inventory(
) -> Vec<WorthTouchedGraphAuthorityInventoryRow> {
    let mut rows = vec![
        row(
            "topology.validation.facade",
            "crates/worth-topo/src/validation/facade.rs",
            Category::StaticValidator,
            "worth-topo",
            "TopologyValidator::materialized_validation_report and derived_validation_report run whole-view validator packs.",
            "Phase 5 touched graph closure selects validator families from touched topology predicates.",
            Action::CertificationOnly,
            "not-residue",
            "Phase 5 replaces ordinary operator legality with touched validator selection; whole-view validation remains certification only.",
            CERTIFICATION_ONLY_PUBLIC_FACADE,
            "inventory row covers whole-view validation facade before touched validator selection exists",
        ),
        row(
            "topology.validation.rule-registry",
            "crates/worth-topo/src/validation/rule_registry.rs",
            Category::StaticInvariant,
            "worth-topo",
            "DERIVED_TOPOLOGY_RULE_SPECS names static invariant families independent of touched graph facts.",
            "Phase 5 moves rule families behind touched graph predicate coverage and closure expansion.",
            Action::Collapse,
            "not-residue",
            "Phase 5 deletes or collapses the static registry into touched predicate buckets.",
            NO_ORDINARY_PUBLIC_FACADE,
            "hostile category test fails if static invariant coverage is removed",
        ),
        row(
            "topology.operator-intent-blueprints",
            "crates/worth-topo/src/topology_operators",
            Category::OperatorIntentLowering,
            "worth-topo",
            "Blueprint proof-obligation, validator-row, scalar declaration, and local rewrite files can describe legality before touched basis lowering.",
            "Phases 2 and 3 require every graph-affecting operator intent to emit sealed touched graph basis before Query lowering.",
            Action::Residue,
            "operator intent may remain only as non-authoritative input; it cannot certify validators or receipts",
            "Phase 3 removes operator-local authority once all scoped topology operators lower through touched basis.",
            CAPPED_RESIDUE_PUBLIC_FACADE,
            "source-derived facade audit caps public topology operator exports as residue",
        ),
        row(
            "query.graph-composition-selection",
            "crates/forge-query/src/runtime/mutation/graph_composition",
            Category::QueryRuntimeSelection,
            "forge-query",
            "Touch descriptors, selector registration, support posture, and composition counters select or deny graph obligations.",
            "Phase 4 consumes Worth touched basis through canonical Query descriptors without Worth-local selector copies.",
            Action::QueryGap,
            "not-residue",
            "Phase 4 resolves missing topology closure selector expressiveness or records Query-owned gaps.",
            NO_ORDINARY_PUBLIC_FACADE,
            "inventory names Query as selector authority and prevents local Worth selector forks",
        ),
        row(
            "topology.projection.read-stage",
            "crates/worth-topo/src/projection",
            Category::DerivedInvalidation,
            "worth-topo",
            "Projection read stages can materialize, interpret, validate, and rebuild derived products from whole-view state.",
            "Phase 6 derives invalidation products from touched graph closure, direct touch counters, and expansion counters.",
            Action::Residue,
            "ordinary topology facade still exposes projection runtime surfaces for existing consumers only; they cannot certify touched dirty-region authority",
            "Phase 6 deletes hidden whole-view invalidation fallbacks after dirty-region products exist.",
            CAPPED_RESIDUE_PUBLIC_FACADE,
            "source-derived facade audit caps public projection runtime exports as residue",
        ),
        row(
            "topology.projection.dirty-propagation",
            "crates/worth-topo/src/projection/runtime_boundary",
            Category::DirtyPropagation,
            "worth-topo",
            "Runtime boundary read stages hide dirty breadth behind staged whole-view reads.",
            "Phase 6 exposes touched dirty-region propagation as a proof product before derived rebuild work.",
            Action::Residue,
            "ordinary topology facade still exposes runtime-boundary query surfaces for existing consumers only; they cannot certify touched dirty propagation",
            "Phase 6 replaces runtime-boundary hidden dirty propagation with explicit touched graph proof.",
            CAPPED_RESIDUE_PUBLIC_FACADE,
            "source-derived facade audit caps public runtime-boundary exports as residue",
        ),
        row(
            "spatial.workload-replay",
            "crates/worth-spatial/src/workload_platform",
            Category::ReplayScope,
            "worth-spatial",
            "Planar split, loop reconstruction, cancellation-chain, and retained replay paths can replay from workload family or retained rows.",
            "Phase 8 carries replay scope as touched graph closure plus receipt digests.",
            Action::Residue,
            "ordinary retained replay facade remains public only as workload vocabulary; it cannot certify touched graph replay scope",
            "Phase 8 removes global replay and family-based replay scopes.",
            CAPPED_RESIDUE_PUBLIC_FACADE,
            "facade audit treats retained replay exports as capped residue, not delete/collapse proof",
        ),
        row(
            "spatial.evidence-ledger",
            "crates/worth-spatial/src/workload_platform/evidence_ledger",
            Category::EvidenceLookup,
            "worth-spatial",
            "Raw WorkloadEvidenceRow vectors, stage links, and stage index products can act as broad evidence lookup authority.",
            "Phase 7 keys evidence lookup by touched graph identity, stage, and receipt digest.",
            Action::Residue,
            "ordinary workload vocabulary may expose evidence row types, but raw rows cannot satisfy touched graph lookup authority",
            "Phase 7 deletes raw evidence scans from public lookup contracts.",
            CAPPED_RESIDUE_PUBLIC_FACADE,
            "compile-fail evidence fences plus facade audit cap raw evidence public residue",
        ),
        row(
            "query.conflict-independence",
            "crates/forge-query/src/runtime/mutation/graph_composition/obligation",
            Category::ConflictIndependence,
            "forge-query",
            "Support posture conflicts and obligation registration can deny or admit work without Worth touched closure identity.",
            "Phase 9 derives conflict posture from touched entity, relation, aspect, closure, evidence, and validator overlap.",
            Action::QueryGap,
            "not-residue",
            "Phase 9 resolves compatible aspect-overlap selector support or records the Query-owned gap.",
            NO_ORDINARY_PUBLIC_FACADE,
            "conflict row prevents lock-first or speculative conflict substitutes",
        ),
        row(
            "spatial.cache-equivalence",
            "crates/worth-spatial/src/workload_platform",
            Category::CacheEquivalenceReuse,
            "worth-spatial",
            "Retained replay catalogs and workload cache identities can reuse by operation family, row count, or retained replay key.",
            "Phase 10 keys reuse by touched graph digest, source authority digest, stage, and equivalence policy.",
            Action::Residue,
            "retained replay facade remains public for workload inspection but cannot certify cache equivalence",
            "Phase 10 deletes family-based cache and equivalence authority.",
            CAPPED_RESIDUE_PUBLIC_FACADE,
            "facade audit catches any attempt to relabel exported retained replay family as delete/collapse",
        ),
        row(
            "query.undo-transaction-scope",
            "crates/forge-query/src/runtime/mutation/graph_composition",
            Category::UndoTransactionScope,
            "forge-query",
            "The scoped graph-composition runtime has no sealed minimal reversible graph patch proof for Worth graph mutations.",
            "Query gap: Phase 8 must define undo scope as touched closure plus reversible graph patch proof before rollback can certify.",
            Action::QueryGap,
            "not-residue",
            "Phase 8 either lands Query transaction/undo proof or keeps the named gap blocking closeout.",
            NO_ORDINARY_PUBLIC_FACADE,
            "explicit undo gap prevents prose-only transaction coverage",
        ),
        row(
            "spatial.workload-diagnostics",
            "crates/worth-spatial/src/workload_platform",
            Category::DiagnosticSurface,
            "worth-spatial",
            "Split, loop, decision-log, and user-response diagnostics can explain outcomes from broad workload rows.",
            "Phase 11 diagnostics cite touched graph facts, selected validators, evidence lookup ids, or named Query gaps.",
            Action::Residue,
            "ordinary user-response diagnostics remain public only as explanations, not touched graph authority",
            "Phase 11 deletes diagnostic strings that imply authority without touched proof.",
            CAPPED_RESIDUE_PUBLIC_FACADE,
            "facade audit caps diagnostic exports and prevents delete/collapse claims while public",
        ),
        row(
            "cross-crate.public-facades",
            "crates/worth-topo/src/validation/mod.rs",
            Category::PublicFacade,
            "cross-crate",
            "Validation and workload public exports can expose whole-view validation or raw evidence helpers to ordinary consumers.",
            "Phases 5, 7, and 11 expose only read-only touched proof status, counters, and denial explanations.",
            Action::CertificationOnly,
            "not-residue",
            "Phase 11 seals ordinary facades so static/global surfaces cannot satisfy touched graph authority.",
            CERTIFICATION_ONLY_PUBLIC_FACADE,
            "deletion test rejects delete/collapse rows that remain ordinary facade exports",
        ),
        row(
            "kernel.touched-deletion-ledger",
            "crates/worth-kernel/src/query_graph_authority_gate",
            Category::DeletionLedger,
            "worth-kernel",
            "Phase 1 inventory and deletion rows are the authority for what old surfaces may remain reachable.",
            "This harness rejects keep-like dispositions and public delete/collapse exports before later phases consume the rows.",
            Action::CertificationOnly,
            "not-residue",
            "Phase 12 closeout matrix consumes this ledger and must leave only implemented, capped residue, or Query-gap rows.",
            CERTIFICATION_ONLY_PUBLIC_FACADE,
            "typed deletion-ledger harness is implemented in worth-kernel",
        ),
        row(
            "kernel.touched-line-cap",
            "crates/worth-kernel/src/query_graph_authority_gate",
            Category::CompositionLineCap,
            "worth-kernel",
            "Large registry or test files can hide broad bucket logic and static/global compatibility paths.",
            "Workspace Rust line-cap script plus focused touched-file test enforces split modules under the 400-line cap.",
            Action::CertificationOnly,
            "not-residue",
            "Every implement/review turn runs line-cap proof for touched Rust files or splits them before close.",
            CERTIFICATION_ONLY_PUBLIC_FACADE,
            "composition test reads touched files and enforces the workspace cap",
        ),
    ];
    rows.extend(current_worth_touched_graph_static_authority_inventory_rows());
    rows
}

pub fn current_worth_touched_graph_deletion_ledger(
) -> Vec<WorthTouchedGraphAuthorityDeletionLedgerRow> {
    vec![
        ledger(
            "delete.static-rule-registry",
            "topology.validation.rule-registry",
            "crates/worth-topo/src/validation/rule_registry.rs",
            "worth-topo",
            Action::Collapse,
            "DERIVED_TOPOLOGY_RULE_SPECS",
            "sealed from ordinary facade; later collapsed into touched validator predicate registry",
            "Phase 5 touched validator predicate buckets",
            "Phase 5 validator derivation lands and ordinary operator legality no longer calls static rule specs.",
            SEALED_FROM_ORDINARY_FACADE,
            "delete/collapse row has no ordinary public facade export",
        ),
        ledger(
            "delete.projection-global-read-stage",
            "topology.projection.read-stage",
            "crates/worth-topo/src/projection",
            "worth-topo",
            Action::Residue,
            "projection runtime boundary whole-view read stage",
            "capped residue: ordinary topology facade exports projection runtime surfaces for existing consumers only",
            "Phase 6 touched invalidation and dirty propagation product",
            "Phase 6 dirty propagation proof is available to derived consumers.",
            CAPPED_RESIDUE_PUBLIC_FACADE,
            "facade audit rejects this row if reclassified as delete/collapse while projection exports remain public",
        ),
        ledger(
            "delete.raw-evidence-ledger",
            "spatial.evidence-ledger",
            "crates/worth-spatial/src/workload_platform/evidence_ledger",
            "worth-spatial",
            Action::Residue,
            "WorkloadEvidenceRow vectors and stage-link index products",
            "capped residue: ordinary workload vocabulary exports evidence row types for existing consumers only",
            "Phase 7 touched evidence lookup keyed by graph digest, stage, and receipt digest",
            "Phase 7 no-raw-scan public contract test passes.",
            CAPPED_RESIDUE_PUBLIC_FACADE,
            "raw evidence rows cannot satisfy touched graph lookup authority and are audited as public residue",
        ),
        ledger(
            "delete.retained-replay-cache",
            "spatial.cache-equivalence",
            "crates/worth-spatial/src/workload_platform",
            "worth-spatial",
            Action::Residue,
            "retained replay cache and canonical catalog reuse keys",
            "capped residue: retained replay facade remains public for workload inspection only",
            "Phase 10 touched graph cache equivalence key",
            "Phase 10 drift test denies reuse for same family with different touched closure.",
            CAPPED_RESIDUE_PUBLIC_FACADE,
            "facade audit rejects this row if reclassified as delete/collapse while retained replay exports remain public",
        ),
        ledger(
            "delete.diagnostic-authority",
            "spatial.workload-diagnostics",
            "crates/worth-spatial/src/workload_platform",
            "worth-spatial",
            Action::Residue,
            "split, loop, retained replay, and user response diagnostic explanations",
            "capped residue: ordinary user-response diagnostics remain explanatory only",
            "Phase 11 touched graph diagnostic facts and denial reasons",
            "Phase 11 diagnostics expose touched fact ids instead of broad workload rows.",
            CAPPED_RESIDUE_PUBLIC_FACADE,
            "facade audit rejects this row if reclassified as delete/collapse while diagnostics exports remain public",
        ),
    ]
}

#[allow(clippy::too_many_arguments)]
const fn row(
    source_id: &'static str,
    source_path: &'static str,
    category: Category,
    owner: &'static str,
    current_authority_source: &'static str,
    touched_graph_replacement: &'static str,
    disposition: Action,
    residue_cap: &'static str,
    removal_trigger: &'static str,
    ordinary_public_facade: &'static str,
    qa_evidence: &'static str,
) -> WorthTouchedGraphAuthorityInventoryRow {
    WorthTouchedGraphAuthorityInventoryRow::new(
        source_id,
        source_path,
        category,
        owner,
        current_authority_source,
        touched_graph_replacement,
        disposition,
        residue_cap,
        removal_trigger,
        ordinary_public_facade,
        qa_evidence,
    )
}

#[allow(clippy::too_many_arguments)]
const fn ledger(
    target_id: &'static str,
    source_id: &'static str,
    source_path: &'static str,
    owner: &'static str,
    disposition: Action,
    former_public_surface: &'static str,
    enforced_outcome: &'static str,
    touched_graph_replacement: &'static str,
    removal_trigger: &'static str,
    ordinary_public_facade: &'static str,
    qa_evidence: &'static str,
) -> WorthTouchedGraphAuthorityDeletionLedgerRow {
    WorthTouchedGraphAuthorityDeletionLedgerRow::new(
        target_id,
        source_id,
        source_path,
        owner,
        disposition,
        former_public_surface,
        enforced_outcome,
        touched_graph_replacement,
        removal_trigger,
        ordinary_public_facade,
        qa_evidence,
    )
}
