pub(super) const SEMANTIC_CAUSAL_SOURCES: &[(&str, &[&str])] = &[
    (
        "root-publication-anchor",
        &[
            "workspaces/worth-store/crates/worth-store/src/physical_runtime/record_serving/planning/rebased_root/assembly.rs",
            "workspaces/worth-store/crates/worth-store/src/physical_runtime/record_serving/publication/root_candidate_writes.rs",
            "workspaces/worth-store/crates/worth-store-physical-backend/src/filesystem_media/artifact_tree/publication_effect/execution/root_protocol_replacement.rs",
            "workspaces/worth-store/crates/worth-store-recovery-runtime/src/orchestration/discovery/observation.rs",
            "workspaces/worth-store/crates/worth-store-recovery-physics/src/source_precedence/current_previous_root.rs",
            "workspaces/worth-store/crates/worth-store-recovery-runtime/tests/phase_three_root_anchor.rs",
        ],
    ),
    (
        "current-root-selector",
        &[
            "workspaces/worth-store/crates/worth-store/src/physical_runtime/record_serving/admission/initialization.rs",
            "workspaces/worth-store/crates/worth-store/src/physical_runtime/record_serving/planning/rebased_root/assembly.rs",
            "workspaces/worth-store/crates/worth-store/src/physical_runtime/record_serving/publication/root_candidate_writes.rs",
            "workspaces/worth-store/crates/worth-store-physical-backend/src/filesystem_media/artifact_tree/publication_effect/execution/root_protocol_replacement.rs",
            "workspaces/worth-store/crates/worth-store-physical-backend/src/recovery_media/publication.rs",
            "workspaces/worth-store/crates/worth-store/src/physical_runtime/recovery_coordination/publication/execution.rs",
            "workspaces/worth-store/crates/worth-store/src/physical_runtime/recovery_coordination/reopen/execution.rs",
            "workspaces/worth-store/crates/worth-store-recovery-runtime/src/orchestration/reopen.rs",
            "workspaces/worth-store/crates/worth-store/tests/physical_record_journeys/durability_admission/data_durability/root_projection_carriage.rs",
        ],
    ),
    (
        "free-space-allocation-header",
        &[
            "workspaces/worth-store/crates/worth-store-physical-format/src/manifest/durable_free_space_header.rs",
            "workspaces/worth-store/crates/worth-store-physical-format/src/binary_format/record_membership_golden_bytes.rs",
            "workspaces/worth-store/crates/worth-store/src/physical_runtime/record_serving/admission/initialization.rs",
            "workspaces/worth-store/crates/worth-store/src/physical_runtime/record_serving/planning/free_space_projection.rs",
            "workspaces/worth-store/crates/worth-store/src/physical_runtime/record_serving/planning/free_space_routing/successor.rs",
            "workspaces/worth-store/crates/worth-store-recovery-runtime/src/orchestration/planning/page_observation/allocation_truth.rs",
            "workspaces/worth-store/crates/worth-store-recovery-runtime/src/orchestration/planning/page_observation/allocation_truth/inline_allocation.rs",
            "workspaces/worth-store/crates/worth-store-recovery-physics/src/redo_replay/plan/allocation_truth.rs",
            "workspaces/worth-store/crates/worth-store-recovery-runtime/src/orchestration/planning/page_observation/allocation_truth/tests/capacity_tests.rs",
        ],
    ),
    (
        "previous-root-selector",
        &[
            "workspaces/worth-store/crates/worth-store/src/physical_runtime/record_serving/planning/rebased_root/assembly.rs",
            "workspaces/worth-store/crates/worth-store/src/physical_runtime/record_serving/publication/root_candidate_writes.rs",
            "workspaces/worth-store/crates/worth-store-physical-backend/src/filesystem_media/artifact_tree/publication_effect/execution/root_protocol_replacement.rs",
            "workspaces/worth-store/crates/worth-store-physical-backend/src/recovery_media/publication.rs",
            "workspaces/worth-store/crates/worth-store/src/physical_runtime/recovery_coordination/publication/execution.rs",
            "workspaces/worth-store/crates/worth-store/tests/physical_record_journeys/durability_admission/data_durability/root_projection_carriage.rs",
        ],
    ),
    (
        "root-manifest",
        &[
            "workspaces/worth-store/crates/worth-store-recovery-runtime/src/progression/planned/basis/derivation/closeout.rs",
            "workspaces/worth-store/crates/worth-store-physical-backend/src/recovery_media/publication.rs",
            "workspaces/worth-store/crates/worth-store/src/physical_runtime/recovery_coordination/publication/execution.rs",
            "workspaces/worth-store/crates/worth-store/src/physical_runtime/recovery_coordination/reopen/execution.rs",
            "workspaces/worth-store/crates/worth-store-recovery-runtime/src/orchestration/reopen.rs",
        ],
    ),
    (
        "checkpoint-binding-compaction",
        &[
            "mutation/idempotency/runtime_owner.rs",
            "checkpoint/publication.rs",
            "checkpoint/reopen/binding_compaction.rs",
        ],
    ),
    (
        "wal-security-binding",
        &[
            "workspaces/worth-store/crates/worth-store-wal/src/artifact_store/segment_inventory/segment_inspection.rs",
            "wal/group_reservation/member_planning.rs",
            "mutation/idempotency/persisted_binding/decoding.rs",
            "workspaces/worth-store/crates/worth-store/src/physical_runtime/recovery_freshness/binding.rs",
        ],
    ),
    (
        "checkpoint-security-binding",
        &[
            "workspaces/worth-store/crates/worth-store-physical-format/src/checkpoint/source.rs",
            "workspaces/worth-store/crates/worth-store-physical-format/src/checkpoint/record.rs",
            "workspaces/worth-store/crates/worth-store-physical-format/src/checkpoint/stream.rs",
            "workspaces/worth-store/crates/worth-store-physical-format/src/checkpoint/inspection.rs",
            "checkpoint/capture.rs",
            "workspaces/worth-store/crates/worth-store/src/physical_runtime/recovery_freshness/binding.rs",
        ],
    ),
    (
        "operation-attempt-binding-wal",
        &[
            "mutation/idempotency/attempt_binding.rs",
            "wal/group_reservation/member_planning.rs",
            "wal/inventory/reopened_member.rs",
            "mutation/idempotency/persisted_binding.rs",
            "mutation/idempotency/persisted_binding/decoding.rs",
            "mutation/idempotency/bootstrap.rs",
        ],
    ),
    (
        "operation-terminal-fate",
        &[
            "mutation/idempotency/fate/persisted.rs",
            "mutation/idempotency/binding_compaction/encoding.rs",
            "mutation/idempotency/binding_compaction/decoding.rs",
            "mutation/idempotency/binding_compaction.rs",
            "mutation/idempotency/bootstrap.rs",
            "mutation/idempotency/runtime_owner.rs",
            "checkpoint/publication.rs",
            "checkpoint/reopen/binding_compaction.rs",
        ],
    ),
    (
        "operation-binding-compaction-state",
        &[
            "mutation/idempotency/binding_compaction/encoding.rs",
            "mutation/idempotency/binding_compaction/decoding.rs",
            "mutation/idempotency/persisted_binding/decoding.rs",
            "mutation/idempotency/fate/persisted.rs",
            "mutation/idempotency/binding_compaction.rs",
            "mutation/idempotency/bootstrap.rs",
            "mutation/idempotency/runtime_owner.rs",
            "checkpoint/publication.rs",
            "checkpoint/reopen/binding_compaction.rs",
        ],
    ),
    (
        "canonical-redo-v3",
        &[
            "workspaces/worth-store/crates/worth-store/src/physical_runtime/durability/wal/canonical_redo.rs",
            "wal/group_reservation/member_planning.rs",
            "workspaces/worth-store/crates/worth-store-recovery-physics/src/redo_replay/record.rs",
            "workspaces/worth-store/crates/worth-store-recovery-physics/src/redo_replay/record/target_decode.rs",
            "workspaces/worth-store/crates/worth-store-recovery-physics/src/redo_replay/plan/admission.rs",
            "workspaces/worth-store/crates/worth-store-recovery-physics/src/redo_replay/plan/group_admission.rs",
            "workspaces/worth-store/crates/worth-store-recovery-physics/src/redo_replay/plan_tests.rs",
        ],
    ),
    (
        "recovery-projection-v3",
        &[
            "workspaces/worth-store/crates/worth-store-physical-format/src/recovery_projection.rs",
            "workspaces/worth-store/crates/worth-store-physical-format/src/recovery_projection/codec.rs",
            "workspaces/worth-store/crates/worth-store-physical-format/src/recovery_projection/codec/cursor.rs",
            "workspaces/worth-store/crates/worth-store-physical-format/src/recovery_projection/root_state.rs",
            "wal/group_reservation/member_planning.rs",
            "workspaces/worth-store/crates/worth-store-recovery-physics/src/redo_replay/record/target_decode.rs",
            "workspaces/worth-store/crates/worth-store-recovery-physics/src/redo_replay/cursor.rs",
            "workspaces/worth-store/crates/worth-store-recovery-physics/src/redo_replay/plan/projection_validation.rs",
            "workspaces/worth-store/crates/worth-store-recovery-physics/src/redo_replay/plan/projection_materialization.rs",
            "workspaces/worth-store/crates/worth-store-recovery-physics/src/redo_replay/plan/group_admission.rs",
            "workspaces/worth-store/crates/worth-store-recovery-physics/src/redo_replay/plan_tests/group_atomic.rs",
            "workspaces/worth-store/crates/worth-store-recovery-physics/src/redo_replay/plan_tests/projection_mutants.rs",
            "workspaces/worth-store/crates/worth-store-recovery-physics/src/redo_replay/plan_tests.rs",
            "workspaces/worth-store/crates/worth-store-recovery-runtime/src/orchestration/planning/page_observation/materialized.rs",
            "workspaces/worth-store/crates/worth-store-recovery-runtime/src/progression/planned/basis/derivation/pending.rs",
            "workspaces/worth-store/crates/worth-store-recovery-runtime/src/progression/planned/basis/derivation/materialization.rs",
            "workspaces/worth-store/crates/worth-store-recovery-runtime/tests/phase_four_process.rs",
            "workspaces/worth-store/crates/worth-store-recovery-runtime/tests/phase_five_generation_axes.rs",
        ],
    ),
];
#[rustfmt::skip]
pub(super) const SEMANTIC_CAUSAL_SYNTAX: &[(&str, &str, &str, &[&str])] = &[
    ("root-publication-anchor", "workspaces/worth-store/crates/worth-store/src/physical_runtime/record_serving/planning/rebased_root/assembly.rs", "assemble_rebased_publication", &["path:BootstrapCatalog::new"]),
    ("root-publication-anchor", "workspaces/worth-store/crates/worth-store/src/physical_runtime/record_serving/publication/root_candidate_writes.rs", "write_root_candidate_artifacts", &["path:std::mem::take"]),
    ("root-publication-anchor", "workspaces/worth-store/crates/worth-store-physical-backend/src/filesystem_media/artifact_tree/publication_effect/execution/root_protocol_replacement.rs", "ArtifactTreeMedia::replace_root_protocol", &["method:replacements.iter().map", "method:replacement.execute"]),
    ("root-publication-anchor", "workspaces/worth-store/crates/worth-store-recovery-runtime/src/orchestration/discovery/observation.rs", "observe_fallback_anchor", &["method:discovery.read_bootstrap_catalog", "path:BootstrapCatalog::decode"]),
    ("root-publication-anchor", "workspaces/worth-store/crates/worth-store-recovery-physics/src/source_precedence/current_previous_root.rs", "select_previous", &["method:anchor.current_root", "method:selector.linked_root_generation"]),
    ("root-publication-anchor", "workspaces/worth-store/crates/worth-store-recovery-runtime/tests/phase_three_root_anchor.rs", "torn_current_fallback_requires_the_exact_completed_publication_anchor", &["path:publish_previous_and_anchor", "path:expect_blocked"]),
    ("current-root-selector", "workspaces/worth-store/crates/worth-store/src/physical_runtime/record_serving/admission/initialization.rs", "initialize", &["path:DurableRootSelector::new", "method:artifacts.write_new"]),
    ("current-root-selector", "workspaces/worth-store/crates/worth-store/src/physical_runtime/record_serving/planning/rebased_root/assembly.rs", "assemble_rebased_publication", &["path:DurableRootSelector::new"]),
    ("current-root-selector", "workspaces/worth-store/crates/worth-store/src/physical_runtime/record_serving/publication/root_candidate_writes.rs", "write_root_candidate_artifacts", &["path:write_candidate", "path:std::mem::take"]),
    ("current-root-selector", "workspaces/worth-store/crates/worth-store-physical-backend/src/filesystem_media/artifact_tree/publication_effect/execution/root_protocol_replacement.rs", "ArtifactTreeMedia::replace_root_protocol", &["method:replacements.iter().map", "method:replacement.execute"]),
    ("current-root-selector", "workspaces/worth-store/crates/worth-store-physical-backend/src/recovery_media/publication.rs", "AdmittedRecoveryFilesystemMedia::replace_recovery_root_protocol_scheduled", &["method:plan.current_candidate", "method:self.parts.artifact_tree().replace_root_protocol_scheduled"]),
    ("current-root-selector", "workspaces/worth-store/crates/worth-store/src/physical_runtime/recovery_coordination/publication/execution.rs", "replace_root_protocol", &["method:media.replace_recovery_root_protocol_scheduled", "path:PerformedRecoveryPhysicalEffect::record_root_protocol"]),
    ("current-root-selector", "workspaces/worth-store/crates/worth-store/src/physical_runtime/recovery_coordination/reopen/execution.rs", "execute", &["path:DurableRootSelector::decode", "method:selector.store_identity"]),
    ("current-root-selector", "workspaces/worth-store/crates/worth-store-recovery-runtime/src/orchestration/reopen.rs", "reopen_recovery", &["path:PhysicalRecoveryFreshReopenCommand::new", "method:state.coordination.owner().execute_fresh_reopen"]),
    ("current-root-selector", "workspaces/worth-store/crates/worth-store/tests/physical_record_journeys/durability_admission/data_durability/root_projection_carriage.rs", "exact_settled_group_advances_only_after_replacement_and_namespace_durability", &["path:worth_store_physical_format::DurableRootSelector::decode"]),
    ("previous-root-selector", "workspaces/worth-store/crates/worth-store/src/physical_runtime/record_serving/planning/rebased_root/assembly.rs", "assemble_rebased_publication", &["path:DurableRootSelector::new"]),
    ("previous-root-selector", "workspaces/worth-store/crates/worth-store/src/physical_runtime/record_serving/publication/root_candidate_writes.rs", "write_root_candidate_artifacts", &["path:write_candidate", "path:std::mem::take"]),
    ("previous-root-selector", "workspaces/worth-store/crates/worth-store-physical-backend/src/filesystem_media/artifact_tree/publication_effect/execution/root_protocol_replacement.rs", "ArtifactTreeMedia::replace_root_protocol", &["method:replacements.iter().map", "method:replacement.execute"]),
    ("previous-root-selector", "workspaces/worth-store/crates/worth-store-physical-backend/src/recovery_media/publication.rs", "AdmittedRecoveryFilesystemMedia::replace_recovery_root_protocol_scheduled", &["method:plan.previous_candidate", "method:self.parts.artifact_tree().replace_root_protocol_scheduled"]),
    ("previous-root-selector", "workspaces/worth-store/crates/worth-store/src/physical_runtime/recovery_coordination/publication/execution.rs", "replace_root_protocol", &["method:media.replace_recovery_root_protocol_scheduled", "path:PerformedRecoveryPhysicalEffect::record_root_protocol"]),
    ("previous-root-selector", "workspaces/worth-store/crates/worth-store/tests/physical_record_journeys/durability_admission/data_durability/root_projection_carriage.rs", "exact_settled_group_advances_only_after_replacement_and_namespace_durability", &["path:worth_store_physical_format::DurableRootSelector::decode"]),
    ("root-manifest", "workspaces/worth-store/crates/worth-store-recovery-runtime/src/progression/planned/basis/derivation/closeout.rs", "seal", &["path:super::super::publication_candidate::build", "path:super::super::identity::bind_publication_candidates"]),
    ("root-manifest", "workspaces/worth-store/crates/worth-store-physical-backend/src/recovery_media/publication.rs", "AdmittedRecoveryFilesystemMedia::replace_recovery_root_protocol_scheduled", &["method:plan.current_candidate", "method:self.parts.artifact_tree().replace_root_protocol_scheduled"]),
    ("root-manifest", "workspaces/worth-store/crates/worth-store/src/physical_runtime/recovery_coordination/publication/execution.rs", "replace_root_protocol", &["method:media.replace_recovery_root_protocol_scheduled", "path:PerformedRecoveryPhysicalEffect::record_root_protocol"]),
    ("root-manifest", "workspaces/worth-store/crates/worth-store/src/physical_runtime/recovery_coordination/reopen/execution.rs", "execute", &["path:DurablePhysicalRootManifest::decode", "method:command.expected_root.node_capacity"]),
    ("root-manifest", "workspaces/worth-store/crates/worth-store-recovery-runtime/src/orchestration/reopen.rs", "reopen_recovery", &["method:expectation.recovered_root", "path:PhysicalRecoveryFreshReopenCommand::new"]),
    ("free-space-allocation-header", "workspaces/worth-store/crates/worth-store-physical-format/src/manifest/durable_free_space_header.rs", "DurableFreeSpaceManifestHeader::decode", &["path:Self::new", "path:crate::maximum_segment_manifest_pages"]),
    ("free-space-allocation-header", "workspaces/worth-store/crates/worth-store-physical-format/src/binary_format/record_membership_golden_bytes.rs", "membership_authority_artifacts_match_independent_golden_bytes", &["path:DurableFreeSpaceManifestHeader::new", "path:independent_frame"]),
    ("free-space-allocation-header", "workspaces/worth-store/crates/worth-store/src/physical_runtime/record_serving/admission/initialization.rs", "initialize", &["path:DurableFreeSpaceManifestHeader::new", "method:placement.segment_pages"]),
    ("free-space-allocation-header", "workspaces/worth-store/crates/worth-store/src/physical_runtime/record_serving/planning/free_space_projection.rs", "project_successor_free_space", &["method:segment.page_capacity", "path:plan_free_space_successor"]),
    ("free-space-allocation-header", "workspaces/worth-store/crates/worth-store/src/physical_runtime/record_serving/planning/free_space_routing/successor.rs", "plan_free_space_successor", &["path:DurableFreeSpaceManifestHeader::new", "method:request.segment_page_capacity"]),
    ("free-space-allocation-header", "workspaces/worth-store/crates/worth-store-recovery-runtime/src/orchestration/planning/page_observation/allocation_truth.rs", "admit_absent_targets", &["path:admit_inline_allocations", "method:header.segment_page_capacity"]),
    ("free-space-allocation-header", "workspaces/worth-store/crates/worth-store-recovery-runtime/src/orchestration/planning/page_observation/allocation_truth/inline_allocation.rs", "admit_inline_allocations", &["method:header.segment_page_capacity", "path:admit_new_segments"]),
    ("free-space-allocation-header", "workspaces/worth-store/crates/worth-store-recovery-physics/src/redo_replay/plan/allocation_truth.rs", "ImmutablePhysicalRedoPlan::admit_inline_allocation_truth", &["path:validate_inline_allocation_truth"]),
    ("free-space-allocation-header", "workspaces/worth-store/crates/worth-store-recovery-runtime/src/orchestration/planning/page_observation/allocation_truth/tests/capacity_tests.rs", "new_segments_fill_the_persisted_capacity_before_spilling", &["path:assert_admitted", "path:assert_rejected"]),
    ("checkpoint-binding-compaction", "mutation/idempotency/runtime_owner.rs", "PhysicalMutationBindingCompactionCutover::for_each_record", &["method:self.pending_ref", "method:self.pending_ref().for_each_record"]),
    ("checkpoint-binding-compaction", "checkpoint/publication.rs", "CreatedCheckpointCandidate::finish", &["method:binding_compaction.for_each_record", "method:encoder.encode_binding_record", "method:self.work.execute"]),
    ("checkpoint-binding-compaction", "checkpoint/reopen/binding_compaction.rs", "NamespaceDurablePhysicalBindingCompactionReopen::stream_records", &["method:tree.read_exact_at", "path:decode_checkpoint_binding_record", "callback:consume"]),
    ("wal-security-binding", "workspaces/worth-store/crates/worth-store-wal/src/artifact_store/segment_inventory/segment_inspection.rs", "inspect_verified_wal_segment", &["path:inspect_verified_wal_active_tail"]),
    ("wal-security-binding", "wal/group_reservation/member_planning.rs", "encode_member_payload", &["method:binding.encode_persisted", "path:write_field"]),
    ("wal-security-binding", "mutation/idempotency/persisted_binding/decoding.rs", "PersistedPhysicalMutationAttemptBinding::decode_from_wal_member", &["path:Self::decode"]),
    ("wal-security-binding", "workspaces/worth-store/crates/worth-store/src/physical_runtime/recovery_freshness/binding.rs", "sample_binding", &["path:decode_wal_member_payload", "path:PersistedPhysicalMutationAttemptBinding::decode_from_wal_member"]),
    ("checkpoint-security-binding", "workspaces/worth-store/crates/worth-store-physical-format/src/checkpoint/source.rs", "encode_header", &["method:source.security_binding"]),
    ("checkpoint-security-binding", "workspaces/worth-store/crates/worth-store-physical-format/src/checkpoint/record.rs", "decode_record", &["path:crc32c::checksum"]),
    ("checkpoint-security-binding", "workspaces/worth-store/crates/worth-store-physical-format/src/checkpoint/stream.rs", "CheckpointStreamEncoder::begin", &["path:encode_header", "path:encode_record"]),
    ("checkpoint-security-binding", "workspaces/worth-store/crates/worth-store-physical-format/src/checkpoint/inspection.rs", "inspect_checkpoint_stream", &["path:CheckpointStreamDecoder::begin", "method:binding_decoder.finish"]),
    ("checkpoint-security-binding", "checkpoint/capture.rs", "PhysicalCheckpointCaptureOwner::admit", &["path:PhysicalCheckpointSource::secured_concurrent"]),
    ("checkpoint-security-binding", "workspaces/worth-store/crates/worth-store/src/physical_runtime/recovery_freshness/binding.rs", "sample_binding", &["method:source.security_binding", "path:PhysicalBindingDecodingContext::new"]),
    ("operation-attempt-binding-wal", "mutation/idempotency/attempt_binding.rs", "PhysicalMutationAttemptBinding::encode_persisted", &["path:write_field"]),
    ("operation-attempt-binding-wal", "wal/group_reservation/member_planning.rs", "encode_member_payload", &["method:binding.encode_persisted", "path:write_field"]),
    ("operation-attempt-binding-wal", "wal/inventory/reopened_member.rs", "ReopenedPhysicalWalMember::decode_retained_frame", &["path:take_field"]),
    ("operation-attempt-binding-wal", "mutation/idempotency/persisted_binding.rs", "PersistedPhysicalMutationAttemptBinding::from_allocated", &["method:persisted.encode"]),
    ("operation-attempt-binding-wal", "mutation/idempotency/persisted_binding/decoding.rs", "PersistedPhysicalMutationAttemptBinding::decode_from_wal_member", &["path:Self::decode"]),
    ("operation-attempt-binding-wal", "mutation/idempotency/bootstrap.rs", "PhysicalIdempotencyRegistryRebuilder::consume_wal_member", &["method:member.persisted_binding", "path:super::PersistedPhysicalMutationAttemptBinding::decode_from_wal_member"]),
    ("operation-terminal-fate", "mutation/idempotency/fate/persisted.rs", "PersistedPhysicalMutationFate::encode", &["path:write_field"]),
    ("operation-terminal-fate", "mutation/idempotency/fate/persisted.rs", "PersistedPhysicalMutationFate::decode", &["path:Self::decode_completed", "path:Self::decode_indeterminate"]),
    ("operation-terminal-fate", "mutation/idempotency/binding_compaction/encoding.rs", "encode_terminal", &["path:encode_basis", "method:fate.encode"]),
    ("operation-terminal-fate", "mutation/idempotency/binding_compaction/decoding.rs", "DecodedPhysicalMutationBindingRecord::decode", &["path:PersistedPhysicalMutationFate::decode"]),
    ("operation-terminal-fate", "mutation/idempotency/binding_compaction.rs", "encode_retained_record", &["path:encode_terminal"]),
    ("operation-terminal-fate", "mutation/idempotency/bootstrap.rs", "PhysicalIdempotencyRegistryRebuilder::consume_compaction_record", &["path:DecodedPhysicalMutationBindingRecord::decode"]),
    ("operation-terminal-fate", "mutation/idempotency/runtime_owner.rs", "PhysicalMutationBindingCompactionCutover::for_each_record", &["method:self.pending_ref", "method:self.pending_ref().for_each_record"]),
    ("operation-terminal-fate", "checkpoint/publication.rs", "CreatedCheckpointCandidate::finish", &["method:binding_compaction.for_each_record", "method:encoder.encode_binding_record", "method:self.work.execute"]),
    ("operation-terminal-fate", "checkpoint/reopen/binding_compaction.rs", "NamespaceDurablePhysicalBindingCompactionReopen::stream_records", &["method:tree.read_exact_at", "path:decode_checkpoint_binding_record", "callback:consume"]),
    ("operation-binding-compaction-state", "mutation/idempotency/binding_compaction/encoding.rs", "encode_unsealed", &["path:encode_basis"]),
    ("operation-binding-compaction-state", "mutation/idempotency/binding_compaction/encoding.rs", "encode_group_sealed", &["path:encode_basis", "path:write_field"]),
    ("operation-binding-compaction-state", "mutation/idempotency/binding_compaction/encoding.rs", "encode_wal_bound", &["path:write_field"]),
    ("operation-binding-compaction-state", "mutation/idempotency/binding_compaction/decoding.rs", "DecodedPhysicalMutationBindingRecord::decode", &["path:decode_basis", "path:PersistedPhysicalMutationAttemptBinding::decode_from_compaction", "path:require_canonical"]),
    ("operation-binding-compaction-state", "mutation/idempotency/binding_compaction/decoding.rs", "decode_basis", &["path:decode_binding_basis"]),
    ("operation-binding-compaction-state", "mutation/idempotency/persisted_binding/decoding.rs", "PersistedPhysicalMutationAttemptBinding::decode_from_compaction", &["path:Self::decode"]),
    ("operation-binding-compaction-state", "mutation/idempotency/fate/persisted.rs", "PersistedPhysicalMutationFate::decode", &["path:Self::decode_completed", "path:Self::decode_indeterminate"]),
    ("operation-binding-compaction-state", "mutation/idempotency/binding_compaction.rs", "encode_retained_record", &["path:encode_unsealed", "path:encode_group_sealed", "path:encode_wal_bound"]),
    ("operation-binding-compaction-state", "mutation/idempotency/bootstrap.rs", "PhysicalIdempotencyRegistryRebuilder::consume_compaction_record", &["path:DecodedPhysicalMutationBindingRecord::decode"]),
    ("operation-binding-compaction-state", "mutation/idempotency/runtime_owner.rs", "PhysicalMutationBindingCompactionCutover::for_each_record", &["method:self.pending_ref", "method:self.pending_ref().for_each_record"]),
    ("operation-binding-compaction-state", "checkpoint/publication.rs", "CreatedCheckpointCandidate::finish", &["method:binding_compaction.for_each_record", "method:encoder.encode_binding_record", "method:self.work.execute"]),
    ("operation-binding-compaction-state", "checkpoint/reopen/binding_compaction.rs", "NamespaceDurablePhysicalBindingCompactionReopen::stream_records", &["method:tree.read_exact_at", "path:decode_checkpoint_binding_record", "callback:consume"]),
    ("canonical-redo-v3", "workspaces/worth-store/crates/worth-store/src/physical_runtime/durability/wal/canonical_redo.rs", "encode", &["method:projection.encode"]),
    ("canonical-redo-v3", "wal/group_reservation/member_planning.rs", "plan_member", &["path:recovery_projection", "path:CanonicalRedoRecords::from_prepared_records"]),
    ("canonical-redo-v3", "workspaces/worth-store/crates/worth-store-recovery-physics/src/redo_replay/plan/admission.rs", "admit_physical_redo_members", &["path:decode_physical_redo_member", "path:validate_projection_semantics", "path:validate_admitted_groups"]),
    ("canonical-redo-v3", "workspaces/worth-store/crates/worth-store-recovery-physics/src/redo_replay/plan/group_admission.rs", "validate_admitted_groups", &["path:validate_one_group"]),
    ("canonical-redo-v3", "workspaces/worth-store/crates/worth-store-recovery-physics/src/redo_replay/record.rs", "decode_member", &["path:PersistedPhysicalRecoveryProjection::decode", "path:validate_projection"]),
    ("canonical-redo-v3", "workspaces/worth-store/crates/worth-store-recovery-physics/src/redo_replay/record/target_decode.rs", "decode_targets", &["path:decode_target"]),
    ("canonical-redo-v3", "workspaces/worth-store/crates/worth-store-recovery-physics/src/redo_replay/plan_tests.rs", "legacy_redo_domains_cannot_masquerade_as_the_v3_projection_grammar", &["path:replace_first", "path:PhysicalRedoMemberInput::new"]),
    ("recovery-projection-v3", "wal/group_reservation/member_planning.rs", "recovery_projection", &["path:PersistedPhysicalRecoveryProjection::new"]),
    ("recovery-projection-v3", "workspaces/worth-store/crates/worth-store-physical-format/src/recovery_projection.rs", "PersistedPhysicalRecoveryProjection::new", &["path:unique", "path:strictly_ordered"]),
    ("recovery-projection-v3", "workspaces/worth-store/crates/worth-store-physical-format/src/recovery_projection/codec.rs", "PersistedPhysicalRecoveryProjection::decode", &["path:Cursor::new", "path:Self::new"]),
    ("recovery-projection-v3", "workspaces/worth-store/crates/worth-store-physical-format/src/recovery_projection/codec/cursor.rs", "Cursor::take", &["method:self.remaining.split_at_checked"]),
    ("recovery-projection-v3", "workspaces/worth-store/crates/worth-store-physical-format/src/recovery_projection/root_state.rs", "PersistedPhysicalRecoveryRootState::new", &["method:inline_allocations.windows"]),
    ("recovery-projection-v3", "workspaces/worth-store/crates/worth-store-recovery-physics/src/redo_replay/record/target_decode.rs", "decode_target", &["path:decode_inline_identity", "method:cursor.require_end"]),
    ("recovery-projection-v3", "workspaces/worth-store/crates/worth-store-recovery-physics/src/redo_replay/cursor.rs", "target_format_basis", &["method:target.artifact", "path:RecordFrameCoordinate::new"]),
    ("recovery-projection-v3", "workspaces/worth-store/crates/worth-store-recovery-physics/src/redo_replay/plan/projection_validation.rs", "validate_projection_semantics", &["path:projected_record_bytes", "path:validate_bidirectional_closure"]),
    ("recovery-projection-v3", "workspaces/worth-store/crates/worth-store-recovery-physics/src/redo_replay/plan/projection_materialization.rs", "projected_record_bytes", &["path:decode_inline_record", "path:decode_extent_chunk"]),
    ("recovery-projection-v3", "workspaces/worth-store/crates/worth-store-recovery-physics/src/redo_replay/plan/group_admission.rs", "validate_admitted_groups", &["path:validate_one_group"]),
    ("recovery-projection-v3", "workspaces/worth-store/crates/worth-store-recovery-physics/src/redo_replay/plan_tests/group_atomic.rs", "segment_update_page_count_must_equal_the_projected_segment_frames", &["path:PhysicalRedoMemberInput::new", "path:encoded_redo_with_segment_page_count"]),
    ("recovery-projection-v3", "workspaces/worth-store/crates/worth-store-recovery-physics/src/redo_replay/plan_tests/projection_mutants.rs", "projection_omission_and_foreign_entry_mutants_are_rejected", &["path:encoded_redo_with_projection_bytes", "path:mutated_projection_bytes"]),
    ("recovery-projection-v3", "workspaces/worth-store/crates/worth-store-recovery-physics/src/redo_replay/plan_tests.rs", "legacy_projection_domains_cannot_masquerade_as_the_v3_grammar", &["path:replace_first", "path:PhysicalRedoMemberInput::new"]),
    ("recovery-projection-v3", "workspaces/worth-store/crates/worth-store-recovery-physics/src/redo_replay/plan_tests.rs", "inline_page_and_segment_artifact_generations_remain_independent", &["path:projection_with_generations", "path:RecoveryPageObservation::absent"]),
    ("recovery-projection-v3", "workspaces/worth-store/crates/worth-store-recovery-runtime/src/orchestration/planning/page_observation/materialized.rs", "observe_inline", &["method:target.artifact", "path:RecoveryPageObservation::materialized"]),
    ("recovery-projection-v3", "workspaces/worth-store/crates/worth-store-recovery-runtime/src/progression/planned/basis/derivation/pending.rs", "admit", &["path:preflight_staging_cost"]),
    ("recovery-projection-v3", "workspaces/worth-store/crates/worth-store-recovery-runtime/src/progression/planned/basis/derivation/materialization.rs", "collect", &["method:projection.materialization"]),
    ("recovery-projection-v3", "workspaces/worth-store/crates/worth-store-recovery-runtime/tests/phase_four_process.rs", "phase_four_planner_process", &["path:admitted_recovery_with_limits", "method:planned.staging_layout"]),
    ("recovery-projection-v3", "workspaces/worth-store/crates/worth-store-recovery-runtime/tests/phase_five_generation_axes.rs", "phase_five_generation_axes_stager", &["method:decision.target().identity", "method:planned.stage"]),
];
