use super::{
    WorthQueryLowerRuntimeAuthorityOwner, WorthQueryLowerRuntimeCloseoutPosture,
    WorthQueryLowerRuntimeCloseoutRegistry, WorthQueryLowerRuntimeCloseoutRow,
    WorthQueryLowerRuntimeRouteKind, WorthQueryLowerRuntimeSeamKey,
};

const CLOSEOUT_ROWS: &[WorthQueryLowerRuntimeCloseoutRow] = &[
    WorthQueryLowerRuntimeCloseoutRow::new(
        WorthQueryLowerRuntimeSeamKey::RuntimeIntentModule,
        "Runtime intent module seam",
        WorthQueryLowerRuntimeCloseoutPosture::SeamEliminated,
        WorthQueryLowerRuntimeAuthorityOwner::Query,
        WorthQueryLowerRuntimeRouteKind::RoutePlanning,
        "phase-2 backend intent authority boundary ownership",
        "runtime/intent/mod.rs must remain free of direct lower-runtime authority imports",
        "phase-2-runtime-intent-elimination",
    ),
    WorthQueryLowerRuntimeCloseoutRow::new(
        WorthQueryLowerRuntimeSeamKey::StoreBackedRouteParityNeighbor,
        "Store-backed route parity",
        WorthQueryLowerRuntimeCloseoutPosture::DeferredNeighbor,
        WorthQueryLowerRuntimeAuthorityOwner::Store,
        WorthQueryLowerRuntimeRouteKind::RoutePlanning,
        "later store-backed route parity milestone",
        "fail deferred until worth-store owns the route-parity contract and replay evidence",
        "deferred-store-route-parity",
    ),
    WorthQueryLowerRuntimeCloseoutRow::new(
        WorthQueryLowerRuntimeSeamKey::DurableRouteReplayNeighbor,
        "Durable route replay",
        WorthQueryLowerRuntimeCloseoutPosture::DeferredNeighbor,
        WorthQueryLowerRuntimeAuthorityOwner::Store,
        WorthQueryLowerRuntimeRouteKind::RoutePlanning,
        "later durable route replay milestone",
        "fail deferred until durable replay binds persisted route evidence to the routing lifecycle",
        "deferred-durable-route-replay",
    ),
    WorthQueryLowerRuntimeCloseoutRow::new(
        WorthQueryLowerRuntimeSeamKey::PersistedBoundaryExecutionReceiptNeighbor,
        "Persisted boundary execution receipts",
        WorthQueryLowerRuntimeCloseoutPosture::DeferredNeighbor,
        WorthQueryLowerRuntimeAuthorityOwner::Store,
        WorthQueryLowerRuntimeRouteKind::RoutePlanning,
        "later persisted boundary artifact milestone",
        "fail deferred until persisted boundary receipts exist as store-owned artifacts",
        "deferred-persisted-boundary-receipts",
    ),
    WorthQueryLowerRuntimeCloseoutRow::new(
        WorthQueryLowerRuntimeSeamKey::RestartStableBoundaryEnvelopeReloadNeighbor,
        "Restart-stable boundary envelope reload",
        WorthQueryLowerRuntimeCloseoutPosture::DeferredNeighbor,
        WorthQueryLowerRuntimeAuthorityOwner::Store,
        WorthQueryLowerRuntimeRouteKind::ReadmissionHandoff,
        "later restart-stable envelope reload milestone",
        "fail deferred until restart-stable reload can read boundary envelopes without Query-side reenactment",
        "deferred-envelope-reload",
    ),
    WorthQueryLowerRuntimeCloseoutRow::new(
        WorthQueryLowerRuntimeSeamKey::TemporalQueryBasisRoutingNeighbor,
        "Temporal query basis routing",
        WorthQueryLowerRuntimeCloseoutPosture::DeferredNeighbor,
        WorthQueryLowerRuntimeAuthorityOwner::Query,
        WorthQueryLowerRuntimeRouteKind::RoutePlanning,
        "later temporal routing milestone",
        "fail deferred until temporal basis identity is admitted into the lower-runtime routing lifecycle",
        "deferred-temporal-routing",
    ),
    WorthQueryLowerRuntimeCloseoutRow::new(
        WorthQueryLowerRuntimeSeamKey::AsyncResourceRoutingNeighbor,
        "Async/resource routing",
        WorthQueryLowerRuntimeCloseoutPosture::DeferredNeighbor,
        WorthQueryLowerRuntimeAuthorityOwner::Query,
        WorthQueryLowerRuntimeRouteKind::RoutePlanning,
        "later async/resource routing milestone",
        "fail deferred until async/resource authorities have a named lower-runtime route family",
        "deferred-async-resource-routing",
    ),
    WorthQueryLowerRuntimeCloseoutRow::new(
        WorthQueryLowerRuntimeSeamKey::MixedTruthTimeAsyncRoutingNeighbor,
        "Mixed truth/time/async routing",
        WorthQueryLowerRuntimeCloseoutPosture::DeferredNeighbor,
        WorthQueryLowerRuntimeAuthorityOwner::Query,
        WorthQueryLowerRuntimeRouteKind::RoutePlanning,
        "later mixed-cause routing milestone",
        "fail deferred until mixed truth/time/async composition has one typed route-planning model",
        "deferred-mixed-routing",
    ),
    WorthQueryLowerRuntimeCloseoutRow::new(
        WorthQueryLowerRuntimeSeamKey::FinalDeferredCertificationClosureNeighbor,
        "Final temporal/async/store/durable certification closure",
        WorthQueryLowerRuntimeCloseoutPosture::DeferredNeighbor,
        WorthQueryLowerRuntimeAuthorityOwner::Query,
        WorthQueryLowerRuntimeRouteKind::RoutePlanning,
        "later cross-neighbor certification milestone",
        "fail deferred until later milestones can certify parity and boundary honesty for the deferred neighbors",
        "deferred-final-certification-closure",
    ),
];

pub fn worth_query_lower_runtime_closeout_registry() -> WorthQueryLowerRuntimeCloseoutRegistry {
    WorthQueryLowerRuntimeCloseoutRegistry::new(CLOSEOUT_ROWS)
}
