use super::crossing_types::{
    WorthQueryLowerRuntimeArtifactStrength, WorthQueryLowerRuntimeAuthorityOwner,
    WorthQueryLowerRuntimeCrossingClassification, WorthQueryLowerRuntimeCrossingInventory,
    WorthQueryLowerRuntimeCrossingRow, WorthQueryLowerRuntimeRouteKind,
    WorthQueryLowerRuntimeSeamKey,
};

const CROSSING_ROWS: &[WorthQueryLowerRuntimeCrossingRow] = &[
    WorthQueryLowerRuntimeCrossingRow::new(
        WorthQueryLowerRuntimeSeamKey::ComposeRead,
        "Composed current read",
        "WorthQueryWorkspace::compose_read(...)",
        WorthQueryLowerRuntimeCrossingClassification::CanonicalLowerRuntimeReuse,
        WorthQueryLowerRuntimeRouteKind::RoutePlanning,
        WorthQueryLowerRuntimeAuthorityOwner::RuntimeBridge,
        WorthQueryLowerRuntimeArtifactStrength::TypedReceipt,
        "delegate through the current-read route row; no side-door execution",
    ),
    WorthQueryLowerRuntimeCrossingRow::new(
        WorthQueryLowerRuntimeSeamKey::ComposeReadWithInvariantPack,
        "Composed current read with invariant pack",
        "WorthQueryWorkspace::compose_read_with_invariant_pack(...)",
        WorthQueryLowerRuntimeCrossingClassification::CanonicalLowerRuntimeReuse,
        WorthQueryLowerRuntimeRouteKind::RoutePlanning,
        WorthQueryLowerRuntimeAuthorityOwner::RuntimeBridge,
        WorthQueryLowerRuntimeArtifactStrength::TypedReceipt,
        "delegate through the current-read route row after invariant admission",
    ),
    WorthQueryLowerRuntimeCrossingRow::new(
        WorthQueryLowerRuntimeSeamKey::ExecuteReadFamily,
        "Defined read-family execution",
        "WorthQueryWorkspace::execute_read_family(...)",
        WorthQueryLowerRuntimeCrossingClassification::CanonicalLowerRuntimeReuse,
        WorthQueryLowerRuntimeRouteKind::RoutePlanning,
        WorthQueryLowerRuntimeAuthorityOwner::RuntimeBridge,
        WorthQueryLowerRuntimeArtifactStrength::TypedReceipt,
        "delegate through the current-read route row",
    ),
    WorthQueryLowerRuntimeCrossingRow::new(
        WorthQueryLowerRuntimeSeamKey::ExecuteReadFamilyInBasisContext,
        "Basis-context read-family execution",
        "WorthQueryWorkspace::execute_read_family_in_basis_context(...)",
        WorthQueryLowerRuntimeCrossingClassification::CanonicalLowerRuntimeReuse,
        WorthQueryLowerRuntimeRouteKind::RoutePlanning,
        WorthQueryLowerRuntimeAuthorityOwner::RuntimeBridge,
        WorthQueryLowerRuntimeArtifactStrength::TypedReceipt,
        "delegate through the basis-context route row",
    ),
    WorthQueryLowerRuntimeCrossingRow::new(
        WorthQueryLowerRuntimeSeamKey::ExecuteRuntimeCurrentReadGraph,
        "Current read execution",
        "runtime/workspace_queries.rs -> execute_runtime_current_read_graph(...)",
        WorthQueryLowerRuntimeCrossingClassification::CanonicalLowerRuntimeReuse,
        WorthQueryLowerRuntimeRouteKind::RoutePlanning,
        WorthQueryLowerRuntimeAuthorityOwner::RuntimeBridge,
        WorthQueryLowerRuntimeArtifactStrength::TypedReceipt,
        "add route plan, receipt, and boundary envelope",
    ),
    WorthQueryLowerRuntimeCrossingRow::new(
        WorthQueryLowerRuntimeSeamKey::ExecuteRuntimeBasisContextReadGraph,
        "Basis-context read execution",
        "runtime/workspace_queries.rs -> execute_runtime_basis_context_read_graph(...)",
        WorthQueryLowerRuntimeCrossingClassification::CanonicalLowerRuntimeReuse,
        WorthQueryLowerRuntimeRouteKind::RoutePlanning,
        WorthQueryLowerRuntimeAuthorityOwner::RuntimeBridge,
        WorthQueryLowerRuntimeArtifactStrength::TypedReceipt,
        "add route plan, receipt, and boundary envelope",
    ),
    WorthQueryLowerRuntimeCrossingRow::new(
        WorthQueryLowerRuntimeSeamKey::PublicLiveViewDeclaration,
        "Public live view declaration",
        "WorthQueryWorkspace::live_view(...) and live_view_request(...)",
        WorthQueryLowerRuntimeCrossingClassification::QueryBoundaryAdapter,
        WorthQueryLowerRuntimeRouteKind::RoutePlanning,
        WorthQueryLowerRuntimeAuthorityOwner::Query,
        WorthQueryLowerRuntimeArtifactStrength::DerivedAggregateArtifact,
        "delegate through live declaration and live installation route rows",
    ),
    WorthQueryLowerRuntimeCrossingRow::new(
        WorthQueryLowerRuntimeSeamKey::LiveViewSchemaAdmission,
        "Live view schema admission",
        "WorthQueryRuntimeSchemaAdapter::admit_live_view(...)",
        WorthQueryLowerRuntimeCrossingClassification::QueryBoundaryAdapter,
        WorthQueryLowerRuntimeRouteKind::ReadmissionHandoff,
        WorthQueryLowerRuntimeAuthorityOwner::Query,
        WorthQueryLowerRuntimeArtifactStrength::TypedReceipt,
        "return LiveViewDeclarationAdmissionReceipt and bind it into the declaration route proof",
    ),
    WorthQueryLowerRuntimeCrossingRow::new(
        WorthQueryLowerRuntimeSeamKey::LiveViewSourceDeclaration,
        "Live view source declaration",
        "WorthQueryRuntimeSourceAdapter::declare_live_view(...)",
        WorthQueryLowerRuntimeCrossingClassification::QueryBoundaryAdapter,
        WorthQueryLowerRuntimeRouteKind::RoutePlanning,
        WorthQueryLowerRuntimeAuthorityOwner::Query,
        WorthQueryLowerRuntimeArtifactStrength::TypedReceipt,
        "bind route plan + declaration receipt + envelope",
    ),
    WorthQueryLowerRuntimeCrossingRow::new(
        WorthQueryLowerRuntimeSeamKey::RuntimeLiveInstallationOrchestration,
        "Runtime live installation orchestration",
        "WorthQueryRuntime::install_live_subscription_for_request(...)",
        WorthQueryLowerRuntimeCrossingClassification::QueryBoundaryAdapter,
        WorthQueryLowerRuntimeRouteKind::RoutePlanning,
        WorthQueryLowerRuntimeAuthorityOwner::Query,
        WorthQueryLowerRuntimeArtifactStrength::DerivedAggregateArtifact,
        "emit installation boundary envelope composed from declaration, activation, and continuity rows",
    ),
    WorthQueryLowerRuntimeCrossingRow::new(
        WorthQueryLowerRuntimeSeamKey::RuntimeIntentAuthorityAdapter,
        "Runtime intent authority seam",
        "WorthQueryIntentAuthorityAdapter::execute_intent(...)",
        WorthQueryLowerRuntimeCrossingClassification::QueryBoundaryAdapter,
        WorthQueryLowerRuntimeRouteKind::RoutePlanning,
        WorthQueryLowerRuntimeAuthorityOwner::Query,
        WorthQueryLowerRuntimeArtifactStrength::TypedReceipt,
        "treat this as an allowed backend-boundary seam, not silent leakage",
    ),
    WorthQueryLowerRuntimeCrossingRow::new(
        WorthQueryLowerRuntimeSeamKey::SubscriptionActivation,
        "Subscription activation",
        "WorthQueryRuntimeSubscriptionActivationAdapter::admit_activation(...)",
        WorthQueryLowerRuntimeCrossingClassification::QueryBoundaryAdapter,
        WorthQueryLowerRuntimeRouteKind::RoutePlanning,
        WorthQueryLowerRuntimeAuthorityOwner::Query,
        WorthQueryLowerRuntimeArtifactStrength::TypedReceipt,
        "return SubscriptionActivationReceipt and bind activation/support evidence into the installation route proof",
    ),
    WorthQueryLowerRuntimeCrossingRow::new(
        WorthQueryLowerRuntimeSeamKey::SubscriptionContinuity,
        "Subscription continuity",
        "bridge continuity and Query continuation surfaces",
        WorthQueryLowerRuntimeCrossingClassification::CanonicalLowerRuntimeReuse,
        WorthQueryLowerRuntimeRouteKind::RoutePlanning,
        WorthQueryLowerRuntimeAuthorityOwner::RuntimeBridge,
        WorthQueryLowerRuntimeArtifactStrength::TypedAuthoritativeArtifact,
        "route through bridge continuity artifacts and include continuity route envelope",
    ),
    WorthQueryLowerRuntimeCrossingRow::new(
        WorthQueryLowerRuntimeSeamKey::PreviewBasisAdmission,
        "Preview basis admission",
        "WorthQueryRuntimePreviewBasisAdapter::admit_preview_basis(...)",
        WorthQueryLowerRuntimeCrossingClassification::QueryBoundaryAdapter,
        WorthQueryLowerRuntimeRouteKind::ReadmissionHandoff,
        WorthQueryLowerRuntimeAuthorityOwner::Query,
        WorthQueryLowerRuntimeArtifactStrength::TypedReceipt,
        "include boundary envelope but no new lower-runtime contract",
    ),
    WorthQueryLowerRuntimeCrossingRow::new(
        WorthQueryLowerRuntimeSeamKey::BasisReadmissionFromTruthViewEvidence,
        "Basis readmission from truth-view evidence",
        "basis_lifecycle::readmit_lower_runtime_evidence truth-view readmission",
        WorthQueryLowerRuntimeCrossingClassification::CanonicalLowerRuntimeReuse,
        WorthQueryLowerRuntimeRouteKind::ReadmissionHandoff,
        WorthQueryLowerRuntimeAuthorityOwner::RuntimeBridge,
        WorthQueryLowerRuntimeArtifactStrength::TypedReceipt,
        "keep current readmission pattern; add 9.3.6 envelope coverage",
    ),
    WorthQueryLowerRuntimeCrossingRow::new(
        WorthQueryLowerRuntimeSeamKey::BasisReadmissionFromSubscriptionEvidence,
        "Basis readmission from subscription evidence",
        "basis_lifecycle::readmit_lower_runtime_evidence subscription declaration/activation readmission",
        WorthQueryLowerRuntimeCrossingClassification::CanonicalLowerRuntimeReuse,
        WorthQueryLowerRuntimeRouteKind::ReadmissionHandoff,
        WorthQueryLowerRuntimeAuthorityOwner::RuntimeBridge,
        WorthQueryLowerRuntimeArtifactStrength::TypedReceipt,
        "keep current readmission pattern; add 9.3.6 envelope coverage",
    ),
    WorthQueryLowerRuntimeCrossingRow::new(
        WorthQueryLowerRuntimeSeamKey::HistoricalBridgeLowering,
        "Historical policy lowering",
        "historical/bridge_lowering.rs",
        WorthQueryLowerRuntimeCrossingClassification::QueryBoundaryAdapter,
        WorthQueryLowerRuntimeRouteKind::RoutePlanning,
        WorthQueryLowerRuntimeAuthorityOwner::RuntimeBridge,
        WorthQueryLowerRuntimeArtifactStrength::TypedReceipt,
        "keep adapter; bind to route plan and envelope",
    ),
    WorthQueryLowerRuntimeCrossingRow::new(
        WorthQueryLowerRuntimeSeamKey::EffectBackedRelationalMutation,
        "Effect-backed relational mutation",
        "effect_lifecycle/execution.rs mutation path",
        WorthQueryLowerRuntimeCrossingClassification::CanonicalLowerRuntimeReuse,
        WorthQueryLowerRuntimeRouteKind::RoutePlanning,
        WorthQueryLowerRuntimeAuthorityOwner::Relational,
        WorthQueryLowerRuntimeArtifactStrength::TypedReceipt,
        "keep path; add route receipt/envelope",
    ),
    WorthQueryLowerRuntimeCrossingRow::new(
        WorthQueryLowerRuntimeSeamKey::EffectBackedRelationalMerge,
        "Effect-backed relational merge",
        "effect_lifecycle/execution.rs merge path",
        WorthQueryLowerRuntimeCrossingClassification::CanonicalLowerRuntimeReuse,
        WorthQueryLowerRuntimeRouteKind::RoutePlanning,
        WorthQueryLowerRuntimeAuthorityOwner::Relational,
        WorthQueryLowerRuntimeArtifactStrength::TypedReceipt,
        "keep path; add route receipt/envelope",
    ),
    WorthQueryLowerRuntimeCrossingRow::new(
        WorthQueryLowerRuntimeSeamKey::EffectBackedBridgeWriteback,
        "Effect-backed bridge writeback",
        "effect_lifecycle/execution_bridge.rs",
        WorthQueryLowerRuntimeCrossingClassification::QueryBoundaryAdapter,
        WorthQueryLowerRuntimeRouteKind::RoutePlanning,
        WorthQueryLowerRuntimeAuthorityOwner::RuntimeBridge,
        WorthQueryLowerRuntimeArtifactStrength::TypedReceipt,
        "keep adapter thin over the bridge admitted writeback execution contract",
    ),
    WorthQueryLowerRuntimeCrossingRow::new(
        WorthQueryLowerRuntimeSeamKey::WriteAuthorityBackendExecution,
        "Write authority backend execution",
        "WorthQueryRuntimeWriteAuthorityAdapter::write(...)",
        WorthQueryLowerRuntimeCrossingClassification::QueryBoundaryAdapter,
        WorthQueryLowerRuntimeRouteKind::RoutePlanning,
        WorthQueryLowerRuntimeAuthorityOwner::Query,
        WorthQueryLowerRuntimeArtifactStrength::TypedReceipt,
        "return typed WriteAuthorityExecutionReceipt",
    ),
    WorthQueryLowerRuntimeCrossingRow::new(
        WorthQueryLowerRuntimeSeamKey::SignalInvalidationRouting,
        "Signal invalidation routing",
        "WorthQueryRuntimeSignalSinkAdapter::route_write_receipt(...)",
        WorthQueryLowerRuntimeCrossingClassification::QueryBoundaryAdapter,
        WorthQueryLowerRuntimeRouteKind::RoutePlanning,
        WorthQueryLowerRuntimeAuthorityOwner::Query,
        WorthQueryLowerRuntimeArtifactStrength::TypedReceipt,
        "return SignalInvalidationRoutingReceipt and bind write routing width into the boundary proof",
    ),
    WorthQueryLowerRuntimeCrossingRow::new(
        WorthQueryLowerRuntimeSeamKey::IntentRuntimeExecution,
        "Intent runtime execution",
        "WorthQueryRuntimeBackend::execute_intent(...) via installed intent_authority",
        WorthQueryLowerRuntimeCrossingClassification::QueryBoundaryAdapter,
        WorthQueryLowerRuntimeRouteKind::RoutePlanning,
        WorthQueryLowerRuntimeAuthorityOwner::Query,
        WorthQueryLowerRuntimeArtifactStrength::TypedReceipt,
        "mark conditionally supported; return boundary receipt/envelope for execution",
    ),
    WorthQueryLowerRuntimeCrossingRow::new(
        WorthQueryLowerRuntimeSeamKey::ProjectionSourceIntakeFromQueryReceipts,
        "Projection source intake from Query receipts",
        "projection_consumption/source.rs from read/write/query-context receipts",
        WorthQueryLowerRuntimeCrossingClassification::QueryBoundaryAdapter,
        WorthQueryLowerRuntimeRouteKind::ReadmissionHandoff,
        WorthQueryLowerRuntimeAuthorityOwner::Query,
        WorthQueryLowerRuntimeArtifactStrength::TypedAuthoritativeArtifact,
        "keep adapter; include source boundary envelope",
    ),
    WorthQueryLowerRuntimeCrossingRow::new(
        WorthQueryLowerRuntimeSeamKey::ProjectionSourceIntakeFromRelationalArtifacts,
        "Projection source intake from relational artifacts",
        "projection_consumption/source.rs relational row/grouped artifacts",
        WorthQueryLowerRuntimeCrossingClassification::QueryBoundaryAdapter,
        WorthQueryLowerRuntimeRouteKind::ReadmissionHandoff,
        WorthQueryLowerRuntimeAuthorityOwner::Relational,
        WorthQueryLowerRuntimeArtifactStrength::TypedAuthoritativeArtifact,
        "keep adapter; no new lower-runtime contract required",
    ),
    WorthQueryLowerRuntimeCrossingRow::new(
        WorthQueryLowerRuntimeSeamKey::ProjectionSourceIntakeFromBridgeArtifacts,
        "Projection source intake from bridge artifacts",
        "projection_consumption/source.rs bridge row/grouped artifacts",
        WorthQueryLowerRuntimeCrossingClassification::QueryBoundaryAdapter,
        WorthQueryLowerRuntimeRouteKind::ReadmissionHandoff,
        WorthQueryLowerRuntimeAuthorityOwner::RuntimeBridge,
        WorthQueryLowerRuntimeArtifactStrength::TypedAuthoritativeArtifact,
        "keep adapter; no new lower-runtime contract required",
    ),
    WorthQueryLowerRuntimeCrossingRow::new(
        WorthQueryLowerRuntimeSeamKey::CausalBridgeMaterialization,
        "Causal bridge materialization",
        "runtime/inspection/causal/builder_bridge.rs",
        WorthQueryLowerRuntimeCrossingClassification::QueryBoundaryAdapter,
        WorthQueryLowerRuntimeRouteKind::RoutePlanning,
        WorthQueryLowerRuntimeAuthorityOwner::RuntimeBridge,
        WorthQueryLowerRuntimeArtifactStrength::TypedEnvelope,
        "keep adapter; include route/receipt/envelope",
    ),
    WorthQueryLowerRuntimeCrossingRow::new(
        WorthQueryLowerRuntimeSeamKey::FrontierEvidenceIntake,
        "Frontier evidence intake",
        "frontier_signal_adapter.rs",
        WorthQueryLowerRuntimeCrossingClassification::QueryBoundaryAdapter,
        WorthQueryLowerRuntimeRouteKind::RoutePlanning,
        WorthQueryLowerRuntimeAuthorityOwner::Signal,
        WorthQueryLowerRuntimeArtifactStrength::TypedReceipt,
        "consume signal facade frontier route receipts without specialist imports",
    ),
];

pub fn worth_query_lower_runtime_crossing_inventory() -> WorthQueryLowerRuntimeCrossingInventory {
    WorthQueryLowerRuntimeCrossingInventory::new(CROSSING_ROWS)
}
