#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum S8StrategyDenial {
    UnsupportedFamily,
    FamilyDoesNotMatchKeyDomain,
    FamilyDoesNotMatchLifecycleAdmission,
    PhysicalKeyDomainDoesNotSupportBaselineBTree,
    PhysicalKeyDomainDoesNotSupportBaselineLsm,
    InvariantSuiteNotAvailableForFamily,
    ComparatorOrderViolation,
    RangeOrPrefixLawRequired,
    SearchPathViolation,
    OccupancyViolation,
    ChecksumLocalizationViolation,
    SiblingLinkViolation,
    TombstonePostureViolation,
    StableReadViolation,
    RootPublicationViolation,
    RecoveryReplayViolation,
    RebuildMigrationViolation,
    ManifestUpdateViolation,
    MergeOrderingViolation,
    TombstonePreservationViolation,
    CompactionOrderingViolation,
    AdvisoryFilterPostureViolation,
    StaleRunCleanupViolation,
    WriteAmplificationViolation,
    CounterExpectationViolation,
}
