pub(in super::super) fn compose_support_report_identity(
    report: &crate::application::WorthQuerySupportReport,
) -> crate::WorthQueryEvidenceIdentity {
    crate::WorthQueryEvidenceIdentity::compose(
        crate::WorthQueryEvidenceScope::ApplicationSupportReport,
    )
    .field_value(
        crate::WorthQueryEvidenceTag::new("support_matrix_digest"),
        report.support_matrix().support_matrix_digest(),
    )
    .field_value(
        crate::WorthQueryEvidenceTag::new("validated_config_digest"),
        report.validated_config_digest(),
    )
    .field_usize(
        crate::WorthQueryEvidenceTag::new("admitted_capability_count"),
        report.admitted_capability_count(),
    )
    .field_usize(
        crate::WorthQueryEvidenceTag::new("deferred_capability_count"),
        report.deferred_capability_count(),
    )
    .field_usize(
        crate::WorthQueryEvidenceTag::new("unsupported_capability_count"),
        report.unsupported_capability_count(),
    )
    .field_value_sequence(
        crate::WorthQueryEvidenceTag::new("admitted_capability_family"),
        report
            .admitted_capability_families()
            .iter()
            .map(crate::application::WorthQueryCapabilityFamily::as_str),
    )
    .field_value_sequence(
        crate::WorthQueryEvidenceTag::new("deferred_capability_family"),
        report
            .deferred_capability_families()
            .iter()
            .map(crate::application::WorthQueryCapabilityFamily::as_str),
    )
    .field_value_sequence(
        crate::WorthQueryEvidenceTag::new("unsupported_capability_family"),
        report
            .unsupported_capability_families()
            .iter()
            .map(crate::application::WorthQueryCapabilityFamily::as_str),
    )
    .field_value_sequence(
        crate::WorthQueryEvidenceTag::new("section_posture_digest"),
        report
            .section_postures()
            .iter()
            .map(crate::application::WorthQuerySupportSectionPosture::posture_digest),
    )
    .optional_value(
        crate::WorthQueryEvidenceTag::new("query_composition_profile_digest"),
        report
            .query_composition_support_profile()
            .map(crate::application::WorthQueryQueryCompositionSupportProfile::profile_digest),
    )
    .optional_value(
        crate::WorthQueryEvidenceTag::new("query_context_profile_digest"),
        report
            .query_context_support_profile()
            .map(crate::application::WorthQueryQueryContextSupportProfile::profile_digest),
    )
    .optional_value(
        crate::WorthQueryEvidenceTag::new("identity_evolution_profile_digest"),
        report
            .identity_evolution_support_profile()
            .map(crate::application::WorthQueryIdentityEvolutionSupportProfile::profile_digest),
    )
    .field_value(
        crate::WorthQueryEvidenceTag::new("identity_boundary_closure_digest"),
        report.identity_boundary_closure().closure_digest(),
    )
    .field_usize(
        crate::WorthQueryEvidenceTag::new("support_report_generation_count"),
        report.counters().support_report_generation_count(),
    )
    .seal()
}
