#[test]
fn topo_public_boundary_rejects_internal_runtime_bypass() {
    let t = trybuild::TestCases::new();
    let compile_fail = "src/certification/public_facade_contracts/compile_fail";
    t.compile_fail(format!("{compile_fail}/private_stage_helper.rs"));
    t.compile_fail(format!("{compile_fail}/mint_materialized_topology_view.rs"));
    t.compile_fail(format!("{compile_fail}/mint_boundary_envelope.rs"));
    t.compile_fail(format!("{compile_fail}/mint_boundary_failure.rs"));
    t.compile_fail(format!(
        "{compile_fail}/public_query_assembly_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_runtime_adapters_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_topology_operator_runner_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_milestone_one_read_view_cert_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_milestone_two_read_view_cert_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_runtime_constructor_requires_adapters.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_query_import_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_query_row_materializer_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_query_row_helpers_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_topology_construction_authority_constructor_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_runtime_read_family_support_row_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_runtime_edit_family_support_row_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_runtime_edit_lane_support_row_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_runtime_posture_row_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_runtime_removed_edit_execution_supported_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_runtime_removed_edit_lane_string_support_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_runtime_removed_current_head_live_reads_supported_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_runtime_removed_historical_basis_supported_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_runtime_closeout_row_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_domain_query_request_report_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_domain_query_closeout_report_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_domain_query_closeout_row_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_no_n_plus_one_contract_row_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_milestone_three_topology_edit_digest_row_not_forgeable.rs"
    ));
}




