#[test]
fn topo_public_boundary_rejects_internal_runtime_bypass() {
    let t = trybuild::TestCases::new();
    let compile_fail = "src/certification/public_facade_contracts/compile_fail";
    t.compile_fail(format!("{compile_fail}/private_stage_helper.rs"));
    t.compile_fail(format!("{compile_fail}/mint_materialized_topology_view.rs"));
    t.compile_fail(format!("{compile_fail}/mint_boundary_envelope.rs"));
    t.compile_fail(format!("{compile_fail}/mint_boundary_failure.rs"));
    t.compile_fail(format!(
        "{compile_fail}/public_runtime_adapters_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_topology_mutation_application_runner_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_milestone_one_read_view_cert_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_milestone_two_read_view_cert_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_runtime_constructor_requires_adapters.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_query_row_materializer_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_query_row_helpers_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_derived_diagnostics_builders_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_projection_surface_entry_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_topology_construction_authority_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_topology_construction_stepwise_lowering_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_topology_construction_stepwise_execution_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_topology_construction_stepwise_certification_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_topology_construction_fact_report_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_topology_construction_boundary_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_topology_construction_boundary_preparation_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_runtime_read_family_support_row_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_runtime_mutation_family_support_row_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_runtime_mutation_lane_support_row_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_runtime_posture_row_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_runtime_removed_mutation_lane_string_support_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_runtime_removed_current_head_live_reads_supported_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_runtime_removed_historical_basis_supported_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_runtime_closeout_row_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_topology_read_request_report_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_topology_read_closeout_report_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_topology_read_closeout_row_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_no_n_plus_one_contract_row_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_milestone_three_topology_mutation_digest_row_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_topology_query_domain_entry_constructors_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_topology_query_domain_entry_not_exported_from_facade.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_topology_query_domain_entry_not_exported_from_projection.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_bridge_registration_entry_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_runtime_builder_not_exported_from_facade.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_topology_read_workspace_methods_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_topology_reads_not_exported_from_facade.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_removed_domain_query_read_names_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_topology_committed_artifact_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_verified_topology_commit_cert_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_topology_declaration_entry_stop_class_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_topology_declaration_entry_refusal_class_not_exported.rs"
    ));
}
