pub(super) const BACKEND_WAL_DURABILITY_DESTINATION_SURFACES: &[(&str, &str, &str)] = &[
    // The destination owner is the concrete backend source module, matching
    // the shipped backend facade's associated-surface owner derivation.
    (
        "WalAppendObservationScope",
        "worth-store-physical-backend/recovery-durability/wal-recovery-basis/append-receipt",
        "phase-8",
    ),
    (
        "WalAppendObservationScope::new",
        "worth-store-physical-backend/recovery-durability/wal-recovery-basis/append-receipt",
        "phase-8",
    ),
    (
        "WalAppendReceipt",
        "worth-store-physical-backend/recovery-durability/wal-recovery-basis/append-receipt",
        "phase-8",
    ),
    (
        "WalAppendReceipt::completed_barriers",
        "worth-store-physical-backend/recovery-durability/wal-recovery-basis/append-receipt",
        "phase-8",
    ),
    (
        "WalAppendReceipt::expected_bytes",
        "worth-store-physical-backend/recovery-durability/wal-recovery-basis/append-receipt",
        "phase-8",
    ),
    (
        "WalAppendReceipt::frame_digest",
        "worth-store-physical-backend/recovery-durability/wal-recovery-basis/append-receipt",
        "phase-8",
    ),
    (
        "WalAppendReceipt::generation",
        "worth-store-physical-backend/recovery-durability/wal-recovery-basis/append-receipt",
        "phase-8",
    ),
    (
        "WalAppendReceipt::lsn_range",
        "worth-store-physical-backend/recovery-durability/wal-recovery-basis/append-receipt",
        "phase-8",
    ),
    (
        "WalAppendReceipt::observed_bytes",
        "worth-store-physical-backend/recovery-durability/wal-recovery-basis/append-receipt",
        "phase-8",
    ),
    (
        "WalAppendReceipt::profile_id",
        "worth-store-physical-backend/recovery-durability/wal-recovery-basis/append-receipt",
        "phase-8",
    ),
    (
        "WalAppendReceipt::required_barriers",
        "worth-store-physical-backend/recovery-durability/wal-recovery-basis/append-receipt",
        "phase-8",
    ),
    (
        "WalAppendReceipt::segment_id",
        "worth-store-physical-backend/recovery-durability/wal-recovery-basis/append-receipt",
        "phase-8",
    ),
    (
        "WalDurabilityObservation",
        "worth-store-physical-backend/recovery-durability/wal-recovery-basis/durability-observation",
        "phase-8",
    ),
    (
        "WalDurabilityObservation::basis",
        "worth-store-physical-backend/recovery-durability/wal-recovery-basis/durability-observation",
        "phase-8",
    ),
    (
        "WalDurabilityObservation::from_append_receipt",
        "worth-store-physical-backend/recovery-durability/wal-recovery-basis/durability-observation",
        "phase-8",
    ),
    (
        "WalDurabilityObservation::profile_id",
        "worth-store-physical-backend/recovery-durability/wal-recovery-basis/durability-observation",
        "phase-8",
    ),
    (
        "WalDurabilityObservationBasis",
        "worth-store-physical-backend/recovery-durability/wal-recovery-basis/durability-observation",
        "phase-8",
    ),
    (
        "WalDurabilityObservationBasis::completed_barriers",
        "worth-store-physical-backend/recovery-durability/wal-recovery-basis/durability-observation",
        "phase-8",
    ),
    (
        "WalDurabilityObservationBasis::frame_digest",
        "worth-store-physical-backend/recovery-durability/wal-recovery-basis/durability-observation",
        "phase-8",
    ),
    (
        "WalDurabilityObservationBasis::generation",
        "worth-store-physical-backend/recovery-durability/wal-recovery-basis/durability-observation",
        "phase-8",
    ),
    (
        "WalDurabilityObservationBasis::lsn_range",
        "worth-store-physical-backend/recovery-durability/wal-recovery-basis/durability-observation",
        "phase-8",
    ),
    (
        "WalDurabilityObservationBasis::profile_id",
        "worth-store-physical-backend/recovery-durability/wal-recovery-basis/durability-observation",
        "phase-8",
    ),
    (
        "WalDurabilityObservationBasis::required_barriers",
        "worth-store-physical-backend/recovery-durability/wal-recovery-basis/durability-observation",
        "phase-8",
    ),
    (
        "WalDurabilityObservationBasis::segment_id",
        "worth-store-physical-backend/recovery-durability/wal-recovery-basis/durability-observation",
        "phase-8",
    ),
    (
        "WalDurabilityObservationDenial",
        "worth-store-physical-backend/recovery-durability/wal-recovery-basis/durability-observation",
        "phase-8",
    ),
    (
        "WalDurabilityObservationDenial::barrier",
        "worth-store-physical-backend/recovery-durability/wal-recovery-basis/durability-observation",
        "phase-8",
    ),
    (
        "WalDurabilityObservationDenial::kind",
        "worth-store-physical-backend/recovery-durability/wal-recovery-basis/durability-observation",
        "phase-8",
    ),
    (
        "WalDurabilityObservationDenial::profile_id",
        "worth-store-physical-backend/recovery-durability/wal-recovery-basis/durability-observation",
        "phase-8",
    ),
    (
        "WalDurabilityObservationDenialKind",
        "worth-store-physical-backend/recovery-durability/wal-recovery-basis/durability-observation",
        "phase-8",
    ),
    (
        "WalFrameDigest",
        "worth-store-physical-backend/recovery-durability/wal-recovery-basis/append-receipt",
        "phase-8",
    ),
    (
        "WalFrameDigest::as_str",
        "worth-store-physical-backend/recovery-durability/wal-recovery-basis/append-receipt",
        "phase-8",
    ),
    (
        "WalFrameDigest::new",
        "worth-store-physical-backend/recovery-durability/wal-recovery-basis/append-receipt",
        "phase-8",
    ),
    (
        "WalAppendFailureObservation",
        "worth-store-physical-backend/recovery-durability/wal-recovery-basis/append-receipt",
        "phase-8",
    ),
    (
        "WalAppendReceipt::from_certification_observation",
        "worth-store-physical-backend/recovery-durability/wal-recovery-basis/append-receipt",
        "phase-8",
    ),
];

pub(super) const BACKEND_WAL_DURABILITY_CERTIFICATION_SURFACES: &[&str] = &[
    "WalAppendFailureObservation",
    "WalAppendReceipt::from_certification_observation",
];
