pub(super) const BLOB_REPLAY_DESTINATION_SURFACES: &[(&str, &str, &str)] = &[
    (
        "BlobReplayAdmissionDenial",
        "worth-store-blob-chunks/recovery-readmission",
        "phase-8",
    ),
    (
        "BlobReplayAdmissionDenial::kind",
        "worth-store-blob-chunks/recovery-readmission",
        "phase-8",
    ),
    (
        "BlobReplayAdmissionDenial::source_digest",
        "worth-store-blob-chunks/recovery-readmission",
        "phase-8",
    ),
    (
        "BlobReplayAdmissionDenialKind",
        "worth-store-blob-chunks/recovery-readmission",
        "phase-8",
    ),
    (
        "BlobReplaySourceAdmission",
        "worth-store-blob-chunks/recovery-readmission",
        "phase-8",
    ),
    (
        "BlobReplaySourceAdmission::from_replayable_wal_report",
        "worth-store-blob-chunks/recovery-readmission",
        "phase-8",
    ),
    (
        "BlobReplaySourceAdmission::kind",
        "worth-store-blob-chunks/recovery-readmission",
        "phase-8",
    ),
    (
        "BlobReplaySourceAdmission::reject_backend_residue",
        "worth-store-blob-chunks/recovery-readmission",
        "phase-8",
    ),
    (
        "BlobReplaySourceAdmission::source_digest",
        "worth-store-blob-chunks/recovery-readmission",
        "phase-8",
    ),
    (
        "BlobReplaySourceKind",
        "worth-store-blob-chunks/recovery-readmission",
        "phase-8",
    ),
    (
        "BlobReplaySourceOutcome",
        "worth-store-blob-chunks/recovery-readmission",
        "phase-8",
    ),
    (
        "BlobReplaySourceOutcome::admitted",
        "worth-store-blob-chunks/recovery-readmission",
        "phase-8",
    ),
    (
        "BlobReplaySourceOutcome::kind",
        "worth-store-blob-chunks/recovery-readmission",
        "phase-8",
    ),
    (
        "BlobReplaySourceOutcomeKind",
        "worth-store-blob-chunks/recovery-readmission",
        "phase-8",
    ),
    (
        "BlobResumeReplayReadmission",
        "worth-store-blob-chunks/recovery-readmission",
        "phase-8",
    ),
    (
        "BlobResumeReplayReadmission::checkpoint_source_digest",
        "worth-store-blob-chunks/recovery-readmission",
        "phase-8",
    ),
    (
        "BlobResumeReplayReadmission::current_store_authority_digest",
        "worth-store-blob-chunks/recovery-readmission",
        "phase-8",
    ),
    (
        "BlobResumeReplayReadmission::from_checkpoint_source",
        "worth-store-blob-chunks/recovery-readmission",
        "phase-8",
    ),
];
