pub(super) const BOUNDED_DECODE_SURFACES: &[(&str, &str, &str)] = &[
    (
        "RootRoutingBlockDecodeLimits",
        "worth-store-physical-format/manifest/durable-root-routing/decode-limits",
        "phase-3",
    ),
    (
        "BoundedRootRoutingBlockDecodeDenial",
        "worth-store-physical-format/manifest/durable-root-routing/decode-limits",
        "phase-3",
    ),
    (
        "PhysicalRootRoutingBlock::decode_bounded",
        "worth-store-physical-format/manifest/durable-root-routing",
        "phase-3",
    ),
    (
        "WalActiveTailInspectionDenial",
        "worth-store-wal/artifact-store/segment-inventory/segment-inspection/denial",
        "phase-3",
    ),
    (
        "WalActiveTailInspectionFailure",
        "worth-store-wal/artifact-store/segment-inventory/segment-inspection/denial",
        "phase-3",
    ),
    (
        "WalActiveTailInspectionFailure::denial",
        "worth-store-wal/artifact-store/segment-inventory/segment-inspection/denial",
        "phase-3",
    ),
    (
        "WalActiveTailInspectionFailure::frames_scanned",
        "worth-store-wal/artifact-store/segment-inventory/segment-inspection/denial",
        "phase-3",
    ),
    (
        "inspect_bounded_wal_active_tail_with_evidence",
        "worth-store-wal/artifact-store/segment-inventory/segment-inspection",
        "phase-3",
    ),
    (
        "artifact_store::WalActiveTailInspectionDenial",
        "worth-store-wal/artifact-store/segment-inventory/segment-inspection/denial",
        "phase-3",
    ),
    (
        "artifact_store::WalActiveTailInspectionFailure",
        "worth-store-wal/artifact-store/segment-inventory/segment-inspection/denial",
        "phase-3",
    ),
    (
        "artifact_store::WalActiveTailInspectionFailure::denial",
        "worth-store-wal/artifact-store/segment-inventory/segment-inspection/denial",
        "phase-3",
    ),
    (
        "artifact_store::WalActiveTailInspectionFailure::frames_scanned",
        "worth-store-wal/artifact-store/segment-inventory/segment-inspection/denial",
        "phase-3",
    ),
    (
        "artifact_store::inspect_bounded_wal_active_tail_with_evidence",
        "worth-store-wal/artifact-store/segment-inventory/segment-inspection",
        "phase-3",
    ),
];
