pub(super) const CHECKPOINT_BACKUP_DESTINATION_SURFACES: &[(&str, &str, &str)] = &[
    (
        "BoundedCheckpointBackupDenial",
        "worth-store-offline-verifier/backup-verification/checkpoint-backup-verification",
        "phase-8",
    ),
    (
        "BoundedCheckpointBackupObservation",
        "worth-store-offline-verifier/backup-verification/checkpoint-backup-verification",
        "phase-8",
    ),
    (
        "BoundedCheckpointBackupObservation::artifact_digest",
        "worth-store-offline-verifier/backup-verification/checkpoint-backup-verification",
        "phase-8",
    ),
    (
        "BoundedCheckpointBackupObservation::frontier_digest",
        "worth-store-offline-verifier/backup-verification/checkpoint-backup-verification",
        "phase-8",
    ),
    (
        "BoundedCheckpointBackupObservation::bytes_read",
        "worth-store-offline-verifier/backup-verification/checkpoint-backup-verification",
        "phase-8",
    ),
    (
        "BoundedCheckpointBackupObservation::checkpoint_identity_digest",
        "worth-store-offline-verifier/backup-verification/checkpoint-backup-verification",
        "phase-8",
    ),
    (
        "BoundedCheckpointBackupObservation::covered_lsn",
        "worth-store-offline-verifier/backup-verification/checkpoint-backup-verification",
        "phase-8",
    ),
    (
        "BoundedCheckpointBackupObservation::decoder_allocation_bytes",
        "worth-store-offline-verifier/backup-verification/checkpoint-backup-verification",
        "phase-8",
    ),
    (
        "BoundedCheckpointBackupObservation::durable_checkpoint_lsn",
        "worth-store-offline-verifier/backup-verification/checkpoint-backup-verification",
        "phase-8",
    ),
    (
        "BoundedCheckpointBackupObservation::manifest_generation",
        "worth-store-offline-verifier/backup-verification/checkpoint-backup-verification",
        "phase-8",
    ),
    (
        "BoundedCheckpointBackupObservation::page_count",
        "worth-store-offline-verifier/backup-verification/checkpoint-backup-verification",
        "phase-8",
    ),
    (
        "BoundedCheckpointBackupObservation::peak_buffer_bytes",
        "worth-store-offline-verifier/backup-verification/checkpoint-backup-verification",
        "phase-8",
    ),
    (
        "BoundedCheckpointBackupObservation::redo_lsn",
        "worth-store-offline-verifier/backup-verification/checkpoint-backup-verification",
        "phase-8",
    ),
    (
        "BoundedCheckpointBackupObservation::root_generation",
        "worth-store-offline-verifier/backup-verification/checkpoint-backup-verification",
        "phase-8",
    ),
    (
        "BoundedCheckpointBackupObservation::root_reference",
        "worth-store-offline-verifier/backup-verification/checkpoint-backup-verification",
        "phase-8",
    ),
    (
        "BoundedCheckpointBackupVerificationRequest",
        "worth-store-offline-verifier/backup-verification/checkpoint-backup-verification",
        "phase-8",
    ),
    (
        "CheckpointBackupArtifact",
        "worth-store-physical-format/checkpoint/backup-artifact",
        "phase-8",
    ),
    (
        "CheckpointBackupArtifact::checkpoint_identity",
        "worth-store-physical-format/checkpoint/backup-artifact",
        "phase-8",
    ),
    (
        "CheckpointBackupArtifact::covered_lsn",
        "worth-store-physical-format/checkpoint/backup-artifact",
        "phase-8",
    ),
    (
        "CheckpointBackupArtifact::durable_checkpoint_lsn",
        "worth-store-physical-format/checkpoint/backup-artifact",
        "phase-8",
    ),
    (
        "CheckpointBackupArtifact::encode",
        "worth-store-physical-format/checkpoint/backup-artifact",
        "phase-8",
    ),
    (
        "CheckpointBackupArtifact::from_input",
        "worth-store-physical-format/checkpoint/backup-artifact",
        "phase-8",
    ),
    (
        "CheckpointBackupArtifact::manifest_generation",
        "worth-store-physical-format/checkpoint/backup-artifact",
        "phase-8",
    ),
    (
        "CheckpointBackupArtifact::pages",
        "worth-store-physical-format/checkpoint/backup-artifact",
        "phase-8",
    ),
    (
        "CheckpointBackupArtifact::redo_lsn",
        "worth-store-physical-format/checkpoint/backup-artifact",
        "phase-8",
    ),
    (
        "CheckpointBackupArtifact::root",
        "worth-store-physical-format/checkpoint/backup-artifact",
        "phase-8",
    ),
    (
        "CheckpointBackupArtifact::root_generation",
        "worth-store-physical-format/checkpoint/backup-artifact",
        "phase-8",
    ),
    (
        "CheckpointBackupArtifact::root_reference",
        "worth-store-physical-format/checkpoint/backup-artifact",
        "phase-8",
    ),
    (
        "CheckpointBackupArtifactDecodeDenial",
        "worth-store-physical-format/checkpoint/backup-artifact-decode",
        "phase-8",
    ),
    (
        "CheckpointBackupArtifactDecodeObservation",
        "worth-store-physical-format/checkpoint/backup-artifact-decode",
        "phase-8",
    ),
    (
        "CheckpointBackupArtifactDecodeObservation::bytes_read",
        "worth-store-physical-format/checkpoint/backup-artifact-decode",
        "phase-8",
    ),
    (
        "CheckpointBackupArtifactDecodeObservation::decoder_allocation_bytes",
        "worth-store-physical-format/checkpoint/backup-artifact-decode",
        "phase-8",
    ),
    (
        "CheckpointBackupArtifactDecodeObservation::peak_buffer_bytes",
        "worth-store-physical-format/checkpoint/backup-artifact-decode",
        "phase-8",
    ),
    (
        "CheckpointBackupArtifactDecodeRequest",
        "worth-store-physical-format/checkpoint/backup-artifact-decode",
        "phase-8",
    ),
    (
        "CheckpointBackupArtifactDecodeRequest::new",
        "worth-store-physical-format/checkpoint/backup-artifact-decode",
        "phase-8",
    ),
    (
        "CheckpointBackupArtifactInput",
        "worth-store-physical-format/checkpoint/backup-artifact",
        "phase-8",
    ),
    (
        "DecodedCheckpointBackupArtifact",
        "worth-store-physical-format/checkpoint/backup-artifact-decode",
        "phase-8",
    ),
    (
        "DecodedCheckpointBackupArtifact::artifact",
        "worth-store-physical-format/checkpoint/backup-artifact-decode",
        "phase-8",
    ),
    (
        "DecodedCheckpointBackupArtifact::observation",
        "worth-store-physical-format/checkpoint/backup-artifact-decode",
        "phase-8",
    ),
    (
        "decode_checkpoint_backup_artifact_from_reader",
        "worth-store-physical-format/checkpoint/backup-artifact-decode",
        "phase-8",
    ),
    (
        "verify_bounded_checkpoint_backup_artifact_from_reader",
        "worth-store-offline-verifier/backup-verification/checkpoint-backup-verification",
        "phase-8",
    ),
];
