type Disposition = (&'static str, &'static str, &'static str);

const DEFAULT: Disposition = (
    "replace",
    "worth-store-recovery-runtime/orchestration",
    "phase-8",
);
const CURRENT_MODULE_DISPOSITIONS: &[(&str, Disposition)] = &[
    (
        "source_precedence",
        (
            "narrow",
            "worth-store-recovery-physics/source-precedence",
            "phase-3",
        ),
    ),
    (
        "candidate_evaluation",
        (
            "narrow",
            "worth-store-recovery-physics/source-precedence",
            "phase-3",
        ),
    ),
    (
        "checkpoint_cutover",
        (
            "narrow",
            "worth-store-recovery-physics/source-precedence",
            "phase-3",
        ),
    ),
    (
        "partial_publication",
        (
            "narrow",
            "worth-store-recovery-physics/source-precedence",
            "phase-3",
        ),
    ),
    (
        "wal_recovery_basis",
        (
            "narrow",
            "worth-store-recovery-physics/wal-prefix",
            "phase-3",
        ),
    ),
    (
        "wal_topology",
        ("preserve", "worth-store-wal/recovery-read", "phase-3"),
    ),
    (
        "worth_store_wal",
        ("preserve", "worth-store-wal/recovery-read", "phase-3"),
    ),
    (
        "redo_replay",
        (
            "narrow",
            "worth-store-recovery-physics/redo-planning",
            "phase-4",
        ),
    ),
    (
        "replay_basis",
        (
            "narrow",
            "worth-store-recovery-physics/redo-planning",
            "phase-4",
        ),
    ),
    (
        "replay_receipt",
        (
            "narrow",
            "worth-store-recovery-physics/redo-planning",
            "phase-4",
        ),
    ),
    (
        "page_redo",
        (
            "preserve",
            "worth-store-recovery-physics/page-redo",
            "phase-4",
        ),
    ),
    (
        "recovery_budget",
        (
            "narrow",
            "worth-store-recovery-physics/recovery-budget",
            "phase-4",
        ),
    ),
    (
        "operation_reconciliation",
        (
            "narrow",
            "worth-store-recovery-physics/operation-reconciliation",
            "phase-4",
        ),
    ),
    (
        "entry",
        (
            "replace",
            "worth-store-recovery-runtime/entry-admission",
            "phase-8",
        ),
    ),
    (
        "memory_allocation",
        (
            "replace",
            "worth-store-recovery-runtime/entry-limits",
            "phase-8",
        ),
    ),
    (
        "staged_wal_application",
        (
            "replace",
            "worth-store-recovery-runtime/orchestration-staging",
            "phase-8",
        ),
    ),
    (
        "staged_wal_replay_source",
        (
            "replace",
            "worth-store-recovery-runtime/orchestration-staging",
            "phase-8",
        ),
    ),
    (
        "publication",
        (
            "replace",
            "worth-store-recovery-runtime/orchestration-publication",
            "phase-8",
        ),
    ),
    (
        "recovery_completion",
        (
            "replace",
            "worth-store-recovery-runtime/progression-reopened",
            "phase-8",
        ),
    ),
    (
        "offline_verifier",
        (
            "replace",
            "worth-store-offline-verifier/c8-recovery-observation",
            "phase-8",
        ),
    ),
    ("recovery_evidence", ("delete", "none", "phase-8")),
    (
        "backup_restore",
        ("replace", "worth-store-operations/backup-import", "phase-8"),
    ),
    (
        "point_in_time_recovery",
        (
            "replace",
            "worth-store-operations/point-in-time-recovery",
            "phase-8",
        ),
    ),
    (
        "rollback_recovery",
        ("replace", "worth-store-operations/rollback", "phase-8"),
    ),
    (
        "replica_bootstrap_source",
        (
            "replace",
            "worth-store-replication/bootstrap-source",
            "phase-8",
        ),
    ),
    (
        "blob_replay",
        (
            "replace",
            "worth-store-blob-chunks/recovery-readmission",
            "phase-8",
        ),
    ),
    (
        "btree_replay",
        (
            "replace",
            "worth-store-layout-indexes/btree-replay",
            "phase-8",
        ),
    ),
    (
        "layout_readmission",
        (
            "replace",
            "worth-store-layout-indexes/integrity-readmission",
            "phase-8",
        ),
    ),
    (
        "layout_projection",
        (
            "replace",
            "worth-store-offline-verifier/c8-layout-observation",
            "phase-8",
        ),
    ),
    (
        "corruption_readmission",
        (
            "replace",
            "worth-store-physical-integrity/recovery-readmission",
            "phase-8",
        ),
    ),
    (
        "integrity_damage_map",
        (
            "replace",
            "worth-store-physical-integrity/damage-classification",
            "phase-8",
        ),
    ),
    (
        "integrity_handoff",
        (
            "replace",
            "worth-store-physical-integrity/recovery-handoff",
            "phase-8",
        ),
    ),
    (
        "integrity_input",
        (
            "replace",
            "worth-store-physical-integrity/recovery-handoff",
            "phase-8",
        ),
    ),
    (
        "recovery_integrity_handoff_receipt",
        (
            "replace",
            "worth-store-physical-integrity/recovery-handoff",
            "phase-8",
        ),
    ),
    (
        "integrity_vetted_records",
        (
            "replace",
            "worth-store-physical-integrity/recovery-records",
            "phase-8",
        ),
    ),
    (
        "recovery_blocking_integrity",
        (
            "replace",
            "worth-store-physical-integrity/recovery-blocking",
            "phase-8",
        ),
    ),
    (
        "security_metadata_admission",
        (
            "replace",
            "worth-store-security/recovery-metadata",
            "phase-8",
        ),
    ),
    (
        "security_scope_propagation",
        (
            "replace",
            "worth-store-security/recovery-metadata",
            "phase-8",
        ),
    ),
    (
        "worth_store_contracts",
        (
            "preserve",
            "worth-store-contracts/corruption-handoff",
            "phase-8",
        ),
    ),
];

pub(crate) fn expected_current_disposition(source_owner: &str, surface: &str) -> Disposition {
    if deleted_observer_runtime_surface(source_owner, surface) {
        return ("delete", "none", "phase-8");
    }
    if matches!(
        surface,
        "PhysicalWalSegmentCandidate::frames" | "SelectedPhysicalWalTail::frames"
    ) {
        return (
            "narrow",
            "worth-store-recovery-physics/source-precedence",
            "phase-4",
        );
    }
    let module = source_owner.split("::").next().unwrap_or(source_owner);
    CURRENT_MODULE_DISPOSITIONS
        .iter()
        .find_map(|(candidate, disposition)| (*candidate == module).then_some(*disposition))
        .unwrap_or(DEFAULT)
}

fn deleted_observer_runtime_surface(source_owner: &str, surface: &str) -> bool {
    let root_surface = surface.split("::").next().unwrap_or(surface);
    source_owner.starts_with("offline_verifier")
        && matches!(
            root_surface,
            "FreshRuntimeRecoveryDriver"
                | "FreshRuntimeRecoveryExecution"
                | "FreshRuntimeRecoveryWitness"
                | "runtime_driver"
                | "fresh_runtime_execution"
        )
}
