//! Exact destination rows for one recovery workflow owner.

pub(super) const DESTINATION_SURFACES: &[(&str, &str, &str)] = &[
    (
        "StagedWalApplicationDenial",
        "worth-store-operations/workflow/recovery-replay",
        "phase-8",
    ),
    (
        "StagedWalApplicationPort",
        "worth-store-operations/workflow/recovery-replay",
        "phase-8",
    ),
    (
        "StagedWalApplicationPort::apply_staged_wal",
        "worth-store-operations/workflow/recovery-replay",
        "phase-8",
    ),
    (
        "StagedWalApplicationProviderReceipt",
        "worth-store-operations/workflow/recovery-replay",
        "phase-8",
    ),
    (
        "StagedWalApplicationProviderReceipt::observed",
        "worth-store-operations/workflow/recovery-replay",
        "phase-8",
    ),
    (
        "StagedWalApplicationReceipt",
        "worth-store-operations/workflow/recovery-replay",
        "phase-8",
    ),
    (
        "StagedWalApplicationReceipt::application_identity",
        "worth-store-operations/workflow/recovery-replay",
        "phase-8",
    ),
    (
        "StagedWalApplicationReceipt::applied_frames",
        "worth-store-operations/workflow/recovery-replay",
        "phase-8",
    ),
    (
        "StagedWalApplicationReceipt::identity",
        "worth-store-operations/workflow/recovery-replay",
        "phase-8",
    ),
    (
        "StagedWalApplicationReceipt::replay_source_identity",
        "worth-store-operations/workflow/recovery-replay",
        "phase-8",
    ),
    (
        "StagedWalApplicationReceipt::resulting_frontier_identity",
        "worth-store-operations/workflow/recovery-replay",
        "phase-8",
    ),
    (
        "StagedWalApplicationRequest",
        "worth-store-operations/workflow/recovery-replay",
        "phase-8",
    ),
    (
        "StagedWalApplicationRequest::application_identity",
        "worth-store-operations/workflow/recovery-replay",
        "phase-8",
    ),
    (
        "StagedWalApplicationRequest::replay_source",
        "worth-store-operations/workflow/recovery-replay",
        "phase-8",
    ),
    (
        "StagedWalApplicationRequest::staging",
        "worth-store-operations/workflow/recovery-replay",
        "phase-8",
    ),
    (
        "StagedWalApplicationRequest::target_frontier_identity",
        "worth-store-operations/workflow/recovery-replay",
        "phase-8",
    ),
    (
        "StagedWalReplaySourceDenial",
        "worth-store-operations/workflow/recovery-replay",
        "phase-8",
    ),
    (
        "StagedWalReplaySourceReceipt",
        "worth-store-operations/workflow/recovery-replay",
        "phase-8",
    ),
    (
        "StagedWalReplaySourceReceipt::bytes_verified",
        "worth-store-operations/workflow/recovery-replay",
        "phase-8",
    ),
    (
        "StagedWalReplaySourceReceipt::frame_count",
        "worth-store-operations/workflow/recovery-replay",
        "phase-8",
    ),
    (
        "StagedWalReplaySourceReceipt::identity",
        "worth-store-operations/workflow/recovery-replay",
        "phase-8",
    ),
    (
        "StagedWalReplaySourceReceipt::interval",
        "worth-store-operations/workflow/recovery-replay",
        "phase-8",
    ),
    (
        "StagedWalReplaySourceReceipt::manifest_digest",
        "worth-store-operations/workflow/recovery-replay",
        "phase-8",
    ),
];
