//! Exact destination rows for one recovery workflow owner.

pub(super) const DESTINATION_SURFACES: &[(&str, &str, &str)] = &[
    (
        "ExactRecoveryFrontier",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "ExactRecoveryFrontier::authority_identity",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "ExactRecoveryFrontier::checkpoint_durability",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "ExactRecoveryFrontier::client_acknowledged",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "ExactRecoveryFrontier::compare",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "ExactRecoveryFrontier::identity",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "ExactRecoveryFrontier::local_durable_commit",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "ExactRecoveryFrontier::replication_acknowledged",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "ExactRecoveryFrontier::source_lineage",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "ExactRecoveryFrontier::wal_structural",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "FrontierPartialOrder",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "PitrCandidatePosture",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "PitrCandidateSelectionDenial",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "PitrRoundingPolicy",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "PointInTimeCandidate",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "PointInTimeCandidate::clock_distance",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "PointInTimeCandidate::clock_uncertainty_interval",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "PointInTimeCandidate::exact_frontier",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "PointInTimeCandidate::identity",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "PointInTimeCandidate::observed_time",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "PointInTimeCandidate::posture",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "PointInTimeCandidate::source_identity",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "PointInTimeCandidateSet",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "PointInTimeCandidateSet::candidates",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "PointInTimeCandidateSet::evidence_count",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "PointInTimeCandidateSet::requested_time",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "PointInTimeCandidateSet::rounding",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "PointInTimeCandidateSet::select",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "PointInTimeRecoveryReceipt",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "PointInTimeRecoveryReceipt::application",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "PointInTimeRecoveryReceipt::exact_frontier",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "PointInTimeRecoveryReceipt::plan_fingerprint",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "PointInTimeRecoveryReceipt::replay_source",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "PointInTimeReplayDenial",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "PointInTimeReplayPlan",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "PointInTimeReplayPlan::exact_frontier",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "PointInTimeReplayPlan::fingerprint",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "PointInTimeReplayRequest",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "PointInTimeReplayRequest::new",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "PointInTimeReplaySourceCoordinates",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "PointInTimeReplayOwner",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "PointInTimeReplayOwner::execute",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "PointInTimeReplayOwner::lower",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "RecoveryTimelineOwner",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "RecoveryTimelineOwner::admit_observation",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "RecoveryTimelineOwner::resolve_candidates",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
    (
        "RecoveryTimelineObservation",
        "worth-store-operations/workflow/point-in-time-recovery",
        "phase-8",
    ),
];
