//! Exact destination rows for one recovery workflow owner.

pub(super) const DESTINATION_SURFACES: &[(&str, &str, &str)] = &[
    (
        "RollbackReplayOwner",
        "worth-store-operations/workflow/rollback",
        "phase-8",
    ),
    (
        "RollbackReplayOwner::execute",
        "worth-store-operations/workflow/rollback",
        "phase-8",
    ),
    (
        "RollbackReplayOwner::lower",
        "worth-store-operations/workflow/rollback",
        "phase-8",
    ),
    (
        "RollbackReplayOwner::resolve_candidate",
        "worth-store-operations/workflow/rollback",
        "phase-8",
    ),
    (
        "RollbackReplayOwner::source_lineage",
        "worth-store-operations/workflow/rollback",
        "phase-8",
    ),
    (
        "ResolvedRollbackCandidate",
        "worth-store-operations/workflow/rollback",
        "phase-8",
    ),
    (
        "ResolvedRollbackCandidate::frontier",
        "worth-store-operations/workflow/rollback",
        "phase-8",
    ),
    (
        "ResolvedRollbackCandidate::manifest_digest",
        "worth-store-operations/workflow/rollback",
        "phase-8",
    ),
    (
        "ResolvedRollbackCandidate::retained_authority",
        "worth-store-operations/workflow/rollback",
        "phase-8",
    ),
    (
        "ResolvedRollbackCandidate::root_generation",
        "worth-store-operations/workflow/rollback",
        "phase-8",
    ),
    (
        "ResolvedRollbackCandidate::source_identity",
        "worth-store-operations/workflow/rollback",
        "phase-8",
    ),
    (
        "ResolvedRollbackCandidate::source_lineage",
        "worth-store-operations/workflow/rollback",
        "phase-8",
    ),
    (
        "RollbackExecutionReceipt",
        "worth-store-operations/workflow/rollback",
        "phase-8",
    ),
    (
        "RollbackExecutionReceipt::application",
        "worth-store-operations/workflow/rollback",
        "phase-8",
    ),
    (
        "RollbackExecutionReceipt::frontier",
        "worth-store-operations/workflow/rollback",
        "phase-8",
    ),
    (
        "RollbackExecutionReceipt::plan_fingerprint",
        "worth-store-operations/workflow/rollback",
        "phase-8",
    ),
    (
        "RollbackExecutionReceipt::replay_source",
        "worth-store-operations/workflow/rollback",
        "phase-8",
    ),
    (
        "RollbackReplayDenial",
        "worth-store-operations/workflow/rollback",
        "phase-8",
    ),
    (
        "RollbackReplayPlan",
        "worth-store-operations/workflow/rollback",
        "phase-8",
    ),
    (
        "RollbackReplayPlan::fingerprint",
        "worth-store-operations/workflow/rollback",
        "phase-8",
    ),
    (
        "RollbackReplayPlan::frontier",
        "worth-store-operations/workflow/rollback",
        "phase-8",
    ),
];
