//! Exact destination rows for one recovery workflow owner.

pub(super) const DESTINATION_SURFACES: &[(&str, &str, &str)] = &[
    (
        "BackupRestoreReplayDenial",
        "worth-store-operations/workflow/restore",
        "phase-8",
    ),
    (
        "BackupRestoreReplayPlan",
        "worth-store-operations/workflow/restore",
        "phase-8",
    ),
    (
        "BackupRestoreReplayPlan::fingerprint",
        "worth-store-operations/workflow/restore",
        "phase-8",
    ),
    (
        "BackupRestoreReplayPlan::target_staging_plan_fingerprint",
        "worth-store-operations/workflow/restore",
        "phase-8",
    ),
    (
        "BackupRestoreReplayRequest",
        "worth-store-operations/workflow/restore",
        "phase-8",
    ),
    (
        "BackupRestoreReplayRequest::from_verified_backup",
        "worth-store-operations/workflow/restore",
        "phase-8",
    ),
    (
        "RecoveredBackupFrontierReceipt",
        "worth-store-operations/workflow/restore",
        "phase-8",
    ),
    (
        "RecoveredBackupFrontierReceipt::acknowledged_frontier",
        "worth-store-operations/workflow/restore",
        "phase-8",
    ),
    (
        "RecoveredBackupFrontierReceipt::application",
        "worth-store-operations/workflow/restore",
        "phase-8",
    ),
    (
        "RecoveredBackupFrontierReceipt::durable_checkpoint_lsn",
        "worth-store-operations/workflow/restore",
        "phase-8",
    ),
    (
        "RecoveredBackupFrontierReceipt::plan_fingerprint",
        "worth-store-operations/workflow/restore",
        "phase-8",
    ),
    (
        "RecoveredBackupFrontierReceipt::replay_source",
        "worth-store-operations/workflow/restore",
        "phase-8",
    ),
    (
        "RecoveredBackupFrontierReceipt::root_generation",
        "worth-store-operations/workflow/restore",
        "phase-8",
    ),
    (
        "RecoveredBackupFrontierReceipt::wal_end_exclusive_lsn",
        "worth-store-operations/workflow/restore",
        "phase-8",
    ),
    (
        "BackupRestoreReplayOwner",
        "worth-store-operations/workflow/restore",
        "phase-8",
    ),
    (
        "BackupRestoreReplayOwner::execute",
        "worth-store-operations/workflow/restore",
        "phase-8",
    ),
    (
        "BackupRestoreReplayOwner::lower",
        "worth-store-operations/workflow/restore",
        "phase-8",
    ),
];
