pub(super) const PHASE_EIGHT_OWNER_DESTINATION_SURFACES: &[(&str, &str, &str)] = &[
    (
        "AdmittedBTreeReplayPhysicalSource",
        "worth-store-layout-indexes/recovery/btree_replay",
        "phase-8",
    ),
    (
        "AdmittedBTreeReplayPhysicalSource::admit",
        "worth-store-layout-indexes/recovery/btree_replay",
        "phase-8",
    ),
    (
        "AdmittedBTreeReplayPhysicalSource::bind_intent",
        "worth-store-layout-indexes/recovery/btree_replay",
        "phase-8",
    ),
    (
        "AdmittedBTreeReplayPhysicalSource::durable_source",
        "worth-store-layout-indexes/recovery/btree_replay",
        "phase-8",
    ),
    (
        "AdmittedBTreeReplayPhysicalSource::identity",
        "worth-store-layout-indexes/recovery/btree_replay",
        "phase-8",
    ),
    (
        "AdmittedBTreeReplayPhysicalSource::root_agreement",
        "worth-store-layout-indexes/recovery/btree_replay",
        "phase-8",
    ),
    (
        "AdmittedBTreeReplayPhysicalSource::root_reference",
        "worth-store-layout-indexes/recovery/btree_replay",
        "phase-8",
    ),
    (
        "AdmittedBTreeReplaySource",
        "worth-store-layout-indexes/recovery/btree_replay",
        "phase-8",
    ),
    (
        "AdmittedBTreeReplaySource::durable_source",
        "worth-store-layout-indexes/recovery/btree_replay",
        "phase-8",
    ),
    (
        "AdmittedBTreeReplaySource::intent",
        "worth-store-layout-indexes/recovery/btree_replay",
        "phase-8",
    ),
    (
        "AdmittedBTreeReplaySource::persisted_layout",
        "worth-store-layout-indexes/recovery/btree_replay",
        "phase-8",
    ),
    (
        "AdmittedBTreeReplaySource::physical_source",
        "worth-store-layout-indexes/recovery/btree_replay",
        "phase-8",
    ),
    (
        "AdmittedBTreeReplaySource::reopen",
        "worth-store-layout-indexes/recovery/btree_replay",
        "phase-8",
    ),
    (
        "AdmittedBTreeReplaySource::root_agreement",
        "worth-store-layout-indexes/recovery/btree_replay",
        "phase-8",
    ),
    (
        "AdmittedBTreeReplaySource::root_reference",
        "worth-store-layout-indexes/recovery/btree_replay",
        "phase-8",
    ),
    (
        "BTreeReplayPhysicalSourceIdentity",
        "worth-store-layout-indexes/recovery/btree_replay",
        "phase-8",
    ),
    (
        "BTreeReplayRootAgreement",
        "worth-store-layout-indexes/recovery/btree_replay",
        "phase-8",
    ),
    (
        "BTreeReplayRootAgreement::checkpoint_coverage",
        "worth-store-layout-indexes/recovery/btree_replay",
        "phase-8",
    ),
    (
        "BTreeReplayRootAgreement::checkpoint_id",
        "worth-store-layout-indexes/recovery/btree_replay",
        "phase-8",
    ),
    (
        "BTreeReplayRootAgreement::replay_tail",
        "worth-store-layout-indexes/recovery/btree_replay",
        "phase-8",
    ),
    (
        "BTreeReplayRootAgreement::root_reference",
        "worth-store-layout-indexes/recovery/btree_replay",
        "phase-8",
    ),
    (
        "BTreeReplaySourceDenial",
        "worth-store-layout-indexes/recovery/btree_replay",
        "phase-8",
    ),
    (
        "RecoveryCheckpointRecordSecurityMetadataEnvelope",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoveryCheckpointRecordSecurityMetadataEnvelope::from_admitted_scope",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoveryCheckpointRecordSecurityMetadataEnvelope::from_checkpoint_record_envelope",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoveryCheckpointRecordSecurityMetadataEnvelope::identity",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoveryCheckpointRecordSecurityMetadataEnvelope::security_metadata",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoveryCheckpointRecordSecurityMetadataIdentity",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoveryCheckpointRecordSecurityMetadataIdentity::checkpoint_epoch",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoveryCheckpointRecordSecurityMetadataIdentity::from_store_checkpoint_record",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoveryCheckpointRecordSecurityMetadataIdentity::new",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoveryRootSecurityMetadataAdmission",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoveryRootSecurityMetadataAdmission::from_physical_metadata",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoveryRootSecurityMetadataAdmission::metadata",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoveryRootSecurityMetadataAdmission::to_raw_security_scope_declaration",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoveryRootSecurityMetadataEnvelope",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoveryRootSecurityMetadataEnvelope::entry_identity",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoveryRootSecurityMetadataEnvelope::from_recovery_entry",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoveryRootSecurityMetadataEnvelope::security_metadata",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoverySecurityScopePropagation",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoverySecurityScopePropagation::admit",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoverySecurityScopePropagation::admit_required",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoverySecurityScopePropagation::checkpoint_record_identity",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoverySecurityScopePropagation::counters",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoverySecurityScopePropagation::entry_identity",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoverySecurityScopePropagation::metadata",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoverySecurityScopePropagation::wal_record_identity",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoverySecurityScopePropagation::witness",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoverySecurityScopePropagationCounters",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoverySecurityScopePropagationCounters::from_wal_checkpoint_counters",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoverySecurityScopePropagationCounters::root_scope_comparisons",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoverySecurityScopePropagationCounters::root_store_counters",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoverySecurityScopePropagationCounters::store_counters",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoverySecurityScopePropagationCounters::wal_checkpoint_comparisons",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoverySecurityScopePropagationCounters::wal_checkpoint_store_counters",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoverySecurityScopePropagationCounters::with_root_scope_comparison",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoverySecurityScopePropagationDenial",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoverySecurityScopePropagationDenial::from_store_denial",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoverySecurityScopePropagationDenial::store_denial",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoverySecurityScopePropagationInput",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoverySecurityScopePropagationInput::checkpoint_metadata",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoverySecurityScopePropagationInput::checkpoint_record_identity",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoverySecurityScopePropagationInput::entry_identity",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoverySecurityScopePropagationInput::new",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoverySecurityScopePropagationInput::root_artifact_present",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoverySecurityScopePropagationInput::root_metadata",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoverySecurityScopePropagationInput::wal_metadata",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoverySecurityScopePropagationInput::wal_record_identity",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoveryWalRecordSecurityMetadataEnvelope",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoveryWalRecordSecurityMetadataEnvelope::from_admitted_scope",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoveryWalRecordSecurityMetadataEnvelope::from_wal_record_envelope",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoveryWalRecordSecurityMetadataEnvelope::identity",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoveryWalRecordSecurityMetadataEnvelope::security_metadata",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoveryWalRecordSecurityMetadataIdentity",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoveryWalRecordSecurityMetadataIdentity::from_store_wal_record",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoveryWalRecordSecurityMetadataIdentity::new",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
    (
        "RecoveryWalRecordSecurityMetadataIdentity::sequence",
        "worth-store-security/recovery-metadata",
        "phase-8",
    ),
];
