pub(super) const PHYSICAL_ISOLATION_PUBLICATION_DESTINATION_SURFACES: &[(&str, &str, &str)] = &[
    (
        "ExecutedPublicationRecoveryReceipt",
        "worth-store-physical-isolation/publication/recovery-replay",
        "phase-8",
    ),
    (
        "ExecutedPublicationRecoveryReceipt::recovered_kind",
        "worth-store-physical-isolation/publication/recovery-replay",
        "phase-8",
    ),
    (
        "ExecutedPublicationRecoveryReceipt::recovery_replayed_frames",
        "worth-store-physical-isolation/publication/recovery-replay",
        "phase-8",
    ),
    (
        "ExecutedPublicationRecoveryReceipt::stage",
        "worth-store-physical-isolation/publication/recovery-replay",
        "phase-8",
    ),
    (
        "PublicationCrashStage",
        "worth-store-physical-isolation/publication/recovery-replay",
        "phase-8",
    ),
    (
        "PublicationRecoveryReplayInput",
        "worth-store-physical-isolation/publication/recovery-replay",
        "phase-8",
    ),
    (
        "PublicationRecoveryReplayInput::from_crash_stage",
        "worth-store-physical-isolation/publication/recovery-replay",
        "phase-8",
    ),
    (
        "PublicationRecoveryReplayInput::mixed_tree_fault_attempt",
        "worth-store-physical-isolation/publication/recovery-replay",
        "phase-8",
    ),
    (
        "RecoveredPublicationStructure",
        "worth-store-physical-isolation/publication/recovery-replay",
        "phase-8",
    ),
    (
        "RecoveredPublicationStructure::kind",
        "worth-store-physical-isolation/publication/recovery-replay",
        "phase-8",
    ),
    (
        "RecoveredPublicationStructure::new_manifest_epoch",
        "worth-store-physical-isolation/publication/recovery-replay",
        "phase-8",
    ),
    (
        "RecoveredPublicationStructure::new_root_epoch",
        "worth-store-physical-isolation/publication/recovery-replay",
        "phase-8",
    ),
    (
        "RecoveredPublicationStructure::new_stable_for_publication_admission",
        "worth-store-physical-isolation/publication/recovery-replay",
        "phase-8",
    ),
    (
        "RecoveredPublicationStructure::old_manifest_epoch",
        "worth-store-physical-isolation/publication/recovery-replay",
        "phase-8",
    ),
    (
        "RecoveredPublicationStructure::old_root_epoch",
        "worth-store-physical-isolation/publication/recovery-replay",
        "phase-8",
    ),
    (
        "RecoveredPublicationStructure::old_stable_for_publication_admission",
        "worth-store-physical-isolation/publication/recovery-replay",
        "phase-8",
    ),
    (
        "RecoveredPublicationStructure::stable_manifest_epoch",
        "worth-store-physical-isolation/publication/recovery-replay",
        "phase-8",
    ),
    (
        "RecoveredPublicationStructure::stable_root_epoch",
        "worth-store-physical-isolation/publication/recovery-replay",
        "phase-8",
    ),
    (
        "RecoveredPublicationStructureKind",
        "worth-store-physical-isolation/publication/recovery-replay",
        "phase-8",
    ),
];
