pub(super) const PHYSICAL_ISOLATION_RECOVERY_SOURCE_DESTINATION_SURFACES: &[(&str, &str, &str)] = &[
    (
        "BootstrapSourceArtifact",
        "worth-store-physical-isolation/recovery-source-lease/bootstrap-source",
        "phase-8",
    ),
    (
        "BootstrapSourceArtifact::byte_length",
        "worth-store-physical-isolation/recovery-source-lease/bootstrap-source",
        "phase-8",
    ),
    (
        "BootstrapSourceArtifact::content_digest",
        "worth-store-physical-isolation/recovery-source-lease/bootstrap-source",
        "phase-8",
    ),
    (
        "BootstrapSourceArtifact::declare",
        "worth-store-physical-isolation/recovery-source-lease/bootstrap-source",
        "phase-8",
    ),
    (
        "BootstrapSourceArtifact::family",
        "worth-store-physical-isolation/recovery-source-lease/bootstrap-source",
        "phase-8",
    ),
    (
        "BootstrapSourceArtifact::relative_path",
        "worth-store-physical-isolation/recovery-source-lease/bootstrap-source",
        "phase-8",
    ),
    (
        "BootstrapSourceArtifactFamily",
        "worth-store-physical-isolation/recovery-source-lease/bootstrap-source",
        "phase-8",
    ),
    (
        "BootstrapSourceEvidenceBinding",
        "worth-store-physical-isolation/recovery-source-lease/bootstrap-source",
        "phase-8",
    ),
    (
        "BootstrapSourceEvidenceBinding::from_independent_verification",
        "worth-store-physical-isolation/recovery-source-lease/bootstrap-source",
        "phase-8",
    ),
    (
        "BootstrapSourceFrontier",
        "worth-store-physical-isolation/recovery-source-lease/bootstrap-source",
        "phase-8",
    ),
    (
        "BootstrapSourceFrontier::admit",
        "worth-store-physical-isolation/recovery-source-lease/bootstrap-source",
        "phase-8",
    ),
    (
        "BootstrapSourceResolutionCounters",
        "worth-store-physical-isolation/recovery-source-lease/bootstrap-source",
        "phase-8",
    ),
    (
        "BootstrapSourceResolutionCounters::artifacts_reopened",
        "worth-store-physical-isolation/recovery-source-lease/bootstrap-source",
        "phase-8",
    ),
    (
        "BootstrapSourceResolutionCounters::bytes_read",
        "worth-store-physical-isolation/recovery-source-lease/bootstrap-source",
        "phase-8",
    ),
    (
        "BootstrapSourceResolutionCounters::resident_buffer_bytes",
        "worth-store-physical-isolation/recovery-source-lease/bootstrap-source",
        "phase-8",
    ),
    (
        "BootstrapSourceResolutionDenial",
        "worth-store-physical-isolation/recovery-source-lease/bootstrap-source",
        "phase-8",
    ),
    (
        "BootstrapSourceResolutionRequest",
        "worth-store-physical-isolation/recovery-source-lease/bootstrap-source",
        "phase-8",
    ),
    (
        "BootstrapSourceResolutionRequest::from_independent_verification",
        "worth-store-physical-isolation/recovery-source-lease/bootstrap-source",
        "phase-8",
    ),
    (
        "PhysicalIsolationBootstrapSourceOwner",
        "worth-store-physical-isolation/recovery-source-lease/bootstrap-source",
        "phase-8",
    ),
    (
        "PhysicalIsolationBootstrapSourceOwner::resolve",
        "worth-store-physical-isolation/recovery-source-lease/bootstrap-source",
        "phase-8",
    ),
    (
        "ResolvedBootstrapRecoverySourceCut",
        "worth-store-physical-isolation/recovery-source-lease/bootstrap-source",
        "phase-8",
    ),
    (
        "ResolvedBootstrapRecoverySourceCut::artifact_paths",
        "worth-store-physical-isolation/recovery-source-lease/bootstrap-source",
        "phase-8",
    ),
    (
        "ResolvedBootstrapRecoverySourceCut::counters",
        "worth-store-physical-isolation/recovery-source-lease/bootstrap-source",
        "phase-8",
    ),
    (
        "ResolvedBootstrapRecoverySourceCut::frontier_identity",
        "worth-store-physical-isolation/recovery-source-lease/bootstrap-source",
        "phase-8",
    ),
    (
        "ResolvedBootstrapRecoverySourceCut::operation_identity",
        "worth-store-physical-isolation/recovery-source-lease/bootstrap-source",
        "phase-8",
    ),
    (
        "ResolvedBootstrapRecoverySourceCut::resolution_identity",
        "worth-store-physical-isolation/recovery-source-lease/bootstrap-source",
        "phase-8",
    ),
    (
        "ResolvedBootstrapRecoverySourceCut::source_identity",
        "worth-store-physical-isolation/recovery-source-lease/bootstrap-source",
        "phase-8",
    ),
    (
        "ResolvedBootstrapRecoverySourceCut::source_lineage_identity",
        "worth-store-physical-isolation/recovery-source-lease/bootstrap-source",
        "phase-8",
    ),
    (
        "ResolvedBootstrapRecoverySourceCut::source_root",
        "worth-store-physical-isolation/recovery-source-lease/bootstrap-source",
        "phase-8",
    ),
    (
        "ResolvedBootstrapRecoverySourceCut::verification_identity",
        "worth-store-physical-isolation/recovery-source-lease/bootstrap-source",
        "phase-8",
    ),
];
