//! Exact destination rows for the recovery-physics facade.

pub(super) const DESTINATION_SURFACES: &[(&str, &str, &str)] = &[
    (
        "AdmittedReplayTailCursor",
        "worth-store-wal/recovery-read",
        "phase-3",
    ),
    (
        "LogSequenceNumber",
        "worth-store-wal/wal-topology",
        "phase-3",
    ),
    ("WalLsnRange", "worth-store-wal/wal-topology", "phase-3"),
    (
        "WalSegmentGeneration",
        "worth-store-wal/wal-topology",
        "phase-3",
    ),
    ("WalSegmentId", "worth-store-wal/wal-topology", "phase-3"),
    (
        "WalSegmentArtifactIdentity",
        "worth-store-wal/artifact-store/segment-inventory",
        "phase-3",
    ),
    (
        "WalSegmentInspection",
        "worth-store-wal/artifact-store/segment-inventory/segment-inspection",
        "phase-3",
    ),
    ("PhysicalRecoveryOpenRequest", "entry/request", "phase-2"),
    (
        "PhysicalRecoveryOpenRequest::declare",
        "entry/request",
        "phase-2",
    ),
    (
        "PhysicalRecoveryOpenRequest::admit",
        "entry/request",
        "phase-2",
    ),
    (
        "PhysicalRecoveryStaticConfiguration",
        "entry/configuration",
        "phase-2",
    ),
    (
        "PhysicalRecoveryStaticConfiguration::current",
        "entry/configuration",
        "phase-2",
    ),
    (
        "PhysicalRecoveryLimitDeclaration",
        "entry/limits",
        "phase-2",
    ),
    ("PhysicalRecoveryLimits", "entry/limits", "phase-2"),
    ("PhysicalRecoveryLimits::admit", "entry/limits", "phase-2"),
    ("PhysicalRecoveryLimitDenial", "entry/limits", "phase-2"),
    (
        "PhysicalRecoveryAdmissionCounters",
        "entry/counters",
        "phase-2",
    ),
    (
        "PhysicalRecoverySessionIdentity",
        "entry/session",
        "phase-2",
    ),
    (
        "PhysicalRecoveryEntryBindingDrift",
        "entry/authority-binding",
        "phase-2",
    ),
    (
        "PhysicalRecoveryPlatformAuthority",
        "entry/authority",
        "phase-2",
    ),
    (
        "PhysicalRecoveryPlatformAuthority::acquire",
        "entry/authority",
        "phase-2",
    ),
    (
        "PhysicalRecoveryPlatformAuthority::qualified_backend_profile",
        "entry/authority",
        "phase-2",
    ),
    (
        "PhysicalRecoveryPlatformAuthority::session_identity",
        "entry/authority",
        "phase-2",
    ),
    (
        "PhysicalRecoveryPlatformAuthority::process_counters",
        "entry/authority",
        "phase-2",
    ),
    (
        "PhysicalRecoveryPlatformAdmissionError",
        "entry/authority",
        "phase-2",
    ),
    ("PhysicalRecoveryOutcome", "entry/outcome", "phase-2"),
    ("WorthStoreRecovery", "lib", "phase-6"),
    ("WorthStoreRecovery::recover", "lib", "phase-6"),
    (
        "AdmittedPhysicalRecovery",
        "progression/admitted",
        "phase-2",
    ),
    (
        "AdmittedPhysicalRecovery::store_identity",
        "progression/admitted",
        "phase-2",
    ),
    (
        "AdmittedPhysicalRecovery::session_identity",
        "progression/admitted",
        "phase-2",
    ),
    (
        "AdmittedPhysicalRecovery::limits",
        "progression/admitted",
        "phase-2",
    ),
    (
        "AdmittedPhysicalRecovery::counters",
        "progression/admitted",
        "phase-2",
    ),
    (
        "AdmittedPhysicalRecovery::cancel_before_discovery",
        "progression/admitted",
        "phase-2",
    ),
    ("PlannedPhysicalRecovery", "progression/planned", "phase-4"),
    (
        "NamespaceDurablePhysicalRecovery",
        "progression/namespace_durable",
        "phase-6",
    ),
    (
        "ReopenedPhysicalRecovery",
        "progression/reopened",
        "phase-6",
    ),
    (
        "RecoveredPhysicalRuntimeHandoff",
        "handoff/recovered",
        "phase-6",
    ),
    (
        "PhysicalRecoveryConstructionPort",
        "worth-store/recovery-construction/port",
        "phase-6",
    ),
    (
        "PhysicalRecoveryFreshnessAuthority",
        "worth-store/recovery-freshness/authority",
        "phase-2",
    ),
    (
        "PhysicalRecoveryFreshnessAuthority::register_session",
        "worth-store/recovery-freshness/registration",
        "phase-2",
    ),
    (
        "PhysicalRecoveryRegisteredSessionAuthority",
        "worth-store/recovery-freshness/registration",
        "phase-2",
    ),
    (
        "PhysicalRecoveryRegisteredSessionAuthority::session_identity_bytes",
        "worth-store/recovery-freshness/registration",
        "phase-2",
    ),
    (
        "PhysicalRecoveryFreshnessPort",
        "worth-store/recovery-freshness/port",
        "phase-2",
    ),
    (
        "PhysicalRecoveryFreshnessPort::admit",
        "worth-store/recovery-freshness/port",
        "phase-2",
    ),
    (
        "PhysicalRecoveryFreshnessPort::sample_binding",
        "worth-store/recovery-freshness/port",
        "phase-4",
    ),
    (
        "PhysicalRecoveryConstructionAuthority",
        "worth-store/recovery-construction/authority",
        "phase-6",
    ),
    ("PhysicalRecoveryRefusal", "entry/outcome", "phase-2"),
    (
        "PhysicalRecoveryRefusal::recovery_effects",
        "entry/outcome",
        "phase-2",
    ),
    ("PhysicalRecoveryRefusalKind", "entry/outcome", "phase-2"),
    ("PhysicalRecoveryBlock", "entry/outcome", "phase-3"),
    (
        "PhysicalRecoveryPublicationIndeterminate",
        "entry/outcome",
        "phase-6",
    ),
    (
        "RecoveryOperationFateSet",
        "handoff/operation_fates",
        "phase-4",
    ),
    (
        "RecoveryCleanupPosture",
        "handoff/cleanup_posture",
        "phase-7",
    ),
    (
        "RecoveryReportEnvelope",
        "observation/report/model",
        "phase-8",
    ),
    (
        "RecoveryObserverReport",
        "worth-store-offline-verifier/c8-recovery-observation/report",
        "phase-8",
    ),
    (
        "StoreRecoveryBindingFreshnessSample",
        "worth-store/recovery-freshness/binding",
        "phase-4",
    ),
    (
        "StoreRecoveryCleanupFreshnessSample",
        "worth-store/recovery-freshness/cleanup",
        "phase-7",
    ),
];
