pub(super) const PHASE_FOUR_DELIVERY_SURFACES: &[(&str, &str, &str)] = &[
    (
        "BoundedRecoveryFilesystemDiscovery::read_extent",
        "worth-store-physical-backend/recovery-media/discovery/addressed-payload",
        "phase-4",
    ),
    (
        "BoundedRecoveryFilesystemDiscovery::read_extent_manifest",
        "worth-store-physical-backend/recovery-media/discovery/addressed-payload",
        "phase-4",
    ),
    (
        "BoundedRecoveryFilesystemDiscovery::read_segment",
        "worth-store-physical-backend/recovery-media/discovery/addressed-payload",
        "phase-4",
    ),
    (
        "BoundedRecoveryFilesystemDiscovery::read_segment_manifest",
        "worth-store-physical-backend/recovery-media/discovery/addressed-payload",
        "phase-4",
    ),
    (
        "PhysicalCheckpointSecurityBinding",
        "worth-store-physical-format/checkpoint/source",
        "phase-4",
    ),
    (
        "PhysicalCheckpointSecurityBinding::digest",
        "worth-store-physical-format/checkpoint/source",
        "phase-4",
    ),
    (
        "PhysicalCheckpointSecurityBinding::idempotency_retention_generations",
        "worth-store-physical-format/checkpoint/source",
        "phase-4",
    ),
    (
        "PhysicalCheckpointSecurityBinding::policy_identity",
        "worth-store-physical-format/checkpoint/source",
        "phase-4",
    ),
    (
        "PhysicalCheckpointSource::secured_concurrent",
        "worth-store-physical-format/checkpoint/source",
        "phase-4",
    ),
    (
        "PhysicalCheckpointSource::security_binding",
        "worth-store-physical-format/checkpoint/source",
        "phase-4",
    ),
    (
        "PlannedPhysicalRecovery::cancel_before_execution",
        "progression/planned",
        "phase-4",
    ),
    (
        "PlannedPhysicalRecovery::discovery_counters",
        "progression/planned",
        "phase-4",
    ),
    (
        "PlannedPhysicalRecovery::freshness_sample",
        "progression/planned",
        "phase-4",
    ),
    (
        "PlannedPhysicalRecovery::operation_fates",
        "progression/planned",
        "phase-4",
    ),
    (
        "PlannedPhysicalRecovery::plan_cost",
        "progression/planned",
        "phase-4",
    ),
    (
        "PlannedPhysicalRecovery::planning_counters",
        "progression/planned",
        "phase-4",
    ),
    (
        "PlannedPhysicalRecovery::redo_plan",
        "progression/planned",
        "phase-4",
    ),
    (
        "PlannedPhysicalRecovery::selected_sources",
        "progression/planned",
        "phase-4",
    ),
    (
        "PlannedPhysicalRecovery::store_identity",
        "progression/planned",
        "phase-4",
    ),
    (
        "RecoveryOperationFateSet::acknowledged_durable",
        "handoff/operation_fates",
        "phase-4",
    ),
    (
        "RecoveryOperationFateSet::durable_unacknowledged",
        "handoff/operation_fates",
        "phase-4",
    ),
    (
        "RecoveryOperationFateSet::indeterminate",
        "handoff/operation_fates",
        "phase-4",
    ),
    (
        "RecoveryOperationFateSet::operations",
        "handoff/operation_fates",
        "phase-4",
    ),
    (
        "RecoveryOperationFateSet::proven_no_effect",
        "handoff/operation_fates",
        "phase-4",
    ),
    (
        "SelectedPhysicalRecovery::plan",
        "progression/selected",
        "phase-4",
    ),
    (
        "StoreRecoveryBindingFreshness",
        "worth-store/recovery-freshness/binding",
        "phase-4",
    ),
    (
        "StoreRecoveryBindingFreshnessSample::operations",
        "worth-store/recovery-freshness/binding/accessors",
        "phase-4",
    ),
    (
        "StoreRecoveryBindingFreshnessSample::policy_identity",
        "worth-store/recovery-freshness/binding/accessors",
        "phase-4",
    ),
    (
        "StoreRecoveryBindingFreshnessSample::sealed_basis_identity",
        "worth-store/recovery-freshness/binding/accessors",
        "phase-4",
    ),
    (
        "StoreRecoveryBindingFreshnessSample::selected_checkpoint_generation",
        "worth-store/recovery-freshness/binding/accessors",
        "phase-4",
    ),
    (
        "StoreRecoveryBindingFreshnessSample::store_identity",
        "worth-store/recovery-freshness/binding/accessors",
        "phase-4",
    ),
    (
        "StoreRecoveryBindingFreshnessSample::wal_members",
        "worth-store/recovery-freshness/binding/accessors",
        "phase-4",
    ),
    (
        "StoreRecoveryBindingSampleDenial",
        "worth-store/recovery-freshness/binding",
        "phase-4",
    ),
    (
        "StoreRecoveryBindingSampleFailure",
        "worth-store/recovery-freshness/binding/failure",
        "phase-4",
    ),
    (
        "StoreRecoveryBindingSampleFailure::denial",
        "worth-store/recovery-freshness/binding/failure",
        "phase-4",
    ),
    (
        "StoreRecoveryBindingSampleFailure::freshness_expired",
        "worth-store/recovery-freshness/binding/failure",
        "phase-4",
    ),
    (
        "StoreRecoveryBindingSampleFailure::freshness_retained",
        "worth-store/recovery-freshness/binding/failure",
        "phase-4",
    ),
    (
        "StoreRecoveryBindingSampleFailure::operation_bindings_observed",
        "worth-store/recovery-freshness/binding/failure",
        "phase-4",
    ),
    (
        "StoreRecoveryBindingSampleFailure::redo_bytes_observed",
        "worth-store/recovery-freshness/binding/failure",
        "phase-4",
    ),
    (
        "StoreRecoveryBindingSampleFailure::wal_members_observed",
        "worth-store/recovery-freshness/binding/failure",
        "phase-4",
    ),
    (
        "StoreRecoveryOperationEvidence",
        "worth-store/recovery-freshness/binding",
        "phase-4",
    ),
    (
        "StoreRecoveryOperationEvidence::fate",
        "worth-store/recovery-freshness/binding/accessors",
        "phase-4",
    ),
    (
        "StoreRecoveryOperationEvidence::freshness",
        "worth-store/recovery-freshness/binding/accessors",
        "phase-4",
    ),
    (
        "StoreRecoveryOperationEvidence::idempotency_identity",
        "worth-store/recovery-freshness/binding/accessors",
        "phase-4",
    ),
    (
        "StoreRecoveryOperationEvidence::lease_expiry_generation",
        "worth-store/recovery-freshness/binding/accessors",
        "phase-4",
    ),
    (
        "StoreRecoveryOperationEvidence::lease_issuance_generation",
        "worth-store/recovery-freshness/binding/accessors",
        "phase-4",
    ),
    (
        "StoreRecoveryOperationEvidence::mutation_identity",
        "worth-store/recovery-freshness/binding/accessors",
        "phase-4",
    ),
    (
        "StoreRecoveryOperationEvidence::request_fingerprint",
        "worth-store/recovery-freshness/binding/accessors",
        "phase-4",
    ),
    (
        "StoreRecoveryOperationFate",
        "worth-store/recovery-freshness/binding",
        "phase-4",
    ),
    (
        "StoreRecoveryWalMember",
        "worth-store/recovery-freshness/binding",
        "phase-4",
    ),
    (
        "StoreRecoveryWalMember::canonical_redo",
        "worth-store/recovery-freshness/binding/accessors",
        "phase-4",
    ),
    (
        "StoreRecoveryWalMember::lsn_range",
        "worth-store/recovery-freshness/binding/accessors",
        "phase-4",
    ),
    (
        "StoreRecoveryWalMember::operation_identity",
        "worth-store/recovery-freshness/binding/accessors",
        "phase-4",
    ),
    (
        "StoreRecoveryWalMember::group_identity",
        "worth-store/recovery-freshness/binding/accessors",
        "phase-4",
    ),
    (
        "StoreRecoveryWalMember::group_member_count",
        "worth-store/recovery-freshness/binding/accessors",
        "phase-4",
    ),
    (
        "StoreRecoveryWalMember::group_member_identity",
        "worth-store/recovery-freshness/binding/accessors",
        "phase-4",
    ),
    (
        "StoreRecoveryWalMember::group_member_ordinal",
        "worth-store/recovery-freshness/binding/accessors",
        "phase-4",
    ),
    (
        "StoreRecoveryWalMember::group_membership_digest",
        "worth-store/recovery-freshness/binding/accessors",
        "phase-4",
    ),
    (
        "VerifiedCheckpointStream::binding_records",
        "worth-store-physical-format/checkpoint/inspection",
        "phase-4",
    ),
    (
        "VerifiedWalFrame",
        "worth-store-wal/artifact-store/segment-inventory/segment-inspection/owned-frame",
        "phase-4",
    ),
    (
        "VerifiedWalFrame::lsn_range",
        "worth-store-wal/artifact-store/segment-inventory/segment-inspection/owned-frame",
        "phase-4",
    ),
    (
        "VerifiedWalFrame::payload",
        "worth-store-wal/artifact-store/segment-inventory/segment-inspection/owned-frame",
        "phase-4",
    ),
    (
        "VerifiedWalFramePayload::to_owned_verified",
        "worth-store-wal/artifact-store/segment-inventory/segment-inspection",
        "phase-4",
    ),
    (
        "artifact_store::VerifiedWalFrame",
        "worth-store-wal/artifact-store/segment-inventory/segment-inspection/owned-frame",
        "phase-4",
    ),
    (
        "artifact_store::VerifiedWalFrame::lsn_range",
        "worth-store-wal/artifact-store/segment-inventory/segment-inspection/owned-frame",
        "phase-4",
    ),
    (
        "artifact_store::VerifiedWalFrame::payload",
        "worth-store-wal/artifact-store/segment-inventory/segment-inspection/owned-frame",
        "phase-4",
    ),
    (
        "artifact_store::VerifiedWalFramePayload::to_owned_verified",
        "worth-store-wal/artifact-store/segment-inventory/segment-inspection",
        "phase-4",
    ),
];
