pub(super) const PHASE_FIVE_DELIVERY_SURFACES: &[(&str, &str, &str)] = &[
    ("StagedPhysicalRecovery", "progression/staged", "phase-5"),
    (
        "ClosedRecoveryStagingGeneration",
        "progression/staged",
        "phase-5",
    ),
    (
        "ClosedRecoveryStagingGeneration::artifact_count",
        "progression/staged",
        "phase-5",
    ),
    (
        "ClosedRecoveryStagingGeneration::byte_count",
        "progression/staged",
        "phase-5",
    ),
    (
        "ClosedRecoveryStagingGeneration::content_identity",
        "progression/staged",
        "phase-5",
    ),
    (
        "ClosedRecoveryStagingGeneration::generation",
        "progression/staged",
        "phase-5",
    ),
    (
        "StagedPhysicalRecovery::base_image",
        "progression/staged",
        "phase-5",
    ),
    (
        "StagedPhysicalRecovery::closed_generation",
        "progression/staged",
        "phase-5",
    ),
    (
        "StagedPhysicalRecovery::discovery_counters",
        "progression/staged",
        "phase-5",
    ),
    (
        "StagedPhysicalRecovery::freshness_sample",
        "progression/staged",
        "phase-5",
    ),
    (
        "StagedPhysicalRecovery::is_quiescent",
        "progression/staged",
        "phase-5",
    ),
    (
        "StagedPhysicalRecovery::operation_fates",
        "progression/staged",
        "phase-5",
    ),
    (
        "StagedPhysicalRecovery::planning_counters",
        "progression/staged",
        "phase-5",
    ),
    (
        "StagedPhysicalRecovery::publication_plan",
        "progression/staged",
        "phase-5",
    ),
    (
        "StagedPhysicalRecovery::quiescence_plan",
        "progression/staged",
        "phase-5",
    ),
    (
        "StagedPhysicalRecovery::selected_sources",
        "progression/staged",
        "phase-5",
    ),
    (
        "StagedPhysicalRecovery::staging_counters",
        "progression/staged",
        "phase-5",
    ),
    (
        "StagedPhysicalRecovery::staging_settlements",
        "progression/staged",
        "phase-5",
    ),
    (
        "StagedPhysicalRecovery::cancel_before_publication",
        "progression/staged",
        "phase-5",
    ),
    (
        "StagedPhysicalRecovery::store_identity",
        "progression/staged",
        "phase-5",
    ),
    (
        "PhysicalRecoveryStagingCounters",
        "entry/staging",
        "phase-5",
    ),
    ("PhysicalRecoveryStagingDenial", "entry/staging", "phase-5"),
    (
        "PhysicalRecoveryStagingSettlement",
        "entry/staging",
        "phase-5",
    ),
    (
        "PhysicalRecoveryStagingSettlementLedger",
        "entry/staging",
        "phase-5",
    ),
    (
        "PhysicalRecoveryStagingSettlementLedger::completed",
        "entry/staging",
        "phase-5",
    ),
    (
        "PhysicalRecoveryStagingSettlementLedger::entries",
        "entry/staging",
        "phase-5",
    ),
    (
        "PlannedPhysicalRecovery::stage",
        "progression/planned",
        "phase-5",
    ),
    (
        "PhysicalRecoveryStagingCancellation",
        "progression/planned/cancellation",
        "phase-5",
    ),
    (
        "PlannedPhysicalRecovery::cancellation_after_command",
        "progression/planned",
        "phase-5",
    ),
    (
        "PlannedPhysicalRecovery::stage_with_cancellation",
        "progression/planned",
        "phase-5",
    ),
];
