pub(super) const RUNTIME_PHASE_THREE_SURFACES: &[(&str, &str, &str)] = &[
    ("PhysicalRecoveryBlock", "entry/outcome", "phase-3"),
    (
        "PhysicalRecoveryBlock::evidence",
        "entry/outcome",
        "phase-3",
    ),
    (
        "PhysicalRecoveryBlock::recovery_effects",
        "entry/outcome",
        "phase-3",
    ),
    (
        "PhysicalRecoveryBlock::session_identity",
        "entry/outcome",
        "phase-3",
    ),
    (
        "PhysicalRecoveryBlock::store_identity",
        "entry/outcome",
        "phase-3",
    ),
    ("PhysicalRecoveryBlockEvidence", "entry/outcome", "phase-3"),
    ("PhysicalRecoveryBlockKind", "entry/outcome", "phase-3"),
    (
        "PhysicalRecoverySourceDenial",
        "entry/source_denial",
        "phase-3",
    ),
    (
        "PhysicalRecoveryMediaObservationFailure",
        "entry/source_denial",
        "phase-3",
    ),
    (
        "PhysicalManifestObservationDenial",
        "entry/source_denial",
        "phase-3",
    ),
    ("PhysicalRecoveryLimitDimension", "entry/outcome", "phase-3"),
    ("PhysicalRecoveryLimitFailure", "entry/outcome", "phase-3"),
    (
        "AdmittedPhysicalRecovery::discover",
        "progression/admitted",
        "phase-3",
    ),
    (
        "DiscoveredPhysicalRecovery",
        "progression/discovered",
        "phase-3",
    ),
    (
        "DiscoveredPhysicalRecovery::counters",
        "progression/discovered",
        "phase-3",
    ),
    (
        "DiscoveredPhysicalRecovery::select",
        "progression/discovered",
        "phase-3",
    ),
    (
        "PhysicalRecoveryDiscoveryCounters",
        "progression/discovered",
        "phase-3",
    ),
    (
        "SelectedPhysicalRecovery",
        "progression/selected",
        "phase-3",
    ),
    (
        "SelectedPhysicalRecovery::cancel_before_reconstruction",
        "progression/selected",
        "phase-3",
    ),
    (
        "SelectedPhysicalRecovery::checkpoint_identity",
        "progression/selected",
        "phase-3",
    ),
    (
        "SelectedPhysicalRecovery::compaction_generation",
        "progression/selected",
        "phase-3",
    ),
    (
        "SelectedPhysicalRecovery::discovery_counters",
        "progression/selected",
        "phase-3",
    ),
    (
        "SelectedPhysicalRecovery::distinct_page_and_extent_count",
        "progression/selected",
        "phase-3",
    ),
    (
        "SelectedPhysicalRecovery::residue_count",
        "progression/selected",
        "phase-3",
    ),
    (
        "SelectedPhysicalRecovery::root_generation",
        "progression/selected",
        "phase-3",
    ),
    (
        "SelectedPhysicalRecovery::root_role",
        "progression/selected",
        "phase-3",
    ),
    (
        "SelectedPhysicalRecovery::selected_page_fact_count",
        "progression/selected",
        "phase-3",
    ),
    (
        "SelectedPhysicalRecovery::store_identity",
        "progression/selected",
        "phase-3",
    ),
    (
        "SelectedPhysicalRecovery::source_trace",
        "progression/selected",
        "phase-3",
    ),
    (
        "SelectedPhysicalRecovery::wal_frame_count",
        "progression/selected",
        "phase-3",
    ),
    (
        "SelectedPhysicalRecovery::wal_segment_count",
        "progression/selected",
        "phase-3",
    ),
];
