pub(super) const PHASE_EIGHT_DELIVERY_SURFACES: &[(&str, &str, &str)] = &[
    ("RecoveryReportEnvelope", "observation/report", "phase-8"),
    (
        "RecoveryReportEnvelope::from_outcome",
        "observation/report",
        "phase-8",
    ),
    (
        "RecoveryReportEnvelope::encode",
        "observation/report",
        "phase-8",
    ),
    (
        "RecoveryReportEnvelope::decode",
        "observation/report",
        "phase-8",
    ),
    (
        "RecoveryReportEnvelope::outcome",
        "observation/report",
        "phase-8",
    ),
    (
        "RecoveryReportEnvelope::store_identity",
        "observation/report",
        "phase-8",
    ),
    (
        "RecoveryReportEnvelope::root_generation",
        "observation/report",
        "phase-8",
    ),
    (
        "RecoveryReportEnvelope::counters",
        "observation/report",
        "phase-8",
    ),
    ("RecoveryReportOutcome", "observation/report", "phase-8"),
    ("RecoveryReportCounters", "observation/counters", "phase-8"),
    (
        "RecoveryReportCounters::recovery_effects",
        "observation/counters",
        "phase-8",
    ),
    (
        "RecoveryReportCounters::cleanup_performed",
        "observation/counters",
        "phase-8",
    ),
    (
        "RecoveryReportCounters::cleanup_deferred",
        "observation/counters",
        "phase-8",
    ),
    (
        "RecoveryReportDecodeDenial",
        "observation/protocol",
        "phase-8",
    ),
    (
        "RECOVERY_REPORT_PROTOCOL",
        "observation/protocol",
        "phase-8",
    ),
    ("RECOVERY_REPORT_VERSION", "observation/protocol", "phase-8"),
    (
        "RECOVERY_REPORT_COMPATIBILITY_WINDOW",
        "observation/protocol",
        "phase-8",
    ),
    (
        "RecoveryObserverReport",
        "worth-store-offline-verifier/c8-recovery-observation/report",
        "phase-8",
    ),
    (
        "observe_recovery_artifacts",
        "worth-store-offline-verifier/c8-recovery-observation/report",
        "phase-8",
    ),
    (
        "RecoveryObserverLimits",
        "worth-store-offline-verifier/c8-recovery-observation/artifact-walk",
        "phase-8",
    ),
    (
        "RecoveryObserverDecodeDenial",
        "worth-store-offline-verifier/c8-recovery-observation/report-protocol",
        "phase-8",
    ),
];
