pub(super) const SUPPORTING_DELIVERY_SURFACES: &[(&str, &str, &str)] = &[
    (
        "ArtifactTreeAccessLimit",
        "worth-store-physical-backend/filesystem-media/artifact-tree/failure",
        "phase-3",
    ),
    (
        "ArtifactTreeFailure::access_limit",
        "worth-store-physical-backend/filesystem-media/artifact-tree/failure",
        "phase-3",
    ),
    (
        "ArtifactTreeMedia::list_bounded",
        "worth-store-physical-backend/filesystem-media/artifact-tree/media",
        "phase-3",
    ),
    (
        "ArtifactTreeReplacement",
        "worth-store-physical-backend/filesystem-media/artifact-tree/publication-effect/outcome",
        "phase-2",
    ),
    (
        "ArtifactTreeReplacement::destination",
        "worth-store-physical-backend/filesystem-media/artifact-tree/publication-effect/outcome",
        "phase-2",
    ),
    (
        "ArtifactTreeReplacement::new",
        "worth-store-physical-backend/filesystem-media/artifact-tree/publication-effect/outcome",
        "phase-2",
    ),
    (
        "ArtifactTreeReplacement::source",
        "worth-store-physical-backend/filesystem-media/artifact-tree/publication-effect/outcome",
        "phase-2",
    ),
    (
        "RootProfileQualificationReport::profile_digest",
        "worth-store-physical-backend/filesystem-media/qualification-report",
        "phase-2",
    ),
    (
        "DurableRootSelector",
        "worth-store-physical-format/root-selector",
        "phase-2",
    ),
    (
        "DurableRootSelector::decode",
        "worth-store-physical-format/root-selector",
        "phase-2",
    ),
    (
        "DurableRootSelector::encode",
        "worth-store-physical-format/root-selector",
        "phase-2",
    ),
    (
        "DurableRootSelector::format",
        "worth-store-physical-format/root-selector",
        "phase-2",
    ),
    (
        "DurableRootSelector::identity",
        "worth-store-physical-format/root-selector",
        "phase-2",
    ),
    (
        "DurableRootSelector::linked_root_generation",
        "worth-store-physical-format/root-selector",
        "phase-2",
    ),
    (
        "DurableRootSelector::linked_selector",
        "worth-store-physical-format/root-selector",
        "phase-2",
    ),
    (
        "DurableRootSelector::new",
        "worth-store-physical-format/root-selector",
        "phase-2",
    ),
    (
        "DurableRootSelector::role",
        "worth-store-physical-format/root-selector",
        "phase-2",
    ),
    (
        "DurableRootSelector::root_generation",
        "worth-store-physical-format/root-selector",
        "phase-2",
    ),
    (
        "DurableRootSelector::store_identity",
        "worth-store-physical-format/root-selector",
        "phase-2",
    ),
    (
        "ROOT_SELECTOR_BYTES",
        "worth-store-physical-format/root-selector",
        "phase-2",
    ),
    (
        "RootSelectorDecodeDenial",
        "worth-store-physical-format/root-selector",
        "phase-2",
    ),
    (
        "RootSelectorIdentity",
        "worth-store-physical-format/root-selector",
        "phase-2",
    ),
    (
        "RootSelectorIdentity::get",
        "worth-store-physical-format/root-selector",
        "phase-2",
    ),
    (
        "RootSelectorIdentity::new",
        "worth-store-physical-format/root-selector",
        "phase-2",
    ),
    (
        "RootSelectorRole",
        "worth-store-physical-format/root-selector",
        "phase-2",
    ),
    (
        "PersistedCompactionCutoverRecord",
        "worth-store-physical-format/checkpoint/compaction-cutover-record",
        "phase-3",
    ),
    (
        "PersistedCompactionCutoverRecord::checkpoint",
        "worth-store-physical-format/checkpoint/compaction-cutover-record",
        "phase-3",
    ),
    (
        "PersistedCompactionCutoverRecord::checkpoint_wal",
        "worth-store-physical-format/checkpoint/compaction-cutover-record",
        "phase-3",
    ),
    (
        "PersistedCompactionCutoverRecord::product_generation",
        "worth-store-physical-format/checkpoint/compaction-cutover-record",
        "phase-3",
    ),
    (
        "PersistedCompactionCutoverRecord::product_role",
        "worth-store-physical-format/checkpoint/compaction-cutover-record",
        "phase-3",
    ),
    (
        "PersistedCompactionCutoverRecord::root",
        "worth-store-physical-format/checkpoint/compaction-cutover-record",
        "phase-3",
    ),
    (
        "PersistedCompactionCutoverRecord::wal_cutoff_lsn_exclusive",
        "worth-store-physical-format/checkpoint/compaction-cutover-record",
        "phase-3",
    ),
    (
        "PersistedCompactionProductRole",
        "worth-store-physical-format/checkpoint/compaction-cutover-record",
        "phase-3",
    ),
    (
        "VerifiedCheckpointStream",
        "worth-store-physical-format/checkpoint/inspection",
        "phase-3",
    ),
    (
        "VerifiedCheckpointStream::compaction_cutover",
        "worth-store-physical-format/checkpoint/inspection",
        "phase-3",
    ),
    (
        "VerifiedCheckpointStream::encoded_bytes",
        "worth-store-physical-format/checkpoint/inspection",
        "phase-3",
    ),
    (
        "VerifiedCheckpointStream::footer",
        "worth-store-physical-format/checkpoint/inspection",
        "phase-3",
    ),
    (
        "VerifiedCheckpointStream::source",
        "worth-store-physical-format/checkpoint/inspection",
        "phase-3",
    ),
    (
        "inspect_checkpoint_stream",
        "worth-store-physical-format/checkpoint/inspection",
        "phase-3",
    ),
];
