#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum OperationalRecoveryYieldpoint {
    BeforeForensicSourceAcquisition,
    AfterForensicSourceRecord,
    BeforeForensicFinalization,
    AfterForensicFinalization,
    BeforeBootstrapTransfer,
    AfterBootstrapTransfer,
    BeforeBootstrapControlRecord,
    AfterBootstrapControlRecord,
    BeforeBootstrapPostVerification,
    AfterBootstrapPostVerification,
    BeforeBootstrapCompletion,
    AfterBootstrapCompletion,
    BeforePromotionExternalFence,
    AfterPromotionExternalFence,
    BeforePromotionFenceRecord,
    AfterPromotionFenceRecord,
    BeforePromotionRecord,
    AfterPromotionRecord,
    BeforePromotionPostVerification,
    AfterPromotionPostVerification,
    BeforePromotionPublication,
    AfterPromotionPublication,
    BeforePromotionReadmission,
    AfterPromotionReadmission,
    BeforeOldPrimaryRejoinPlan,
    AfterOldPrimaryRejoinPlan,
    BeforeOldPrimaryRejoinExecution,
    AfterOldPrimaryRejoinExecution,
    BeforeOldPrimaryRejoinCompletion,
    AfterOldPrimaryRejoinCompletion,
    BeforeAuditDerivation,
    AfterAuditDerivation,
    BeforeAuditExport,
    AfterAuditExport,
}

impl OperationalRecoveryYieldpoint {
    pub const ALL: [Self; 34] = [
        Self::BeforeForensicSourceAcquisition,
        Self::AfterForensicSourceRecord,
        Self::BeforeForensicFinalization,
        Self::AfterForensicFinalization,
        Self::BeforeBootstrapTransfer,
        Self::AfterBootstrapTransfer,
        Self::BeforeBootstrapControlRecord,
        Self::AfterBootstrapControlRecord,
        Self::BeforeBootstrapPostVerification,
        Self::AfterBootstrapPostVerification,
        Self::BeforeBootstrapCompletion,
        Self::AfterBootstrapCompletion,
        Self::BeforePromotionExternalFence,
        Self::AfterPromotionExternalFence,
        Self::BeforePromotionFenceRecord,
        Self::AfterPromotionFenceRecord,
        Self::BeforePromotionRecord,
        Self::AfterPromotionRecord,
        Self::BeforePromotionPostVerification,
        Self::AfterPromotionPostVerification,
        Self::BeforePromotionPublication,
        Self::AfterPromotionPublication,
        Self::BeforePromotionReadmission,
        Self::AfterPromotionReadmission,
        Self::BeforeOldPrimaryRejoinPlan,
        Self::AfterOldPrimaryRejoinPlan,
        Self::BeforeOldPrimaryRejoinExecution,
        Self::AfterOldPrimaryRejoinExecution,
        Self::BeforeOldPrimaryRejoinCompletion,
        Self::AfterOldPrimaryRejoinCompletion,
        Self::BeforeAuditDerivation,
        Self::AfterAuditDerivation,
        Self::BeforeAuditExport,
        Self::AfterAuditExport,
    ];

    pub const fn token(self) -> &'static str {
        match self {
            Self::BeforeForensicSourceAcquisition => "s10-forensic-before-source-acquisition",
            Self::AfterForensicSourceRecord => "s10-forensic-after-source-record",
            Self::BeforeForensicFinalization => "s10-forensic-before-finalization",
            Self::AfterForensicFinalization => "s10-forensic-after-finalization",
            Self::BeforeBootstrapTransfer => "s10-bootstrap-before-transfer",
            Self::AfterBootstrapTransfer => "s10-bootstrap-after-transfer",
            Self::BeforeBootstrapControlRecord => "s10-bootstrap-before-control-record",
            Self::AfterBootstrapControlRecord => "s10-bootstrap-after-control-record",
            Self::BeforeBootstrapPostVerification => "s10-bootstrap-before-post-verification",
            Self::AfterBootstrapPostVerification => "s10-bootstrap-after-post-verification",
            Self::BeforeBootstrapCompletion => "s10-bootstrap-before-completion",
            Self::AfterBootstrapCompletion => "s10-bootstrap-after-completion",
            Self::BeforePromotionExternalFence => "s10-promotion-before-external-fence",
            Self::AfterPromotionExternalFence => "s10-promotion-after-external-fence",
            Self::BeforePromotionFenceRecord => "s10-promotion-before-fence-record",
            Self::AfterPromotionFenceRecord => "s10-promotion-after-fence-record",
            Self::BeforePromotionRecord => "s10-promotion-before-record",
            Self::AfterPromotionRecord => "s10-promotion-after-record",
            Self::BeforePromotionPostVerification => "s10-promotion-before-post-verification",
            Self::AfterPromotionPostVerification => "s10-promotion-after-post-verification",
            Self::BeforePromotionPublication => "s10-promotion-before-publication",
            Self::AfterPromotionPublication => "s10-promotion-after-publication",
            Self::BeforePromotionReadmission => "s10-promotion-before-readmission",
            Self::AfterPromotionReadmission => "s10-promotion-after-readmission",
            Self::BeforeOldPrimaryRejoinPlan => "s10-promotion-before-old-primary-rejoin-plan",
            Self::AfterOldPrimaryRejoinPlan => "s10-promotion-after-old-primary-rejoin-plan",
            Self::BeforeOldPrimaryRejoinExecution => "s10-rejoin-before-owner-execution",
            Self::AfterOldPrimaryRejoinExecution => "s10-rejoin-after-owner-execution",
            Self::BeforeOldPrimaryRejoinCompletion => "s10-rejoin-before-completion-record",
            Self::AfterOldPrimaryRejoinCompletion => "s10-rejoin-after-completion-record",
            Self::BeforeAuditDerivation => "s10-audit-before-derivation",
            Self::AfterAuditDerivation => "s10-audit-after-derivation",
            Self::BeforeAuditExport => "s10-audit-before-export",
            Self::AfterAuditExport => "s10-audit-after-export",
        }
    }
}
