use crate::evidence_identity::WorthQueryEvidenceScope;

const SUBSCRIPTION_IDENTITY_SCOPE: WorthQueryEvidenceScope =
    WorthQueryEvidenceScope::SubscriptionActivationReceipt;

mod acknowledgement;
mod activation;
mod delivery;
mod diagnostic_bundle;
mod diagnostic_source;
mod diagnostic_trace;
mod lifecycle_certification;
mod lifecycle_context;
mod lifecycle_delivery;
mod lifecycle_maintenance;
mod manual_bridge;
mod preview;
mod preview_residue;
mod scale;
mod support;

pub(super) use acknowledgement::lifecycle_acknowledgement_frontier_identity;
#[cfg(test)]
pub(super) use acknowledgement::lifecycle_continuation_endpoint_identity;
#[cfg(test)]
pub(super) use acknowledgement::lifecycle_continuation_ordinary_checkpoint_identity;
pub(super) use acknowledgement::subscription_performance_receipt_source_identity;
pub(super) use activation::activation_checkpoint_identity;
pub(super) use activation::activation_input_identity;
pub(super) use activation::admission_artifact_identity;
pub(super) use activation::basis_binding_request_identity;
pub(super) use activation::bridge_lowering_plan_identity;
pub(super) use activation::query_subscription_declaration_identity;
pub(super) use activation::signal_strategy_request_identity;
pub(super) use delivery::delivery_cause_evidence_label_identity;
pub(super) use delivery::delivery_cause_identity;
pub(super) use delivery::live_delivery_intent_projection_identity;
pub(super) use delivery::live_relevance_identity;
pub(super) use delivery::patch_group_identity;
pub(super) use delivery::slice_intent_identity;
pub(super) use delivery::subscription_fanout_plan_identity;
pub(super) use delivery::subscription_fanout_report_identity;
pub(super) use diagnostic_bundle::diagnostic_admitted_bundle_identity;
pub(super) use diagnostic_bundle::diagnostic_assembly_receipt_identity;
pub(super) use diagnostic_bundle::diagnostic_bundle_width_identity;
pub(super) use diagnostic_bundle::diagnostic_counters_identity;
pub(super) use diagnostic_bundle::diagnostic_denied_bundle_identity;
pub(super) use diagnostic_bundle::diagnostic_failure_identity;
pub(super) use diagnostic_bundle::diagnostic_semantic_labels_identity;
pub(super) use diagnostic_source::diagnostic_source_identity;
pub(super) use diagnostic_trace::diagnostic_evidence_identity;
pub(super) use diagnostic_trace::diagnostic_selection_context_denied_identity;
pub(super) use diagnostic_trace::diagnostic_selection_context_selected_identity;
pub(super) use diagnostic_trace::diagnostic_stage_trace_identity;
pub(super) use diagnostic_trace::diagnostic_trace_identity;
pub(super) use lifecycle_certification::lifecycle_active_delivery_density_posture_identity;
pub(super) use lifecycle_certification::lifecycle_active_lane_lookup_class_identity;
pub(super) use lifecycle_certification::lifecycle_allocation_posture_identity;
pub(super) use lifecycle_certification::lifecycle_certification_bundle_identity;
pub(super) use lifecycle_certification::lifecycle_context_basis_posture_identity;
pub(super) use lifecycle_certification::lifecycle_context_view_shape_identity;
pub(super) use lifecycle_certification::lifecycle_preview_promotion_residue_identity;
pub(super) use lifecycle_certification::lifecycle_subscription_budget_identity;
pub(super) use lifecycle_context::lifecycle_absent_continuation_identity;
pub(super) use lifecycle_context::lifecycle_absent_performance_receipt_identity;
pub(super) use lifecycle_context::lifecycle_absent_preview_isolation_identity;
pub(super) use lifecycle_context::lifecycle_absent_preview_residue_identity;
#[cfg(test)]
pub(super) use lifecycle_context::lifecycle_absent_work_packet_identity;
pub(super) use lifecycle_context::lifecycle_active_lane_handle_identity;
pub(super) use lifecycle_context::lifecycle_context_collection_absent_identity;
pub(super) use lifecycle_context::lifecycle_context_policy_identity;
pub(super) use lifecycle_context::lifecycle_context_query_identity;
pub(super) use lifecycle_context::lifecycle_context_relationship_proof_identity;
pub(super) use lifecycle_context::lifecycle_context_tenant_basis_identity;
pub(super) use lifecycle_context::lifecycle_counter_sequence_identity;
pub(super) use lifecycle_context::lifecycle_labeled_counter_identity;
pub(super) use lifecycle_context::lifecycle_performance_sequence_identity;
pub(super) use lifecycle_context::lifecycle_subscription_equivalence_identity;
pub(super) use lifecycle_context::lifecycle_subscription_family_identity;
pub(super) use lifecycle_context::lifecycle_support_matrix_identity;
pub(super) use lifecycle_delivery::lifecycle_closeout_identity;
#[cfg(test)]
pub(super) use lifecycle_delivery::lifecycle_continuation_identity;
pub(super) use lifecycle_delivery::lifecycle_delivery_batch_identity;
pub(super) use lifecycle_delivery::lifecycle_delivery_batch_receipt_identity;
pub(super) use lifecycle_delivery::lifecycle_work_packet_identity;
pub(super) use lifecycle_maintenance::lifecycle_delivery_window_identity;
pub(super) use lifecycle_maintenance::lifecycle_maintenance_delta_identity;
pub(super) use lifecycle_maintenance::lifecycle_maintenance_delta_identity_typed;
pub(super) use lifecycle_maintenance::lifecycle_maintenance_delta_scope_identity;
pub(super) use manual_bridge::manual_bridge_witness_identity;
pub(super) use preview::preview_authoritative_sharing_denial_identity;
pub(super) use preview::preview_discard_closeout_identity;
#[cfg(test)]
pub(super) use preview::preview_epoch_identity;
#[cfg(test)]
pub(super) use preview::preview_isolation_identity;
pub(super) use preview::preview_promotion_authority_identity;
pub(super) use preview::preview_promotion_handoff_identity;
pub(super) use preview::preview_promotion_rebinding_identity;
pub(super) use preview_residue::preview_residue_report_identity;
pub(super) use scale::active_lane_identity;
pub(super) use scale::certification_activation_bundle_identity;
pub(super) use scale::scale_counter_snapshot_identity;
pub(super) use scale::scale_slope_report_identity;
pub(super) use scale::typed_identity_drift;
pub(super) use support::subscription_family_capability_identity;
pub(super) use support::support_counters_identity;
pub(super) use support::support_lookup_receipt_identity;
pub(super) use support::support_matrix_identity;
pub(super) use support::support_matrix_row_identity;
pub(super) use support::support_report_identity;
pub(super) use support::support_subject_identity;
