#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
pub enum WorthUiRuntimeFactFamily {
    ActiveArtifact,
    ExecutionPlan,
    ThemeToken,
    Command,
    CommandProjection,
    DropdownSelectionState,
    ComponentInteractionState,
    QueryBinding,
    QueryResultPosture,
    QueryProjectionFact,
    QueryComputedView,
    QueryStateSnapshot,
    QueryEffectPosture,
    QueryRecoveryPosture,
    QueryInspectionTarget,
    LayoutTopology,
    LayoutGap,
    LayoutPadding,
    ContentMount,
    ShellSurface,
    ShellSlotAssignment,
    PageTemplate,
    PageInstance,
    PageInstanceTemplateBinding,
    PageContentSlot,
    SurfaceMount,
    AuthoredMountComponentSelection,
    AuthoredSurfaceProps,
    PrimitiveConstruction,
    PrimitiveContent,
    PrimitiveContainer,
    PrimitiveMeasurement,
    PrimitiveAppearance,
    PrimitiveAppearanceState,
    PrimitiveActiveAppearance,
    PrimitiveInteraction,
    PrimitiveMotion,
    PrimitiveFlowLayout,
    PrimitiveDrawPlan,
    PrimitiveEventGeometry,
    PrimitiveEventRegion,
    UserIntentTargetBinding,
    AuthoredQueryBindingShape,
    Component,
    Appearance,
    AppearanceRecipe,
    DensityToken,
    ActionPosture,
    LiveViewBinding,
    LiveViewDeclaration,
    LiveViewStateBinding,
    LiveViewStateValue,
    LiveViewControlProjection,
    LiveViewControlOptions,
    LiveViewConditionalProjection,
    LiveViewParticipation,
    LiveViewExpressionDeclaration,
    LiveViewExpressionProjection,
    LiveViewExpressionOutput,
    LiveViewReadinessProjection,
    LiveViewInteractionIntent,
    LiveViewPayloadProjection,
    CompositionRoot,
    CompositionNode,
    CompositionEdge,
    CompositionParticipation,
    CompositionPolicy,
    CompositionContext,
    CompositionContextOverride,
    CompositionContextPropagation,
    HostMeasurementObservation,
    LayoutAllocation,
    ViewportBoundary,
    ClipBoundary,
    ScrollRestoration,
    ViewportEventParticipation,
    CompositionTopology,
    CompositionRootMountAuthority,
    MosaicPlacementLegality,
    VirtualizedDataFrame,
    DurableStateFamily,
    OverlaySurface,
    ToastSurface,
    InspectorSurface,
    InteractionPolicy,
}

impl WorthUiRuntimeFactFamily {
    pub const fn token(self) -> &'static str {
        match self {
            Self::ActiveArtifact => "active_artifact",
            Self::ExecutionPlan => "execution_plan",
            Self::ThemeToken => "theme_token",
            Self::Command => "command",
            Self::CommandProjection => "command_projection",
            Self::DropdownSelectionState => "dropdown_selection_state",
            Self::ComponentInteractionState => "component_interaction_state",
            Self::QueryBinding => "query_binding",
            Self::QueryResultPosture => "query_result_posture",
            Self::QueryProjectionFact => "query_projection_fact",
            Self::QueryComputedView => "query_computed_view",
            Self::QueryStateSnapshot => "query_state_snapshot",
            Self::QueryEffectPosture => "query_effect_posture",
            Self::QueryRecoveryPosture => "query_recovery_posture",
            Self::QueryInspectionTarget => "query_inspection_target",
            Self::LayoutTopology => "layout_topology",
            Self::LayoutGap => "layout_gap",
            Self::LayoutPadding => "layout_padding",
            Self::ContentMount => "content_mount",
            Self::ShellSurface => "shell_surface",
            Self::ShellSlotAssignment => "shell_slot_assignment",
            Self::PageTemplate => "page_template",
            Self::PageInstance => "page_instance",
            Self::PageInstanceTemplateBinding => "page_instance_template_binding",
            Self::PageContentSlot => "page_content_slot",
            Self::SurfaceMount => "surface_mount",
            Self::AuthoredMountComponentSelection => "authored_mount_component_selection",
            Self::AuthoredSurfaceProps => "authored_surface_props",
            Self::PrimitiveConstruction => "primitive_construction",
            Self::PrimitiveContent => "primitive_content",
            Self::PrimitiveContainer => "primitive_container",
            Self::PrimitiveMeasurement => "primitive_measurement",
            Self::PrimitiveAppearance => "primitive_appearance",
            Self::PrimitiveAppearanceState => "primitive_appearance_state",
            Self::PrimitiveActiveAppearance => "primitive_active_appearance",
            Self::PrimitiveInteraction => "primitive_interaction",
            Self::PrimitiveMotion => "primitive_motion",
            Self::PrimitiveFlowLayout => "primitive_flow_layout",
            Self::PrimitiveDrawPlan => "primitive_draw_plan",
            Self::PrimitiveEventGeometry => "primitive_event_geometry",
            Self::PrimitiveEventRegion => "primitive_event_region",
            Self::UserIntentTargetBinding => "user_intent_target_binding",
            Self::AuthoredQueryBindingShape => "authored_query_binding_shape",
            Self::Component => "component",
            Self::Appearance => "appearance",
            Self::AppearanceRecipe => "appearance_recipe",
            Self::DensityToken => "density_token",
            Self::ActionPosture => "action_posture",
            Self::LiveViewBinding => "live_view_binding",
            Self::LiveViewDeclaration => "live_view_declaration",
            Self::LiveViewStateBinding => "live_view_state_binding",
            Self::LiveViewStateValue => "live_view_state_value",
            Self::LiveViewControlProjection => "live_view_control_projection",
            Self::LiveViewControlOptions => "live_view_control_options",
            Self::LiveViewConditionalProjection => "live_view_conditional_projection",
            Self::LiveViewParticipation => "live_view_participation",
            Self::LiveViewExpressionDeclaration => "live_view_expression_declaration",
            Self::LiveViewExpressionProjection => "live_view_expression_projection",
            Self::LiveViewExpressionOutput => "live_view_expression_output",
            Self::LiveViewReadinessProjection => "live_view_readiness_projection",
            Self::LiveViewInteractionIntent => "live_view_interaction_intent",
            Self::LiveViewPayloadProjection => "live_view_payload_projection",
            Self::CompositionRoot => "composition_root",
            Self::CompositionNode => "composition_node",
            Self::CompositionEdge => "composition_edge",
            Self::CompositionParticipation => "composition_participation",
            Self::CompositionPolicy => "composition_policy",
            Self::CompositionContext => "composition_context",
            Self::CompositionContextOverride => "composition_context_override",
            Self::CompositionContextPropagation => "composition_context_propagation",
            Self::HostMeasurementObservation => "host_measurement_observation",
            Self::LayoutAllocation => "layout_allocation",
            Self::ViewportBoundary => "viewport_boundary",
            Self::ClipBoundary => "clip_boundary",
            Self::ScrollRestoration => "scroll_restoration",
            Self::ViewportEventParticipation => "viewport_event_participation",
            Self::CompositionTopology => "composition_topology",
            Self::CompositionRootMountAuthority => "composition_root_mount_authority",
            Self::MosaicPlacementLegality => "mosaic_placement_legality",
            Self::VirtualizedDataFrame => "virtualized_data_frame",
            Self::DurableStateFamily => "durable_state_family",
            Self::OverlaySurface => "overlay_surface",
            Self::ToastSurface => "toast_surface",
            Self::InspectorSurface => "inspector_surface",
            Self::InteractionPolicy => "interaction_policy",
        }
    }
}
