#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
pub enum WorthUiRuntimeFactFamily {
    ActiveArtifact,
    ExecutionPlan,
    ThemeToken,
    Command,
    CommandProjection,
    DropdownSelectionState,
    ComponentInteractionState,
    QueryBinding,
    QueryResultPosture,
    QueryProjectionFact,
    QueryComputedView,
    QueryStateSnapshot,
    QueryEffectPosture,
    QueryRecoveryPosture,
    QueryInspectionTarget,
    LayoutTopology,
    LayoutGap,
    LayoutPadding,
    ContentMount,
    ShellSurface,
    ShellSlotAssignment,
    PageTemplate,
    PageInstance,
    PageInstanceTemplateBinding,
    PageContentSlot,
    SurfaceMount,
    AuthoredMountComponentSelection,
    AuthoredSurfaceProps,
    PrimitiveContent,
    PrimitiveContainer,
    PrimitiveMeasurement,
    PrimitiveAppearance,
    PrimitiveAppearanceState,
    PrimitiveInteraction,
    PrimitiveMotion,
    PrimitiveFlowLayout,
    PrimitiveEventGeometry,
    AuthoredQueryBindingShape,
    Component,
    Appearance,
    AppearanceRecipe,
    DensityToken,
    ActionPosture,
    LiveViewBinding,
    VirtualizedDataFrame,
    DurableStateFamily,
    OverlaySurface,
    ToastSurface,
    InspectorSurface,
    InteractionPolicy,
}

impl WorthUiRuntimeFactFamily {
    pub const fn token(self) -> &'static str {
        match self {
            Self::ActiveArtifact => "active_artifact",
            Self::ExecutionPlan => "execution_plan",
            Self::ThemeToken => "theme_token",
            Self::Command => "command",
            Self::CommandProjection => "command_projection",
            Self::DropdownSelectionState => "dropdown_selection_state",
            Self::ComponentInteractionState => "component_interaction_state",
            Self::QueryBinding => "query_binding",
            Self::QueryResultPosture => "query_result_posture",
            Self::QueryProjectionFact => "query_projection_fact",
            Self::QueryComputedView => "query_computed_view",
            Self::QueryStateSnapshot => "query_state_snapshot",
            Self::QueryEffectPosture => "query_effect_posture",
            Self::QueryRecoveryPosture => "query_recovery_posture",
            Self::QueryInspectionTarget => "query_inspection_target",
            Self::LayoutTopology => "layout_topology",
            Self::LayoutGap => "layout_gap",
            Self::LayoutPadding => "layout_padding",
            Self::ContentMount => "content_mount",
            Self::ShellSurface => "shell_surface",
            Self::ShellSlotAssignment => "shell_slot_assignment",
            Self::PageTemplate => "page_template",
            Self::PageInstance => "page_instance",
            Self::PageInstanceTemplateBinding => "page_instance_template_binding",
            Self::PageContentSlot => "page_content_slot",
            Self::SurfaceMount => "surface_mount",
            Self::AuthoredMountComponentSelection => "authored_mount_component_selection",
            Self::AuthoredSurfaceProps => "authored_surface_props",
            Self::PrimitiveContent => "primitive_content",
            Self::PrimitiveContainer => "primitive_container",
            Self::PrimitiveMeasurement => "primitive_measurement",
            Self::PrimitiveAppearance => "primitive_appearance",
            Self::PrimitiveAppearanceState => "primitive_appearance_state",
            Self::PrimitiveInteraction => "primitive_interaction",
            Self::PrimitiveMotion => "primitive_motion",
            Self::PrimitiveFlowLayout => "primitive_flow_layout",
            Self::PrimitiveEventGeometry => "primitive_event_geometry",
            Self::AuthoredQueryBindingShape => "authored_query_binding_shape",
            Self::Component => "component",
            Self::Appearance => "appearance",
            Self::AppearanceRecipe => "appearance_recipe",
            Self::DensityToken => "density_token",
            Self::ActionPosture => "action_posture",
            Self::LiveViewBinding => "live_view_binding",
            Self::VirtualizedDataFrame => "virtualized_data_frame",
            Self::DurableStateFamily => "durable_state_family",
            Self::OverlaySurface => "overlay_surface",
            Self::ToastSurface => "toast_surface",
            Self::InspectorSurface => "inspector_surface",
            Self::InteractionPolicy => "interaction_policy",
        }
    }
}
