use super::super::classification::{
    PlannerOwnedRoutingDisplacedLane as DisplacedLane,
    PlannerOwnedRoutingDisposition as Disposition, PlannerOwnedRoutingLifecycleRole as Role,
    PlannerOwnedRoutingOwner as Owner, PlannerOwnedRoutingReplacementLane as Lane,
};
use super::super::row::{
    PlannerOwnedRoutingInventoryRow as Row, PlannerOwnedRoutingSurfaceIdentity as Surface,
};

pub(super) fn rows() -> Vec<Row> {
    vec![
        row(
            Surface::WorthTouchedGraphConflictArchitectureAlignmentReport,
            "crates/worth-kernel/src/workload_composition/planner_owned_routing/public_proof/architecture_alignment_report.rs",
            "WorthTouchedGraphConflictArchitectureAlignmentReport",
            &["WorthTouchedGraphConflictArchitectureAlignmentReport"],
            "public closeout review and proof consumers",
            Role::PublicProofProjection,
            Disposition::Migrate,
            Lane::KernelPublicProof,
            "alignment proof is still exported from the displaced public_closeout lane",
            "planner_owned_routing/public_proof/ owns public-proof alignment projection",
        ),
        row(
            Surface::WorthTouchedGraphConflictArchitectureAlignmentReportRow,
            "crates/worth-kernel/src/workload_composition/planner_owned_routing/public_proof/architecture_alignment_report.rs",
            "WorthTouchedGraphConflictArchitectureAlignmentReportRow",
            &["WorthTouchedGraphConflictArchitectureAlignmentReport"],
            "alignment row inspectors",
            Role::PublicProofProjection,
            Disposition::Migrate,
            Lane::KernelPublicProof,
            "alignment rows are still exported from the displaced public_closeout lane",
            "planner_owned_routing/public_proof/ owns typed alignment row projection",
        ),
        row(
            Surface::WorthTouchedGraphConflictDeletionAlignmentRow,
            "crates/worth-kernel/src/workload_composition/planner_owned_routing/public_proof/architecture_alignment_report.rs",
            "WorthTouchedGraphConflictDeletionAlignmentRow",
            &["WorthTouchedGraphConflictArchitectureAlignmentReport"],
            "alignment row inspectors",
            Role::PublicProofProjection,
            Disposition::Migrate,
            Lane::KernelPublicProof,
            "deletion-alignment rows still describe public proof from the displaced lane",
            "planner_owned_routing/public_proof/ owns typed alignment row projection",
        ),
        row(
            Surface::CurrentPublicCloseoutConsumerResidueManifest,
            "crates/worth-kernel/src/workload_composition/planner_owned_routing/public_facade/residue_manifest.rs",
            "current_public_closeout_consumer_residue_manifest",
            &["current_public_closeout_consumer_residue_manifest"],
            "residue and closeout audit callers",
            Role::ForbiddenLegacyExplainer,
            Disposition::Delete,
            Lane::KernelPublicFacade,
            "current residue manifest still localizes ordinary public-closeout debt inside the displaced lane",
            "planner_owned_routing/public_facade/ exposes residue only through the new cut-line ledger",
        ),
        row(
            Surface::PublicCloseoutConsumerResidueManifestError,
            "crates/worth-kernel/src/workload_composition/planner_owned_routing/public_facade/residue_manifest.rs",
            "PublicCloseoutConsumerResidueManifestError",
            &["current_public_closeout_consumer_residue_manifest"],
            "public closeout residue callers",
            Role::PublicProofProjection,
            Disposition::Migrate,
            Lane::KernelPublicFacade,
            "public residue-manifest error shaping is still exported from the displaced public_closeout lane",
            "planner_owned_routing/public_facade/ owns public residue-manifest error shaping",
        ),
        row(
            Surface::PublicCloseoutConsumerResidueBoundaryPosture,
            "crates/worth-kernel/src/workload_composition/planner_owned_routing/public_facade/residue_manifest.rs",
            "PublicCloseoutConsumerResidueBoundaryPosture",
            &["PublicCloseoutConsumerResidueRow"],
            "public closeout residue inspectors",
            Role::PublicProofProjection,
            Disposition::Migrate,
            Lane::KernelPublicFacade,
            "public residue posture is still exported from the displaced public_closeout lane",
            "planner_owned_routing/public_facade/ owns public residue posture projection",
        ),
        row(
            Surface::PublicCloseoutConsumerResidueDisposition,
            "crates/worth-kernel/src/workload_composition/planner_owned_routing/public_facade/residue_manifest.rs",
            "PublicCloseoutConsumerResidueDisposition",
            &["PublicCloseoutConsumerResidueRow"],
            "public closeout residue inspectors",
            Role::PublicProofProjection,
            Disposition::Migrate,
            Lane::KernelPublicFacade,
            "public residue disposition is still exported from the displaced public_closeout lane",
            "planner_owned_routing/public_facade/ owns public residue disposition projection",
        ),
        row(
            Surface::PublicCloseoutConsumerResidueOwner,
            "crates/worth-kernel/src/workload_composition/planner_owned_routing/public_facade/residue_manifest.rs",
            "PublicCloseoutConsumerResidueOwner",
            &["PublicCloseoutConsumerResidueRow"],
            "public closeout residue inspectors",
            Role::PublicProofProjection,
            Disposition::Migrate,
            Lane::KernelPublicFacade,
            "public residue owner is still exported from the displaced public_closeout lane",
            "planner_owned_routing/public_facade/ owns public residue owner projection",
        ),
        row(
            Surface::PublicCloseoutConsumerResidueRow,
            "crates/worth-kernel/src/workload_composition/planner_owned_routing/public_facade/residue_manifest.rs",
            "PublicCloseoutConsumerResidueRow",
            &["current_public_closeout_consumer_residue_manifest"],
            "public closeout residue inspectors",
            Role::PublicProofProjection,
            Disposition::Migrate,
            Lane::KernelPublicFacade,
            "public residue rows are still authored under the displaced public_closeout lane",
            "planner_owned_routing/public_facade/ owns public residue row projection",
        ),
        row(
            Surface::CurrentWorthTouchedGraphConflictPublicCloseout,
            "crates/worth-kernel/src/workload_composition/planner_owned_routing/public_proof/current.rs",
            "current_worth_touched_graph_conflict_public_closeout",
            &[
                "WorthTouchedGraphConflictProofChain",
                "WorthTouchedGraphConflictResidueChain",
                "current_worth_touched_graph_conflict_source_firewall_report",
            ],
            "worth_workload::ordinary_consumer_sweep::closeout",
            Role::PublicProofProjection,
            Disposition::Migrate,
            Lane::KernelPublicProof,
            "wrapper public_closeout exports still name the old lane instead of certifying the live planner-owned public-proof owner",
            "ordinary public-closeout callers certify planner_owned_routing/public_proof/ as the live authority lane",
        ),
        row(
            Surface::WorthTouchedGraphConflictPublicCloseout,
            "crates/worth-kernel/src/workload_composition/planner_owned_routing/public_proof/types.rs",
            "WorthTouchedGraphConflictPublicCloseout",
            &["current_worth_touched_graph_conflict_public_closeout"],
            "kernel public closeout facade callers",
            Role::PublicProofProjection,
            Disposition::Migrate,
            Lane::KernelPublicProof,
            "public proof projection still lives under legacy public_closeout",
            "planner_owned_routing/public_proof/ owns the projection type",
        ),
        row(
            Surface::WorthTouchedGraphConflictPublicCloseoutError,
            "crates/worth-kernel/src/workload_composition/planner_owned_routing/public_proof/types.rs",
            "WorthTouchedGraphConflictPublicCloseoutError",
            &["current_worth_touched_graph_conflict_public_closeout"],
            "kernel public closeout facade callers",
            Role::PublicProofProjection,
            Disposition::Migrate,
            Lane::KernelPublicFacade,
            "public closeout error shaping still lives under the displaced lane",
            "planner_owned_routing/public_facade/ owns public closeout error shaping",
        ),
        row(
            Surface::WorthTouchedGraphConflictPublicCloseoutErrorKind,
            "crates/worth-kernel/src/workload_composition/planner_owned_routing/public_proof/types.rs",
            "WorthTouchedGraphConflictPublicCloseoutErrorKind",
            &["WorthTouchedGraphConflictPublicCloseoutError"],
            "kernel public closeout facade callers",
            Role::PublicProofProjection,
            Disposition::Migrate,
            Lane::KernelPublicFacade,
            "public closeout error kinds are still exported from the displaced lane",
            "planner_owned_routing/public_facade/ owns public closeout error taxonomy",
        ),
        row(
            Surface::WorthTouchedGraphConflictResidueBoundaryPosture,
            "crates/worth-kernel/src/workload_composition/planner_owned_routing/public_proof/residue_chain.rs",
            "WorthTouchedGraphConflictResidueBoundaryPosture",
            &["WorthTouchedGraphConflictResidueRow"],
            "residue inspectors",
            Role::PublicProofProjection,
            Disposition::Migrate,
            Lane::KernelPublicProof,
            "residue boundary posture is still exported from the displaced lane",
            "planner_owned_routing/public_proof/ owns residue boundary posture projection",
        ),
        row(
            Surface::WorthTouchedGraphConflictResidueChain,
            "crates/worth-kernel/src/workload_composition/planner_owned_routing/public_proof/residue_chain.rs",
            "WorthTouchedGraphConflictResidueChain",
            &["WorthTouchedGraphConflictResidueChain"],
            "public closeout and residue ledger consumers",
            Role::PublicProofProjection,
            Disposition::Migrate,
            Lane::KernelPublicProof,
            "residue-chain explanation still ships from legacy public_closeout",
            "planner_owned_routing/public_proof/ owns residue-chain projection",
        ),
        row(
            Surface::WorthTouchedGraphConflictResidueRow,
            "crates/worth-kernel/src/workload_composition/planner_owned_routing/public_proof/residue_chain.rs",
            "WorthTouchedGraphConflictResidueRow",
            &["WorthTouchedGraphConflictResidueChain"],
            "residue inspectors",
            Role::PublicProofProjection,
            Disposition::Migrate,
            Lane::KernelPublicProof,
            "residue rows still expose ordinary route fallout from the displaced lane",
            "planner_owned_routing/public_proof/ owns residue-row projection",
        ),
        row(
            Surface::CurrentWorthTouchedGraphConflictMilestoneFifteenSeed,
            "crates/worth-kernel/src/workload_composition/planner_owned_routing/public_proof/current.rs",
            "current_worth_touched_graph_conflict_milestone_fifteen_seed",
            &["WorthTouchedGraphConflictPublicCloseout"],
            "phase-fifteen handoff callers",
            Role::ForbiddenLegacyExplainer,
            Disposition::Delete,
            Lane::KernelAdmittedPublicProofInput,
            "wrapper public_closeout exports still imply the deleted conflict-era seed helper remains a live owner",
            "planner-owned seed lowering is certified from the live public-proof current seam only",
        ),
        row(
            Surface::WorthTouchedGraphConflictMilestoneFifteenSeed,
            "crates/worth-kernel/src/workload_composition/planner_owned_routing/public_proof/milestone_fifteen_seed.rs",
            "WorthTouchedGraphConflictMilestoneFifteenSeed",
            &["WorthTouchedGraphConflictPublicCloseout"],
            "future public proof and parity handoff callers",
            Role::SelectedRouteConsumer,
            Disposition::Migrate,
            Lane::KernelAdmittedPublicProofInput,
            "seed lowering still certifies the deleted legacy public-closeout helper instead of the live planner-owned seed packet",
            "planner-owned seed lowering owns the route-derived handoff packet",
        ),
        row(
            Surface::WorthTouchedGraphConflictMilestoneFifteenPlannerProofInput,
            "crates/worth-kernel/src/workload_composition/planner_owned_routing/public_proof/admitted_input.rs",
            "WorthTouchedGraphConflictMilestoneFifteenPlannerProofInput",
            &["WorthTouchedGraphConflictAdmittedPublicProofInput"],
            "WorthTouchedGraphConflictMilestoneFifteenSeed",
            Role::SelectedRouteConsumer,
            Disposition::Migrate,
            Lane::KernelAdmittedPublicProofInput,
            "planner proof input still certifies the deleted legacy assembly helper instead of the live admitted-input wrapper",
            "planner-owned public-proof admitted input owns the sealed lowering product",
        ),
        row(
            Surface::WorthTouchedGraphConflictProofChain,
            "crates/worth-kernel/src/workload_composition/planner_owned_routing/public_proof/proof_chain.rs",
            "WorthTouchedGraphConflictProofChain",
            &[
                "WorthWorkloadOrdinaryConsumerCutover",
                "EvidenceLookupPublicCloseout",
                "TopologyQueryBackedConsumerCutover",
            ],
            "current_worth_touched_graph_conflict_public_closeout",
            Role::SelectedRouteConsumer,
            Disposition::Migrate,
            Lane::KernelPublicProof,
            "proof chain still certifies the deleted legacy public-closeout file instead of the live planner-owned proof lane",
            "planner_owned_routing/public_proof/ owns the public proof chain",
        ),
        row(
            Surface::CurrentWorthWorkloadOrdinaryConsumerSweepCloseout,
            "crates/worth-kernel/src/workload_composition/worth_workload/ordinary_consumer_sweep/closeout.rs",
            "current_worth_workload_ordinary_consumer_sweep_closeout",
            &[
                "current_evidence_lookup_public_closeout",
                "current_worth_touched_graph_conflict_public_closeout",
                "TopologyQueryBackedConsumerCutover",
            ],
            "workload-composition route-local status callers",
            Role::SelectedRouteConsumer,
            Disposition::Migrate,
            Lane::KernelSelectedRoute,
            "workload-composition route-local status still reconstructs route meaning beside legacy closeout lanes",
            "workload-composition callers consume planner_owned_routing/selected_route/ or planner_owned_routing/public_proof/",
        ),
    ]
}

fn row(
    surface_identity: Surface,
    source_path: &'static str,
    surface_name: &'static str,
    current_authority_sources: &'static [&'static str],
    current_caller: &'static str,
    lifecycle_role: Role,
    disposition: Disposition,
    replacement_lane: Lane,
    blocker: &'static str,
    removal_trigger: &'static str,
) -> Row {
    Row::new(
        surface_identity,
        DisplacedLane::KernelPublicCloseout,
        source_path,
        surface_name,
        current_authority_sources,
        current_caller,
        lifecycle_role,
        disposition,
        Owner::WorthKernel,
        replacement_lane,
        blocker,
        removal_trigger,
        true,
        false,
        None,
        surface_name,
    )
}
