use super::classification::{
    PlannerOwnedRoutingDisplacedLane as DisplacedLane,
    PlannerOwnedRoutingDisposition as Disposition, PlannerOwnedRoutingLifecycleRole as Role,
    PlannerOwnedRoutingOwner as Owner, PlannerOwnedRoutingReplacementLane as Lane,
};
use super::row::{
    PlannerOwnedRoutingInventoryRow as Row, PlannerOwnedRoutingSurfaceIdentity as Surface,
};

pub(super) fn rows() -> Vec<Row> {
    vec![
        row(
            Surface::EvidenceLookupPublicCloseoutAssemblyInput,
            DisplacedLane::SpatialEvidenceLookupPublicCloseout,
            "crates/worth-spatial/src/workload_platform/evidence_lookup_public_closeout/assembly_input.rs",
            "EvidenceLookupPublicCloseoutAssemblyInput",
            &["current_evidence_lookup_public_closeout_assembly_input"],
            "public closeout assembly inspectors",
            Role::ForbiddenLegacyExplainer,
            Disposition::Delete,
            Lane::SpatialPublicCloseoutRoute,
            "the assembly-input carrier still belongs to the displaced public closeout lane",
            "planner_owned_routing/public_closeout_route/ owns lowered closeout input without legacy assembly ownership",
            true,
            false,
        ),
        row(
            Surface::CurrentEvidenceLookupPublicCloseout,
            DisplacedLane::SpatialEvidenceLookupPublicCloseout,
            "crates/worth-spatial/src/workload_platform/evidence_lookup_public_closeout/compiled_product_consumer_cutover/closeout.rs",
            "current_evidence_lookup_public_closeout",
            &["current_evidence_lookup_public_closeout"],
            "kernel proof chain + workload closeout callers",
            Role::PublicProofProjection,
            Disposition::Migrate,
            Lane::SpatialPublicCloseoutRoute,
            "spatial public closeout still owns ordinary route explanation in the displaced lane",
            "planner_owned_routing/public_closeout_route/ owns the spatial public proof projection",
            true,
            false,
        ),
        row(
            Surface::CurrentEvidenceLookupPublicCloseoutAssemblyInput,
            DisplacedLane::SpatialEvidenceLookupPublicCloseout,
            "crates/worth-spatial/src/workload_platform/evidence_lookup_public_closeout/compiled_product_consumer_cutover/closeout.rs",
            "current_evidence_lookup_public_closeout_assembly_input",
            &["current_evidence_lookup_public_closeout_assembly_input"],
            "current_evidence_lookup_public_closeout",
            Role::ForbiddenLegacyExplainer,
            Disposition::Delete,
            Lane::SpatialPublicCloseoutRoute,
            "current-source assembly input still mints ordinary route meaning beside the future planner lane",
            "planner_owned_routing/public_closeout_route/ lowers public closeout from route inputs without current-source assembly",
            true,
            false,
        ),
        row(
            Surface::EvidenceLookupPublicCloseout,
            DisplacedLane::SpatialEvidenceLookupPublicCloseout,
            "crates/worth-spatial/src/workload_platform/evidence_lookup_public_closeout/closeout_artifacts.rs",
            "EvidenceLookupPublicCloseout",
            &["current_evidence_lookup_public_closeout"],
            "kernel proof chain + public spatial closeout callers",
            Role::PublicProofProjection,
            Disposition::Migrate,
            Lane::SpatialPublicCloseoutRoute,
            "spatial closeout projection still lives in legacy evidence_lookup_public_closeout",
            "planner_owned_routing/public_closeout_route/ owns the spatial projection type",
            true,
            false,
        ),
        row(
            Surface::EvidenceLookupPublicCloseoutDisposition,
            DisplacedLane::SpatialEvidenceLookupPublicCloseout,
            "crates/worth-spatial/src/workload_platform/evidence_lookup_public_closeout/closeout_artifacts.rs",
            "EvidenceLookupPublicCloseoutDisposition",
            &["EvidenceLookupPublicCloseout"],
            "public spatial closeout callers",
            Role::PublicProofProjection,
            Disposition::Migrate,
            Lane::SpatialPublicCloseoutRoute,
            "spatial public-closeout disposition is still exported from the displaced lane",
            "planner_owned_routing/public_closeout_route/ owns closeout disposition projection",
            true,
            false,
        ),
        row(
            Surface::EvidenceLookupPublicCloseoutFamilyStageRow,
            DisplacedLane::SpatialEvidenceLookupPublicCloseout,
            "crates/worth-spatial/src/workload_platform/evidence_lookup_public_closeout/closeout_artifacts.rs",
            "EvidenceLookupPublicCloseoutFamilyStageRow",
            &["EvidenceLookupPublicCloseout::assemble_from_proof_products"],
            "EvidenceLookupPublicCloseout row consumers",
            Role::FamilyRouteProduct,
            Disposition::Migrate,
            Lane::SpatialEvidenceLookupRoute,
            "family-stage route meaning is still exported from the displaced public closeout lane",
            "planner_owned_routing/evidence_lookup_route/ owns the spatial family-route product",
            true,
            false,
        ),
        row(
            Surface::EvidenceLookupPublicCloseoutCounters,
            DisplacedLane::SpatialEvidenceLookupPublicCloseout,
            "crates/worth-spatial/src/workload_platform/evidence_lookup_public_closeout/counters.rs",
            "EvidenceLookupPublicCloseoutCounters",
            &["current_evidence_lookup_public_closeout"],
            "public closeout status callers",
            Role::PublicProofProjection,
            Disposition::Migrate,
            Lane::SpatialPublicCloseoutRoute,
            "public closeout counters still live in the displaced lane",
            "planner_owned_routing/public_closeout_route/ owns closeout status counters",
            true,
            false,
        ),
        row(
            Surface::CurrentEvidenceLookupPublicCloseoutResidueManifest,
            DisplacedLane::SpatialEvidenceLookupPublicCloseout,
            "crates/worth-spatial/src/workload_platform/evidence_lookup_public_closeout/compiled_product_consumer_cutover/residue_manifest.rs",
            "current_evidence_lookup_public_closeout_residue_manifest",
            &["current_evidence_lookup_public_closeout_residue_manifest"],
            "public closeout residue reviewers",
            Role::ForbiddenLegacyExplainer,
            Disposition::Delete,
            Lane::SpatialPublicCloseoutRoute,
            "current residue manifest still publishes spatial route-local debt from the displaced lane",
            "planner_owned_routing/public_closeout_route/ exposes residue only through the new lane ledger",
            true,
            false,
        ),
        row(
            Surface::EvidenceLookupPublicCloseoutResidueDisposition,
            DisplacedLane::SpatialEvidenceLookupPublicCloseout,
            "crates/worth-spatial/src/workload_platform/evidence_lookup_public_closeout/compiled_product_consumer_cutover/residue_manifest.rs",
            "EvidenceLookupPublicCloseoutResidueDisposition",
            &["EvidenceLookupPublicCloseoutResidueRow"],
            "spatial residue inspectors",
            Role::DerivedDiagnosticProjection,
            Disposition::Migrate,
            Lane::SpatialDiagnosticProjectionInput,
            "spatial residue disposition is still exported from the displaced closeout lane",
            "planner_owned_routing/diagnostic_projection_input/ owns spatial residue disposition projection",
            true,
            false,
        ),
        row(
            Surface::EvidenceLookupPublicCloseoutResidueOwner,
            DisplacedLane::SpatialEvidenceLookupPublicCloseout,
            "crates/worth-spatial/src/workload_platform/evidence_lookup_public_closeout/compiled_product_consumer_cutover/residue_manifest.rs",
            "EvidenceLookupPublicCloseoutResidueOwner",
            &["EvidenceLookupPublicCloseoutResidueRow"],
            "spatial residue inspectors",
            Role::DerivedDiagnosticProjection,
            Disposition::Migrate,
            Lane::SpatialDiagnosticProjectionInput,
            "spatial residue owner is still exported from the displaced closeout lane",
            "planner_owned_routing/diagnostic_projection_input/ owns spatial residue owner projection",
            true,
            false,
        ),
        row(
            Surface::EvidenceLookupPublicCloseoutResidueRow,
            DisplacedLane::SpatialEvidenceLookupPublicCloseout,
            "crates/worth-spatial/src/workload_platform/evidence_lookup_public_closeout/compiled_product_consumer_cutover/residue_manifest.rs",
            "EvidenceLookupPublicCloseoutResidueRow",
            &["current_evidence_lookup_public_closeout_residue_manifest"],
            "spatial residue inspectors",
            Role::DerivedDiagnosticProjection,
            Disposition::Migrate,
            Lane::SpatialDiagnosticProjectionInput,
            "spatial residue rows still describe route fallout from the displaced closeout lane",
            "planner_owned_routing/diagnostic_projection_input/ owns spatial residue localization",
            true,
            false,
        ),
        row(
            Surface::EvidenceLookupPublicCloseoutError,
            DisplacedLane::SpatialEvidenceLookupPublicCloseout,
            "crates/worth-spatial/src/workload_platform/evidence_lookup_public_closeout/error.rs",
            "EvidenceLookupPublicCloseoutError",
            &["current_evidence_lookup_public_closeout"],
            "public spatial closeout callers",
            Role::PublicProofProjection,
            Disposition::Migrate,
            Lane::SpatialPublicCloseoutRoute,
            "spatial public-closeout error shaping is still exported from the displaced lane",
            "planner_owned_routing/public_closeout_route/ owns closeout error shaping",
            true,
            false,
        ),
        row(
            Surface::EvidenceLookupPublicCloseoutErrorKind,
            DisplacedLane::SpatialEvidenceLookupPublicCloseout,
            "crates/worth-spatial/src/workload_platform/evidence_lookup_public_closeout/error.rs",
            "EvidenceLookupPublicCloseoutErrorKind",
            &["EvidenceLookupPublicCloseoutError"],
            "public spatial closeout callers",
            Role::PublicProofProjection,
            Disposition::Migrate,
            Lane::SpatialPublicCloseoutRoute,
            "spatial public-closeout error kinds are still exported from the displaced lane",
            "planner_owned_routing/public_closeout_route/ owns closeout error taxonomy",
            true,
            false,
        ),
    ]
}

fn row(
    surface_identity: Surface,
    displaced_lane: DisplacedLane,
    source_path: &'static str,
    surface_name: &'static str,
    current_authority_sources: &'static [&'static str],
    current_caller: &'static str,
    lifecycle_role: Role,
    disposition: Disposition,
    replacement_lane: Lane,
    blocker: &'static str,
    removal_trigger: &'static str,
    ordinary_path: bool,
    certification_only: bool,
) -> Row {
    Row::new(
        surface_identity,
        displaced_lane,
        source_path,
        surface_name,
        current_authority_sources,
        current_caller,
        lifecycle_role,
        disposition,
        Owner::WorthSpatial,
        replacement_lane,
        blocker,
        removal_trigger,
        ordinary_path,
        certification_only,
        None,
        surface_name,
    )
}
