use super::classification::{
    PlannerOwnedRoutingDisplacedLane as DisplacedLane,
    PlannerOwnedRoutingDisposition as Disposition, PlannerOwnedRoutingLifecycleRole as Role,
    PlannerOwnedRoutingOwner as Owner, PlannerOwnedRoutingReplacementLane as Lane,
};
use super::row::{
    PlannerOwnedRoutingInventoryRow as Row, PlannerOwnedRoutingSurfaceIdentity as Surface,
};

pub(super) fn rows() -> Vec<Row> {
    vec![
        row(
            Surface::EvidenceLookupPublicCloseoutAssemblyInput,
            DisplacedLane::SpatialEvidenceLookupPublicCloseout,
            "crates/worth-spatial/src/workload_platform/planner_owned_routing/public_closeout_route/assembly_input.rs",
            "EvidenceLookupPublicCloseoutAssemblyInput",
            &["current_evidence_lookup_public_closeout_assembly_input"],
            "public closeout assembly inspectors",
            Role::ForbiddenLegacyExplainer,
            Disposition::Cap,
            Lane::SpatialPublicCloseoutRoute,
            "the assembly-input carrier still belongs to the displaced public closeout lane",
            "touched_graph_parity_closeout/retained_surface_family/ owns the retained-surface claim without legacy assembly ownership",
            false,
            false,
        ),
        row(
            Surface::CurrentEvidenceLookupPublicCloseout,
            DisplacedLane::SpatialEvidenceLookupPublicCloseout,
            "crates/worth-spatial/src/workload_platform/planner_owned_routing/public_closeout_route/current.rs",
            "current_evidence_lookup_public_closeout",
            &["current_evidence_lookup_public_closeout"],
            "kernel proof chain + workload closeout callers",
            Role::PublicProofProjection,
            Disposition::Cap,
            Lane::SpatialPublicCloseoutRoute,
            "spatial public closeout still owns ordinary route explanation in the displaced lane",
            "touched_graph_parity_closeout/retained_surface_family/ owns the retained-surface ordinary claim",
            false,
            false,
        ),
        row(
            Surface::CurrentEvidenceLookupPublicCloseoutRouteInput,
            DisplacedLane::SpatialEvidenceLookupPublicCloseout,
            "crates/worth-spatial/src/workload_platform/planner_owned_routing/public_closeout_route/current.rs",
            "current_evidence_lookup_public_closeout_route_input",
            &["current_evidence_lookup_route_packet"],
            "current_evidence_lookup_public_closeout",
            Role::SelectedRouteConsumer,
            Disposition::Cap,
            Lane::SpatialPublicCloseoutRoute,
            "spatial public closeout still lowers selected-route support from the displaced lane",
            "touched_graph_parity_closeout/retained_surface_family/ owns retained-surface route input lowering",
            false,
            false,
        ),
        row(
            Surface::CurrentEvidenceLookupPublicCloseoutAssemblyInput,
            DisplacedLane::SpatialEvidenceLookupPublicCloseout,
            "crates/worth-spatial/src/workload_platform/planner_owned_routing/public_closeout_route/current.rs",
            "current_evidence_lookup_public_closeout_assembly_input",
            &["current_evidence_lookup_public_closeout_assembly_input"],
            "current_evidence_lookup_public_closeout",
            Role::ForbiddenLegacyExplainer,
            Disposition::Cap,
            Lane::SpatialPublicCloseoutRoute,
            "current-source assembly input still mints ordinary route meaning beside the future planner lane",
            "touched_graph_parity_closeout/retained_surface_family/ is the only ordinary closeout lane that may carry retained-surface truth",
            false,
            false,
        ),
        row(
            Surface::EvidenceLookupPublicCloseoutRouteInput,
            DisplacedLane::SpatialEvidenceLookupPublicCloseout,
            "crates/worth-spatial/src/workload_platform/planner_owned_routing/public_closeout_route/input.rs",
            "EvidenceLookupPublicCloseoutRouteInput",
            &["current_evidence_lookup_public_closeout_route_input"],
            "public closeout route-input consumers",
            Role::SelectedRouteConsumer,
            Disposition::Cap,
            Lane::SpatialPublicCloseoutRoute,
            "selected-route public closeout input is still exported from the displaced lane",
            "touched_graph_parity_closeout/retained_surface_family/ owns retained-surface route input authority",
            false,
            false,
        ),
        row(
            Surface::EvidenceLookupPublicCloseout,
            DisplacedLane::SpatialEvidenceLookupPublicCloseout,
            "crates/worth-spatial/src/workload_platform/planner_owned_routing/public_closeout_route/closeout_artifacts.rs",
            "EvidenceLookupPublicCloseout",
            &["current_evidence_lookup_public_closeout"],
            "kernel proof chain + public spatial closeout callers",
            Role::PublicProofProjection,
            Disposition::Cap,
            Lane::SpatialPublicCloseoutRoute,
            "spatial closeout projection still lives in legacy evidence_lookup_public_closeout",
            "touched_graph_parity_closeout/retained_surface_family/ owns the retained-surface projection claim",
            false,
            false,
        ),
        row(
            Surface::EvidenceLookupPublicCloseoutDisposition,
            DisplacedLane::SpatialEvidenceLookupPublicCloseout,
            "crates/worth-spatial/src/workload_platform/planner_owned_routing/public_closeout_route/closeout_artifacts.rs",
            "EvidenceLookupPublicCloseoutDisposition",
            &["EvidenceLookupPublicCloseout"],
            "public spatial closeout callers",
            Role::PublicProofProjection,
            Disposition::Cap,
            Lane::SpatialPublicCloseoutRoute,
            "spatial public-closeout disposition is still exported from the displaced lane",
            "touched_graph_parity_closeout/retained_surface_family/ owns retained-surface closeout disposition",
            false,
            false,
        ),
        row(
            Surface::EvidenceLookupPublicCloseoutFamilyStageRow,
            DisplacedLane::SpatialEvidenceLookupPublicCloseout,
            "crates/worth-spatial/src/workload_platform/planner_owned_routing/public_closeout_route/closeout_artifacts.rs",
            "EvidenceLookupPublicCloseoutFamilyStageRow",
            &["EvidenceLookupPublicCloseout::assemble_from_proof_products"],
            "EvidenceLookupPublicCloseout row consumers",
            Role::FamilyRouteProduct,
            Disposition::Cap,
            Lane::SpatialEvidenceLookupRoute,
            "family-stage route meaning is still exported from the displaced public closeout lane",
            "touched_graph_parity_closeout/evidence_lookup_family/ owns the ordinary evidence-lookup architecture claim",
            false,
            false,
        ),
        row(
            Surface::EvidenceLookupPublicCloseoutCounters,
            DisplacedLane::SpatialEvidenceLookupPublicCloseout,
            "crates/worth-spatial/src/workload_platform/planner_owned_routing/public_closeout_route/counters.rs",
            "EvidenceLookupPublicCloseoutCounters",
            &["current_evidence_lookup_public_closeout"],
            "public closeout status callers",
            Role::PublicProofProjection,
            Disposition::Cap,
            Lane::SpatialPublicCloseoutRoute,
            "public closeout counters still live in the displaced lane",
            "touched_graph_parity_closeout/retained_surface_family/ owns retained-surface closeout counters",
            false,
            false,
        ),
        row(
            Surface::CurrentEvidenceLookupPublicCloseoutResidueManifest,
            DisplacedLane::SpatialEvidenceLookupPublicCloseout,
            "crates/worth-spatial/src/workload_platform/planner_owned_routing/public_closeout_route/residue_manifest.rs",
            "current_evidence_lookup_public_closeout_residue_manifest",
            &["current_evidence_lookup_public_closeout_residue_manifest"],
            "public closeout residue reviewers",
            Role::ForbiddenLegacyExplainer,
            Disposition::Cap,
            Lane::SpatialPublicCloseoutRoute,
            "current residue manifest still publishes spatial route-local debt from the displaced lane",
            "touched_graph_parity_closeout/retained_surface_family/ exposes any remaining residue only through the parity closeout ledger",
            false,
            false,
        ),
        row(
            Surface::EvidenceLookupPublicCloseoutResidueDisposition,
            DisplacedLane::SpatialEvidenceLookupPublicCloseout,
            "crates/worth-spatial/src/workload_platform/planner_owned_routing/public_closeout_route/residue_manifest.rs",
            "EvidenceLookupPublicCloseoutResidueDisposition",
            &["EvidenceLookupPublicCloseoutResidueRow"],
            "spatial residue inspectors",
            Role::DerivedDiagnosticProjection,
            Disposition::Cap,
            Lane::SpatialDiagnosticProjectionInput,
            "spatial residue disposition is still exported from the displaced closeout lane",
            "planner_owned_routing/diagnostic_projection_input/ owns spatial residue disposition projection",
            false,
            false,
        ),
        row(
            Surface::EvidenceLookupPublicCloseoutResidueOwner,
            DisplacedLane::SpatialEvidenceLookupPublicCloseout,
            "crates/worth-spatial/src/workload_platform/planner_owned_routing/public_closeout_route/residue_manifest.rs",
            "EvidenceLookupPublicCloseoutResidueOwner",
            &["EvidenceLookupPublicCloseoutResidueRow"],
            "spatial residue inspectors",
            Role::DerivedDiagnosticProjection,
            Disposition::Cap,
            Lane::SpatialDiagnosticProjectionInput,
            "spatial residue owner is still exported from the displaced closeout lane",
            "planner_owned_routing/diagnostic_projection_input/ owns spatial residue owner projection",
            false,
            false,
        ),
        row(
            Surface::EvidenceLookupPublicCloseoutResidueRow,
            DisplacedLane::SpatialEvidenceLookupPublicCloseout,
            "crates/worth-spatial/src/workload_platform/planner_owned_routing/public_closeout_route/residue_manifest.rs",
            "EvidenceLookupPublicCloseoutResidueRow",
            &["current_evidence_lookup_public_closeout_residue_manifest"],
            "spatial residue inspectors",
            Role::DerivedDiagnosticProjection,
            Disposition::Cap,
            Lane::SpatialDiagnosticProjectionInput,
            "spatial residue rows still describe route fallout from the displaced closeout lane",
            "planner_owned_routing/diagnostic_projection_input/ owns spatial residue localization",
            false,
            false,
        ),
        row(
            Surface::EvidenceLookupPublicCloseoutError,
            DisplacedLane::SpatialEvidenceLookupPublicCloseout,
            "crates/worth-spatial/src/workload_platform/planner_owned_routing/public_closeout_route/error.rs",
            "EvidenceLookupPublicCloseoutError",
            &["current_evidence_lookup_public_closeout"],
            "public spatial closeout callers",
            Role::PublicProofProjection,
            Disposition::Cap,
            Lane::SpatialPublicCloseoutRoute,
            "spatial public-closeout error shaping is still exported from the displaced lane",
            "touched_graph_parity_closeout/retained_surface_family/ owns retained-surface closeout error shaping",
            false,
            false,
        ),
        row(
            Surface::EvidenceLookupPublicCloseoutErrorKind,
            DisplacedLane::SpatialEvidenceLookupPublicCloseout,
            "crates/worth-spatial/src/workload_platform/planner_owned_routing/public_closeout_route/error.rs",
            "EvidenceLookupPublicCloseoutErrorKind",
            &["EvidenceLookupPublicCloseoutError"],
            "public spatial closeout callers",
            Role::PublicProofProjection,
            Disposition::Cap,
            Lane::SpatialPublicCloseoutRoute,
            "spatial public-closeout error kinds are still exported from the displaced lane",
            "touched_graph_parity_closeout/retained_surface_family/ owns retained-surface closeout error taxonomy",
            false,
            false,
        ),
    ]
}

fn row(
    surface_identity: Surface,
    displaced_lane: DisplacedLane,
    source_path: &'static str,
    surface_name: &'static str,
    current_authority_sources: &'static [&'static str],
    _current_caller: &'static str,
    lifecycle_role: Role,
    disposition: Disposition,
    replacement_lane: Lane,
    blocker: &'static str,
    removal_trigger: &'static str,
    ordinary_path: bool,
    certification_only: bool,
) -> Row {
    Row::new(
        surface_identity,
        displaced_lane,
        source_path,
        surface_name,
        current_authority_sources,
        lifecycle_role,
        disposition,
        Owner::WorthSpatial,
        replacement_lane,
        blocker,
        removal_trigger,
        ordinary_path,
        certification_only,
        surface_name,
    )
}
