use super::super::classification::{
    PlannerOwnedRoutingDisplacedLane as DisplacedLane,
    PlannerOwnedRoutingDisposition as Disposition, PlannerOwnedRoutingLifecycleRole as Role,
    PlannerOwnedRoutingOwner as Owner, PlannerOwnedRoutingReplacementLane as Lane,
};
use super::super::row::{
    PlannerOwnedRoutingInventoryRow as Row, PlannerOwnedRoutingSurfaceIdentity as Surface,
};

pub(super) fn rows() -> Vec<Row> {
    vec![
        row(
            Surface::WorthTouchedGraphConflictForbiddenSurface,
            "crates/worth-kernel/src/workload_composition/source_firewall/forbidden_surface.rs",
            "WorthTouchedGraphConflictForbiddenSurface",
            &["WorthTouchedGraphConflictForbiddenSurface"],
            "source-firewall and residue reviewers",
            Role::PriorProofInputConsumer,
            Disposition::Migrate,
            Lane::KernelSourceFirewall,
            "forbidden surface classification still lives on the displaced firewall lane",
            "planner_owned_routing/source_firewall/ owns forbidden-surface classification",
        ),
        row(
            Surface::CurrentWorthTouchedGraphConflictSourceFirewallReport,
            "crates/worth-kernel/src/workload_composition/source_firewall/ordinary_cutover_firewall.rs",
            "current_worth_touched_graph_conflict_source_firewall_report",
            &["phase_fifteen_semantic_source_registry"],
            "public closeout + deletion closeout",
            Role::PriorProofInputConsumer,
            Disposition::Migrate,
            Lane::KernelSourceFirewall,
            "firewall report remains a prerequisite for public proof and residue honesty",
            "planner_owned_routing/source_firewall/ owns the route-local firewall evidence",
        ),
        row(
            Surface::CurrentWorthTouchedGraphConflictSourceFirewallCloseout,
            "crates/worth-kernel/src/workload_composition/source_firewall/closeout.rs",
            "current_worth_touched_graph_conflict_source_firewall_closeout",
            &[
                "current_worth_touched_graph_conflict_source_firewall_report",
                "current_worth_touched_graph_conflict_deletion_closeout",
            ],
            "public closeout seed and deletion closeout callers",
            Role::PriorProofInputConsumer,
            Disposition::Migrate,
            Lane::KernelSourceFirewall,
            "source-firewall closeout remains a public-proof prerequisite under the legacy lane",
            "planner_owned_routing/source_firewall/ owns closeout-ready firewall evidence",
        ),
        row(
            Surface::WorthTouchedGraphConflictSourceFirewallCloseout,
            "crates/worth-kernel/src/workload_composition/source_firewall/closeout.rs",
            "WorthTouchedGraphConflictSourceFirewallCloseout",
            &["current_worth_touched_graph_conflict_source_firewall_closeout"],
            "public proof and firewall review callers",
            Role::PriorProofInputConsumer,
            Disposition::Migrate,
            Lane::KernelSourceFirewall,
            "source-firewall closeout type remains exported from the displaced lane",
            "planner_owned_routing/source_firewall/ owns the closeout projection type",
        ),
        row(
            Surface::WorthTouchedGraphConflictSourceFirewallCloseoutError,
            "crates/worth-kernel/src/workload_composition/source_firewall/closeout.rs",
            "WorthTouchedGraphConflictSourceFirewallCloseoutError",
            &["current_worth_touched_graph_conflict_source_firewall_closeout"],
            "public proof and firewall review callers",
            Role::PriorProofInputConsumer,
            Disposition::Migrate,
            Lane::KernelSourceFirewall,
            "source-firewall closeout error shaping still lives under the displaced lane",
            "planner_owned_routing/source_firewall/ owns public closeout error shaping",
        ),
        row(
            Surface::WorthTouchedGraphConflictSourceFirewallCloseoutErrorKind,
            "crates/worth-kernel/src/workload_composition/source_firewall/closeout.rs",
            "WorthTouchedGraphConflictSourceFirewallCloseoutErrorKind",
            &["WorthTouchedGraphConflictSourceFirewallCloseoutError"],
            "public proof and firewall review callers",
            Role::PriorProofInputConsumer,
            Disposition::Migrate,
            Lane::KernelSourceFirewall,
            "source-firewall closeout error kinds are still exported from the displaced lane",
            "planner_owned_routing/source_firewall/ owns closeout error taxonomy",
        ),
        row(
            Surface::WorthTouchedGraphConflictSourceFirewallRegionReport,
            "crates/worth-kernel/src/workload_composition/source_firewall/report.rs",
            "WorthTouchedGraphConflictSourceFirewallRegionReport",
            &["current_worth_touched_graph_conflict_source_firewall_report"],
            "firewall report inspectors",
            Role::PriorProofInputConsumer,
            Disposition::Migrate,
            Lane::KernelSourceFirewall,
            "firewall region detail is still exported from the displaced lane",
            "planner_owned_routing/source_firewall/ owns region-level firewall projection",
        ),
        row(
            Surface::WorthTouchedGraphConflictSourceFirewallReport,
            "crates/worth-kernel/src/workload_composition/source_firewall/report.rs",
            "WorthTouchedGraphConflictSourceFirewallReport",
            &["current_worth_touched_graph_conflict_source_firewall_report"],
            "public proof and firewall review callers",
            Role::PriorProofInputConsumer,
            Disposition::Migrate,
            Lane::KernelSourceFirewall,
            "source-firewall report is still exported from the displaced lane",
            "planner_owned_routing/source_firewall/ owns the public firewall report shape",
        ),
        row(
            Surface::WorthTouchedGraphConflictSourceFirewallViolation,
            "crates/worth-kernel/src/workload_composition/source_firewall/report.rs",
            "WorthTouchedGraphConflictSourceFirewallViolation",
            &["current_worth_touched_graph_conflict_source_firewall_report"],
            "firewall denial and review callers",
            Role::PriorProofInputConsumer,
            Disposition::Migrate,
            Lane::KernelSourceFirewall,
            "firewall violations remain an exported legacy-lane explanation carrier",
            "planner_owned_routing/source_firewall/ owns typed violation projection",
        ),
    ]
}

fn row(
    surface_identity: Surface,
    source_path: &'static str,
    surface_name: &'static str,
    current_authority_sources: &'static [&'static str],
    _current_caller: &'static str,
    lifecycle_role: Role,
    disposition: Disposition,
    replacement_lane: Lane,
    blocker: &'static str,
    removal_trigger: &'static str,
) -> Row {
    Row::new(
        surface_identity,
        DisplacedLane::KernelSourceFirewall,
        source_path,
        surface_name,
        current_authority_sources,
        lifecycle_role,
        disposition,
        Owner::WorthKernel,
        replacement_lane,
        blocker,
        removal_trigger,
        true,
        false,
        surface_name,
    )
}
