use super::classification::{
    PlannerOwnedRoutingDisplacedLane as DisplacedLane,
    PlannerOwnedRoutingDisposition as Disposition, PlannerOwnedRoutingLifecycleRole as Role,
    PlannerOwnedRoutingOwner as Owner, PlannerOwnedRoutingReplacementLane as Lane,
};
use super::row::{
    PlannerOwnedRoutingInventoryRow as Row, PlannerOwnedRoutingSurfaceIdentity as Surface,
};

pub(super) fn rows() -> Vec<Row> {
    vec![
        row(
            Surface::DiagnosticSurfaceDeterministicDigest,
            DisplacedLane::TopoDiagnosticSurfaces,
            "crates/worth-topo/src/projection/diagnostic_surfaces/mod.rs",
            "DeterministicDigest",
            &["DerivedReadDiagnostics"],
            "diagnostic surface import callers",
            Role::ForbiddenLegacyExplainer,
            Disposition::Delete,
            Lane::TopoDiagnosticProjectionInput,
            "diagnostic_surfaces still re-exports a generic digest support type from the displaced lane",
            "planner_owned_routing/diagnostic_projection_input/ exposes only typed diagnostic products, not a lane-local digest re-export",
            true,
            false,
        ),
        row(
            Surface::DerivedFallbackReport,
            DisplacedLane::TopoDiagnosticSurfaces,
            "crates/worth-topo/src/projection/diagnostic_surfaces/derived_read_diagnostics.rs",
            "DerivedFallbackReport",
            &["build_derived_fallback_report"],
            "diagnostic inspectors",
            Role::DerivedDiagnosticProjection,
            Disposition::Migrate,
            Lane::TopoDiagnosticProjectionInput,
            "fallback localization still lives under displaced diagnostic_surfaces",
            "planner_owned_routing/diagnostic_projection_input/ owns derived fallback localization input",
            true,
            false,
        ),
        row(
            Surface::DerivedInvalidationReport,
            DisplacedLane::TopoDiagnosticSurfaces,
            "crates/worth-topo/src/projection/diagnostic_surfaces/derived_read_diagnostics.rs",
            "DerivedInvalidationReport",
            &["build_derived_invalidation_report"],
            "diagnostic inspectors",
            Role::DerivedDiagnosticProjection,
            Disposition::Migrate,
            Lane::TopoDiagnosticProjectionInput,
            "invalidation localization still lives under displaced diagnostic_surfaces",
            "planner_owned_routing/diagnostic_projection_input/ owns invalidation localization input",
            true,
            false,
        ),
        row(
            Surface::DerivedInvalidationTargetRow,
            DisplacedLane::TopoDiagnosticSurfaces,
            "crates/worth-topo/src/projection/diagnostic_surfaces/derived_read_diagnostics.rs",
            "DerivedInvalidationTargetRow",
            &["build_derived_invalidation_report_from_aspects"],
            "diagnostic inspectors",
            Role::DerivedDiagnosticProjection,
            Disposition::Migrate,
            Lane::TopoDiagnosticProjectionInput,
            "crate-visible invalidation target rows still live under displaced diagnostic_surfaces",
            "planner_owned_routing/diagnostic_projection_input/ owns invalidation target row localization",
            true,
            false,
        ),
        row(
            Surface::DerivedRebuildReport,
            DisplacedLane::TopoDiagnosticSurfaces,
            "crates/worth-topo/src/projection/diagnostic_surfaces/derived_read_diagnostics.rs",
            "DerivedRebuildReport",
            &["build_derived_rebuild_report"],
            "diagnostic inspectors",
            Role::DerivedDiagnosticProjection,
            Disposition::Migrate,
            Lane::TopoDiagnosticProjectionInput,
            "rebuild localization still lives under displaced diagnostic_surfaces",
            "planner_owned_routing/diagnostic_projection_input/ owns rebuild localization input",
            true,
            false,
        ),
        row(
            Surface::DerivedReadDiagnostics,
            DisplacedLane::TopoDiagnosticSurfaces,
            "crates/worth-topo/src/projection/diagnostic_surfaces/derived_read_diagnostics.rs",
            "DerivedReadDiagnostics",
            &["build_derived_read_diagnostics"],
            "retained query diagnostics and derived read debugging callers",
            Role::DerivedDiagnosticProjection,
            Disposition::Migrate,
            Lane::TopoDiagnosticProjectionInput,
            "topology diagnostic projection is still authored in the legacy diagnostic_surfaces lane",
            "planner_owned_routing/diagnostic_projection_input/ owns the topo diagnostic input packet",
            true,
            false,
        ),
        row(
            Surface::DerivedValidationExecutionReport,
            DisplacedLane::TopoDiagnosticSurfaces,
            "crates/worth-topo/src/projection/diagnostic_surfaces/derived_read_diagnostics.rs",
            "DerivedValidationExecutionReport",
            &["derived_validation_execution_report"],
            "diagnostic inspectors",
            Role::DerivedDiagnosticProjection,
            Disposition::Migrate,
            Lane::TopoDiagnosticProjectionInput,
            "crate-visible validation execution localization still lives under displaced diagnostic_surfaces",
            "planner_owned_routing/diagnostic_projection_input/ owns validation execution localization input",
            true,
            false,
        ),
        row(
            Surface::AdmitTopologyQueryBackedConsumerCutover,
            DisplacedLane::TopoQueryBackedConsumerCutover,
            "crates/worth-topo/src/projection/query_backed_consumer_cutover/closeout.rs",
            "admit_topology_query_backed_consumer_cutover",
            &["admit_topology_query_backed_consumer_cutover"],
            "topology query-backed route callers",
            Role::FamilyRouteProduct,
            Disposition::Migrate,
            Lane::TopoQueryBackedReadFamily,
            "the admitting route entrypoint still lives in the displaced query_backed_consumer_cutover lane",
            "planner_owned_routing/query_backed_read_family/ owns family-route admission",
            true,
            false,
        ),
        row(
            Surface::CurrentTopologyQueryBackedConsumerCutover,
            DisplacedLane::TopoQueryBackedConsumerCutover,
            "crates/worth-topo/src/projection/query_backed_consumer_cutover/current_closeout.rs",
            "current_topology_query_backed_consumer_cutover",
            &[
                "current_topology_query_backed_consumer_cutover",
                "current_topology_selected_equivalence_family_catalog",
            ],
            "kernel public closeout + spatial evidence admission",
            Role::ForbiddenLegacyExplainer,
            Disposition::Delete,
            Lane::TopoQueryBackedReadFamily,
            "legacy query-backed current-closeout path still owns ordinary route reconstruction",
            "planner_owned_routing/query_backed_read_family/ loads the route input directly",
            true,
            false,
        ),
        row(
            Surface::TopologyQueryBackedConsumerCutoverCurrentError,
            DisplacedLane::TopoQueryBackedConsumerCutover,
            "crates/worth-topo/src/projection/query_backed_consumer_cutover/current_closeout.rs",
            "TopologyQueryBackedConsumerCutoverCurrentError",
            &["current_topology_query_backed_consumer_cutover"],
            "kernel public closeout + spatial evidence admission",
            Role::ForbiddenLegacyExplainer,
            Disposition::Delete,
            Lane::TopoQueryBackedReadFamily,
            "the current-closeout error type is still exported from the displaced topology lane",
            "planner_owned_routing/query_backed_read_family/ owns the cutover error surface or removes it from ordinary imports",
            true,
            false,
        ),
        row(
            Surface::TopologyQueryBackedConsumerCutover,
            DisplacedLane::TopoQueryBackedConsumerCutover,
            "crates/worth-topo/src/projection/query_backed_consumer_cutover/closeout.rs",
            "TopologyQueryBackedConsumerCutover",
            &["admit_topology_query_backed_consumer_cutover"],
            "kernel proof chain + spatial public closeout",
            Role::FamilyRouteProduct,
            Disposition::Migrate,
            Lane::TopoQueryBackedReadFamily,
            "topology route product still lives in legacy query_backed_consumer_cutover",
            "planner_owned_routing/query_backed_read_family/ owns the family route product",
            true,
            false,
        ),
        row(
            Surface::TopologyQueryBackedConsumerFamilyRow,
            DisplacedLane::TopoQueryBackedConsumerCutover,
            "crates/worth-topo/src/projection/query_backed_consumer_cutover/closeout.rs",
            "TopologyQueryBackedConsumerFamilyRow",
            &["admit_topology_query_backed_consumer_cutover"],
            "kernel proof chain + spatial public closeout row consumers",
            Role::FamilyRouteProduct,
            Disposition::Migrate,
            Lane::TopoQueryBackedReadFamily,
            "family-row route meaning is still exported from the legacy query-backed cutover lane",
            "planner_owned_routing/query_backed_read_family/ owns the family-row route carrier",
            true,
            false,
        ),
        row(
            Surface::TopologyReadModelReusePosture,
            DisplacedLane::TopoQueryBackedConsumerCutover,
            "crates/worth-topo/src/projection/query_backed_consumer_cutover/read_model_reuse_posture.rs",
            "TopologyReadModelReusePosture",
            &["TopologyReadModelReusePosture"],
            "topology and spatial route inspectors",
            Role::FamilyRouteProduct,
            Disposition::Migrate,
            Lane::TopoQueryBackedReadFamily,
            "reuse posture is still exported from the displaced query_backed_consumer_cutover lane",
            "planner_owned_routing/query_backed_read_family/ owns typed read-model reuse posture",
            true,
            false,
        ),
        row(
            Surface::CurrentQueryBackedConsumerResidueManifest,
            DisplacedLane::TopoQueryBackedConsumerCutover,
            "crates/worth-topo/src/projection/query_backed_consumer_cutover/residue_manifest.rs",
            "current_query_backed_consumer_residue_manifest",
            &["current_query_backed_consumer_residue_manifest"],
            "query-backed residue reviewers",
            Role::ForbiddenLegacyExplainer,
            Disposition::Delete,
            Lane::TopoQueryBackedReadFamily,
            "current residue manifest still publishes route-local debt from the displaced topology lane",
            "planner_owned_routing/query_backed_read_family/ exposes residue only through the new lane ledger",
            true,
            false,
        ),
        row(
            Surface::QueryBackedConsumerResidueDisposition,
            DisplacedLane::TopoQueryBackedConsumerCutover,
            "crates/worth-topo/src/projection/query_backed_consumer_cutover/residue_manifest.rs",
            "QueryBackedConsumerResidueDisposition",
            &["QueryBackedConsumerResidueRow"],
            "query-backed residue inspectors",
            Role::DerivedDiagnosticProjection,
            Disposition::Migrate,
            Lane::TopoDiagnosticProjectionInput,
            "query-backed residue disposition is still exported from the displaced topology lane",
            "planner_owned_routing/diagnostic_projection_input/ owns query-backed residue disposition projection",
            true,
            false,
        ),
        row(
            Surface::QueryBackedConsumerResidueOwner,
            DisplacedLane::TopoQueryBackedConsumerCutover,
            "crates/worth-topo/src/projection/query_backed_consumer_cutover/residue_manifest.rs",
            "QueryBackedConsumerResidueOwner",
            &["QueryBackedConsumerResidueRow"],
            "query-backed residue inspectors",
            Role::DerivedDiagnosticProjection,
            Disposition::Migrate,
            Lane::TopoDiagnosticProjectionInput,
            "query-backed residue owner is still exported from the displaced topology lane",
            "planner_owned_routing/diagnostic_projection_input/ owns query-backed residue owner projection",
            true,
            false,
        ),
        row(
            Surface::QueryBackedConsumerResidueRow,
            DisplacedLane::TopoQueryBackedConsumerCutover,
            "crates/worth-topo/src/projection/query_backed_consumer_cutover/residue_manifest.rs",
            "QueryBackedConsumerResidueRow",
            &["current_query_backed_consumer_residue_manifest"],
            "query-backed residue inspectors",
            Role::DerivedDiagnosticProjection,
            Disposition::Migrate,
            Lane::TopoDiagnosticProjectionInput,
            "query-backed residue rows still describe route fallout from the displaced lane",
            "planner_owned_routing/diagnostic_projection_input/ owns query-backed residue localization",
            true,
            false,
        ),
    ]
}

fn row(
    surface_identity: Surface,
    displaced_lane: DisplacedLane,
    source_path: &'static str,
    surface_name: &'static str,
    current_authority_sources: &'static [&'static str],
    current_caller: &'static str,
    lifecycle_role: Role,
    disposition: Disposition,
    replacement_lane: Lane,
    blocker: &'static str,
    removal_trigger: &'static str,
    ordinary_path: bool,
    certification_only: bool,
) -> Row {
    Row::new(
        surface_identity,
        displaced_lane,
        source_path,
        surface_name,
        current_authority_sources,
        current_caller,
        lifecycle_role,
        disposition,
        Owner::WorthTopo,
        replacement_lane,
        blocker,
        removal_trigger,
        ordinary_path,
        certification_only,
        None,
        surface_name,
    )
}
