use super::{
    ForgeQueryLowerRuntimeAuthorityOwner, ForgeQueryLowerRuntimeCloseoutPosture,
    ForgeQueryLowerRuntimeCloseoutRegistry, ForgeQueryLowerRuntimeCloseoutRow,
    ForgeQueryLowerRuntimeRouteKind, ForgeQueryLowerRuntimeSeamKey,
};

const CLOSEOUT_ROWS: &[ForgeQueryLowerRuntimeCloseoutRow] = &[
    ForgeQueryLowerRuntimeCloseoutRow::new(
        ForgeQueryLowerRuntimeSeamKey::RuntimeIntentModule,
        "Runtime intent module seam",
        ForgeQueryLowerRuntimeCloseoutPosture::SeamEliminated,
        ForgeQueryLowerRuntimeAuthorityOwner::Query,
        ForgeQueryLowerRuntimeRouteKind::RoutePlanning,
        "phase-2 backend intent authority boundary ownership",
        "runtime/intent/mod.rs must remain free of direct lower-runtime authority imports",
        "phase-2-runtime-intent-elimination",
    ),
    ForgeQueryLowerRuntimeCloseoutRow::new(
        ForgeQueryLowerRuntimeSeamKey::StoreBackedRouteParityNeighbor,
        "Store-backed route parity",
        ForgeQueryLowerRuntimeCloseoutPosture::DeferredNeighbor,
        ForgeQueryLowerRuntimeAuthorityOwner::Store,
        ForgeQueryLowerRuntimeRouteKind::RoutePlanning,
        "later store-backed route parity milestone",
        "fail deferred until forge-store owns the route-parity contract and replay evidence",
        "deferred-store-route-parity",
    ),
    ForgeQueryLowerRuntimeCloseoutRow::new(
        ForgeQueryLowerRuntimeSeamKey::DurableRouteReplayNeighbor,
        "Durable route replay",
        ForgeQueryLowerRuntimeCloseoutPosture::DeferredNeighbor,
        ForgeQueryLowerRuntimeAuthorityOwner::Store,
        ForgeQueryLowerRuntimeRouteKind::RoutePlanning,
        "later durable route replay milestone",
        "fail deferred until durable replay binds persisted route evidence to the routing lifecycle",
        "deferred-durable-route-replay",
    ),
    ForgeQueryLowerRuntimeCloseoutRow::new(
        ForgeQueryLowerRuntimeSeamKey::PersistedBoundaryExecutionReceiptNeighbor,
        "Persisted boundary execution receipts",
        ForgeQueryLowerRuntimeCloseoutPosture::DeferredNeighbor,
        ForgeQueryLowerRuntimeAuthorityOwner::Store,
        ForgeQueryLowerRuntimeRouteKind::RoutePlanning,
        "later persisted boundary artifact milestone",
        "fail deferred until persisted boundary receipts exist as store-owned artifacts",
        "deferred-persisted-boundary-receipts",
    ),
    ForgeQueryLowerRuntimeCloseoutRow::new(
        ForgeQueryLowerRuntimeSeamKey::RestartStableBoundaryEnvelopeReloadNeighbor,
        "Restart-stable boundary envelope reload",
        ForgeQueryLowerRuntimeCloseoutPosture::DeferredNeighbor,
        ForgeQueryLowerRuntimeAuthorityOwner::Store,
        ForgeQueryLowerRuntimeRouteKind::ReadmissionHandoff,
        "later restart-stable envelope reload milestone",
        "fail deferred until restart-stable reload can read boundary envelopes without Query-side reenactment",
        "deferred-envelope-reload",
    ),
    ForgeQueryLowerRuntimeCloseoutRow::new(
        ForgeQueryLowerRuntimeSeamKey::TemporalQueryBasisRoutingNeighbor,
        "Temporal query basis routing",
        ForgeQueryLowerRuntimeCloseoutPosture::DeferredNeighbor,
        ForgeQueryLowerRuntimeAuthorityOwner::Query,
        ForgeQueryLowerRuntimeRouteKind::RoutePlanning,
        "later temporal routing milestone",
        "fail deferred until temporal basis identity is admitted into the lower-runtime routing lifecycle",
        "deferred-temporal-routing",
    ),
    ForgeQueryLowerRuntimeCloseoutRow::new(
        ForgeQueryLowerRuntimeSeamKey::AsyncResourceRoutingNeighbor,
        "Async/resource routing",
        ForgeQueryLowerRuntimeCloseoutPosture::DeferredNeighbor,
        ForgeQueryLowerRuntimeAuthorityOwner::Query,
        ForgeQueryLowerRuntimeRouteKind::RoutePlanning,
        "later async/resource routing milestone",
        "fail deferred until async/resource authorities have a named lower-runtime route family",
        "deferred-async-resource-routing",
    ),
    ForgeQueryLowerRuntimeCloseoutRow::new(
        ForgeQueryLowerRuntimeSeamKey::MixedTruthTimeAsyncRoutingNeighbor,
        "Mixed truth/time/async routing",
        ForgeQueryLowerRuntimeCloseoutPosture::DeferredNeighbor,
        ForgeQueryLowerRuntimeAuthorityOwner::Query,
        ForgeQueryLowerRuntimeRouteKind::RoutePlanning,
        "later mixed-cause routing milestone",
        "fail deferred until mixed truth/time/async composition has one typed route-planning model",
        "deferred-mixed-routing",
    ),
    ForgeQueryLowerRuntimeCloseoutRow::new(
        ForgeQueryLowerRuntimeSeamKey::FinalDeferredCertificationClosureNeighbor,
        "Final temporal/async/store/durable certification closure",
        ForgeQueryLowerRuntimeCloseoutPosture::DeferredNeighbor,
        ForgeQueryLowerRuntimeAuthorityOwner::Query,
        ForgeQueryLowerRuntimeRouteKind::RoutePlanning,
        "later cross-neighbor certification milestone",
        "fail deferred until later milestones can certify parity and boundary honesty for the deferred neighbors",
        "deferred-final-certification-closure",
    ),
];

pub fn forge_query_lower_runtime_closeout_registry() -> ForgeQueryLowerRuntimeCloseoutRegistry {
    ForgeQueryLowerRuntimeCloseoutRegistry::new(CLOSEOUT_ROWS)
}
