use super::crossing_types::{
    ForgeQueryLowerRuntimeArtifactStrength, ForgeQueryLowerRuntimeAuthorityOwner,
    ForgeQueryLowerRuntimeCrossingClassification, ForgeQueryLowerRuntimeCrossingInventory,
    ForgeQueryLowerRuntimeCrossingRow, ForgeQueryLowerRuntimeRouteKind,
    ForgeQueryLowerRuntimeSeamKey,
};

const CROSSING_ROWS: &[ForgeQueryLowerRuntimeCrossingRow] = &[
    ForgeQueryLowerRuntimeCrossingRow::new(
        ForgeQueryLowerRuntimeSeamKey::ComposeRead,
        "Composed current read",
        "ForgeQueryWorkspace::compose_read(...)",
        ForgeQueryLowerRuntimeCrossingClassification::CanonicalLowerRuntimeReuse,
        ForgeQueryLowerRuntimeRouteKind::RoutePlanning,
        ForgeQueryLowerRuntimeAuthorityOwner::RuntimeBridge,
        ForgeQueryLowerRuntimeArtifactStrength::TypedReceipt,
        "delegate through the current-read route row; no side-door execution",
    ),
    ForgeQueryLowerRuntimeCrossingRow::new(
        ForgeQueryLowerRuntimeSeamKey::ComposeReadWithInvariantPack,
        "Composed current read with invariant pack",
        "ForgeQueryWorkspace::compose_read_with_invariant_pack(...)",
        ForgeQueryLowerRuntimeCrossingClassification::CanonicalLowerRuntimeReuse,
        ForgeQueryLowerRuntimeRouteKind::RoutePlanning,
        ForgeQueryLowerRuntimeAuthorityOwner::RuntimeBridge,
        ForgeQueryLowerRuntimeArtifactStrength::TypedReceipt,
        "delegate through the current-read route row after invariant admission",
    ),
    ForgeQueryLowerRuntimeCrossingRow::new(
        ForgeQueryLowerRuntimeSeamKey::ExecuteReadFamily,
        "Defined read-family execution",
        "ForgeQueryWorkspace::execute_read_family(...)",
        ForgeQueryLowerRuntimeCrossingClassification::CanonicalLowerRuntimeReuse,
        ForgeQueryLowerRuntimeRouteKind::RoutePlanning,
        ForgeQueryLowerRuntimeAuthorityOwner::RuntimeBridge,
        ForgeQueryLowerRuntimeArtifactStrength::TypedReceipt,
        "delegate through the current-read route row",
    ),
    ForgeQueryLowerRuntimeCrossingRow::new(
        ForgeQueryLowerRuntimeSeamKey::ExecuteReadFamilyInBasisContext,
        "Basis-context read-family execution",
        "ForgeQueryWorkspace::execute_read_family_in_basis_context(...)",
        ForgeQueryLowerRuntimeCrossingClassification::CanonicalLowerRuntimeReuse,
        ForgeQueryLowerRuntimeRouteKind::RoutePlanning,
        ForgeQueryLowerRuntimeAuthorityOwner::RuntimeBridge,
        ForgeQueryLowerRuntimeArtifactStrength::TypedReceipt,
        "delegate through the basis-context route row",
    ),
    ForgeQueryLowerRuntimeCrossingRow::new(
        ForgeQueryLowerRuntimeSeamKey::ExecuteRuntimeCurrentReadGraph,
        "Current read execution",
        "runtime/workspace_queries.rs -> execute_runtime_current_read_graph(...)",
        ForgeQueryLowerRuntimeCrossingClassification::CanonicalLowerRuntimeReuse,
        ForgeQueryLowerRuntimeRouteKind::RoutePlanning,
        ForgeQueryLowerRuntimeAuthorityOwner::RuntimeBridge,
        ForgeQueryLowerRuntimeArtifactStrength::TypedReceipt,
        "add route plan, receipt, and boundary envelope",
    ),
    ForgeQueryLowerRuntimeCrossingRow::new(
        ForgeQueryLowerRuntimeSeamKey::ExecuteRuntimeBasisContextReadGraph,
        "Basis-context read execution",
        "runtime/workspace_queries.rs -> execute_runtime_basis_context_read_graph(...)",
        ForgeQueryLowerRuntimeCrossingClassification::CanonicalLowerRuntimeReuse,
        ForgeQueryLowerRuntimeRouteKind::RoutePlanning,
        ForgeQueryLowerRuntimeAuthorityOwner::RuntimeBridge,
        ForgeQueryLowerRuntimeArtifactStrength::TypedReceipt,
        "add route plan, receipt, and boundary envelope",
    ),
    ForgeQueryLowerRuntimeCrossingRow::new(
        ForgeQueryLowerRuntimeSeamKey::PublicLiveViewDeclaration,
        "Public live view declaration",
        "ForgeQueryWorkspace::live_view(...) and live_view_request(...)",
        ForgeQueryLowerRuntimeCrossingClassification::QueryBoundaryAdapter,
        ForgeQueryLowerRuntimeRouteKind::RoutePlanning,
        ForgeQueryLowerRuntimeAuthorityOwner::Query,
        ForgeQueryLowerRuntimeArtifactStrength::DerivedAggregateArtifact,
        "delegate through live declaration and live installation route rows",
    ),
    ForgeQueryLowerRuntimeCrossingRow::new(
        ForgeQueryLowerRuntimeSeamKey::LiveViewSchemaAdmission,
        "Live view schema admission",
        "ForgeQueryRuntimeSchemaAdapter::admit_live_view(...)",
        ForgeQueryLowerRuntimeCrossingClassification::QueryBoundaryAdapter,
        ForgeQueryLowerRuntimeRouteKind::ReadmissionHandoff,
        ForgeQueryLowerRuntimeAuthorityOwner::Query,
        ForgeQueryLowerRuntimeArtifactStrength::TypedReceipt,
        "return LiveViewDeclarationAdmissionReceipt and bind it into the declaration route proof",
    ),
    ForgeQueryLowerRuntimeCrossingRow::new(
        ForgeQueryLowerRuntimeSeamKey::LiveViewSourceDeclaration,
        "Live view source declaration",
        "ForgeQueryRuntimeSourceAdapter::declare_live_view(...)",
        ForgeQueryLowerRuntimeCrossingClassification::QueryBoundaryAdapter,
        ForgeQueryLowerRuntimeRouteKind::RoutePlanning,
        ForgeQueryLowerRuntimeAuthorityOwner::Query,
        ForgeQueryLowerRuntimeArtifactStrength::TypedReceipt,
        "bind route plan + declaration receipt + envelope",
    ),
    ForgeQueryLowerRuntimeCrossingRow::new(
        ForgeQueryLowerRuntimeSeamKey::RuntimeLiveInstallationOrchestration,
        "Runtime live installation orchestration",
        "ForgeQueryRuntime::install_live_subscription_for_request(...)",
        ForgeQueryLowerRuntimeCrossingClassification::QueryBoundaryAdapter,
        ForgeQueryLowerRuntimeRouteKind::RoutePlanning,
        ForgeQueryLowerRuntimeAuthorityOwner::Query,
        ForgeQueryLowerRuntimeArtifactStrength::DerivedAggregateArtifact,
        "emit installation boundary envelope composed from declaration, activation, and continuity rows",
    ),
    ForgeQueryLowerRuntimeCrossingRow::new(
        ForgeQueryLowerRuntimeSeamKey::RuntimeIntentAuthorityAdapter,
        "Runtime intent authority seam",
        "ForgeQueryIntentAuthorityAdapter::execute_intent(...)",
        ForgeQueryLowerRuntimeCrossingClassification::QueryBoundaryAdapter,
        ForgeQueryLowerRuntimeRouteKind::RoutePlanning,
        ForgeQueryLowerRuntimeAuthorityOwner::Query,
        ForgeQueryLowerRuntimeArtifactStrength::TypedReceipt,
        "treat this as an allowed backend-boundary seam, not silent leakage",
    ),
    ForgeQueryLowerRuntimeCrossingRow::new(
        ForgeQueryLowerRuntimeSeamKey::SubscriptionActivation,
        "Subscription activation",
        "ForgeQueryRuntimeSubscriptionActivationAdapter::admit_activation(...)",
        ForgeQueryLowerRuntimeCrossingClassification::QueryBoundaryAdapter,
        ForgeQueryLowerRuntimeRouteKind::RoutePlanning,
        ForgeQueryLowerRuntimeAuthorityOwner::Query,
        ForgeQueryLowerRuntimeArtifactStrength::TypedReceipt,
        "return SubscriptionActivationReceipt and bind activation/support evidence into the installation route proof",
    ),
    ForgeQueryLowerRuntimeCrossingRow::new(
        ForgeQueryLowerRuntimeSeamKey::SubscriptionContinuity,
        "Subscription continuity",
        "bridge continuity and Query continuation surfaces",
        ForgeQueryLowerRuntimeCrossingClassification::CanonicalLowerRuntimeReuse,
        ForgeQueryLowerRuntimeRouteKind::RoutePlanning,
        ForgeQueryLowerRuntimeAuthorityOwner::RuntimeBridge,
        ForgeQueryLowerRuntimeArtifactStrength::TypedAuthoritativeArtifact,
        "route through bridge continuity artifacts and include continuity route envelope",
    ),
    ForgeQueryLowerRuntimeCrossingRow::new(
        ForgeQueryLowerRuntimeSeamKey::PreviewBasisAdmission,
        "Preview basis admission",
        "ForgeQueryRuntimePreviewBasisAdapter::admit_preview_basis(...)",
        ForgeQueryLowerRuntimeCrossingClassification::QueryBoundaryAdapter,
        ForgeQueryLowerRuntimeRouteKind::ReadmissionHandoff,
        ForgeQueryLowerRuntimeAuthorityOwner::Query,
        ForgeQueryLowerRuntimeArtifactStrength::TypedReceipt,
        "include boundary envelope but no new lower-runtime contract",
    ),
    ForgeQueryLowerRuntimeCrossingRow::new(
        ForgeQueryLowerRuntimeSeamKey::BasisReadmissionFromTruthViewEvidence,
        "Basis readmission from truth-view evidence",
        "query_basis_lifecycle/binding.rs truth-view readmission",
        ForgeQueryLowerRuntimeCrossingClassification::CanonicalLowerRuntimeReuse,
        ForgeQueryLowerRuntimeRouteKind::ReadmissionHandoff,
        ForgeQueryLowerRuntimeAuthorityOwner::RuntimeBridge,
        ForgeQueryLowerRuntimeArtifactStrength::TypedReceipt,
        "keep current readmission pattern; add 9.3.6 envelope coverage",
    ),
    ForgeQueryLowerRuntimeCrossingRow::new(
        ForgeQueryLowerRuntimeSeamKey::BasisReadmissionFromSubscriptionEvidence,
        "Basis readmission from subscription evidence",
        "query_basis_lifecycle/binding.rs subscription declaration/activation readmission",
        ForgeQueryLowerRuntimeCrossingClassification::CanonicalLowerRuntimeReuse,
        ForgeQueryLowerRuntimeRouteKind::ReadmissionHandoff,
        ForgeQueryLowerRuntimeAuthorityOwner::RuntimeBridge,
        ForgeQueryLowerRuntimeArtifactStrength::TypedReceipt,
        "keep current readmission pattern; add 9.3.6 envelope coverage",
    ),
    ForgeQueryLowerRuntimeCrossingRow::new(
        ForgeQueryLowerRuntimeSeamKey::HistoricalBridgeLowering,
        "Historical policy lowering",
        "historical/bridge_lowering.rs",
        ForgeQueryLowerRuntimeCrossingClassification::QueryBoundaryAdapter,
        ForgeQueryLowerRuntimeRouteKind::RoutePlanning,
        ForgeQueryLowerRuntimeAuthorityOwner::RuntimeBridge,
        ForgeQueryLowerRuntimeArtifactStrength::TypedReceipt,
        "keep adapter; bind to route plan and envelope",
    ),
    ForgeQueryLowerRuntimeCrossingRow::new(
        ForgeQueryLowerRuntimeSeamKey::EffectBackedRelationalMutation,
        "Effect-backed relational mutation",
        "effect_lifecycle/execution.rs mutation path",
        ForgeQueryLowerRuntimeCrossingClassification::CanonicalLowerRuntimeReuse,
        ForgeQueryLowerRuntimeRouteKind::RoutePlanning,
        ForgeQueryLowerRuntimeAuthorityOwner::Relational,
        ForgeQueryLowerRuntimeArtifactStrength::TypedReceipt,
        "keep path; add route receipt/envelope",
    ),
    ForgeQueryLowerRuntimeCrossingRow::new(
        ForgeQueryLowerRuntimeSeamKey::EffectBackedRelationalMerge,
        "Effect-backed relational merge",
        "effect_lifecycle/execution.rs merge path",
        ForgeQueryLowerRuntimeCrossingClassification::CanonicalLowerRuntimeReuse,
        ForgeQueryLowerRuntimeRouteKind::RoutePlanning,
        ForgeQueryLowerRuntimeAuthorityOwner::Relational,
        ForgeQueryLowerRuntimeArtifactStrength::TypedReceipt,
        "keep path; add route receipt/envelope",
    ),
    ForgeQueryLowerRuntimeCrossingRow::new(
        ForgeQueryLowerRuntimeSeamKey::EffectBackedBridgeWriteback,
        "Effect-backed bridge writeback",
        "effect_lifecycle/execution_bridge.rs",
        ForgeQueryLowerRuntimeCrossingClassification::QueryBoundaryAdapter,
        ForgeQueryLowerRuntimeRouteKind::RoutePlanning,
        ForgeQueryLowerRuntimeAuthorityOwner::RuntimeBridge,
        ForgeQueryLowerRuntimeArtifactStrength::TypedReceipt,
        "keep adapter thin over the bridge admitted writeback execution contract",
    ),
    ForgeQueryLowerRuntimeCrossingRow::new(
        ForgeQueryLowerRuntimeSeamKey::WriteAuthorityBackendExecution,
        "Write authority backend execution",
        "ForgeQueryRuntimeWriteAuthorityAdapter::write(...)",
        ForgeQueryLowerRuntimeCrossingClassification::QueryBoundaryAdapter,
        ForgeQueryLowerRuntimeRouteKind::RoutePlanning,
        ForgeQueryLowerRuntimeAuthorityOwner::Query,
        ForgeQueryLowerRuntimeArtifactStrength::TypedReceipt,
        "return typed WriteAuthorityExecutionReceipt",
    ),
    ForgeQueryLowerRuntimeCrossingRow::new(
        ForgeQueryLowerRuntimeSeamKey::SignalInvalidationRouting,
        "Signal invalidation routing",
        "ForgeQueryRuntimeSignalSinkAdapter::route_write_receipt(...)",
        ForgeQueryLowerRuntimeCrossingClassification::QueryBoundaryAdapter,
        ForgeQueryLowerRuntimeRouteKind::RoutePlanning,
        ForgeQueryLowerRuntimeAuthorityOwner::Query,
        ForgeQueryLowerRuntimeArtifactStrength::TypedReceipt,
        "return SignalInvalidationRoutingReceipt and bind write routing width into the boundary proof",
    ),
    ForgeQueryLowerRuntimeCrossingRow::new(
        ForgeQueryLowerRuntimeSeamKey::IntentRuntimeExecution,
        "Intent runtime execution",
        "ForgeQueryRuntimeBackend::execute_intent(...) via installed intent_authority",
        ForgeQueryLowerRuntimeCrossingClassification::QueryBoundaryAdapter,
        ForgeQueryLowerRuntimeRouteKind::RoutePlanning,
        ForgeQueryLowerRuntimeAuthorityOwner::Query,
        ForgeQueryLowerRuntimeArtifactStrength::TypedReceipt,
        "mark conditionally supported; return boundary receipt/envelope for execution",
    ),
    ForgeQueryLowerRuntimeCrossingRow::new(
        ForgeQueryLowerRuntimeSeamKey::ProjectionSourceIntakeFromQueryReceipts,
        "Projection source intake from Query receipts",
        "projection_consumption/source.rs from read/write/query-context receipts",
        ForgeQueryLowerRuntimeCrossingClassification::QueryBoundaryAdapter,
        ForgeQueryLowerRuntimeRouteKind::ReadmissionHandoff,
        ForgeQueryLowerRuntimeAuthorityOwner::Query,
        ForgeQueryLowerRuntimeArtifactStrength::TypedAuthoritativeArtifact,
        "keep adapter; include source boundary envelope",
    ),
    ForgeQueryLowerRuntimeCrossingRow::new(
        ForgeQueryLowerRuntimeSeamKey::ProjectionSourceIntakeFromRelationalArtifacts,
        "Projection source intake from relational artifacts",
        "projection_consumption/source.rs relational row/grouped artifacts",
        ForgeQueryLowerRuntimeCrossingClassification::QueryBoundaryAdapter,
        ForgeQueryLowerRuntimeRouteKind::ReadmissionHandoff,
        ForgeQueryLowerRuntimeAuthorityOwner::Relational,
        ForgeQueryLowerRuntimeArtifactStrength::TypedAuthoritativeArtifact,
        "keep adapter; no new lower-runtime contract required",
    ),
    ForgeQueryLowerRuntimeCrossingRow::new(
        ForgeQueryLowerRuntimeSeamKey::ProjectionSourceIntakeFromBridgeArtifacts,
        "Projection source intake from bridge artifacts",
        "projection_consumption/source.rs bridge row/grouped artifacts",
        ForgeQueryLowerRuntimeCrossingClassification::QueryBoundaryAdapter,
        ForgeQueryLowerRuntimeRouteKind::ReadmissionHandoff,
        ForgeQueryLowerRuntimeAuthorityOwner::RuntimeBridge,
        ForgeQueryLowerRuntimeArtifactStrength::TypedAuthoritativeArtifact,
        "keep adapter; no new lower-runtime contract required",
    ),
    ForgeQueryLowerRuntimeCrossingRow::new(
        ForgeQueryLowerRuntimeSeamKey::CausalBridgeMaterialization,
        "Causal bridge materialization",
        "runtime/inspection/causal/builder_bridge.rs",
        ForgeQueryLowerRuntimeCrossingClassification::QueryBoundaryAdapter,
        ForgeQueryLowerRuntimeRouteKind::RoutePlanning,
        ForgeQueryLowerRuntimeAuthorityOwner::RuntimeBridge,
        ForgeQueryLowerRuntimeArtifactStrength::TypedEnvelope,
        "keep adapter; include route/receipt/envelope",
    ),
    ForgeQueryLowerRuntimeCrossingRow::new(
        ForgeQueryLowerRuntimeSeamKey::FrontierEvidenceIntake,
        "Frontier evidence intake",
        "frontier_signal_adapter.rs",
        ForgeQueryLowerRuntimeCrossingClassification::QueryBoundaryAdapter,
        ForgeQueryLowerRuntimeRouteKind::RoutePlanning,
        ForgeQueryLowerRuntimeAuthorityOwner::Signal,
        ForgeQueryLowerRuntimeArtifactStrength::TypedReceipt,
        "consume signal facade frontier route receipts without specialist imports",
    ),
];

pub fn forge_query_lower_runtime_crossing_inventory() -> ForgeQueryLowerRuntimeCrossingInventory {
    ForgeQueryLowerRuntimeCrossingInventory::new(CROSSING_ROWS)
}
