#[test]
fn application_schema_compiler_boundaries_hold() {
    let cases = trybuild::TestCases::new();
    for fixture in [
        "tests/ui/application_schema/cross_schema_field.rs",
        "tests/ui/application_schema/wrong_field_value.rs",
        "tests/ui/application_schema/wrong_unit_value.rs",
        "tests/ui/application_schema/unsupported_equality_operator.rs",
        "tests/ui/application_schema/wrong_operation_input.rs",
        "tests/ui/application_schema/wrong_relation_direction.rs",
        "tests/ui/application_schema/illegal_write.rs",
        "tests/ui/application_schema/illegal_graph_mutation.rs",
        "tests/ui/application_schema/installed_handle_constructor_is_private.rs",
        "tests/ui/application_schema/installed_handle_is_not_clone.rs",
        "tests/ui/application_schema/application_query_plan_constructor_is_private.rs",
        "tests/ui/application_schema/application_query_plan_is_not_clone.rs",
        "tests/ui/application_schema/application_query_read_completion_constructor_is_private.rs",
        "tests/ui/application_schema/application_query_read_completion_has_no_mutation_authority.rs",
        "tests/ui/application_schema/application_query_raw_plan_review_is_not_public.rs",
        "tests/ui/application_schema/application_query_planning_input_is_not_public.rs",
        "tests/ui/application_schema/monolith_graph_read_plan_is_not_public.rs",
        "tests/ui/application_schema/application_query_pinned_basis_constructor_is_private.rs",
        "tests/ui/application_schema/application_query_pinned_basis_is_not_clone.rs",
        "tests/ui/application_schema/application_query_truth_view_bases_are_move_only.rs",
        "tests/ui/application_schema/application_query_released_basis_cannot_be_reused.rs",
        "tests/ui/application_schema/application_query_projection_row_constructor_is_private.rs",
        "tests/ui/application_schema/application_query_relation_requires_cardinality.rs",
        "tests/ui/application_schema/application_query_selector_requires_matching_query.rs",
        "tests/ui/application_schema/application_query_relation_accessor_requires_cardinality.rs",
        "tests/ui/application_schema/application_query_relation_requires_matching_direction.rs",
        "tests/ui/application_schema/application_query_ordering_requires_matching_query.rs",
        "tests/ui/application_schema/application_query_ability_requires_matching_scope.rs",
        "tests/ui/application_schema/application_query_authoring_requires_lanes.rs",
        "tests/ui/application_schema/application_query_access_requires_mapped_principal.rs",
        "tests/ui/application_schema/application_query_access_requires_matching_scope.rs",
        "tests/ui/application_schema/application_query_foreign_schema_cannot_validate.rs",
        "tests/ui/application_schema/application_query_host_definition_is_not_installed.rs",
        "tests/ui/application_schema/application_query_live_target_requires_equality.rs",
        "tests/ui/application_schema/legacy_live_effect_authority_is_unavailable.rs",
        "tests/ui/application_schema/application_query_live_lease_is_thread_affine.rs",
        "tests/ui/application_schema/capability_rule_category_substitution.rs",
        "tests/ui/application_schema/capability_context_anchor_requires_matching_entity.rs",
        "tests/ui/application_schema/descriptive_capability_is_not_installed_authority.rs",
        "tests/ui/application_schema/operation_definition_requires_external_effect_choice.rs",
        "tests/ui/application_schema/operation_definition_requires_aftermath_choice.rs",
        "tests/ui/application_schema/operation_definition_rejects_duplicate_external_effect.rs",
        "tests/ui/application_schema/operation_definition_rejects_duplicate_aftermath.rs",
        "tests/ui/application_schema/principal_binding_status_cannot_fill_identity_role.rs",
        "tests/ui/application_schema/principal_binding_reversed_target_is_rejected.rs",
    ] {
        cases.compile_fail(fixture);
    }
    cases.pass("tests/ui/application_schema/capability_composition_categories_are_typed.rs");
    cases.pass("tests/ui/application_schema/operation_definition_zero_one_contracts_are_typed.rs");
    cases.pass("tests/ui/application_schema/query_and_principal_authoring_roles_are_typed.rs");
}
