#[test]
fn managed_run_authority_boundaries_hold() {
    let cases = trybuild::TestCases::new();
    cases.compile_fail(
        "tests/ui/installed_domain/managed_run/direct_run_cannot_lend_provider_call.rs",
    );
    cases
        .compile_fail("tests/ui/installed_domain/managed_run/provider_call_cannot_mint_receipt.rs");
    cases.compile_fail(
        "tests/ui/installed_domain/managed_run/raw_provider_anchor_cannot_execute.rs",
    );
    cases.compile_fail(
        "tests/ui/installed_domain/managed_run/provider_step_cannot_retain_checkpoint_payload.rs",
    );
    cases.compile_fail(
        "tests/ui/installed_domain/managed_run/provider_execution_requires_disposal.rs",
    );
    cases.compile_fail(
        "tests/ui/installed_domain/managed_run/execution_start_construction_is_private.rs",
    );
    cases.compile_fail(
        "tests/ui/installed_domain/managed_run/provider_begin_cannot_return_raw_execution.rs",
    );
    cases.compile_fail(
        "tests/ui/installed_domain/managed_run/retained_memory_construction_is_private.rs",
    );
    cases.compile_fail("tests/ui/installed_domain/managed_run/retained_memory_is_move_only.rs");
    cases.compile_fail(
        "tests/ui/installed_domain/managed_run/running_run_cannot_fabricate_terminal.rs",
    );
    cases.compile_fail(
        "tests/ui/installed_domain/managed_run/pending_chunk_cannot_advance_provider.rs",
    );
    cases.compile_fail("tests/ui/installed_domain/managed_run/yielded_run_is_move_only.rs");
    cases.compile_fail(
        "tests/ui/installed_domain/managed_run/yield_requires_consumed_safe_point.rs",
    );
    cases.compile_fail("tests/ui/installed_domain/managed_run/yield_outcome_must_be_resolved.rs");
    cases.compile_fail("tests/ui/installed_domain/managed_run/pending_chunk_cannot_yield.rs");
    cases.compile_fail(
        "tests/ui/installed_domain/managed_run/raw_checkpoint_cannot_mint_yielded_run.rs",
    );
    cases.compile_fail(
        "tests/ui/installed_domain/managed_run/yielded_run_cannot_execute_or_publish.rs",
    );
    cases.compile_fail(
        "tests/ui/installed_domain/managed_run/checkpoint_export_handoff_cannot_resume.rs",
    );
    cases.compile_fail("tests/ui/installed_domain/managed_run/bridge_receipt_cannot_readmit.rs");
    cases.compile_fail(
        "tests/ui/installed_domain/managed_run/checkpoint_evidence_cannot_restore.rs",
    );
    cases.compile_fail(
        "tests/ui/installed_domain/managed_run/partial_readmission_states_cannot_advance.rs",
    );
}
