mod branch_local;
mod committed_authority;
pub(crate) mod fixtures;
mod merge_verdicts;
mod phase5_basis;
mod readiness;
mod receipts_and_bundles;
mod scoped_merge;
mod scoped_merge_canonical;
mod scoped_merge_denials;
mod scoped_merge_diagnostics;
mod scoped_merge_evidence;
mod scoped_merge_locator;
mod scoped_merge_posture;
