use worth_kernel::facade::certification::closeout::prepare_primitive_construction_proof_boundary_compile_fail_report;

#[test]
fn kernel_public_boundary_rejects_internal_constructor_bypass() {
    let t = trybuild::TestCases::new();
    let compile_fail = "src/certification/public_facade_contracts/compile_fail";
    t.compile_fail(format!(
        "{compile_fail}/authority/public_authoring_session_constructor_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/phases/public_raw_request_cannot_skip_admission.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/phases/public_scaffold_cannot_skip_spatial_birth.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/phases/public_lowering_plan_cannot_skip_execution_phase.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/authority/public_kernel_certification_plan_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/results/public_canonical_artifact_constructor_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/results/public_prepared_result_constructor_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/results/public_root_happy_path_exports_demoted.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/reports/public_branch_local_parity_report_constructor_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/reports/public_query_basis_preview_parity_report_constructor_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/reports/public_query_boundary_gap_register_constructor_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/reports/public_realization_exhaustion_report_constructor_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/reports/public_corpus_replay_siege_report_constructor_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/reports/public_motion_report_bundle_constructor_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/reports/public_intent_arbitration_report_bundle_constructor_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/reports/public_intent_arbitration_hostility_suite_constructor_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/reports/public_intent_arbitration_helper_exports_demoted.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/reports/public_authoring_bucket_exports_demoted.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/reports/public_diagnostics_bucket_exports_demoted.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/reports/public_certification_bucket_exports_demoted.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/reports/public_misclassified_surface_exports_demoted.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/reports/public_preview_report_bundle_constructor_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/reports/public_preview_helper_exports_demoted.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/reports/public_continuity_report_bundle_constructor_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/reports/public_policy_profile_report_bundle_constructor_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/reports/public_preview_continuity_hostility_suite_constructor_not_exported.rs"
    ));
    for fixture in prepare_primitive_construction_proof_boundary_compile_fail_report().fixtures() {
        t.compile_fail(fixture.path().to_string());
    }
}
