use worth_kernel::facade::certification::closeout::prepare_primitive_construction_proof_boundary_compile_fail_report;

#[test]
fn kernel_public_boundary_rejects_internal_constructor_bypass() {
    let t = trybuild::TestCases::new();
    let compile_fail = "src/certification/public_facade_contracts/compile_fail";
    t.compile_fail(format!(
        "{compile_fail}/authority/public_authoring_session_constructor_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/authority/public_authoring_session_prepare_helpers_demoted.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/phases/public_raw_request_cannot_skip_admission.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/phases/public_intent_admission_phase_demoted.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/phases/public_spatial_intent_direct_admission_helpers_demoted.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/phases/public_spatial_intent_catalog_admission_helpers_demoted.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/phases/public_spatial_intent_finish_helpers_demoted.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/phases/public_spatial_intent_catalog_finish_helpers_demoted.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/phases/public_admitted_intent_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/phases/public_admitted_handoff_helper_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/phases/public_scaffold_handoff_helper_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/phases/public_raw_handoff_helper_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/phases/public_execution_phase_exports_demoted.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/phases/public_authoring_input_traits_are_sealed.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/authority/public_kernel_certification_plan_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/results/public_canonical_artifact_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/results/public_prepared_result_constructor_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/results/public_root_happy_path_exports_demoted.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/results/public_create_placement_exports_demoted.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/results/public_outcome_prepared_happy_path_helpers_demoted.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/results/public_prelude_happy_path_helpers_demoted.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/reports/public_branch_local_parity_report_constructor_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/reports/public_query_basis_preview_parity_report_constructor_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/reports/public_query_boundary_gap_register_constructor_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/reports/public_realization_exhaustion_report_constructor_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/reports/public_corpus_replay_siege_report_constructor_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/reports/public_motion_report_bundle_constructor_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/reports/public_intent_arbitration_report_bundle_constructor_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/reports/public_intent_arbitration_hostility_suite_constructor_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/reports/public_intent_arbitration_helper_exports_demoted.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/reports/public_authoring_bucket_exports_demoted.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/reports/public_top_level_spatial_intent_exports_demoted.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/reports/public_spatial_intent_lowering_error_not_exported_from_intents.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/reports/public_prelude_spatial_intent_exports_demoted.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/reports/public_diagnostics_bucket_exports_demoted.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/reports/public_certification_bucket_exports_demoted.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/reports/public_misclassified_surface_exports_demoted.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/reports/public_preview_report_bundle_constructor_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/reports/public_preview_helper_exports_demoted.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/reports/public_continuity_report_bundle_constructor_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/reports/public_policy_profile_report_bundle_constructor_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/reports/public_preview_continuity_hostility_suite_constructor_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/reports/public_phase_five_boundary_closeout_report_constructor_not_exported.rs"
    ));
    for fixture in prepare_primitive_construction_proof_boundary_compile_fail_report().fixtures() {
        t.compile_fail(fixture.path().to_string());
    }
}
