#[test]
fn resource_compile_fail_boundaries_hold() {
    let cases = trybuild::TestCases::new();
    cases.compile_fail("tests/ui/admitted_resource_request_fields_are_private.rs");
    cases.compile_fail("tests/ui/admitted_resource_completion_fields_are_private.rs");
    cases.compile_fail("tests/ui/cancelled_resource_request_fields_are_private.rs");
    cases.compile_fail("tests/ui/denied_resource_cancellation_fields_are_private.rs");
    cases.compile_fail("tests/ui/timed_out_resource_request_fields_are_private.rs");
    cases.compile_fail("tests/ui/denied_resource_timeout_fields_are_private.rs");
    cases.compile_fail("tests/ui/denied_resource_completion_fields_are_private.rs");
    cases.compile_fail("tests/ui/validated_completion_envelope_fields_are_private.rs");
    cases.compile_fail("tests/ui/resource_lifecycle_transition_fields_are_private.rs");
    cases.compile_fail("tests/ui/resource_supersession_record_fields_are_private.rs");
    cases.compile_fail("tests/ui/resource_request_admission_report_fields_are_private.rs");
    cases.compile_fail("tests/ui/resource_cancellation_report_fields_are_private.rs");
    cases.compile_fail("tests/ui/resource_timeout_report_fields_are_private.rs");
    cases.compile_fail("tests/ui/resource_retry_schedule_report_fields_are_private.rs");
    cases.compile_fail("tests/ui/resource_retry_admission_report_fields_are_private.rs");
    cases.compile_fail("tests/ui/resource_revalidation_report_fields_are_private.rs");
    cases.compile_fail("tests/ui/resource_completion_admission_report_fields_are_private.rs");
    cases.compile_fail("tests/ui/resource_completion_batch_admission_report_fields_are_private.rs");
    cases.compile_fail("tests/ui/resource_completion_batch_admission_report_cannot_be_cloned.rs");
    cases.compile_fail("tests/ui/resource_branch_restore_report_fields_are_private.rs");
    cases.compile_fail("tests/ui/resource_replay_reconstruction_report_fields_are_private.rs");
    cases.compile_fail("tests/ui/resource_certification_record_fields_are_private.rs");
    cases.compile_fail("tests/ui/resource_certification_record_passing_is_private.rs");
    cases.compile_fail("tests/ui/resource_certification_artifacts_cannot_be_deserialized.rs");
    cases.compile_fail(
        "tests/ui/resource_milestone_b_hostile_scenario_evidence_fields_are_private.rs",
    );
    cases.compile_fail("tests/ui/resource_milestone_b_performance_closeout_fields_are_private.rs");
    cases.compile_fail("tests/ui/resource_milestone_b_scenario_row_fields_are_private.rs");
    cases.compile_fail("tests/ui/resource_milestone_b_scenario_matrix_fields_are_private.rs");
    cases.compile_fail("tests/ui/resource_milestone_b_certification_run_fields_are_private.rs");
    cases.compile_fail("tests/ui/resource_diagnostics_expansion_budget_fields_are_private.rs");
    cases.compile_fail("tests/ui/resource_diagnostics_expansion_denial_fields_are_private.rs");
    cases.compile_fail("tests/ui/resource_diagnostics_summary_fields_are_private.rs");
    cases.compile_fail("tests/ui/resource_runtime_summary_read_report_fields_are_private.rs");
    cases.compile_fail(
        "tests/ui/resource_lifecycle_retention_compaction_report_fields_are_private.rs",
    );
    cases.compile_fail("tests/ui/denied_resource_completion_cannot_be_staged.rs");
    cases.compile_fail("tests/ui/staged_resource_completion_effect_fields_are_private.rs");
    cases.compile_fail("tests/ui/staged_denied_resource_completion_effect_fields_are_private.rs");
    cases.compile_fail("tests/ui/committed_resource_completion_artifact_fields_are_private.rs");
    cases.compile_fail("tests/ui/staged_resource_completion_effect_cannot_be_cloned.rs");
    cases.compile_fail("tests/ui/staged_denied_resource_completion_effect_cannot_be_cloned.rs");
    cases.compile_fail("tests/ui/staged_denied_resource_completion_cannot_commit.rs");
    cases.compile_fail("tests/ui/staged_denied_resource_completion_cannot_transaction_commit.rs");
    cases.compile_fail("tests/ui/committed_resource_completion_artifact_cannot_be_cloned.rs");
    cases.compile_fail("tests/ui/resource_runtime_summary_fields_are_private.rs");
    cases.compile_fail("tests/ui/resource_policy_descriptor_fields_are_private.rs");
    cases.compile_fail("tests/ui/resource_initial_lifecycle_class_fields_are_private.rs");
    cases.compile_fail("tests/ui/resource_lifecycle_policy_rejects_pending_initial_class.rs");
    cases.compile_fail("tests/ui/resource_lifecycle_policy_rejects_terminal_initial_class.rs");
    cases.compile_fail("tests/ui/raw_resource_completion_cannot_be_staged.rs");
    cases.compile_fail("tests/ui/raw_resource_completion_cannot_be_committed.rs");
    cases.compile_fail("tests/ui/admitted_resource_completion_cannot_commit_without_staging.rs");
    cases.compile_fail(
        "tests/ui/admitted_resource_completion_cannot_transaction_commit_without_staging.rs",
    );
    cases.compile_fail("tests/ui/cancelled_resource_request_cannot_be_staged_as_completion.rs");
    cases.compile_fail("tests/ui/resource_runtime_internals_are_not_public.rs");
}
