//! Public API boundary for worth-spatial.

pub use crate::bindings::{
    build_primitive_construction_birth_mapping_report,
    certify_primitive_construction_birth_completeness, construction_birth_authority,
    impossible_primitive_construction_birth_attachment, plan_primitive_construction_birth,
    primitive_birth_contract_matches_counts, primitive_birth_contract_matches_support_planes,
    PrimitiveConstructionBirthContractCounts, PrimitiveConstructionBirthFamily,
    PrimitiveConstructionBirthScaffoldInput, SpatialConstructionBirthAuthority,
    SpatialConstructionBirthCompletenessReport, SpatialConstructionBirthError,
    SpatialConstructionBirthMappingKind, SpatialConstructionBirthMappingReport,
    SpatialConstructionBirthMappingRow, SpatialConstructionBirthPlan,
    SpatialConstructionBirthRejectionKind, SpatialConstructionBirthRejectionRow,
};
pub use crate::spatial_intent::{
    admit_spatial_anchor_match_constraint, admit_spatial_frame, admit_spatial_lies_on_constraint,
    admit_spatial_move, admit_spatial_move_with_catalog, admit_spatial_offset,
    admit_spatial_placement, admit_spatial_placement_with_catalog,
    admit_spatial_points_toward_constraint, admit_spatial_points_toward_constraint_with_catalog,
    admit_spatial_reorient, admit_spatial_reorient_with_catalog, admit_spatial_rotate,
    admit_spatial_rotate_with_catalog, analyze_spatial_intent_conflict,
    analyze_spatial_intent_conflict_with_capabilities,
    apply_admitted_anchor_match_constraint_to_placement,
    apply_admitted_lies_on_constraint_to_placement, apply_admitted_move_to_placement,
    apply_admitted_offset_to_placement, apply_admitted_points_toward_constraint_to_placement,
    apply_admitted_reorient_to_placement, apply_admitted_rotate_to_placement,
    apply_spatial_placement, resolve_spatial_direction_witness,
    resolve_spatial_direction_witness_with_catalog, resolve_spatial_intent_conflict_by_choice,
    resolve_spatial_intent_conflict_by_policy, resolve_spatial_point_witness,
    resolve_spatial_point_witness_with_catalog, AdmittedSpatialAnchorMatchConstraint,
    AdmittedSpatialFrameRef, AdmittedSpatialLiesOnConstraint, AdmittedSpatialMove,
    AdmittedSpatialOffset, AdmittedSpatialPlacement, AdmittedSpatialPointsTowardConstraint,
    AdmittedSpatialReorient, AdmittedSpatialRotate, EmptySpatialWitnessCatalog,
    ResolvedSpatialDirectionWitness, ResolvedSpatialPointWitness, SpatialAnchorMatchConstraintSpec,
    SpatialAnchorRef, SpatialAuthoredActKind, SpatialAxis, SpatialBlockedCapability,
    SpatialCarrierDirectionRole, SpatialCarrierKind, SpatialCarrierPointRole,
    SpatialCatalogResolvedDirectionWitness, SpatialCatalogResolvedPointWitness,
    SpatialCatalogWitnessResolutionClass, SpatialChosenIntentAuthority,
    SpatialChosenIntentResolution, SpatialConstraintError, SpatialDirectionWitnessRef,
    SpatialFixtureWitnessCatalog, SpatialFrameBasis, SpatialFrameError, SpatialFrameRef,
    SpatialIntentArbitrationAnalysis, SpatialIntentCandidate, SpatialIntentCandidateAvailability,
    SpatialIntentCandidateRank, SpatialIntentCapabilitySet, SpatialIntentConflictClass,
    SpatialIntentEscalation, SpatialIntentExplanationClass, SpatialIntentResolutionError,
    SpatialLiesOnConstraintSpec, SpatialMotionError, SpatialMoveSpec, SpatialObservedRelationFact,
    SpatialOffsetSpec, SpatialPlacementConstraintError, SpatialPlacementError,
    SpatialPlacementFrame, SpatialPlacementGeometry, SpatialPlacementMotionError,
    SpatialPlacementSpec, SpatialPointWitnessRef, SpatialPointsTowardConstraintSpec,
    SpatialReorientSpec, SpatialRotateSpec, SpatialWitnessCatalog, SpatialWitnessFailureClass,
    SpatialWitnessResolutionClass,
};
