//! Public API boundary for worth-spatial.

pub use crate::bindings::{
    build_primitive_construction_birth_mapping_report,
    certify_primitive_construction_birth_completeness, construction_birth_authority,
    impossible_primitive_construction_birth_attachment, plan_primitive_construction_birth,
    primitive_birth_contract_matches_counts, primitive_birth_contract_matches_support_planes,
    PrimitiveConstructionBirthContractCounts, PrimitiveConstructionBirthFamily,
    PrimitiveConstructionBirthScaffoldInput, SpatialConstructionBirthAuthority,
    SpatialConstructionBirthCompletenessReport, SpatialConstructionBirthError,
    SpatialConstructionBirthMappingKind, SpatialConstructionBirthMappingReport,
    SpatialConstructionBirthMappingRow, SpatialConstructionBirthPlan,
    SpatialConstructionBirthRejectionKind, SpatialConstructionBirthRejectionRow,
};
pub use crate::spatial_intent::{
    admit_spatial_anchor_match_constraint, admit_spatial_frame, admit_spatial_lies_on_constraint,
    admit_spatial_move, admit_spatial_move_with_catalog, admit_spatial_offset,
    admit_spatial_placement, admit_spatial_placement_with_catalog,
    admit_spatial_points_toward_constraint, admit_spatial_points_toward_constraint_with_catalog,
    admit_spatial_reorient, admit_spatial_reorient_with_catalog, admit_spatial_rotate,
    admit_spatial_rotate_with_catalog, analyze_spatial_intent_conflict,
    analyze_spatial_intent_conflict_with_capabilities,
    analyze_spatial_intent_conflict_with_capabilities_and_profile,
    analyze_spatial_intent_conflict_with_profile,
    apply_admitted_anchor_match_constraint_to_placement,
    apply_admitted_anchor_match_constraint_to_placement_with_catalog,
    apply_admitted_lies_on_constraint_to_placement,
    apply_admitted_lies_on_constraint_to_placement_with_catalog, apply_admitted_move_to_placement,
    apply_admitted_move_to_placement_with_catalog, apply_admitted_offset_to_placement,
    apply_admitted_offset_to_placement_with_catalog,
    apply_admitted_points_toward_constraint_to_placement,
    apply_admitted_points_toward_constraint_to_placement_with_catalog,
    apply_admitted_reorient_to_placement, apply_admitted_reorient_to_placement_with_catalog,
    apply_admitted_rotate_to_placement, apply_admitted_rotate_to_placement_with_catalog,
    apply_spatial_placement, assess_spatial_identity_continuity_from_analysis,
    assess_spatial_identity_continuity_from_resolution, prepare_spatial_intent_preview,
    prepare_spatial_intent_preview_with_capabilities,
    prepare_spatial_intent_preview_with_capabilities_and_profile,
    prepare_spatial_intent_preview_with_profile, resolve_spatial_direction_witness,
    resolve_spatial_direction_witness_with_catalog, resolve_spatial_intent_conflict_by_choice,
    resolve_spatial_intent_conflict_by_policy, resolve_spatial_point_witness,
    resolve_spatial_point_witness_with_catalog, AdmittedSpatialAnchorMatchConstraint,
    AdmittedSpatialFrameRef, AdmittedSpatialLiesOnConstraint, AdmittedSpatialMove,
    AdmittedSpatialOffset, AdmittedSpatialPlacement, AdmittedSpatialPointsTowardConstraint,
    AdmittedSpatialReorient, AdmittedSpatialRotate, EmptySpatialWitnessCatalog,
    ResolvedSpatialDirectionWitness, ResolvedSpatialPointWitness, SpatialAnchorMatchConstraintSpec,
    SpatialAnchorRef, SpatialArbitrationPosture, SpatialAuthoredActKind, SpatialAxis,
    SpatialBlockedCapability, SpatialCarrierDirectionRole, SpatialCarrierKind,
    SpatialCarrierPointRole, SpatialCatalogResolvedDirectionWitness,
    SpatialCatalogResolvedGeometricTag, SpatialCatalogResolvedPointWitness,
    SpatialCatalogWitnessResolutionClass, SpatialChosenIntentAuthority,
    SpatialChosenIntentResolution, SpatialConstraintError, SpatialDirectionWitnessRef,
    SpatialFixtureWitnessCatalog, SpatialFrameBasis, SpatialFrameError, SpatialFrameRef,
    SpatialGeometricTagFailureClass, SpatialIdentityContinuityAssessment,
    SpatialIdentityContinuityClass, SpatialIdentityContinuityExplanationClass,
    SpatialIntentArbitrationAnalysis, SpatialIntentCandidate, SpatialIntentCandidateAvailability,
    SpatialIntentCandidateRank, SpatialIntentCapabilitySet, SpatialIntentConflictClass,
    SpatialIntentEscalation, SpatialIntentExplanationClass, SpatialIntentPolicyProfile,
    SpatialIntentPolicyProfileOverride, SpatialIntentPreview,
    SpatialIntentPreviewCommitDisposition, SpatialIntentPreviewWarning,
    SpatialIntentResolutionError, SpatialLiesOnConstraintSpec, SpatialMotionError, SpatialMoveSpec,
    SpatialObservedRelationFact, SpatialOffsetSpec, SpatialPlacementConstraintError,
    SpatialPlacementError, SpatialPlacementFrame, SpatialPlacementGeometry,
    SpatialPlacementMotionError, SpatialPlacementSpec, SpatialPointWitnessRef,
    SpatialPointsTowardConstraintSpec, SpatialPreviewRichness, SpatialReorientSpec,
    SpatialRotateSpec, SpatialThresholdPosture, SpatialWitnessCatalog, SpatialWitnessFailureClass,
    SpatialWitnessResolutionClass,
};
