mod phase1_source_package_tests;
mod phase2_parse_tests;
mod phase3_artifact_input_tests;
mod phase4_snapshot_resolution_tests;
mod phase5_structural_legality_tests;
mod phase6_binding_semantics_tests;
mod phase7_identity_seeding_tests;
