from runner.graph_runtime.nodes.node_ids import (
    APPEND_RUNNER_EVENT_NODE_ID,
    CLASSIFY_TURN_OUTCOME_NODE_ID,
    EVALUATE_ESCALATION_NODE_ID,
    EXECUTE_ROLE_TURN_NODE_ID,
    LOAD_RUN_AUTHORITY_NODE_ID,
    LOWER_PHASE_PROGRAM_NODE_ID,
    PUBLISH_PROJECTION_NODE_ID,
    ROUTE_NEXT_STEP_NODE_ID,
    ROUTE_OUTCOME_REPAIR_OR_RECOVERY_NODE_ID,
    SELECT_ROLE_SESSION_NODE_ID,
)

GRAPH_LINEAR_EDGES = (
    (LOAD_RUN_AUTHORITY_NODE_ID, LOWER_PHASE_PROGRAM_NODE_ID),
    (LOWER_PHASE_PROGRAM_NODE_ID, SELECT_ROLE_SESSION_NODE_ID),
    (EXECUTE_ROLE_TURN_NODE_ID, CLASSIFY_TURN_OUTCOME_NODE_ID),
    (CLASSIFY_TURN_OUTCOME_NODE_ID, ROUTE_OUTCOME_REPAIR_OR_RECOVERY_NODE_ID),
    (ROUTE_OUTCOME_REPAIR_OR_RECOVERY_NODE_ID, APPEND_RUNNER_EVENT_NODE_ID),
    (APPEND_RUNNER_EVENT_NODE_ID, PUBLISH_PROJECTION_NODE_ID),
    (PUBLISH_PROJECTION_NODE_ID, EVALUATE_ESCALATION_NODE_ID),
    (EVALUATE_ESCALATION_NODE_ID, ROUTE_NEXT_STEP_NODE_ID),
)

__all__ = ["GRAPH_LINEAR_EDGES"]

__all__ = ["GRAPH_LINEAR_EDGES"]
