pub use crate::spatial_intent::{
    analyze_spatial_intent_conflict, analyze_spatial_intent_conflict_with_capabilities,
    analyze_spatial_intent_conflict_with_capabilities_and_profile,
    analyze_spatial_intent_conflict_with_profile, resolve_spatial_intent_conflict_by_choice,
    resolve_spatial_intent_conflict_by_policy, SpatialArbitrationContinuityHint,
    SpatialArbitrationPosture, SpatialArbitrationPreviewHint, SpatialAuthoredActKind,
    SpatialBlockedCapability, SpatialChosenIntentAuthority, SpatialChosenIntentResolution,
    SpatialIdentityContinuityAssessment, SpatialIdentityContinuityClass,
    SpatialIdentityContinuityExplanationClass, SpatialIntentArbitrationAnalysis,
    SpatialIntentArbitrationDeclaration, SpatialIntentCandidate,
    SpatialIntentCandidateAvailability, SpatialIntentCandidateRank, SpatialIntentCapabilitySet,
    SpatialIntentCapabilitySummary, SpatialIntentConflictClass, SpatialIntentEscalation,
    SpatialIntentExplanationClass, SpatialIntentPolicyProfile, SpatialIntentPolicyProfileOverride,
    SpatialIntentPreviewCommitDisposition, SpatialIntentPreviewWarning,
    SpatialIntentResolutionError, SpatialObservedRelationFact, SpatialPreviewRichness,
    SpatialThresholdPosture,
};
