#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum HadwigerArtifactKind {
    GraphIdentity,
    GraphVersion,
    VertexIdentity,
    EdgeIdentity,
    EmbeddingCandidate,
    UnitDistanceVerification,
    ColorabilityEncoding,
    SolverRun,
    ColorabilityVerification,
    UnsatCoreArtifact,
    GadgetDefinition,
    GadgetContract,
    GraphComposition,
    ReductionTrace,
    ProofClaim,
    AIAdvisoryArtifact,
    AgentAdvisoryArtifact,
    AgentExplorationBatch,
    AgentAdvisoryContributionRecord,
    AgentExperimentProposalScreening,
    WholePlaneColoringConstruction,
    WholePlaneColoringVerification,
    LowerBoundWitnessArtifact,
    RetainedBackgroundTheorem,
    RejectionExplanation,
    PartialAdmissionExplanation,
    QueryRecoveryExplanation,
    RepairObligation,
    ReusableNegativeEvidence,
    ConservativeEscalationExplanation,
    ResearchEvidenceCorpus,
    GraphResidentFailure,
    FailureBasisFingerprint,
    PatternSignature,
    MotifObservation,
    InvariantHypothesis,
    InvariantCandidate,
    CounterexampleObligation,
    DeadEndSignature,
    ExperimentSuppressionProof,
    ExperimentPlan,
    ExperimentBatch,
    ExperimentResult,
    DiscoveryFrontier,
    DerivedFrontierState,
    RetiredHypothesisRecord,
    ReactivationCondition,
    HadwigerResearchInvariantCatalog,
    ResearchGraphInvariantRule,
    ResearchGraphInvariantViolation,
    ResearchGraphInvariantDenial,
    ResearchGraphInvariantRuntimeProjection,
    ResearchCockpitSession,
    ResearchCockpitActionPacket,
    ResearchCockpitEquivalenceClass,
    ResearchCockpitReport,
    HadwigerCertificationBundle,
    TileEquivalenceWitness,
    CandidateScreeningInvariantCatalog,
    CandidateScreeningInvariantNode,
    CandidateScreeningEvaluation,
    CandidateScreeningEvaluationReport,
    CandidateScreeningAdvisoryArtifact,
    CandidateScreeningAdvisoryContributionRecord,
    MotifArtifact,
    TerminalForcingRelation,
    TilingCell,
    TilingGeometryCertification,
    TilingBoundaryOwnershipReport,
    TilingContactReplayReport,
    PeriodicQuotientCell,
    GeneratedPatternReplaySuite,
    GeneratedPatternReplayReport,
    TilingConflictGraph,
    ConflictCoreExtractionReport,
    TilingCandidateEquivalenceProof,
    TilingCandidateSuppressionProof,
    TilingReactivationChecked,
    TilingIterationPacket,
    TilingIterationReplayReport,
}

impl HadwigerArtifactKind {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::GraphIdentity => "graph_identity",
            Self::GraphVersion => "graph_version",
            Self::VertexIdentity => "vertex_identity",
            Self::EdgeIdentity => "edge_identity",
            Self::EmbeddingCandidate => "embedding_candidate",
            Self::UnitDistanceVerification => "unit_distance_verification",
            Self::ColorabilityEncoding => "colorability_encoding",
            Self::SolverRun => "solver_run",
            Self::ColorabilityVerification => "colorability_verification",
            Self::UnsatCoreArtifact => "unsat_core_artifact",
            Self::GadgetDefinition => "gadget_definition",
            Self::GadgetContract => "gadget_contract",
            Self::GraphComposition => "graph_composition",
            Self::ReductionTrace => "reduction_trace",
            Self::ProofClaim => "proof_claim",
            Self::AIAdvisoryArtifact => "ai_advisory_artifact",
            Self::AgentAdvisoryArtifact => "agent_advisory_artifact",
            Self::AgentExplorationBatch => "agent_exploration_batch",
            Self::AgentAdvisoryContributionRecord => "agent_advisory_contribution_record",
            Self::AgentExperimentProposalScreening => "agent_experiment_proposal_screening",
            Self::WholePlaneColoringConstruction => "whole_plane_coloring_construction",
            Self::WholePlaneColoringVerification => "whole_plane_coloring_verification",
            Self::LowerBoundWitnessArtifact => "lower_bound_witness_artifact",
            Self::RetainedBackgroundTheorem => "retained_background_theorem",
            Self::RejectionExplanation => "rejection_explanation",
            Self::PartialAdmissionExplanation => "partial_admission_explanation",
            Self::QueryRecoveryExplanation => "query_recovery_explanation",
            Self::RepairObligation => "repair_obligation",
            Self::ReusableNegativeEvidence => "reusable_negative_evidence",
            Self::ConservativeEscalationExplanation => "conservative_escalation_explanation",
            Self::ResearchEvidenceCorpus => "research_evidence_corpus",
            Self::GraphResidentFailure => "graph_resident_failure",
            Self::FailureBasisFingerprint => "failure_basis_fingerprint",
            Self::PatternSignature => "pattern_signature",
            Self::MotifObservation => "motif_observation",
            Self::InvariantHypothesis => "invariant_hypothesis",
            Self::InvariantCandidate => "invariant_candidate",
            Self::CounterexampleObligation => "counterexample_obligation",
            Self::DeadEndSignature => "dead_end_signature",
            Self::ExperimentSuppressionProof => "experiment_suppression_proof",
            Self::ExperimentPlan => "experiment_plan",
            Self::ExperimentBatch => "experiment_batch",
            Self::ExperimentResult => "experiment_result",
            Self::DiscoveryFrontier => "discovery_frontier",
            Self::DerivedFrontierState => "derived_frontier_state",
            Self::RetiredHypothesisRecord => "retired_hypothesis_record",
            Self::ReactivationCondition => "reactivation_condition",
            Self::HadwigerResearchInvariantCatalog => "hadwiger_research_invariant_catalog",
            Self::ResearchGraphInvariantRule => "research_graph_invariant_rule",
            Self::ResearchGraphInvariantViolation => "research_graph_invariant_violation",
            Self::ResearchGraphInvariantDenial => "research_graph_invariant_denial",
            Self::ResearchGraphInvariantRuntimeProjection => {
                "research_graph_invariant_runtime_projection"
            }
            Self::ResearchCockpitSession => "research_cockpit_session",
            Self::ResearchCockpitActionPacket => "research_cockpit_action_packet",
            Self::ResearchCockpitEquivalenceClass => "research_cockpit_equivalence_class",
            Self::ResearchCockpitReport => "research_cockpit_report",
            Self::HadwigerCertificationBundle => "hadwiger_certification_bundle",
            Self::TileEquivalenceWitness => "tile_equivalence_witness",
            Self::CandidateScreeningInvariantCatalog => "candidate_screening_invariant_catalog",
            Self::CandidateScreeningInvariantNode => "candidate_screening_invariant_node",
            Self::CandidateScreeningEvaluation => "candidate_screening_evaluation",
            Self::CandidateScreeningEvaluationReport => "candidate_screening_evaluation_report",
            Self::CandidateScreeningAdvisoryArtifact => "candidate_screening_advisory_artifact",
            Self::CandidateScreeningAdvisoryContributionRecord => {
                "candidate_screening_advisory_contribution_record"
            }
            Self::MotifArtifact => "motif_artifact",
            Self::TerminalForcingRelation => "terminal_forcing_relation",
            Self::TilingCell => "tiling_cell",
            Self::TilingGeometryCertification => "tiling_geometry_certification",
            Self::TilingBoundaryOwnershipReport => "tiling_boundary_ownership_report",
            Self::TilingContactReplayReport => "tiling_contact_replay_report",
            Self::PeriodicQuotientCell => "periodic_quotient_cell",
            Self::GeneratedPatternReplaySuite => "generated_pattern_replay_suite",
            Self::GeneratedPatternReplayReport => "generated_pattern_replay_report",
            Self::TilingConflictGraph => "tiling_conflict_graph",
            Self::ConflictCoreExtractionReport => "conflict_core_extraction_report",
            Self::TilingCandidateEquivalenceProof => "tiling_candidate_equivalence_proof",
            Self::TilingCandidateSuppressionProof => "tiling_candidate_suppression_proof",
            Self::TilingReactivationChecked => "tiling_reactivation_checked",
            Self::TilingIterationPacket => "tiling_iteration_packet",
            Self::TilingIterationReplayReport => "tiling_iteration_replay_report",
        }
    }
}
