[package]
name = "forge-ui-components"
edition.workspace = true
version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
forge-ui-theme  = { workspace = true }
egui            = { workspace = true }
egui_extras     = { version = "0.31", features = ["svg", "image"] }
