[package]
name = "forge-signal"
edition.workspace = true
version.workspace = true
license.workspace = true
description = "Generic deterministic reactive computation runtime"

[dependencies]
tracing.workspace = true
serde = { workspace = true, features = ["derive"] }
smallvec = { workspace = true, features = ["serde"] }

[lints]
workspace = true
