from __future__ import annotations

STANDARD_LOOP_PROGRAM_ID = "standard_loop"
IMPLEMENT_REVIEW_LOOP_PROGRAM_ID = "implement_review_loop"
STANDARD_SINGLE_PASS_FOLLOWUPS_PROGRAM_ID = "standard_single_pass_followups"
SINGLE_PROMPT_PROGRAM_ID = "single_prompt"

SUPPORTED_PROGRAM_IDS = {
    STANDARD_LOOP_PROGRAM_ID,
    IMPLEMENT_REVIEW_LOOP_PROGRAM_ID,
    STANDARD_SINGLE_PASS_FOLLOWUPS_PROGRAM_ID,
    SINGLE_PROMPT_PROGRAM_ID,
}
