use super::types::{
    WorthQueryIntentAdmissionCoverageInventory, WorthQueryIntentAdmissionCoverageRow,
    WorthQueryIntentAdmissionCoverageStatus, WorthQueryIntentAdmissionCoveredEntrypoint,
    WorthQueryIntentAdmissionDecisionClass, WorthQueryIntentAdmissionEligibilityAuthority,
    WorthQueryIntentAdmissionExecutionBoundary, WorthQueryIntentAdmissionExecutionHandoffInventory,
    WorthQueryIntentAdmissionPlanKind, WorthQueryIntentAdmissionResultArtifact,
    WorthQueryIntentAdmissionSurfaceDescriptor,
};
use crate::intent_admission::surface_catalog::*;
use crate::intent_admission::WorthQueryIntentAdmissionFamily;

const INTENT_ADMISSION_ROWS: [WorthQueryIntentAdmissionCoverageRow; 14] = [
    WorthQueryIntentAdmissionCoverageRow::new(
        WorthQueryIntentAdmissionFamily::AuthoritativeUserIntent,
        WorthQueryIntentAdmissionCoveredEntrypoint::ExecuteIntent,
        WorthQueryIntentAdmissionExecutionBoundary::covered_backend_intent_authority_route(),
        WorthQueryIntentAdmissionCoverageStatus::Implemented,
        WorthQueryIntentAdmissionEligibilityAuthority::RuntimeIntentAuthorityAdapter,
        WorthQueryIntentAdmissionPlanKind::AuthoritativeIntentExecutionPlan,
        WorthQueryIntentAdmissionExecutionHandoffInventory::available(
            "WorthQueryAdmittedIntentExecutionHandoff",
        ),
        WorthQueryIntentAdmissionDecisionClass::AdvisoryNotYetExercisedOnCoveredEntrypoint,
        WorthQueryIntentAdmissionDecisionClass::AdmissionOrExecutionViolation,
        WorthQueryIntentAdmissionResultArtifact::WorthQueryIntentReceipt,
        WorthQueryIntentAdmissionSurfaceDescriptor::available(
            AUTHORITATIVE_RUNTIME_RAW_ENTRYPOINT,
        ),
        WorthQueryIntentAdmissionSurfaceDescriptor::available(
            AUTHORITATIVE_RUNTIME_COMMON_PATH,
        ),
        WorthQueryIntentAdmissionSurfaceDescriptor::available(
            AUTHORITATIVE_RUNTIME_ADVANCED_PATH,
        ),
    ),
    WorthQueryIntentAdmissionCoverageRow::new(
        WorthQueryIntentAdmissionFamily::EffectTriggeredWriteIntent,
        WorthQueryIntentAdmissionCoveredEntrypoint::ExecuteNextEffectWriteIntent,
        WorthQueryIntentAdmissionExecutionBoundary::covered_backend_intent_authority_route(),
        WorthQueryIntentAdmissionCoverageStatus::Implemented,
        WorthQueryIntentAdmissionEligibilityAuthority::RuntimeIntentAuthorityAdapter,
        WorthQueryIntentAdmissionPlanKind::EffectTriggeredIntentExecutionPlan,
        WorthQueryIntentAdmissionExecutionHandoffInventory::available(
            "WorthQueryAdmittedIntentExecutionHandoff",
        ),
        WorthQueryIntentAdmissionDecisionClass::AdvisoryNotYetExercisedOnCoveredEntrypoint,
        WorthQueryIntentAdmissionDecisionClass::AdmissionOrExecutionViolation,
        WorthQueryIntentAdmissionResultArtifact::WorthQueryEffectIntentReceipt,
        WorthQueryIntentAdmissionSurfaceDescriptor::available(
            EFFECT_RUNTIME_RAW_ENTRYPOINT,
        ),
        WorthQueryIntentAdmissionSurfaceDescriptor::available(
            EFFECT_RUNTIME_COMMON_PATH,
        ),
        WorthQueryIntentAdmissionSurfaceDescriptor::available(
            EFFECT_RUNTIME_ADVANCED_PATH,
        ),
    ),
    WorthQueryIntentAdmissionCoverageRow::new(
        WorthQueryIntentAdmissionFamily::AuthoritativeMutationIntent,
        WorthQueryIntentAdmissionCoveredEntrypoint::ExecuteScalarWrite,
        WorthQueryIntentAdmissionExecutionBoundary::covered_backend_write_authority_route(),
        WorthQueryIntentAdmissionCoverageStatus::Implemented,
        WorthQueryIntentAdmissionEligibilityAuthority::RuntimeWriteAuthorityAdapter,
        WorthQueryIntentAdmissionPlanKind::AuthoritativeMutationExecutionPlan,
        WorthQueryIntentAdmissionExecutionHandoffInventory::available(
            "WorthQueryAdmittedIntentExecutionHandoff",
        ),
        WorthQueryIntentAdmissionDecisionClass::AdvisoryNotYetExercisedOnCoveredEntrypoint,
        WorthQueryIntentAdmissionDecisionClass::AdmissionOrExecutionViolation,
        WorthQueryIntentAdmissionResultArtifact::WorthQueryWriteReceipt,
        WorthQueryIntentAdmissionSurfaceDescriptor::available(
            AUTHORITATIVE_MUTATION_RAW_ENTRYPOINT,
        ),
        WorthQueryIntentAdmissionSurfaceDescriptor::available(
            AUTHORITATIVE_MUTATION_COMMON_PATHS,
        ),
        WorthQueryIntentAdmissionSurfaceDescriptor::available(
            AUTHORITATIVE_MUTATION_ADVANCED_PATHS,
        ),
    ),
    WorthQueryIntentAdmissionCoverageRow::new(
        WorthQueryIntentAdmissionFamily::AuthoritativeMutationIntent,
        WorthQueryIntentAdmissionCoveredEntrypoint::ExecuteBatchWrite,
        WorthQueryIntentAdmissionExecutionBoundary::covered_backend_write_authority_route(),
        WorthQueryIntentAdmissionCoverageStatus::Implemented,
        WorthQueryIntentAdmissionEligibilityAuthority::RuntimeWriteAuthorityAdapter,
        WorthQueryIntentAdmissionPlanKind::AuthoritativeMutationBatchExecutionPlan,
        WorthQueryIntentAdmissionExecutionHandoffInventory::available(
            "WorthQueryAdmittedIntentExecutionHandoff",
        ),
        WorthQueryIntentAdmissionDecisionClass::AdvisoryNotYetExercisedOnCoveredEntrypoint,
        WorthQueryIntentAdmissionDecisionClass::AdmissionOrExecutionViolation,
        WorthQueryIntentAdmissionResultArtifact::WorthQueryBatchWriteReceipt,
        WorthQueryIntentAdmissionSurfaceDescriptor::available(
            AUTHORITATIVE_MUTATION_BATCH_RAW_ENTRYPOINT,
        ),
        WorthQueryIntentAdmissionSurfaceDescriptor::available(
            AUTHORITATIVE_MUTATION_BATCH_COMMON_PATHS,
        ),
        WorthQueryIntentAdmissionSurfaceDescriptor::available(
            AUTHORITATIVE_MUTATION_BATCH_ADVANCED_PATHS,
        ),
    ),
    WorthQueryIntentAdmissionCoverageRow::new(
        WorthQueryIntentAdmissionFamily::BasisUseIntent,
        WorthQueryIntentAdmissionCoveredEntrypoint::BasisObservation,
        WorthQueryIntentAdmissionExecutionBoundary::deferred_neighbor(
            "no-execution-handoff-basis-observation-scope",
        ),
        WorthQueryIntentAdmissionCoverageStatus::Implemented,
        WorthQueryIntentAdmissionEligibilityAuthority::BasisLifecycleObservationAuthority,
        WorthQueryIntentAdmissionPlanKind::BasisObservationPlan,
        WorthQueryIntentAdmissionExecutionHandoffInventory::no_execution_handoff(
            "basis-observation-admitted-plan-scopes-to-lower-runtime-evidence-without-query-execution-handoff",
        ),
        WorthQueryIntentAdmissionDecisionClass::AdvisoryNotYetExercisedOnCoveredEntrypoint,
        WorthQueryIntentAdmissionDecisionClass::AdmissionOrExecutionViolation,
        WorthQueryIntentAdmissionResultArtifact::ScopedObservationBasis,
        WorthQueryIntentAdmissionSurfaceDescriptor::available(
            BASIS_OBSERVATION_RAW_ENTRYPOINT,
        ),
        WorthQueryIntentAdmissionSurfaceDescriptor::available(
            BASIS_OBSERVATION_COMMON_PATH,
        ),
        WorthQueryIntentAdmissionSurfaceDescriptor::available(
            BASIS_OBSERVATION_ADVANCED_PATH,
        ),
    ),
    WorthQueryIntentAdmissionCoverageRow::new(
        WorthQueryIntentAdmissionFamily::ProjectionConsumptionIntent,
        WorthQueryIntentAdmissionCoveredEntrypoint::ProjectionConsumption,
        WorthQueryIntentAdmissionExecutionBoundary::deferred_neighbor(
            "no-execution-handoff-projection-consumption-contract",
        ),
        WorthQueryIntentAdmissionCoverageStatus::Implemented,
        WorthQueryIntentAdmissionEligibilityAuthority::ProjectionConsumptionEligibilityAuthority,
        WorthQueryIntentAdmissionPlanKind::ProjectionConsumptionPlan,
        WorthQueryIntentAdmissionExecutionHandoffInventory::no_execution_handoff(
            "projection-consumption-admitted-plan-binds-contract-without-query-execution-handoff",
        ),
        WorthQueryIntentAdmissionDecisionClass::ProjectionWarningBearingAdmission,
        WorthQueryIntentAdmissionDecisionClass::AdmissionOrExecutionViolation,
        WorthQueryIntentAdmissionResultArtifact::MaterializedProjectionContract,
        WorthQueryIntentAdmissionSurfaceDescriptor::available(
            PROJECTION_CONSUMPTION_RAW_ENTRYPOINT,
        ),
        WorthQueryIntentAdmissionSurfaceDescriptor::available(
            PROJECTION_CONSUMPTION_COMMON_PATH,
        ),
        WorthQueryIntentAdmissionSurfaceDescriptor::available(
            PROJECTION_CONSUMPTION_ADVANCED_PATH,
        ),
    ),
    WorthQueryIntentAdmissionCoverageRow::new(
        WorthQueryIntentAdmissionFamily::ReadExecutionIntent,
        WorthQueryIntentAdmissionCoveredEntrypoint::ExecuteReadFamily,
        WorthQueryIntentAdmissionExecutionBoundary::covered_query_runtime_read_execution_route(),
        WorthQueryIntentAdmissionCoverageStatus::Implemented,
        WorthQueryIntentAdmissionEligibilityAuthority::ReadCompositionExecutionAuthority,
        WorthQueryIntentAdmissionPlanKind::ReadExecutionPlan,
        WorthQueryIntentAdmissionExecutionHandoffInventory::available(
            "WorthQueryReadExecutionHandoff",
        ),
        WorthQueryIntentAdmissionDecisionClass::AdvisoryNotYetExercisedOnCoveredEntrypoint,
        WorthQueryIntentAdmissionDecisionClass::AdmissionOrExecutionViolation,
        WorthQueryIntentAdmissionResultArtifact::WorthQueryReadResult,
        WorthQueryIntentAdmissionSurfaceDescriptor::available(
            READ_EXECUTION_RAW_ENTRYPOINT,
        ),
        WorthQueryIntentAdmissionSurfaceDescriptor::available(
            READ_EXECUTION_COMMON_PATHS,
        ),
        WorthQueryIntentAdmissionSurfaceDescriptor::available(
            READ_EXECUTION_ADVANCED_PATH,
        ),
    ),
    WorthQueryIntentAdmissionCoverageRow::new(
        WorthQueryIntentAdmissionFamily::ReadExecutionIntent,
        WorthQueryIntentAdmissionCoveredEntrypoint::ExecuteReadFamilyInBasisContext,
        WorthQueryIntentAdmissionExecutionBoundary::covered_query_runtime_read_execution_route(),
        WorthQueryIntentAdmissionCoverageStatus::Implemented,
        WorthQueryIntentAdmissionEligibilityAuthority::ReadCompositionExecutionAuthority,
        WorthQueryIntentAdmissionPlanKind::ReadExecutionPlan,
        WorthQueryIntentAdmissionExecutionHandoffInventory::available(
            "WorthQueryReadExecutionHandoff",
        ),
        WorthQueryIntentAdmissionDecisionClass::AdvisoryNotYetExercisedOnCoveredEntrypoint,
        WorthQueryIntentAdmissionDecisionClass::AdmissionOrExecutionViolation,
        WorthQueryIntentAdmissionResultArtifact::WorthQueryReadResult,
        WorthQueryIntentAdmissionSurfaceDescriptor::available(
            READ_EXECUTION_BASIS_RAW_ENTRYPOINT,
        ),
        WorthQueryIntentAdmissionSurfaceDescriptor::available(
            READ_EXECUTION_BASIS_COMMON_PATHS,
        ),
        WorthQueryIntentAdmissionSurfaceDescriptor::available(
            READ_EXECUTION_BASIS_ADVANCED_PATH,
        ),
    ),
    WorthQueryIntentAdmissionCoverageRow::new(
        WorthQueryIntentAdmissionFamily::ReadExecutionIntent,
        WorthQueryIntentAdmissionCoveredEntrypoint::ExecuteLiveRead,
        WorthQueryIntentAdmissionExecutionBoundary::covered_query_runtime_read_execution_route(),
        WorthQueryIntentAdmissionCoverageStatus::Implemented,
        WorthQueryIntentAdmissionEligibilityAuthority::ReadCompositionExecutionAuthority,
        WorthQueryIntentAdmissionPlanKind::ReadExecutionPlan,
        WorthQueryIntentAdmissionExecutionHandoffInventory::available(
            "WorthQueryLiveReadExecutionHandoff",
        ),
        WorthQueryIntentAdmissionDecisionClass::AdvisoryNotYetExercisedOnCoveredEntrypoint,
        WorthQueryIntentAdmissionDecisionClass::AdmissionOrExecutionViolation,
        WorthQueryIntentAdmissionResultArtifact::WorthQueryLiveReadResult,
        WorthQueryIntentAdmissionSurfaceDescriptor::available(
            LIVE_READ_RAW_ENTRYPOINT,
        ),
        WorthQueryIntentAdmissionSurfaceDescriptor::available(
            LIVE_READ_COMMON_PATHS,
        ),
        WorthQueryIntentAdmissionSurfaceDescriptor::available(
            LIVE_READ_ADVANCED_PATH,
        ),
    ),
    WorthQueryIntentAdmissionCoverageRow::new(
        WorthQueryIntentAdmissionFamily::InspectionMaterializationIntent,
        WorthQueryIntentAdmissionCoveredEntrypoint::ExecuteUnifiedInspection,
        WorthQueryIntentAdmissionExecutionBoundary::covered_query_runtime_inspection_materialization_route(),
        WorthQueryIntentAdmissionCoverageStatus::Implemented,
        WorthQueryIntentAdmissionEligibilityAuthority::InspectionMaterializationExecutionAuthority,
        WorthQueryIntentAdmissionPlanKind::UnifiedInspectionExecutionPlan,
        WorthQueryIntentAdmissionExecutionHandoffInventory::available(
            "WorthQueryUnifiedInspectionExecutionHandoff",
        ),
        WorthQueryIntentAdmissionDecisionClass::InspectionDetailRedactionAdvisory,
        WorthQueryIntentAdmissionDecisionClass::AdmissionOrExecutionViolation,
        WorthQueryIntentAdmissionResultArtifact::WorthQueryUnifiedInspectionResult,
        WorthQueryIntentAdmissionSurfaceDescriptor::available(
            UNIFIED_INSPECTION_RAW_ENTRYPOINT,
        ),
        WorthQueryIntentAdmissionSurfaceDescriptor::available(
            UNIFIED_INSPECTION_COMMON_PATHS,
        ),
        WorthQueryIntentAdmissionSurfaceDescriptor::available(
            UNIFIED_INSPECTION_ADVANCED_PATH,
        ),
    ),
    WorthQueryIntentAdmissionCoverageRow::new(
        WorthQueryIntentAdmissionFamily::InspectionMaterializationIntent,
        WorthQueryIntentAdmissionCoveredEntrypoint::ExecuteDerivedMaterialization,
        WorthQueryIntentAdmissionExecutionBoundary::covered_query_runtime_inspection_materialization_route(),
        WorthQueryIntentAdmissionCoverageStatus::Implemented,
        WorthQueryIntentAdmissionEligibilityAuthority::InspectionMaterializationExecutionAuthority,
        WorthQueryIntentAdmissionPlanKind::InspectionMaterializationExecutionPlan,
        WorthQueryIntentAdmissionExecutionHandoffInventory::available(
            "WorthQueryDerivedMaterializationExecutionHandoff",
        ),
        WorthQueryIntentAdmissionDecisionClass::AdvisoryNotYetExercisedOnCoveredEntrypoint,
        WorthQueryIntentAdmissionDecisionClass::AdmissionOrExecutionViolation,
        WorthQueryIntentAdmissionResultArtifact::WorthQueryDerivedMaterializationResult,
        WorthQueryIntentAdmissionSurfaceDescriptor::available(
            DERIVED_MATERIALIZATION_RAW_ENTRYPOINT,
        ),
        WorthQueryIntentAdmissionSurfaceDescriptor::available(
            DERIVED_MATERIALIZATION_COMMON_PATHS,
        ),
        WorthQueryIntentAdmissionSurfaceDescriptor::available(
            DERIVED_MATERIALIZATION_ADVANCED_PATH,
        ),
    ),
    WorthQueryIntentAdmissionCoverageRow::new(
        WorthQueryIntentAdmissionFamily::InspectionMaterializationIntent,
        WorthQueryIntentAdmissionCoveredEntrypoint::ExecuteDerivedInspection,
        WorthQueryIntentAdmissionExecutionBoundary::covered_query_runtime_inspection_materialization_route(),
        WorthQueryIntentAdmissionCoverageStatus::Implemented,
        WorthQueryIntentAdmissionEligibilityAuthority::InspectionMaterializationExecutionAuthority,
        WorthQueryIntentAdmissionPlanKind::InspectionMaterializationExecutionPlan,
        WorthQueryIntentAdmissionExecutionHandoffInventory::available(
            "WorthQueryDerivedInspectionExecutionHandoff",
        ),
        WorthQueryIntentAdmissionDecisionClass::AdvisoryNotYetExercisedOnCoveredEntrypoint,
        WorthQueryIntentAdmissionDecisionClass::AdmissionOrExecutionViolation,
        WorthQueryIntentAdmissionResultArtifact::WorthQueryDerivedInspectionResult,
        WorthQueryIntentAdmissionSurfaceDescriptor::available(
            DERIVED_INSPECTION_RAW_ENTRYPOINT,
        ),
        WorthQueryIntentAdmissionSurfaceDescriptor::available(
            DERIVED_INSPECTION_COMMON_PATHS,
        ),
        WorthQueryIntentAdmissionSurfaceDescriptor::available(
            DERIVED_INSPECTION_ADVANCED_PATH,
        ),
    ),
    WorthQueryIntentAdmissionCoverageRow::new(
        WorthQueryIntentAdmissionFamily::InspectionMaterializationIntent,
        WorthQueryIntentAdmissionCoveredEntrypoint::ExecuteInspectionNeighborDeferred,
        WorthQueryIntentAdmissionExecutionBoundary::deferred_neighbor(
            "inspection-materialization-neighbor-deferred-until-covered",
        ),
        WorthQueryIntentAdmissionCoverageStatus::PlannedNeighbor,
        WorthQueryIntentAdmissionEligibilityAuthority::DeferredInspectionMaterializationAuthority,
        WorthQueryIntentAdmissionPlanKind::DeferredInspectionMaterializationPlan,
        WorthQueryIntentAdmissionExecutionHandoffInventory::no_execution_handoff(
            "inspection-materialization-neighbor-deferred-until-covered",
        ),
        WorthQueryIntentAdmissionDecisionClass::DeferredNeighborSupport,
        WorthQueryIntentAdmissionDecisionClass::NeighborUnsupportedUntilCoverage,
        WorthQueryIntentAdmissionResultArtifact::DeferredInspectionMaterializationArtifact,
        WorthQueryIntentAdmissionSurfaceDescriptor::deferred(
            "inspection-materialization-neighbor-deferred-until-covered",
        ),
        WorthQueryIntentAdmissionSurfaceDescriptor::deferred(
            "inspection-materialization-neighbor-deferred-until-covered",
        ),
        WorthQueryIntentAdmissionSurfaceDescriptor::deferred(
            "inspection-materialization-neighbor-deferred-until-covered",
        ),
    ),
    WorthQueryIntentAdmissionCoverageRow::new(
        WorthQueryIntentAdmissionFamily::LowerRuntimeCapabilityRoutingIntent,
        WorthQueryIntentAdmissionCoveredEntrypoint::ExecuteExistingTruthProbeRouting,
        WorthQueryIntentAdmissionExecutionBoundary::covered_backend_existing_truth_probe_route(),
        WorthQueryIntentAdmissionCoverageStatus::Implemented,
        WorthQueryIntentAdmissionEligibilityAuthority::LowerRuntimeCapabilityRoutingAuthority,
        WorthQueryIntentAdmissionPlanKind::ExistingTruthProbeRoutingPlan,
        WorthQueryIntentAdmissionExecutionHandoffInventory::available(
            "WorthQueryExistingTruthProbeExecutionHandoff",
        ),
        WorthQueryIntentAdmissionDecisionClass::AdvisoryNotYetExercisedOnCoveredEntrypoint,
        WorthQueryIntentAdmissionDecisionClass::AdmissionOrExecutionViolation,
        WorthQueryIntentAdmissionResultArtifact::WorthQueryExistingTruthProbeResult,
        WorthQueryIntentAdmissionSurfaceDescriptor::available(
            EXISTING_TRUTH_PROBE_RAW_ENTRYPOINT,
        ),
        WorthQueryIntentAdmissionSurfaceDescriptor::available(
            EXISTING_TRUTH_PROBE_FAMILY_COMMON_PATHS,
        ),
        WorthQueryIntentAdmissionSurfaceDescriptor::available(
            EXISTING_TRUTH_PROBE_ADVANCED_PATHS,
        ),
    ),
];

pub fn worth_query_intent_admission_coverage_inventory(
) -> WorthQueryIntentAdmissionCoverageInventory {
    WorthQueryIntentAdmissionCoverageInventory::new(&INTENT_ADMISSION_ROWS)
}
