pub(super) struct AuditContract {
    pub(super) reviewer: &'static str,
    pub(super) revision_suffix: &'static str,
    pub(super) snapshot: &'static str,
    pub(super) prompt: &'static str,
    pub(super) findings: (u8, u8),
    pub(super) disposition: &'static str,
    pub(super) verification: &'static str,
}

pub(super) const AUDIT_CONTRACTS: &[AuditContract] = &[
    AuditContract {
        reviewer: "/root/c8_phase1_critic",
        revision_suffix: "plus audit-start dirty snapshot",
        snapshot: "87ddf09b1f7235fe9f317173b6857b946a7d70ac4348571b9bb557ea78aaf1e2",
        prompt: "Read-only falsify specification fidelity architecture authority topology tests and ledger closure; retain exact evidence and do not edit",
        findings: (6, 13),
        disposition: "audit-start findings closed",
        verification: "focused boundary suite plus four inherited C7 trybuild attacks",
    },
    AuditContract {
        reviewer: "/root/c8_phase1_test_critic",
        revision_suffix: "plus frozen corrected dirty snapshot",
        snapshot: "ceddb3f5156790ff9fb6345b3790e0a16466ca4194d9110cc29e88e8a3886f6a",
        prompt: "Read-only falsify test realism oracle independence mutation strength and evidence causality; retain exact evidence and do not edit",
        findings: (14, 18),
        disposition: "frozen-snapshot findings closed",
        verification: "21-test warnings-denied boundary suite plus four inherited C7 trybuild attacks",
    },
    AuditContract {
        reviewer: "/root/c8_phase1_test_closure_critic",
        revision_suffix: "plus closure-candidate dirty snapshot",
        snapshot: "45282d1c3089a9a8b553ca3e9a3621822bf4543814a9b51a7a0b1413d3adb913",
        prompt: "Read-only falsify persisted producer coupling topology path semantics API trait reachability cutover aliases causal closures audit retention and documentation equality; retain exact evidence and do not edit",
        findings: (19, 25),
        disposition: "closure-candidate findings closed",
        verification: "22-test warnings-denied boundary suite plus four inherited C7 trybuild attacks",
    },
    AuditContract {
        reviewer: "/root/c8_phase1_final_critic",
        revision_suffix: "plus final closure-candidate dirty snapshot",
        snapshot: "10a02362ff7ac6439ee907e33e231b5eea911660e7926f8800e39343faf15343",
        prompt: "Read-only falsify final Phase 1 API impl reachability grouped aliases audit binding and composition; retain exact evidence and do not edit",
        findings: (26, 28),
        disposition: "final-critic findings closed",
        verification: "read-only Rust scrutiny plus git diff and dirty Rust line-cap checks; focused boundary suite timed out before result",
    },
    AuditContract {
        reviewer: "/root/c8_phase1_postfix_closure_critic",
        revision_suffix: "plus post-F35 closure-candidate dirty snapshot",
        snapshot: "03dfafe7f05b3105f70c300de083594a69b286f7ddeace14638cc1a49687ff79",
        prompt: "Read-only falsify closure of parent alias API semantic persisted producer and codec chains performed effect homes complete dirty source manifests and causal ledger history; retain exact evidence and do not edit",
        findings: (29, 35),
        disposition: "postfix findings closed",
        verification: "26-test warnings-denied boundary suite plus four inherited C7 trybuild attacks",
    },
    AuditContract {
        reviewer: "/root/c8_phase1_absolute_final_critic",
        revision_suffix: "plus post-F42 closure-candidate review snapshot",
        snapshot: "c8cbf3df6cb80d55ba9104277a8c2d6a7eed2d45bf0885460875afcd38f829cf",
        prompt: "Read-only falsify final Phase 1 persisted syntax freshness topology destination API audit reproducibility and commit-stable source closure; retain exact evidence and do not edit",
        findings: (36, 42),
        disposition: "absolute-final findings closed",
        verification: "28-test warnings-denied boundary suite plus four inherited C7 trybuild attacks and constitutional checks",
    },
];
