//! Public API boundary for `forge-query`.
//! External crates should import through this module rather than reaching into
//! internal crate structure directly.

pub use crate::application::{
    CapabilityAdmissionDecision, CapabilityAdmissionError, CapabilityAdmissionFailureClass,
    ConfigurationAdmissionError, ConfigurationAdmissionFailureClass, ForgeQueryApplicationFacade,
    ForgeQueryCapabilityDescriptor, ForgeQueryCapabilityFamily, ForgeQueryCapabilityRegistry,
    ForgeQueryCapabilityResolution, ForgeQueryCapabilityStatus, ForgeQueryCapabilitySupportStatus,
    ForgeQueryConfig, ForgeQueryConfigCounters, ForgeQueryConfigSectionFamily,
    ForgeQueryConfigSectionResolution, ForgeQueryFacadeCounters, ForgeQueryFacadeError,
    ForgeQueryFacadeFailureClass, ForgeQueryIdentityEvolutionSupportProfile,
    ForgeQueryQueryCompositionSupportProfile, ForgeQueryQueryConfig,
    ForgeQueryQueryContextSupportProfile, ForgeQueryRelationalConfig,
    ForgeQueryRuntimeBridgeConfig, ForgeQuerySignalConfig, ForgeQueryStoreConfig,
    ForgeQuerySubsystemOwner, ForgeQuerySupportMatrix, ForgeQuerySupportReport,
    ForgeQuerySupportReportCounters, ForgeQuerySupportSectionPosture,
    HistoricalEvaluationCapability, IdentityEvolutionCapability, LiveQueryCapability,
    PreviewSessionCapability, QueryCompositionCapability, QueryContextCapability,
    QueryContextDeferredScopeMarker, QueryReadCapability, ValidatedForgeQueryConfig,
    WorkflowOrchestrationCapability,
};
pub use crate::authoring::{
    AspectFieldSelector, AuthoredBundleError, AuthoredBundleFailureClass, AuthoredResultShapeField,
    AuthoringError, AuthoringFailureClass, CollectionAuthoredQuery, CollectionAuthoredResultShape,
    CollectionQueryBuilder, CollectionResultShapeBuilder, DetailAuthoredQuery,
    DetailAuthoredResultShape, DetailQueryBuilder, DetailResultShapeBuilder, EqualityPredicate,
    GuidedAuthoringPath, IntegerComparisonOperator, IntegerComparisonPredicate, OrderingDirection,
    OrderingSelector, PredicateSelector, QueryFamily, ResultShapeFamily, RootEntityKey,
    ScalarPredicateValue, TraversalSelector,
};
pub use crate::authorized_projection::{
    runtime_backed_authorized_projection_support_profile, AuthorizedProjectionArtifact,
    AuthorizedProjectionCounters, AuthorizedProjectionError, AuthorizedProjectionFailureClass,
    AuthorizedProjectionIdentity, AuthorizedProjectionSupportProfile,
    AuthorizedProjectionSupportStatus, AuthorizedProjectionSurface, MaskedProjectionArtifact,
    PolicyAspectMask, PolicyFieldInfluenceSet, PolicyInfluenceEntry, PolicyInfluencePurpose,
    PolicyInfluenceSet, PolicyMaskSnapshot, ProjectionVisibility,
};
pub use crate::basis::{
    preflight_execution_basis, resolve_snapshot_basis, snapshot_resolution_report,
    BasisAuthorityFamily, BasisPreflightError, BasisResolutionError, BasisResolutionMode,
    ExecutionBasisIntent, ExecutionPreflightBundle, ResolvedBasisProof, ResolvedSnapshotBasis,
    ResolvedSnapshotIdentity, SnapshotLineageClass, SnapshotResolutionReport,
};
pub use crate::binding::{
    derive_binding_requirements, resolve_bindings, BindingError, BindingFailureClass,
    BindingRequirement, BindingRequirements, BindingResolution, BindingResolutionError,
    BoundBinding, BoundBindings, IdentityBindingDescriptor, NonIdentityBindingMetadata,
    NonIdentityBindingMetadataKey, QueryBindingDescriptor, QueryBindingSlot, QueryBindingSubject,
};
pub use crate::canonicalization::{
    canonicalize_request, CanonicalOrderingEntry, CanonicalPredicateEntry,
    CanonicalPredicateFamily, CanonicalProjectionEntry, CanonicalQueryArtifact,
    CanonicalQueryBundle, CanonicalResultField, CanonicalResultShapeArtifact,
    CanonicalTraversalEntry, CanonicalizationFailureClass, QueryCanonicalizationError,
};
pub use crate::collection::{
    AggregateFunctionFamily, AggregateGroupingShape, AggregateInputBreadth, AggregateShapeArtifact,
    CollectionOrderingBasis, CollectionOrderingDirection, CollectionPlanBundle,
    CollectionPlanningContext, CollectionResultFamily, CollectionWindowPolicy,
    CursorAdvanceContract, CursorBoundaryDigest, DerivedFieldComputationClass,
    DerivedFieldPlanArtifact, MaterializationBreadthClass, OpaquePageCursor, OrderingKeyPath,
    OrderingTieBreakContract, PostReadShapingPlan, RollupEdgeClass, RollupShapeArtifact,
    StableOrderingContract, TraversalBoundContract, TraversalDepthLimit, TraversalEdgeClass,
};
pub use crate::composition::{
    runtime_backed_query_composition_support_profile, BasisScopeEvidence,
    ComposedCanonicalQueryBundle, CompositionCounters, CompositionDigest, CompositionReport,
    ExpandedComposedIntent, ExpandedScopeArtifact, GuidedCompositionPath,
    QueryCompositionAdmissionFailureClass, QueryCompositionComplexityStatus,
    QueryCompositionDeferredScopeMarker, QueryCompositionError, QueryCompositionFamily,
    QueryCompositionSupportProfile, QueryScopeDescriptor, QueryTemplateDescriptor, ScopeFamily,
    ScopeLineageDigest, TemplateBindingDigest, TemplateBindingSet, TemplateFamily,
    TemplateInstantiationArtifact, TemplateParameterSlot, TemplateParameterSlotKind,
};
pub use crate::correspondence::{
    resolve_correspondence_evidence, AdvisoryStructuralAmbiguous, AdvisoryStructuralUnique,
    CorrespondenceAmbiguityEnvelope, CorrespondenceCandidateSet, CorrespondenceComplexityContract,
    CorrespondenceCostPosture, CorrespondenceCounterSnapshot, CorrespondenceDenied,
    CorrespondenceDisagreementEnvelope, CorrespondenceEvaluationError,
    CorrespondenceEvaluationFailureClass, CorrespondenceEvaluationRequest,
    CorrespondenceEvidenceResolved, CorrespondenceOutcome, CorrespondencePerformanceStatusMarker,
    CorrespondenceVocabularyReport, LineageContinuity, LineageStructuralDisagreement,
    StructuralCandidateBudget, StructuralCandidateDiscoveryPlan,
    StructuralCandidateOrderingContract, UniqueStructuralCorrespondenceWitness,
};
pub use crate::correspondence_history::{
    compose_correspondence_historical_envelope, compose_historical_admission_denied_envelope,
    compose_historical_path_denied_envelope, CorrespondenceHistoricalAmbiguityEnvelope,
    CorrespondenceHistoricalDeniedEnvelope, CorrespondenceHistoricalDisagreementEnvelope,
    CorrespondenceHistoricalEnvelope, CorrespondenceHistoricalSuccessEnvelope,
    HistoricalPathAdmissionDeniedEnvelope, HistoricalPathDeniedEnvelope,
    MetadataPreservingHistoricalResultView,
};
pub use crate::correspondence_history_parity::{
    build_correspondence_historical_parity_bundle, CorrespondenceHistoricalParityBundle,
    CorrespondenceHistoricalParityBundleError, CorrespondenceHistoricalParityVariant,
};
pub use crate::declarative_live::{
    declare_branch_compare_from_live_sessions, declare_live_query_session,
    declare_runtime_live_query_session, declare_writeback_from_live_session,
    DeclarativeBranchCompareArtifact, DeclarativeBranchCompareChangeFamily,
    DeclarativeBranchCompareFieldDelta, DeclarativeBranchCompareIdentityClass,
    DeclarativeBranchCompareInputRow, DeclarativeBranchCompareRow, DeclarativeBranchCompareValue,
    DeclarativeEqualityFilter, DeclarativeLiveQueryError, DeclarativeLiveQueryRequest,
    DeclarativeLiveQuerySession, DeclarativeLiveViewShape, DeclarativeProjectionField,
    DeclarativeWritebackArtifact, DeclarativeWritebackChange, DeclarativeWritebackIntent,
    DeclarativeWritebackValue,
};
pub use crate::diagnostics::{
    CanonicalizationCounters, CanonicalizationReport, CanonicalizationWarning,
    CompatibilityEvidence, IdentityFreezeEvidence, NormalizationEvent,
};
pub use crate::execution::{
    execute_parallel_admission_route, execute_preflight_bundle, execute_serial_fallback_route,
    ExecutionCounters, ExecutionError, ExecutionFailureClass, ExecutionReport,
    ExecutionResultEnvelope,
};
pub use crate::frontier_planning::{
    BoundedMaterializationFrontierPreflight, FrontierAwarePlan, FrontierBreadthPrediction,
    FrontierBundleRoutePlanningError, FrontierComplexityContract, FrontierCounterSnapshot,
    FrontierDisjointnessClass, FrontierParityBundle, FrontierParityBundleError,
    FrontierPerformanceStatus, FrontierPlanningCounters, FrontierPlanningReport,
    FrontierPostureDigest, FrontierPredictionDriftOutcome, FrontierPreflightAdmissionError,
    FrontierRouteCounters, FrontierRoutePlanningError, FrontierRouteReport, FrontierSurfaceDigest,
    OrderedCollectionFrontierPreflight, ParallelAdmissionDecision, ParallelAdmissionRoute,
    ParallelAdmissionRouteSet, PlannedRouteFamily, SerialFallbackBundleRoutes,
    SerialFallbackReason, SerialFallbackRoute,
};
pub use crate::frontier_signal_adapter::{
    SignalAdmissionEvidenceError, SignalFrontierSurfaceEvidence,
};
pub use crate::historical::{
    admit_historical_evaluation_path, materialization_metadata_from_resolved,
    resolve_historical_materialization_path, AdmittedHistoricalPathClass,
    HistoricalCapabilityDescriptor, HistoricalCounterSnapshot, HistoricalEvaluationAdmission,
    HistoricalEvaluationError, HistoricalEvaluationFailureClass, HistoricalEvaluationRequest,
    HistoricalMaterializationDescriptor, HistoricalMaterializationPathMetadata,
    HistoricalPathAdmitted, HistoricalPathCompatibilityOutcome, HistoricalPathComplexityContract,
    HistoricalPathCostPosture, HistoricalPathRequested, HistoricalPathResolved,
    HistoricalPathReuseDescriptor, HistoricalPathSubstitutionDenied,
    HistoricalPathVocabularyReport, HistoricalPerformanceStatusMarker,
    HistoricalReconstructionBudget, HistoricalReplaySpanBudget, PerformancePredictionDriftOutcome,
    ReplayTailReuseEligibility, RequestedHistoricalPathClass, ResolvedHistoricalPathClass,
    RetainedStateReuseEligibility,
};
pub use crate::identity::{
    BasisDigest, BindingFulfillmentDigest, CanonicalEquivalence, CanonicalQueryDigest,
    CanonicalResultShapeDigest, CollectionPlanDigest, CorrespondenceCostPostureDigest,
    CorrespondenceOutcomeDigest, CounterSnapshotDigest, FailureDigest, HistoricalCostPostureDigest,
    HistoricalPathClassDigest, LineageDigest, PlanDigest, ResultDigest, SchemaBasisDigest,
    ValidatedQueryDigest, ValidatedResultShapeDigest,
};
pub use crate::identity_evolution::{
    admit_identity_evolution_query, compare_identity_evolution_denial_classification,
    compare_identity_evolution_denial_replay, compare_identity_evolution_result_classification,
    compare_identity_evolution_result_replay, execute_admitted_identity_evolution_query,
    runtime_backed_direct_identity_evolution_support_profile, AdmittedIdentityEvolutionQuery,
    AdvisoryIdentityCandidateSet, BranchLocalityClass, CorrespondenceIdentityComparison,
    IdentityComparisonIntent, IdentityEvolutionAdmissionError,
    IdentityEvolutionAdmissionFailureClass, IdentityEvolutionAmbiguityBundle,
    IdentityEvolutionBudgetClass, IdentityEvolutionCertificationDenialEvidence,
    IdentityEvolutionCertificationEvidence, IdentityEvolutionCertificationResultEvidence,
    IdentityEvolutionComparisonBasisFamily, IdentityEvolutionComplexityContract,
    IdentityEvolutionComplexityReport, IdentityEvolutionComplexityStatus,
    IdentityEvolutionCostClass, IdentityEvolutionCounterSnapshot,
    IdentityEvolutionDeferredScopeMarker, IdentityEvolutionDeniedBundle,
    IdentityEvolutionExecutionArtifact, IdentityEvolutionExecutionCounters,
    IdentityEvolutionExecutionFamily, IdentityEvolutionIdentityBreakBundle,
    IdentityEvolutionMetadata, IdentityEvolutionOutcomeFamily,
    IdentityEvolutionPredictionDriftOutcome, IdentityEvolutionPredictionReport,
    IdentityEvolutionQueryContext, IdentityEvolutionQueryFamily, IdentityEvolutionReplayArtifact,
    IdentityEvolutionReplayParityClass, IdentityEvolutionResultBundle,
    IdentityEvolutionSupportProfile, InspectorIdentityArtifact, InspectorIdentityClassification,
    InspectorIdentityDigest, LineageTraversalDescriptor, LineageTraversalFamily,
    PluralIdentitySuccessorSet, PromotionOrMergeAuthorityState, SingularIdentityContinuityResult,
};
pub use crate::live::{
    admit_region_scoped_live_plan, build_milestone_five_live_artifact, execute_live_change,
    execute_region_scoped_live_change, lower_region_scoped_execution_to_stream_contract,
    promote_preflight_bundle_to_live, replay_live_sequence, AdmittedStreamConsumerContract,
    BoundedMaterializationLiveOutcome, BoundedMaterializationPatch,
    BoundedMaterializationPatchKind, BridgeChangeSummary, BridgeFieldDelta, BridgeLocalitySlice,
    BridgeRelationDelta, BridgeSliceCategory, ChangeRelevance, CoalescingDecision,
    CollectionMembershipChange, CollectionOrderingChange, DeliveryContractLowering,
    DeliveryContractReplayRecord, DeliveryLocalityOutcome, DetailLiveOutcome, DetailPatch,
    IrrelevantChangeClass, LiveBoundedMaterializationPatchError, LiveCertificationLane,
    LiveCertificationRejectionLane, LiveChangeOrdinal, LiveChangeSequenceId, LiveCoalescingError,
    LiveCollectionPatchError, LiveDetailPatchError, LiveExecutionEnvelope, LiveExecutionError,
    LiveExecutionReport, LiveExpectedRejectionError, LivePatchDigest, LivePatchEnvelope,
    LivePatchPayload, LivePolicyCounters, LiveProgressBasis, LiveProgressError,
    LivePromotionDescriptor, LivePromotionError, LiveQueryFamily, LiveQueryPlan, LiveRefreshError,
    LiveReplayBundle, LiveReplayDigest, LiveReplayError, LiveReplayRun, LiveReplayStepInput,
    LiveStartBasis, LiveSubscriptionDigest, LocalityAdmissionClass, LocalityAwareRelevanceContract,
    LocalityBreadthBudget, LocalityCostPosture, LocalityMaintenanceClass, LocalityMatchClass,
    LocalityMatchKind, LocalityPerformanceStatus, LocalityPredicateContract,
    LocalityScopeAdmission, LocalityScopeDigest, LocalityScopeKind, LocalitySemanticBasis,
    LocalityWideningBudget, LocalityWideningDecision, LocalityWideningPolicy,
    MaterializationScopeChange, MaterializationScopeTransition, MembershipTransition,
    MilestoneFiveLiveAdapter, MilestoneFiveLiveArtifact, OrderedCollectionLiveOutcome,
    OrderedCollectionPatch, OrderedCollectionPatchKind, OrderingFieldDelta, PartitionSliceMatch,
    PatchWidthAssessment, PatchWidthResolution, ProjectionFieldDelta, QueryDeliveryContract,
    QueryFieldKey, QueryRelevanceContract, RefreshAdmissionClass, RefreshAdmissionMatrix,
    RefreshFallback, RegionScopedExecutionReport, RegionScopedLiveCounters, RegionScopedLiveError,
    RegionScopedLiveExecutionEnvelope, RegionScopedLivePlan, RegionScopedPlanningReport,
    RegionScopedReplayBundle, RegionScopedSubscriptionIdentity, RegionSliceMatch,
    RelevantChangeClass, StreamConsumerShape, StreamContractDigest, StreamContractRequest,
    StreamLoweredDeliveryContract, StreamLoweringAdmissionClass, StreamLoweringCostPosture,
    StreamMemberProjection, StreamMemberWidthBudget, StreamWindowCompatibility,
    StreamWindowWidthBudget, SuppressionDecision, SuppressionReason,
};
pub use crate::live_performance::{
    CoalescingAdmissionClass, DebtPerformance, ForbiddenPerformance, IncrementalMaintenanceClass,
    IncrementalPatchEligibility, LiveMaintenanceComplexityContract, LiveMaintenanceCostClass,
    LiveMaintenanceWorkUnit, LivePerformanceReport, PatchWidthBudget, PatchWidthPolicy,
    PatchWidthUnit, PerformanceStatus, PerformanceStatusMarker, RefreshAdmissionStatus,
    RefreshCostClass, VerifiedPerformance,
};
pub use crate::memory_workspace::{
    ForgeQueryAspect, ForgeQueryCollection, ForgeQueryEntity, ForgeQueryLivePatch,
    ForgeQueryLiveViewHandle, ForgeQueryMemoryApp, ForgeQueryMemoryWorkspace,
    ForgeQueryMutationDelta, ForgeQueryMutationKind, ForgeQueryMutationReceipt,
    ForgeQueryWorkspaceError,
};
pub use crate::planning::{
    plan_validated_bundle, plan_validated_bundle_for_collection_family,
    planning_request_context_for_bound, planning_request_context_for_direct, seed_execution_plan,
    ExecutionCostMarker, ExecutionMechanics, ExecutionPlanBundle, FallbackDisposition,
    PlannedExecutionRoute, PlannedQueryArtifact, PlannedResultShapeArtifact,
    PlanningAmbientContext, PlanningCounters, PlanningError, PlanningFailureClass, PlanningReport,
    PlanningRequestContext, PlanningSemanticInputs,
};
pub use crate::policy_basis::{
    admit_policy_tenant_context, classify_saved_query_policy_tenant_reuse,
    runtime_backed_policy_tenant_admission_support_profile, AdmittedPolicyTenantContext,
    BranchAccessGrant, BranchAccessGrantClass, PolicyAdmissionDisposition, PolicyBasis,
    PolicyBasisCounters, PolicyBasisIdentity, PolicyCostPosture, PolicyEpoch,
    PolicyExecutionModeRequest, PolicyReuseEquivalenceContract, PolicyRuleSnapshot,
    PolicyTenantAdmissionBundle, PolicyTenantAdmissionCounters, PolicyTenantAdmissionDigest,
    PolicyTenantAdmissionError, PolicyTenantAdmissionFailureClass,
    PolicyTenantAdmissionSupportProfile, PolicyTenantPhaseOneSurface, PolicyTenantSupportStatus,
    PolicyWorkBudget, SavedQueryPolicyReuseDescriptor, SavedQueryPolicyReuseDisposition,
};
pub use crate::policy_certification::{
    employee_record_policy_fixture, employee_record_policy_scale_report,
    policy_composition_parity_report, policy_identity_aware_inspector_parity_report,
    policy_mask_parity_report, policy_view_shape_parity_report, EmployeeRecordCertificationBundle,
    EmployeeRecordPolicyFixture, EmployeeRecordPolicyScenario, EmployeeRecordQueryFamily,
    EmployeeRecordTenantVariant, PolicyCompositionParityReport,
    PolicyIdentityAwareInspectorParityReport, PolicyMaskParityReport, PolicyScaleCounterSnapshot,
    PolicyScaleFixtureSize, PolicyScaleSlopeDigest, PolicyScaleSlopeReport,
    PolicyViewShapeParityReport,
};
pub use crate::policy_delivery::{
    deny_policy_placeholder_masking, lower_policy_aware_delivery_shape, DeliveryWidthClass,
    PolicyAwareDeliveryDigest, PolicyAwareDeliveryReport, PolicyAwareDeliveryShape,
    PolicyPlaceholderMaskingDenial, PolicyPlaceholderMaskingRequest,
};
pub use crate::policy_execution_seam::{
    deny_durable_policy_artifact_reload_claim, deny_durable_policy_cursor_claim,
    deny_durable_policy_delivery_metadata_reload_claim, deny_policy_cross_tenant_fanout_claim,
    deny_policy_per_row_allocation_claim, deny_saved_query_policy_bypass_claim,
    deny_unsupported_policy_workflow_composition_claim,
    runtime_backed_policy_execution_seam_handoff_report,
    runtime_backed_policy_execution_seam_support_profile, PolicyAwareExecutionMode,
    PolicyAwareExecutionSeam, PolicyAwareExecutionSeamError, PolicyAwareExecutionSeamFailureClass,
    PolicyAwareExecutionSeamIdentity, PolicyAwareSeamCounters, PolicyExecutionSeamHandoffReport,
    PolicyExecutionSeamSupportProfile, PolicyExecutionSeamSupportStatus,
    PolicyExecutionSeamSurface,
};
pub use crate::policy_live::{
    admit_policy_aware_live_plan, certify_policy_live_drift_evidence,
    PolicyAwareLiveAdmissionReport, PolicyAwareLivePlan, PolicyAwareLiveRelevanceContract,
    PolicyDriftDisposition, PolicyLiveDensityEvidence, PolicyLiveDensityPosture,
    PolicyLiveDriftEvidenceReport, PolicyLiveEpochEvidence,
};
pub use crate::policy_narrowing::{
    classify_saved_policy_narrowing_reuse, narrow_policy_query,
    optimizer_input_from_narrowed_policy_query, runtime_backed_policy_narrowing_support_profile,
    NarrowedPolicyQueryArtifact, PolicyAwareOptimizerInput, PolicyAwareValidationReport,
    PolicyNarrowingCostPosture, PolicyNarrowingCounters, PolicyNarrowingError,
    PolicyNarrowingFailureClass, PolicyNarrowingSupportProfile, PolicyNarrowingSupportStatus,
    PolicyNarrowingSurface, PolicyNarrowingWorkBudget, SavedPolicyNarrowingReuseDescriptor,
    SavedPolicyNarrowingReuseDisposition,
};
pub use crate::policy_plan::{
    defer_store_backed_policy_historical_plan, deny_raw_diff_scrub, lower_policy_aware_branch_plan,
    lower_policy_aware_current_plan, lower_policy_aware_diff_plan,
    lower_policy_aware_historical_plan, lower_policy_aware_optimizer_input, PolicyAwareBranchPlan,
    PolicyAwareCurrentPlan, PolicyAwareDiffBasisPair, PolicyAwareDiffPlan,
    PolicyAwareDiffScrubDisposition, PolicyAwareHistoricalBasis, PolicyAwareHistoricalPlan,
    PolicyAwarePlanCore, PolicyAwarePlanCostPosture, PolicyAwarePlanDigest,
    PolicyAwarePlanLoweringReport, PolicyAwarePlanWorkBudget, PolicyAwareReadBasis,
};
pub use crate::preview::{
    admit_authoritative_preview_comparison_candidate, admit_preview_live_session_plan,
    admit_preview_promotion_parity_comparison, admit_preview_workflow_foundation,
    admit_preview_workflow_foundation_request,
    admit_promotion_eligible_preview_session_plan_binding,
    admit_read_only_preview_session_plan_binding, assess_preview_live_drift,
    bind_preflight_to_preview_session, execute_preview_live_session_plan,
    execute_promotion_eligible_preview_session_plan, execute_read_only_preview_session_plan,
    AdmittedPreviewWorkflowFoundation, AuthoritativePreviewComparisonCandidate,
    PreviewBindingCounters, PreviewBindingError, PreviewBindingFailureClass, PreviewBindingReport,
    PreviewComparisonCounters, PreviewComparisonEligibilityArtifact, PreviewComparisonError,
    PreviewComparisonFailureClass, PreviewComplexityContract, PreviewEvaluationClass,
    PreviewExecutionCounters, PreviewExecutionError, PreviewExecutionFailureClass,
    PreviewExecutionReport, PreviewLifecycleMetadata, PreviewLiveAdmissionReport,
    PreviewLiveCounters, PreviewLiveDriftDenied, PreviewLiveDriftOutcome, PreviewLiveError,
    PreviewLiveExecutionEnvelope, PreviewLiveFailureClass, PreviewLiveMaintained,
    PreviewLiveRebindArtifact, PreviewLiveSessionPlanBinding, PreviewPerformanceStatusMarker,
    PreviewSessionBasis, PreviewSessionBindingTuple, PreviewSessionPlanBinding,
    PreviewSessionQueryContext, PreviewWorkflowFoundationArtifact, PreviewWorkflowFoundationError,
    PreviewWorkflowFoundationFailureClass, PreviewWorkflowFoundationRequest,
    PromotionEligiblePreviewEvaluation, PromotionEligiblePreviewExecutionEnvelope,
    PromotionEligiblePreviewSessionPlanBinding, PromotionParityPreviewComparisonAdmission,
    ReadOnlyPreviewEvaluation, ReadOnlyPreviewExecutionEnvelope, ReadOnlyPreviewSessionPlanBinding,
};
pub use crate::program::{
    ForgeQueryAuthorityRequirement, ForgeQueryDerivedView, ForgeQueryOperation,
    ForgeQueryOperationInput, ForgeQueryOperationOutput, ForgeQueryPortType, ForgeQueryProgram,
    ForgeQueryProgramEffect, ForgeQueryProgramError, ForgeQueryProgramSource,
    ForgeQueryProgramTrace, ForgeQuerySchemaAdapter, ForgeQueryTypedPort, ForgeQueryValueExpr,
    ForgeQueryWorkflowGraph, ForgeQueryWriteCommandTemplate,
};
pub use crate::query_context::{
    admit_query_basis_context, attach_diff_query_metadata, attach_query_basis_metadata,
    bind_diff_query_context, bind_query_basis_context, build_query_basis_result_bundle,
    build_query_diff_result_bundle, execute_query_basis_context, shape_query_diff_change_set,
    AdmittedDiffQueryContext, AdmittedQueryBasisContext, ComparisonBasisFamily, DiffQueryMetadata,
    HistoricalAdmissionClass, HistoricalMaterializationCostClass, QueryBasisContextBinding,
    QueryBasisContextRequest, QueryBasisMetadata, QueryBasisResultBundle,
    QueryContextAdmissionError, QueryContextAdmissionFailureClass, QueryContextBindingSource,
    QueryContextBudgetClass, QueryContextCostClass, QueryContextCounters, QueryContextDriftOutcome,
    QueryContextExecutionArtifact, QueryContextExecutionCounters, QueryContextExecutionFamily,
    QueryContextFamily, QueryContextPredictionDriftOutcome, QueryContextPredictionReport,
    QueryDiffChangeFamily, QueryDiffChangeRow, QueryDiffChangeSetArtifact, QueryDiffResultBundle,
};
pub use crate::relationship_proof::{
    admit_relationship_proofs, runtime_backed_relationship_proof_support_profile,
    RelationshipProofAdmission, RelationshipProofAdmissionIdentity, RelationshipProofBudget,
    RelationshipProofCounters, RelationshipProofDescriptor, RelationshipProofDescriptorSet,
    RelationshipProofError, RelationshipProofFailureClass, RelationshipProofSupportProfile,
    RelationshipProofSupportStatus, RelationshipProofSurface, RelationshipProofTopologyClass,
};
pub use crate::runtime::{
    ForgeQueryArtifactInspector, ForgeQueryBridgeBackedRuntimeBackend, ForgeQueryDerivedPatch,
    ForgeQueryDerivedPatchFamily, ForgeQueryDerivedViewHandle, ForgeQueryDerivedViewMaintainer,
    ForgeQueryDerivedViewMaterialization, ForgeQueryInspectedArtifact,
    ForgeQueryInstalledOperation, ForgeQueryInstalledProgram, ForgeQueryLiveView,
    ForgeQueryPatchBatch, ForgeQueryPreviewDiff, ForgeQueryPreviewOutcome,
    ForgeQueryPreviewSession, ForgeQueryRunReceipt, ForgeQueryRuntime, ForgeQueryRuntimeBackend,
    ForgeQueryRuntimeBackendParts, ForgeQueryRuntimeBuilder, ForgeQueryRuntimeError,
    ForgeQueryRuntimeSchemaAdapter, ForgeQueryRuntimeSignalSinkAdapter,
    ForgeQueryRuntimeSourceAdapter, ForgeQueryRuntimeWriteAuthorityAdapter, ForgeQueryWriteCommand,
    ForgeQueryWriteReceipt,
};
pub use crate::saved_query::{
    evaluate_saved_query_reuse, freeze_composed_saved_query, freeze_direct_saved_query,
    runtime_backed_saved_query_support_profile, SavedQueryArtifact, SavedQueryArtifactDigest,
    SavedQueryBindingMatrixArtifact, SavedQueryBindingMatrixRow, SavedQueryComplexityStatus,
    SavedQueryError, SavedQueryFailureClass, SavedQueryFreezeContext, SavedQueryMetadata,
    SavedQueryPersistenceClaim, SavedQueryPersistenceFamily, SavedQueryRebindingDimension,
    SavedQueryRebindingLegality, SavedQueryReuseDecision, SavedQueryReuseDenial,
    SavedQueryReuseDescriptor, SavedQueryReuseOutcome, SchemaBasisEquivalenceEvidence,
};
pub use crate::schema_view::{
    QuerySchemaView, SchemaFieldKind, SchemaFieldView, SchemaRelationView,
};
pub use crate::subscription::{
    admit_active_subscription_lane, admit_preview_subscription_isolation, admit_query_subscription,
    admit_subscription_continuation_evidence, advance_subscription_acknowledgement,
    apply_active_subscription_continuation, apply_subscription_continuation,
    attach_subscription_consumer, build_active_delivery_work_packet,
    certify_query_subscription_activation, certify_query_subscription_scale_slope,
    certify_subscription_lifecycle, close_subscription_lifecycle, declare_query_subscription,
    deny_preview_authoritative_sharing, deny_raw_bridge_invalidation_delivery,
    deny_raw_cdc_delivery_fallback, discard_preview_subscription, emit_query_delivery_batch,
    join_active_subscription_lane, lower_query_subscription_maintenance_delta,
    lower_query_subscription_to_bridge, lower_subscription_continuation_report,
    measure_preview_subscription_residue, open_active_subscription_lane,
    open_query_delivery_window, prepare_subscription_activation, promote_preview_subscription,
    select_query_subscription_family, ActiveAllocationScopeWidth,
    ActiveDeliveryAffectedAttachmentWidth, ActiveDeliveryAffectedLaneWidth,
    ActiveDeliveryContinuationWidth, ActiveDeliveryDensityPosture,
    ActiveDeliveryPreviewResidueWidth, ActiveDeliveryWorkPacket, ActiveFanoutWidth,
    ActiveLaneLookupClass, ActiveRegistryLookupWidth, ActiveSubscriptionAllocationPolicy,
    ActiveSubscriptionAllocationPosture, ActiveSubscriptionCounters,
    ActiveSubscriptionDeliveryPosture, ActiveSubscriptionLane, ActiveSubscriptionLaneAdmission,
    ActiveSubscriptionLaneDigest, ActiveSubscriptionLaneHandle,
    ActiveSubscriptionLifecycleDenialKind, ActiveSubscriptionLifecycleError,
    ActiveSubscriptionLifecyclePosture, ActiveSubscriptionRuntime, ActiveSubscriptionWorkBudget,
    BridgeSubscriptionDeclarationFamilyKind, BridgeSubscriptionLoweringPlan,
    BridgeSubscriptionSliceKind, ConsumerDeliveryPacingWidth, ContinuationRemapWidth,
    DeliveryBackpressurePolicy, DeliveryWindowWidth, LiveQueryAdmissionArtifact,
    MaintenanceDeltaWidth, PatchGroupWidth, PreviewResidueWidth,
    PreviewSubscriptionDiscardCloseout, PreviewSubscriptionIsolationArtifact,
    PreviewSubscriptionIsolationDenialKind, PreviewSubscriptionIsolationError,
    PreviewSubscriptionLifecycleState, PreviewSubscriptionPromotionHandoff,
    PreviewSubscriptionResidueClass, PreviewSubscriptionResidueReport, QueryDeliveryBatch,
    QueryDeliveryBatchReceipt, QueryDeliveryDenialKind, QueryDeliveryError, QueryDeliverySequence,
    QueryDeliveryWindow, QueryDeliveryWindowBudget, QueryMaintenanceDeltaLoweringReport,
    QueryPatchGroup, QueryPatchGroupKind, QuerySubscriptionActiveLifecycleSupport,
    QuerySubscriptionAdmissionArtifact, QuerySubscriptionAdmissionBudget,
    QuerySubscriptionAdmissionDenialKind, QuerySubscriptionAdmissionDiagnosticOutcome,
    QuerySubscriptionAdmissionDiagnosticStage, QuerySubscriptionAdmissionDiagnostics,
    QuerySubscriptionAdmissionDimensions, QuerySubscriptionAdmissionError,
    QuerySubscriptionAllocationPosture, QuerySubscriptionBasisBindingRequest,
    QuerySubscriptionBasisBindingRequestKind, QuerySubscriptionBasisPosture,
    QuerySubscriptionBridgeLoweringBudget, QuerySubscriptionBridgeLoweringDenialKind,
    QuerySubscriptionBridgeLoweringError, QuerySubscriptionBridgePosture,
    QuerySubscriptionCertificationBundle, QuerySubscriptionCertificationDenialKind,
    QuerySubscriptionCertificationError, QuerySubscriptionConstructionSource,
    QuerySubscriptionCostPosture, QuerySubscriptionDeclarationArtifact,
    QuerySubscriptionDeclarationCounters, QuerySubscriptionDeclarationDenial,
    QuerySubscriptionDeclarationDenialKind, QuerySubscriptionDeclarationDigest,
    QuerySubscriptionDeliveryIntent, QuerySubscriptionDiagnosticEvidence,
    QuerySubscriptionDiagnosticOutcome, QuerySubscriptionDiagnosticStage,
    QuerySubscriptionDurableSupport, QuerySubscriptionEquivalenceBasis, QuerySubscriptionFamily,
    QuerySubscriptionFamilySelection, QuerySubscriptionFamilySelectionError,
    QuerySubscriptionFamilySelectionFailureClass, QuerySubscriptionLifecycleCloseoutSupport,
    QuerySubscriptionMaintenanceDelta, QuerySubscriptionMaintenanceDeltaKind,
    QuerySubscriptionMeaningDigest, QuerySubscriptionRelationshipProofPosture,
    QuerySubscriptionRuntimeBackedSupport, QuerySubscriptionScaleCounterSnapshot,
    QuerySubscriptionScaleFixtureSize, QuerySubscriptionScaleSlopeReport,
    QuerySubscriptionSignalStrategyRequest, QuerySubscriptionSignalStrategyRequestKind,
    QuerySubscriptionSliceBudget, QuerySubscriptionSliceIntent, QuerySubscriptionSliceKind,
    QuerySubscriptionSlicePart, QuerySubscriptionSupportProfile, QuerySubscriptionWorkBudget,
    QueryToBridgeSliceMap, QueryToBridgeSubscriptionFamilyMap, SubscriptionAcknowledgementFrontier,
    SubscriptionActivationInput, SubscriptionConsumerAttachment,
    SubscriptionConsumerAttachmentBudget, SubscriptionConsumerAttachmentDenialKind,
    SubscriptionConsumerAttachmentDigest, SubscriptionConsumerAttachmentError,
    SubscriptionConsumerAttachmentRequest, SubscriptionContinuationClass,
    SubscriptionContinuationDenialKind, SubscriptionContinuationError,
    SubscriptionContinuationEvidence, SubscriptionContinuationReport, SubscriptionFanoutPlan,
    SubscriptionFanoutReport, SubscriptionLifecycleCertificationBundle,
    SubscriptionLifecycleCertificationContext, SubscriptionLifecycleCertificationDenialKind,
    SubscriptionLifecycleCertificationError, SubscriptionLifecycleCloseDenialKind,
    SubscriptionLifecycleCloseError, SubscriptionLifecycleCloseRequest,
    SubscriptionLifecycleCloseout, SubscriptionLifecycleCloseoutKind,
    SubscriptionLifecyclePreviewCertification, SubscriptionPerformanceReceipt,
};
pub use crate::tenant_basis::{
    SchemaVariantSnapshot, TenantBasisAdmissionError, TenantBasisAdmissionFailureClass,
    TenantBasisCounters, TenantBasisEpoch, TenantBindingSnapshot, TenantResolutionClass,
    TenantSchemaBasis, TenantSchemaBasisIdentity, TenantTruthBasis, TenantTruthBasisIdentity,
};
pub use crate::typed::{
    TypedCollectionQuery, TypedCollectionQueryBuilder, TypedCollectionResultShape,
    TypedCollectionResultShapeBuilder, TypedDetailQuery, TypedDetailQueryBuilder,
    TypedDetailResultShape, TypedDetailResultShapeBuilder, TypedEqualityField,
    TypedGuidedAuthoringPath, TypedIntegerComparableField, TypedMembershipField,
    TypedOrderableField, TypedPresenceField, TypedProjectableField, TypedSchemaField,
    TypedSchemaRoot, TypedStringContainsField, TypedTraversalRelation,
};
pub use crate::validation::{
    validate_canonical_bundle, QueryValidationCounters, QueryValidationError,
    QueryValidationReport, ValidatedOrderingEntry, ValidatedOrderingSet, ValidatedPredicateEntry,
    ValidatedPredicateSet, ValidatedProjectionEntry, ValidatedQueryArtifact, ValidatedQueryBundle,
    ValidatedResultShapeArtifact, ValidatedResultShapeBinding, ValidatedTraversalEntry,
    ValidationEvent, ValidationFailureClass, ValidationRejectionMatrix, ValidationWarning,
};
pub use crate::view_shape::{
    admit_view_shape, plan_admitted_view_shape, runtime_backed_view_shape_support_profile,
    validate_canonical_bundle_for_admitted_view_shape, AdmittedViewShape,
    GroupedBaselineMaterializationContract, GroupedDeltaAdmissionPolicy,
    GroupedReplayDeliveryPosture, GroupedViewPlanningArtifact, KanbanGroupedLiveContract,
    QueryResultBindingProof, ViewShapeCompatibilityMatrixArtifact, ViewShapeComplexityReport,
    ViewShapeComplexityStatus, ViewShapeCostClass, ViewShapeDeliveryMetadata, ViewShapeDescriptor,
    ViewShapeDigest, ViewShapeError, ViewShapeFailureClass, ViewShapeFamily,
    ViewShapeIdentityBinding, ViewShapeIdentityConsumption, ViewShapeInvalidationPosture,
    ViewShapeMaintenanceContract, ViewShapePatchPosture, ViewShapePlanArtifact,
    ViewShapePlanDigest, ViewShapeValidatedBundle,
};
pub use crate::view_shape_live::{
    admit_grouped_live_view, execute_grouped_live_view_shape_change,
    execute_live_view_shape_change, lower_view_shape_plan_to_live,
    materialize_authoritative_grouped_baseline,
    materialize_authoritative_grouped_baseline_from_members,
    materialize_grouped_execution_surface_from_truth_view, AuthoritativeGroupedBaselineArtifact,
    DetailFieldPatchArtifact, FocusedInspectorAspectPatchArtifact, GroupedDeltaArtifact,
    GroupedDeltaComputation, GroupedDesiredStateArtifact, GroupedExecutionLaneValue,
    GroupedExecutionMemberRow, GroupedExecutionSurfaceArtifact, GroupedLaneIdentity,
    GroupedLiveViewShapeArtifact, GroupedMemberState, GroupedMembershipTransition,
    GroupedMembershipTransitionKind, GroupedRefreshReason, GroupedViewResultArtifact,
    LiveViewShapeArtifact, LiveViewShapeExecutionEnvelope, LiveViewShapeFamily,
    ObservedInspectorPatchArtifact, TableRowPatchArtifact, ViewShapeLiveCounters,
    ViewShapeLiveError, ViewShapeLiveFailureClass, ViewShapeLiveLowering, ViewShapeLiveReport,
    ViewShapePatchEnvelope, ViewShapePatchFamily, ViewShapePatchPayload,
    ViewShapeRefreshDisposition, ViewShapeReplayBundle, ViewShapeSuppressionDisposition,
};
pub use crate::workflow::{
    admit_query_workflow_declaration, bind_workflow_context, build_workflow_replay_bundle,
    inspect_merge_conflicts, inspect_post_merge_outcome, lower_merge_workflow_declaration,
    lower_mutation_intent_declaration, lower_query_writeback_declaration,
    shape_merge_authority_outcome, shape_mutation_authority_outcome,
    shape_writeback_authority_outcome, ConflictInspectionFamily, ConflictInspectionRow,
    LoweredMergeWorkflowDeclaration, LoweredMutationIntentDeclaration, MergeAuthorityTarget,
    MergeClassAdmission, MergeLoweringInput, MergeWorkflowIntent, MutationIntentFamily,
    MutationLoweringInput, PostMergeInspectionFamily, PostMergeInspectionRow,
    QueryConflictInspectionArtifact, QueryPostMergeInspectionArtifact, QueryWorkflowDeclaration,
    QueryWritebackDeclaration, RelationalStrategyTarget, WorkflowAdmissionError,
    WorkflowAdmissionFailureClass, WorkflowAdmissionReport, WorkflowAuthorityOutcomeArtifact,
    WorkflowAuthorityOutcomeFamily, WorkflowAuthorityTargetFamily, WorkflowBasisFamily,
    WorkflowBindingSource, WorkflowBudgetClass, WorkflowBudgetOutcome, WorkflowContextBinding,
    WorkflowCostClass, WorkflowCounters, WorkflowDeclarationFamily, WorkflowDeclarationRequest,
    WorkflowExplicitRebindArtifact, WorkflowFreshnessBinding, WorkflowFreshnessPolicy,
    WorkflowInspectionBudget, WorkflowInspectionCounters, WorkflowInspectionError,
    WorkflowInspectionFailureClass, WorkflowLoweringCounters, WorkflowLoweringError,
    WorkflowLoweringFailureClass, WorkflowPredictionDriftOutcome, WorkflowPredictionReport,
    WorkflowPreviewEvaluationClass, WorkflowReplayBundle, WorkflowStalenessClass,
    WorkflowStalenessOutcome, WritebackCausalityBinding, WritebackDeclarationFamily,
    WritebackLoweringInput,
};
