pub use crate::projection::data::{
    ProjectedBodyData, ProjectedBodyId, ProjectedEdgeData, ProjectedEdgeId, ProjectedFaceData,
    ProjectedFaceId, ProjectedHalfEdgeData, ProjectedHalfEdgeId, ProjectedLoopData,
    ProjectedLoopId, ProjectedLumpData, ProjectedLumpId, ProjectedRegionData, ProjectedRegionId,
    ProjectedShellData, ProjectedShellId, ProjectedTopology, ProjectedTopologyError,
    ProjectedEntityRef,
    ProjectedVertexData, ProjectedVertexId,
};
pub use crate::projection::logic::{
    validate_projected_acyclic_containment,
    validate_projected_bidirectional_links,
    ProjectedTopologyQueries, ProjectionBuilder, compute_projected_topology_hash,
    validate_projected_broken_boundary, validate_projected_face_adjacency,
    validate_projected_face_has_at_least_one_loop,
    validate_projected_disk_closure,
    validate_projected_hierarchy,
    validate_projected_inner_outer_loop_consistency,
    validate_projected_laminar_edges,
    validate_projected_loop_wiring, validate_projected_manifold_edges,
    validate_projected_orientation_consistency,
    validate_projected_no_dangling_refs,
    validate_projected_no_cross_disk_coedges,
    validate_projected_no_orphan_half_edges,
    validate_projected_per_component_euler,
    validate_projected_radial_edge, validate_projected_shell_closure,
    validate_projected_shell_consistency,
    validate_projected_single_owner_per_loop,
    validate_projected_topology_baseline, validate_projected_vertex_disk,
    validate_projected_vertex_disk_partition, validate_projected_vertex_outgoing,
};
pub use crate::projection::presentation::contracts::ProjectedTopologyContract;
