#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ArtifactFamilyDenial {
    AuthenticityBoundaryDenied,
    ConcreteKeyKindDoesNotMatchPhysicalKeyDomain,
    CourtroomCannotMintAuthority,
    TerminalProjectionCannotMintAuthority,
    CrossKeyScopePartitionDenied,
    CrossTenantScopePartitionDenied,
    CustodyBoundaryDenied,
    HashIdentityRequiresCollisionVerification,
    InexactFamilyCannotSatisfyExactClaim,
    MissingFamilyDeclaration,
    IncompleteProjectionPosture,
    DerivedFamilyCannotMintProductionAuthority,
    DiagnosticFamilyCannotMintProductionAuthority,
    PhysicalKeyDomainNotDeclaredForFamily,
    PhysicalKeyDomainDoesNotSupportPrefixBounds,
    PhysicalKeyDomainDoesNotSupportRangeBounds,
    ReadmissionFamilyCannotEnterStrategyAdmission,
    SecurityAuthorityMismatch,
    VerifierLaneCannotEnterStrategyAdmission,
    TransferBoundaryFamilyCannotEnterStrategyAdmission,
    OfflineImportOnlyFamilyCannotEnterStrategyAdmission,
}
