use forge_runtime_bridge::facade::{
    BridgeAspectRegistration, BridgeAspectRegistrationId, BridgeMappingId,
    BridgeMappingRegistration, CoarseRoutingMode, MappingSelector, SignalInvalidationScope,
    SliceFallbackPolicy, SubscriptionSliceKind, TruthDeltaSurfaceKind, TruthPatchScope,
};

pub fn worth_milestone_one_bridge_mapping_registrations() -> Vec<BridgeMappingRegistration> {
    vec![
        BridgeMappingRegistration::new(
            BridgeMappingId::new("worth:m1:relation-source-structural"),
            TruthPatchScope::new(
                MappingSelector::any(),
                MappingSelector::exact("source"),
                MappingSelector::any(),
            ),
            SignalInvalidationScope::new("worth.topology.structure"),
            CoarseRoutingMode::Direct,
        ),
        BridgeMappingRegistration::new(
            BridgeMappingId::new("worth:m1:relation-target-structural"),
            TruthPatchScope::new(
                MappingSelector::any(),
                MappingSelector::exact("target"),
                MappingSelector::any(),
            ),
            SignalInvalidationScope::new("worth.topology.structure"),
            CoarseRoutingMode::Direct,
        ),
        BridgeMappingRegistration::new(
            BridgeMappingId::new("worth:m1:topology-structural-lifecycle"),
            TruthPatchScope::new(
                MappingSelector::any(),
                MappingSelector::exact("lifecycle"),
                MappingSelector::any(),
            ),
            SignalInvalidationScope::new("worth.topology.structure"),
            CoarseRoutingMode::Direct,
        ),
        BridgeMappingRegistration::new(
            BridgeMappingId::new("worth:m1:topology-structure"),
            TruthPatchScope::new(
                MappingSelector::any(),
                MappingSelector::exact("topology.structure"),
                MappingSelector::any(),
            ),
            SignalInvalidationScope::new("worth.topology.structure"),
            CoarseRoutingMode::Direct,
        ),
        BridgeMappingRegistration::new(
            BridgeMappingId::new("worth:m1:topology-ownership"),
            TruthPatchScope::new(
                MappingSelector::any(),
                MappingSelector::exact("topology.ownership"),
                MappingSelector::any(),
            ),
            SignalInvalidationScope::new("worth.topology.ownership"),
            CoarseRoutingMode::Direct,
        ),
        BridgeMappingRegistration::new(
            BridgeMappingId::new("worth:m1:topology-boundary"),
            TruthPatchScope::new(
                MappingSelector::any(),
                MappingSelector::exact("topology.boundary"),
                MappingSelector::any(),
            ),
            SignalInvalidationScope::new("worth.topology.boundary"),
            CoarseRoutingMode::Direct,
        ),
        BridgeMappingRegistration::new(
            BridgeMappingId::new("worth:m1:topology-radial"),
            TruthPatchScope::new(
                MappingSelector::any(),
                MappingSelector::exact("topology.radial"),
                MappingSelector::any(),
            ),
            SignalInvalidationScope::new("worth.topology.radial"),
            CoarseRoutingMode::Direct,
        ),
        BridgeMappingRegistration::new(
            BridgeMappingId::new("worth:m1:naming-persistent-name"),
            TruthPatchScope::new(
                MappingSelector::any(),
                MappingSelector::exact("naming.persistent_name"),
                MappingSelector::any(),
            ),
            SignalInvalidationScope::new("worth.naming.persistent_name"),
            CoarseRoutingMode::Direct,
        ),
    ]
}

pub fn worth_milestone_one_bridge_aspect_registrations() -> Vec<BridgeAspectRegistration> {
    vec![
        BridgeAspectRegistration::new(
            BridgeAspectRegistrationId::new("worth:m1:aspect:relation-source-structural"),
            TruthPatchScope::new(
                MappingSelector::any(),
                MappingSelector::exact("source"),
                MappingSelector::any(),
            ),
            TruthDeltaSurfaceKind::EntityRelationEndpoint,
            SubscriptionSliceKind::SignalField,
            SliceFallbackPolicy::Disallow,
        ),
        BridgeAspectRegistration::new(
            BridgeAspectRegistrationId::new("worth:m1:aspect:relation-target-structural"),
            TruthPatchScope::new(
                MappingSelector::any(),
                MappingSelector::exact("target"),
                MappingSelector::any(),
            ),
            TruthDeltaSurfaceKind::EntityRelationEndpoint,
            SubscriptionSliceKind::SignalField,
            SliceFallbackPolicy::Disallow,
        ),
        BridgeAspectRegistration::new(
            BridgeAspectRegistrationId::new("worth:m1:aspect:topology-structural-lifecycle"),
            TruthPatchScope::new(
                MappingSelector::any(),
                MappingSelector::exact("lifecycle"),
                MappingSelector::any(),
            ),
            TruthDeltaSurfaceKind::EntityField,
            SubscriptionSliceKind::SignalField,
            SliceFallbackPolicy::Disallow,
        ),
        BridgeAspectRegistration::new(
            BridgeAspectRegistrationId::new("worth:m1:aspect:topology-structure"),
            TruthPatchScope::new(
                MappingSelector::any(),
                MappingSelector::exact("topology.structure"),
                MappingSelector::any(),
            ),
            TruthDeltaSurfaceKind::EntityField,
            SubscriptionSliceKind::SignalField,
            SliceFallbackPolicy::Disallow,
        ),
        BridgeAspectRegistration::new(
            BridgeAspectRegistrationId::new("worth:m1:aspect:topology-ownership"),
            TruthPatchScope::new(
                MappingSelector::any(),
                MappingSelector::exact("topology.ownership"),
                MappingSelector::any(),
            ),
            TruthDeltaSurfaceKind::EntityRelationEndpoint,
            SubscriptionSliceKind::SignalField,
            SliceFallbackPolicy::Disallow,
        ),
        BridgeAspectRegistration::new(
            BridgeAspectRegistrationId::new("worth:m1:aspect:topology-boundary"),
            TruthPatchScope::new(
                MappingSelector::any(),
                MappingSelector::exact("topology.boundary"),
                MappingSelector::any(),
            ),
            TruthDeltaSurfaceKind::EntityRelationEndpoint,
            SubscriptionSliceKind::SignalField,
            SliceFallbackPolicy::Disallow,
        ),
        BridgeAspectRegistration::new(
            BridgeAspectRegistrationId::new("worth:m1:aspect:topology-radial"),
            TruthPatchScope::new(
                MappingSelector::any(),
                MappingSelector::exact("topology.radial"),
                MappingSelector::any(),
            ),
            TruthDeltaSurfaceKind::EntityRelationEndpoint,
            SubscriptionSliceKind::SignalField,
            SliceFallbackPolicy::Disallow,
        ),
        BridgeAspectRegistration::new(
            BridgeAspectRegistrationId::new("worth:m1:aspect:naming-persistent-name"),
            TruthPatchScope::new(
                MappingSelector::any(),
                MappingSelector::exact("naming.persistent_name"),
                MappingSelector::any(),
            ),
            TruthDeltaSurfaceKind::EntityRelationEndpoint,
            SubscriptionSliceKind::SignalField,
            SliceFallbackPolicy::Disallow,
        ),
    ]
}
