[package]
name = "forge-ui"
edition.workspace = true
version.workspace = true
license.workspace = true

[[bin]]
name = "forge-ui"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
forge-ui-theme      = { workspace = true }
forge-ui-components = { workspace = true }
forge-query          = { workspace = true }
serde_json           = { workspace = true }

# UI framework
eframe = { workspace = true }
egui   = { workspace = true }
