use super::{
    S8HazardContainment, S8HazardProofLane, S8HazardRecovery, S8LayoutHazard, S8LayoutHazardRow,
    S9LayoutMachineTransition, S9LayoutStateMachine,
};

pub(crate) const CANONICAL_HAZARDS: &[S8LayoutHazardRow] = &[
    row(
        S8LayoutHazard::HiddenBroadScan,
        S9LayoutStateMachine::FullDeclaredScanAdmission,
        S8HazardProofLane::Runtime,
        S8HazardContainment::Deny,
        S8HazardRecovery::None,
        S9LayoutMachineTransition::Deny,
    ),
    row(
        S8LayoutHazard::StaleIndexExactness,
        S9LayoutStateMachine::StaleRebindReadmission,
        S8HazardProofLane::Runtime,
        S8HazardContainment::Rebind,
        S8HazardRecovery::RebindCurrentAuthority,
        S9LayoutMachineTransition::Deny,
    ),
    row(
        S8LayoutHazard::PartialIndexFalseAbsence,
        S9LayoutStateMachine::MaterializationCoverageAbsence,
        S8HazardProofLane::Runtime,
        S8HazardContainment::Deny,
        S8HazardRecovery::RebuildDerived,
        S9LayoutMachineTransition::ProveAbsence,
    ),
    row(
        S8LayoutHazard::DerivedAsAuthority,
        S9LayoutStateMachine::AccessSelectionAndBudgetAdmission,
        S8HazardProofLane::CompileFail,
        S8HazardContainment::Deny,
        S8HazardRecovery::None,
        S9LayoutMachineTransition::Deny,
    ),
    row(
        S8LayoutHazard::CrossScopeIndex,
        S9LayoutStateMachine::LayoutAdmission,
        S8HazardProofLane::Runtime,
        S8HazardContainment::Deny,
        S8HazardRecovery::None,
        S9LayoutMachineTransition::Deny,
    ),
    row(
        S8LayoutHazard::CorruptionAsEmpty,
        S9LayoutStateMachine::CorruptionQuarantine,
        S8HazardProofLane::Runtime,
        S8HazardContainment::Quarantine,
        S8HazardRecovery::RepairAuthoritativeSource,
        S9LayoutMachineTransition::Quarantine,
    ),
    row(
        S8LayoutHazard::DerivedRollbackAuthority,
        S9LayoutStateMachine::MigrationRollbackPlanning,
        S8HazardProofLane::CompileFail,
        S8HazardContainment::Deny,
        S8HazardRecovery::None,
        S9LayoutMachineTransition::Deny,
    ),
    row(
        S8LayoutHazard::BTreeSeparatorMisroute,
        S9LayoutStateMachine::BTreeSearchPathInvariant,
        S8HazardProofLane::Runtime,
        S8HazardContainment::Quarantine,
        S8HazardRecovery::RebuildDerived,
        S9LayoutMachineTransition::ValidateSeparator,
    ),
    row(
        S8LayoutHazard::LsmTombstoneLoss,
        S9LayoutStateMachine::CompactionCutover,
        S8HazardProofLane::FormalModel,
        S8HazardContainment::Deny,
        S8HazardRecovery::RebuildDerived,
        S9LayoutMachineTransition::AdmitTombstoneRetention,
    ),
    row(
        S8LayoutHazard::BootstrapCatalogMisdiscovery,
        S9LayoutStateMachine::BootstrapCatalogDiscovery,
        S8HazardProofLane::Runtime,
        S8HazardContainment::Deny,
        S8HazardRecovery::RebindCurrentAuthority,
        S9LayoutMachineTransition::Deny,
    ),
    row(
        S8LayoutHazard::CacheAdmissionBypass,
        S9LayoutStateMachine::ExecutionReadiness,
        S8HazardProofLane::CompileFail,
        S8HazardContainment::Deny,
        S8HazardRecovery::None,
        S9LayoutMachineTransition::Ready,
    ),
    row(
        S8LayoutHazard::LegacyReadyPlan,
        S9LayoutStateMachine::ExecutedEvidence,
        S8HazardProofLane::CompileFail,
        S8HazardContainment::Deny,
        S8HazardRecovery::None,
        S9LayoutMachineTransition::Deny,
    ),
    row(
        S8LayoutHazard::CopiedCounters,
        S9LayoutStateMachine::ExecutedEvidence,
        S8HazardProofLane::CompileFail,
        S8HazardContainment::Deny,
        S8HazardRecovery::None,
        S9LayoutMachineTransition::Deny,
    ),
    row(
        S8LayoutHazard::DegradedExactScanWithoutBudget,
        S9LayoutStateMachine::DegradedExactScan,
        S8HazardProofLane::Runtime,
        S8HazardContainment::Deny,
        S8HazardRecovery::None,
        S9LayoutMachineTransition::Deny,
    ),
];

const fn row(
    hazard: S8LayoutHazard,
    machine: S9LayoutStateMachine,
    proof_lane: S8HazardProofLane,
    containment: S8HazardContainment,
    recovery: S8HazardRecovery,
    transition: S9LayoutMachineTransition,
) -> S8LayoutHazardRow {
    S8LayoutHazardRow::new(
        hazard,
        machine,
        proof_lane,
        containment,
        recovery,
        transition,
    )
}
