mod accessors;
mod admission;
mod classification;
mod compatibility;
mod maintenance;
mod portability;
mod recovery;
mod retention;

#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(default)]
pub struct SubscriptionSupportCounterSnapshot {
    pub(super) declarations_admitted: u64,
    pub(super) declarations_rejected: u64,
    pub(super) artifacts_published: u64,
    pub(super) artifacts_fetched: u64,
    pub(super) family_catalog_lookups: u64,
    pub(super) lookup_keys_used: u64,
    pub(super) rows_read: u64,
    pub(super) duplicate_retries: u64,
    pub(super) identity_collisions: u64,
    pub(super) access_structure_debts: u64,
    pub(super) malformed_support_records: u64,
    pub(super) missing_manifest_rejections: u64,
    pub(super) compatibility_drifts: u64,
    pub(super) exact_classifications: u64,
    pub(super) degraded_classifications: u64,
    pub(super) rebuild_required_classifications: u64,
    pub(super) denied_classifications: u64,
    pub(super) budget_denials: u64,
    pub(super) restart_reconstruction_count: u64,
    pub(super) restart_shards_touched: u64,
    pub(super) restart_global_scan_count: u64,
    pub(super) rebuild_basis_plan_count: u64,
    pub(super) runtime_handoff_count: u64,
    pub(super) operational_verdict_translation_count: u64,
    pub(super) operational_verdict_translation_rejections: u64,
    pub(super) support_action_envelope_publications: u64,
    pub(super) support_action_recovery_count: u64,
    pub(super) support_hidden_exact_loss_count: u64,
    pub(super) support_hot_path_rejections: u64,
    pub(super) support_payload_budget_rejection_count: u64,
    pub(super) support_batch_receipt_reuse_count: u64,
    pub(super) support_store_global_debt_rejections: u64,
    pub(super) support_global_scan_recovery_rejection_count: u64,
    pub(super) support_retention_plan_count: u64,
    pub(super) support_retention_affected_entries: u64,
    pub(super) support_retained_family_count: u64,
    pub(super) support_reclaimed_family_count: u64,
    pub(super) support_compacted_basis_count: u64,
    pub(super) support_expired_family_count: u64,
    pub(super) support_reclaim_consequence_count: u64,
    pub(super) support_policy_expiration_count: u64,
    pub(super) support_compatibility_plan_count: u64,
    pub(super) support_compatibility_affected_entries: u64,
    pub(super) support_manifest_admission_count: u64,
    pub(super) support_compatibility_receipt_binding_count: u64,
    pub(super) support_exact_compatible_migration_count: u64,
    pub(super) support_degraded_compatibility_count: u64,
    pub(super) support_version_skew_rejection_count: u64,
    pub(super) support_portability_plan_count: u64,
    pub(super) support_portability_manifest_entries: u64,
    pub(super) support_portability_required_basis_count: u64,
    pub(super) support_portability_omitted_support_count: u64,
    pub(super) support_replication_inclusion_count: u64,
    pub(super) support_replication_omission_count: u64,
    pub(super) support_import_admission_count: u64,
    pub(super) support_import_rejection_count: u64,
    pub(super) support_capsule_manifest_budget_denial_count: u64,
    pub(super) support_maintenance_descriptor_count: u64,
    pub(super) support_maintenance_delay_count: u64,
    pub(super) support_maintenance_rebuild_debt_count: u64,
    pub(super) support_maintenance_refresh_count: u64,
    pub(super) support_maintenance_compatibility_migration_count: u64,
    pub(super) support_maintenance_degradation_recovery_count: u64,
    pub(super) support_maintenance_coalesced_duplicate_count: u64,
    pub(super) support_maintenance_interrupted_restart_recovery_count: u64,
}
