use super::types::{
    ForgeQueryIntentAdmissionCoverageInventory, ForgeQueryIntentAdmissionCoverageRow,
    ForgeQueryIntentAdmissionCoverageStatus, ForgeQueryIntentAdmissionCoveredEntrypoint,
    ForgeQueryIntentAdmissionDecisionClass, ForgeQueryIntentAdmissionEligibilityAuthority,
    ForgeQueryIntentAdmissionExecutionBoundary, ForgeQueryIntentAdmissionExecutionHandoffInventory,
    ForgeQueryIntentAdmissionPlanKind, ForgeQueryIntentAdmissionResultArtifact,
    ForgeQueryIntentAdmissionSurfaceDescriptor,
};
use crate::intent_admission::ForgeQueryIntentAdmissionFamily;

const INTENT_ADMISSION_ROWS: [ForgeQueryIntentAdmissionCoverageRow; 14] = [
    ForgeQueryIntentAdmissionCoverageRow::new(
        ForgeQueryIntentAdmissionFamily::AuthoritativeUserIntent,
        ForgeQueryIntentAdmissionCoveredEntrypoint::ExecuteIntent,
        ForgeQueryIntentAdmissionExecutionBoundary::covered_backend_intent_authority_route(),
        ForgeQueryIntentAdmissionCoverageStatus::Implemented,
        ForgeQueryIntentAdmissionEligibilityAuthority::RuntimeIntentAuthorityAdapter,
        ForgeQueryIntentAdmissionPlanKind::AuthoritativeIntentExecutionPlan,
        ForgeQueryIntentAdmissionExecutionHandoffInventory::available(
            "ForgeQueryAdmittedIntentExecutionHandoff",
        ),
        ForgeQueryIntentAdmissionDecisionClass::AdvisoryNotYetExercisedOnCoveredEntrypoint,
        ForgeQueryIntentAdmissionDecisionClass::AdmissionOrExecutionViolation,
        ForgeQueryIntentAdmissionResultArtifact::ForgeQueryIntentReceipt,
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            "ForgeQueryRawIntentAdmissionRequest::authoritative_runtime_entrypoint(...)",
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            "runtime.intent(declaration).execute()",
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            "runtime.intent(declaration).review()?.admit()?.execute()",
        ),
    ),
    ForgeQueryIntentAdmissionCoverageRow::new(
        ForgeQueryIntentAdmissionFamily::EffectTriggeredWriteIntent,
        ForgeQueryIntentAdmissionCoveredEntrypoint::ExecuteNextEffectWriteIntent,
        ForgeQueryIntentAdmissionExecutionBoundary::covered_backend_intent_authority_route(),
        ForgeQueryIntentAdmissionCoverageStatus::Implemented,
        ForgeQueryIntentAdmissionEligibilityAuthority::RuntimeIntentAuthorityAdapter,
        ForgeQueryIntentAdmissionPlanKind::EffectTriggeredIntentExecutionPlan,
        ForgeQueryIntentAdmissionExecutionHandoffInventory::available(
            "ForgeQueryAdmittedIntentExecutionHandoff",
        ),
        ForgeQueryIntentAdmissionDecisionClass::AdvisoryNotYetExercisedOnCoveredEntrypoint,
        ForgeQueryIntentAdmissionDecisionClass::AdmissionOrExecutionViolation,
        ForgeQueryIntentAdmissionResultArtifact::ForgeQueryEffectIntentReceipt,
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            "ForgeQueryRawIntentAdmissionRequest::effect_runtime_entrypoint(...)",
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            "runtime.next_effect_write_intent(&effect, version, contract).execute()",
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            "runtime.next_effect_write_intent(&effect, version, contract).review()?.admit()?.execute()",
        ),
    ),
    ForgeQueryIntentAdmissionCoverageRow::new(
        ForgeQueryIntentAdmissionFamily::AuthoritativeMutationIntent,
        ForgeQueryIntentAdmissionCoveredEntrypoint::ExecuteScalarWrite,
        ForgeQueryIntentAdmissionExecutionBoundary::covered_backend_write_authority_route(),
        ForgeQueryIntentAdmissionCoverageStatus::Implemented,
        ForgeQueryIntentAdmissionEligibilityAuthority::RuntimeWriteAuthorityAdapter,
        ForgeQueryIntentAdmissionPlanKind::AuthoritativeMutationExecutionPlan,
        ForgeQueryIntentAdmissionExecutionHandoffInventory::available(
            "ForgeQueryAdmittedIntentExecutionHandoff",
        ),
        ForgeQueryIntentAdmissionDecisionClass::AdvisoryNotYetExercisedOnCoveredEntrypoint,
        ForgeQueryIntentAdmissionDecisionClass::AdmissionOrExecutionViolation,
        ForgeQueryIntentAdmissionResultArtifact::ForgeQueryWriteReceipt,
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            "ForgeQueryRawIntentAdmissionRequest::authoritative_write_entrypoint(...)",
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            "runtime.write_intent(command).execute(); workspace.write_intent(command).execute()",
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            "runtime.write_intent(command).review()?.admit()?.execute(); workspace.write_intent(command).review()?.admit()?.execute()",
        ),
    ),
    ForgeQueryIntentAdmissionCoverageRow::new(
        ForgeQueryIntentAdmissionFamily::AuthoritativeMutationIntent,
        ForgeQueryIntentAdmissionCoveredEntrypoint::ExecuteBatchWrite,
        ForgeQueryIntentAdmissionExecutionBoundary::covered_backend_write_authority_route(),
        ForgeQueryIntentAdmissionCoverageStatus::Implemented,
        ForgeQueryIntentAdmissionEligibilityAuthority::RuntimeWriteAuthorityAdapter,
        ForgeQueryIntentAdmissionPlanKind::AuthoritativeMutationBatchExecutionPlan,
        ForgeQueryIntentAdmissionExecutionHandoffInventory::available(
            "ForgeQueryAdmittedIntentExecutionHandoff",
        ),
        ForgeQueryIntentAdmissionDecisionClass::AdvisoryNotYetExercisedOnCoveredEntrypoint,
        ForgeQueryIntentAdmissionDecisionClass::AdmissionOrExecutionViolation,
        ForgeQueryIntentAdmissionResultArtifact::ForgeQueryBatchWriteReceipt,
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            "ForgeQueryRawIntentAdmissionRequest::authoritative_write_batch_entrypoint(...)",
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            "runtime.write_batch_intent(commands).execute(); workspace.write_batch_intent(commands).execute()",
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            "runtime.write_batch_intent(commands).review()?.admit()?.execute(); workspace.write_batch_intent(commands).review()?.admit()?.execute()",
        ),
    ),
    ForgeQueryIntentAdmissionCoverageRow::new(
        ForgeQueryIntentAdmissionFamily::BasisUseIntent,
        ForgeQueryIntentAdmissionCoveredEntrypoint::BasisObservation,
        ForgeQueryIntentAdmissionExecutionBoundary::deferred_neighbor(
            "no-execution-handoff-basis-observation-scope",
        ),
        ForgeQueryIntentAdmissionCoverageStatus::Implemented,
        ForgeQueryIntentAdmissionEligibilityAuthority::BasisLifecycleObservationAuthority,
        ForgeQueryIntentAdmissionPlanKind::BasisObservationPlan,
        ForgeQueryIntentAdmissionExecutionHandoffInventory::no_execution_handoff(
            "basis-observation-admitted-plan-scopes-to-lower-runtime-evidence-without-query-execution-handoff",
        ),
        ForgeQueryIntentAdmissionDecisionClass::AdvisoryNotYetExercisedOnCoveredEntrypoint,
        ForgeQueryIntentAdmissionDecisionClass::AdmissionOrExecutionViolation,
        ForgeQueryIntentAdmissionResultArtifact::ScopedObservationBasis,
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            "ForgeQueryRawIntentAdmissionRequest::basis_observation_lane(...)",
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            "forge_query_basis_observation_intent(raw).admit()",
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            "forge_query_basis_observation_intent(raw).review()?.admit()",
        ),
    ),
    ForgeQueryIntentAdmissionCoverageRow::new(
        ForgeQueryIntentAdmissionFamily::ProjectionConsumptionIntent,
        ForgeQueryIntentAdmissionCoveredEntrypoint::ProjectionConsumption,
        ForgeQueryIntentAdmissionExecutionBoundary::deferred_neighbor(
            "no-execution-handoff-projection-consumption-contract",
        ),
        ForgeQueryIntentAdmissionCoverageStatus::Implemented,
        ForgeQueryIntentAdmissionEligibilityAuthority::ProjectionConsumptionEligibilityAuthority,
        ForgeQueryIntentAdmissionPlanKind::ProjectionConsumptionPlan,
        ForgeQueryIntentAdmissionExecutionHandoffInventory::no_execution_handoff(
            "projection-consumption-admitted-plan-binds-contract-without-query-execution-handoff",
        ),
        ForgeQueryIntentAdmissionDecisionClass::ProjectionWarningBearingAdmission,
        ForgeQueryIntentAdmissionDecisionClass::AdmissionOrExecutionViolation,
        ForgeQueryIntentAdmissionResultArtifact::MaterializedProjectionContract,
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            "ForgeQueryRawIntentAdmissionRequest::projection_consumption(declaration)",
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            "forge_query_projection_consumption_intent(declaration).admit()",
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            "forge_query_projection_consumption_intent(declaration).review()?.admit()",
        ),
    ),
    ForgeQueryIntentAdmissionCoverageRow::new(
        ForgeQueryIntentAdmissionFamily::ReadExecutionIntent,
        ForgeQueryIntentAdmissionCoveredEntrypoint::ExecuteReadFamily,
        ForgeQueryIntentAdmissionExecutionBoundary::covered_query_runtime_read_execution_route(),
        ForgeQueryIntentAdmissionCoverageStatus::Implemented,
        ForgeQueryIntentAdmissionEligibilityAuthority::ReadCompositionExecutionAuthority,
        ForgeQueryIntentAdmissionPlanKind::ReadExecutionPlan,
        ForgeQueryIntentAdmissionExecutionHandoffInventory::available(
            "ForgeQueryReadExecutionHandoff",
        ),
        ForgeQueryIntentAdmissionDecisionClass::AdvisoryNotYetExercisedOnCoveredEntrypoint,
        ForgeQueryIntentAdmissionDecisionClass::AdmissionOrExecutionViolation,
        ForgeQueryIntentAdmissionResultArtifact::ForgeQueryReadResult,
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            "ForgeQueryRawIntentAdmissionRequest::read_family_entrypoint(...)",
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            "workspace.read_family_intent(&family).execute()",
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            "workspace.read_family_intent(&family).review()?.admit()?.execute()",
        ),
    ),
    ForgeQueryIntentAdmissionCoverageRow::new(
        ForgeQueryIntentAdmissionFamily::ReadExecutionIntent,
        ForgeQueryIntentAdmissionCoveredEntrypoint::ExecuteReadFamilyInBasisContext,
        ForgeQueryIntentAdmissionExecutionBoundary::covered_query_runtime_read_execution_route(),
        ForgeQueryIntentAdmissionCoverageStatus::Implemented,
        ForgeQueryIntentAdmissionEligibilityAuthority::ReadCompositionExecutionAuthority,
        ForgeQueryIntentAdmissionPlanKind::ReadExecutionPlan,
        ForgeQueryIntentAdmissionExecutionHandoffInventory::available(
            "ForgeQueryReadExecutionHandoff",
        ),
        ForgeQueryIntentAdmissionDecisionClass::AdvisoryNotYetExercisedOnCoveredEntrypoint,
        ForgeQueryIntentAdmissionDecisionClass::AdmissionOrExecutionViolation,
        ForgeQueryIntentAdmissionResultArtifact::ForgeQueryReadResult,
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            "ForgeQueryRawIntentAdmissionRequest::read_family_in_basis_context_entrypoint(...)",
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            "workspace.read_family_in_basis_context_intent(&family, &context).execute()",
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            "workspace.read_family_in_basis_context_intent(&family, &context).review()?.admit()?.execute()",
        ),
    ),
    ForgeQueryIntentAdmissionCoverageRow::new(
        ForgeQueryIntentAdmissionFamily::ReadExecutionIntent,
        ForgeQueryIntentAdmissionCoveredEntrypoint::ExecuteLiveRead,
        ForgeQueryIntentAdmissionExecutionBoundary::covered_query_runtime_read_execution_route(),
        ForgeQueryIntentAdmissionCoverageStatus::Implemented,
        ForgeQueryIntentAdmissionEligibilityAuthority::ReadCompositionExecutionAuthority,
        ForgeQueryIntentAdmissionPlanKind::ReadExecutionPlan,
        ForgeQueryIntentAdmissionExecutionHandoffInventory::available(
            "ForgeQueryLiveReadExecutionHandoff",
        ),
        ForgeQueryIntentAdmissionDecisionClass::AdvisoryNotYetExercisedOnCoveredEntrypoint,
        ForgeQueryIntentAdmissionDecisionClass::AdmissionOrExecutionViolation,
        ForgeQueryIntentAdmissionResultArtifact::ForgeQueryLiveReadResult,
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            "ForgeQueryRawIntentAdmissionRequest::live_read_entrypoint(...)",
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            "workspace.read_live_intent(&view).execute()",
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            "workspace.read_live_intent(&view).review()?.admit()?.execute()",
        ),
    ),
    ForgeQueryIntentAdmissionCoverageRow::new(
        ForgeQueryIntentAdmissionFamily::InspectionMaterializationIntent,
        ForgeQueryIntentAdmissionCoveredEntrypoint::ExecuteUnifiedInspection,
        ForgeQueryIntentAdmissionExecutionBoundary::covered_query_runtime_inspection_materialization_route(),
        ForgeQueryIntentAdmissionCoverageStatus::Implemented,
        ForgeQueryIntentAdmissionEligibilityAuthority::InspectionMaterializationExecutionAuthority,
        ForgeQueryIntentAdmissionPlanKind::UnifiedInspectionExecutionPlan,
        ForgeQueryIntentAdmissionExecutionHandoffInventory::available(
            "ForgeQueryUnifiedInspectionExecutionHandoff",
        ),
        ForgeQueryIntentAdmissionDecisionClass::InspectionDetailRedactionAdvisory,
        ForgeQueryIntentAdmissionDecisionClass::AdmissionOrExecutionViolation,
        ForgeQueryIntentAdmissionResultArtifact::ForgeQueryUnifiedInspectionResult,
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            "ForgeQueryRawIntentAdmissionRequest::generic_inspection_entrypoint(...)",
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            "workspace.inspect_intent(target).execute()",
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            "workspace.inspect_intent(target).review()?.admit()?.execute()",
        ),
    ),
    ForgeQueryIntentAdmissionCoverageRow::new(
        ForgeQueryIntentAdmissionFamily::InspectionMaterializationIntent,
        ForgeQueryIntentAdmissionCoveredEntrypoint::ExecuteDerivedMaterialization,
        ForgeQueryIntentAdmissionExecutionBoundary::covered_query_runtime_inspection_materialization_route(),
        ForgeQueryIntentAdmissionCoverageStatus::Implemented,
        ForgeQueryIntentAdmissionEligibilityAuthority::InspectionMaterializationExecutionAuthority,
        ForgeQueryIntentAdmissionPlanKind::InspectionMaterializationExecutionPlan,
        ForgeQueryIntentAdmissionExecutionHandoffInventory::available(
            "ForgeQueryDerivedMaterializationExecutionHandoff",
        ),
        ForgeQueryIntentAdmissionDecisionClass::AdvisoryNotYetExercisedOnCoveredEntrypoint,
        ForgeQueryIntentAdmissionDecisionClass::AdmissionOrExecutionViolation,
        ForgeQueryIntentAdmissionResultArtifact::ForgeQueryDerivedMaterializationResult,
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            "ForgeQueryRawIntentAdmissionRequest::derived_materialization_entrypoint(...)",
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            "workspace.materialize_intent(&view).execute()",
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            "workspace.materialize_intent(&view).review()?.admit()?.execute()",
        ),
    ),
    ForgeQueryIntentAdmissionCoverageRow::new(
        ForgeQueryIntentAdmissionFamily::InspectionMaterializationIntent,
        ForgeQueryIntentAdmissionCoveredEntrypoint::ExecuteDerivedInspection,
        ForgeQueryIntentAdmissionExecutionBoundary::covered_query_runtime_inspection_materialization_route(),
        ForgeQueryIntentAdmissionCoverageStatus::Implemented,
        ForgeQueryIntentAdmissionEligibilityAuthority::InspectionMaterializationExecutionAuthority,
        ForgeQueryIntentAdmissionPlanKind::InspectionMaterializationExecutionPlan,
        ForgeQueryIntentAdmissionExecutionHandoffInventory::available(
            "ForgeQueryDerivedInspectionExecutionHandoff",
        ),
        ForgeQueryIntentAdmissionDecisionClass::AdvisoryNotYetExercisedOnCoveredEntrypoint,
        ForgeQueryIntentAdmissionDecisionClass::AdmissionOrExecutionViolation,
        ForgeQueryIntentAdmissionResultArtifact::ForgeQueryDerivedInspectionResult,
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            "ForgeQueryRawIntentAdmissionRequest::derived_inspection_entrypoint(...)",
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            "workspace.inspect_derived_intent(&view).execute()",
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            "workspace.inspect_derived_intent(&view).review()?.admit()?.execute()",
        ),
    ),
    ForgeQueryIntentAdmissionCoverageRow::new(
        ForgeQueryIntentAdmissionFamily::InspectionMaterializationIntent,
        ForgeQueryIntentAdmissionCoveredEntrypoint::ExecuteInspectionNeighborDeferred,
        ForgeQueryIntentAdmissionExecutionBoundary::deferred_neighbor(
            "inspection-materialization-neighbor-deferred-until-covered",
        ),
        ForgeQueryIntentAdmissionCoverageStatus::PlannedNeighbor,
        ForgeQueryIntentAdmissionEligibilityAuthority::DeferredInspectionMaterializationAuthority,
        ForgeQueryIntentAdmissionPlanKind::DeferredInspectionMaterializationPlan,
        ForgeQueryIntentAdmissionExecutionHandoffInventory::no_execution_handoff(
            "inspection-materialization-neighbor-deferred-until-covered",
        ),
        ForgeQueryIntentAdmissionDecisionClass::DeferredNeighborSupport,
        ForgeQueryIntentAdmissionDecisionClass::NeighborUnsupportedUntilCoverage,
        ForgeQueryIntentAdmissionResultArtifact::DeferredInspectionMaterializationArtifact,
        ForgeQueryIntentAdmissionSurfaceDescriptor::deferred(
            "inspection-materialization-neighbor-deferred-until-covered",
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::deferred(
            "inspection-materialization-neighbor-deferred-until-covered",
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::deferred(
            "inspection-materialization-neighbor-deferred-until-covered",
        ),
    ),
    ForgeQueryIntentAdmissionCoverageRow::new(
        ForgeQueryIntentAdmissionFamily::LowerRuntimeCapabilityRoutingIntent,
        ForgeQueryIntentAdmissionCoveredEntrypoint::ExecuteExistingTruthProbeRouting,
        ForgeQueryIntentAdmissionExecutionBoundary::covered_backend_existing_truth_probe_route(),
        ForgeQueryIntentAdmissionCoverageStatus::Implemented,
        ForgeQueryIntentAdmissionEligibilityAuthority::LowerRuntimeCapabilityRoutingAuthority,
        ForgeQueryIntentAdmissionPlanKind::ExistingTruthProbeRoutingPlan,
        ForgeQueryIntentAdmissionExecutionHandoffInventory::available(
            "ForgeQueryExistingTruthProbeExecutionHandoff",
        ),
        ForgeQueryIntentAdmissionDecisionClass::AdvisoryNotYetExercisedOnCoveredEntrypoint,
        ForgeQueryIntentAdmissionDecisionClass::AdmissionOrExecutionViolation,
        ForgeQueryIntentAdmissionResultArtifact::ForgeQueryExistingTruthProbeResult,
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            "ForgeQueryRawIntentAdmissionRequest::existing_truth_probe_entrypoint(...)",
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            "runtime.probe_existing_intent(request).execute(); workspace.probe_existing_intent(request).execute()",
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            "runtime.probe_existing_intent(request).review()?.admit()?.execute(); workspace.probe_existing_intent(request).review()?.admit()?.execute()",
        ),
    ),
];

pub fn forge_query_intent_admission_coverage_inventory(
) -> ForgeQueryIntentAdmissionCoverageInventory {
    ForgeQueryIntentAdmissionCoverageInventory::new(&INTENT_ADMISSION_ROWS)
}
