use super::types::{
    ForgeQueryIntentAdmissionCoverageInventory, ForgeQueryIntentAdmissionCoverageRow,
    ForgeQueryIntentAdmissionCoverageStatus, ForgeQueryIntentAdmissionCoveredEntrypoint,
    ForgeQueryIntentAdmissionDecisionClass, ForgeQueryIntentAdmissionEligibilityAuthority,
    ForgeQueryIntentAdmissionExecutionBoundary, ForgeQueryIntentAdmissionExecutionHandoffInventory,
    ForgeQueryIntentAdmissionPlanKind, ForgeQueryIntentAdmissionResultArtifact,
    ForgeQueryIntentAdmissionSurfaceDescriptor,
};
use crate::intent_admission::surface_catalog::*;
use crate::intent_admission::ForgeQueryIntentAdmissionFamily;

const INTENT_ADMISSION_ROWS: [ForgeQueryIntentAdmissionCoverageRow; 14] = [
    ForgeQueryIntentAdmissionCoverageRow::new(
        ForgeQueryIntentAdmissionFamily::AuthoritativeUserIntent,
        ForgeQueryIntentAdmissionCoveredEntrypoint::ExecuteIntent,
        ForgeQueryIntentAdmissionExecutionBoundary::covered_backend_intent_authority_route(),
        ForgeQueryIntentAdmissionCoverageStatus::Implemented,
        ForgeQueryIntentAdmissionEligibilityAuthority::RuntimeIntentAuthorityAdapter,
        ForgeQueryIntentAdmissionPlanKind::AuthoritativeIntentExecutionPlan,
        ForgeQueryIntentAdmissionExecutionHandoffInventory::available(
            "ForgeQueryAdmittedIntentExecutionHandoff",
        ),
        ForgeQueryIntentAdmissionDecisionClass::AdvisoryNotYetExercisedOnCoveredEntrypoint,
        ForgeQueryIntentAdmissionDecisionClass::AdmissionOrExecutionViolation,
        ForgeQueryIntentAdmissionResultArtifact::ForgeQueryIntentReceipt,
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            AUTHORITATIVE_RUNTIME_RAW_ENTRYPOINT,
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            AUTHORITATIVE_RUNTIME_COMMON_PATH,
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            AUTHORITATIVE_RUNTIME_ADVANCED_PATH,
        ),
    ),
    ForgeQueryIntentAdmissionCoverageRow::new(
        ForgeQueryIntentAdmissionFamily::EffectTriggeredWriteIntent,
        ForgeQueryIntentAdmissionCoveredEntrypoint::ExecuteNextEffectWriteIntent,
        ForgeQueryIntentAdmissionExecutionBoundary::covered_backend_intent_authority_route(),
        ForgeQueryIntentAdmissionCoverageStatus::Implemented,
        ForgeQueryIntentAdmissionEligibilityAuthority::RuntimeIntentAuthorityAdapter,
        ForgeQueryIntentAdmissionPlanKind::EffectTriggeredIntentExecutionPlan,
        ForgeQueryIntentAdmissionExecutionHandoffInventory::available(
            "ForgeQueryAdmittedIntentExecutionHandoff",
        ),
        ForgeQueryIntentAdmissionDecisionClass::AdvisoryNotYetExercisedOnCoveredEntrypoint,
        ForgeQueryIntentAdmissionDecisionClass::AdmissionOrExecutionViolation,
        ForgeQueryIntentAdmissionResultArtifact::ForgeQueryEffectIntentReceipt,
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            EFFECT_RUNTIME_RAW_ENTRYPOINT,
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            EFFECT_RUNTIME_COMMON_PATH,
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            EFFECT_RUNTIME_ADVANCED_PATH,
        ),
    ),
    ForgeQueryIntentAdmissionCoverageRow::new(
        ForgeQueryIntentAdmissionFamily::AuthoritativeMutationIntent,
        ForgeQueryIntentAdmissionCoveredEntrypoint::ExecuteScalarWrite,
        ForgeQueryIntentAdmissionExecutionBoundary::covered_backend_write_authority_route(),
        ForgeQueryIntentAdmissionCoverageStatus::Implemented,
        ForgeQueryIntentAdmissionEligibilityAuthority::RuntimeWriteAuthorityAdapter,
        ForgeQueryIntentAdmissionPlanKind::AuthoritativeMutationExecutionPlan,
        ForgeQueryIntentAdmissionExecutionHandoffInventory::available(
            "ForgeQueryAdmittedIntentExecutionHandoff",
        ),
        ForgeQueryIntentAdmissionDecisionClass::AdvisoryNotYetExercisedOnCoveredEntrypoint,
        ForgeQueryIntentAdmissionDecisionClass::AdmissionOrExecutionViolation,
        ForgeQueryIntentAdmissionResultArtifact::ForgeQueryWriteReceipt,
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            AUTHORITATIVE_MUTATION_RAW_ENTRYPOINT,
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            AUTHORITATIVE_MUTATION_COMMON_PATHS,
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            AUTHORITATIVE_MUTATION_ADVANCED_PATHS,
        ),
    ),
    ForgeQueryIntentAdmissionCoverageRow::new(
        ForgeQueryIntentAdmissionFamily::AuthoritativeMutationIntent,
        ForgeQueryIntentAdmissionCoveredEntrypoint::ExecuteBatchWrite,
        ForgeQueryIntentAdmissionExecutionBoundary::covered_backend_write_authority_route(),
        ForgeQueryIntentAdmissionCoverageStatus::Implemented,
        ForgeQueryIntentAdmissionEligibilityAuthority::RuntimeWriteAuthorityAdapter,
        ForgeQueryIntentAdmissionPlanKind::AuthoritativeMutationBatchExecutionPlan,
        ForgeQueryIntentAdmissionExecutionHandoffInventory::available(
            "ForgeQueryAdmittedIntentExecutionHandoff",
        ),
        ForgeQueryIntentAdmissionDecisionClass::AdvisoryNotYetExercisedOnCoveredEntrypoint,
        ForgeQueryIntentAdmissionDecisionClass::AdmissionOrExecutionViolation,
        ForgeQueryIntentAdmissionResultArtifact::ForgeQueryBatchWriteReceipt,
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            AUTHORITATIVE_MUTATION_BATCH_RAW_ENTRYPOINT,
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            AUTHORITATIVE_MUTATION_BATCH_COMMON_PATHS,
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            AUTHORITATIVE_MUTATION_BATCH_ADVANCED_PATHS,
        ),
    ),
    ForgeQueryIntentAdmissionCoverageRow::new(
        ForgeQueryIntentAdmissionFamily::BasisUseIntent,
        ForgeQueryIntentAdmissionCoveredEntrypoint::BasisObservation,
        ForgeQueryIntentAdmissionExecutionBoundary::deferred_neighbor(
            "no-execution-handoff-basis-observation-scope",
        ),
        ForgeQueryIntentAdmissionCoverageStatus::Implemented,
        ForgeQueryIntentAdmissionEligibilityAuthority::BasisLifecycleObservationAuthority,
        ForgeQueryIntentAdmissionPlanKind::BasisObservationPlan,
        ForgeQueryIntentAdmissionExecutionHandoffInventory::no_execution_handoff(
            "basis-observation-admitted-plan-scopes-to-lower-runtime-evidence-without-query-execution-handoff",
        ),
        ForgeQueryIntentAdmissionDecisionClass::AdvisoryNotYetExercisedOnCoveredEntrypoint,
        ForgeQueryIntentAdmissionDecisionClass::AdmissionOrExecutionViolation,
        ForgeQueryIntentAdmissionResultArtifact::ScopedObservationBasis,
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            BASIS_OBSERVATION_RAW_ENTRYPOINT,
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            BASIS_OBSERVATION_COMMON_PATH,
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            BASIS_OBSERVATION_ADVANCED_PATH,
        ),
    ),
    ForgeQueryIntentAdmissionCoverageRow::new(
        ForgeQueryIntentAdmissionFamily::ProjectionConsumptionIntent,
        ForgeQueryIntentAdmissionCoveredEntrypoint::ProjectionConsumption,
        ForgeQueryIntentAdmissionExecutionBoundary::deferred_neighbor(
            "no-execution-handoff-projection-consumption-contract",
        ),
        ForgeQueryIntentAdmissionCoverageStatus::Implemented,
        ForgeQueryIntentAdmissionEligibilityAuthority::ProjectionConsumptionEligibilityAuthority,
        ForgeQueryIntentAdmissionPlanKind::ProjectionConsumptionPlan,
        ForgeQueryIntentAdmissionExecutionHandoffInventory::no_execution_handoff(
            "projection-consumption-admitted-plan-binds-contract-without-query-execution-handoff",
        ),
        ForgeQueryIntentAdmissionDecisionClass::ProjectionWarningBearingAdmission,
        ForgeQueryIntentAdmissionDecisionClass::AdmissionOrExecutionViolation,
        ForgeQueryIntentAdmissionResultArtifact::MaterializedProjectionContract,
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            PROJECTION_CONSUMPTION_RAW_ENTRYPOINT,
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            PROJECTION_CONSUMPTION_COMMON_PATH,
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            PROJECTION_CONSUMPTION_ADVANCED_PATH,
        ),
    ),
    ForgeQueryIntentAdmissionCoverageRow::new(
        ForgeQueryIntentAdmissionFamily::ReadExecutionIntent,
        ForgeQueryIntentAdmissionCoveredEntrypoint::ExecuteReadFamily,
        ForgeQueryIntentAdmissionExecutionBoundary::covered_query_runtime_read_execution_route(),
        ForgeQueryIntentAdmissionCoverageStatus::Implemented,
        ForgeQueryIntentAdmissionEligibilityAuthority::ReadCompositionExecutionAuthority,
        ForgeQueryIntentAdmissionPlanKind::ReadExecutionPlan,
        ForgeQueryIntentAdmissionExecutionHandoffInventory::available(
            "ForgeQueryReadExecutionHandoff",
        ),
        ForgeQueryIntentAdmissionDecisionClass::AdvisoryNotYetExercisedOnCoveredEntrypoint,
        ForgeQueryIntentAdmissionDecisionClass::AdmissionOrExecutionViolation,
        ForgeQueryIntentAdmissionResultArtifact::ForgeQueryReadResult,
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            READ_EXECUTION_RAW_ENTRYPOINT,
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            READ_EXECUTION_COMMON_PATHS,
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            READ_EXECUTION_ADVANCED_PATH,
        ),
    ),
    ForgeQueryIntentAdmissionCoverageRow::new(
        ForgeQueryIntentAdmissionFamily::ReadExecutionIntent,
        ForgeQueryIntentAdmissionCoveredEntrypoint::ExecuteReadFamilyInBasisContext,
        ForgeQueryIntentAdmissionExecutionBoundary::covered_query_runtime_read_execution_route(),
        ForgeQueryIntentAdmissionCoverageStatus::Implemented,
        ForgeQueryIntentAdmissionEligibilityAuthority::ReadCompositionExecutionAuthority,
        ForgeQueryIntentAdmissionPlanKind::ReadExecutionPlan,
        ForgeQueryIntentAdmissionExecutionHandoffInventory::available(
            "ForgeQueryReadExecutionHandoff",
        ),
        ForgeQueryIntentAdmissionDecisionClass::AdvisoryNotYetExercisedOnCoveredEntrypoint,
        ForgeQueryIntentAdmissionDecisionClass::AdmissionOrExecutionViolation,
        ForgeQueryIntentAdmissionResultArtifact::ForgeQueryReadResult,
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            READ_EXECUTION_BASIS_RAW_ENTRYPOINT,
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            READ_EXECUTION_BASIS_COMMON_PATHS,
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            READ_EXECUTION_BASIS_ADVANCED_PATH,
        ),
    ),
    ForgeQueryIntentAdmissionCoverageRow::new(
        ForgeQueryIntentAdmissionFamily::ReadExecutionIntent,
        ForgeQueryIntentAdmissionCoveredEntrypoint::ExecuteLiveRead,
        ForgeQueryIntentAdmissionExecutionBoundary::covered_query_runtime_read_execution_route(),
        ForgeQueryIntentAdmissionCoverageStatus::Implemented,
        ForgeQueryIntentAdmissionEligibilityAuthority::ReadCompositionExecutionAuthority,
        ForgeQueryIntentAdmissionPlanKind::ReadExecutionPlan,
        ForgeQueryIntentAdmissionExecutionHandoffInventory::available(
            "ForgeQueryLiveReadExecutionHandoff",
        ),
        ForgeQueryIntentAdmissionDecisionClass::AdvisoryNotYetExercisedOnCoveredEntrypoint,
        ForgeQueryIntentAdmissionDecisionClass::AdmissionOrExecutionViolation,
        ForgeQueryIntentAdmissionResultArtifact::ForgeQueryLiveReadResult,
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            LIVE_READ_RAW_ENTRYPOINT,
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            LIVE_READ_COMMON_PATHS,
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            LIVE_READ_ADVANCED_PATH,
        ),
    ),
    ForgeQueryIntentAdmissionCoverageRow::new(
        ForgeQueryIntentAdmissionFamily::InspectionMaterializationIntent,
        ForgeQueryIntentAdmissionCoveredEntrypoint::ExecuteUnifiedInspection,
        ForgeQueryIntentAdmissionExecutionBoundary::covered_query_runtime_inspection_materialization_route(),
        ForgeQueryIntentAdmissionCoverageStatus::Implemented,
        ForgeQueryIntentAdmissionEligibilityAuthority::InspectionMaterializationExecutionAuthority,
        ForgeQueryIntentAdmissionPlanKind::UnifiedInspectionExecutionPlan,
        ForgeQueryIntentAdmissionExecutionHandoffInventory::available(
            "ForgeQueryUnifiedInspectionExecutionHandoff",
        ),
        ForgeQueryIntentAdmissionDecisionClass::InspectionDetailRedactionAdvisory,
        ForgeQueryIntentAdmissionDecisionClass::AdmissionOrExecutionViolation,
        ForgeQueryIntentAdmissionResultArtifact::ForgeQueryUnifiedInspectionResult,
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            UNIFIED_INSPECTION_RAW_ENTRYPOINT,
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            UNIFIED_INSPECTION_COMMON_PATHS,
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            UNIFIED_INSPECTION_ADVANCED_PATH,
        ),
    ),
    ForgeQueryIntentAdmissionCoverageRow::new(
        ForgeQueryIntentAdmissionFamily::InspectionMaterializationIntent,
        ForgeQueryIntentAdmissionCoveredEntrypoint::ExecuteDerivedMaterialization,
        ForgeQueryIntentAdmissionExecutionBoundary::covered_query_runtime_inspection_materialization_route(),
        ForgeQueryIntentAdmissionCoverageStatus::Implemented,
        ForgeQueryIntentAdmissionEligibilityAuthority::InspectionMaterializationExecutionAuthority,
        ForgeQueryIntentAdmissionPlanKind::InspectionMaterializationExecutionPlan,
        ForgeQueryIntentAdmissionExecutionHandoffInventory::available(
            "ForgeQueryDerivedMaterializationExecutionHandoff",
        ),
        ForgeQueryIntentAdmissionDecisionClass::AdvisoryNotYetExercisedOnCoveredEntrypoint,
        ForgeQueryIntentAdmissionDecisionClass::AdmissionOrExecutionViolation,
        ForgeQueryIntentAdmissionResultArtifact::ForgeQueryDerivedMaterializationResult,
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            DERIVED_MATERIALIZATION_RAW_ENTRYPOINT,
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            DERIVED_MATERIALIZATION_COMMON_PATHS,
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            DERIVED_MATERIALIZATION_ADVANCED_PATH,
        ),
    ),
    ForgeQueryIntentAdmissionCoverageRow::new(
        ForgeQueryIntentAdmissionFamily::InspectionMaterializationIntent,
        ForgeQueryIntentAdmissionCoveredEntrypoint::ExecuteDerivedInspection,
        ForgeQueryIntentAdmissionExecutionBoundary::covered_query_runtime_inspection_materialization_route(),
        ForgeQueryIntentAdmissionCoverageStatus::Implemented,
        ForgeQueryIntentAdmissionEligibilityAuthority::InspectionMaterializationExecutionAuthority,
        ForgeQueryIntentAdmissionPlanKind::InspectionMaterializationExecutionPlan,
        ForgeQueryIntentAdmissionExecutionHandoffInventory::available(
            "ForgeQueryDerivedInspectionExecutionHandoff",
        ),
        ForgeQueryIntentAdmissionDecisionClass::AdvisoryNotYetExercisedOnCoveredEntrypoint,
        ForgeQueryIntentAdmissionDecisionClass::AdmissionOrExecutionViolation,
        ForgeQueryIntentAdmissionResultArtifact::ForgeQueryDerivedInspectionResult,
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            DERIVED_INSPECTION_RAW_ENTRYPOINT,
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            DERIVED_INSPECTION_COMMON_PATHS,
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            DERIVED_INSPECTION_ADVANCED_PATH,
        ),
    ),
    ForgeQueryIntentAdmissionCoverageRow::new(
        ForgeQueryIntentAdmissionFamily::InspectionMaterializationIntent,
        ForgeQueryIntentAdmissionCoveredEntrypoint::ExecuteInspectionNeighborDeferred,
        ForgeQueryIntentAdmissionExecutionBoundary::deferred_neighbor(
            "inspection-materialization-neighbor-deferred-until-covered",
        ),
        ForgeQueryIntentAdmissionCoverageStatus::PlannedNeighbor,
        ForgeQueryIntentAdmissionEligibilityAuthority::DeferredInspectionMaterializationAuthority,
        ForgeQueryIntentAdmissionPlanKind::DeferredInspectionMaterializationPlan,
        ForgeQueryIntentAdmissionExecutionHandoffInventory::no_execution_handoff(
            "inspection-materialization-neighbor-deferred-until-covered",
        ),
        ForgeQueryIntentAdmissionDecisionClass::DeferredNeighborSupport,
        ForgeQueryIntentAdmissionDecisionClass::NeighborUnsupportedUntilCoverage,
        ForgeQueryIntentAdmissionResultArtifact::DeferredInspectionMaterializationArtifact,
        ForgeQueryIntentAdmissionSurfaceDescriptor::deferred(
            "inspection-materialization-neighbor-deferred-until-covered",
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::deferred(
            "inspection-materialization-neighbor-deferred-until-covered",
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::deferred(
            "inspection-materialization-neighbor-deferred-until-covered",
        ),
    ),
    ForgeQueryIntentAdmissionCoverageRow::new(
        ForgeQueryIntentAdmissionFamily::LowerRuntimeCapabilityRoutingIntent,
        ForgeQueryIntentAdmissionCoveredEntrypoint::ExecuteExistingTruthProbeRouting,
        ForgeQueryIntentAdmissionExecutionBoundary::covered_backend_existing_truth_probe_route(),
        ForgeQueryIntentAdmissionCoverageStatus::Implemented,
        ForgeQueryIntentAdmissionEligibilityAuthority::LowerRuntimeCapabilityRoutingAuthority,
        ForgeQueryIntentAdmissionPlanKind::ExistingTruthProbeRoutingPlan,
        ForgeQueryIntentAdmissionExecutionHandoffInventory::available(
            "ForgeQueryExistingTruthProbeExecutionHandoff",
        ),
        ForgeQueryIntentAdmissionDecisionClass::AdvisoryNotYetExercisedOnCoveredEntrypoint,
        ForgeQueryIntentAdmissionDecisionClass::AdmissionOrExecutionViolation,
        ForgeQueryIntentAdmissionResultArtifact::ForgeQueryExistingTruthProbeResult,
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            EXISTING_TRUTH_PROBE_RAW_ENTRYPOINT,
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            EXISTING_TRUTH_PROBE_FAMILY_COMMON_PATHS,
        ),
        ForgeQueryIntentAdmissionSurfaceDescriptor::available(
            EXISTING_TRUTH_PROBE_ADVANCED_PATHS,
        ),
    ),
];

pub fn forge_query_intent_admission_coverage_inventory(
) -> ForgeQueryIntentAdmissionCoverageInventory {
    ForgeQueryIntentAdmissionCoverageInventory::new(&INTENT_ADMISSION_ROWS)
}
