#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct WorthQueryProjectionPromotionCounters {
    pub retained_authority_checks: usize,
    pub basis_checks: usize,
    pub support_checks: usize,
    pub installed_read_checks: usize,
    pub conditional_lowerings_checked: usize,
    pub lifecycle_attempts: usize,
    pub fresh_conditional_decisions: usize,
    pub conditional_dependency_checks: usize,
    pub conditional_semantic_reads: usize,
    pub conditional_condition_checks: usize,
    pub conditional_condition_deferrals: usize,
    pub conditional_temporal_deferrals: usize,
    pub conditional_on_demand_deferrals: usize,
    pub conditional_comparator_checks: usize,
    pub conditional_compute_contacts: usize,
    pub conditional_reverted_clean_outcomes: usize,
    pub conditional_semantic_changes: usize,
    pub conditional_reuse_checks: usize,
    pub conditional_decisions_delivered: usize,
    pub context_admission_attempts: usize,
    pub planning_attempts: usize,
    pub planning_completions: usize,
    pub lower_runtime_contacts: usize,
    pub managed_resource_registrations: usize,
    pub maintenance_calls: usize,
    pub delivery_calls: usize,
}
