//! Public Hadwiger research facade.
//!
//! Ordinary callers enter through this module for Query declaration entry,
//! canonical artifacts, and aspect authority surfaces.

pub use crate::agent_advisory::{
    admit_agent_exploration_batch_checked, materialize_agent_declaration_advisory_checked,
    materialize_agent_grouped_advisory_checked, screen_agent_experiment_proposals_checked,
    AgentAdmissionAdvisory, AgentAdvisoryArtifact, AgentAdvisoryContributionRecord,
    AgentAdvisoryError, AgentAdvisoryKind, AgentExperimentProposal,
    AgentExperimentProposalScreening, AgentExplorationAdmissionChecked, AgentExplorationBatch,
    AgentExplorationBatchBuilder, AgentGroupedContributionStopKind,
    AgentInvariantHypothesisSuggestion, AgentMotifSuggestion, AgentPromotionPathDescriptor,
    AgentRepairSuggestion, AgentSourceRecord,
};
pub use crate::aspect_authority::{
    query_aspect_contract_for_hadwiger_kind, query_aspect_coverage_for_hadwiger_posture,
    query_aspect_publication_for_hadwiger_kind, AdvisoryAspectRecord, AspectClosureStop,
    AspectDependencyGraph, AspectDependencyGraphBuilder, ColorabilityAspectRecord,
    GraphShapeAspectRecord, HadwigerAspectAuthorityError, HadwigerAspectDependencyEdge,
    HadwigerAspectDependencyRole, HadwigerAspectInvalidationScope, HadwigerAspectKind,
    HadwigerAspectPosture, HadwigerAspectRecord, HadwigerAspectScope,
    HadwigerConservativeInvalidationPosture, HadwigerDependencyClosureBlocker,
    HadwigerDependencyClosureReport, HadwigerPromotionRuleDescriptor, HadwigerRecomputePolicy,
    UnitDistanceAspectRecord,
};
pub use crate::candidate_screening::{
    advise_maximum_degree_sanity_checked, assemble_candidate_screening_report_checked,
    draft_candidate_screening_invariant_catalog_checked,
    evaluate_autocorrelation_zero_screening_checked, evaluate_boundary_ownership_screening_checked,
    evaluate_candidate_novelty_screening_checked, evaluate_certificate_screening_invariant_checked,
    evaluate_density_cap_screening_checked, evaluate_exact_arithmetic_interval_screening_checked,
    evaluate_exact_conflict_graph_screening_checked,
    evaluate_exact_unit_distance_conflict_screening_checked,
    evaluate_exhaustive_local_neighborhood_screening_checked,
    evaluate_finite_patch_boundary_extension_screening_checked,
    evaluate_forbidden_displacement_screening_checked,
    evaluate_fractional_chromatic_certificate_checked,
    evaluate_fractional_chromatic_screening_checked, evaluate_graph_screening_invariant_checked,
    evaluate_known_obstruction_containment_screening_checked,
    evaluate_local_density_window_screening_checked, evaluate_lovasz_theta_certificate_checked,
    evaluate_lovasz_theta_screening_checked, evaluate_minkowski_difference_screening_checked,
    evaluate_monodromy_color_holonomy_screening_checked,
    evaluate_numerical_margin_screening_checked,
    evaluate_periodic_quotient_graph_screening_checked,
    evaluate_rigidity_realization_screening_checked,
    evaluate_same_color_separation_screening_checked,
    evaluate_substitution_consistency_screening_checked,
    evaluate_symmetry_orbit_reduction_screening_checked, evaluate_tile_diameter_screening_checked,
    evaluate_translation_rotation_closure_screening_checked,
    evaluate_unit_distance_embeddability_screening_checked, AutocorrelationOverlapCertificate,
    BoundaryOwnedRegion, BoundaryOwnershipCertificate, CandidateNoveltyCertificate,
    CandidateScreeningAdvisoryArtifact, CandidateScreeningAdvisoryContributionRecord,
    CandidateScreeningAdvisoryPosture, CandidateScreeningApplicability,
    CandidateScreeningCertificate, CandidateScreeningError, CandidateScreeningEvaluation,
    CandidateScreeningEvaluationMode, CandidateScreeningEvaluationReport,
    CandidateScreeningInvariantAuthority, CandidateScreeningInvariantCatalog,
    CandidateScreeningInvariantFamily, CandidateScreeningInvariantNode, CandidateScreeningVerdict,
    ColorPermutation, DensityCapCertificate, ExactArithmeticIntervalCertificate,
    ExactArithmeticIntervalExpectation, ExactConflictGraphEdgeCertificate,
    ExactUnitDistanceConflictCertificate, ExhaustiveLocalNeighborhoodCertificate,
    FinitePatchBoundaryExtensionCertificate, ForbiddenDisplacementCertificate,
    FractionalChromaticCertificate, KnownObstructionContainmentCertificate,
    LocalDensityWindowCertificate, LovaszThetaCertificate, MinkowskiUnitIntersectionCertificate,
    MonodromyColorHolonomyCertificate, NumericalMarginCertificate, PeriodicColorClassMeasureModel,
    PeriodicMeasureCell, PeriodicMeasureWindow, PeriodicQuotientConflictCertificate,
    PeriodicQuotientRectangleModel, PeriodicQuotientTile, RigidityRealizationCertificate,
    RigidityRealizationPosture, SameColorSeparationCertificate, ScreeningMatrixCertificate,
    ScreeningPsdWitnessCertificate, ScreeningRational, ScreeningRectangularRegion,
    ScreeningSolverTranscript, SubstitutionConsistencyCertificate,
    SubstitutionConsistencyFailureKind, SymmetryOrbitReductionCertificate, TileDiameterCertificate,
    TranslationRotationClosureCertificate, UnitDistanceEmbeddabilityCertificate,
};
pub use crate::conflict_graphs::{
    extract_conflict_core_checked, extract_conflict_graph_checked, ConflictCoreDeletionCheck,
    ConflictCoreDeletionCheckKind, ConflictCoreDeletionCheckPosture,
    ConflictCoreExtractionCounters, ConflictCoreExtractionPosture, ConflictCoreExtractionReport,
    ConflictCoreExtractionRequest, ConflictCoreMinimalityCertificate, ConflictGraphError,
    ConflictGraphExtractionCounters, TilingConflictEdge, TilingConflictEdgeBasis,
    TilingConflictGraph, TilingConflictGraphExtractionReport, TilingConflictGraphExtractionRequest,
};
pub use crate::discovery_loop::{
    attach_failure_to_research_graph, mine_research_patterns, plan_next_experiments,
    propose_invariant_hypotheses, recompute_derived_discovery_frontier, update_discovery_frontier,
    CounterexampleObligation, DeadEndSignature, DerivedFrontierState, DiscoveryFrontier,
    DiscoveryScorecard, ExperimentBatch, ExperimentPlan, ExperimentResult,
    ExperimentSuppressionProof, FailureBasisFingerprint, FailureScope, GraphResidentFailure,
    HadwigerDiscoveryCounters, HadwigerDiscoveryError, HadwigerDiscoveryEvidenceReference,
    InvariantCandidate, InvariantHypothesis, MotifObservation, PatternSignature,
    ReactivationCondition, ResearchEvidenceCorpus, ResearchEvidenceCorpusBuilder,
    RetiredHypothesisRecord, SuppressionRelation,
};
pub use crate::domain_artifacts::{
    AIAdvisoryArtifact, ColorabilityEncoding, ColorabilityVerification,
    ColorabilityVerificationPosture, ColoringRefutationCertificate, EdgeIdentity,
    EmbeddingCandidate, GadgetContract, GadgetDefinition, GraphComposition, GraphIdentity,
    GraphVersion, GraphVersionBuilder, HadwigerArtifactAuthorityOwner, HadwigerArtifactDigest,
    HadwigerArtifactKind, HadwigerArtifactReference, HadwigerArtifactShapeError,
    HadwigerArtifactSourceReference, HadwigerCanonicalArtifact, HadwigerCheckerBoundaryKind,
    HadwigerCheckerCausalEvidence, HadwigerCheckerPosture, HadwigerDeclaredFamilyCheckedExt,
    HadwigerProofClaimKind, HadwigerProofClaimPosture, HadwigerQueryDeclarationReference,
    LowerBoundWitnessArtifact, ProofClaim, ReductionTrace, RetainedBackgroundTheorem, SolverRun,
    SolverRunPosture, UnitDistanceVerification, UnsatCoreArtifact, VertexIdentity,
};
pub use crate::domain_declarations::{
    declare_research_request_checked, research_declaration_entry_inventory,
    research_declaration_entry_readiness, AdvisoryNoteDeclaration, AdvisoryNoteDeclarationFamily,
    AutocorrelationZeroScreeningDeclaration, AutocorrelationZeroScreeningDeclarationFamily,
    BackgroundTheoremDeclaration, BackgroundTheoremDeclarationFamily,
    BoundaryOwnershipScreeningDeclaration, BoundaryOwnershipScreeningDeclarationFamily,
    CandidateGraphDeclaration, CandidateGraphDeclarationFamily,
    CandidateNoveltyScreeningDeclaration, CandidateNoveltyScreeningDeclarationFamily,
    ColorabilityDeclaration, ColorabilityDeclarationFamily, ConflictGraphExtractionDeclaration,
    ConflictGraphExtractionDeclarationFamily, CoreExtractionDeclaration,
    CoreExtractionDeclarationFamily, DensityCapScreeningDeclaration,
    DensityCapScreeningDeclarationFamily, EmbeddingDeclaration, EmbeddingDeclarationFamily,
    ExactArithmeticIntervalScreeningDeclaration, ExactArithmeticIntervalScreeningDeclarationFamily,
    ExactConflictGraphScreeningDeclaration, ExactConflictGraphScreeningDeclarationFamily,
    ExactUnitDistanceConflictScreeningDeclaration,
    ExactUnitDistanceConflictScreeningDeclarationFamily,
    ExhaustiveLocalNeighborhoodScreeningDeclaration,
    ExhaustiveLocalNeighborhoodScreeningDeclarationFamily,
    FinitePatchBoundaryExtensionScreeningDeclaration,
    FinitePatchBoundaryExtensionScreeningDeclarationFamily,
    ForbiddenDisplacementScreeningDeclaration, ForbiddenDisplacementScreeningDeclarationFamily,
    FractionalChromaticScreeningDeclaration, FractionalChromaticScreeningDeclarationFamily,
    GeneratedPatternClosureDeclaration, GeneratedPatternClosureDeclarationFamily,
    HadwigerResearchDeclarationInput, HadwigerResearchDeclarationShapeError,
    KnownObstructionContainmentScreeningDeclaration,
    KnownObstructionContainmentScreeningDeclarationFamily, LocalDensityWindowScreeningDeclaration,
    LocalDensityWindowScreeningDeclarationFamily, LovaszThetaScreeningDeclaration,
    LovaszThetaScreeningDeclarationFamily, LowerBoundTilingIterationDeclaration,
    LowerBoundTilingIterationDeclarationFamily, LowerBoundWitnessDeclaration,
    LowerBoundWitnessDeclarationFamily, MinkowskiDifferenceScreeningDeclaration,
    MinkowskiDifferenceScreeningDeclarationFamily, MonodromyColorHolonomyScreeningDeclaration,
    MonodromyColorHolonomyScreeningDeclarationFamily, MotifSeedDeclaration,
    MotifSeedDeclarationFamily, NumericalMarginScreeningDeclaration,
    NumericalMarginScreeningDeclarationFamily, PartialAdmissionExplanationDeclaration,
    PartialAdmissionExplanationDeclarationFamily, PeriodicQuotientCellDeclaration,
    PeriodicQuotientCellDeclarationFamily, PeriodicQuotientGraphScreeningDeclaration,
    PeriodicQuotientGraphScreeningDeclarationFamily, PlaneExactValueClaimDeclaration,
    PlaneExactValueClaimDeclarationFamily, PlaneLowerBoundClaimDeclaration,
    PlaneLowerBoundClaimDeclarationFamily, PlaneUpperBoundClaimDeclaration,
    PlaneUpperBoundClaimDeclarationFamily, RejectionExplanationDeclaration,
    RejectionExplanationDeclarationFamily, RigidityRealizationScreeningDeclaration,
    RigidityRealizationScreeningDeclarationFamily, SameColorSeparationScreeningDeclaration,
    SameColorSeparationScreeningDeclarationFamily, SubstitutionConsistencyScreeningDeclaration,
    SubstitutionConsistencyScreeningDeclarationFamily, SymmetryOrbitReductionScreeningDeclaration,
    SymmetryOrbitReductionScreeningDeclarationFamily, TerminalForcingStudyDeclaration,
    TerminalForcingStudyDeclarationFamily, TileContactWitnessDeclaration,
    TileContactWitnessDeclarationFamily, TileDiameterScreeningDeclaration,
    TileDiameterScreeningDeclarationFamily, TilingEquivalenceClassificationDeclaration,
    TilingEquivalenceClassificationDeclarationFamily, TilingReactivationDeclaration,
    TilingReactivationDeclarationFamily, TilingSuppressionDeclaration,
    TilingSuppressionDeclarationFamily, TranslationRotationClosureScreeningDeclaration,
    TranslationRotationClosureScreeningDeclarationFamily,
    UnitDistanceEmbeddabilityScreeningDeclaration,
    UnitDistanceEmbeddabilityScreeningDeclarationFamily, UnitDistanceVerificationDeclaration,
    UnitDistanceVerificationDeclarationFamily, UpperBoundTilingIterationDeclaration,
    UpperBoundTilingIterationDeclarationFamily, WholePlaneColoringConstructionDeclaration,
    WholePlaneColoringConstructionDeclarationFamily,
};
pub use crate::explanations::{
    explain_partial_admission, explain_query_recovery_brief, explain_rejection,
    recover_research_stop_from_contribution_composed_checked,
    recover_research_stop_from_declaration_entry_checked,
    recover_research_stop_from_grouped_orchestration_checked,
    recover_research_stop_from_grouped_orchestration_proof, recover_research_stop_from_outcome,
    ExplainPartialAdmissionRequest, ExplainRejectionRequest,
    HadwigerConservativeEscalationExplanation, HadwigerExplanationAuthoritySurface,
    HadwigerExplanationError, HadwigerExplanationStopFamily, HadwigerPartialAdmissionExplanation,
    HadwigerQueryRecoveryExplanation, HadwigerQueryRecoveryExplanationRequest,
    HadwigerRejectionExplanation, HadwigerRepairObligation, HadwigerReusableNegativeEvidence,
    HadwigerSurvivingEvidenceReport,
};
pub use crate::mathematical_verification::{
    verify_hexagonal_seven_coloring_checked, verify_k_colorability_checked,
    verify_unit_distance_embedding_checked, ExactGraphEmbedding, ExactGraphEmbeddingBuilder,
    ExactPoint2, ExactRational, HadwigerColorabilityError, HadwigerExactGeometryError,
    HadwigerPlaneColoringError, HexagonalSevenColoringConstruction,
    HexagonalSevenColoringVerificationChecked, KColorabilityVerificationChecked,
    UnitDistanceVerificationChecked, WholePlaneColoringConstruction,
    WholePlaneColoringVerification,
};
pub use crate::motif_language::{
    build_motif_from_seed_declaration_checked, certify_terminal_forcing_relation_checked,
    MotifArtifact, MotifArtifactBuilder, MotifForbiddenSameColorPair,
    MotifGeometryTemplateReference, MotifLanguageError, MotifParameterBinding,
    MotifProofSupportPosture, MotifTerminal, MotifUnitEdge, MotifVertex, TerminalForcingRelation,
    TerminalForcingRelationCertificate, TerminalForcingRelationEvidence,
    TerminalForcingRelationKind, TerminalForcingRelationPosture,
};
pub use crate::periodic_patterns::{
    certify_generated_pattern_replay_checked, certify_periodic_quotient_replay_checked,
    ColorHolonomyLoopCertificate, ColorPermutationRule, GeneratedPatternReplayBlocker,
    GeneratedPatternReplayChecked, GeneratedPatternReplayCounters, GeneratedPatternReplayError,
    GeneratedPatternReplayReport, GeneratedPatternReplayShapeError, GeneratedPatternReplaySuite,
    GeneratedPatternReplaySuiteBuilder, PeriodicLatticeBasis, PeriodicLatticeVector,
    PeriodicQuotientCell, PeriodicQuotientCellBuilder, PeriodicQuotientReplayChecked,
    PeriodicTranslationRule, PeriodicTranslationRuleBuilder,
};
pub use crate::proof_claims::{
    admit_plane_exact_value_claim_checked, admit_plane_lower_bound_claim_checked,
    admit_plane_upper_bound_claim_checked, retain_background_plane_seven_upper_bound_checked,
    HadwigerBlockedProofClaim, HadwigerProofAuthorityChain, HadwigerProofAuthorityStep,
    HadwigerProofAuthorityStepKind, HadwigerProofClaimAdmissionChecked,
    HadwigerProofClaimAdmissionError, HadwigerProofClaimAdmissionOutcome,
    HadwigerProofClaimBlocker, HadwigerProofClaimBlockerKind, PlaneExactValueClaimRequest,
    PlaneLowerBoundClaimRequest, PlaneUpperBoundClaimRequest,
};
pub use crate::query_entry::{
    hadwiger_research_domain_package, HadwigerCandidateContribution,
    HadwigerResearchAssumptionRegime, HadwigerResearchCheckerSupportRegime,
    HadwigerResearchDomainEntry, HadwigerResearchHandle, HadwigerResearchInvalidationRegime,
    HadwigerResearchOperatingContext, HadwigerResearchQueryExt,
};
pub use crate::research_cockpit::{
    assemble_research_cockpit_session_checked, certify_hadwiger_milestone_one_bundle_checked,
    declare_tile_equivalence_witness_checked, derive_research_cockpit_action_packet_checked,
    replay_research_cockpit_session_checked, HadwigerCertificationBundle,
    HadwigerCertificationDigestInventory, HadwigerCertificationScenario,
    PeriodicColorRuleSignature, ResearchCockpitAction, ResearchCockpitActionBlocker,
    ResearchCockpitActionEligibility, ResearchCockpitActionKind, ResearchCockpitActionPacket,
    ResearchCockpitCounters, ResearchCockpitEquivalenceClass, ResearchCockpitEquivalenceScope,
    ResearchCockpitError, ResearchCockpitInputDigest, ResearchCockpitReport,
    ResearchCockpitSession, ResearchCockpitSessionBuilder, TileConstraintSignature,
    TileContactGraphSignature, TileEquivalencePosture, TileEquivalenceScope,
    TileEquivalenceWitness, TileEquivalenceWitnessChecked, TileMetricThresholdSignature,
};
pub use crate::research_graph_invariants::{
    certify_research_graph_invariant_violation, draft_research_graph_invariant_catalog,
    materialize_research_graph_invariant_denial, plan_research_graph_invariant_registration,
    project_research_graph_for_invariant_registration_checked,
    register_research_graph_invariants_checked, HadwigerResearchInvariantCatalog,
    HadwigerResearchInvariantRegistrationChecked, ResearchGraphInvariantCheckRequest,
    ResearchGraphInvariantCompatibilitySurface, ResearchGraphInvariantCompatibilitySurfaces,
    ResearchGraphInvariantCounters, ResearchGraphInvariantDenial,
    ResearchGraphInvariantDenialRequest, ResearchGraphInvariantError, ResearchGraphInvariantFamily,
    ResearchGraphInvariantRegistrationPlan, ResearchGraphInvariantRegistrationPosture,
    ResearchGraphInvariantRule, ResearchGraphInvariantRuntimeProjection,
    ResearchGraphInvariantScope, ResearchGraphInvariantViolation,
    ResearchGraphInvariantViolationKind, ResearchGraphRuntimeEntityProjection,
    ResearchGraphRuntimeRelationProjection,
};
pub use crate::tiling_equivalence::{
    classify_tiling_candidate_equivalence_checked, reactivate_tiling_candidate_checked,
    suppress_equivalent_tiling_candidate_checked, TilingCandidateEquivalencePosture,
    TilingCandidateEquivalenceProof, TilingCandidateEquivalenceRequest,
    TilingCandidateSuppressionProof, TilingCandidateSuppressionRequest, TilingEquivalenceCounters,
    TilingEquivalenceError, TilingEquivalenceScope, TilingReactivationChecked,
    TilingReactivationPosture, TilingReactivationRequest, TilingSuppressionPosture,
};
pub use crate::tiling_geometry::{
    certify_rectangular_tiling_cell_geometry_checked, evaluate_tiling_boundary_ownership_checked,
    evaluate_tiling_exact_unit_contact_checked, evaluate_tiling_minkowski_contact_checked,
    evaluate_tiling_same_color_contact_checked, evaluate_tiling_tile_diameter_checked,
    BoundaryOwnershipKind, BoundaryOwnershipPolicy, RectangularTileRegion,
    TilingBoundaryOwnershipReport, TilingCell, TilingCellBuilder, TilingColorId, TilingContactFact,
    TilingContactReplayReport, TilingContactRole, TilingGeometryCertification,
    TilingGeometryCounters, TilingGeometryError, TilingTileId,
};
pub use crate::tiling_iteration::{
    derive_tiling_iteration_packet_checked, replay_tiling_iteration_packet_checked,
    TilingIterationAction, TilingIterationActionEligibility, TilingIterationActionKind,
    TilingIterationBlocker, TilingIterationCounters, TilingIterationError, TilingIterationPacket,
    TilingIterationPacketKind, TilingIterationPacketRequest, TilingIterationReplayReport,
};
