//! Public Hadwiger research facade.
//!
//! Ordinary callers enter through this module for Query declaration entry,
//! canonical artifacts, and aspect authority surfaces.

pub use crate::agent_advisory::{
    admit_agent_exploration_batch_checked, materialize_agent_declaration_advisory_checked,
    materialize_agent_grouped_advisory_checked, screen_agent_experiment_proposals_checked,
    AgentAdmissionAdvisory, AgentAdvisoryArtifact, AgentAdvisoryContributionRecord,
    AgentAdvisoryError, AgentAdvisoryKind, AgentExperimentProposal,
    AgentExperimentProposalScreening, AgentExplorationAdmissionChecked, AgentExplorationBatch,
    AgentExplorationBatchBuilder, AgentGroupedContributionStopKind,
    AgentInvariantHypothesisSuggestion, AgentMotifSuggestion, AgentPromotionPathDescriptor,
    AgentRepairSuggestion, AgentSourceRecord,
};
pub use crate::aspect_authority::{
    query_aspect_contract_for_hadwiger_kind, query_aspect_coverage_for_hadwiger_posture,
    query_aspect_publication_for_hadwiger_kind, AdvisoryAspectRecord, AspectClosureStop,
    AspectDependencyGraph, AspectDependencyGraphBuilder, ColorabilityAspectRecord,
    GraphShapeAspectRecord, HadwigerAspectAuthorityError, HadwigerAspectDependencyEdge,
    HadwigerAspectDependencyRole, HadwigerAspectInvalidationScope, HadwigerAspectKind,
    HadwigerAspectPosture, HadwigerAspectRecord, HadwigerAspectScope,
    HadwigerConservativeInvalidationPosture, HadwigerDependencyClosureBlocker,
    HadwigerDependencyClosureReport, HadwigerPromotionRuleDescriptor, HadwigerRecomputePolicy,
    UnitDistanceAspectRecord,
};
pub use crate::candidate_screening::{
    advise_maximum_degree_sanity_checked, assemble_candidate_screening_report_checked,
    draft_candidate_screening_invariant_catalog_checked,
    evaluate_autocorrelation_zero_screening_checked, evaluate_boundary_ownership_screening_checked,
    evaluate_candidate_novelty_screening_checked, evaluate_certificate_screening_invariant_checked,
    evaluate_density_cap_screening_checked, evaluate_exact_arithmetic_interval_screening_checked,
    evaluate_exact_conflict_graph_screening_checked,
    evaluate_exact_unit_distance_conflict_screening_checked,
    evaluate_exhaustive_local_neighborhood_screening_checked,
    evaluate_finite_patch_boundary_extension_screening_checked,
    evaluate_forbidden_displacement_screening_checked,
    evaluate_fractional_chromatic_certificate_checked,
    evaluate_fractional_chromatic_screening_checked,
    evaluate_geometric_fractional_chromatic_certificate_checked,
    evaluate_geometric_fractional_chromatic_screening_checked,
    evaluate_graph_screening_invariant_checked,
    evaluate_known_obstruction_containment_screening_checked,
    evaluate_local_density_window_screening_checked, evaluate_lovasz_theta_certificate_checked,
    evaluate_lovasz_theta_screening_checked, evaluate_minkowski_difference_screening_checked,
    evaluate_monodromy_color_holonomy_screening_checked,
    evaluate_numerical_margin_screening_checked,
    evaluate_periodic_quotient_graph_screening_checked,
    evaluate_rigidity_realization_screening_checked,
    evaluate_same_color_separation_screening_checked,
    evaluate_substitution_consistency_screening_checked,
    evaluate_symmetry_orbit_reduction_screening_checked, evaluate_tile_diameter_screening_checked,
    evaluate_translation_rotation_closure_screening_checked,
    evaluate_unit_distance_embeddability_screening_checked, AutocorrelationOverlapCertificate,
    BoundaryOwnedRegion, BoundaryOwnershipCertificate, CandidateNoveltyCertificate,
    CandidateScreeningAdvisoryArtifact, CandidateScreeningAdvisoryContributionRecord,
    CandidateScreeningAdvisoryPosture, CandidateScreeningApplicability,
    CandidateScreeningCertificate, CandidateScreeningError, CandidateScreeningEvaluation,
    CandidateScreeningEvaluationMode, CandidateScreeningEvaluationReport,
    CandidateScreeningInvariantAuthority, CandidateScreeningInvariantCatalog,
    CandidateScreeningInvariantFamily, CandidateScreeningInvariantNode, CandidateScreeningVerdict,
    ColorPermutation, DensityCapCertificate, ExactArithmeticIntervalCertificate,
    ExactArithmeticIntervalExpectation, ExactConflictGraphEdgeCertificate,
    ExactUnitDistanceConflictCertificate, ExhaustiveLocalNeighborhoodCertificate,
    FinitePatchBoundaryExtensionCertificate, ForbiddenDisplacementCertificate,
    FractionalChromaticCertificate, GeometricFractionalChromaticCertificate,
    GeometricFractionalEqualityAdjustment, GeometricFractionalSearchScope,
    GeometricPairwiseSquaredDistance, GeometricSubsetIsometryWitness,
    KnownObstructionContainmentCertificate, LocalDensityWindowCertificate, LovaszThetaCertificate,
    MinkowskiUnitIntersectionCertificate, MonodromyColorHolonomyCertificate,
    NumericalMarginCertificate, PeriodicColorClassMeasureModel, PeriodicMeasureCell,
    PeriodicMeasureWindow, PeriodicQuotientConflictCertificate, PeriodicQuotientRectangleModel,
    PeriodicQuotientTile, RigidityRealizationCertificate, RigidityRealizationPosture,
    SameColorSeparationCertificate, ScreeningMatrixCertificate, ScreeningPsdWitnessCertificate,
    ScreeningRational, ScreeningRectangularRegion, ScreeningSolverTranscript,
    SubstitutionConsistencyCertificate, SubstitutionConsistencyFailureKind,
    SymmetryOrbitReductionCertificate, TileDiameterCertificate,
    TranslationRotationClosureCertificate, UnitDistanceEmbeddabilityCertificate,
};
pub use crate::conflict_graphs::{
    extract_conflict_core_checked, extract_conflict_graph_checked, ConflictCoreDeletionCheck,
    ConflictCoreDeletionCheckKind, ConflictCoreDeletionCheckPosture,
    ConflictCoreExtractionCounters, ConflictCoreExtractionPosture, ConflictCoreExtractionReport,
    ConflictCoreExtractionRequest, ConflictCoreMinimalityCertificate, ConflictGraphError,
    ConflictGraphExtractionCounters, TilingConflictEdge, TilingConflictEdgeBasis,
    TilingConflictGraph, TilingConflictGraphExtractionReport, TilingConflictGraphExtractionRequest,
};
pub use crate::discovery_loop::{
    attach_failure_to_research_graph, mine_research_patterns, plan_next_experiments,
    propose_invariant_hypotheses, recompute_derived_discovery_frontier, update_discovery_frontier,
    CounterexampleObligation, DeadEndSignature, DerivedFrontierState, DiscoveryFrontier,
    DiscoveryScorecard, ExperimentBatch, ExperimentPlan, ExperimentResult,
    ExperimentSuppressionProof, FailureBasisFingerprint, FailureScope, GraphResidentFailure,
    HadwigerDiscoveryCounters, HadwigerDiscoveryError, HadwigerDiscoveryEvidenceReference,
    InvariantCandidate, InvariantHypothesis, MotifObservation, PatternSignature,
    ReactivationCondition, ResearchEvidenceCorpus, ResearchEvidenceCorpusBuilder,
    RetiredHypothesisRecord, SuppressionRelation,
};
pub use crate::domain_artifacts::{
    AIAdvisoryArtifact, ColorabilityEncoding, ColorabilityVerification,
    ColorabilityVerificationPosture, ColoringRefutationCertificate, EdgeIdentity,
    EmbeddingCandidate, GadgetContract, GadgetDefinition, GraphComposition, GraphIdentity,
    GraphVersion, GraphVersionBuilder, HadwigerArtifactAuthorityOwner, HadwigerArtifactDigest,
    HadwigerArtifactKind, HadwigerArtifactReference, HadwigerArtifactShapeError,
    HadwigerArtifactSourceReference, HadwigerCanonicalArtifact, HadwigerCheckerBoundaryKind,
    HadwigerCheckerCausalEvidence, HadwigerCheckerPosture, HadwigerDeclaredFamilyCheckedExt,
    HadwigerProofClaimKind, HadwigerProofClaimPosture, HadwigerQueryDeclarationReference,
    HadwigerQueryEnvelopeReference, LowerBoundWitnessArtifact, ProofClaim, ReductionTrace,
    RetainedBackgroundTheorem, SolverRun, SolverRunPosture, UnitDistanceVerification,
    UnsatCoreArtifact, VertexIdentity,
};
pub use crate::domain_declarations::{
    declare_research_request_checked, orchestrate_research_request_entry,
    research_declaration_entry_inventory, research_declaration_entry_readiness,
    AdvisoryNoteDeclaration, AdvisoryNoteDeclarationFamily,
    AutocorrelationZeroScreeningDeclaration, AutocorrelationZeroScreeningDeclarationFamily,
    BackgroundTheoremDeclaration, BackgroundTheoremDeclarationFamily,
    BoundaryOwnershipScreeningDeclaration, BoundaryOwnershipScreeningDeclarationFamily,
    CandidateGraphDeclaration, CandidateGraphDeclarationFamily,
    CandidateNoveltyScreeningDeclaration, CandidateNoveltyScreeningDeclarationFamily,
    ColorabilityDeclaration, ColorabilityDeclarationFamily, ConflictGraphExtractionDeclaration,
    ConflictGraphExtractionDeclarationFamily, CoreExtractionDeclaration,
    CoreExtractionDeclarationFamily, DensityCapScreeningDeclaration,
    DensityCapScreeningDeclarationFamily, EmbeddingDeclaration, EmbeddingDeclarationFamily,
    ExactArithmeticIntervalScreeningDeclaration, ExactArithmeticIntervalScreeningDeclarationFamily,
    ExactConflictGraphScreeningDeclaration, ExactConflictGraphScreeningDeclarationFamily,
    ExactUnitDistanceConflictScreeningDeclaration,
    ExactUnitDistanceConflictScreeningDeclarationFamily,
    ExhaustiveLocalNeighborhoodScreeningDeclaration,
    ExhaustiveLocalNeighborhoodScreeningDeclarationFamily,
    FinitePatchBoundaryExtensionScreeningDeclaration,
    FinitePatchBoundaryExtensionScreeningDeclarationFamily,
    ForbiddenDisplacementScreeningDeclaration, ForbiddenDisplacementScreeningDeclarationFamily,
    FractionalChromaticScreeningDeclaration, FractionalChromaticScreeningDeclarationFamily,
    GeneratedPatternClosureDeclaration, GeneratedPatternClosureDeclarationFamily,
    GeometricFractionalChromaticScreeningDeclaration,
    GeometricFractionalChromaticScreeningDeclarationFamily, HadwigerResearchDeclarationInput,
    HadwigerResearchDeclarationShapeError, KnownObstructionContainmentScreeningDeclaration,
    KnownObstructionContainmentScreeningDeclarationFamily, LocalDensityWindowScreeningDeclaration,
    LocalDensityWindowScreeningDeclarationFamily, LovaszThetaScreeningDeclaration,
    LovaszThetaScreeningDeclarationFamily, LowerBoundTilingIterationDeclaration,
    LowerBoundTilingIterationDeclarationFamily, LowerBoundWitnessDeclaration,
    LowerBoundWitnessDeclarationFamily, MinkowskiDifferenceScreeningDeclaration,
    MinkowskiDifferenceScreeningDeclarationFamily, MonodromyColorHolonomyScreeningDeclaration,
    MonodromyColorHolonomyScreeningDeclarationFamily, MotifSeedDeclaration,
    MotifSeedDeclarationFamily, NumericalMarginScreeningDeclaration,
    NumericalMarginScreeningDeclarationFamily, PartialAdmissionExplanationDeclaration,
    PartialAdmissionExplanationDeclarationFamily, PeriodicQuotientCellDeclaration,
    PeriodicQuotientCellDeclarationFamily, PeriodicQuotientGraphScreeningDeclaration,
    PeriodicQuotientGraphScreeningDeclarationFamily, PlaneExactValueClaimDeclaration,
    PlaneExactValueClaimDeclarationFamily, PlaneLowerBoundClaimDeclaration,
    PlaneLowerBoundClaimDeclarationFamily, PlaneUpperBoundClaimDeclaration,
    PlaneUpperBoundClaimDeclarationFamily, RejectionExplanationDeclaration,
    RejectionExplanationDeclarationFamily, RigidityRealizationScreeningDeclaration,
    RigidityRealizationScreeningDeclarationFamily, SameColorSeparationScreeningDeclaration,
    SameColorSeparationScreeningDeclarationFamily, SubstitutionConsistencyScreeningDeclaration,
    SubstitutionConsistencyScreeningDeclarationFamily, SymmetryOrbitReductionScreeningDeclaration,
    SymmetryOrbitReductionScreeningDeclarationFamily, TerminalForcingStudyDeclaration,
    TerminalForcingStudyDeclarationFamily, TileContactWitnessDeclaration,
    TileContactWitnessDeclarationFamily, TileDiameterScreeningDeclaration,
    TileDiameterScreeningDeclarationFamily, TilingEquivalenceClassificationDeclaration,
    TilingEquivalenceClassificationDeclarationFamily, TilingReactivationDeclaration,
    TilingReactivationDeclarationFamily, TilingSuppressionDeclaration,
    TilingSuppressionDeclarationFamily, TranslationRotationClosureScreeningDeclaration,
    TranslationRotationClosureScreeningDeclarationFamily,
    UnitDistanceEmbeddabilityScreeningDeclaration,
    UnitDistanceEmbeddabilityScreeningDeclarationFamily, UnitDistanceVerificationDeclaration,
    UnitDistanceVerificationDeclarationFamily, UpperBoundTilingIterationDeclaration,
    UpperBoundTilingIterationDeclarationFamily, WholePlaneColoringConstructionDeclaration,
    WholePlaneColoringConstructionDeclarationFamily,
};
pub use crate::explanations::{
    explain_partial_admission, explain_query_recovery_brief, explain_rejection,
    recover_research_stop_from_contribution_composed_checked,
    recover_research_stop_from_declaration_entry_checked,
    recover_research_stop_from_grouped_orchestration_checked,
    recover_research_stop_from_grouped_orchestration_proof, recover_research_stop_from_outcome,
    ExplainPartialAdmissionRequest, ExplainRejectionRequest,
    HadwigerConservativeEscalationExplanation, HadwigerExplanationAuthoritySurface,
    HadwigerExplanationError, HadwigerExplanationStopFamily, HadwigerPartialAdmissionExplanation,
    HadwigerQueryRecoveryExplanation, HadwigerQueryRecoveryExplanationRequest,
    HadwigerRejectionExplanation, HadwigerRepairObligation, HadwigerReusableNegativeEvidence,
    HadwigerSurvivingEvidenceReport,
};
pub use crate::frontier_exploration::{
    build_frontier_research_projection_graph_checked, mine_virtual_edge_motifs_checked,
    propose_frontier_pressure_halo_hypotheses_checked,
    run_frontier_seed_exploration_iterations_checked, BichromaticVirtualEdgeMotif,
    FrontierDegreeBucket, FrontierExplorationEvidenceBundle, FrontierExplorationEvidencePosture,
    FrontierExplorationIterationReport, FrontierExplorationRunReport,
    FrontierExplorationRunRequest, FrontierMotifMiningReport, FrontierMutationPolicy,
    FrontierPressureHaloHypothesis, FrontierPressureHaloMotif, FrontierPressureSatellite,
    FrontierPressureVertex, FrontierProjectionEdge, FrontierProjectionNode,
    FrontierResearchProjectionGraph, FrontierResearchProjectionRequest, TerminalColorForcingMotif,
    VirtualEdgeMotif,
};
pub use crate::frontier_seeds::{
    analyze_g27_algebraic_field_friction_checked, analyze_g27_dual_slack_inversion_checked,
    analyze_g27_w_circles_marginal_pressure_channel_checked,
    analyze_g27_w_circles_tight_atom_contacts_checked, audit_g27_exact_moser_basis_checked,
    audit_g27_quadratic_anchor_attachments_checked, audit_g27_w_circles_607_exact_geometry_checked,
    audit_g27_w_circles_607_finite_fractional_core_checked,
    decide_g27_row_685_next_program_checked, derive_g27_exact_rotation_pin_equation_checked,
    diagnose_g27_same_field_mwis_frontier_shape_checked,
    diagnose_g27_same_field_mwis_full_frontier_shape_checked,
    diagnose_g27_same_field_mwis_lp_guided_branch_checked,
    enumerate_g27_tight_atom_hitting_sets_checked,
    export_g27_same_field_dominant_mwis_artifact_checked,
    export_g27_same_field_retained_alignment_mwis_sweep_checked,
    export_g27_same_field_top10_mwis_sweep_checked, import_frontier_graph_seed_checked,
    inventory_g27_w_circles_public_artifacts_checked,
    load_heule_510_not_four_colorability_certificate_checked,
    materialize_g27_pressure_escape_lead_checked,
    materialize_g27_unit_attachment_obligation_checked,
    preflight_g27_cross_ring_fusion_column_generation_checked,
    preflight_g27_pressure_skeleton_spindle_checked,
    preflight_g27_same_field_mwis_branch_certificate_checked,
    preflight_g27_same_field_mwis_lp_guided_final_top_pair_checked,
    preflight_g27_same_field_mwis_lp_guided_micro_checked,
    preflight_g27_same_field_mwis_lp_guided_next_prefix_checked,
    preflight_g27_same_field_mwis_lp_guided_remaining_pair_checked,
    preflight_g27_same_field_mwis_lp_guided_second_checked,
    preflight_g27_same_field_mwis_lp_guided_third_prefix_checked,
    preflight_g27_same_field_mwis_lp_guided_top_prefix_checked,
    preflight_g27_same_field_mwis_odd_cycle_branch_checked,
    preflight_g27_same_field_mwis_top_band_collapse_checked,
    preflight_g27_same_field_pb_sat_threshold_checked, preflight_g27_same_field_structure_checked,
    preflight_g27_w_circles_symmetry_checked, preflight_g27_w_circles_weighted_certificate_checked,
    price_g27_w_circles_fixed_dual_channels_checked,
    replay_g27_cross_ring_column_generation_state_checked,
    replay_g27_exact_rotation_pin_closures_checked, replay_g27_outside_moser_anchor_checked,
    replay_g27_rotation_pin_batch_exact_checked,
    replay_g27_same_field_dominant_mwis_witness_checked,
    replay_g27_same_field_mwis_branch_prefix_checked,
    replay_g27_same_field_mwis_frontier_closure_exact_chunk_checked,
    replay_g27_same_field_mwis_lp_guided_micro_duals_checked,
    replay_g27_same_field_mwis_odd_cycle_duals_checked,
    replay_g27_same_field_mwis_odd_cycle_one_sided_duals_checked,
    replay_g27_same_field_mwis_odd_cycle_rows_checked,
    replay_g27_same_field_retained_alignment_mwis_witnesses_checked,
    replay_g27_same_field_top10_mwis_witness_checked,
    replay_g27_same_field_top10_mwis_witnesses_checked,
    replay_g27_w_circles_branch_slack_lift_checked,
    replay_g27_w_circles_certificate_admission_gap_checked,
    replay_g27_w_circles_full_terminal_export_checked,
    replay_g27_w_circles_gamma0_leaf_dual_checked, replay_g27_w_circles_gamma1_leaf_dual_checked,
    replay_g27_w_circles_parent_lift_readiness_checked,
    replay_g27_w_circles_projected_parent_lift_checked,
    replay_g27_w_circles_root_dual_cover_checked,
    replay_g27_w_circles_row_family_semantics_checked,
    replay_g27_w_circles_semantic_partition_checked,
    replay_g27_w_circles_v304_exclude_dual_cover_checked,
    replay_g27_w_circles_v304_include_dual_cover_checked,
    replay_g27_w_circles_weighted_rank_cuts_checked,
    replay_mwis_upper_bound_certificate_fixtures_checked,
    reproduce_g27_geometric_fractional_witness_checked,
    run_g27_pressure_escape_hypothesis_iterations_checked,
    run_g27_same_field_threshold_mwis_bnb_checked, scan_g27_row_685_moser_anchor_breakers_checked,
    score_g27_rotation_pin_exact_survivors_checked,
    scout_g27_same_field_mwis_frontier_closure_campaign_checked,
    screen_g27_quadratic_survivor_mutation_eligibility_checked,
    screen_g27_same_field_mwis_certificate_feasibility_checked,
    search_g27_bounded_quadratic_anchors_checked, search_g27_cross_ring_fusion_candidates_checked,
    search_g27_pressure_skeleton_spindle_rotations_checked,
    search_g27_rotation_pin_closures_checked, search_g27_same_field_witness_repair_checked,
    search_g27_w_circles_same_field_pressure_interfaces_checked,
    search_g27_w_circles_slack_halo_interfaces_checked, test_g27_dual_unit_anchor_pair_checked,
    test_g27_parameterized_one_anchor_transversal_checked, FrontierGraphSeedArtifact,
    FrontierGraphSeedImport, FrontierGraphSeedImportReport, FrontierSeedError, FrontierSeedFormat,
    G27AlgebraicFieldFrictionCandidate, G27AlgebraicFieldFrictionPosture,
    G27AlgebraicFieldFrictionReport, G27AlignmentMwisReplayReport, G27AlignmentMwisReplayStatus,
    G27AlignmentMwisSweepAlignment, G27AlignmentMwisSweepArtifact, G27AlignmentMwisSweepChannel,
    G27CrossRingColumnGenerationReplayPosture, G27CrossRingColumnGenerationReplayReport,
    G27CrossRingFusionCandidate, G27CrossRingFusionPreflightPosture,
    G27CrossRingFusionPreflightReport, G27CrossRingFusionPreflightScore,
    G27CrossRingFusionSearchReport, G27CrossRingPricingObligation, G27DominantMwisArtifact,
    G27DualSlackInversionCandidate, G27DualSlackInversionPosture, G27DualSlackInversionReport,
    G27DualUnitAnchor, G27DualUnitAnchorPosture, G27DualUnitAnchorTestReport,
    G27EscapeHypothesisIteration, G27EscapeHypothesisIterationKind, G27ExactMoserBasisAuditReport,
    G27ExactRotationBranchReplay, G27ExactRotationClosurePairReplay,
    G27ExactRotationPinClosureReplayPosture, G27ExactRotationPinClosureReplayReport,
    G27ExactRotationPinEquationPosture, G27ExactRotationPinEquationReport,
    G27FiniteFractionalCoreAuditPosture, G27FiniteFractionalCoreAuditReport,
    G27FixedDualPricingChannel, G27FixedDualPricingPosture, G27GeometricFractionalDualReplay,
    G27GeometricFractionalError, G27GeometricFractionalPressureReport,
    G27GeometricFractionalReproductionReport, G27GeometricFractionalStructuralReplay,
    G27HittingSetPosture, G27IsometryLeadDetail, G27MarginalPressureContactChannel,
    G27MoserAnchorBreakerCandidate, G27MoserAnchorScanReport, G27MotifSearchPosture,
    G27MutationEligibilityBlocker, G27MutationEligibilityPosture, G27MutationEligibilityReport,
    G27MwisBranchCertificatePreflightReport, G27MwisBranchCertificatePreflightStatus,
    G27MwisBranchPrefixReplayReport, G27MwisBranchPrefixReplayStatus,
    G27MwisCertificateFeasibilityChannel, G27MwisCertificateFeasibilityReport,
    G27MwisCertificateFeasibilityStatus, G27MwisFrontierCampaignNode, G27MwisFrontierCampaignRow,
    G27MwisFrontierCampaignRowClass, G27MwisFrontierCampaignStatus,
    G27MwisFrontierClosureCampaignScoutReport, G27MwisFrontierClosureExactLeaf,
    G27MwisFrontierClosureExactLeafStatus, G27MwisFrontierClosureExactNode,
    G27MwisFrontierClosureExactReplayReport, G27MwisFrontierClosureExactStatus,
    G27MwisFrontierShapeReport, G27MwisFrontierShapeStatus, G27MwisLpGuidedBranchReport,
    G27MwisLpGuidedBranchRow, G27MwisLpGuidedBranchStatus, G27MwisLpGuidedMicroDualReport,
    G27MwisLpGuidedMicroDualStatus, G27MwisLpGuidedMicroReport, G27MwisLpGuidedMicroStatus,
    G27MwisLpGuidedSecondReport, G27MwisLpGuidedSecondStatus, G27MwisLpGuidedTopPrefixNode,
    G27MwisLpGuidedTopPrefixReport, G27MwisLpGuidedTopPrefixStatus,
    G27MwisOddCycleBranchPreflightReport, G27MwisOddCycleBranchPreflightStatus,
    G27MwisOddCycleDualReplayReport, G27MwisOddCycleDualReplayStatus,
    G27MwisOddCycleRowReplayReport, G27MwisOddCycleRowReplayStatus, G27MwisSweepArtifact,
    G27MwisSweepChannel, G27MwisSweepReplayReport, G27MwisSweepReplayStatus,
    G27MwisTopBandCollapseReport, G27MwisTopBandCollapseStatus, G27MwisWitnessReplayReport,
    G27MwisWitnessReplayStatus, G27OneAnchorTransversalPosture, G27OneAnchorTransversalReport,
    G27OutsideMoserAnchorCandidate, G27OutsideMoserAnchorPosture,
    G27OutsideMoserAnchorReplayReport, G27OutsideMoserAxis, G27OutsideMoserMutationObligation,
    G27PbSatPreflightReport, G27PbSatPreflightStatus, G27PressureEscapeHypothesisRun,
    G27PressureEscapeLeadReport, G27PressureIsometryRow, G27PressureSkeletonSpindleReport,
    G27PressureVertex, G27QuadraticAnchorAttachmentAuditReport,
    G27QuadraticAnchorAttachmentAuditRow, G27QuadraticAnchorAttachmentStatus,
    G27QuadraticAnchorExtension, G27QuadraticAnchorSearchReport,
    G27RotationPinBatchExactReplayPosture, G27RotationPinBatchExactReplayReport,
    G27RotationPinCandidateExactReplay, G27RotationPinClosureCandidate,
    G27RotationPinClosurePosture, G27RotationPinClosureSearchReport,
    G27RotationPinPressureCandidateScore, G27RotationPinPressureScorePosture,
    G27RotationPinPressureScoreReport, G27RoundDecisionPosture, G27RoundDecisionReport,
    G27SameFieldFixedDualPricingReport, G27SameFieldMarginalPressurePosture,
    G27SameFieldMarginalPressureReport, G27SameFieldPressureInterfaceCandidate,
    G27SameFieldPressureInterfacePosture, G27SameFieldPressureInterfaceSearchReport,
    G27SameFieldTightAtomContactReport, G27SpindlePreflightPosture, G27SpindleRotationCandidate,
    G27SpindleRotationSearchReport, G27StructurePreflightReport, G27StructurePreflightStatus,
    G27ThresholdMwisBnbReport, G27ThresholdMwisBnbStatus, G27TightAtomContactChannel,
    G27TightAtomContactPosture, G27TightAtomHittingSetReport, G27TightAtomTransversal,
    G27TightAtomVertexPair, G27UnitAttachmentObligationReport,
    G27WCirclesBranchSlackLiftReplayReport, G27WCirclesBranchSlackLiftReplayStatus,
    G27WCirclesCertificateAdmissionGapReplayReport, G27WCirclesCertificateAdmissionGapReplayStatus,
    G27WCirclesExactGeometryAuditReport, G27WCirclesFullTerminalExportReplayReport,
    G27WCirclesFullTerminalExportReplayStatus, G27WCirclesGamma0LeafDualReplayReport,
    G27WCirclesGamma0LeafDualReplayStatus, G27WCirclesGamma1LeafDualReplayReport,
    G27WCirclesGamma1LeafDualReplayStatus, G27WCirclesParentLiftReadinessReplayReport,
    G27WCirclesParentLiftReadinessReplayStatus, G27WCirclesProjectedParentLiftReplayReport,
    G27WCirclesProjectedParentLiftReplayStatus, G27WCirclesPublicArtifactInventoryReport,
    G27WCirclesPublicArtifactInventoryStatus, G27WCirclesPublicArtifactKind,
    G27WCirclesPublicArtifactRow, G27WCirclesRootDualCoverReplayReport,
    G27WCirclesRootDualCoverReplayStatus, G27WCirclesRowFamilySemanticsReplayReport,
    G27WCirclesRowFamilySemanticsReplayStatus, G27WCirclesSemanticPartitionReplayReport,
    G27WCirclesSemanticPartitionReplayStatus, G27WCirclesSymmetryPreflightReport,
    G27WCirclesSymmetryPreflightStatus, G27WCirclesSymmetryTransformRow,
    G27WCirclesSymmetryTransformStatus, G27WCirclesV304ExcludeDualCoverReplayReport,
    G27WCirclesV304ExcludeDualCoverReplayStatus, G27WCirclesV304IncludeDualCoverReplayReport,
    G27WCirclesV304IncludeDualCoverReplayStatus, G27WCirclesWeightedCertificatePreflightReport,
    G27WCirclesWeightedCertificatePreflightStatus, G27WCirclesWeightedRankCutReplayReport,
    G27WCirclesWeightedRankCutReplayRow, G27WCirclesWeightedRankCutReplayStatus,
    G27WitnessRepairReport, G27WitnessRepairStatus, MwisUpperBoundCertificateReplayCase,
    MwisUpperBoundCertificateReplayReport, MwisUpperBoundCertificateReplayStatus,
    RetainedFrontierColoringProof, RetainedFrontierProofError, WeightedCliqueCoverLeafV1,
    WeightedCliqueCoverRow,
};
pub use crate::mathematical_verification::{
    generate_k_colorability_certificate_with_varisat_checked,
    verify_algebraic_unit_distance_embedding_checked, verify_hexagonal_seven_coloring_checked,
    verify_k_colorability_checked, verify_k_colorability_with_certificate_checked,
    verify_unit_distance_embedding_checked, AlgebraicGraphEmbedding,
    AlgebraicGraphEmbeddingBuilder, AlgebraicPoint2, AlgebraicScalar,
    AlgebraicUnitDistanceCertificate, ColoringProofCertificate, ColoringProofCertificateFormat,
    ColoringRefutationReplayReport, ExactGraphEmbedding, ExactGraphEmbeddingBuilder, ExactPoint2,
    ExactRational, HadwigerAlgebraicGeometryError, HadwigerColorabilityError,
    HadwigerExactGeometryError, HadwigerPlaneColoringError, HexagonalSevenColoringConstruction,
    HexagonalSevenColoringVerificationChecked, KColorabilityVerificationChecked,
    QuadraticFieldElement, UnitDistanceVerificationChecked, WholePlaneColoringConstruction,
    WholePlaneColoringVerification,
};
pub use crate::motif_language::{
    build_motif_from_seed_declaration_checked, certify_terminal_forcing_relation_checked,
    MotifArtifact, MotifArtifactBuilder, MotifForbiddenSameColorPair,
    MotifGeometryTemplateReference, MotifLanguageError, MotifParameterBinding,
    MotifProofSupportPosture, MotifTerminal, MotifUnitEdge, MotifVertex, TerminalForcingRelation,
    TerminalForcingRelationCertificate, TerminalForcingRelationEvidence,
    TerminalForcingRelationKind, TerminalForcingRelationPosture,
};
pub use crate::periodic_patterns::{
    certify_generated_pattern_replay_checked, certify_periodic_quotient_replay_checked,
    ColorHolonomyLoopCertificate, ColorPermutationRule, GeneratedPatternReplayBlocker,
    GeneratedPatternReplayChecked, GeneratedPatternReplayCounters, GeneratedPatternReplayError,
    GeneratedPatternReplayReport, GeneratedPatternReplayShapeError, GeneratedPatternReplaySuite,
    GeneratedPatternReplaySuiteBuilder, PeriodicLatticeBasis, PeriodicLatticeVector,
    PeriodicQuotientCell, PeriodicQuotientCellBuilder, PeriodicQuotientReplayChecked,
    PeriodicTranslationRule, PeriodicTranslationRuleBuilder,
};
pub use crate::proof_claims::{
    admit_plane_exact_value_claim_checked, admit_plane_lower_bound_claim_checked,
    admit_plane_upper_bound_claim_checked, retain_background_plane_seven_upper_bound_checked,
    HadwigerBlockedProofClaim, HadwigerProofAuthorityChain, HadwigerProofAuthorityStep,
    HadwigerProofAuthorityStepKind, HadwigerProofClaimAdmissionChecked,
    HadwigerProofClaimAdmissionError, HadwigerProofClaimAdmissionOutcome,
    HadwigerProofClaimBlocker, HadwigerProofClaimBlockerKind, PlaneExactValueClaimRequest,
    PlaneLowerBoundClaimRequest, PlaneUpperBoundClaimRequest,
};
pub use crate::query_entry::{
    admit_hadwiger_research_handle, HadwigerResearchAdmissionError,
    HadwigerResearchAssumptionRegime, HadwigerResearchCheckerSupportRegime,
    HadwigerResearchDomainEntry, HadwigerResearchHandle, HadwigerResearchInvalidationRegime,
    HadwigerResearchOperatingContext,
};
pub use crate::research_cockpit::{
    assemble_research_cockpit_session_checked, certify_hadwiger_milestone_one_bundle_checked,
    declare_tile_equivalence_witness_checked, derive_research_cockpit_action_packet_checked,
    replay_research_cockpit_session_checked, HadwigerCertificationBundle,
    HadwigerCertificationDigestInventory, HadwigerCertificationScenario,
    PeriodicColorRuleSignature, ResearchCockpitAction, ResearchCockpitActionBlocker,
    ResearchCockpitActionEligibility, ResearchCockpitActionKind, ResearchCockpitActionPacket,
    ResearchCockpitCounters, ResearchCockpitEquivalenceClass, ResearchCockpitEquivalenceScope,
    ResearchCockpitError, ResearchCockpitInputDigest, ResearchCockpitReport,
    ResearchCockpitSession, ResearchCockpitSessionBuilder, TileConstraintSignature,
    TileContactGraphSignature, TileEquivalencePosture, TileEquivalenceScope,
    TileEquivalenceWitness, TileEquivalenceWitnessChecked, TileMetricThresholdSignature,
};
pub use crate::research_graph_invariants::{
    certify_research_graph_invariant_violation, draft_research_graph_invariant_catalog,
    materialize_research_graph_invariant_denial, plan_research_graph_invariant_registration,
    project_research_graph_for_invariant_registration_checked,
    register_research_graph_invariants_checked, HadwigerResearchInvariantCatalog,
    HadwigerResearchInvariantRegistrationChecked, ResearchGraphInvariantCheckRequest,
    ResearchGraphInvariantCompatibilitySurface, ResearchGraphInvariantCompatibilitySurfaces,
    ResearchGraphInvariantCounters, ResearchGraphInvariantDenial,
    ResearchGraphInvariantDenialRequest, ResearchGraphInvariantError, ResearchGraphInvariantFamily,
    ResearchGraphInvariantObligation, ResearchGraphInvariantObligationSet,
    ResearchGraphInvariantRegistrationPlan, ResearchGraphInvariantRegistrationPosture,
    ResearchGraphInvariantRule, ResearchGraphInvariantRuntimeProjection,
    ResearchGraphInvariantScope, ResearchGraphInvariantViolation,
    ResearchGraphInvariantViolationKind, ResearchGraphLegalityPosture, ResearchGraphLegalityReport,
    ResearchGraphLegalityViolation, ResearchGraphRuntimeEntityProjection,
    ResearchGraphRuntimeRelationProjection,
};
pub use crate::tiling_equivalence::{
    classify_tiling_candidate_equivalence_checked, reactivate_tiling_candidate_checked,
    suppress_equivalent_tiling_candidate_checked, TilingCandidateEquivalencePosture,
    TilingCandidateEquivalenceProof, TilingCandidateEquivalenceRequest,
    TilingCandidateSuppressionProof, TilingCandidateSuppressionRequest, TilingEquivalenceCounters,
    TilingEquivalenceError, TilingEquivalenceScope, TilingReactivationChecked,
    TilingReactivationPosture, TilingReactivationRequest, TilingSuppressionPosture,
};
pub use crate::tiling_geometry::{
    certify_rectangular_tiling_cell_geometry_checked, evaluate_tiling_boundary_ownership_checked,
    evaluate_tiling_exact_unit_contact_checked, evaluate_tiling_minkowski_contact_checked,
    evaluate_tiling_same_color_contact_checked, evaluate_tiling_tile_diameter_checked,
    BoundaryOwnershipKind, BoundaryOwnershipPolicy, RectangularTileRegion,
    TilingBoundaryOwnershipReport, TilingCell, TilingCellBuilder, TilingColorId, TilingContactFact,
    TilingContactReplayReport, TilingContactRole, TilingGeometryCertification,
    TilingGeometryCounters, TilingGeometryError, TilingTileId,
};
pub use crate::tiling_iteration::{
    derive_tiling_iteration_packet_checked, replay_tiling_iteration_packet_checked,
    TilingIterationAction, TilingIterationActionEligibility, TilingIterationActionKind,
    TilingIterationBlocker, TilingIterationCounters, TilingIterationError, TilingIterationPacket,
    TilingIterationPacketKind, TilingIterationPacketRequest, TilingIterationReplayReport,
};
