use super::{
    registry_row, WorthQueryConsumerResidueClass, WorthQueryConsumerResidueDetection,
    WorthQueryConsumerResidueRegistryRow,
};

pub(super) const AUTHORITY_ADOPTION_ROWS: &[WorthQueryConsumerResidueRegistryRow] = &[
    registry_row(
        WorthQueryConsumerResidueClass::DecomposedProjectionConsumptionAttempt,
        WorthQueryConsumerResidueDetection::ExactText,
        "ProjectionFactConsumptionAttempt",
        "consumer accepts a decomposed attempt instead of Query's sealed authority outcome",
        "downstream-authority-adoption",
    ),
    registry_row(
        WorthQueryConsumerResidueClass::IndependentlyPairableProjectionConsumptionParts,
        WorthQueryConsumerResidueDetection::ExactText,
        "CompletedProjectionFactConsumption",
        "consumer retains completed consumption parts that can be paired outside Query authority",
        "downstream-authority-adoption",
    ),
    registry_row(
        WorthQueryConsumerResidueClass::LegacyProjectionFactConsumptionCall,
        WorthQueryConsumerResidueDetection::ExactText,
        ".consume_projection_facts(",
        "consumer invokes the decomposed fact-consumption lifecycle instead of requesting sealed authority",
        "downstream-authority-adoption",
    ),
    registry_row(
        WorthQueryConsumerResidueClass::LegacyProjectionDeclarationCall,
        WorthQueryConsumerResidueDetection::ExactText,
        ".declare_projection_fact_consumption(",
        "consumer authors the intermediate projection lifecycle outside Query authority",
        "downstream-authority-adoption",
    ),
    registry_row(
        WorthQueryConsumerResidueClass::LegacyProjectionIntentAdmissionCall,
        WorthQueryConsumerResidueDetection::ExactText,
        "worth_query_projection_consumption_intent(",
        "consumer routes through the retired projection-consumption intent instead of requesting sealed authority",
        "downstream-authority-adoption",
    ),
    registry_row(
        WorthQueryConsumerResidueClass::LocalQueryMeasurementConsumptionIdentity,
        WorthQueryConsumerResidueDetection::ExactText,
        "ConsumerMeasurementConsumptionIdentity",
        "consumer mints a local mirror of Query consumption identity",
        "downstream-authority-adoption",
    ),
    registry_row(
        WorthQueryConsumerResidueClass::LocalProjectionContractBinding,
        WorthQueryConsumerResidueDetection::ExactText,
        "bind_projection_contract(",
        "consumer binds a decomposed projection contract instead of retaining Query authority",
        "downstream-authority-adoption",
    ),
    registry_row(
        WorthQueryConsumerResidueClass::LocalQueryBasisDigestCompatibility,
        WorthQueryConsumerResidueDetection::ExactText,
        "contract.basis_digest() != Some(",
        "consumer reopens Query basis compatibility through a reporting digest",
        "downstream-authority-adoption",
    ),
    registry_row(
        WorthQueryConsumerResidueClass::LegacyProjectionPrerequisiteAssembly,
        WorthQueryConsumerResidueDetection::ExactText,
        "with_query_prerequisites_from_projection_consumption",
        "consumer reconstructs prerequisites from decomposed projection consumption",
        "downstream-authority-adoption",
    ),
    registry_row(
        WorthQueryConsumerResidueClass::DirectInternalQueryImport,
        WorthQueryConsumerResidueDetection::ExactText,
        "worth_query::projection_consumption",
        "consumer imports Query implementation topology instead of the curated facade",
        "downstream-authority-adoption",
    ),
    registry_row(
        WorthQueryConsumerResidueClass::LegacyQueryBasisLifecycle,
        WorthQueryConsumerResidueDetection::ExactText,
        "query_basis_lifecycle",
        "consumer imports or reconstructs the deleted parallel basis lifecycle",
        "downstream-authority-adoption",
    ),
    registry_row(
        WorthQueryConsumerResidueClass::RawDomainStringAuthority,
        WorthQueryConsumerResidueDetection::ExactText,
        "worth_query_domain(",
        "consumer starts domain authority from an uninstalled string-authored root",
        "installed-domain-handle",
    ),
    registry_row(
        WorthQueryConsumerResidueClass::ConsumerAuthoredContextDigest,
        WorthQueryConsumerResidueDetection::ExactText,
        "fn context_identity_digest(",
        "consumer authors a representation digest instead of typed context identity fields",
        "installed-domain-context-identity",
    ),
    registry_row(
        WorthQueryConsumerResidueClass::ApplicationFacadeDomainAuthority,
        WorthQueryConsumerResidueDetection::ExactText,
        "WorthQueryApplicationFacade",
        "consumer retains executable domain authority outside runtime installation",
        "installed-domain-handle",
    ),
    registry_row(
        WorthQueryConsumerResidueClass::IndependentOperationRegistry,
        WorthQueryConsumerResidueDetection::ExactText,
        "WorthQueryGraphReadOperationRegistry",
        "consumer owns an operation registry independently of installed package authority",
        "installed-domain-execution-index",
    ),
    registry_row(
        WorthQueryConsumerResidueClass::CallerSuppliedOperationRegistry,
        WorthQueryConsumerResidueDetection::ExactText,
        "with_operation_registry(",
        "consumer injects operation authority into an ordinary execution path",
        "installed-domain-execution-index",
    ),
    registry_row(
        WorthQueryConsumerResidueClass::QueryPhaseMaterializerImport,
        WorthQueryConsumerResidueDetection::Ast,
        "worth-query-phase-materializer-import",
        "consumer imports Query transition machinery instead of using installed capabilities",
        "installed-domain-capability",
    ),
    registry_row(
        WorthQueryConsumerResidueClass::ConsumerSemanticDomainAdapter,
        WorthQueryConsumerResidueDetection::Ast,
        "consumer-semantic-domain-adapter",
        "consumer inserts a semantic adapter between package declaration and installed authority",
        "installed-domain-extension",
    ),
];
