use super::{
    registry_row, WorthQueryConsumerResidueClass, WorthQueryConsumerResidueDetection,
    WorthQueryConsumerResidueRegistryRow,
};

pub(super) const INSTALLED_OPERATION_ROWS: &[WorthQueryConsumerResidueRegistryRow] = &[
    registry_row(
        WorthQueryConsumerResidueClass::LocalQueryOperationRegistry,
        WorthQueryConsumerResidueDetection::ExactText,
        "QueryOperationRegistry",
        "consumer reconstructs stable installed-operation authority in a local registry",
        "installed-operating-world",
    ),
    registry_row(
        WorthQueryConsumerResidueClass::LocalQueryDependencyGraph,
        WorthQueryConsumerResidueDetection::ExactText,
        "QueryDependencyGraph",
        "consumer reconstructs Query dependency authority instead of consuming compiled impact",
        "installed-dependency-impact",
    ),
    registry_row(
        WorthQueryConsumerResidueClass::LocalQueryRecomputePolicy,
        WorthQueryConsumerResidueDetection::ExactText,
        "QueryRecomputePolicy",
        "consumer owns a local Query recompute decision instead of consuming owner impact",
        "installed-dependency-impact",
    ),
    registry_row(
        WorthQueryConsumerResidueClass::LocalQuerySharingRegistry,
        WorthQueryConsumerResidueDetection::ExactText,
        "QuerySharingRegistry",
        "consumer owns Query sharing admission or resource identity",
        "installed-managed-lease",
    ),
    registry_row(
        WorthQueryConsumerResidueClass::LocalQuerySupportMirror,
        WorthQueryConsumerResidueDetection::ExactText,
        "QuerySupportMirror",
        "consumer mirrors Query support posture instead of consuming the bound support contract",
        "installed-consumer-support",
    ),
    registry_row(
        WorthQueryConsumerResidueClass::LocalQueryInvalidationMirror,
        WorthQueryConsumerResidueDetection::ExactText,
        "QueryInvalidationMirror",
        "consumer mirrors Query invalidation meaning instead of readmitting the owner delta",
        "installed-consumer-invalidation",
    ),
    registry_row(
        WorthQueryConsumerResidueClass::LocalQueryBasisCompatibilityMirror,
        WorthQueryConsumerResidueDetection::ExactText,
        "QueryBasisCompatibility",
        "consumer reimplements Query basis compatibility outside pair-bound admission",
        "installed-compatibility",
    ),
    registry_row(
        WorthQueryConsumerResidueClass::LocalQueryPatchPosture,
        WorthQueryConsumerResidueDetection::ExactText,
        "QueryPatchPosture",
        "consumer reconstructs Query patch posture instead of applying the admitted patch",
        "installed-collection-delivery",
    ),
    registry_row(
        WorthQueryConsumerResidueClass::RawChangeDataCaptureInterpretation,
        WorthQueryConsumerResidueDetection::ExactText,
        "change_data_capture",
        "consumer interprets raw change-data-capture events as Query patch meaning",
        "installed-collection-delivery",
    ),
    registry_row(
        WorthQueryConsumerResidueClass::RawSignalImport,
        WorthQueryConsumerResidueDetection::ExactText,
        "worth_signal::",
        "consumer imports raw Signal configuration or decision machinery",
        "installed-conditional-operation",
    ),
    registry_row(
        WorthQueryConsumerResidueClass::RawRuntimeBridgeImport,
        WorthQueryConsumerResidueDetection::ExactText,
        "worth_runtime_bridge::",
        "consumer assembles Runtime Bridge requests outside the installed Query boundary",
        "installed-conditional-operation",
    ),
    registry_row(
        WorthQueryConsumerResidueClass::LocalQueryConditionEvaluator,
        WorthQueryConsumerResidueDetection::ExactText,
        "QueryConditionEvaluator",
        "consumer reimplements Query conditional evaluation or eligibility",
        "installed-conditional-operation",
    ),
    registry_row(
        WorthQueryConsumerResidueClass::OrphanQueryLifecycleJoin,
        WorthQueryConsumerResidueDetection::ExactText,
        "QueryLifecycleJoin",
        "consumer joins detached Query lifecycle parts outside their bound predecessor",
        "installed-operation-lifecycle",
    ),
];
