use super::{
    registry_row, WorthQueryConsumerResidueClass, WorthQueryConsumerResidueDetection,
    WorthQueryConsumerResidueRegistryRow,
};

pub(super) const TEST_BACKEND_ROWS: &[WorthQueryConsumerResidueRegistryRow] = &[
    registry_row(
        WorthQueryConsumerResidueClass::RuntimeSchemaAdapter,
        WorthQueryConsumerResidueDetection::ExactText,
        "impl WorthQueryRuntimeSchemaAdapter",
        "consumer reimplements the runtime schema adapter",
        "in-memory-test-backend",
    ),
    registry_row(
        WorthQueryConsumerResidueClass::RuntimeSourceAdapter,
        WorthQueryConsumerResidueDetection::ExactText,
        "impl WorthQueryRuntimeSourceAdapter",
        "consumer reimplements the runtime source adapter",
        "in-memory-test-backend",
    ),
    registry_row(
        WorthQueryConsumerResidueClass::RuntimeWriteAuthorityAdapter,
        WorthQueryConsumerResidueDetection::ExactText,
        "impl WorthQueryRuntimeWriteAuthorityAdapter",
        "consumer reimplements write authority instead of using the kit",
        "in-memory-test-backend",
    ),
    registry_row(
        WorthQueryConsumerResidueClass::RuntimeSignalSinkAdapter,
        WorthQueryConsumerResidueDetection::ExactText,
        "impl WorthQueryRuntimeSignalSinkAdapter",
        "consumer reimplements the runtime signal sink adapter",
        "in-memory-test-backend",
    ),
    registry_row(
        WorthQueryConsumerResidueClass::RuntimeSnapshotIdentityAdapter,
        WorthQueryConsumerResidueDetection::ExactText,
        "impl WorthQueryRuntimeSnapshotIdentityAdapter",
        "consumer reimplements runtime snapshot identity",
        "in-memory-test-backend",
    ),
    registry_row(
        WorthQueryConsumerResidueClass::RuntimeSubscriptionActivationAdapter,
        WorthQueryConsumerResidueDetection::ExactText,
        "impl WorthQueryRuntimeSubscriptionActivationAdapter",
        "consumer reimplements subscription activation",
        "in-memory-test-backend",
    ),
    registry_row(
        WorthQueryConsumerResidueClass::RuntimePreviewBasisAdapter,
        WorthQueryConsumerResidueDetection::ExactText,
        "impl WorthQueryRuntimePreviewBasisAdapter",
        "consumer reimplements preview basis support",
        "in-memory-test-backend",
    ),
    registry_row(
        WorthQueryConsumerResidueClass::RuntimeInspectorEvidenceAdapter,
        WorthQueryConsumerResidueDetection::ExactText,
        "impl WorthQueryRuntimeInspectorEvidenceAdapter",
        "consumer reimplements inspector evidence support",
        "in-memory-test-backend",
    ),
    registry_row(
        WorthQueryConsumerResidueClass::RuntimeBridgeHandAssembly,
        WorthQueryConsumerResidueDetection::ExactText,
        "RuntimeBridge::",
        "consumer hand-assembles runtime bridge internals",
        "in-memory-test-backend",
    ),
    registry_row(
        WorthQueryConsumerResidueClass::FabricatedMutationReceipt,
        WorthQueryConsumerResidueDetection::ExactText,
        "WorthQueryMutationReceipt::from_authoritative_parts",
        "consumer fabricates mutation receipts",
        "in-memory-test-backend",
    ),
    registry_row(
        WorthQueryConsumerResidueClass::FabricatedBridgeMutationReceipt,
        WorthQueryConsumerResidueDetection::ExactText,
        "WorthQueryMutationReceipt::from_bridge_authoritative_parts",
        "consumer fabricates bridge mutation receipts",
        "in-memory-test-backend",
    ),
    registry_row(
        WorthQueryConsumerResidueClass::FabricatedWriteAuthorityReceipt,
        WorthQueryConsumerResidueDetection::ExactText,
        "WriteAuthorityExecutionReceipt",
        "consumer fabricates write authority receipts",
        "in-memory-test-backend",
    ),
];
