from __future__ import annotations


TEXT = "workspaces/worth-ui/crates/worth-ui-text/src"
TEXT_RASTER = f"{TEXT}/raster"

COLOR_PRODUCTION_SOURCES = (
    f"{TEXT}/font_collection/color_glyph.rs",
    f"{TEXT}/font_collection/color_glyph/bitmap.rs",
    f"{TEXT}/font_collection/color_glyph/bitmap/cbdt.rs",
    f"{TEXT}/font_collection/color_glyph/bitmap/sbix.rs",
    f"{TEXT}/font_collection/color_glyph/bitmap_selection.rs",
    f"{TEXT}/font_collection/color_glyph/boundedness.rs",
    f"{TEXT}/font_collection/color_glyph/colr.rs",
    f"{TEXT}/font_collection/color_glyph/path.rs",
    f"{TEXT}/font_collection/color_glyph/png.rs",
    f"{TEXT}/font_collection/color_glyph/traversal.rs",
    f"{TEXT_RASTER}/color/admission.rs",
    f"{TEXT_RASTER}/color/bitmap.rs",
    f"{TEXT_RASTER}/color/bitmap/composite.rs",
    f"{TEXT_RASTER}/color/bitmap/decode.rs",
    f"{TEXT_RASTER}/color/colr.rs",
    f"{TEXT_RASTER}/color/colr/brush.rs",
    f"{TEXT_RASTER}/color/completion.rs",
    f"{TEXT_RASTER}/color/compositing.rs",
    f"{TEXT_RASTER}/color/image.rs",
    f"{TEXT_RASTER}/color/pixels.rs",
    f"{TEXT_RASTER}/color/transform.rs",
)

GLYPH_RASTER_SOURCES = (
    f"{TEXT}/lib.rs",
    f"{TEXT}/phase5_ledger_evidence.rs",
    f"{TEXT}/layout.rs",
    f"{TEXT}/layout_artifact.rs",
    f"{TEXT}/qualification.rs",
    f"{TEXT}/font_collection.rs",
    f"{TEXT}/font_collection/admission.rs",
    f"{TEXT}/font_collection/application_pack.rs",
    f"{TEXT}/font_collection/application_pack/qualification.rs",
    f"{TEXT}/font_collection/face.rs",
    f"{TEXT}/font_collection/lifecycle.rs",
    f"{TEXT}/font_collection/profile_data.rs",
    f"{TEXT}/font_collection/application_alpha_raster_controls.rs",
    f"{TEXT}/font_collection/application_selection_tests.rs",
    f"{TEXT}/font_collection/application_test_world.rs",
    f"{TEXT}/font_collection/phase5_raster_evidence.rs",
    f"{TEXT_RASTER}/mod.rs",
    f"{TEXT_RASTER}/phase5_evidence.rs",
    f"{TEXT_RASTER}/alpha.rs",
    f"{TEXT_RASTER}/alpha_admission.rs",
    f"{TEXT_RASTER}/alpha_record.rs",
    f"{TEXT_RASTER}/alpha_transaction_admission.rs",
    f"{TEXT_RASTER}/alpha_transaction_completion.rs",
    f"{TEXT_RASTER}/alpha_transaction_tests.rs",
    f"{TEXT_RASTER}/batch.rs",
    f"{TEXT_RASTER}/capacity.rs",
    f"{TEXT_RASTER}/cost.rs",
    f"{TEXT_RASTER}/demand.rs",
    f"{TEXT_RASTER}/demand/derivation.rs",
    f"{TEXT_RASTER}/demand_alpha_tests.rs",
    f"{TEXT_RASTER}/demand_candidate.rs",
    f"{TEXT_RASTER}/demand_geometry.rs",
    f"{TEXT_RASTER}/demand_identity.rs",
    f"{TEXT_RASTER}/denial.rs",
    f"{TEXT_RASTER}/key.rs",
    f"{TEXT_RASTER}/placement.rs",
    f"{TEXT_RASTER}/planning_geometry.rs",
    f"{TEXT_RASTER}/qualified_raster_admission.rs",
    f"{TEXT_RASTER}/source.rs",
    f"{TEXT_RASTER}/color/mod.rs",
    f"{TEXT_RASTER}/color/phase5_evidence.rs",
    f"{TEXT_RASTER}/color/tests.rs",
    f"{TEXT_RASTER}/color/transaction_tests.rs",
    "workspaces/worth-ui/crates/worth-ui-text/build.rs",
    "workspaces/worth-ui/crates/worth-ui-text/build/profile_tables.rs",
    "workspaces/worth-ui/profiles/worth-ui-global-text-v2/manifest.toml",
    "workspaces/worth-ui/profiles/worth-ui-global-text-v2/artifact-inventory.toml",
    "workspaces/worth-ui/profiles/worth-ui-global-text-v2/fonts/NotoSans-VF.ttf",
    "workspaces/worth-ui/profiles/worth-ui-global-text-v2/fonts/NotoColorEmoji.ttf",
    "workspaces/worth-ui/profiles/worth-ui-global-text-v2/fonts/LastResort-Regular.ttf",
) + COLOR_PRODUCTION_SOURCES

COLOR_RASTER_SOURCES = GLYPH_RASTER_SOURCES + (
    f"{TEXT}/font_collection/application_color_fixtures.rs",
    f"{TEXT}/font_collection/application_color_graph_controls.rs",
    f"{TEXT}/font_collection/application_color_graph_fixtures.rs",
    f"{TEXT}/font_collection/application_color_raster_controls.rs",
    f"{TEXT}/font_collection/application_color_tests.rs",
    "workspaces/worth-ui/profiles/worth-ui-global-text-v2/unicode/emoji/emoji-sequences.txt",
    "workspaces/worth-ui/profiles/worth-ui-global-text-v2/unicode/emoji/emoji-zwj-sequences.txt",
    "workspaces/worth-ui/profiles/worth-ui-global-text-v2/unicode/emoji/emoji-test.txt",
)
