use super::{
    bypass::LegacyAccessPathBypass,
    disposition::LegacySurfaceDisposition,
    surface_row::{LegacySurfaceInventoryRow, LegacySurfaceOwner, LegacySurfaceStage},
};

const fn legacy_root_row(
    surface: &'static str,
    stage: LegacySurfaceStage,
    disposition: LegacySurfaceDisposition,
    bypass: LegacyAccessPathBypass,
) -> LegacySurfaceInventoryRow {
    LegacySurfaceInventoryRow::new(
        surface,
        LegacySurfaceOwner::LegacyRootCrate,
        stage,
        disposition,
        bypass,
    )
}

const fn superseded_facade(
    surface: &'static str,
    stage: LegacySurfaceStage,
    bypass: LegacyAccessPathBypass,
) -> LegacySurfaceInventoryRow {
    legacy_root_row(
        surface,
        stage,
        LegacySurfaceDisposition::SupersededAndForbidden,
        bypass,
    )
}

const fn forbidden_surface(
    surface: &'static str,
    stage: LegacySurfaceStage,
    bypass: LegacyAccessPathBypass,
) -> LegacySurfaceInventoryRow {
    legacy_root_row(
        surface,
        stage,
        LegacySurfaceDisposition::ForbiddenAsAuthority,
        bypass,
    )
}

const fn terminal_surface(surface: &'static str) -> LegacySurfaceInventoryRow {
    legacy_root_row(
        surface,
        LegacySurfaceStage::ExecutionArtifact,
        LegacySurfaceDisposition::TerminalOnly,
        LegacyAccessPathBypass::Execution,
    )
}

const fn input_only_surface(
    surface: &'static str,
    bypass: LegacyAccessPathBypass,
) -> LegacySurfaceInventoryRow {
    legacy_root_row(
        surface,
        LegacySurfaceStage::InputOnlyArtifact,
        LegacySurfaceDisposition::ConsumedAsInputOnly,
        bypass,
    )
}

pub(crate) const LEGACY_SURFACE_ROWS: [LegacySurfaceInventoryRow; 88] = [
    superseded_facade(
        "ForgeStore",
        LegacySurfaceStage::ExecutionFacade,
        LegacyAccessPathBypass::Execution,
    ),
    superseded_facade(
        "ForgeStoreBuilder",
        LegacySurfaceStage::DeclarationFacade,
        LegacyAccessPathBypass::Declaration,
    ),
    superseded_facade(
        "ForgeStore::plan_aspect_layout_read",
        LegacySurfaceStage::SelectionFacade,
        LegacyAccessPathBypass::Selection,
    ),
    superseded_facade(
        "ForgeStore::admit_structural_block_reuse",
        LegacySurfaceStage::AdmissionFacade,
        LegacyAccessPathBypass::Admission,
    ),
    superseded_facade(
        "ForgeStore::freeze_chunk_model",
        LegacySurfaceStage::ExecutionFacade,
        LegacyAccessPathBypass::Execution,
    ),
    superseded_facade(
        "ForgeStore::admit_milestone_7_independent_layout_reference",
        LegacySurfaceStage::AdmissionFacade,
        LegacyAccessPathBypass::Admission,
    ),
    superseded_facade(
        "ForgeStore::admit_milestone_9_physical_chunk_reference",
        LegacySurfaceStage::AdmissionFacade,
        LegacyAccessPathBypass::Admission,
    ),
    superseded_facade(
        "ForgeStore::prepare_milestone_6_layout_support",
        LegacySurfaceStage::ReadinessFacade,
        LegacyAccessPathBypass::Readiness,
    ),
    superseded_facade(
        "ForgeStore::prepare_milestone_6_layout_support_with_policy",
        LegacySurfaceStage::ReadinessFacade,
        LegacyAccessPathBypass::Readiness,
    ),
    superseded_facade(
        "ForgeStore::materialize_milestone_6_layout_support",
        LegacySurfaceStage::ExecutionFacade,
        LegacyAccessPathBypass::Execution,
    ),
    superseded_facade(
        "ForgeStore::fetch_milestone_6_layout_support",
        LegacySurfaceStage::ExecutionFacade,
        LegacyAccessPathBypass::Execution,
    ),
    superseded_facade(
        "ForgeStore::execute_aspect_layout_read",
        LegacySurfaceStage::ExecutionFacade,
        LegacyAccessPathBypass::Execution,
    ),
    superseded_facade(
        "ForgeStore::read_aspect_layout_control_truth",
        LegacySurfaceStage::ExecutionFacade,
        LegacyAccessPathBypass::Execution,
    ),
    superseded_facade(
        "ForgeStore::execute_aspect_layout_read_in_lane",
        LegacySurfaceStage::ExecutionFacade,
        LegacyAccessPathBypass::Execution,
    ),
    superseded_facade(
        "ForgeStore::execute_aspect_layout_read_in_lane_with_policy",
        LegacySurfaceStage::ExecutionFacade,
        LegacyAccessPathBypass::Execution,
    ),
    superseded_facade(
        "ForgeStore::execute_dedup_backed_read",
        LegacySurfaceStage::ExecutionFacade,
        LegacyAccessPathBypass::Execution,
    ),
    superseded_facade(
        "ForgeStore::execute_dedup_backed_read_in_lane",
        LegacySurfaceStage::ExecutionFacade,
        LegacyAccessPathBypass::Execution,
    ),
    superseded_facade(
        "ForgeStore::execute_dedup_backed_read_in_lane_with_policy",
        LegacySurfaceStage::ExecutionFacade,
        LegacyAccessPathBypass::Execution,
    ),
    superseded_facade(
        "ForgeStore::structural_block_lookup",
        LegacySurfaceStage::ExecutionFacade,
        LegacyAccessPathBypass::Execution,
    ),
    superseded_facade(
        "ForgeStore::export_milestone_6_chunk_model",
        LegacySurfaceStage::ExecutionFacade,
        LegacyAccessPathBypass::Execution,
    ),
    superseded_facade(
        "ForgeStore::export_milestone_6_chunk_model_in_lane",
        LegacySurfaceStage::ExecutionFacade,
        LegacyAccessPathBypass::Execution,
    ),
    superseded_facade(
        "ForgeStore::export_milestone_6_chunk_model_in_lane_with_policy",
        LegacySurfaceStage::ExecutionFacade,
        LegacyAccessPathBypass::Execution,
    ),
    superseded_facade(
        "ForgeStore::rebuild_milestone_6_derived_artifacts_from_materializations",
        LegacySurfaceStage::ExecutionFacade,
        LegacyAccessPathBypass::Execution,
    ),
    superseded_facade(
        "ForgeStore::rebuild_milestone_6_derived_artifacts_from_authority",
        LegacySurfaceStage::ExecutionFacade,
        LegacyAccessPathBypass::Execution,
    ),
    forbidden_surface(
        "AspectLayoutReadRequest",
        LegacySurfaceStage::DeclarationArtifact,
        LegacyAccessPathBypass::Declaration,
    ),
    forbidden_surface(
        "AdmittedAspectLayoutReadPlan",
        LegacySurfaceStage::AdmissionArtifact,
        LegacyAccessPathBypass::Admission,
    ),
    forbidden_surface(
        "AspectLayoutReadExecutionDecision",
        LegacySurfaceStage::ExecutionArtifact,
        LegacyAccessPathBypass::Execution,
    ),
    forbidden_surface(
        "AspectLayoutReadPlanDecision",
        LegacySurfaceStage::SelectionArtifact,
        LegacyAccessPathBypass::Selection,
    ),
    forbidden_surface(
        "AspectLayoutReadExecutionResult",
        LegacySurfaceStage::ExecutionArtifact,
        LegacyAccessPathBypass::Execution,
    ),
    forbidden_surface(
        "AspectLayoutControlTruth",
        LegacySurfaceStage::ExecutionArtifact,
        LegacyAccessPathBypass::Execution,
    ),
    terminal_surface("Milestone6LayoutMaterialization"),
    terminal_surface("Milestone6ChunkModelExport"),
    forbidden_surface(
        "Milestone6DerivedArtifactRebuildReport",
        LegacySurfaceStage::ExecutionArtifact,
        LegacyAccessPathBypass::Execution,
    ),
    forbidden_surface(
        "Milestone6PreparedLayoutSupport",
        LegacySurfaceStage::ReadinessArtifact,
        LegacyAccessPathBypass::Readiness,
    ),
    forbidden_surface(
        "ChunkModelFrozenPhysicalLayout",
        LegacySurfaceStage::ExecutionArtifact,
        LegacyAccessPathBypass::Execution,
    ),
    forbidden_surface(
        "StructuralBlockLookup",
        LegacySurfaceStage::ExecutionFacade,
        LegacyAccessPathBypass::Execution,
    ),
    forbidden_surface(
        "DedupAdmittedBlockReuse",
        LegacySurfaceStage::AdmissionArtifact,
        LegacyAccessPathBypass::Admission,
    ),
    forbidden_surface(
        "DedupBackedReadResult",
        LegacySurfaceStage::ExecutionArtifact,
        LegacyAccessPathBypass::Execution,
    ),
    forbidden_surface(
        "Milestone7IndependentLayoutReference",
        LegacySurfaceStage::ExecutionArtifact,
        LegacyAccessPathBypass::Execution,
    ),
    forbidden_surface(
        "Milestone9PhysicalChunkReference",
        LegacySurfaceStage::ExecutionArtifact,
        LegacyAccessPathBypass::Execution,
    ),
    superseded_facade(
        "AspectLayoutFallbackClass",
        LegacySurfaceStage::SelectionArtifact,
        LegacyAccessPathBypass::Selection,
    ),
    superseded_facade(
        "ExplicitBroadFallbackPlan",
        LegacySurfaceStage::SelectionArtifact,
        LegacyAccessPathBypass::Selection,
    ),
    superseded_facade(
        "BranchDeltaFallbackClass",
        LegacySurfaceStage::SelectionArtifact,
        LegacyAccessPathBypass::Selection,
    ),
    input_only_surface(
        "CompatibilityRegistry",
        LegacyAccessPathBypass::DeepImportPrecedent,
    ),
    input_only_surface(
        "CompatibilityRegistrySnapshot",
        LegacyAccessPathBypass::DeepImportPrecedent,
    ),
    input_only_surface("MaintenanceDeclaration", LegacyAccessPathBypass::Lowering),
    input_only_surface(
        "AdmittedMaintenanceDeclaration",
        LegacyAccessPathBypass::Lowering,
    ),
    input_only_surface(
        "AuthoritativeReclaimMaintenanceDeclaration",
        LegacyAccessPathBypass::Lowering,
    ),
    input_only_surface(
        "CompactionMaintenanceDeclaration",
        LegacyAccessPathBypass::Lowering,
    ),
    input_only_surface(
        "DerivedFamilyRebuildMaintenanceDeclaration",
        LegacyAccessPathBypass::Lowering,
    ),
    input_only_surface(
        "MaintenanceAuditMaintenanceDeclaration",
        LegacyAccessPathBypass::Lowering,
    ),
    input_only_surface(
        "MaintenanceDeclarationClass",
        LegacyAccessPathBypass::Lowering,
    ),
    input_only_surface("MaintenanceDeclarationId", LegacyAccessPathBypass::Lowering),
    input_only_surface(
        "RebuildMaintenanceDeclaration",
        LegacyAccessPathBypass::Lowering,
    ),
    input_only_surface(
        "ReclaimMaintenanceDeclaration",
        LegacyAccessPathBypass::Lowering,
    ),
    input_only_surface(
        "ReplicationPreparationMaintenanceDeclaration",
        LegacyAccessPathBypass::Lowering,
    ),
    input_only_surface(
        "RetentionMaintenanceDeclaration",
        LegacyAccessPathBypass::Lowering,
    ),
    input_only_surface(
        "SnapshotRefreshMaintenanceDeclaration",
        LegacyAccessPathBypass::Lowering,
    ),
    input_only_surface(
        "TierMoveMaintenanceDeclaration",
        LegacyAccessPathBypass::Lowering,
    ),
    input_only_surface(
        "TierPlacementMaintenanceDeclaration",
        LegacyAccessPathBypass::Lowering,
    ),
    input_only_surface(
        "SubscriptionSupportAccessStructure",
        LegacyAccessPathBypass::Admission,
    ),
    input_only_surface(
        "SubscriptionSupportAccessStructureReport",
        LegacyAccessPathBypass::Admission,
    ),
    input_only_surface(
        "SupportTrustAccessIndexKind",
        LegacyAccessPathBypass::Admission,
    ),
    forbidden_surface(
        "Milestone7IndependentReference",
        LegacySurfaceStage::ExecutionArtifact,
        LegacyAccessPathBypass::Execution,
    ),
    forbidden_surface(
        "SupportTrustAccessPath",
        LegacySurfaceStage::SelectionArtifact,
        LegacyAccessPathBypass::Selection,
    ),
    input_only_surface(
        "SupportTrustAccessStructurePlan",
        LegacyAccessPathBypass::Admission,
    ),
    LegacySurfaceInventoryRow::new(
        "Milestone5ReadPathReport",
        LegacySurfaceOwner::CertificationLane,
        LegacySurfaceStage::CertificationArtifact,
        LegacySurfaceDisposition::CertificationOnly,
        LegacyAccessPathBypass::CertificationShortcut,
    ),
    LegacySurfaceInventoryRow::new(
        "Milestone6AccessStructureClaim",
        LegacySurfaceOwner::CertificationLane,
        LegacySurfaceStage::CertificationArtifact,
        LegacySurfaceDisposition::CertificationOnly,
        LegacyAccessPathBypass::CertificationShortcut,
    ),
    LegacySurfaceInventoryRow::new(
        "Milestone6AccessStructureContract",
        LegacySurfaceOwner::CertificationLane,
        LegacySurfaceStage::CertificationArtifact,
        LegacySurfaceDisposition::CertificationOnly,
        LegacyAccessPathBypass::CertificationShortcut,
    ),
    LegacySurfaceInventoryRow::new(
        "Milestone6AccessStructureVerification",
        LegacySurfaceOwner::CertificationLane,
        LegacySurfaceStage::CertificationArtifact,
        LegacySurfaceDisposition::CertificationOnly,
        LegacyAccessPathBypass::CertificationShortcut,
    ),
    LegacySurfaceInventoryRow::new(
        "Milestone6AccessStructureVerificationPath",
        LegacySurfaceOwner::CertificationLane,
        LegacySurfaceStage::CertificationArtifact,
        LegacySurfaceDisposition::CertificationOnly,
        LegacyAccessPathBypass::CertificationShortcut,
    ),
    LegacySurfaceInventoryRow::new(
        "Milestone6CertificationBundle",
        LegacySurfaceOwner::CertificationLane,
        LegacySurfaceStage::CertificationArtifact,
        LegacySurfaceDisposition::CertificationOnly,
        LegacyAccessPathBypass::CertificationShortcut,
    ),
    LegacySurfaceInventoryRow::new(
        "Milestone6CertificationOrigin",
        LegacySurfaceOwner::CertificationLane,
        LegacySurfaceStage::CertificationArtifact,
        LegacySurfaceDisposition::CertificationOnly,
        LegacyAccessPathBypass::CertificationShortcut,
    ),
    LegacySurfaceInventoryRow::new(
        "Milestone6CertificationSummary",
        LegacySurfaceOwner::CertificationLane,
        LegacySurfaceStage::CertificationArtifact,
        LegacySurfaceDisposition::CertificationOnly,
        LegacyAccessPathBypass::CertificationShortcut,
    ),
    LegacySurfaceInventoryRow::new(
        "Milestone6ComplexityPathStatus",
        LegacySurfaceOwner::CertificationLane,
        LegacySurfaceStage::CertificationArtifact,
        LegacySurfaceDisposition::CertificationOnly,
        LegacyAccessPathBypass::CertificationShortcut,
    ),
    LegacySurfaceInventoryRow::new(
        "Milestone6ComplexitySurface",
        LegacySurfaceOwner::CertificationLane,
        LegacySurfaceStage::CertificationArtifact,
        LegacySurfaceDisposition::CertificationOnly,
        LegacyAccessPathBypass::CertificationShortcut,
    ),
    LegacySurfaceInventoryRow::new(
        "Milestone6CounterContract",
        LegacySurfaceOwner::CertificationLane,
        LegacySurfaceStage::CertificationArtifact,
        LegacySurfaceDisposition::CertificationOnly,
        LegacyAccessPathBypass::CertificationShortcut,
    ),
    LegacySurfaceInventoryRow::new(
        "Milestone6LayoutMaterializationReport",
        LegacySurfaceOwner::CertificationLane,
        LegacySurfaceStage::CertificationArtifact,
        LegacySurfaceDisposition::CertificationOnly,
        LegacyAccessPathBypass::CertificationShortcut,
    ),
    LegacySurfaceInventoryRow::new(
        "Milestone6LayoutReadReport",
        LegacySurfaceOwner::CertificationLane,
        LegacySurfaceStage::CertificationArtifact,
        LegacySurfaceDisposition::CertificationOnly,
        LegacyAccessPathBypass::CertificationShortcut,
    ),
    LegacySurfaceInventoryRow::new(
        "Milestone6PhysicalLayoutReport",
        LegacySurfaceOwner::CertificationLane,
        LegacySurfaceStage::CertificationArtifact,
        LegacySurfaceDisposition::CertificationOnly,
        LegacyAccessPathBypass::CertificationShortcut,
    ),
    LegacySurfaceInventoryRow::new(
        "Milestone7AccessStructureClaim",
        LegacySurfaceOwner::CertificationLane,
        LegacySurfaceStage::CertificationArtifact,
        LegacySurfaceDisposition::CertificationOnly,
        LegacyAccessPathBypass::CertificationShortcut,
    ),
    LegacySurfaceInventoryRow::new(
        "Milestone7AccessStructureContract",
        LegacySurfaceOwner::CertificationLane,
        LegacySurfaceStage::CertificationArtifact,
        LegacySurfaceDisposition::CertificationOnly,
        LegacyAccessPathBypass::CertificationShortcut,
    ),
    LegacySurfaceInventoryRow::new(
        "Milestone7AccessStructureVerification",
        LegacySurfaceOwner::CertificationLane,
        LegacySurfaceStage::CertificationArtifact,
        LegacySurfaceDisposition::CertificationOnly,
        LegacyAccessPathBypass::CertificationShortcut,
    ),
    LegacySurfaceInventoryRow::new(
        "Milestone7AccessStructureVerificationPath",
        LegacySurfaceOwner::CertificationLane,
        LegacySurfaceStage::CertificationArtifact,
        LegacySurfaceDisposition::CertificationOnly,
        LegacyAccessPathBypass::CertificationShortcut,
    ),
    LegacySurfaceInventoryRow::new(
        "Milestone7CertificationBundle",
        LegacySurfaceOwner::CertificationLane,
        LegacySurfaceStage::CertificationArtifact,
        LegacySurfaceDisposition::CertificationOnly,
        LegacyAccessPathBypass::CertificationShortcut,
    ),
    LegacySurfaceInventoryRow::new(
        "Milestone7ComplexityPathStatus",
        LegacySurfaceOwner::CertificationLane,
        LegacySurfaceStage::CertificationArtifact,
        LegacySurfaceDisposition::CertificationOnly,
        LegacyAccessPathBypass::CertificationShortcut,
    ),
    LegacySurfaceInventoryRow::new(
        "Milestone7ComplexitySurface",
        LegacySurfaceOwner::CertificationLane,
        LegacySurfaceStage::CertificationArtifact,
        LegacySurfaceDisposition::CertificationOnly,
        LegacyAccessPathBypass::CertificationShortcut,
    ),
    LegacySurfaceInventoryRow::new(
        "Milestone7CounterContract",
        LegacySurfaceOwner::CertificationLane,
        LegacySurfaceStage::CertificationArtifact,
        LegacySurfaceDisposition::CertificationOnly,
        LegacyAccessPathBypass::CertificationShortcut,
    ),
];
