use worth_ui::facade::{
    WorthUiCapabilityReloadEvidence, WorthUiCapabilityReloadStatus,
    WorthUiCompileBoundaryCertification, WorthUiHeaderFrameRebindReceipt, WorthUiRuntimeFactId,
};

use crate::reload::{
    ValidationAuthoredStructuralReloadEvidence, ValidationHeaderRebindEvidence,
    ValidationPageHostRebindEvidence, ValidationPhaseExecutionEvidence,
    ValidationReloadInputDenial, ValidationReloadStage, ValidationReloadStatus,
    ValidationRuntimeChangeEvidence, ValidationThemeReloadDenial,
};

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ValidationReloadEvidenceEntry {
    RuntimeReload {
        status: ValidationReloadStatus,
        active_artifact_digest: u64,
        active_plan_digest: u64,
        phase_execution: Option<ValidationPhaseExecutionEvidence>,
        authored_structural: Option<ValidationAuthoredStructuralReloadEvidence>,
        header_rebind: Option<ValidationHeaderRebindEvidence>,
        page_host_rebind: Option<ValidationPageHostRebindEvidence>,
        query_bindings_compared: usize,
        query_rebind_entries: usize,
        changed_fact_count: usize,
        changed_facts: Vec<WorthUiRuntimeFactId>,
    },
    ThemeReload {
        status: WorthUiCapabilityReloadStatus,
        active_snapshot_digest: u64,
        touched_theme_token_count: usize,
        changed_fact_count: usize,
        changed_facts: Vec<WorthUiRuntimeFactId>,
        phase_execution: Option<ValidationPhaseExecutionEvidence>,
        header_rebind: Option<ValidationHeaderRebindEvidence>,
        page_host_rebind: Option<ValidationPageHostRebindEvidence>,
    },
    CommandReload {
        status: WorthUiCapabilityReloadStatus,
        active_snapshot_digest: u64,
        touched_command_count: usize,
        changed_fact_count: usize,
        changed_facts: Vec<WorthUiRuntimeFactId>,
        phase_execution: Option<ValidationPhaseExecutionEvidence>,
        header_rebind: Option<ValidationHeaderRebindEvidence>,
        page_host_rebind: Option<ValidationPageHostRebindEvidence>,
    },
    ComponentReload {
        status: WorthUiCapabilityReloadStatus,
        active_snapshot_digest: u64,
        touched_component_count: usize,
        changed_component_count: usize,
        family_rebuild_breadth: usize,
        changed_fact_count: usize,
        changed_facts: Vec<WorthUiRuntimeFactId>,
        phase_execution: Option<ValidationPhaseExecutionEvidence>,
        header_rebind: Option<ValidationHeaderRebindEvidence>,
        page_host_rebind: Option<ValidationPageHostRebindEvidence>,
    },
    CommandProjectionReload {
        status: WorthUiCapabilityReloadStatus,
        active_snapshot_digest: u64,
        touched_projection_count: usize,
        changed_fact_count: usize,
        changed_facts: Vec<WorthUiRuntimeFactId>,
        phase_execution: Option<ValidationPhaseExecutionEvidence>,
        header_rebind: Option<ValidationHeaderRebindEvidence>,
        page_host_rebind: Option<ValidationPageHostRebindEvidence>,
    },
    AppearanceReload {
        status: WorthUiCapabilityReloadStatus,
        active_snapshot_digest: u64,
        touched_appearance_count: usize,
        changed_appearance_count: usize,
        canonicalization_count: usize,
        descriptor_lookup_count: usize,
        family_rebuild_breadth: usize,
        changed_fact_count: usize,
        changed_facts: Vec<WorthUiRuntimeFactId>,
        phase_execution: Option<ValidationPhaseExecutionEvidence>,
        header_rebind: Option<ValidationHeaderRebindEvidence>,
        page_host_rebind: Option<ValidationPageHostRebindEvidence>,
    },
    DensityReload {
        status: WorthUiCapabilityReloadStatus,
        active_snapshot_digest: u64,
        touched_density_count: usize,
        changed_density_count: usize,
        canonicalization_count: usize,
        descriptor_lookup_count: usize,
        family_rebuild_breadth: usize,
        changed_fact_count: usize,
        changed_facts: Vec<WorthUiRuntimeFactId>,
        phase_execution: Option<ValidationPhaseExecutionEvidence>,
        header_rebind: Option<ValidationHeaderRebindEvidence>,
        page_host_rebind: Option<ValidationPageHostRebindEvidence>,
    },
    AuthoredBatchReload {
        source_evidence: crate::reload::ValidationReloadEvidence,
        capability_evidence: WorthUiCapabilityReloadEvidence,
        runtime_change: ValidationRuntimeChangeEvidence,
        compile_boundary: WorthUiCompileBoundaryCertification,
        phase_execution: Option<ValidationPhaseExecutionEvidence>,
        authored_structural: Option<ValidationAuthoredStructuralReloadEvidence>,
        header_rebind: Option<ValidationHeaderRebindEvidence>,
        page_host_rebind: Option<ValidationPageHostRebindEvidence>,
    },
    ThemeDenied(ValidationThemeReloadDenial),
    SourceActivationDenied(ValidationReloadStage),
    ThemeActivationDenied(worth_ui::facade::WorthUiCapabilityReloadStage),
    ComponentActivationDenied(worth_ui::facade::WorthUiCapabilityReloadStage),
    CommandActivationDenied(worth_ui::facade::WorthUiCapabilityReloadStage),
    CommandProjectionActivationDenied(worth_ui::facade::WorthUiCapabilityReloadStage),
    AppearanceActivationDenied(worth_ui::facade::WorthUiCapabilityReloadStage),
    DensityActivationDenied(worth_ui::facade::WorthUiCapabilityReloadStage),
    InputUnreadable(ValidationReloadInputDenial),
}

pub fn header_rebind_evidence(
    receipt: Option<&WorthUiHeaderFrameRebindReceipt>,
) -> Option<ValidationHeaderRebindEvidence> {
    receipt.map(ValidationHeaderRebindEvidence::from_receipt)
}
