use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum SubscriptionSupportCertificationLaneKind {
    ExactResumeControl,
    RestartExactResume,
    RebuildRequiredMissingSupport,
    DegradedButRecoverable,
    NotResumableBasisDrift,
    NotResumableCursorDrift,
    SupportDigestDrift,
    CompatibilityDrift,
    CursorOnlyExactResumeRejected,
    CrossFamilyReuseRejected,
    SessionMemoryLossNonAuthoritative,
    TierRecallCostOnly,
    RuntimeHandoffEquivalence,
    UnknownUpstreamAuthorityRejected,
    NonCanonicalScopeRejected,
    UnsupportedFamilyKindRejected,
    MultiDriftBasisPrecedence,
    MultiDriftCompatibilityPrecedence,
    RebuildBasisMissingNotResumable,
    BackendAccessStructureDebt,
    DecodedRowPublicationRejected,
    OversizedPayloadRejectedBeforeDecode,
    RestartShardBoundedReconstruction,
    ResultCostSurfaceExact,
    BatchClassificationDebt,
    SupportCompatibilityExactMigration,
    SupportCompatibilityDegraded,
    SupportCompatibilityOldReaderRejected,
    SupportCompatibilityUnknownFamilyRejected,
    SupportCompatibilityVersionSkewRejected,
    SupportRetentionExactPreserved,
    SupportRetentionCompactedExact,
    SupportRetentionReclaimedRebuildable,
    SupportRetentionExpiredByPolicy,
    SupportPortabilityFullScopeReplicated,
    SupportPortabilityPartialOmission,
    SupportPortabilityImportAdmitted,
    SupportPortabilityImportMissingBasisNotResumable,
    SupportMaintenanceRebuildAdmitted,
    SupportMaintenanceRefreshAdmitted,
    SupportMaintenanceCompatibilityMigrationAdmitted,
    SupportMaintenanceDegradationRecoveryAdmitted,
    SupportMaintenanceInterruptedRestartRecovered,
    SupportMaintenanceDelayedDebtReported,
    SupportMaintenanceCoalescedRebuildAdmitted,
    SupportFamilyLocalBatchBounded,
    SupportBasisLocalBatchBounded,
    SupportPortabilityScopeBatchBounded,
    SupportMaintenanceKeyBatchBounded,
    SupportStoreGlobalDensityRejected,
    SupportForegroundOperationalWorkRejected,
    SupportBatchReceiptReuseVerified,
    SupportActionPublicationCrashRecovered,
    SupportGlobalScanRecoveryForbidden,
    SupportHiddenExactLossForbidden,
}

impl SubscriptionSupportCertificationLaneKind {
    pub fn phase_5b_required() -> &'static [Self] {
        &PHASE_5B_REQUIRED_CERTIFICATION_LANES
    }

    pub fn phase_6a_required() -> &'static [Self] {
        &PHASE_6A_REQUIRED_CERTIFICATION_LANES
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SubscriptionSupportCertificationMatrixStatus {
    Phase5BComplete,
    Phase6AOperationalParticipationComplete,
}

const PHASE_5B_REQUIRED_CERTIFICATION_LANES: [SubscriptionSupportCertificationLaneKind; 25] = [
    SubscriptionSupportCertificationLaneKind::ExactResumeControl,
    SubscriptionSupportCertificationLaneKind::RestartExactResume,
    SubscriptionSupportCertificationLaneKind::RebuildRequiredMissingSupport,
    SubscriptionSupportCertificationLaneKind::DegradedButRecoverable,
    SubscriptionSupportCertificationLaneKind::NotResumableBasisDrift,
    SubscriptionSupportCertificationLaneKind::NotResumableCursorDrift,
    SubscriptionSupportCertificationLaneKind::SupportDigestDrift,
    SubscriptionSupportCertificationLaneKind::CompatibilityDrift,
    SubscriptionSupportCertificationLaneKind::CursorOnlyExactResumeRejected,
    SubscriptionSupportCertificationLaneKind::CrossFamilyReuseRejected,
    SubscriptionSupportCertificationLaneKind::SessionMemoryLossNonAuthoritative,
    SubscriptionSupportCertificationLaneKind::TierRecallCostOnly,
    SubscriptionSupportCertificationLaneKind::RuntimeHandoffEquivalence,
    SubscriptionSupportCertificationLaneKind::UnknownUpstreamAuthorityRejected,
    SubscriptionSupportCertificationLaneKind::NonCanonicalScopeRejected,
    SubscriptionSupportCertificationLaneKind::UnsupportedFamilyKindRejected,
    SubscriptionSupportCertificationLaneKind::MultiDriftBasisPrecedence,
    SubscriptionSupportCertificationLaneKind::MultiDriftCompatibilityPrecedence,
    SubscriptionSupportCertificationLaneKind::RebuildBasisMissingNotResumable,
    SubscriptionSupportCertificationLaneKind::BackendAccessStructureDebt,
    SubscriptionSupportCertificationLaneKind::DecodedRowPublicationRejected,
    SubscriptionSupportCertificationLaneKind::OversizedPayloadRejectedBeforeDecode,
    SubscriptionSupportCertificationLaneKind::RestartShardBoundedReconstruction,
    SubscriptionSupportCertificationLaneKind::ResultCostSurfaceExact,
    SubscriptionSupportCertificationLaneKind::BatchClassificationDebt,
];

const PHASE_6A_REQUIRED_CERTIFICATION_LANES: [SubscriptionSupportCertificationLaneKind; 55] = [
    SubscriptionSupportCertificationLaneKind::ExactResumeControl,
    SubscriptionSupportCertificationLaneKind::RestartExactResume,
    SubscriptionSupportCertificationLaneKind::RebuildRequiredMissingSupport,
    SubscriptionSupportCertificationLaneKind::DegradedButRecoverable,
    SubscriptionSupportCertificationLaneKind::NotResumableBasisDrift,
    SubscriptionSupportCertificationLaneKind::NotResumableCursorDrift,
    SubscriptionSupportCertificationLaneKind::SupportDigestDrift,
    SubscriptionSupportCertificationLaneKind::CompatibilityDrift,
    SubscriptionSupportCertificationLaneKind::CursorOnlyExactResumeRejected,
    SubscriptionSupportCertificationLaneKind::CrossFamilyReuseRejected,
    SubscriptionSupportCertificationLaneKind::SessionMemoryLossNonAuthoritative,
    SubscriptionSupportCertificationLaneKind::TierRecallCostOnly,
    SubscriptionSupportCertificationLaneKind::RuntimeHandoffEquivalence,
    SubscriptionSupportCertificationLaneKind::UnknownUpstreamAuthorityRejected,
    SubscriptionSupportCertificationLaneKind::NonCanonicalScopeRejected,
    SubscriptionSupportCertificationLaneKind::UnsupportedFamilyKindRejected,
    SubscriptionSupportCertificationLaneKind::MultiDriftBasisPrecedence,
    SubscriptionSupportCertificationLaneKind::MultiDriftCompatibilityPrecedence,
    SubscriptionSupportCertificationLaneKind::RebuildBasisMissingNotResumable,
    SubscriptionSupportCertificationLaneKind::BackendAccessStructureDebt,
    SubscriptionSupportCertificationLaneKind::DecodedRowPublicationRejected,
    SubscriptionSupportCertificationLaneKind::OversizedPayloadRejectedBeforeDecode,
    SubscriptionSupportCertificationLaneKind::RestartShardBoundedReconstruction,
    SubscriptionSupportCertificationLaneKind::ResultCostSurfaceExact,
    SubscriptionSupportCertificationLaneKind::BatchClassificationDebt,
    SubscriptionSupportCertificationLaneKind::SupportCompatibilityExactMigration,
    SubscriptionSupportCertificationLaneKind::SupportCompatibilityDegraded,
    SubscriptionSupportCertificationLaneKind::SupportCompatibilityOldReaderRejected,
    SubscriptionSupportCertificationLaneKind::SupportCompatibilityUnknownFamilyRejected,
    SubscriptionSupportCertificationLaneKind::SupportCompatibilityVersionSkewRejected,
    SubscriptionSupportCertificationLaneKind::SupportRetentionExactPreserved,
    SubscriptionSupportCertificationLaneKind::SupportRetentionCompactedExact,
    SubscriptionSupportCertificationLaneKind::SupportRetentionReclaimedRebuildable,
    SubscriptionSupportCertificationLaneKind::SupportRetentionExpiredByPolicy,
    SubscriptionSupportCertificationLaneKind::SupportPortabilityFullScopeReplicated,
    SubscriptionSupportCertificationLaneKind::SupportPortabilityPartialOmission,
    SubscriptionSupportCertificationLaneKind::SupportPortabilityImportAdmitted,
    SubscriptionSupportCertificationLaneKind::SupportPortabilityImportMissingBasisNotResumable,
    SubscriptionSupportCertificationLaneKind::SupportMaintenanceRebuildAdmitted,
    SubscriptionSupportCertificationLaneKind::SupportMaintenanceRefreshAdmitted,
    SubscriptionSupportCertificationLaneKind::SupportMaintenanceCompatibilityMigrationAdmitted,
    SubscriptionSupportCertificationLaneKind::SupportMaintenanceDegradationRecoveryAdmitted,
    SubscriptionSupportCertificationLaneKind::SupportMaintenanceInterruptedRestartRecovered,
    SubscriptionSupportCertificationLaneKind::SupportMaintenanceDelayedDebtReported,
    SubscriptionSupportCertificationLaneKind::SupportMaintenanceCoalescedRebuildAdmitted,
    SubscriptionSupportCertificationLaneKind::SupportFamilyLocalBatchBounded,
    SubscriptionSupportCertificationLaneKind::SupportBasisLocalBatchBounded,
    SubscriptionSupportCertificationLaneKind::SupportPortabilityScopeBatchBounded,
    SubscriptionSupportCertificationLaneKind::SupportMaintenanceKeyBatchBounded,
    SubscriptionSupportCertificationLaneKind::SupportStoreGlobalDensityRejected,
    SubscriptionSupportCertificationLaneKind::SupportForegroundOperationalWorkRejected,
    SubscriptionSupportCertificationLaneKind::SupportBatchReceiptReuseVerified,
    SubscriptionSupportCertificationLaneKind::SupportActionPublicationCrashRecovered,
    SubscriptionSupportCertificationLaneKind::SupportGlobalScanRecoveryForbidden,
    SubscriptionSupportCertificationLaneKind::SupportHiddenExactLossForbidden,
];
