use worth_ui_host_contract::{
    UiHostKey, UiHostKeyTransition, UiHostKeyboardModifiers, UiHostObservationPayload,
};

pub(super) fn translate(
    key: egui::Key,
    physical_key: Option<egui::Key>,
    pressed: bool,
    repeat: bool,
    modifiers: egui::Modifiers,
) -> UiHostObservationPayload {
    UiHostObservationPayload::Keyboard {
        logical_key: key_from_egui(key),
        physical_key: physical_key.map(key_from_egui),
        modifiers: modifiers_from_egui(modifiers),
        transition: if pressed {
            UiHostKeyTransition::Pressed { repeat }
        } else {
            UiHostKeyTransition::Released
        },
    }
}

fn modifiers_from_egui(modifiers: egui::Modifiers) -> UiHostKeyboardModifiers {
    UiHostKeyboardModifiers::new(
        modifiers.alt,
        modifiers.ctrl,
        modifiers.shift,
        modifiers.mac_cmd,
        modifiers.command,
    )
}

macro_rules! map_egui_keys {
    ($key:expr; $($variant:ident),+ $(,)?) => {
        match $key {
            $(egui::Key::$variant => UiHostKey::$variant,)+
        }
    };
}

fn key_from_egui(key: egui::Key) -> UiHostKey {
    map_egui_keys!(
        key;
        ArrowDown,
        ArrowLeft,
        ArrowRight,
        ArrowUp,
        Escape,
        Tab,
        Backspace,
        Enter,
        Space,
        Insert,
        Delete,
        Home,
        End,
        PageUp,
        PageDown,
        Copy,
        Cut,
        Paste,
        Colon,
        Comma,
        Backslash,
        Slash,
        Pipe,
        Questionmark,
        Exclamationmark,
        OpenBracket,
        CloseBracket,
        OpenCurlyBracket,
        CloseCurlyBracket,
        Backtick,
        Minus,
        Period,
        Plus,
        Equals,
        Semicolon,
        Quote,
        Num0,
        Num1,
        Num2,
        Num3,
        Num4,
        Num5,
        Num6,
        Num7,
        Num8,
        Num9,
        A,
        B,
        C,
        D,
        E,
        F,
        G,
        H,
        I,
        J,
        K,
        L,
        M,
        N,
        O,
        P,
        Q,
        R,
        S,
        T,
        U,
        V,
        W,
        X,
        Y,
        Z,
        F1,
        F2,
        F3,
        F4,
        F5,
        F6,
        F7,
        F8,
        F9,
        F10,
        F11,
        F12,
        F13,
        F14,
        F15,
        F16,
        F17,
        F18,
        F19,
        F20,
        F21,
        F22,
        F23,
        F24,
        F25,
        F26,
        F27,
        F28,
        F29,
        F30,
        F31,
        F32,
        F33,
        F34,
        F35,
        BrowserBack,
        ShiftLeft,
        ShiftRight,
        ControlLeft,
        ControlRight,
        AltLeft,
        AltRight,
        SuperLeft,
        SuperRight,
        IntlBackslash,
    )
}
