use super::{
    OperationalBoundaryDirection, OperationalCostClass, OperationalProofLane,
    OperationalRecoveryBoundaryEntry, SharedVocabularyAdoptionEntry,
    SharedVocabularyAdoptionLedger,
};

macro_rules! entry {
    (
        $artifact:expr,
        $authority_owner:expr,
        $observation_owner:expr,
        $mutation_owner:expr,
        $consumer:expr,
        $direction:expr,
        $construction_authority:expr,
        $cost_class:expr,
        $failure_topology:expr,
        $proof_lane:expr $(,)?
    ) => {
        OperationalRecoveryBoundaryEntry {
            artifact: $artifact,
            authority_owner: $authority_owner,
            observation_owner: $observation_owner,
            mutation_owner: $mutation_owner,
            consumer: $consumer,
            direction: $direction,
            construction_authority: $construction_authority,
            cost_class: $cost_class,
            failure_topology: $failure_topology,
            proof_lane: $proof_lane,
        }
    };
}

const ENTRIES: &[OperationalRecoveryBoundaryEntry] = &[
    entry!(
        "current authority",
        "worth-store-authority",
        "worth-store-authority",
        "worth-store-authority",
        "worth-store-operations",
        OperationalBoundaryDirection::OwnerToOperations,
        "StoreCurrentAuthorityWitness",
        OperationalCostClass::Constant,
        "authority media",
        OperationalProofLane::OwnerReceipt,
    ),
    entry!(
        "backup/export custody",
        "worth-store-security",
        "worth-store-security",
        "worth-store-security",
        "worth-store-operations",
        OperationalBoundaryDirection::OwnerToOperations,
        "StoreAuthorityBoundSecurityScopeReceipt",
        OperationalCostClass::Constant,
        "key and custody provider",
        OperationalProofLane::OwnerReceipt,
    ),
    entry!(
        "blob custody",
        "worth-store-blob-chunks",
        "worth-store-blob-chunks",
        "worth-store-blob-chunks",
        "worth-store-operations",
        OperationalBoundaryDirection::OwnerToOperations,
        "AdmittedBlobCustody",
        OperationalCostClass::Constant,
        "blob placement media",
        OperationalProofLane::LoweredOwnerPlan,
    ),
    entry!(
        "offline media",
        "external media",
        "worth-store-offline-verifier",
        "none",
        "worth-store-operations",
        OperationalBoundaryDirection::ExternalObservationToVerifier,
        "UntrustedOfflineMediaSet",
        OperationalCostClass::BoundedStreaming,
        "independent inspection media",
        OperationalProofLane::UntrustedObservation,
    ),
    entry!(
        "recovery candidate",
        "worth-store-recovery-physics",
        "worth-store-offline-verifier",
        "worth-store-recovery-physics",
        "worth-store-operations",
        OperationalBoundaryDirection::OwnerToOperations,
        "RecoveryCandidateSet analysis",
        OperationalCostClass::Reconstructive,
        "source and recovery media",
        OperationalProofLane::UntrustedObservation,
    ),
    entry!(
        "backup reachability lease",
        "worth-store-physical-isolation",
        "worth-store-physical-isolation",
        "worth-store-physical-isolation",
        "worth-store-operations",
        OperationalBoundaryDirection::OwnerToOperations,
        "BackupReachabilityLease",
        OperationalCostClass::BoundedStreaming,
        "source media",
        OperationalProofLane::OwnerReceipt,
    ),
    entry!(
        "repair blast-radius readiness",
        "worth-store-operations",
        "worth-store-offline-verifier",
        "worth-store-physical-integrity",
        "repair workflow",
        OperationalBoundaryDirection::OperationsToOwner,
        "RepairBlastRadiusReadiness admission",
        OperationalCostClass::BoundedStreaming,
        "damaged source media",
        OperationalProofLane::LoweredOwnerPlan,
    ),
    entry!(
        "repair quarantine scope",
        "worth-store-physical-integrity",
        "worth-store-offline-verifier",
        "worth-store-physical-integrity",
        "repair workflow",
        OperationalBoundaryDirection::OwnerToOperations,
        "RepairQuarantineScopePreservation",
        OperationalCostClass::Constant,
        "quarantine and source media",
        OperationalProofLane::OwnerReceipt,
    ),
    entry!(
        "import publication readiness",
        "worth-store-operations",
        "worth-store-layout-indexes",
        "worth-store-layout-indexes",
        "import workflow",
        OperationalBoundaryDirection::OperationsToOwner,
        "ImportPublicationReadiness admission",
        OperationalCostClass::Constant,
        "target publication media",
        OperationalProofLane::OwnerReceipt,
    ),
    entry!(
        "restored layout materialization",
        "worth-store-layout-indexes",
        "worth-store-recovery-physics",
        "worth-store-layout-indexes",
        "import workflow",
        OperationalBoundaryDirection::OwnerToOperations,
        "PublishedImportedLayout",
        OperationalCostClass::Reconstructive,
        "staging and target media",
        OperationalProofLane::OwnerReceipt,
    ),
    entry!(
        "operational control record",
        "worth-store-operations",
        "worth-store-physical-backend",
        "worth-store-physical-backend",
        "all operational workflows",
        OperationalBoundaryDirection::OperationsToOwner,
        "owner-specific control-record constructor",
        OperationalCostClass::Constant,
        "independent control media",
        OperationalProofLane::LoweredOwnerPlan,
    ),
    entry!(
        "selected control generation",
        "worth-store-authority",
        "worth-store-physical-backend",
        "worth-store-authority",
        "destructive resume and cutover gates",
        OperationalBoundaryDirection::OwnerToOperations,
        "ControlStoreFencingPort -> SelectedControlStoreGeneration",
        OperationalCostClass::BoundedStreaming,
        "fencing authority and independent control media",
        OperationalProofLane::OwnerReceipt,
    ),
    entry!(
        "physical backup artifact observation",
        "worth-store-physical-backend",
        "worth-store-physical-backend",
        "none",
        "worth-store-physical-isolation",
        OperationalBoundaryDirection::OwnerToOwner,
        "PhysicalBackupArtifactObservation",
        OperationalCostClass::BoundedStreaming,
        "source media allocation",
        OperationalProofLane::UntrustedObservation,
    ),
    entry!(
        "structurally walked offline media",
        "worth-store-offline-verifier",
        "worth-store-physical-backend",
        "none",
        "truth composition and operator diagnostics",
        OperationalBoundaryDirection::ExternalObservationToVerifier,
        "OfflineInspectionSession",
        OperationalCostClass::BoundedStreaming,
        "offline inspection media",
        OperationalProofLane::UntrustedObservation,
    ),
    entry!(
        "operational truth report",
        "worth-store-offline-verifier",
        "physical, integrity, security, and recovery owners",
        "none",
        "operations resolution",
        OperationalBoundaryDirection::OwnerToOperations,
        "compose_operational_truth",
        OperationalCostClass::Reconstructive,
        "offline inspection and owner evidence media",
        OperationalProofLane::SupportProjection,
    ),
    entry!(
        "backup cut storage posture",
        "worth-store-physical-backend",
        "worth-store-physical-backend",
        "none",
        "worth-store-physical-isolation",
        OperationalBoundaryDirection::OwnerToOwner,
        "BackupCutStoragePosture from certified backend capability claims",
        OperationalCostClass::Constant,
        "source backend and media",
        OperationalProofLane::OwnerReceipt,
    ),
    entry!(
        "admitted backup cut",
        "worth-store-physical-isolation",
        "physical and authority owners",
        "worth-store-physical-isolation",
        "backup workflow",
        OperationalBoundaryDirection::OwnerToOperations,
        "BackupCutAdmissionAuthority",
        OperationalCostClass::BoundedStreaming,
        "source and control media",
        OperationalProofLane::OwnerReceipt,
    ),
    entry!(
        "materialized backup bundle",
        "worth-store-physical-format",
        "worth-store-physical-backend",
        "worth-store-physical-backend",
        "worth-store-offline-verifier",
        OperationalBoundaryDirection::OwnerToOwner,
        "BackupBundleFormatAuthority",
        OperationalCostClass::BoundedStreaming,
        "backup staging and destination media",
        OperationalProofLane::OwnerReceipt,
    ),
    entry!(
        "structurally verified backup bundle",
        "worth-store-offline-verifier",
        "physical, format, and integrity owners",
        "none",
        "backup custody qualification",
        OperationalBoundaryDirection::OwnerToOperations,
        "verify_materialized_backup",
        OperationalCostClass::Reconstructive,
        "independently reopened backup media",
        OperationalProofLane::OwnerReceipt,
    ),
    entry!(
        "custody-qualified backup bundle",
        "worth-store-security",
        "worth-store-offline-verifier",
        "none",
        "production restore admission",
        OperationalBoundaryDirection::OwnerToOperations,
        "qualify_backup_custody",
        OperationalCostClass::Constant,
        "security and custody provider",
        OperationalProofLane::OwnerReceipt,
    ),
    entry!(
        "production-restore-admissible backup bundle",
        "worth-store-authority",
        "worth-store-offline-verifier and worth-store-security",
        "none",
        "ordinary restore workflow",
        OperationalBoundaryDirection::OwnerToOperations,
        "BackupRestoreAdmissionAuthority",
        OperationalCostClass::Constant,
        "current authority and backup media",
        OperationalProofLane::OwnerReceipt,
    ),
];

const ADOPTIONS: &[SharedVocabularyAdoptionEntry] = &[
    SharedVocabularyAdoptionEntry {
        adoption_point: "backup custody admission progression",
        stronger_store_source: "BackupExportCustodyDeclaration and BackupExportCustodyReadiness",
        shared_family: "worth-proof TransitionOutcome",
        lowering_direction: "private transition carrier inside the Store domain admission",
        strength_loss: "generic outcome has no custody, key, or authority meaning",
        construction_authority: "backup custody domain constructor",
        reverse_flow_denial: "TransitionOutcome cannot construct custody readiness",
        proof: "private readiness fields and compile-fail raw-scope case",
    },
    SharedVocabularyAdoptionEntry {
        adoption_point: "import publication progression",
        stronger_store_source: "ImportPublicationReadinessOutcome",
        shared_family: "worth-proof TransitionOutcome and DenialTransitionOutcome",
        lowering_direction: "private result carrier inside import publication admission",
        strength_loss: "generic outcome has no layout publication identity",
        construction_authority: "import publication admission",
        reverse_flow_denial: "generic outcomes cannot construct PublishedImportedLayout",
        proof: "owner outcome binding tests and private constructors",
    },
    SharedVocabularyAdoptionEntry {
        adoption_point: "repair blast-radius admission progression",
        stronger_store_source: "RepairBlastRadiusReadiness",
        shared_family: "worth-proof TransitionOutcome",
        lowering_direction: "private transition carrier inside repair admission",
        strength_loss: "generic outcome has no physical region or operator scope",
        construction_authority: "repair blast-radius admission",
        reverse_flow_denial: "TransitionOutcome cannot construct repair readiness",
        proof: "compile-fail operator/readiness separation and hostile denial tests",
    },
];

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct OperationalRecoveryBoundaryLedger;

impl OperationalRecoveryBoundaryLedger {
    pub const fn current() -> Self {
        Self
    }
    pub const fn entries(self) -> &'static [OperationalRecoveryBoundaryEntry] {
        ENTRIES
    }
    pub const fn shared_vocabulary(self) -> SharedVocabularyAdoptionLedger {
        SharedVocabularyAdoptionLedger::new(ADOPTIONS)
    }
}
