pub(super) const BACKEND_RECOVERY_SURFACES: &[(&str, &str, &str)] = &[
    (
        "PhysicalRecoveryMediaGeneration",
        "worth-store-physical-backend/recovery-media/generation",
        "phase-2",
    ),
    (
        "QualifiedPhysicalBackendProfile",
        "worth-store-physical-backend/recovery-media/profile",
        "phase-2",
    ),
    (
        "QualifiedRecoveryFilesystemMedia",
        "worth-store-physical-backend/recovery-media/qualified",
        "phase-2",
    ),
    (
        "QualifiedRecoveryFilesystemMedia::qualify_existing",
        "worth-store-physical-backend/recovery-media/qualified",
        "phase-2",
    ),
    (
        "QualifiedRecoveryFilesystemMedia::backend_profile",
        "worth-store-physical-backend/recovery-media/qualified",
        "phase-2",
    ),
    (
        "QualifiedRecoveryFilesystemMedia::media_generation",
        "worth-store-physical-backend/recovery-media/qualified",
        "phase-2",
    ),
    (
        "QualifiedRecoveryFilesystemMedia::root_ownership_identity",
        "worth-store-physical-backend/recovery-media/qualified",
        "phase-2",
    ),
    (
        "QualifiedRecoveryFilesystemMedia::recovery_effect_count",
        "worth-store-physical-backend/recovery-media/qualified",
        "phase-2",
    ),
    (
        "QualifiedRecoveryFilesystemMedia::admit_persisted_store",
        "worth-store-physical-backend/recovery-media/qualified",
        "phase-2",
    ),
    (
        "RecoveryFilesystemQualificationError",
        "worth-store-physical-backend/recovery-media/qualification",
        "phase-2",
    ),
    (
        "AdmittedRecoveryFilesystemMedia",
        "worth-store-physical-backend/recovery-media/admitted",
        "phase-2",
    ),
    (
        "AdmittedRecoveryFilesystemMedia::store_identity",
        "worth-store-physical-backend/recovery-media/admitted",
        "phase-2",
    ),
    (
        "AdmittedRecoveryFilesystemMedia::bounded_discovery",
        "worth-store-physical-backend/recovery-media/admitted",
        "phase-2",
    ),
    (
        "AdmittedRecoveryFilesystemMedia::recovery_effect_count",
        "worth-store-physical-backend/recovery-media/admitted",
        "phase-2",
    ),
    (
        "AdmittedRecoveryFilesystemMedia::media_generation",
        "worth-store-physical-backend/recovery-media/admitted",
        "phase-2",
    ),
    (
        "AdmittedRecoveryFilesystemMedia::scheduler_capability_claim",
        "worth-store-physical-backend/recovery-media/admitted",
        "phase-2",
    ),
    (
        "AdmittedRecoveryFilesystemMedia::handle_observation",
        "worth-store-physical-backend/recovery-media/admitted",
        "phase-5",
    ),
    (
        "RecoveryMediaHandleObservation",
        "worth-store-physical-backend/recovery-media/admitted",
        "phase-5",
    ),
    (
        "RecoveryMediaHandleObservation::excess_over",
        "worth-store-physical-backend/recovery-media/admitted",
        "phase-5",
    ),
    (
        "RecoveryMediaHandleObservation::live_directory_handles",
        "worth-store-physical-backend/recovery-media/admitted",
        "phase-5",
    ),
    (
        "RecoveryMediaHandleObservation::live_file_handles",
        "worth-store-physical-backend/recovery-media/admitted",
        "phase-5",
    ),
    (
        "BoundedRecoveryFilesystemDiscovery",
        "worth-store-physical-backend/recovery-media/discovery",
        "phase-2",
    ),
    (
        "BoundedRecoveryFilesystemDiscovery::store_identity",
        "worth-store-physical-backend/recovery-media/discovery",
        "phase-3",
    ),
    (
        "BoundedRecoveryFilesystemDiscovery::read_current_selector",
        "worth-store-physical-backend/recovery-media/discovery",
        "phase-3",
    ),
    (
        "BoundedRecoveryFilesystemDiscovery::read_previous_selector",
        "worth-store-physical-backend/recovery-media/discovery",
        "phase-3",
    ),
    (
        "BoundedRecoveryFilesystemDiscovery::read_root_manifest",
        "worth-store-physical-backend/recovery-media/discovery",
        "phase-3",
    ),
    (
        "BoundedRecoveryFilesystemDiscovery::read_root_routing_block",
        "worth-store-physical-backend/recovery-media/discovery",
        "phase-3",
    ),
    (
        "BoundedRecoveryFilesystemDiscovery::read_current_checkpoint",
        "worth-store-physical-backend/recovery-media/discovery",
        "phase-3",
    ),
    (
        "BoundedRecoveryFilesystemDiscovery::read_bootstrap_catalog",
        "worth-store-physical-backend/recovery-media/discovery",
        "phase-3",
    ),
    (
        "BoundedRecoveryFilesystemDiscovery::read_wal_artifacts",
        "worth-store-physical-backend/recovery-media/discovery",
        "phase-3",
    ),
    (
        "BoundedRecoveryFilesystemDiscovery::counters",
        "worth-store-physical-backend/recovery-media/discovery",
        "phase-3",
    ),
    (
        "BoundedRecoveryFilesystemDiscovery::finish",
        "worth-store-physical-backend/recovery-media/discovery",
        "phase-3",
    ),
    (
        "ObservedRecoveryArtifact",
        "worth-store-physical-backend/recovery-media/discovery",
        "phase-3",
    ),
    (
        "ObservedRecoveryArtifact::bytes",
        "worth-store-physical-backend/recovery-media/discovery",
        "phase-3",
    ),
    (
        "ObservedRecoveryArtifact::into_bytes",
        "worth-store-physical-backend/recovery-media/discovery",
        "phase-3",
    ),
    (
        "ObservedWalArtifact",
        "worth-store-physical-backend/recovery-media/discovery",
        "phase-3",
    ),
    (
        "ObservedWalArtifact::name",
        "worth-store-physical-backend/recovery-media/discovery",
        "phase-3",
    ),
    (
        "ObservedWalArtifact::entry_type",
        "worth-store-physical-backend/recovery-media/discovery",
        "phase-3",
    ),
    (
        "ObservedWalArtifact::bytes",
        "worth-store-physical-backend/recovery-media/discovery",
        "phase-3",
    ),
    (
        "RecoveryDiscoveryCounters",
        "worth-store-physical-backend/recovery-media/discovery",
        "phase-3",
    ),
    (
        "RecoveryDiscoveryFailure",
        "worth-store-physical-backend/recovery-media/discovery",
        "phase-3",
    ),
    (
        "RecoveryDiscoveryByteLimitScope",
        "worth-store-physical-backend/recovery-media/discovery",
        "phase-3",
    ),
    (
        "RecoveryDiscoveryArtifact",
        "worth-store-physical-backend/recovery-media/discovery/artifact",
        "phase-3",
    ),
    (
        "CompletedRecoveryStagingWrite",
        "worth-store-physical-backend/recovery-media/staging",
        "phase-5",
    ),
    (
        "CompletedRecoveryStagingWrite::artifact",
        "worth-store-physical-backend/recovery-media/staging",
        "phase-5",
    ),
    (
        "CompletedRecoveryStagingWrite::coordinate",
        "worth-store-physical-backend/recovery-media/staging",
        "phase-5",
    ),
    (
        "CompletedRecoveryStagingWrite::byte_count",
        "worth-store-physical-backend/recovery-media/staging",
        "phase-5",
    ),
    (
        "CompletedRecoveryStagingWrite::disposition",
        "worth-store-physical-backend/recovery-media/staging",
        "phase-5",
    ),
    (
        "CompletedRecoveryStagingWrite::payload_digest",
        "worth-store-physical-backend/recovery-media/staging",
        "phase-5",
    ),
    (
        "CompletedRecoveryStagingWrite::created",
        "worth-store-physical-backend/recovery-media/staging",
        "phase-5",
    ),
    (
        "CompletedRecoveryStagingWrite::verified",
        "worth-store-physical-backend/recovery-media/staging",
        "phase-5",
    ),
    (
        "RecoveryStagingWriteDisposition",
        "worth-store-physical-backend/recovery-media/staging",
        "phase-5",
    ),
    (
        "RecoveryStagingWriteOutcome",
        "worth-store-physical-backend/recovery-media/staging",
        "phase-5",
    ),
    (
        "AdmittedRecoveryFilesystemMedia::mutation_owner_observation",
        "worth-store-physical-backend/recovery-media/admitted",
        "phase-5",
    ),
    (
        "AdmittedRecoveryFilesystemMedia::stage_recovery_artifact_scheduled",
        "worth-store-physical-backend/recovery-media/staging",
        "phase-5",
    ),
    (
        "AdmittedRecoveryFilesystemMedia::synchronize_recovery_artifact_scheduled",
        "worth-store-physical-backend/recovery-media/staging",
        "phase-5",
    ),
    (
        "CompletedScheduledRecoveryStagingSynchronization",
        "worth-store-physical-backend/recovery-media/staging",
        "phase-5",
    ),
    (
        "CompletedScheduledRecoveryStagingSynchronization::physical",
        "worth-store-physical-backend/recovery-media/staging",
        "phase-5",
    ),
    (
        "CompletedScheduledRecoveryStagingSynchronization::queue",
        "worth-store-physical-backend/recovery-media/staging",
        "phase-5",
    ),
    (
        "CompletedScheduledRecoveryStagingWrite",
        "worth-store-physical-backend/recovery-media/staging",
        "phase-5",
    ),
    (
        "CompletedScheduledRecoveryStagingWrite::physical",
        "worth-store-physical-backend/recovery-media/staging",
        "phase-5",
    ),
    (
        "CompletedScheduledRecoveryStagingWrite::queue",
        "worth-store-physical-backend/recovery-media/staging",
        "phase-5",
    ),
    (
        "DeniedScheduledRecoveryStagingWrite",
        "worth-store-physical-backend/recovery-media/staging",
        "phase-5",
    ),
    (
        "DeniedScheduledRecoveryStagingWrite::failure",
        "worth-store-physical-backend/recovery-media/staging",
        "phase-5",
    ),
    (
        "DeniedScheduledRecoveryStagingWrite::queue",
        "worth-store-physical-backend/recovery-media/staging",
        "phase-5",
    ),
    (
        "IndeterminateRecoveryStagingWrite",
        "worth-store-physical-backend/recovery-media/staging",
        "phase-5",
    ),
    (
        "IndeterminateRecoveryStagingWrite::artifact",
        "worth-store-physical-backend/recovery-media/staging",
        "phase-5",
    ),
    (
        "IndeterminateRecoveryStagingWrite::into_physical",
        "worth-store-physical-backend/recovery-media/staging",
        "phase-5",
    ),
    (
        "IndeterminateRecoveryStagingWrite::physical",
        "worth-store-physical-backend/recovery-media/staging",
        "phase-5",
    ),
    (
        "IndeterminateScheduledRecoveryStagingSynchronization",
        "worth-store-physical-backend/recovery-media/staging",
        "phase-5",
    ),
    (
        "IndeterminateScheduledRecoveryStagingSynchronization::physical",
        "worth-store-physical-backend/recovery-media/staging",
        "phase-5",
    ),
    (
        "IndeterminateScheduledRecoveryStagingSynchronization::queue",
        "worth-store-physical-backend/recovery-media/staging",
        "phase-5",
    ),
    (
        "IndeterminateScheduledRecoveryStagingWrite",
        "worth-store-physical-backend/recovery-media/staging",
        "phase-5",
    ),
    (
        "IndeterminateScheduledRecoveryStagingWrite::physical",
        "worth-store-physical-backend/recovery-media/staging",
        "phase-5",
    ),
    (
        "IndeterminateScheduledRecoveryStagingWrite::queue",
        "worth-store-physical-backend/recovery-media/staging",
        "phase-5",
    ),
    (
        "RecoveryStagingSynchronizationOutcome",
        "worth-store-physical-backend/recovery-media/staging",
        "phase-5",
    ),
    (
        "ArtifactTreePublicationEffect::is_file_synchronization",
        "worth-store-physical-backend/filesystem-media/artifact-tree/publication-effect/outcome",
        "phase-5",
    ),
];
