pub(super) const BACKEND_RECOVERY_PUBLICATION_SURFACES: &[(&str, &str, &str)] = &[
    (
        "RecoveryRootProtocolPublicationDenial",
        "worth-store-physical-backend/recovery-media/publication",
        "phase-6",
    ),
    (
        "RecoveryRootProtocolPublicationPlan",
        "worth-store-physical-backend/recovery-media/publication",
        "phase-6",
    ),
    (
        "RecoveryRootProtocolPublicationPlan::from_catalog_candidate",
        "worth-store-physical-backend/recovery-media/publication",
        "phase-6",
    ),
    (
        "RecoveryRootProtocolPublicationPlan::publication",
        "worth-store-physical-backend/recovery-media/publication",
        "phase-6",
    ),
    (
        "RecoveryRootProtocolPublicationPlan::previous_candidate",
        "worth-store-physical-backend/recovery-media/publication",
        "phase-6",
    ),
    (
        "RecoveryRootProtocolPublicationPlan::current_candidate",
        "worth-store-physical-backend/recovery-media/publication",
        "phase-6",
    ),
    (
        "RecoveryRootProtocolPublicationPlan::catalog_candidate",
        "worth-store-physical-backend/recovery-media/publication",
        "phase-6",
    ),
    (
        "AdmittedRecoveryFilesystemMedia::replace_recovery_root_protocol_scheduled",
        "worth-store-physical-backend/recovery-media/publication",
        "phase-6",
    ),
    (
        "AdmittedRecoveryFilesystemMedia::synchronize_recovery_record_namespace_scheduled",
        "worth-store-physical-backend/recovery-media/publication",
        "phase-6",
    ),
];
