pub(super) const BACKEND_RECOVERY_EVIDENCE_SURFACES: &[(&str, &str, &str)] = &[
    (
        "ArtifactTreeFailure::recovery_damaged",
        "worth-store-physical-backend/filesystem-media/artifact-tree/failure",
        "phase-7",
    ),
    (
        "CompletedRecoveryStagingWrite::appended",
        "worth-store-physical-backend/recovery-media/staging",
        "phase-5",
    ),
    (
        "CompletedRecoveryStagingWrite::prefix_verified",
        "worth-store-physical-backend/recovery-media/staging",
        "phase-5",
    ),
    (
        "IndeterminateRecoveryStagingWrite::evidence",
        "worth-store-physical-backend/recovery-media/staging",
        "phase-5",
    ),
    (
        "IndeterminateRecoveryStagingWrite::payload_digest",
        "worth-store-physical-backend/recovery-media/staging",
        "phase-5",
    ),
    (
        "RecoveryStagingIndeterminatePhysical",
        "worth-store-physical-backend/recovery-media/staging",
        "phase-5",
    ),
];
