pub(super) const STORE_RECOVERY_PUBLICATION_SURFACES: &[(&str, &str, &str)] = &[
    (
        "CompletedPhysicalRecoveryPublicationCommand",
        "worth-store/recovery-coordination/publication",
        "phase-6",
    ),
    (
        "CompletedPhysicalRecoveryPublicationCommand::record_namespace",
        "worth-store/recovery-coordination/publication",
        "phase-6",
    ),
    (
        "CompletedPhysicalRecoveryPublicationCommand::root_protocol",
        "worth-store/recovery-coordination/publication",
        "phase-6",
    ),
    (
        "PhysicalRecoveryCoordination::execute_publication_command",
        "worth-store/recovery-coordination/publication",
        "phase-6",
    ),
    (
        "PhysicalRecoveryPublicationCommand",
        "worth-store/recovery-coordination/publication",
        "phase-6",
    ),
    (
        "PhysicalRecoveryPublicationCommand::new",
        "worth-store/recovery-coordination/publication",
        "phase-6",
    ),
    (
        "PhysicalRecoveryPublicationCommandDenial",
        "worth-store/recovery-coordination/publication",
        "phase-6",
    ),
    (
        "PhysicalRecoveryPublicationCommandDenial::denial",
        "worth-store/recovery-coordination/publication",
        "phase-6",
    ),
    (
        "PhysicalRecoveryPublicationCommandDenial::root_protocol",
        "worth-store/recovery-coordination/publication",
        "phase-6",
    ),
    (
        "PhysicalRecoveryPublicationCommandDenial::scheduler_posture",
        "worth-store/recovery-coordination/publication",
        "phase-6",
    ),
    (
        "PhysicalRecoveryPublicationCommandDenial::stage",
        "worth-store/recovery-coordination/publication",
        "phase-6",
    ),
    (
        "PhysicalRecoveryPublicationCommandDenialKind",
        "worth-store/recovery-coordination/publication",
        "phase-6",
    ),
    (
        "PhysicalRecoveryPublicationCommandIndeterminate",
        "worth-store/recovery-coordination/publication",
        "phase-6",
    ),
    (
        "PhysicalRecoveryPublicationCommandOutcome",
        "worth-store/recovery-coordination/publication",
        "phase-6",
    ),
    (
        "PhysicalRecoveryPublicationCommandStage",
        "worth-store/recovery-coordination/publication",
        "phase-6",
    ),
    (
        "RecoveryPublicationOccurrence",
        "worth-store/recovery-coordination/effect",
        "phase-6",
    ),
    (
        "RecoveryPublicationOccurrence::physical",
        "worth-store/recovery-coordination/effect",
        "phase-6",
    ),
    (
        "RecoveryPublicationOccurrence::plan",
        "worth-store/recovery-coordination/effect",
        "phase-6",
    ),
    (
        "RecoveryPublicationOccurrence::publication",
        "worth-store/recovery-coordination/effect",
        "phase-6",
    ),
    (
        "RecoveryPublicationOccurrence::scheduler",
        "worth-store/recovery-coordination/effect",
        "phase-6",
    ),
    (
        "RecoveryPublicationOccurrence::session",
        "worth-store/recovery-coordination/effect",
        "phase-6",
    ),
    (
        "RecoveryPublicationOccurrence::signal",
        "worth-store/recovery-coordination/effect",
        "phase-6",
    ),
    (
        "RecoveryPublicationOccurrence::staging_generation",
        "worth-store/recovery-coordination/effect",
        "phase-6",
    ),
    (
        "RecoveryPublicationOccurrence::work",
        "worth-store/recovery-coordination/effect",
        "phase-6",
    ),
    (
        "RecoveryRecordNamespaceSynchronizationAction",
        "worth-store/recovery-coordination/effect",
        "phase-6",
    ),
    (
        "RecoveryRootProtocolReplacementAction",
        "worth-store/recovery-coordination/effect",
        "phase-6",
    ),
];
