pub(super) const STORE_RECOVERY_COORDINATION_SURFACES: &[(&str, &str, &str)] = &[
    (
        "PhysicalRecoveryCoordinationCapacity",
        "worth-store/recovery-coordination/capacity",
        "phase-2",
    ),
    (
        "PhysicalRecoveryCoordinationCapacity::admit",
        "worth-store/recovery-coordination/capacity",
        "phase-2",
    ),
    (
        "PhysicalRecoveryCoordination",
        "worth-store/recovery-coordination/owner",
        "phase-2",
    ),
    (
        "PhysicalRecoveryCoordination::is_ready",
        "worth-store/recovery-coordination/owner",
        "phase-2",
    ),
    (
        "PhysicalRecoveryCoordination::shutdown_is_quiescent",
        "worth-store/recovery-coordination/owner",
        "phase-2",
    ),
    (
        "PhysicalRecoveryCoordinationAdmissionError",
        "worth-store/recovery-coordination/owner",
        "phase-2",
    ),
    (
        "PhysicalRecoveryRegisteredSessionAuthority::admit_coordination",
        "worth-store/recovery-coordination/owner",
        "phase-2",
    ),
    (
        "CompletedPhysicalRecoveryStagingCommand",
        "worth-store/recovery-coordination/staging",
        "phase-5",
    ),
    (
        "CompletedPhysicalRecoveryStagingCommand::materialization",
        "worth-store/recovery-coordination/staging",
        "phase-5",
    ),
    (
        "CompletedPhysicalRecoveryStagingCommand::synchronization",
        "worth-store/recovery-coordination/staging",
        "phase-5",
    ),
    (
        "PhysicalRecoveryCoordination::execute_staging_command",
        "worth-store/recovery-coordination/staging",
        "phase-5",
    ),
    (
        "PhysicalRecoveryCoordination::quiescence_observation",
        "worth-store/recovery-coordination/owner",
        "phase-5",
    ),
    (
        "PhysicalRecoveryQuiescenceObservation",
        "worth-store/recovery-coordination/owner",
        "phase-5",
    ),
    (
        "PhysicalRecoveryQuiescenceObservation::live_commands",
        "worth-store/recovery-coordination/owner",
        "phase-5",
    ),
    (
        "PhysicalRecoveryQuiescenceObservation::live_scheduler_reservations",
        "worth-store/recovery-coordination/owner",
        "phase-5",
    ),
    (
        "PhysicalRecoveryQuiescenceObservation::pending_signal_reconciliations",
        "worth-store/recovery-coordination/owner",
        "phase-5",
    ),
    (
        "PhysicalRecoveryQuiescenceObservation::signal_available",
        "worth-store/recovery-coordination/owner",
        "phase-5",
    ),
    (
        "PhysicalRecoveryQuiescenceObservation::signal_reconciliation_overflow",
        "worth-store/recovery-coordination/owner",
        "phase-5",
    ),
    (
        "PhysicalRecoveryStagingCommand",
        "worth-store/recovery-coordination/staging",
        "phase-5",
    ),
    (
        "PhysicalRecoveryStagingCommand::new",
        "worth-store/recovery-coordination/staging",
        "phase-5",
    ),
    (
        "PhysicalRecoveryStagingCommandDenial",
        "worth-store/recovery-coordination/staging",
        "phase-5",
    ),
    (
        "PhysicalRecoveryStagingCommandDenial::denial",
        "worth-store/recovery-coordination/staging",
        "phase-5",
    ),
    (
        "PhysicalRecoveryStagingCommandDenial::materialization",
        "worth-store/recovery-coordination/staging",
        "phase-5",
    ),
    (
        "PhysicalRecoveryStagingCommandDenial::scheduler_posture",
        "worth-store/recovery-coordination/staging",
        "phase-5",
    ),
    (
        "PhysicalRecoveryStagingCommandDenial::stage",
        "worth-store/recovery-coordination/staging",
        "phase-5",
    ),
    (
        "PhysicalRecoveryStagingCommandDenialKind",
        "worth-store/recovery-coordination/staging",
        "phase-5",
    ),
    (
        "PhysicalRecoveryStagingCommandIndeterminate",
        "worth-store/recovery-coordination/staging",
        "phase-5",
    ),
    (
        "PhysicalRecoveryStagingCommandIndeterminate::scheduler_posture",
        "worth-store/recovery-coordination/staging",
        "phase-5",
    ),
    (
        "PhysicalRecoveryStagingCommandOutcome",
        "worth-store/recovery-coordination/staging",
        "phase-5",
    ),
    (
        "PhysicalRecoveryStagingCommandStage",
        "worth-store/recovery-coordination/staging",
        "phase-5",
    ),
    (
        "PhysicalRecoveryStagingMaterialization",
        "worth-store/recovery-coordination/staging",
        "phase-5",
    ),
    (
        "PhysicalRecoveryStagingMaterialization::physical",
        "worth-store/recovery-coordination/staging",
        "phase-5",
    ),
    (
        "PhysicalRecoveryStagingMaterializationEvidence",
        "worth-store/recovery-coordination/staging",
        "phase-5",
    ),
    (
        "PhysicalRecoveryStagingMaterializationEvidence::physical",
        "worth-store/recovery-coordination/staging",
        "phase-5",
    ),
    (
        "PhysicalRecoveryStagingMaterializationEvidence::is_performed",
        "worth-store/recovery-coordination/staging",
        "phase-5",
    ),
    (
        "PerformedRecoveryPhysicalEffect",
        "worth-store/recovery-coordination/effect",
        "phase-5",
    ),
    (
        "PerformedRecoveryPhysicalEffect::into_occurrence",
        "worth-store/recovery-coordination/effect",
        "phase-5",
    ),
    (
        "PerformedRecoveryPhysicalEffect::occurrence",
        "worth-store/recovery-coordination/effect",
        "phase-5",
    ),
    (
        "RecoveryPhysicalEffectOccurrence",
        "worth-store/recovery-coordination/effect",
        "phase-5",
    ),
    (
        "RecoveryStagingSynchronizationAction",
        "worth-store/recovery-coordination/effect",
        "phase-5",
    ),
    (
        "RecoveryStagingSynchronizationOccurrence",
        "worth-store/recovery-coordination/effect",
        "phase-5",
    ),
    (
        "RecoveryStagingSynchronizationOccurrence::command_ordinal",
        "worth-store/recovery-coordination/effect",
        "phase-5",
    ),
    (
        "RecoveryStagingSynchronizationOccurrence::physical",
        "worth-store/recovery-coordination/effect",
        "phase-5",
    ),
    (
        "RecoveryStagingSynchronizationOccurrence::plan",
        "worth-store/recovery-coordination/effect",
        "phase-5",
    ),
    (
        "RecoveryStagingSynchronizationOccurrence::scheduler",
        "worth-store/recovery-coordination/effect",
        "phase-5",
    ),
    (
        "RecoveryStagingSynchronizationOccurrence::session",
        "worth-store/recovery-coordination/effect",
        "phase-5",
    ),
    (
        "RecoveryStagingSynchronizationOccurrence::signal",
        "worth-store/recovery-coordination/effect",
        "phase-5",
    ),
    (
        "RecoveryStagingSynchronizationOccurrence::staging_generation",
        "worth-store/recovery-coordination/effect",
        "phase-5",
    ),
    (
        "RecoveryStagingSynchronizationOccurrence::work",
        "worth-store/recovery-coordination/effect",
        "phase-5",
    ),
    (
        "RecoveryStagingWriteAction",
        "worth-store/recovery-coordination/effect",
        "phase-5",
    ),
    (
        "RecoveryStagingWriteOccurrence",
        "worth-store/recovery-coordination/effect",
        "phase-5",
    ),
    (
        "RecoveryStagingWriteOccurrence::command_ordinal",
        "worth-store/recovery-coordination/effect",
        "phase-5",
    ),
    (
        "RecoveryStagingWriteOccurrence::physical",
        "worth-store/recovery-coordination/effect",
        "phase-5",
    ),
    (
        "RecoveryStagingWriteOccurrence::plan",
        "worth-store/recovery-coordination/effect",
        "phase-5",
    ),
    (
        "RecoveryStagingWriteOccurrence::scheduler",
        "worth-store/recovery-coordination/effect",
        "phase-5",
    ),
    (
        "RecoveryStagingWriteOccurrence::session",
        "worth-store/recovery-coordination/effect",
        "phase-5",
    ),
    (
        "RecoveryStagingWriteOccurrence::signal",
        "worth-store/recovery-coordination/effect",
        "phase-5",
    ),
    (
        "RecoveryStagingWriteOccurrence::staging_generation",
        "worth-store/recovery-coordination/effect",
        "phase-5",
    ),
    (
        "RecoveryStagingWriteOccurrence::work",
        "worth-store/recovery-coordination/effect",
        "phase-5",
    ),
];
