#[test]
fn spatial_public_boundary_rejects_internal_constructor_bypass() {
    let t = trybuild::TestCases::new();
    let compile_fail = "src/certification/public_facade_contracts/compile_fail";
    macro_rules! cf {
        ($case:literal) => {
            t.compile_fail(format!("{compile_fail}/{}", $case));
        };
    }
    cf!("public_spatial_admitted_witness_request_artifacts_not_exported.rs");
    cf!("public_spatial_top_level_witness_helpers_not_exported.rs");
    cf!("public_spatial_top_level_refs_not_exported.rs");
    cf!("public_spatial_top_level_lowering_runtime_products_not_exported.rs");
    cf!("public_spatial_top_level_arbitration_runtime_products_not_exported.rs");
    cf!("public_spatial_policy_namespace_not_exported.rs");
    cf!("public_spatial_arbitration_namespace_not_exported.rs");
    cf!("public_spatial_birth_namespace_not_exported.rs");
    t.compile_fail(format!(
        "{compile_fail}/public_spatial_binding_birth_comparison_helpers_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_spatial_binding_birth_assessment_helpers_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_spatial_binding_birth_materialization_helper_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_spatial_binding_birth_materialization_runtime_products_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_spatial_binding_birth_scaffold_input_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_spatial_preview_and_continuity_helpers_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_spatial_top_level_bindings_report_products_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_spatial_lowering_namespace_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_spatial_flat_semantic_facade_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_spatial_frame_admission_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_spatial_witness_resolution_namespace_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_spatial_support_namespace_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_spatial_placement_no_catalog_helpers_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_spatial_anchor_selection_no_catalog_helpers_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_spatial_anchor_selection_lowering_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_spatial_test_support_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_spatial_raw_binding_authority_carriers_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/public_spatial_geometry_intent_family_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/planar_admission/receipt_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/planar_boolean_common_plane/receipt_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/planar_boolean_common_plane/shared_plane_identity_receipt_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/planar_boolean_common_plane/local_frame_selection_receipt_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/planar_boolean_common_plane/operand_projection_consumption_receipt_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/planar_boolean_events/segment_carrier_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/planar_boolean_events/segment_carrier_set_not_from_coordinate_segments.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/planar_boolean_events/canonical_segment_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/planar_boolean_events/canonical_segment_set_not_from_coordinate_segments.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/planar_boolean_events/normalized_endpoint_pair_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/planar_boolean_events/endpoint_order_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/planar_boolean_events/segment_pair_work_item_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/planar_boolean_events/candidate_row_receipt_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/planar_boolean_events/candidate_index_product_not_from_raw_rows.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/planar_boolean_events/segment_pair_enumeration_receipt_not_from_raw_pairs.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/planar_boolean_events/predicate_bound_pair_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/planar_boolean_events/event_predicate_binding_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/planar_boolean_events/event_classifier_requires_predicate_binding_context.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/planar_boolean_events/event_classifier_input_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/planar_boolean_events/point_event_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/planar_boolean_events/point_event_coordinate_fact_not_from_raw_coordinates.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/planar_boolean_events/point_event_extraction_receipt_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/planar_boolean_events/interval_event_receipt_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/planar_boolean_events/event_group_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/planar_boolean_events/event_ledger_receipt_not_forgeable.rs"
    ));
    cf!("planar_boolean_edge_splitting/candidate_index_consumption_gate_not_forgeable.rs");
    cf!("planar_boolean_edge_splitting/edge_split_request_not_forgeable.rs");
    cf!("planar_boolean_edge_splitting/edge_split_request_not_from_raw_split_inputs.rs");
    cf!("planar_boolean_edge_splitting/split_scope_admission_not_forgeable.rs");
    cf!("planar_boolean_edge_splitting/split_scope_admission_not_from_raw_events.rs");
    cf!("planar_boolean_edge_splitting/split_scope_admission_not_boolean_evidence_receipt.rs");
    cf!("planar_boolean_edge_splitting/source_edge_carrier_not_forgeable.rs");
    cf!("planar_boolean_edge_splitting/source_edge_carrier_set_not_forgeable.rs");
    cf!("planar_boolean_edge_splitting/source_edge_carrier_recovery_not_from_raw_carriers.rs");
    cf!("planar_boolean_edge_splitting/participation_index_not_forgeable.rs");
    cf!("planar_boolean_edge_splitting/participation_row_not_from_raw_strings.rs");
    cf!("planar_boolean_edge_splitting/point_split_candidate_not_forgeable.rs");
    cf!("planar_boolean_edge_splitting/admitted_point_split_candidate_not_forgeable.rs");
    cf!("planar_boolean_edge_splitting/admitted_point_split_candidate_set_not_forgeable.rs");
    cf!("planar_boolean_edge_splitting/postured_point_split_candidate_not_forgeable.rs");
    cf!("planar_boolean_edge_splitting/raw_edge_split_schedule_not_forgeable.rs");
    cf!("planar_boolean_edge_splitting/ordered_edge_split_schedule_not_forgeable.rs");
    cf!("planar_boolean_edge_splitting/duplicate_split_cut_key_not_public.rs");
    cf!("planar_boolean_edge_splitting/normalized_split_cut_not_forgeable.rs");
    cf!("planar_boolean_edge_splitting/normalized_edge_split_schedule_not_forgeable.rs");
    cf!("planar_boolean_edge_splitting/normalized_edge_split_schedule_set_not_forgeable.rs");
    cf!("planar_boolean_edge_splitting/endpoint_contact_decision_not_forgeable.rs");
    cf!("planar_boolean_edge_splitting/endpoint_boundary_normalized_schedule_not_forgeable.rs");
    cf!("planar_boolean_edge_splitting/endpoint_boundary_normalized_schedule_set_not_forgeable.rs");
    cf!("planar_boolean_edge_splitting/retained_interval_split_entry_not_forgeable.rs");
    cf!("planar_boolean_edge_splitting/normalized_interval_subdivision_row_not_forgeable.rs");
    cf!("planar_boolean_edge_splitting/interval_subdivision_normalized_schedule_set_not_forgeable.rs");
    cf!("planar_boolean_edge_splitting/split_vertex_identity_not_forgeable.rs");
    cf!("planar_boolean_edge_splitting/split_vertex_identity_set_not_forgeable.rs");
    cf!("planar_boolean_edge_splitting/split_edge_fragment_not_forgeable.rs");
    cf!("planar_boolean_edge_splitting/split_edge_fragment_set_not_forgeable.rs");
    cf!("planar_boolean_edge_splitting/fragment_endpoint_ref_not_hand_filled.rs");
    cf!("planar_boolean_edge_splitting/overlap_edge_chain_member_not_forgeable.rs");
    cf!("planar_boolean_edge_splitting/overlap_edge_chain_not_forgeable.rs");
    cf!("planar_boolean_edge_splitting/overlap_edge_chain_set_not_forgeable.rs");
    cf!("planar_boolean_edge_splitting/split_chain_validation_receipt_not_forgeable.rs");
    cf!("planar_boolean_edge_splitting/split_fragment_coverage_row_not_forgeable.rs");
    cf!("planar_boolean_edge_splitting/overlap_chain_coverage_row_not_forgeable.rs");
    cf!("planar_boolean_edge_splitting/coordinate_only_split_vertex_identity_rejected.rs");
    cf!("planar_boolean_edge_splitting/interval_split_candidate_not_forgeable.rs");
    cf!("planar_boolean_edge_splitting/interval_split_candidate_set_not_forgeable.rs");
    cf!("planar_boolean_edge_splitting/admitted_interval_split_candidate_not_forgeable.rs");
    cf!("planar_boolean_edge_splitting/admitted_interval_split_candidate_set_not_forgeable.rs");
    cf!("planar_predicate/receipt_not_forgeable.rs");
    cf!("planar_precision/receipt_not_forgeable.rs");
    cf!("planar_local_frame/receipt_not_forgeable.rs");
    t.compile_fail(format!(
        "{compile_fail}/planar_projection/receipt_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/planar_segment_segment/receipt_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/planar_winding/receipt_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/planar_signed_area/receipt_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/planar_overlap/receipt_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/planar_contract_bundle/receipt_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/planar_contract_bundle/m7_readiness_receipt_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/planar_predicate_consumption/receipt_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/planar_structural_identity/receipt_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/planar_motion_posture/receipt_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/planar_topology_contract/receipt_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/planar_retained_facts/receipt_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/planar_projection_consumption/receipt_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/planar_recovery/receipt_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/planar_diagnostics/receipt_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/planar_local_rebuild_parity/receipt_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/planar_clean_fail_boundary/receipt_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/planar_m6_closeout/receipt_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/planar_m6_closeout/hand_filled_premetaboss_evidence_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/planar_m6_closeout/generic_ledger_premetaboss_target_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/planar_m6_closeout/readiness_summary_premetaboss_target_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/workload_vocabulary/out_of_order_phase_transition.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/workload_vocabulary/evidence_ledger_complete_not_hand_filled.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/workload_vocabulary/evidence_stage_index_product_not_hand_filled.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/workload_operators/coplanar_overlap_operator_not_from_raw_evidence_rows.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/workload_operators/operator_stage_links_not_hand_filled.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/geometry_binding_workload/bound_workload_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/surface_support_workload/certified_plane_support_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/surface_support_workload/unsupported_surface_receipt_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/surface_support_workload/unsupported_surface_not_projectable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/projection_workload/projected_workload_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/projection_workload/loose_points_not_operator_projection.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/projection_workload/unsupported_surface_not_projection_workload.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/projection_workload/projection_consumption_receipt_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/workload_certification_context/context_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/workload_certification_context/raw_strings_do_not_build_context.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/workload_certification_context/loose_projected_overlap_contracts_not_public.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/workload_certification_context/raw_motion_adversary_string_not_accepted.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/nmt_certification_context/context_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/nmt_certification_context/projection_receipt_not_from_raw_coordinates.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/nmt_certification_context/retained_receipt_not_from_aggregate_replay.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/nmt_certification_context/boss_closeout_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/transform_workload/transformed_workload_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/transform_workload/label_motion_not_transform_evidence.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/transform_workload/transform_posture_receipt_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/retained_replay_workload/replayed_workload_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/retained_replay_workload/replay_receipt_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/retained_replay_workload/retained_artifact_set_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/retained_replay_workload/capture_receipt_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/user_response/user_outcome_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/user_response/user_response_receipt_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/user_response/user_response_source_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/coplanar_overlap_storm/storm_receipt_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/projected_overlap_faces/certified_face_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/projected_overlap_faces/certified_pair_not_from_raw_coordinates.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/projected_overlap_faces/candidate_pair_snapshot_not_exported.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/projected_overlap_faces/bridge_authority_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/blocker_provenance/receipt_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/blocker_provenance/generic_unsupported_surface_provenance_not_public.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/projection_policy_choice/receipt_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/high_valence_singularity/receipt_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/thin_feature_scale_separation/receipt_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/retained_cancellation_chain/receipt_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/dirty_planar_clean_fail/receipt_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/open_planar_posture/receipt_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/projection_fact_parity/receipt_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/boolean_readiness_workload/receipt_not_forgeable.rs"
    ));
    t.compile_fail(format!(
        "{compile_fail}/grazing_basket_stack/receipt_not_forgeable.rs"
    ));
}
