use super::{ForgeQueryLowerRuntimePublicSurfaceKind, ForgeQueryLowerRuntimePublicSurfaceRow};
use crate::lower_runtime_routing::ForgeQueryLowerRuntimeSeamKey;

pub(super) const PUBLIC_SURFACE_ROWS: &[ForgeQueryLowerRuntimePublicSurfaceRow] = &[
    ForgeQueryLowerRuntimePublicSurfaceRow::new(
        ForgeQueryLowerRuntimeSeamKey::RuntimeBackendBoundaryModules,
        "ForgeQueryRuntime backend boundary modules",
        "crates/forge-query/src/runtime/backend/*",
        ForgeQueryLowerRuntimePublicSurfaceKind::AllowedBoundaryAdapter,
        "canonical backend boundary hub for live declaration, source, preview, write, signal, activation, and intent adapter contracts",
    ),
    ForgeQueryLowerRuntimePublicSurfaceRow::new(
        ForgeQueryLowerRuntimeSeamKey::ComposeRead,
        "ForgeQueryWorkspace::compose_read(...)",
        "crates/forge-query/src/runtime/workspace_queries.rs",
        ForgeQueryLowerRuntimePublicSurfaceKind::PublicFacade,
        "read-family intent execution",
    ),
    ForgeQueryLowerRuntimePublicSurfaceRow::new(
        ForgeQueryLowerRuntimeSeamKey::ComposeReadWithInvariantPack,
        "ForgeQueryWorkspace::compose_read_with_invariant_pack(...)",
        "crates/forge-query/src/runtime/workspace_queries.rs",
        ForgeQueryLowerRuntimePublicSurfaceKind::PublicFacade,
        "read-family intent execution after invariant admission",
    ),
    ForgeQueryLowerRuntimePublicSurfaceRow::new(
        ForgeQueryLowerRuntimeSeamKey::ExecuteReadFamily,
        "ForgeQueryWorkspace::execute_read_family(...)",
        "crates/forge-query/src/runtime/workspace_queries.rs",
        ForgeQueryLowerRuntimePublicSurfaceKind::PublicFacade,
        "read-family intent execution",
    ),
    ForgeQueryLowerRuntimePublicSurfaceRow::new(
        ForgeQueryLowerRuntimeSeamKey::ExecuteReadFamilyInBasisContext,
        "ForgeQueryWorkspace::execute_read_family_in_basis_context(...)",
        "crates/forge-query/src/runtime/workspace_queries.rs",
        ForgeQueryLowerRuntimePublicSurfaceKind::PublicFacade,
        "basis-context read-family intent execution",
    ),
    ForgeQueryLowerRuntimePublicSurfaceRow::new(
        ForgeQueryLowerRuntimeSeamKey::ExecuteRuntimeCurrentReadGraph,
        "execute_runtime_current_read_graph(...)",
        "crates/forge-query/src/runtime/read_composition_runtime.rs",
        ForgeQueryLowerRuntimePublicSurfaceKind::InternalRouteComposer,
        "current read-family route execution",
    ),
    ForgeQueryLowerRuntimePublicSurfaceRow::new(
        ForgeQueryLowerRuntimeSeamKey::ExecuteRuntimeBasisContextReadGraph,
        "execute_runtime_basis_context_read_graph(...)",
        "crates/forge-query/src/runtime/read_composition_runtime.rs",
        ForgeQueryLowerRuntimePublicSurfaceKind::InternalRouteComposer,
        "basis-context read-family route execution",
    ),
    ForgeQueryLowerRuntimePublicSurfaceRow::new(
        ForgeQueryLowerRuntimeSeamKey::PublicLiveViewDeclaration,
        "ForgeQueryWorkspace::live_view(...)",
        "crates/forge-query/src/runtime/workspace.rs",
        ForgeQueryLowerRuntimePublicSurfaceKind::PublicFacade,
        "workspace live declaration routed through runtime declaration and installation",
    ),
    ForgeQueryLowerRuntimePublicSurfaceRow::new(
        ForgeQueryLowerRuntimeSeamKey::PublicLiveViewDeclaration,
        "ForgeQueryWorkspace::live_view_request(...)",
        "crates/forge-query/src/runtime/workspace.rs",
        ForgeQueryLowerRuntimePublicSurfaceKind::PublicFacade,
        "workspace live declaration routed through runtime declaration and installation",
    ),
    ForgeQueryLowerRuntimePublicSurfaceRow::new(
        ForgeQueryLowerRuntimeSeamKey::PublicLiveViewDeclaration,
        "ForgeQueryRuntime::declare_live_view(...)",
        "crates/forge-query/src/runtime/runtime_declarations.rs",
        ForgeQueryLowerRuntimePublicSurfaceKind::PublicFacade,
        "live declaration receipt plus installation route",
    ),
    ForgeQueryLowerRuntimePublicSurfaceRow::new(
        ForgeQueryLowerRuntimeSeamKey::WriteAuthorityBackendExecution,
        "ForgeQueryWorkspace::write(...)",
        "crates/forge-query/src/runtime/workspace.rs",
        ForgeQueryLowerRuntimePublicSurfaceKind::PublicFacade,
        "authoritative mutation intent execution through write-authority routing",
    ),
    ForgeQueryLowerRuntimePublicSurfaceRow::new(
        ForgeQueryLowerRuntimeSeamKey::WriteAuthorityBackendExecution,
        "ForgeQueryWorkspace::insert(...)",
        "crates/forge-query/src/runtime/workspace.rs",
        ForgeQueryLowerRuntimePublicSurfaceKind::PublicFacade,
        "authoritative mutation intent execution through write-authority routing",
    ),
    ForgeQueryLowerRuntimePublicSurfaceRow::new(
        ForgeQueryLowerRuntimeSeamKey::WriteAuthorityBackendExecution,
        "ForgeQueryWorkspace::update(...)",
        "crates/forge-query/src/runtime/workspace.rs",
        ForgeQueryLowerRuntimePublicSurfaceKind::PublicFacade,
        "authoritative mutation intent execution through write-authority routing",
    ),
    ForgeQueryLowerRuntimePublicSurfaceRow::new(
        ForgeQueryLowerRuntimeSeamKey::WriteAuthorityBackendExecution,
        "ForgeQueryWorkspace::update_existing(...)",
        "crates/forge-query/src/runtime/workspace.rs",
        ForgeQueryLowerRuntimePublicSurfaceKind::PublicFacade,
        "authoritative mutation intent execution after existing-truth binding admission",
    ),
    ForgeQueryLowerRuntimePublicSurfaceRow::new(
        ForgeQueryLowerRuntimeSeamKey::WriteAuthorityBackendExecution,
        "ForgeQueryWorkspace::assert_existing(...)",
        "crates/forge-query/src/runtime/workspace.rs",
        ForgeQueryLowerRuntimePublicSurfaceKind::PublicFacade,
        "authoritative mutation intent execution after existing-truth binding admission",
    ),
    ForgeQueryLowerRuntimePublicSurfaceRow::new(
        ForgeQueryLowerRuntimeSeamKey::WriteAuthorityBackendExecution,
        "ForgeQueryWorkspace::verify_existing(...)",
        "crates/forge-query/src/runtime/workspace.rs",
        ForgeQueryLowerRuntimePublicSurfaceKind::PublicFacade,
        "authoritative mutation intent execution after existing-truth binding admission",
    ),
    ForgeQueryLowerRuntimePublicSurfaceRow::new(
        ForgeQueryLowerRuntimeSeamKey::WriteAuthorityBackendExecution,
        "ForgeQueryWorkspace::update_existing_verified(...)",
        "crates/forge-query/src/runtime/workspace.rs",
        ForgeQueryLowerRuntimePublicSurfaceKind::PublicFacade,
        "authoritative mutation intent execution after backend-verified existing-truth admission",
    ),
    ForgeQueryLowerRuntimePublicSurfaceRow::new(
        ForgeQueryLowerRuntimeSeamKey::WriteAuthorityBackendExecution,
        "ForgeQueryWorkspace::delete(...)",
        "crates/forge-query/src/runtime/workspace.rs",
        ForgeQueryLowerRuntimePublicSurfaceKind::PublicFacade,
        "authoritative mutation intent execution through write-authority routing",
    ),
    ForgeQueryLowerRuntimePublicSurfaceRow::new(
        ForgeQueryLowerRuntimeSeamKey::WriteAuthorityBackendExecution,
        "ForgeQueryWorkspace::delete_with(...)",
        "crates/forge-query/src/runtime/workspace.rs",
        ForgeQueryLowerRuntimePublicSurfaceKind::PublicFacade,
        "authoritative mutation intent execution through write-authority routing",
    ),
    ForgeQueryLowerRuntimePublicSurfaceRow::new(
        ForgeQueryLowerRuntimeSeamKey::WriteAuthorityBackendExecution,
        "ForgeQueryWorkspace::delete_existing(...)",
        "crates/forge-query/src/runtime/workspace.rs",
        ForgeQueryLowerRuntimePublicSurfaceKind::PublicFacade,
        "authoritative mutation intent execution after existing-truth binding admission",
    ),
    ForgeQueryLowerRuntimePublicSurfaceRow::new(
        ForgeQueryLowerRuntimeSeamKey::WriteAuthorityBackendExecution,
        "ForgeQueryWorkspace::delete_existing_with(...)",
        "crates/forge-query/src/runtime/workspace.rs",
        ForgeQueryLowerRuntimePublicSurfaceKind::PublicFacade,
        "authoritative mutation intent execution after existing-truth binding admission",
    ),
    ForgeQueryLowerRuntimePublicSurfaceRow::new(
        ForgeQueryLowerRuntimeSeamKey::WriteAuthorityBackendExecution,
        "ForgeQueryWorkspace::delete_existing_verified(...)",
        "crates/forge-query/src/runtime/workspace.rs",
        ForgeQueryLowerRuntimePublicSurfaceKind::PublicFacade,
        "authoritative mutation intent execution after backend-verified existing-truth admission",
    ),
    ForgeQueryLowerRuntimePublicSurfaceRow::new(
        ForgeQueryLowerRuntimeSeamKey::WriteAuthorityBackendExecution,
        "ForgeQueryRuntime::write(...)",
        "crates/forge-query/src/runtime/runtime_writes.rs",
        ForgeQueryLowerRuntimePublicSurfaceKind::PublicFacade,
        "authoritative mutation intent execution through write-authority routing",
    ),
    ForgeQueryLowerRuntimePublicSurfaceRow::new(
        ForgeQueryLowerRuntimeSeamKey::WriteAuthorityBackendExecution,
        "ForgeQueryRuntime::write_batch(...)",
        "crates/forge-query/src/runtime/runtime_batch_write_entrypoints.rs",
        ForgeQueryLowerRuntimePublicSurfaceKind::PublicFacade,
        "authoritative batch mutation intent execution through write-authority routing",
    ),
    ForgeQueryLowerRuntimePublicSurfaceRow::new(
        ForgeQueryLowerRuntimeSeamKey::WriteAuthorityBackendExecution,
        "ForgeQueryWorkspace::batch(...)",
        "crates/forge-query/src/runtime/workspace.rs",
        ForgeQueryLowerRuntimePublicSurfaceKind::PublicFacade,
        "authoritative batch mutation intent execution through write-authority routing",
    ),
    ForgeQueryLowerRuntimePublicSurfaceRow::new(
        ForgeQueryLowerRuntimeSeamKey::SignalInvalidationRouting,
        "ForgeQueryRuntime::execute_authoritative_write_command_direct(...)",
        "crates/forge-query/src/runtime/runtime_writes.rs",
        ForgeQueryLowerRuntimePublicSurfaceKind::InternalRouteComposer,
        "mutation receipt routing through signal invalidation boundary receipts",
    ),
    ForgeQueryLowerRuntimePublicSurfaceRow::new(
        ForgeQueryLowerRuntimeSeamKey::SignalInvalidationRouting,
        "ForgeQueryRuntime::execute_authoritative_write_batch_direct(...)",
        "crates/forge-query/src/runtime/runtime_batch_writes.rs",
        ForgeQueryLowerRuntimePublicSurfaceKind::InternalRouteComposer,
        "batch mutation receipt routing through signal invalidation boundary receipts",
    ),
    ForgeQueryLowerRuntimePublicSurfaceRow::new(
        ForgeQueryLowerRuntimeSeamKey::RuntimeLiveInstallationOrchestration,
        "ForgeQueryRuntime::install_live_subscription_for_request(...)",
        "crates/forge-query/src/runtime/runtime_sessions.rs",
        ForgeQueryLowerRuntimePublicSurfaceKind::InternalRouteComposer,
        "subscription declaration, lowering, admission, and activation route",
    ),
    ForgeQueryLowerRuntimePublicSurfaceRow::new(
        ForgeQueryLowerRuntimeSeamKey::SubscriptionContinuity,
        "basis-lifecycle bridge continuity readmission",
        "crates/forge-query/src/basis_lifecycle/lower_runtime/mod.rs",
        ForgeQueryLowerRuntimePublicSurfaceKind::InternalRouteComposer,
        "continuity evidence is readmitted through lower-runtime basis binding instead of a side-door runtime lane",
    ),
    ForgeQueryLowerRuntimePublicSurfaceRow::new(
        ForgeQueryLowerRuntimeSeamKey::BasisReadmissionFromTruthViewEvidence,
        "basis readmission from truth-view evidence",
        "crates/forge-query/src/basis_lifecycle/lower_runtime/mod.rs",
        ForgeQueryLowerRuntimePublicSurfaceKind::InternalRouteComposer,
        "truth-view evidence is readmitted through lower-runtime basis binding",
    ),
    ForgeQueryLowerRuntimePublicSurfaceRow::new(
        ForgeQueryLowerRuntimeSeamKey::BasisReadmissionFromSubscriptionEvidence,
        "basis readmission from subscription evidence",
        "crates/forge-query/src/basis_lifecycle/lower_runtime/mod.rs",
        ForgeQueryLowerRuntimePublicSurfaceKind::InternalRouteComposer,
        "subscription evidence is readmitted through lower-runtime basis binding",
    ),
    ForgeQueryLowerRuntimePublicSurfaceRow::new(
        ForgeQueryLowerRuntimeSeamKey::HistoricalBridgeLowering,
        "historical bridge policy lowering adapter",
        "crates/forge-query/src/historical/bridge_lowering.rs",
        ForgeQueryLowerRuntimePublicSurfaceKind::AllowedBoundaryAdapter,
        "historical lowering remains a declared runtime-bridge adapter rather than an untracked direct import site",
    ),
    ForgeQueryLowerRuntimePublicSurfaceRow::new(
        ForgeQueryLowerRuntimeSeamKey::EffectBackedRelationalMutation,
        "effect-backed relational mutation execution",
        "crates/forge-query/src/effect_lifecycle/execution.rs",
        ForgeQueryLowerRuntimePublicSurfaceKind::AllowedBoundaryAdapter,
        "effect execution stays routed through the admitted relational execution lane",
    ),
    ForgeQueryLowerRuntimePublicSurfaceRow::new(
        ForgeQueryLowerRuntimeSeamKey::EffectBackedRelationalMerge,
        "effect-backed relational merge execution",
        "crates/forge-query/src/effect_lifecycle/execution.rs",
        ForgeQueryLowerRuntimePublicSurfaceKind::AllowedBoundaryAdapter,
        "effect merge execution stays routed through the admitted relational execution lane",
    ),
    ForgeQueryLowerRuntimePublicSurfaceRow::new(
        ForgeQueryLowerRuntimeSeamKey::EffectBackedBridgeWriteback,
        "effect-backed bridge writeback adapter",
        "crates/forge-query/src/effect_lifecycle/execution_bridge.rs",
        ForgeQueryLowerRuntimePublicSurfaceKind::AllowedBoundaryAdapter,
        "bridge writeback remains a declared bridge adapter over the admitted writeback contract",
    ),
    ForgeQueryLowerRuntimePublicSurfaceRow::new(
        ForgeQueryLowerRuntimeSeamKey::RuntimeIntentAuthorityAdapter,
        "runtime intent authority adapter",
        "crates/forge-query/src/runtime/backend/intent_authority.rs",
        ForgeQueryLowerRuntimePublicSurfaceKind::AllowedBoundaryAdapter,
        "intent authority adapter remains confined to the backend boundary over admitted runtime bridge and relational authority",
    ),
    ForgeQueryLowerRuntimePublicSurfaceRow::new(
        ForgeQueryLowerRuntimeSeamKey::IntentRuntimeExecution,
        "installed intent authority backend execution",
        "crates/forge-query/src/runtime/backend/intent_authority.rs",
        ForgeQueryLowerRuntimePublicSurfaceKind::AllowedBoundaryAdapter,
        "intent execution remains confined to the backend authority seam",
    ),
    ForgeQueryLowerRuntimePublicSurfaceRow::new(
        ForgeQueryLowerRuntimeSeamKey::ProjectionSourceIntakeFromQueryReceipts,
        "projection source intake from Query receipts",
        "crates/forge-query/src/projection_consumption/source.rs",
        ForgeQueryLowerRuntimePublicSurfaceKind::AllowedBoundaryAdapter,
        "projection source intake remains a declared Query boundary adapter over Query-owned authoritative receipts",
    ),
    ForgeQueryLowerRuntimePublicSurfaceRow::new(
        ForgeQueryLowerRuntimeSeamKey::ProjectionSourceIntakeFromRelationalArtifacts,
        "projection source intake from relational artifacts",
        "crates/forge-query/src/projection_consumption/source.rs",
        ForgeQueryLowerRuntimePublicSurfaceKind::AllowedBoundaryAdapter,
        "projection source intake remains a declared Query boundary adapter over relational authoritative artifacts",
    ),
    ForgeQueryLowerRuntimePublicSurfaceRow::new(
        ForgeQueryLowerRuntimeSeamKey::ProjectionSourceIntakeFromBridgeArtifacts,
        "projection source intake from bridge artifacts",
        "crates/forge-query/src/projection_consumption/source.rs",
        ForgeQueryLowerRuntimePublicSurfaceKind::AllowedBoundaryAdapter,
        "projection source intake remains a declared Query boundary adapter over bridge authoritative artifacts",
    ),
    ForgeQueryLowerRuntimePublicSurfaceRow::new(
        ForgeQueryLowerRuntimeSeamKey::CausalBridgeMaterialization,
        "causal bridge materialization adapter",
        "crates/forge-query/src/runtime/inspection/causal/builder_bridge.rs",
        ForgeQueryLowerRuntimePublicSurfaceKind::AllowedBoundaryAdapter,
        "causal inspection bridge materialization remains a declared Query boundary adapter",
    ),
    ForgeQueryLowerRuntimePublicSurfaceRow::new(
        ForgeQueryLowerRuntimeSeamKey::FrontierEvidenceIntake,
        "frontier signal evidence adapter",
        "crates/forge-query/src/frontier_signal_adapter.rs",
        ForgeQueryLowerRuntimePublicSurfaceKind::AllowedBoundaryAdapter,
        "frontier evidence intake remains a declared Query boundary adapter over signal facade receipts",
    ),
    ForgeQueryLowerRuntimePublicSurfaceRow::new(
        ForgeQueryLowerRuntimeSeamKey::DownstreamQueryRuntimeBoundarySubtree,
        "worth-topo projection runtime boundary",
        "crates/worth-topo/src/projection/runtime_boundary",
        ForgeQueryLowerRuntimePublicSurfaceKind::DownstreamRuntimeBoundary,
        "declared downstream runtime-boundary subtree",
    ),
];
