#[path = "authority.rs"]
mod authority;
#[path = "bulk.rs"]
mod bulk;
#[path = "delta_layout.rs"]
mod delta_layout;
#[path = "durability.rs"]
mod durability;
#[path = "live_query.rs"]
mod live_query;
#[path = "mode.rs"]
mod mode;
#[path = "retention.rs"]
mod retention;
#[path = "snapshot.rs"]
mod snapshot;
#[path = "tiering.rs"]
mod tiering;

use serde::Serialize;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize)]
pub struct CanonicalizationMetrics {
    pub canonicalization_item_count: u64,
    pub canonicalization_duplicate_collapse_count: u64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize)]
pub struct StoreCounterSnapshot {
    pub durable_mode_selection_count: u64,
    pub embedded_mode_selection_count: u64,
    pub absent_mode_selection_count: u64,
    pub hosted_runtime_start_count: u64,
    pub hosted_runtime_stop_count: u64,
    pub external_commit_intake_count: u64,
    pub external_checkpoint_intake_count: u64,
    pub embedded_checkpoint_authority_rejection_count: u64,
    pub cross_mode_canonical_boundary_reuse_count: u64,
    pub mode_misuse_rejection_count: u64,
    pub absent_mode_store_touch_count: u64,
    pub canonicalization_item_count: u64,
    pub canonicalization_duplicate_collapse_count: u64,
    pub authoritative_commit_append_count: u64,
    pub authoritative_commit_fetch_count: u64,
    pub commit_parent_record_write_count: u64,
    pub branch_head_write_count: u64,
    pub authoritative_digest_write_count: u64,
    pub commit_support_publication_count: u64,
    pub commit_support_publication_gap_count: u64,
    pub commit_support_summary_build_count: u64,
    pub schema_boundary_fetch_count: u64,
    pub schema_boundary_index_lookup_count: u64,
    pub schema_boundary_rows_read: u64,
    pub schema_boundary_resolution_count: u64,
    pub lineage_lookup_count: u64,
    pub lineage_identity_lookup_count: u64,
    pub lineage_event_rows_read: u64,
    pub lineage_resolution_breadth: u64,
    pub authoritative_fetch_verification_count: u64,
    pub authoritative_fetch_verification_failure_count: u64,
    pub cursor_resume_count: u64,
    pub cursor_identity_lookup_count: u64,
    pub cursor_resume_support_rows_read: u64,
    pub cursor_resume_step_count: u64,
    pub cursor_ack_count: u64,
    pub cursor_equivalence_reject_count: u64,
    pub cursor_regression_reject_count: u64,
    pub stable_basis_lookup_count: u64,
    pub stable_basis_read_count: u64,
    pub stable_basis_support_rows_read: u64,
    pub stable_basis_scope_lookup_count: u64,
    pub stable_basis_fallback_count: u64,
    pub stable_basis_broadening_count: u64,
    pub continuation_batch_gap_count: u64,
    pub continuation_batch_duplicate_count: u64,
    pub continuation_plan_count: u64,
    pub continuation_cursor_identity_lookup_count: u64,
    pub continuation_checkpoint_lookup_count: u64,
    pub continuation_support_rows_read: u64,
    pub continuation_batch_count: u64,
    pub continuation_narrowed_item_count: u64,
    pub continuation_broadened_item_count: u64,
    pub continuation_step_count: u64,
    pub continuation_schema_mismatch_count: u64,
    pub continuation_scope_mismatch_count: u64,
    pub continuation_degraded_basis_count: u64,
    pub continuation_rejected_basis_count: u64,
    pub continuation_control_lane_fallback_count: u64,
    pub continuation_broadening_count: u64,
    pub continuation_parity_count: u64,
    pub continuation_illegal_acknowledgment_count: u64,
    pub subscriber_checkpoint_write_count: u64,
    pub embedded_checkpoint_fetch_count: u64,
    pub embedded_checkpoint_index_lookup_count: u64,
    pub embedded_checkpoint_basis_read_count: u64,
    pub checkpoint_shape_reject_count: u64,
    pub support_artifact_recovery_gap_count: u64,
    pub state_delta_apply_count: u64,
    pub state_delta_touched_family_count: u64,
    pub state_delta_touched_record_count: u64,
    pub state_clone_fallback_count: u64,
    pub wal_record_append_count: u64,
    pub wal_record_scan_count: u64,
    pub wal_record_decode_failure_count: u64,
    pub durable_mutation_admit_count: u64,
    pub durable_commit_acknowledged_count: u64,
    pub durable_commit_recovered_count: u64,
    pub durable_commit_duplicate_suppression_count: u64,
    pub durable_commit_unacknowledged_discard_count: u64,
    pub recovery_requires_full_rebuild_count: u64,
    pub recovery_failure_count: u64,
    pub durable_frame_scan_count: u64,
    pub durable_frame_reject_count: u64,
    pub durable_truncated_tail_count: u64,
    pub durable_torn_write_count: u64,
    pub durable_barrier_verified_count: u64,
    pub durable_ack_barrier_violation_count: u64,
    pub recovery_source_precedence_resolution_count: u64,
    pub recovery_source_precedence_fallback_count: u64,
    pub recovery_quiescent_restart_count: u64,
    pub recovery_non_quiescent_restart_count: u64,
    pub recovery_quarantine_count: u64,
    pub recovery_salvage_count: u64,
    pub interrupted_maintenance_recovery_count: u64,
    pub backup_restore_compatibility_reject_count: u64,
    pub snapshot_capture_count: u64,
    pub snapshot_capture_record_count: u64,
    pub snapshot_capture_byte_count: u64,
    pub snapshot_read_count: u64,
    pub snapshot_read_record_count: u64,
    pub snapshot_read_tail_commit_count: u64,
    pub snapshot_read_tail_replay_count: u64,
    pub snapshot_restore_count: u64,
    pub snapshot_restore_tail_commit_count: u64,
    pub snapshot_restore_tail_replay_count: u64,
    pub snapshot_rebuild_count: u64,
    pub snapshot_rebuild_record_count: u64,
    pub snapshot_integrity_failure_count: u64,
    pub snapshot_basis_mismatch_count: u64,
    pub branch_create_count: u64,
    pub branch_base_reuse_count: u64,
    pub branch_base_copy_count: u64,
    pub branch_hidden_full_base_materialization_count: u64,
    pub branch_delta_read_count: u64,
    pub branch_delta_layers_traversed_count: u64,
    pub branch_delta_read_record_count: u64,
    pub branch_delta_replay_commit_count: u64,
    pub branch_delta_authority_replay_fallback_count: u64,
    pub branch_delta_rewrite_count: u64,
    pub branch_delta_rewrite_layers_replaced_count: u64,
    pub branch_delta_rewrite_record_count: u64,
    pub branch_delta_hidden_full_stack_rewrite_count: u64,
    pub branch_delta_merge_path_search_count: u64,
    pub branch_delta_rebuild_count: u64,
    pub branch_delta_rebuild_record_count: u64,
    pub branch_delta_integrity_failure_count: u64,
    pub concurrent_artifact_boundary_rejection_count: u64,
    pub aspect_layout_plan_count: u64,
    pub aspect_layout_admitted_count: u64,
    pub aspect_layout_fallback_count: u64,
    pub aspect_layout_rejected_count: u64,
    pub aspect_layout_slice_read_count: u64,
    pub aspect_layout_block_decode_count: u64,
    pub aspect_layout_control_replay_breadth: u64,
    pub aspect_layout_whole_state_fallback_count: u64,
    pub structural_block_lookup_count: u64,
    pub structural_block_reuse_admission_count: u64,
    pub structural_block_reuse_hit_count: u64,
    pub structural_block_reuse_miss_count: u64,
    pub chunk_model_freeze_count: u64,
    pub physical_chunk_export_count: u64,
    pub physical_chunk_width_count: u64,
    pub physical_chunk_determinism_violation_count: u64,
    pub milestone_6_proof_only_prepare_count: u64,
    pub milestone_6_on_demand_materialize_count: u64,
    pub milestone_6_policy_eager_resolution_count: u64,
    pub milestone_6_policy_eager_publish_count: u64,
    pub milestone_6_policy_eager_reuse_existing_count: u64,
    pub milestone_7_layout_reference_admission_count: u64,
    pub milestone_9_physical_chunk_reference_admission_count: u64,
    pub bulk_program_plan_count: u64,
    pub bulk_source_manifest_member_count: u64,
    pub bulk_source_manifest_stream_pass_count: u64,
    pub bulk_transform_partition_count: u64,
    pub bulk_chunk_plan_count: u64,
    pub bulk_chunk_execute_count: u64,
    pub bulk_checkpoint_write_count: u64,
    pub bulk_chunk_witness_write_count: u64,
    pub bulk_resume_index_lookup_count: u64,
    pub bulk_chunk_resume_count: u64,
    pub bulk_chunk_commit_count: u64,
    pub bulk_chunk_width_units: u64,
    pub bulk_peak_in_flight_memory_units: u64,
    pub bulk_fallback_path_count: u64,
    pub bulk_fallback_breadth_units: u64,
    pub retention_policy_evaluation_count: u64,
    pub retained_authoritative_range_count: u64,
    pub expired_authoritative_range_count: u64,
    pub compaction_plan_count: u64,
    pub compacted_delta_layer_count: u64,
    pub compacted_snapshot_family_count: u64,
    pub compacted_layout_family_count: u64,
    pub compaction_cutover_count: u64,
    pub compaction_cutover_rejection_count: u64,
    pub reclaim_candidate_count: u64,
    pub reclaimed_authoritative_artifact_count: u64,
    pub reclaimed_derived_artifact_count: u64,
    pub reclaim_rejected_live_basis_count: u64,
    pub retention_closure_ancestor_count: u64,
    pub retention_closure_failure_count: u64,
    pub retained_range_rebuild_count: u64,
    pub rebuild_debt_count: u64,
    pub compaction_debt_count: u64,
    pub retention_truth_parity_failure_count: u64,
    pub retention_restore_parity_failure_count: u64,
    pub retention_artifact_rebuild_failure_count: u64,
    pub maintenance_declaration_count: u64,
    pub maintenance_admission_count: u64,
    pub maintenance_rejection_count: u64,
    pub maintenance_resume_count: u64,
    pub maintenance_restart_readmission_count: u64,
    pub maintenance_restart_rejection_count: u64,
    pub maintenance_checkpoint_count: u64,
    pub maintenance_completion_count: u64,
    pub maintenance_failure_count: u64,
    pub maintenance_debt_link_count: u64,
    pub maintenance_foreground_borrow_count: u64,
    pub maintenance_foreground_wait_count: u64,
    pub maintenance_cutover_dependency_count: u64,
    pub maintenance_coalesced_work_count: u64,
    pub maintenance_cancelled_superseded_work_count: u64,
    pub maintenance_store_global_scope_count: u64,
    pub maintenance_starvation_trigger_count: u64,
    pub maintenance_debt_escalation_count: u64,
    pub maintenance_io_budget_units_reserved: u64,
    pub maintenance_cpu_budget_units_reserved: u64,
    pub maintenance_memory_budget_units_reserved: u64,
    pub maintenance_publication_slot_budget_reserved: u64,
    pub maintenance_quantum_grant_count: u64,
    pub maintenance_quantum_exhaustion_count: u64,
    pub maintenance_background_unit_execute_count: u64,
    pub maintenance_foreground_interference_count: u64,
    pub maintenance_foreground_wait_on_cutover_count: u64,
    pub maintenance_foreground_broadened_count: u64,
    pub maintenance_reservation_violation_count: u64,
    pub maintenance_cross_locality_escalation_count: u64,
    pub maintenance_freshness_rejection_count: u64,
    pub maintenance_locality_touch_count: u64,
    pub maintenance_global_scope_fallback_count: u64,
    pub maintenance_cold_start_boot_count: u64,
    pub maintenance_cold_start_summary_load_count: u64,
    pub maintenance_cold_start_legacy_backfill_count: u64,
    pub maintenance_cold_start_recovery_backlog_count: u64,
    pub maintenance_cold_start_integrity_reject_count: u64,
    pub maintenance_cold_start_global_scan_count: u64,
    pub maintenance_plan_execute_without_descriptor_count: u64,
    pub maintenance_illegal_escalation_count: u64,
    pub maintenance_truth_visibility_violation_count: u64,
    pub placement_state_manifest_load_count: u64,
    pub placement_state_recovery_count: u64,
    pub working_set_observation_window_count: u64,
    pub working_set_reclassification_count: u64,
    pub hot_tier_resident_read_count: u64,
    pub warm_tier_resident_read_count: u64,
    pub cold_tier_recall_count: u64,
    pub foreground_cold_recall_count: u64,
    pub background_tier_move_count: u64,
    pub restart_recall_count: u64,
    pub tier_move_plan_count: u64,
    pub tier_move_cutover_count: u64,
    pub tier_move_cutover_rejection_count: u64,
    pub authoritative_tier_move_count: u64,
    pub derived_tier_move_count: u64,
    pub tier_move_rejection_count: u64,
    pub tier_miss_count: u64,
    pub broadened_recall_plan_count: u64,
    pub recall_coalesced_request_count: u64,
    pub recall_duplicate_suppression_count: u64,
    pub tier_interleaved_read_count: u64,
    pub tier_interleaved_continuation_count: u64,
    pub tier_interleaving_recall_count: u64,
    pub tier_interleaving_parity_failure_count: u64,
    pub placement_debt_count: u64,
    pub working_set_debt_count: u64,
    pub tier_truth_parity_failure_count: u64,
    pub tier_restore_parity_failure_count: u64,
    pub tier_recall_failure_count: u64,
}

#[derive(Debug, Default)]
pub(crate) struct StoreCounters {
    mode: mode::ModeCounters,
    authority: authority::AuthorityCounters,
    live_query: live_query::LiveQueryCounters,
    durability: durability::DurabilityCounters,
    snapshot: snapshot::SnapshotCounters,
    delta_layout: delta_layout::DeltaLayoutCounters,
    bulk: bulk::BulkCounters,
    retention: retention::RetentionCounters,
    tiering: tiering::TieringCounters,
}

impl StoreCounters {
    pub fn snapshot(&self) -> StoreCounterSnapshot {
        let mut snapshot = StoreCounterSnapshot::default();
        mode::write_snapshot(&self.mode, &mut snapshot);
        authority::write_snapshot(&self.authority, &mut snapshot);
        live_query::write_snapshot(&self.live_query, &mut snapshot);
        durability::write_snapshot(&self.durability, &mut snapshot);
        snapshot::write_snapshot(&self.snapshot, &mut snapshot);
        delta_layout::write_snapshot(&self.delta_layout, &mut snapshot);
        bulk::write_snapshot(&self.bulk, &mut snapshot);
        retention::write_snapshot(&self.retention, &mut snapshot);
        tiering::write_snapshot(&self.tiering, &mut snapshot);
        snapshot
    }
}
