use topology::derived_invalidation_route_input::current_topology_invalidation_route_input;

use super::current_worth_touched_graph_conflict_derived_read_diagnostic_input;
use crate::workload_composition::planner_owned_routing::current_worth_touched_graph_conflict_selected_route_packet;

#[test]
fn current_derived_read_diagnostic_input_requires_real_selected_route_packet() {
    let invalidation_route_input = current_topology_invalidation_route_input().expect(
        "current invalidation-route input should lower from the real topology invalidation proof",
    );
    let selected_route_packet = current_worth_touched_graph_conflict_selected_route_packet()
        .expect(
            "current selected-route packet should lower from the real planner-owned route seam",
        );
    let diagnostic_input = current_worth_touched_graph_conflict_derived_read_diagnostic_input()
        .expect(
        "current derived-read diagnostic input should lower from the real selected-route packet",
    );

    assert_eq!(
        diagnostic_input
            .invalidation_route_input()
            .touched_closure_digest(),
        invalidation_route_input.touched_closure_digest()
    );
    assert_eq!(
        diagnostic_input
            .invalidation_route_input()
            .selected_plan_digest(),
        invalidation_route_input.selected_plan_digest()
    );
    assert_eq!(
        diagnostic_input
            .invalidation_route_input()
            .routing_contract_digest(),
        invalidation_route_input.routing_contract_digest()
    );
    assert_eq!(
        diagnostic_input
            .invalidation_route_input()
            .query_support_digest(),
        invalidation_route_input.query_support_digest()
    );
    assert_eq!(
        diagnostic_input
            .invalidation_route_input()
            .legality_support_digest(),
        invalidation_route_input.legality_support_digest()
    );
    assert_eq!(
        diagnostic_input
            .invalidation_route_input()
            .execution_admission(),
        invalidation_route_input.execution_admission()
    );
    assert_eq!(
        diagnostic_input.invalidation_route_input().selected_rows(),
        invalidation_route_input.selected_rows()
    );
    assert_eq!(
        diagnostic_input.selected_route_identity_digest(),
        selected_route_packet.selected_route_identity_digest()
    );
    assert_eq!(
        diagnostic_input.batch_admission_route_packet_identity(),
        Some(selected_route_packet.batch_admission_route_packet_identity())
    );
    assert_eq!(
        diagnostic_input.batch_admission_denial_witness_identity(),
        selected_route_packet.batch_admission_denial_witness_identity()
    );
    assert_eq!(
        diagnostic_input.batch_admission_denial_witness_kind(),
        selected_route_packet.batch_admission_denial_witness_kind()
    );
    assert_eq!(
        diagnostic_input.conflict_independence_route_packet_identity(),
        Some(selected_route_packet.conflict_independence_route_packet_identity())
    );
    assert_eq!(
        diagnostic_input.conflict_independence_denial_witness_identity(),
        selected_route_packet.conflict_independence_denial_witness_identity()
    );
    assert_eq!(
        diagnostic_input.conflict_independence_denial_witness_kind(),
        selected_route_packet.conflict_independence_denial_witness_kind()
    );
    assert_eq!(
        diagnostic_input.selected_family_identity(),
        Some(selected_route_packet.selected_family_identity())
    );
    assert_eq!(
        diagnostic_input
            .equivalence_contract_report()
            .compiled_product_identity_digest(),
        Some(selected_route_packet.selected_product_identity_digest())
    );
    assert_eq!(
        diagnostic_input
            .equivalence_contract_report()
            .equivalence_policy_identity_digest(),
        Some(selected_route_packet.selected_equivalence_policy_identity_digest())
    );
    assert_eq!(
        diagnostic_input
            .equivalence_contract_report()
            .selected_compatibility_basis_identity_digest(),
        Some(selected_route_packet.selected_compatibility_basis_identity_digest())
    );
    assert_eq!(
        diagnostic_input
            .equivalence_contract_report()
            .selected_reuse_basis_identity_digest(),
        Some(selected_route_packet.selected_reuse_basis_identity_digest())
    );
    let read_diagnostics = diagnostic_input.as_read_diagnostics();
    assert_eq!(
        read_diagnostics.batch_admission_route_packet_identity,
        selected_route_packet
            .batch_admission_route_packet_identity()
            .to_string()
            .into()
    );
    assert_eq!(
        read_diagnostics.batch_admission_denial_witness_identity,
        selected_route_packet
            .batch_admission_denial_witness_identity()
            .map(str::to_string)
    );
    assert_eq!(
        read_diagnostics.batch_admission_denial_witness_kind,
        selected_route_packet.batch_admission_denial_witness_kind()
    );
    assert_eq!(
        read_diagnostics.conflict_independence_route_packet_identity,
        selected_route_packet
            .conflict_independence_route_packet_identity()
            .to_string()
            .into()
    );
    assert_eq!(
        read_diagnostics.conflict_independence_denial_witness_identity,
        selected_route_packet
            .conflict_independence_denial_witness_identity()
            .map(str::to_string)
    );
    assert_eq!(
        read_diagnostics.conflict_independence_denial_witness_kind,
        selected_route_packet.conflict_independence_denial_witness_kind()
    );
}
