use crate::authority::CURRENT_CANONICALIZATION_VERSION;

use super::super::records::StoreState;

impl Default for StoreState {
    fn default() -> Self {
        Self {
            canonicalization_version: CURRENT_CANONICALIZATION_VERSION,
            next_commit_sequence: 1,
            next_head_update_sequence: 1,
            branch_records: std::collections::BTreeMap::new(),
            branch_head_records: std::collections::BTreeMap::new(),
            commit_envelopes: std::collections::BTreeMap::new(),
            commit_parent_records: std::collections::BTreeMap::new(),
            authoritative_artifact_digests: std::collections::BTreeMap::new(),
            compatibility_manifest_records: std::collections::BTreeMap::new(),
            subscription_support_record_sets: std::collections::BTreeMap::new(),
            subscription_support_maintenance_descriptor_records: std::collections::BTreeMap::new(),
            subscription_support_counter_snapshot: Default::default(),
            subscription_support_access_structures_verified: true,
            subscription_support_access_structure_debts: Vec::new(),
            commit_support_summaries: std::collections::BTreeMap::new(),
            schema_support_records: std::collections::BTreeMap::new(),
            lineage_support_records: std::collections::BTreeMap::new(),
            durable_cursor_identity_records: std::collections::BTreeMap::new(),
            subscriber_checkpoint_records: std::collections::BTreeMap::new(),
            stable_basis_records: std::collections::BTreeMap::new(),
            compaction_product_records: std::collections::BTreeMap::new(),
            retention_basis_records: std::collections::BTreeMap::new(),
            retention_closure_records: std::collections::BTreeMap::new(),
            rebuild_debt_records: std::collections::BTreeMap::new(),
            next_maintenance_declaration_order: 0,
            next_maintenance_checkpoint_order: 0,
            maintenance_declaration_records: std::collections::BTreeMap::new(),
            maintenance_execution_records: std::collections::BTreeMap::new(),
            maintenance_batch_records: std::collections::BTreeMap::new(),
            maintenance_checkpoint_records: std::collections::BTreeMap::new(),
            maintenance_queue_summary_records: std::collections::BTreeMap::new(),
            maintenance_locality_summary_records: std::collections::BTreeMap::new(),
            maintenance_reservation_summary_records: std::collections::BTreeMap::new(),
            maintenance_resource_budget_summary_records: std::collections::BTreeMap::new(),
            maintenance_debt_summary_records: std::collections::BTreeMap::new(),
            maintenance_loaded_persisted_summaries_on_boot: false,
            maintenance_used_legacy_summary_backfill_on_boot: false,
            maintenance_recovered_backlog_on_boot: 0,
            maintenance_boot_integrity_reject_count: 0,
            branch_shared_base_records: std::collections::BTreeMap::new(),
            next_branch_delta_layer_id: 1,
            branch_delta_layer_records: std::collections::BTreeMap::new(),
            embedded_checkpoint_records: std::collections::BTreeMap::new(),
            milestone_6_layout_materialization_records: std::collections::BTreeMap::new(),
            milestone_6_commit_coupled_layout_seed_records: std::collections::BTreeMap::new(),
            milestone_6_scope_slice_membership_records: std::collections::BTreeMap::new(),
            milestone_6_chunk_membership_records: std::collections::BTreeMap::new(),
            milestone_6_structural_block_records: std::collections::BTreeMap::new(),
            bulk_program_identity_records: std::collections::BTreeMap::new(),
            frozen_bulk_manifest_records: std::collections::BTreeMap::new(),
            frozen_transform_basis_records: std::collections::BTreeMap::new(),
            frozen_transform_partition_records: std::collections::BTreeMap::new(),
            bulk_deterministic_plan_records: std::collections::BTreeMap::new(),
            bulk_progress_checkpoint_records: std::collections::BTreeMap::new(),
            bulk_chunk_witness_records: std::collections::BTreeMap::new(),
            program_chunk_witness_index_records: std::collections::BTreeMap::new(),
            next_snapshot_id: 1,
            snapshot_basis_records: std::collections::BTreeMap::new(),
            snapshot_image_records: std::collections::BTreeMap::new(),
            tier_residency_records: std::collections::BTreeMap::new(),
            tier_transfer_records: std::collections::BTreeMap::new(),
            tier_recall_records: std::collections::BTreeMap::new(),
            next_durable_mutation_id: 1,
            next_wal_sequence: 1,
            wal_records: std::collections::BTreeMap::new(),
        }
    }
}
