use super::error::ConflictBatchAdmissionInventoryError;
use super::row::{
    ConflictBatchAdmissionAuthorityKind as AuthorityKind,
    ConflictBatchAdmissionCertificationPosture as CertificationPosture,
    ConflictBatchAdmissionCostPosture as CostPosture,
    ConflictBatchAdmissionDisposition as Disposition, ConflictBatchAdmissionInventoryRow,
    ConflictBatchAdmissionOwner as Owner, ConflictBatchAdmissionQuerySurface as QuerySurface,
    ConflictBatchAdmissionReplacementPhase as ReplacementPhase,
    ConflictBatchAdmissionRowScope as RowScope, ConflictBatchAdmissionSurfaceIdentity as Surface,
};

pub(crate) fn additional_conflict_batch_admission_rows(
) -> Result<Vec<ConflictBatchAdmissionInventoryRow>, ConflictBatchAdmissionInventoryError> {
    let mut rows = Vec::new();
    rows.extend(workload_handoff_rows()?);
    rows.extend(phase_fourteen_closeout_rows()?);
    rows.extend(super::compatibility_rows::compatibility_inventory_rows()?);
    rows.extend(super::phase_thirteen_firewall_rows::phase_thirteen_firewall_rows()?);
    rows.extend(spatial_overlap_rows()?);
    rows.extend(topo_certification_rows()?);
    rows.extend(residue_rows()?);
    rows.extend(broad_scan_counter_rows()?);
    rows.extend(rollback_admission_rows()?);
    Ok(rows)
}

fn phase_fourteen_closeout_rows(
) -> Result<Vec<ConflictBatchAdmissionInventoryRow>, ConflictBatchAdmissionInventoryError> {
    Ok(vec![
        row(
            Surface::WorthWorkloadOrdinaryConsumerSweepCloseout,
            "crates/worth-kernel/src/workload_composition/worth_workload/ordinary_consumer_sweep/closeout.rs",
            "current_worth_workload_ordinary_consumer_sweep_closeout",
            Owner::WorthKernel,
            "phase 14 ordinary consumer sweep QA and closeout",
            AuthorityKind::SourceFirewallCloseout,
            Disposition::CertificationOnly,
            ReplacementPhase::NotReplacedCertificationOnly,
            "phase-14 closeout is a certification surface over the ordinary compiled-product lane and must not become a hidden admission shortcut",
            "later milestone QA and source-firewall consumers read the closeout artifact while ordinary runtime still consumes the routed compiled-product lane itself",
            CertificationPosture::CertificationOnlyDeniedAsOrdinaryProof,
            CostPosture::SourceFirewallOnly,
            QuerySurface::NotQuery,
            RowScope::ConcreteSource,
        )?,
        row(
            Surface::WorthWorkloadOrdinaryConsumerSweepRequireAllCoveredConsumersOnCompiledProductLane,
            "crates/worth-kernel/src/workload_composition/worth_workload/ordinary_consumer_sweep/closeout.rs",
            "WorthWorkloadOrdinaryConsumerSweepCloseout::require_all_covered_consumers_on_compiled_product_lane",
            Owner::WorthKernel,
            "phase 14 ordinary consumer sweep QA and closeout",
            AuthorityKind::SourceFirewallCloseout,
            Disposition::CertificationOnly,
            ReplacementPhase::NotReplacedCertificationOnly,
            "phase-14 route gate certifies coverage and must not become ordinary workload admission authority",
            "QA and source-firewall review consume the certification-only route gate while runtime stays on selected-plan and typed public/read-model consumers",
            CertificationPosture::CertificationOnlyDeniedAsOrdinaryProof,
            CostPosture::SourceFirewallOnly,
            QuerySurface::NotQuery,
            RowScope::ConcreteSource,
        )?,
        row(
            Surface::WorthWorkloadOrdinaryConsumerSweepRequireZeroBroadScanFallbackOnOrdinaryPath,
            "crates/worth-kernel/src/workload_composition/worth_workload/ordinary_consumer_sweep/closeout.rs",
            "WorthWorkloadOrdinaryConsumerSweepCloseout::require_zero_broad_scan_fallback_on_ordinary_path",
            Owner::WorthKernel,
            "phase 14 ordinary consumer sweep QA and closeout",
            AuthorityKind::SourceFirewallCloseout,
            Disposition::CertificationOnly,
            ReplacementPhase::NotReplacedCertificationOnly,
            "phase-14 broad-scan denial gate is certification-only and must not become ordinary workload admission authority",
            "QA and source-firewall review consume the broad-scan denial gate while runtime stays on routed compiled-product consumers",
            CertificationPosture::CertificationOnlyDeniedAsOrdinaryProof,
            CostPosture::SourceFirewallOnly,
            QuerySurface::NotQuery,
            RowScope::ConcreteSource,
        )?,
    ])
}

fn workload_handoff_rows(
) -> Result<Vec<ConflictBatchAdmissionInventoryRow>, ConflictBatchAdmissionInventoryError> {
    Ok(vec![
        row(Surface::CompletedBooleanSplitHandoff, "crates/worth-kernel/src/workload_composition/worth_workload/boolean_split_handoff.rs", "CompletedBooleanSplitHandoff", Owner::WorthKernel, "boolean split workload consumers", AuthorityKind::WorkloadCompositionAdmission, Disposition::Migrate, ReplacementPhase::PhaseFourAdmittedConflictInput, "split handoff currently chains workload, lookup, touch, and replay/undo admission", "conflict input consumes explicit split participant proof", CertificationPosture::OrdinaryProductionReachable, CostPosture::PriorProofBoundary, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::CompletedBooleanSplitHandoffAdmitDownstreamSplitConsumption, "crates/worth-kernel/src/workload_composition/worth_workload/boolean_split_handoff.rs", "CompletedBooleanSplitHandoff::admit_downstream_split_consumption", Owner::WorthKernel, "downstream split consumers", AuthorityKind::LookupConsumedWorkloadAdmission, Disposition::Migrate, ReplacementPhase::PhaseElevenConsumerSweep, "downstream split consumers must admit through the explicit batch-execution cluster instead of the lookup-consumed convenience lane", "consumer sweep routes downstream split consumers through selected plans and workload-attached batch execution", CertificationPosture::OrdinaryProductionReachable, CostPosture::ReceiptBackedTypedLookup, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::CompletedBooleanSplitHandoffAdmitSplitSpatialTouchAuthority, "crates/worth-kernel/src/workload_composition/worth_workload/boolean_split_handoff.rs", "CompletedBooleanSplitHandoff::admit_split_spatial_touch_authority", Owner::WorthKernel, "split spatial touch consumers", AuthorityKind::SpatialTouchAuthorityAdmission, Disposition::Migrate, ReplacementPhase::PhaseFourAdmittedConflictInput, "spatial touch admission is current spatial authority bridge for split work", "conflict admission consumes sealed spatial touch authority directly", CertificationPosture::OrdinaryProductionReachable, CostPosture::PriorProofBoundary, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::CompletedBooleanLoopReconstructionHandoff, "crates/worth-kernel/src/workload_composition/worth_workload/boolean_loop_reconstruction_handoff.rs", "CompletedBooleanLoopReconstructionHandoff", Owner::WorthKernel, "loop reconstruction workload consumers", AuthorityKind::ReplayUndoBoundaryAdmission, Disposition::Migrate, ReplacementPhase::PhaseFourAdmittedConflictInput, "loop handoff carries reconstruction, lookup, and transaction boundary proof", "conflict input binds loop reconstruction participant proof", CertificationPosture::OrdinaryProductionReachable, CostPosture::PriorProofBoundary, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::PlanarBooleanLoopRuntimeRegistrationProof, "crates/worth-kernel/src/workload_composition/worth_workload/boolean_loop_reconstruction_handoff.rs", "PlanarBooleanLoopRuntimeRegistrationProof", Owner::WorthKernel, "loop runtime registration closeout and certification", AuthorityKind::CutLineResidue, Disposition::Cap, ReplacementPhase::PhaseElevenConsumerSweep, "runtime registration proof remains Query-proof accompaniment and cannot authorize ordinary grouped conflict or batch admission", "phase 12 firewall deletion removes runtime-registration accompaniment from ordinary-consumer accounting", CertificationPosture::NonOrdinaryResidueDeniedAsOrdinaryProof, CostPosture::CappedResidue, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::BooleanChainIntegrationHandoff, "crates/worth-kernel/src/workload_composition/worth_workload/boolean_chain_handoff.rs", "BooleanChainIntegrationHandoff", Owner::WorthKernel, "replay/undo cutover closeout assembly", AuthorityKind::CutLineResidue, Disposition::Cap, ReplacementPhase::PhaseElevenConsumerSweep, "boolean chain integration remains replay/undo closeout assembly and cannot act as selected-plan or batch-execution authority", "phase 12 firewall deletion replaces chain handoff accounting with proof-only closeout artifacts", CertificationPosture::NonOrdinaryResidueDeniedAsOrdinaryProof, CostPosture::CappedResidue, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::WorkloadCatalogPlanarBooleanCoplanarOverlapPair, "crates/worth-kernel/src/workload_composition/workload_catalog/catalog_constructors.rs", "WorkloadCatalog::planar_boolean_coplanar_overlap_pair", Owner::WorthKernel, "workload catalog boolean operand pair consumers", AuthorityKind::WorkloadCompositionAdmission, Disposition::Migrate, ReplacementPhase::PhaseSevenBatchCatalog, "catalog constructor currently admits the coplanar overlap workload recipe before batch catalog selection exists", "batch catalog names coplanar overlap admission through selected conflict family and workload recipe identity", CertificationPosture::OrdinaryProductionReachable, CostPosture::LocalTypedAdmission, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::WorkloadCatalogCoplanarOverlapStorm, "crates/worth-kernel/src/workload_composition/workload_catalog/catalog_constructors.rs", "WorkloadCatalog::coplanar_overlap_storm", Owner::WorthKernel, "workload catalog stress-recipe consumers", AuthorityKind::WorkloadCompositionAdmission, Disposition::Migrate, ReplacementPhase::PhaseSevenBatchCatalog, "catalog constructor currently admits an overlap-storm workload recipe before batch catalog selection exists", "batch catalog names overlap-storm stress admission through selected conflict family and workload recipe identity", CertificationPosture::OrdinaryProductionReachable, CostPosture::LocalTypedAdmission, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::OperatorOutcomeFromCoplanarOverlapReceipt, "crates/worth-kernel/src/workload_composition/operator_harness/outcome.rs", "OperatorOutcome::from_coplanar_overlap_receipt", Owner::WorthKernel, "operator harness coplanar overlap callers", AuthorityKind::OperationalOverlapReceipt, Disposition::Migrate, ReplacementPhase::PhaseNineExecutionReceipt, "operator outcome currently admits a coplanar overlap receipt into kernel workload outcome", "batch execution receipt consumes selected overlap receipt identity instead of outcome-local admission", CertificationPosture::OrdinaryProductionReachable, CostPosture::ReceiptBackedTypedLookup, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::OperatorReceiptSetFromCoplanarOverlapReceipt, "crates/worth-kernel/src/workload_composition/operator_harness/receipt_set.rs", "OperatorReceiptSet::from_coplanar_overlap_receipt", Owner::WorthKernel, "OperatorOutcome::from_coplanar_overlap_receipt", AuthorityKind::OperationalOverlapReceipt, Disposition::Migrate, ReplacementPhase::PhaseNineExecutionReceipt, "receipt set currently translates coplanar overlap receipts into kernel workload evidence rows", "batch execution receipt binds the same evidence row identity after selected conflict planning", CertificationPosture::OrdinaryProductionReachable, CostPosture::ReceiptBackedTypedLookup, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
    ])
}

fn spatial_overlap_rows(
) -> Result<Vec<ConflictBatchAdmissionInventoryRow>, ConflictBatchAdmissionInventoryError> {
    Ok(vec![
        row(Surface::CertifiedProjectedOverlapBridgeAuthority, "crates/worth-spatial/src/workload_platform/projected_overlap_faces/authority.rs", "CertifiedProjectedOverlapBridgeAuthority", Owner::WorthSpatial, "projected overlap bridge consumers", AuthorityKind::OperationalOverlapExecution, Disposition::Migrate, ReplacementPhase::PhaseThreeConflictCatalog, "bridge authority currently composes projected overlap face and extraction authority", "spatial conflict catalog names the same overlap authority through shared vocabulary", CertificationPosture::OrdinaryProductionReachable, CostPosture::OperationalOverlapExecution, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::ProjectedOverlapFaceSet, "crates/worth-spatial/src/workload_platform/projected_overlap_faces/face_set.rs", "ProjectedOverlapFaceSet", Owner::WorthSpatial, "projected overlap certification", AuthorityKind::OperationalOverlapExecution, Disposition::Migrate, ReplacementPhase::PhaseFourAdmittedConflictInput, "face set is current projected overlap candidate boundary", "admitted spatial conflict input binds projected overlap candidates explicitly", CertificationPosture::OrdinaryProductionReachable, CostPosture::OperationalOverlapExecution, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::ProjectedOverlapFaceGeometry, "crates/worth-spatial/src/workload_platform/projected_overlap_faces/face_set.rs", "ProjectedOverlapFaceGeometry", Owner::WorthSpatial, "ProjectedOverlapFaceSet", AuthorityKind::OperationalOverlapExecution, Disposition::Migrate, ReplacementPhase::PhaseFourAdmittedConflictInput, "face geometry currently carries projected-overlap candidate coordinates", "admitted spatial conflict input consumes projected face geometry through typed candidates", CertificationPosture::OrdinaryProductionReachable, CostPosture::OperationalOverlapExecution, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::ProjectedOverlapCandidatePolicy, "crates/worth-spatial/src/workload_platform/projected_overlap_faces/face_set.rs", "ProjectedOverlapCandidatePolicy", Owner::WorthSpatial, "ProjectedOverlapFaceSet", AuthorityKind::OperationalOverlapExecution, Disposition::Migrate, ReplacementPhase::PhaseFiveSelectedConflictPlan, "candidate policy currently shapes which projected overlaps can proceed", "selected conflict plans own candidate policy instead of face-set local posture", CertificationPosture::OrdinaryProductionReachable, CostPosture::OperationalOverlapExecution, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::CertifiedProjectedOverlapFaceSet, "crates/worth-spatial/src/workload_platform/projected_overlap_faces/certified_set.rs", "CertifiedProjectedOverlapFaceSet", Owner::WorthSpatial, "projected overlap certification", AuthorityKind::OperationalOverlapExecution, Disposition::Migrate, ReplacementPhase::PhaseFourAdmittedConflictInput, "certified face set is current overlap candidate proof", "admitted conflict input consumes certified overlap proof", CertificationPosture::OrdinaryProductionReachable, CostPosture::OperationalOverlapExecution, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::CertifiedProjectedOverlapFace, "crates/worth-spatial/src/workload_platform/projected_overlap_faces/certified_face.rs", "CertifiedProjectedOverlapFace", Owner::WorthSpatial, "CertifiedProjectedOverlapFaceSet", AuthorityKind::OperationalOverlapExecution, Disposition::Migrate, ReplacementPhase::PhaseFourAdmittedConflictInput, "certified projected face is current per-face overlap proof", "admitted conflict input names per-face overlap proof without rediscovery", CertificationPosture::OrdinaryProductionReachable, CostPosture::OperationalOverlapExecution, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::CertifiedProjectedOverlapCandidatePair, "crates/worth-spatial/src/workload_platform/projected_overlap_faces/certified_pair.rs", "CertifiedProjectedOverlapCandidatePair", Owner::WorthSpatial, "coplanar overlap extraction", AuthorityKind::OperationalOverlapExecution, Disposition::Migrate, ReplacementPhase::PhaseFourAdmittedConflictInput, "candidate pair currently decides which projected faces enter overlap extraction", "spatial conflict input names participant pair identity", CertificationPosture::OrdinaryProductionReachable, CostPosture::OperationalOverlapExecution, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::CertifiedProjectedOverlapCandidatePairs, "crates/worth-spatial/src/workload_platform/projected_overlap_faces/certified_set.rs", "CertifiedProjectedOverlapCandidatePairs", Owner::WorthSpatial, "CertifiedProjectedOverlapFaceSet", AuthorityKind::OperationalOverlapExecution, Disposition::Migrate, ReplacementPhase::PhaseFourAdmittedConflictInput, "candidate pair collection is current overlap pair enumeration", "admitted conflict input binds pair enumeration as typed overlap proof", CertificationPosture::OrdinaryProductionReachable, CostPosture::OperationalOverlapExecution, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::ProjectedOverlapFaceDenial, "crates/worth-spatial/src/workload_platform/projected_overlap_faces/denial.rs", "ProjectedOverlapFaceDenial", Owner::WorthSpatial, "projected overlap certification", AuthorityKind::OperationalOverlapExecution, Disposition::Migrate, ReplacementPhase::PhaseFiveSelectedConflictPlan, "denial is current projected-overlap failure vocabulary", "selected conflict plans preserve denial cause before execution", CertificationPosture::OrdinaryProductionReachable, CostPosture::OperationalOverlapExecution, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::ProjectedOverlapExtractionContracts, "crates/worth-spatial/src/workload_platform/projected_overlap_faces/bundle.rs", "ProjectedOverlapExtractionContracts", Owner::WorthSpatial, "CoplanarOverlapExtractionBundle", AuthorityKind::OperationalOverlapReceipt, Disposition::Migrate, ReplacementPhase::PhaseNineExecutionReceipt, "extraction contracts currently bind projected-overlap receipts into the bundle", "execution receipt owns extraction contract identity after selected conflict planning", CertificationPosture::OrdinaryProductionReachable, CostPosture::ReceiptBackedTypedLookup, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::CoplanarOverlapExtractionBundle, "crates/worth-spatial/src/workload_platform/projected_overlap_faces/bundle.rs", "CoplanarOverlapExtractionBundle", Owner::WorthSpatial, "CoplanarOverlapWorkloadOperator::with_extraction_bundle", AuthorityKind::OperationalOverlapReceipt, Disposition::Migrate, ReplacementPhase::PhaseNineExecutionReceipt, "extraction bundle is current retained overlap receipt carrier", "execution receipt binds bundle identities through shared conflict vocabulary", CertificationPosture::OrdinaryProductionReachable, CostPosture::ReceiptBackedTypedLookup, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::PlanarBooleanRawEdgeSplitScheduleSetAssembleFromAdmittedCandidates, "crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/raw_edge_split_schedule/assembly.rs", "PlanarBooleanRawEdgeSplitScheduleSet::assemble_from_admitted_candidates", Owner::WorthSpatial, "edge split schedule assembly", AuthorityKind::OperationalOverlapExecution, Disposition::Migrate, ReplacementPhase::PhaseFiveSelectedConflictPlan, "raw edge split schedule assembly consumes admitted candidates and can otherwise hide local compatibility posture", "selected conflict plans replace schedule-local compatibility inference", CertificationPosture::OrdinaryProductionReachable, CostPosture::OperationalOverlapExecution, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::PlanarBooleanOverlapEdgeChainsModule, "crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/mod.rs", "overlap_edge_chains", Owner::WorthSpatial, "planar boolean edge splitting module graph", AuthorityKind::OperationalOverlapExecution, Disposition::Migrate, ReplacementPhase::PhaseFiveSelectedConflictPlan, "module entry is the current public-in-crate route to overlap-chain construction", "selected conflict planning owns the overlap-chain module boundary by named rows", CertificationPosture::OrdinaryProductionReachable, CostPosture::OperationalOverlapExecution, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::PlanarBooleanBuildOverlapEdgeChains, "crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/overlap_edge_chains/construction.rs", "PlanarBooleanIntervalSubdivisionNormalizedScheduleSet::build_overlap_edge_chains", Owner::WorthSpatial, "overlap edge chain construction", AuthorityKind::OperationalOverlapExecution, Disposition::Migrate, ReplacementPhase::PhaseFiveSelectedConflictPlan, "builder currently constructs overlap chains from normalized interval schedules and split fragments", "selected conflict plans consume overlap-chain authority through shared overlap identity", CertificationPosture::OrdinaryProductionReachable, CostPosture::OperationalOverlapExecution, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::PlanarBooleanOverlapEdgeChainSet, "crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/overlap_edge_chains/chain_set.rs", "PlanarBooleanOverlapEdgeChainSet", Owner::WorthSpatial, "overlap edge chain construction", AuthorityKind::OperationalOverlapReceipt, Disposition::Migrate, ReplacementPhase::PhaseNineExecutionReceipt, "chain set is the current prepared overlap-chain product", "execution receipt binds overlap-chain set identity and counters", CertificationPosture::OrdinaryProductionReachable, CostPosture::OperationalOverlapExecution, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::PlanarBooleanOverlapEdgeChainSetCertifiesPreparedOverlapChains, "crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/overlap_edge_chains/chain_set.rs", "PlanarBooleanOverlapEdgeChainSet::certifies_prepared_overlap_chains", Owner::WorthSpatial, "PlanarBooleanOverlapEdgeChainSet consumers", AuthorityKind::OperationalOverlapReceipt, Disposition::Migrate, ReplacementPhase::PhaseNineExecutionReceipt, "method currently certifies prepared overlap-chain products and denies topology truth emission", "execution receipt consumes prepared-chain certification as typed non-topology proof", CertificationPosture::OrdinaryProductionReachable, CostPosture::PriorProofBoundary, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::PlanarBooleanOverlapEdgeChain, "crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/overlap_edge_chains/chain_row.rs", "PlanarBooleanOverlapEdgeChain", Owner::WorthSpatial, "PlanarBooleanOverlapEdgeChainSet", AuthorityKind::OperationalOverlapReceipt, Disposition::Migrate, ReplacementPhase::PhaseNineExecutionReceipt, "chain row is the current per-overlap proof record", "execution receipt preserves per-chain participant identity", CertificationPosture::OrdinaryProductionReachable, CostPosture::OperationalOverlapExecution, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::PlanarBooleanOverlapEdgeChainMember, "crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/overlap_edge_chains/chain_member.rs", "PlanarBooleanOverlapEdgeChainMember", Owner::WorthSpatial, "PlanarBooleanOverlapEdgeChain", AuthorityKind::OperationalOverlapReceipt, Disposition::Migrate, ReplacementPhase::PhaseNineExecutionReceipt, "chain member is current fragment-level overlap participation proof", "shared conflict vocabulary names member participation without rediscovery", CertificationPosture::OrdinaryProductionReachable, CostPosture::OperationalOverlapExecution, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::PlanarBooleanOverlapEdgeChainCounters, "crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/overlap_edge_chains/counters.rs", "PlanarBooleanOverlapEdgeChainCounters", Owner::WorthSpatial, "PlanarBooleanOverlapEdgeChainSet", AuthorityKind::OperationalOverlapReceipt, Disposition::Migrate, ReplacementPhase::PhaseNineExecutionReceipt, "counters expose overlap-chain breadth and posture pressure", "batch execution receipt carries semantic breadth counters", CertificationPosture::OrdinaryProductionReachable, CostPosture::OperationalOverlapExecution, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::PlanarBooleanOverlapEdgeChainCountersPartialOverlapChains, "crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/overlap_edge_chains/counters.rs", "PlanarBooleanOverlapEdgeChainCounters::partial_overlap_chains", Owner::WorthSpatial, "PlanarBooleanOverlapEdgeChainSet::certifies_prepared_overlap_chains", AuthorityKind::OperationalOverlapReceipt, Disposition::Migrate, ReplacementPhase::PhaseNineExecutionReceipt, "counter accessor exposes partial-overlap chain breadth as current receipt metadata", "execution receipt carries equivalent typed overlap-chain posture counter", CertificationPosture::OrdinaryProductionReachable, CostPosture::OperationalOverlapExecution, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::OverlapChainIndexedInputs, "crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/overlap_edge_chains/indexed_inputs.rs", "OverlapChainIndexedInputs", Owner::WorthSpatial, "PlanarBooleanIntervalSubdivisionNormalizedScheduleSet::build_overlap_edge_chains", AuthorityKind::OperationalOverlapExecution, Disposition::Migrate, ReplacementPhase::PhaseFiveSelectedConflictPlan, "indexed input struct currently owns fragment-to-subdivision lookup for overlap-chain construction", "selected conflict plan consumes the lookup as typed construction proof instead of helper-local rediscovery", CertificationPosture::OrdinaryProductionReachable, CostPosture::OperationalOverlapExecution, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::FragmentOverlapsSubdivision, "crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/overlap_edge_chains/indexed_inputs.rs", "fragment_overlaps_subdivision", Owner::WorthSpatial, "OverlapChainIndexedInputs::new", AuthorityKind::OperationalOverlapExecution, Disposition::Migrate, ReplacementPhase::PhaseFiveSelectedConflictPlan, "helper currently admits fragment/subdivision interval overlap during chain construction", "selected conflict plan owns interval-overlap admission through typed overlap-chain inputs", CertificationPosture::OrdinaryProductionReachable, CostPosture::OperationalOverlapExecution, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::PlanarBooleanSplitChainValidationCountersOverlapChainsChecked, "crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/split_chain_validation/counters.rs", "PlanarBooleanSplitChainValidationCounters::overlap_chains_checked", Owner::WorthSpatial, "split chain validation closeout", AuthorityKind::OperationalOverlapReceipt, Disposition::Migrate, ReplacementPhase::PhaseNineExecutionReceipt, "validation counter exposes overlap-chain validation breadth as current receipt metadata", "execution receipt carries equivalent typed validation counter after selected conflict planning", CertificationPosture::OrdinaryProductionReachable, CostPosture::OperationalOverlapExecution, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::PlanarBooleanOverlapEdgeChainDenial, "crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/overlap_edge_chains/denial.rs", "PlanarBooleanOverlapEdgeChainDenial", Owner::WorthSpatial, "overlap edge chain construction", AuthorityKind::OperationalOverlapExecution, Disposition::Migrate, ReplacementPhase::PhaseFiveSelectedConflictPlan, "denial is current overlap-chain construction failure topology", "selected conflict plans preserve denial cause before execution", CertificationPosture::OrdinaryProductionReachable, CostPosture::OperationalOverlapExecution, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::PlanarBooleanOverlapEdgeChainDenialKind, "crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/overlap_edge_chains/denial.rs", "PlanarBooleanOverlapEdgeChainDenialKind", Owner::WorthSpatial, "PlanarBooleanOverlapEdgeChainDenial", AuthorityKind::OperationalOverlapExecution, Disposition::Migrate, ReplacementPhase::PhaseFiveSelectedConflictPlan, "denial kind names current overlap-chain construction failure classes", "selected conflict plans keep denial classes typed", CertificationPosture::OrdinaryProductionReachable, CostPosture::OperationalOverlapExecution, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::PlanarBooleanOverlapChainBoundaryRole, "crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/overlap_edge_chains/boundary_role.rs", "PlanarBooleanOverlapChainBoundaryRole", Owner::WorthSpatial, "PlanarBooleanOverlapEdgeChainMember", AuthorityKind::OperationalOverlapReceipt, Disposition::Migrate, ReplacementPhase::PhaseThreeConflictCatalog, "boundary role is current aspect-local overlap participation vocabulary", "shared conflict vocabulary owns equivalent boundary-role distinction", CertificationPosture::OrdinaryProductionReachable, CostPosture::PriorProofBoundary, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::PlanarBooleanOverlapChainPosture, "crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/overlap_edge_chains/boundary_role.rs", "PlanarBooleanOverlapChainPosture", Owner::WorthSpatial, "PlanarBooleanOverlapEdgeChain", AuthorityKind::OperationalOverlapReceipt, Disposition::Migrate, ReplacementPhase::PhaseThreeConflictCatalog, "chain posture is current overlap-chain semantic class", "shared conflict vocabulary owns equivalent overlap posture identity", CertificationPosture::OrdinaryProductionReachable, CostPosture::PriorProofBoundary, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
    ])
}

fn topo_certification_rows(
) -> Result<Vec<ConflictBatchAdmissionInventoryRow>, ConflictBatchAdmissionInventoryError> {
    Ok(vec![
        row(Surface::TopoEdgeSplitOverlapChainPublicContract, "crates/worth-topo/src/certification/public_facade_contracts/contracts/public_api_edge_split_blueprint.rs", "edge_split_overlap_chain_rows_are_publicly_registered_as_prepared_products", Owner::WorthTopo, "worth-topo public facade contract tests", AuthorityKind::SourceFirewallCloseout, Disposition::CertificationOnly, ReplacementPhase::NotReplacedCertificationOnly, "public facade certification names overlap-chain prepared products but cannot authorize ordinary overlap admission", "ordinary conflict admission consumes spatial overlap-chain rows; this contract remains certification-only proof", CertificationPosture::CertificationOnlyDeniedAsOrdinaryProof, CostPosture::SourceFirewallOnly, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
    ])
}

fn residue_rows(
) -> Result<Vec<ConflictBatchAdmissionInventoryRow>, ConflictBatchAdmissionInventoryError> {
    Ok(vec![
        row(Surface::BooleanChainResidueRows, "crates/worth-kernel/src/workload_composition/worth_workload/boolean_chain_handoff.rs", "BooleanChainResidueRow", Owner::WorthKernel, "BooleanChainIntegrationHandoff::residue_manifest", AuthorityKind::CutLineResidue, Disposition::Cap, ReplacementPhase::PhaseTwelveFirewallDeletion, "existing boolean chain residue is non-authority snapshot/query-proof accompaniment", "Phase 12 deletes or replaces capped residue after selected conflict and batch plans exist", CertificationPosture::NonOrdinaryResidueDeniedAsOrdinaryProof, CostPosture::CappedResidue, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::TraversalViewsOldAuthorityResidue, "crates/worth-topo/src/derived_topology/invalidation_plan/migrated_products/traversal_views/old_authority_residue.rs", "TraversalViewsOldAuthorityResidue", Owner::WorthTopo, "traversal views migration closeout", AuthorityKind::CutLineResidue, Disposition::Cap, ReplacementPhase::PhaseTwelveFirewallDeletion, "topology traversal old-authority residue remains capped and cannot satisfy ordinary conflict proof", "topology conflict families consume selected invalidation and replay/undo proof instead", CertificationPosture::NonOrdinaryResidueDeniedAsOrdinaryProof, CostPosture::CappedResidue, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
    ])
}

fn broad_scan_counter_rows(
) -> Result<Vec<ConflictBatchAdmissionInventoryRow>, ConflictBatchAdmissionInventoryError> {
    Ok(vec![
        row(Surface::ReplayScopeProductBroadReceiptScanCounter, "crates/worth-spatial/src/replay_undo_semantic_graph/scope_product/replay_scope_product_counters.rs", "SpatialReplayScopeProductCounters::broad_receipt_scan_count", Owner::WorthSpatial, "spatial replay scope product counters", AuthorityKind::CutLineResidue, Disposition::Cap, ReplacementPhase::PhaseTwelveFirewallDeletion, "replay scope still exposes broad receipt scan pressure as a capped counter", "replay scope consumes typed lookup handoff proof without broad receipt scanning", CertificationPosture::NonOrdinaryResidueDeniedAsOrdinaryProof, CostPosture::CappedResidue, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::UndoScopeProductBroadReceiptScanCounter, "crates/worth-spatial/src/replay_undo_semantic_graph/scope_product/undo_scope_product_counters.rs", "SpatialUndoScopeProductCounters::broad_receipt_scan_count", Owner::WorthSpatial, "spatial undo scope product counters", AuthorityKind::CutLineResidue, Disposition::Cap, ReplacementPhase::PhaseTwelveFirewallDeletion, "undo scope still exposes broad receipt scan pressure as a capped counter", "undo scope consumes typed lookup handoff proof without broad receipt scanning", CertificationPosture::NonOrdinaryResidueDeniedAsOrdinaryProof, CostPosture::CappedResidue, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::EvidenceLookupDiagnosticsHiddenBroadReceiptScanCounter, "crates/worth-spatial/src/workload_platform/evidence_lookup_diagnostics/counters.rs", "EvidenceLookupDiagnosticCounters::hidden_broad_receipt_scan_count", Owner::WorthSpatial, "evidence lookup diagnostics counters", AuthorityKind::CutLineResidue, Disposition::Cap, ReplacementPhase::PhaseTwelveFirewallDeletion, "diagnostics may report hidden broad-scan pressure but cannot authorize it", "diagnostics consume selected-plan counters after conflict admission replaces broad scans", CertificationPosture::NonOrdinaryResidueDeniedAsOrdinaryProof, CostPosture::CappedResidue, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::EvidenceLookupInventoryBroadScanRowCounter, "crates/worth-spatial/src/workload_platform/evidence_lookup_inventory/closeout.rs", "EvidenceLookupInventoryCloseoutCounters::broad_scan_row_count", Owner::WorthSpatial, "evidence lookup inventory closeout counters", AuthorityKind::CutLineResidue, Disposition::Cap, ReplacementPhase::PhaseTwelveFirewallDeletion, "inventory closeout counts broad-scan rows only as deletion pressure", "conflict admission consumes evidence lookup selected plans and not broad inventory scans", CertificationPosture::NonOrdinaryResidueDeniedAsOrdinaryProof, CostPosture::CappedResidue, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::EvidenceLookupSourceFirewallMentionsBroadReceiptScan, "crates/worth-spatial/src/workload_platform/evidence_lookup_source_firewall/semantic_shape.rs", "mentions_broad_receipt_scan", Owner::WorthSpatial, "evidence lookup source firewall semantic shape", AuthorityKind::CutLineResidue, Disposition::Cap, ReplacementPhase::PhaseTwelveFirewallDeletion, "semantic firewall detects broad receipt scan residue but is not ordinary authority", "Phase 12 hard deletion preserves firewall shape while conflict admission owns proof", CertificationPosture::NonOrdinaryResidueDeniedAsOrdinaryProof, CostPosture::CappedResidue, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::EvidenceLookupSourceFirewallBroadReceiptScanRowCounter, "crates/worth-spatial/src/workload_platform/evidence_lookup_source_firewall/counters.rs", "EvidenceLookupSourceFirewallCounters::broad_receipt_scan_row_count", Owner::WorthSpatial, "evidence lookup source firewall counters", AuthorityKind::CutLineResidue, Disposition::Cap, ReplacementPhase::PhaseTwelveFirewallDeletion, "source firewall counts broad receipt scan rows only as closeout pressure", "conflict admission consumes typed lookup proof products instead of firewall counters", CertificationPosture::NonOrdinaryResidueDeniedAsOrdinaryProof, CostPosture::CappedResidue, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::EvidenceLookupWorkloadCutoverBroadReceiptScanCounter, "crates/worth-spatial/src/workload_platform/evidence_lookup_workload_cutover/counters.rs", "EvidenceLookupWorkloadCutoverCounters::broad_receipt_scan_count", Owner::WorthSpatial, "evidence lookup workload cutover counters", AuthorityKind::CutLineResidue, Disposition::Cap, ReplacementPhase::PhaseTwelveFirewallDeletion, "workload cutover exposes broad receipt scan pressure as a capped denial counter", "workload cutover consumes selected lookup proof without broad receipt scans", CertificationPosture::NonOrdinaryResidueDeniedAsOrdinaryProof, CostPosture::CappedResidue, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::EvidenceLookupStageCutoverBroadReceiptScanCounter, "crates/worth-spatial/src/workload_platform/evidence_lookup_stage_cutover/counters.rs", "EvidenceLookupStageCutoverCounters::broad_receipt_scan_count", Owner::WorthSpatial, "evidence lookup stage cutover counters", AuthorityKind::CutLineResidue, Disposition::Cap, ReplacementPhase::PhaseTwelveFirewallDeletion, "stage cutover exposes broad receipt scan pressure as a capped denial counter", "stage cutover consumes selected lookup proof without broad receipt scans", CertificationPosture::NonOrdinaryResidueDeniedAsOrdinaryProof, CostPosture::CappedResidue, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::EvidenceLookupStageCutoverWithTestBroadReceiptScanCount, "crates/worth-spatial/src/workload_platform/evidence_lookup_stage_cutover/covered_stage.rs", "EvidenceLookupCoveredStageCutoverProof::with_test_broad_receipt_scan_count", Owner::WorthSpatial, "evidence lookup stage cutover test support", AuthorityKind::CutLineResidue, Disposition::CertificationOnly, ReplacementPhase::NotReplacedCertificationOnly, "test-only broad receipt counter mutation must not become ordinary admission authority", "ordinary conflict admission consumes selected proof products and denies test-only counter mutation", CertificationPosture::CertificationOnlyDeniedAsOrdinaryProof, CostPosture::SourceFirewallOnly, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::TopologyQueryBackedConsumerCutoverWithTestLoopCycleSelectedCompatibilityBasisIdentityOverride, "crates/worth-topo/src/projection/planner_owned_routing/query_backed_read_family/selected_route.rs", "TopologyQueryBackedConsumerCutover::with_test_loop_cycle_selected_compatibility_basis_identity_override", Owner::WorthTopo, "topology query-backed cutover hostile proof tests", AuthorityKind::CutLineResidue, Disposition::CertificationOnly, ReplacementPhase::NotReplacedCertificationOnly, "test-only topology cutover compatibility-basis mutation must not become ordinary public-closeout authority", "kernel public closeout consumes current topology query-backed proof products and denies test-only compatibility-basis mutation", CertificationPosture::CertificationOnlyDeniedAsOrdinaryProof, CostPosture::SourceFirewallOnly, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::EvidenceLookupPlanSelectionBroadReceiptScanCounter, "crates/worth-spatial/src/workload_platform/evidence_lookup_plan_selection/counters.rs", "EvidenceLookupPlanSelectionCounters::broad_receipt_scan_count", Owner::WorthSpatial, "evidence lookup plan selection counters", AuthorityKind::CutLineResidue, Disposition::Cap, ReplacementPhase::PhaseTwelveFirewallDeletion, "plan selection exposes broad receipt scan pressure but cannot rely on it as proof", "selected conflict plans consume evidence lookup selected plan identity and prior proof", CertificationPosture::NonOrdinaryResidueDeniedAsOrdinaryProof, CostPosture::CappedResidue, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::EvidenceLookupReuseDecisionBroadReceiptScanCounter, "crates/worth-spatial/src/workload_platform/evidence_lookup_reuse_decision/counters.rs", "EvidenceLookupReuseDecisionCounters::broad_receipt_scan_count", Owner::WorthSpatial, "evidence lookup reuse decision counters", AuthorityKind::CutLineResidue, Disposition::Cap, ReplacementPhase::PhaseTwelveFirewallDeletion, "reuse decisions still expose broad receipt scan pressure as a capped counter and cannot authorize fallback", "query-backed public closeout consumes typed reuse decisions while preserving zero-broad-scan denial posture", CertificationPosture::NonOrdinaryResidueDeniedAsOrdinaryProof, CostPosture::CappedResidue, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::EvidenceLookupReuseExecutionInputBroadReceiptScanCounter, "crates/worth-spatial/src/workload_platform/evidence_lookup_reuse_decision/execution_input.rs", "EvidenceLookupIndexReuseExecutionInput::broad_receipt_scan_count", Owner::WorthSpatial, "evidence lookup reuse execution input", AuthorityKind::CutLineResidue, Disposition::Cap, ReplacementPhase::PhaseTwelveFirewallDeletion, "reuse execution input still exposes broad receipt scan pressure as a lowered counter and cannot authorize fallback", "query-backed public closeout consumes typed reuse execution proof while preserving zero-broad-scan denial posture", CertificationPosture::NonOrdinaryResidueDeniedAsOrdinaryProof, CostPosture::CappedResidue, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::ReplayUndoSpatialBoundaryFixtureWithTestBroadReceiptScanCount, "crates/worth-spatial/src/replay_undo_semantic_graph/test_support.rs", "ReplayUndoSpatialBoundaryFixture::workload_handoff_with_test_broad_receipt_scan_count", Owner::WorthSpatial, "replay/undo spatial boundary test support", AuthorityKind::CutLineResidue, Disposition::CertificationOnly, ReplacementPhase::NotReplacedCertificationOnly, "test-only replay/undo handoff broad-scan mutation must not become ordinary admission authority", "ordinary conflict admission consumes selected lookup proof products and denies replay/undo test-only broad-scan mutation", CertificationPosture::CertificationOnlyDeniedAsOrdinaryProof, CostPosture::SourceFirewallOnly, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::EvidenceLookupConsumedWorkloadHandoffWithTestBroadReceiptScanCount, "crates/worth-spatial/src/workload_platform/evidence_lookup_workload_cutover/handoff.rs", "EvidenceLookupConsumedWorkloadHandoff::with_test_broad_receipt_scan_count", Owner::WorthSpatial, "evidence lookup workload handoff test support", AuthorityKind::CutLineResidue, Disposition::CertificationOnly, ReplacementPhase::NotReplacedCertificationOnly, "test-only lookup handoff broad-scan mutation must not become ordinary admission authority", "ordinary conflict admission consumes selected lookup proof products and denies lookup-handoff test-only broad-scan mutation", CertificationPosture::CertificationOnlyDeniedAsOrdinaryProof, CostPosture::SourceFirewallOnly, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::SpatialTouchBroadLedgerScanCounter, "crates/worth-spatial/src/workload_platform/evidence_ledger/spatial_touch_admission/query_lowering/counters.rs", "SpatialEvidenceQueryLoweringCounters::broad_ledger_scan_count", Owner::WorthSpatial, "spatial touch query lowering counters", AuthorityKind::CutLineResidue, Disposition::Cap, ReplacementPhase::PhaseTwelveFirewallDeletion, "spatial touch broad ledger scan counter is bounded denial evidence", "spatial conflict admission consumes sealed touch authority without ledger scans", CertificationPosture::NonOrdinaryResidueDeniedAsOrdinaryProof, CostPosture::CappedResidue, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
    ])
}

fn rollback_admission_rows(
) -> Result<Vec<ConflictBatchAdmissionInventoryRow>, ConflictBatchAdmissionInventoryError> {
    Ok(vec![
        row(Surface::SpatialRollbackBooleanEventLedgerAdmission, "crates/worth-spatial/src/replay_undo_semantic_graph/undo_family_execution/rollback_admission.rs", "lower_spatial_undo_scope_product_from_boolean_event_ledger_request", Owner::WorthSpatial, "spatial undo rollback execution", AuthorityKind::ReplayUndoBoundaryAdmission, Disposition::Migrate, ReplacementPhase::PhaseFourAdmittedConflictInput, "rollback admission lowers boolean-event ledger requests into undo scope proof before conflict routing exists", "admitted conflict input consumes rollback scope product proof without re-opening local admission", CertificationPosture::OrdinaryProductionReachable, CostPosture::PriorProofBoundary, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::SpatialRollbackProjectionReceiptAdmission, "crates/worth-spatial/src/replay_undo_semantic_graph/undo_family_execution/rollback_admission.rs", "lower_spatial_undo_scope_product_from_projection_receipt_request", Owner::WorthSpatial, "spatial undo rollback execution", AuthorityKind::ReplayUndoBoundaryAdmission, Disposition::Migrate, ReplacementPhase::PhaseFourAdmittedConflictInput, "rollback admission lowers projection receipt requests into undo scope proof before conflict routing exists", "admitted conflict input consumes rollback scope product proof without projection-local rediscovery", CertificationPosture::OrdinaryProductionReachable, CostPosture::PriorProofBoundary, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::TopologyRollbackTraversalViewsAdmission, "crates/worth-topo/src/replay_undo_semantic_graph/undo_family_execution/rollback_admission.rs", "lower_topology_undo_scope_product_from_traversal_views_request", Owner::WorthTopo, "topology undo rollback execution", AuthorityKind::ReplayUndoBoundaryAdmission, Disposition::Migrate, ReplacementPhase::PhaseFourAdmittedConflictInput, "rollback admission lowers traversal-view requests into topology undo scope proof before conflict routing exists", "admitted conflict input consumes topology rollback proof without traversal-local admission", CertificationPosture::OrdinaryProductionReachable, CostPosture::PriorProofBoundary, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::TopologyRollbackMaterializedGraphAdmission, "crates/worth-topo/src/replay_undo_semantic_graph/undo_family_execution/rollback_admission.rs", "lower_topology_undo_scope_product_from_materialized_graph_request", Owner::WorthTopo, "topology undo rollback execution", AuthorityKind::ReplayUndoBoundaryAdmission, Disposition::Migrate, ReplacementPhase::PhaseFourAdmittedConflictInput, "rollback admission lowers materialized-graph requests into topology undo scope proof before conflict routing exists", "admitted conflict input consumes topology rollback proof without materialized-graph-local admission", CertificationPosture::OrdinaryProductionReachable, CostPosture::PriorProofBoundary, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
    ])
}

fn row(
    surface_identity: Surface,
    source_path: &'static str,
    surface_name: &'static str,
    owner: Owner,
    current_caller: &'static str,
    authority_kind: AuthorityKind,
    disposition: Disposition,
    replacement_phase: ReplacementPhase,
    blocker: &'static str,
    removal_trigger: &'static str,
    certification_posture: CertificationPosture,
    cost_posture: CostPosture,
    query_surface: QuerySurface,
    row_scope: RowScope,
) -> Result<ConflictBatchAdmissionInventoryRow, ConflictBatchAdmissionInventoryError> {
    ConflictBatchAdmissionInventoryRow::builder()
        .surface_identity(surface_identity)
        .source_path(source_path)
        .surface_name(surface_name)
        .owner(owner)
        .current_caller(current_caller)
        .authority_kind(authority_kind)
        .disposition(disposition)
        .replacement_phase(replacement_phase)
        .blocker(blocker)
        .removal_trigger(removal_trigger)
        .certification_posture(certification_posture)
        .cost_posture(cost_posture)
        .query_surface(query_surface)
        .row_scope(row_scope)
        .build()
}
