use super::error::ConflictBatchAdmissionInventoryError;
use super::row::{
    ConflictBatchAdmissionAuthorityKind as AuthorityKind,
    ConflictBatchAdmissionCertificationPosture as CertificationPosture,
    ConflictBatchAdmissionCostPosture as CostPosture,
    ConflictBatchAdmissionDisposition as Disposition, ConflictBatchAdmissionInventoryRow,
    ConflictBatchAdmissionOwner as Owner, ConflictBatchAdmissionQuerySurface as QuerySurface,
    ConflictBatchAdmissionReplacementPhase as ReplacementPhase,
    ConflictBatchAdmissionRowScope as RowScope, ConflictBatchAdmissionSurfaceIdentity as Surface,
};

pub(crate) fn spatial_compatibility_inventory_rows(
) -> Result<Vec<ConflictBatchAdmissionInventoryRow>, ConflictBatchAdmissionInventoryError> {
    Ok(vec![
        row(Surface::EvidenceLookupIndexProductSelectedCompatibilityBasisIdentityDigest, "crates/worth-spatial/src/workload_platform/evidence_lookup_index_product/product.rs", "EvidenceLookupIndexProduct::selected_compatibility_basis_identity_digest", Owner::WorthSpatial, "current_evidence_lookup_public_closeout", AuthorityKind::CompatibilityPostureAdmission, Disposition::Migrate, ReplacementPhase::PhaseThirteenPublicReadCloseoutCutover, "evidence lookup index products currently expose selected compatibility basis through a caller-owned product accessor", "public closeout and query-backed consumers consume the same compatibility basis through typed reuse and closeout products", CertificationPosture::OrdinaryProductionReachable, CostPosture::ReceiptBackedTypedLookup, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::EvidenceLookupIndexProductSelectedCompatibilityPosture, "crates/worth-spatial/src/workload_platform/evidence_lookup_index_product/product.rs", "EvidenceLookupIndexProduct::selected_compatibility_posture", Owner::WorthSpatial, "current_evidence_lookup_public_closeout", AuthorityKind::CompatibilityPostureAdmission, Disposition::Migrate, ReplacementPhase::PhaseThirteenPublicReadCloseoutCutover, "evidence lookup index products currently expose selected compatibility posture through a caller-owned product accessor", "public closeout and query-backed consumers consume typed compatibility posture through closeout and reuse products", CertificationPosture::OrdinaryProductionReachable, CostPosture::ReceiptBackedTypedLookup, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::EvidenceLookupIndexReuseDecisionSelectedCompatibilityBasisIdentityDigest, "crates/worth-spatial/src/workload_platform/evidence_lookup_reuse_decision/decision.rs", "EvidenceLookupIndexReuseDecision::selected_compatibility_basis_identity_digest", Owner::WorthSpatial, "current_evidence_lookup_public_closeout", AuthorityKind::CompatibilityPostureAdmission, Disposition::Migrate, ReplacementPhase::PhaseThirteenPublicReadCloseoutCutover, "evidence lookup reuse decisions currently expose selected compatibility basis through a local decision carrier", "public closeout and query-backed consumers consume typed reuse decisions without rebuilding compatibility folklore locally", CertificationPosture::OrdinaryProductionReachable, CostPosture::ReceiptBackedTypedLookup, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::EvidenceLookupIndexRebuildDenialSelectedCompatibilityBasisIdentityDigest, "crates/worth-spatial/src/workload_platform/evidence_lookup_reuse_decision/denial.rs", "EvidenceLookupIndexRebuildDenial::selected_compatibility_basis_identity_digest", Owner::WorthSpatial, "current_evidence_lookup_public_closeout", AuthorityKind::CompatibilityPostureAdmission, Disposition::Migrate, ReplacementPhase::PhaseThirteenPublicReadCloseoutCutover, "evidence lookup rebuild denials currently expose selected compatibility basis through a local denial carrier", "public closeout and query-backed consumers consume typed denial proof instead of historical stability assumptions", CertificationPosture::OrdinaryProductionReachable, CostPosture::ReceiptBackedTypedLookup, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::SelectedSpatialEquivalenceFamilyCompatibilityBasisIdentity, "crates/worth-spatial/src/workload_platform/selected_equivalence_family/selected_family.rs", "SelectedSpatialEquivalenceFamily::compatibility_basis_identity", Owner::WorthSpatial, "EvidenceLookupIndexProduct::new", AuthorityKind::CompatibilityPostureAdmission, Disposition::Migrate, ReplacementPhase::PhaseThirteenPublicReadCloseoutCutover, "selected spatial family currently exposes compatibility basis through a local accessor", "public closeout and query-backed consumers consume selected family compatibility through typed product and closeout proof", CertificationPosture::OrdinaryProductionReachable, CostPosture::PriorProofBoundary, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::SelectedSpatialEquivalenceFamilyCompatibilityPosture, "crates/worth-spatial/src/workload_platform/selected_equivalence_family/selected_family.rs", "SelectedSpatialEquivalenceFamily::compatibility_posture", Owner::WorthSpatial, "EvidenceLookupIndexProduct::selected_compatibility_posture", AuthorityKind::CompatibilityPostureAdmission, Disposition::Migrate, ReplacementPhase::PhaseThirteenPublicReadCloseoutCutover, "selected spatial family currently exposes compatibility posture as a local accessor", "public closeout and query-backed consumers consume compatibility posture through typed selected-family and closeout proof", CertificationPosture::OrdinaryProductionReachable, CostPosture::PriorProofBoundary, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::SpatialSelectedCompatibilityBasisIdentityStruct, "crates/worth-spatial/src/workload_platform/selected_equivalence_family/basis_identity.rs", "SpatialSelectedCompatibilityBasisIdentity", Owner::WorthSpatial, "SelectedSpatialEquivalenceFamily::compatibility_basis_identity", AuthorityKind::CompatibilityPostureAdmission, Disposition::Migrate, ReplacementPhase::PhaseThirteenPublicReadCloseoutCutover, "selected spatial compatibility basis still exists as a local identity carrier", "public closeout and query-backed consumers consume compatibility identity through typed selected-family and reuse products", CertificationPosture::OrdinaryProductionReachable, CostPosture::PriorProofBoundary, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::SpatialSelectedCompatibilityBasisIdentityIdentityDigest, "crates/worth-spatial/src/workload_platform/selected_equivalence_family/basis_identity.rs", "SpatialSelectedCompatibilityBasisIdentity::identity_digest", Owner::WorthSpatial, "SelectedSpatialEquivalenceFamily::compatibility_basis_identity", AuthorityKind::CompatibilityPostureAdmission, Disposition::Migrate, ReplacementPhase::PhaseThirteenPublicReadCloseoutCutover, "selected spatial compatibility basis currently exposes its digest as a local accessor", "public closeout and query-backed consumers consume the same digest through typed selected-family and reuse products", CertificationPosture::OrdinaryProductionReachable, CostPosture::PriorProofBoundary, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::SpatialSelectedEquivalenceFamilyDeclarationCompatibilityPosture, "crates/worth-spatial/src/workload_platform/selected_equivalence_family/declaration.rs", "SpatialSelectedEquivalenceFamilyDeclaration::compatibility_posture", Owner::WorthSpatial, "SelectedSpatialEquivalenceFamily::compatibility_posture", AuthorityKind::CompatibilityPostureAdmission, Disposition::Migrate, ReplacementPhase::PhaseThirteenPublicReadCloseoutCutover, "selected spatial family declarations currently expose compatibility posture directly", "typed selected-family and closeout proof consume declaration posture without local support folklore", CertificationPosture::OrdinaryProductionReachable, CostPosture::PriorProofBoundary, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::SpatialCompatibilityPostureEnum, "crates/worth-spatial/src/workload_platform/selected_equivalence_family/posture.rs", "SpatialCompatibilityPosture", Owner::WorthSpatial, "SelectedSpatialEquivalenceFamily::compatibility_posture", AuthorityKind::CompatibilityPostureAdmission, Disposition::Migrate, ReplacementPhase::PhaseThirteenPublicReadCloseoutCutover, "selected spatial compatibility posture enum currently carries local compatibility semantics", "public closeout and query-backed consumers consume the same posture through typed selected-family and reuse products", CertificationPosture::OrdinaryProductionReachable, CostPosture::PriorProofBoundary, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::HighValenceRebuildMotionCompatibilitySetter, "crates/worth-spatial/src/workload_platform/high_valence_singularity/singularity_workload.rs", "HighValenceSingularityWorkload::requiring_rebuild_motion_compatibility", Owner::WorthSpatial, "high-valence singularity workload construction", AuthorityKind::CompatibilityPostureAdmission, Disposition::Migrate, ReplacementPhase::PhaseFiveSelectedConflictPlan, "builder method carries caller-selected rebuild-motion compatibility before selected conflict planning owns posture", "selected conflict plan consumes typed compatibility posture instead of workload-local caller selection", CertificationPosture::OrdinaryProductionReachable, CostPosture::PriorProofBoundary, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::HighValenceRequireRebuildMotionCompatibility, "crates/worth-spatial/src/workload_platform/high_valence_singularity/singularity_workload.rs", "HighValenceSingularityWorkload::require_rebuild_motion_compatibility", Owner::WorthSpatial, "HighValenceSingularityWorkload::certify", AuthorityKind::CompatibilityPostureAdmission, Disposition::Migrate, ReplacementPhase::PhaseFiveSelectedConflictPlan, "certification currently denies incompatible rebuild motion through workload-local compatibility checks", "selected conflict plan carries the compatibility denial as admitted conflict posture", CertificationPosture::OrdinaryProductionReachable, CostPosture::PriorProofBoundary, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::HighValenceRebuildMotionCompatibility, "crates/worth-spatial/src/workload_platform/high_valence_singularity/singularity_workload.rs", "HighValenceRebuildMotionCompatibility", Owner::WorthSpatial, "high-valence singularity workload certification", AuthorityKind::CompatibilityPostureAdmission, Disposition::Migrate, ReplacementPhase::PhaseFiveSelectedConflictPlan, "enum is the current rebuild-motion compatibility truth carrier for high-valence admission", "selected conflict plan owns compatibility proof identity and denial topology", CertificationPosture::OrdinaryProductionReachable, CostPosture::PriorProofBoundary, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::DuplicateSplitRejectContradictorySameParameterPoints, "crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/duplicate_split_normalization/contradiction_basis.rs", "reject_contradictory_same_parameter_points", Owner::WorthSpatial, "duplicate split normalization", AuthorityKind::CompatibilityPostureAdmission, Disposition::Migrate, ReplacementPhase::PhaseFiveSelectedConflictPlan, "normalization currently rejects contradictory same-parameter compatibility as helper-local conflict denial", "selected conflict plan consumes duplicate-split compatibility basis before normalization executes", CertificationPosture::OrdinaryProductionReachable, CostPosture::OperationalOverlapExecution, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::PointSplitCompatibilityBasis, "crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/duplicate_split_normalization/contradiction_basis.rs", "PointSplitCompatibilityBasis", Owner::WorthSpatial, "reject_contradictory_same_parameter_points", AuthorityKind::CompatibilityPostureAdmission, Disposition::Migrate, ReplacementPhase::PhaseFiveSelectedConflictPlan, "basis struct is the helper-local compatibility key used to deny contradictory duplicate split points", "selected conflict plan names duplicate-split compatibility basis explicitly", CertificationPosture::OrdinaryProductionReachable, CostPosture::OperationalOverlapExecution, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
    ])
}

fn row(
    surface_identity: Surface,
    source_path: &'static str,
    surface_name: &'static str,
    owner: Owner,
    current_caller: &'static str,
    authority_kind: AuthorityKind,
    disposition: Disposition,
    replacement_phase: ReplacementPhase,
    blocker: &'static str,
    removal_trigger: &'static str,
    certification_posture: CertificationPosture,
    cost_posture: CostPosture,
    query_surface: QuerySurface,
    row_scope: RowScope,
) -> Result<ConflictBatchAdmissionInventoryRow, ConflictBatchAdmissionInventoryError> {
    ConflictBatchAdmissionInventoryRow::builder()
        .surface_identity(surface_identity)
        .source_path(source_path)
        .surface_name(surface_name)
        .owner(owner)
        .current_caller(current_caller)
        .authority_kind(authority_kind)
        .disposition(disposition)
        .replacement_phase(replacement_phase)
        .blocker(blocker)
        .removal_trigger(removal_trigger)
        .certification_posture(certification_posture)
        .cost_posture(cost_posture)
        .query_surface(query_surface)
        .row_scope(row_scope)
        .build()
}
