use super::error::ConflictBatchAdmissionInventoryError;
use super::row::{
    ConflictBatchAdmissionAuthorityKind as AuthorityKind,
    ConflictBatchAdmissionCertificationPosture as CertificationPosture,
    ConflictBatchAdmissionCostPosture as CostPosture,
    ConflictBatchAdmissionDisposition as Disposition, ConflictBatchAdmissionInventoryRow,
    ConflictBatchAdmissionOwner as Owner, ConflictBatchAdmissionQuerySurface as QuerySurface,
    ConflictBatchAdmissionReplacementPhase as ReplacementPhase,
    ConflictBatchAdmissionRowScope as RowScope, ConflictBatchAdmissionSurfaceIdentity as Surface,
};

pub(crate) fn topology_compatibility_inventory_rows(
) -> Result<Vec<ConflictBatchAdmissionInventoryRow>, ConflictBatchAdmissionInventoryError> {
    Ok(vec![
        row(Surface::LookupConsumedReuseResolutionSelectedCompatibilityBasisIdentityDigest, "crates/worth-kernel/src/workload_composition/worth_workload/lookup_consumed_workload/reuse_resolution_denial.rs", "LookupConsumedWorkloadReuseResolutionDenied::selected_compatibility_basis_identity_digest", Owner::WorthKernel, "LookupConsumedWorkloadComposition::admit_lookup_reuse_resolution", AuthorityKind::CompatibilityPostureAdmission, Disposition::Migrate, ReplacementPhase::PhaseThirteenPublicReadCloseoutCutover, "lookup-consumed denial currently exposes selected compatibility basis as a caller-owned compatibility accessor", "consumer sweep and public closeout consume typed denial proof without local compatibility folklore", CertificationPosture::OrdinaryProductionReachable, CostPosture::ReceiptBackedTypedLookup, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::TopologyDerivedReuseDecisionSelectedCompatibilityBasisIdentityDigest, "crates/worth-topo/src/compiled_product_reuse_decision/decision.rs", "TopologyDerivedReuseDecision::selected_compatibility_basis_identity_digest", Owner::WorthTopo, "admit_topology_query_backed_consumer_cutover", AuthorityKind::CompatibilityPostureAdmission, Disposition::Migrate, ReplacementPhase::PhaseFiveSelectedConflictPlan, "topology derived reuse decisions currently expose selected compatibility basis through a local reuse decision carrier", "query-backed cutover and public closeout consume typed read-model reuse posture instead of rendered-row coincidence", CertificationPosture::OrdinaryProductionReachable, CostPosture::ReceiptBackedTypedLookup, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::TopologyDerivedRebuildDenialSelectedCompatibilityBasisIdentityDigest, "crates/worth-topo/src/compiled_product_reuse_decision/denial.rs", "TopologyDerivedRebuildDenial::selected_compatibility_basis_identity_digest", Owner::WorthTopo, "admit_topology_query_backed_consumer_cutover", AuthorityKind::CompatibilityPostureAdmission, Disposition::Migrate, ReplacementPhase::PhaseFiveSelectedConflictPlan, "topology rebuild denials currently expose selected compatibility basis through a local denial carrier", "query-backed cutover and public closeout consume typed rebuild proof instead of historical stability folklore", CertificationPosture::OrdinaryProductionReachable, CostPosture::ReceiptBackedTypedLookup, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::TopologyDerivedReuseExecutionInputSelectedCompatibilityBasisIdentityDigest, "crates/worth-topo/src/compiled_product_reuse_decision/execution_input.rs", "TopologyDerivedReuseExecutionInput::selected_compatibility_basis_identity_digest", Owner::WorthTopo, "admit_topology_query_backed_consumer_cutover", AuthorityKind::CompatibilityPostureAdmission, Disposition::Migrate, ReplacementPhase::PhaseFiveSelectedConflictPlan, "topology derived reuse execution input currently exposes selected compatibility basis as a lowered local accessor", "query-backed cutover and public closeout consume lowered reuse proof without local compatibility reconstruction", CertificationPosture::OrdinaryProductionReachable, CostPosture::ReceiptBackedTypedLookup, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::DerivedEquivalenceContractReportSelectedCompatibilityBasisIdentityDigest, "crates/worth-topo/src/derived_topology/compiled_product_consumer_cutover/topology_derived_cluster/admitted_contract.rs", "DerivedEquivalenceContractReport::selected_compatibility_basis_identity_digest", Owner::WorthTopo, "admit_topology_query_backed_consumer_cutover", AuthorityKind::CompatibilityPostureAdmission, Disposition::Migrate, ReplacementPhase::PhaseFiveSelectedConflictPlan, "derived topology contract reports currently surface selected compatibility basis as a local proof accessor", "query-backed cutover and public closeout consume typed contract proof rather than local rendered-row stability", CertificationPosture::OrdinaryProductionReachable, CostPosture::ReceiptBackedTypedLookup, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::TopologySelectedCompatibilityBasisIdentityStruct, "crates/worth-topo/src/selected_equivalence_family/basis_identity.rs", "TopologySelectedCompatibilityBasisIdentity", Owner::WorthTopo, "SelectedTopologyEquivalenceFamily::compatibility_basis_identity", AuthorityKind::CompatibilityPostureAdmission, Disposition::Migrate, ReplacementPhase::PhaseFiveSelectedConflictPlan, "selected topology equivalence still names compatibility basis through a local identity carrier", "query-backed cutover and public closeout consume selected compatibility identity through typed reuse proof products", CertificationPosture::OrdinaryProductionReachable, CostPosture::PriorProofBoundary, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::TopologySelectedCompatibilityBasisIdentityIdentityDigest, "crates/worth-topo/src/selected_equivalence_family/basis_identity.rs", "TopologySelectedCompatibilityBasisIdentity::identity_digest", Owner::WorthTopo, "SelectedTopologyEquivalenceFamily::compatibility_basis_identity", AuthorityKind::CompatibilityPostureAdmission, Disposition::Migrate, ReplacementPhase::PhaseFiveSelectedConflictPlan, "selected topology compatibility basis currently exposes its digest as a local accessor", "query-backed cutover and public closeout consume the same digest through typed selected-family and reuse products", CertificationPosture::OrdinaryProductionReachable, CostPosture::PriorProofBoundary, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::SelectedTopologyEquivalenceFamilyCompatibilityBasisIdentity, "crates/worth-topo/src/selected_equivalence_family/selected_family.rs", "SelectedTopologyEquivalenceFamily::compatibility_basis_identity", Owner::WorthTopo, "admit_topology_query_backed_consumer_cutover", AuthorityKind::CompatibilityPostureAdmission, Disposition::Migrate, ReplacementPhase::PhaseFiveSelectedConflictPlan, "selected topology family currently exposes compatibility basis through a local accessor", "query-backed cutover consumes selected family compatibility through typed compiled-product proof", CertificationPosture::OrdinaryProductionReachable, CostPosture::PriorProofBoundary, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::SelectedTopologyEquivalenceFamilyCompatibilityPosture, "crates/worth-topo/src/selected_equivalence_family/selected_family.rs", "SelectedTopologyEquivalenceFamily::compatibility_posture", Owner::WorthTopo, "admit_topology_query_backed_consumer_cutover", AuthorityKind::CompatibilityPostureAdmission, Disposition::Migrate, ReplacementPhase::PhaseFiveSelectedConflictPlan, "selected topology family currently exposes compatibility posture as a local accessor", "query-backed cutover consumes selected compatibility posture through typed proof products", CertificationPosture::OrdinaryProductionReachable, CostPosture::PriorProofBoundary, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::TopologySelectedEquivalenceFamilyDeclarationCompatibilityPosture, "crates/worth-topo/src/selected_equivalence_family/declaration.rs", "TopologySelectedEquivalenceFamilyDeclaration::compatibility_posture", Owner::WorthTopo, "SelectedTopologyEquivalenceFamily::compatibility_posture", AuthorityKind::CompatibilityPostureAdmission, Disposition::Migrate, ReplacementPhase::PhaseFiveSelectedConflictPlan, "selected family declarations currently expose compatibility posture directly", "typed selected-family proof consumes declaration posture without local support folklore", CertificationPosture::OrdinaryProductionReachable, CostPosture::PriorProofBoundary, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::TopologySelectedEquivalenceComparatorContractCompatibilityPosture, "crates/worth-topo/src/selected_equivalence_family/comparator_contract.rs", "TopologySelectedEquivalenceComparatorContract::compatibility_posture", Owner::WorthTopo, "admit_topology_query_backed_consumer_cutover", AuthorityKind::CompatibilityPostureAdmission, Disposition::Migrate, ReplacementPhase::PhaseFiveSelectedConflictPlan, "selected comparator contracts currently expose compatibility posture directly", "query-backed cutover consumes comparator posture through typed selected-family proof instead of local interpretation", CertificationPosture::OrdinaryProductionReachable, CostPosture::PriorProofBoundary, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::TopologyCompatibilityPostureEnum, "crates/worth-topo/src/selected_equivalence_family/posture.rs", "TopologyCompatibilityPosture", Owner::WorthTopo, "SelectedTopologyEquivalenceFamily::compatibility_posture", AuthorityKind::CompatibilityPostureAdmission, Disposition::Migrate, ReplacementPhase::PhaseFiveSelectedConflictPlan, "selected topology compatibility posture enum currently carries local compatibility semantics", "query-backed cutover and public closeout consume the same posture through typed selected-family and reuse products", CertificationPosture::OrdinaryProductionReachable, CostPosture::PriorProofBoundary, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::TopologyQueryBackedConsumerFamilyRowSelectedCompatibilityBasisIdentityDigest, "crates/worth-topo/src/projection/planner_owned_routing/query_backed_read_family/selected_route.rs", "TopologyQueryBackedConsumerFamilyRow::selected_compatibility_basis_identity_digest", Owner::WorthTopo, "current_worth_touched_graph_conflict_public_closeout current_evidence_lookup_public_closeout", AuthorityKind::CompatibilityPostureAdmission, Disposition::Migrate, ReplacementPhase::PhaseThirteenPublicReadCloseoutCutover, "phase-13 topology query-backed consumer rows now expose selected compatibility basis through a typed public/read-model cutover accessor", "kernel and spatial public closeout consume this typed Query-backed compatibility proof directly instead of reopening local compatibility folklore", CertificationPosture::OrdinaryProductionReachable, CostPosture::ReceiptBackedTypedLookup, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::TopologyQueryBackedReadFamilyAdmissionAuthoritySelectedCompatibilityBasisDigestForAdmission, "crates/worth-topo/src/projection/planner_owned_routing/query_backed_read_family/admitted_route.rs", "TopologyQueryBackedReadFamilyAdmissionAuthority::selected_compatibility_basis_digest_for_admission", Owner::WorthTopo, "admit_topology_query_backed_read_family_route_with_authority", AuthorityKind::CompatibilityPostureAdmission, Disposition::Migrate, ReplacementPhase::PhaseThirteenPublicReadCloseoutCutover, "planner-owned topo route admission now carries selected compatibility basis through an internal packet-aligned authority product before selected-route packet lowering", "topo route admission and hostile packet-mismatch proof consume the typed admission authority directly instead of reopening local closeout folklore", CertificationPosture::OrdinaryProductionReachable, CostPosture::ReceiptBackedTypedLookup, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::WorthTouchedGraphConflictProofChainTopologyQuerySelectedCompatibilityBasisIdentityDigest, "crates/worth-kernel/src/workload_composition/public_closeout/proof_chain.rs", "WorthTouchedGraphConflictProofChain::topology_query_selected_compatibility_basis_identity_digest", Owner::WorthKernel, "current_worth_touched_graph_conflict_public_closeout", AuthorityKind::CompatibilityPostureAdmission, Disposition::Migrate, ReplacementPhase::PhaseThirteenPublicReadCloseoutCutover, "kernel public closeout proof chain now publishes topology selected compatibility basis through a typed public closeout accessor", "public closeout consumers receive the typed Query-backed compatibility proof directly from the kernel proof chain instead of reopening local compatibility folklore", CertificationPosture::OrdinaryProductionReachable, CostPosture::ReceiptBackedTypedLookup, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
        row(Surface::WorthTouchedGraphConflictMilestoneFourteenSeedTopologyQuerySelectedCompatibilityBasisIdentityDigest, "crates/worth-kernel/src/workload_composition/public_closeout/milestone_fifteen_seed.rs", "WorthTouchedGraphConflictMilestoneFifteenSeed::topology_query_selected_compatibility_basis_identity_digest", Owner::WorthKernel, "current_worth_touched_graph_conflict_milestone_fifteen_seed", AuthorityKind::CompatibilityPostureAdmission, Disposition::Migrate, ReplacementPhase::PhaseThirteenPublicReadCloseoutCutover, "kernel Milestone 15 seed now publishes topology selected compatibility basis through a typed public proof seed accessor", "future public proof consumers inherit the typed Query-backed compatibility basis from the seed instead of rebuilding it from local stability folklore", CertificationPosture::OrdinaryProductionReachable, CostPosture::ReceiptBackedTypedLookup, QuerySurface::NotQuery, RowScope::ConcreteSource)?,
    ])
}

fn row(
    surface_identity: Surface,
    source_path: &'static str,
    surface_name: &'static str,
    owner: Owner,
    current_caller: &'static str,
    authority_kind: AuthorityKind,
    disposition: Disposition,
    replacement_phase: ReplacementPhase,
    blocker: &'static str,
    removal_trigger: &'static str,
    certification_posture: CertificationPosture,
    cost_posture: CostPosture,
    query_surface: QuerySurface,
    row_scope: RowScope,
) -> Result<ConflictBatchAdmissionInventoryRow, ConflictBatchAdmissionInventoryError> {
    ConflictBatchAdmissionInventoryRow::builder()
        .surface_identity(surface_identity)
        .source_path(source_path)
        .surface_name(surface_name)
        .owner(owner)
        .current_caller(current_caller)
        .authority_kind(authority_kind)
        .disposition(disposition)
        .replacement_phase(replacement_phase)
        .blocker(blocker)
        .removal_trigger(removal_trigger)
        .certification_posture(certification_posture)
        .cost_posture(cost_posture)
        .query_surface(query_surface)
        .row_scope(row_scope)
        .build()
}
