//! Mounted identity and surface-binding observations.

pub use crate::mounting::{
    UiHostPresentationReconciliation, UiHostSurfaceBaselineReceipt, UiHostSurfaceIdentity,
    UiHostSurfacePresentationMode, UiMountIncarnation, UiMountedFrameIdentity,
    UiMountedFrameIdentityView, UiMountedFrameOutcome, UiMountedFramePreparationDenial,
    UiMountedFramePublicationReceipt, UiMountedFrameReceipt, UiMountedFrameRequest,
    UiMountedFrameReuseWitness, UiMountedGraphNodeHandle, UiMountedGraphWorldIdentity,
    UiMountedIdentityBasis, UiMountedIdentityDenial, UiMountedIdentityView,
    UiMountedIndeterminateFrame, UiMountedInstanceIdentity, UiMountedInstanceIdentityView,
    UiMountedNodeReceipt, UiMountedNodeReceiptIdentity, UiMountedPresentationAdmission,
    UiMountedPresentationAdmissionDenial, UiMountedPresentationAdmissionRejection,
    UiMountedPresentationAttempt, UiMountedPresentationCompletionDenial,
    UiMountedPresentationInFlight, UiMountedPresentationOutcome, UiMountedPresentationReceipt,
    UiMountedPresentationShutdownAttempt, UiMountedPresentationShutdownDisposition,
    UiMountedPresentationShutdownReport, UiMountedPresentationWitness, UiMountedPresentedFrame,
    UiMountedProjectionAudience, UiMountedProjectionDenial, UiMountedProjectionFrame,
    UiMountedPublicationLeaseDenial, UiMountedRejectedFrame, UiMountedSurfacePresentationReceipt,
    UiMountedSurfacePresentationRejection, UiMountedSurfaceReceipt,
    UiMountedSurfaceReconciliationBinding, UiPreparedMountedFrame,
    UiPresentationIndeterminateReport, UiProjectedMountedFrameCandidate, UiSemanticSurfaceIdentity,
    UiSurfaceBindingCoordinatePosture, UiSurfaceBindingGeneration, UiSurfaceBindingIdentityView,
    UiSurfaceBindingProfile,
};
pub use worth_ui_host_contract::{
    UiHeadlessMountedResourceHandle, UiHostPresentationCompletionToken,
    UiHostSurfaceCancellationOutcome, UiHostSurfaceInFlightCompletion,
    UiHostSurfacePresentationDenial, UiHostSurfacePresentationOutcome,
    UiMountedAccessibilityProjection, UiMountedAllocationBasis, UiMountedAllocationProjection,
    UiMountedCanonicalBox, UiMountedCanonicalBoxInput, UiMountedClipProjection,
    UiMountedClipReference, UiMountedClipRow, UiMountedClipTable, UiMountedCompletedEffects,
    UiMountedCoordinateSpace, UiMountedDiagnosticProjection, UiMountedDiagnosticReference,
    UiMountedEffectFamily, UiMountedFrameCanonicalCore, UiMountedFrameIntegrity,
    UiMountedFrameManifest, UiMountedGeometryDenial, UiMountedGeometryPosture,
    UiMountedLaneParticipation, UiMountedLayerProjection, UiMountedLayerReference,
    UiMountedLayerRow, UiMountedLayerTable, UiMountedMotionProjection, UiMountedNodeProjectionView,
    UiMountedOmissionReason, UiMountedPaintBatchReference, UiMountedPaintBatchRow,
    UiMountedPaintBatchTable, UiMountedPaintPrimitiveKind, UiMountedPaintProjection,
    UiMountedParticipation, UiMountedParticipationFact, UiMountedParticipationStatus,
    UiMountedPresentationAttemptIdentity, UiMountedPreviewProjection, UiMountedProjectionView,
    UiMountedRealtimeBatchReference, UiMountedRealtimeBatchRow, UiMountedRealtimeBatchTable,
    UiMountedResourceEntry, UiMountedResourceKind, UiMountedResourceReference,
    UiMountedResourceTable, UiMountedSpatialBatchReference, UiMountedSpatialBatchRow,
    UiMountedSpatialBatchTable, UiMountedSurfaceBindingRequirement,
    UiMountedSurfacePresentationCompletion, UiMountedTableProjectionStatus,
    UiMountedTransformProjection, UiPresentationDeadline, UiRequiredLaneContribution,
    UiRequiredLaneContributionStatus, WorthUiHeadlessMountedResourceCache,
    WorthUiMountedResourceCacheDenial,
};
