use super::*;

impl WorthQueryHandleContract {
    pub fn from_public_api_contract(contract: &WorthQueryRuntimePublicApiContract) -> Self {
        let family_status = |family| {
            contract
                .family(family)
                .map(|row| row.status())
                .unwrap_or(WorthQueryRuntimeFamilySupportStatus::Unsupported)
        };
        let rows = vec![
            WorthQueryHandleContractRow::new(
                WorthQueryHandleContractFamily::LiveView,
                [WorthQueryAuthorityLane::AuthoritativeTruth],
                [WorthQueryAuthorityLane::AuthoritativeTruth],
                family_status(WorthQueryRuntimeFacadeFamily::Live),
                [
                    "declaration-identity",
                    "query-result-shape",
                    "authority-lane",
                    "basis-lane",
                    "support-posture",
                    "subscription-lifecycle",
                    "delivery-counters",
                    "inspection-digest",
                ],
                true,
                false,
            ),
            WorthQueryHandleContractRow::new(
                WorthQueryHandleContractFamily::ComputedView,
                [WorthQueryAuthorityLane::DerivedRuntimeState],
                [WorthQueryAuthorityLane::AuthoritativeTruth],
                family_status(WorthQueryRuntimeFacadeFamily::Computed),
                [
                    "declaration-identity",
                    "dependency-aspects",
                    "produced-aspects",
                    "authority-lane",
                    "basis-lane",
                    "support-posture",
                    "materialization",
                    "pending-patches",
                    "inspection-digest",
                ],
                true,
                false,
            ),
            WorthQueryHandleContractRow::new(
                WorthQueryHandleContractFamily::Effect,
                [
                    WorthQueryAuthorityLane::EffectDeliveryState,
                    WorthQueryAuthorityLane::PendingWriteIntent,
                ],
                [WorthQueryAuthorityLane::AuthoritativeTruth],
                family_status(WorthQueryRuntimeFacadeFamily::Effect),
                [
                    "declaration-identity",
                    "trigger-aspects",
                    "condition",
                    "authority-lane",
                    "basis-lane",
                    "support-posture",
                    "delivery-residue",
                    "feedback-phase-graph",
                    "inspection-digest",
                ],
                true,
                false,
            ),
            WorthQueryHandleContractRow::new(
                WorthQueryHandleContractFamily::WriteReceipt,
                [WorthQueryAuthorityLane::AuthoritativeTruth],
                [WorthQueryAuthorityLane::AuthoritativeTruth],
                family_status(WorthQueryRuntimeFacadeFamily::Write),
                [
                    "mutation-family",
                    "declared-target",
                    "commit-identity",
                    "snapshot-token",
                    "authority-lane",
                    "basis-lane",
                    "support-posture",
                    "runtime-evidence",
                    "inspection-digest",
                ],
                true,
                false,
            ),
            WorthQueryHandleContractRow::new(
                WorthQueryHandleContractFamily::BatchWriteReceipt,
                [
                    WorthQueryAuthorityLane::AuthoritativeTruth,
                    WorthQueryAuthorityLane::PreviewTruth,
                ],
                [
                    WorthQueryAuthorityLane::AuthoritativeTruth,
                    WorthQueryAuthorityLane::PreviewTruth,
                ],
                family_status(WorthQueryRuntimeFacadeFamily::Write),
                [
                    "batch-digest",
                    "write-receipt-count",
                    "component-operations",
                    "touched-aspects",
                    "affected-surfaces",
                    "authority-lane",
                    "basis-lane",
                    "support-posture",
                    "inspection-digest",
                ],
                true,
                false,
            ),
            WorthQueryHandleContractRow::new(
                WorthQueryHandleContractFamily::IntentReceipt,
                [WorthQueryAuthorityLane::AuthoritativeTruth],
                [WorthQueryAuthorityLane::AuthoritativeTruth],
                family_status(WorthQueryRuntimeFacadeFamily::Intent),
                [
                    "strategy-identity",
                    "source-target-lanes",
                    "authority-lane",
                    "basis-lane",
                    "support-posture",
                    "outcome",
                    "delivery-counters",
                    "inspection-digest",
                ],
                true,
                false,
            ),
            WorthQueryHandleContractRow::new(
                WorthQueryHandleContractFamily::IntentDenial,
                [WorthQueryAuthorityLane::PendingWriteIntent],
                [WorthQueryAuthorityLane::AuthoritativeTruth],
                family_status(WorthQueryRuntimeFacadeFamily::Intent),
                [
                    "strategy-identity",
                    "source-target-lanes",
                    "authority-lane",
                    "basis-lane",
                    "support-posture",
                    "denial-kind",
                    "returned-strategy",
                    "inspection-digest",
                ],
                true,
                false,
            ),
            WorthQueryHandleContractRow::new(
                WorthQueryHandleContractFamily::EffectIntentReceipt,
                [WorthQueryAuthorityLane::PendingWriteIntent],
                [WorthQueryAuthorityLane::AuthoritativeTruth],
                family_status(WorthQueryRuntimeFacadeFamily::Intent),
                [
                    "effect-source",
                    "authority-lane",
                    "basis-lane",
                    "support-posture",
                    "phase-evidence",
                    "intent-receipt",
                    "feedback-phase-graph",
                    "inspection-digest",
                ],
                true,
                false,
            ),
            WorthQueryHandleContractRow::new(
                WorthQueryHandleContractFamily::PreviewBinding,
                [
                    WorthQueryAuthorityLane::PreviewTruth,
                    WorthQueryAuthorityLane::DerivedRuntimeState,
                    WorthQueryAuthorityLane::EffectDeliveryState,
                ],
                [
                    WorthQueryAuthorityLane::AuthoritativeTruth,
                    WorthQueryAuthorityLane::PreviewTruth,
                ],
                family_status(WorthQueryRuntimeFacadeFamily::BranchPreview),
                [
                    "basis-evidence",
                    "binding-family",
                    "authority-lane",
                    "basis-lane",
                    "support-posture",
                    "effect-policy",
                    "inspection-digest",
                ],
                true,
                false,
            ),
            WorthQueryHandleContractRow::new(
                WorthQueryHandleContractFamily::PreviewOutcome,
                [WorthQueryAuthorityLane::PreviewTruth],
                [
                    WorthQueryAuthorityLane::AuthoritativeTruth,
                    WorthQueryAuthorityLane::PreviewTruth,
                ],
                family_status(WorthQueryRuntimeFacadeFamily::BranchPreview),
                [
                    "basis-evidence",
                    "execution-kind",
                    "authority-lane",
                    "basis-lane",
                    "support-posture",
                    "residue-counters",
                    "closeout-posture",
                    "inspection-digest",
                ],
                true,
                false,
            ),
            WorthQueryHandleContractRow::new(
                WorthQueryHandleContractFamily::PreviewIntentReceipt,
                [WorthQueryAuthorityLane::PreviewTruth],
                [
                    WorthQueryAuthorityLane::AuthoritativeTruth,
                    WorthQueryAuthorityLane::PreviewTruth,
                ],
                family_status(WorthQueryRuntimeFacadeFamily::Intent),
                [
                    "basis-evidence",
                    "source-target-lanes",
                    "authority-lane",
                    "basis-lane",
                    "support-posture",
                    "effect-policy",
                    "pending-intent-residue",
                    "inspection-digest",
                ],
                true,
                false,
            ),
            WorthQueryHandleContractRow::new(
                WorthQueryHandleContractFamily::BranchBinding,
                [
                    WorthQueryAuthorityLane::BranchLocalTruth,
                    WorthQueryAuthorityLane::DerivedRuntimeState,
                    WorthQueryAuthorityLane::EffectDeliveryState,
                ],
                [
                    WorthQueryAuthorityLane::AuthoritativeTruth,
                    WorthQueryAuthorityLane::BranchLocalTruth,
                ],
                WorthQueryRuntimeFamilySupportStatus::Unsupported,
                [
                    "unsupported-branch-handle-reuse",
                    "basis-lane",
                    "authority-lane",
                    "support-posture",
                    "future-inspection-digest",
                    "inspection-digest",
                ],
                false,
                false,
            ),
            WorthQueryHandleContractRow::new(
                WorthQueryHandleContractFamily::BranchIntentReceipt,
                [WorthQueryAuthorityLane::BranchLocalTruth],
                [
                    WorthQueryAuthorityLane::AuthoritativeTruth,
                    WorthQueryAuthorityLane::BranchLocalTruth,
                ],
                family_status(WorthQueryRuntimeFacadeFamily::Intent),
                [
                    "basis-evidence",
                    "source-target-lanes",
                    "authority-lane",
                    "basis-lane",
                    "support-posture",
                    "effect-policy",
                    "branch-local-residue",
                    "inspection-digest",
                ],
                true,
                false,
            ),
            WorthQueryHandleContractRow::new(
                WorthQueryHandleContractFamily::TemporalCapableHandle,
                [WorthQueryAuthorityLane::TemporalExecutionState],
                [
                    WorthQueryAuthorityLane::AuthoritativeTruth,
                    WorthQueryAuthorityLane::TemporalExecutionState,
                ],
                family_status(WorthQueryRuntimeFacadeFamily::Temporal),
                [
                    "support-posture",
                    "state-kind",
                    "basis-identity",
                    "temporal-readiness-neighbor",
                    "authority-lane",
                    "basis-lane",
                    "future-inspection-digest",
                    "inspection-digest",
                ],
                false,
                true,
            ),
            WorthQueryHandleContractRow::new(
                WorthQueryHandleContractFamily::AsyncResourceCapableHandle,
                [WorthQueryAuthorityLane::AsyncResourceState],
                [
                    WorthQueryAuthorityLane::AuthoritativeTruth,
                    WorthQueryAuthorityLane::AsyncResourceState,
                ],
                family_status(WorthQueryRuntimeFacadeFamily::AsyncResource),
                [
                    "support-posture",
                    "state-kind",
                    "basis-identity",
                    "async-request-identity",
                    "authority-lane",
                    "basis-lane",
                    "future-inspection-digest",
                    "inspection-digest",
                ],
                false,
                true,
            ),
            WorthQueryHandleContractRow::new(
                WorthQueryHandleContractFamily::MixedCauseDeliveryCapableHandle,
                [WorthQueryAuthorityLane::BridgeExternalState],
                [
                    WorthQueryAuthorityLane::AuthoritativeTruth,
                    WorthQueryAuthorityLane::TemporalExecutionState,
                    WorthQueryAuthorityLane::AsyncResourceState,
                    WorthQueryAuthorityLane::BridgeExternalState,
                ],
                family_status(WorthQueryRuntimeFacadeFamily::MixedCauseDelivery),
                [
                    "support-posture",
                    "state-kind",
                    "basis-identity",
                    "mixed-cause-ordering-neighbor",
                    "authority-lane",
                    "basis-lane",
                    "future-inspection-digest",
                    "inspection-digest",
                ],
                false,
                true,
            ),
        ];
        let inspectable_family_count = rows.len();
        let retained_artifact_family_count = rows
            .iter()
            .filter(|row| row.retained_artifact_required())
            .count();
        let deferred_future_family_count = rows
            .iter()
            .filter(|row| row.deferred_future_posture())
            .count();
        let support_contract_digest = contract.contract_digest().to_string();
        let mut parts = vec![
            "worth_query_handle_contract_v1".to_string(),
            format!("support:{support_contract_digest}"),
            format!("inspectable:{inspectable_family_count}"),
            format!("retained:{retained_artifact_family_count}"),
            format!("deferred:{deferred_future_family_count}"),
        ];
        parts.extend(rows.iter().map(|row| row.contract_digest().to_string()));
        let contract_digest = hash_parts(&parts);
        Self {
            rows,
            support_contract_digest,
            inspectable_family_count,
            retained_artifact_family_count,
            deferred_future_family_count,
            contract_digest,
        }
    }
}
