#[path = "support/trybuild_helpers.rs"]
mod trybuild_helpers;

const RUNTIME_AUTHORITY_PASS_CASES: &[&str] =
    &["tests/ui/runtime_authority/pass/runtime_facade_types.rs"];

const RUNTIME_AUTHORITY_FAIL_CASES: &[&str] = &[
    "tests/ui/runtime_authority/fail/runtime_internal_module_is_not_public.rs",
    "tests/ui/runtime_authority/fail/runtime_launch_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/runtime_fact_id_raw_constructor_not_public.rs",
    "tests/ui/runtime_authority/fail/runtime_host_authority_not_cloneable.rs",
    "tests/ui/runtime_authority/fail/replacement_candidate_bundle_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/unadmitted_candidate_cannot_enter_admitted_boundary.rs",
    "tests/ui/runtime_authority/fail/active_runtime_state_not_constructible_from_app_local_parts.rs",
    "tests/ui/runtime_authority/fail/forged_last_valid_receipt_not_installable.rs",
    "tests/ui/runtime_authority/fail/pending_execution_plan_lowering_input_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/raw_source_cannot_enter_plan_lowering.rs",
    "tests/ui/runtime_authority/fail/execution_plan_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/plan_lookup_index_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/frame_path_cannot_scan_artifact_tree_from_execution_plan.rs",
    "tests/ui/runtime_authority/fail/pointer_identity_cannot_replace_plan_equivalence.rs",
    "tests/ui/runtime_authority/fail/node_replacement_plan_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/runtime_handle_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/stale_runtime_handle_cannot_replace_fresh_plan_receipt.rs",
    "tests/ui/runtime_authority/fail/frame_boundary_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/execution_plan_inspection_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/extension_hook_cannot_override_active_plan_truth.rs",
    "tests/ui/runtime_authority/fail/component_interaction_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/interaction_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/mounted_interaction_eligible_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/denied_mounted_interaction_cannot_submit.rs",
    "tests/ui/runtime_authority/fail/interaction_payload_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/interaction_field_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/primitive_proof_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/primitive_construction_graph_proof_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/primitive_construction_plan_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/graph_invalidation_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/appearance_enabled_posture_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/primitive_observed_posture_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/raw_host_observation_cannot_satisfy_paint_plan.rs",
    "tests/ui/runtime_authority/fail/primitive_nested_authority_types_not_mintable.rs",
    "tests/ui/runtime_authority/fail/raw_surface_cannot_resolve_primitive_proof.rs",
    "tests/ui/runtime_authority/fail/raw_surface_cannot_resolve_primitive_projection.rs",
    "tests/ui/runtime_authority/fail/raw_surface_cannot_resolve_mounted_interaction_plan.rs",
    "tests/ui/runtime_authority/fail/primitive_target_cannot_authorize_mounted_interaction.rs",
    "tests/ui/runtime_authority/fail/raw_event_point_cannot_dispatch_or_cursor.rs",
    "tests/ui/runtime_authority/fail/event_region_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/event_dispatch_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/pointer_frame_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/query_graph_execution_receipt_constructor_not_public.rs",
    "tests/ui/runtime_authority/fail/live_view_declaration_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/live_view_declaration_rebind_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/live_view_state_edit_intent_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/live_view_control_projection_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/live_view_control_host_frame_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/live_view_composition_child_binding_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/live_view_composition_subject_reconciliation_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/mounted_control_node_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/live_view_conditional_projection_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/live_view_expression_projection_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/live_view_participation_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/live_view_projection_admission_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/raw_live_view_projection_cannot_mount_product_view.rs",
    "tests/ui/runtime_authority/fail/graph_backed_live_view_projection_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/composition_source_report_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/composition_source_denial_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/live_view_projection_rebind_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/live_view_projection_render_plan_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/mounted_product_view_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/mounted_content_node_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/host_observation_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/measured_product_view_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/layout_allocation_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/viewport_boundary_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/effective_viewport_participation_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/composition_participation_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/composition_participation_relationship_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/composition_focus_scope_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/composition_participation_traversal_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/composition_participation_denial_report_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/accessibility_host_inspection_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/mounted_composition_tree_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/mounted_composition_child_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/live_view_readiness_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/live_view_payload_projection_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/live_view_interaction_intent_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/live_view_activation_eligible_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/live_view_submission_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/live_view_raw_interaction_cannot_submit.rs",
    "tests/ui/runtime_authority/fail/composition_graph_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/composition_graph_access_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/composition_graph_access_plan_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/composition_node_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/composition_edge_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/composition_policy_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/composition_root_mount_receipt_fields_not_public.rs",
    "tests/ui/runtime_authority/fail/composition_root_authority/composition_root_authority_receipts_not_mintable.rs",
];

#[test]
fn runtime_authority_public_types_compile() {
    trybuild_helpers::run_pass_cases(RUNTIME_AUTHORITY_PASS_CASES);
}

#[test]
fn runtime_authority_boundaries_stay_sealed() {
    trybuild_helpers::run_compile_fail_cases(RUNTIME_AUTHORITY_FAIL_CASES);
}
