from __future__ import annotations

from runner.graph_runtime.state.runtime_state import (
    CURRENT_TURN_AUTHORITY_KEY,
    LOWERED_PHASE_PROGRAM_KEY,
    PROMPT_TURN_KEY,
    ROLE_SESSION_KEY,
    RUN_AUTHORITY_KEY,
    RUN_CONTEXT_KEY,
    TURN_CONTINUATION_KEY,
    TURN_EXECUTION_KEY,
    TURN_OUTCOME_KEY,
    TURN_TRANSITION_KEY,
)

GRAPH_STATE_KEYS = (
    RUN_CONTEXT_KEY,
    RUN_AUTHORITY_KEY,
    CURRENT_TURN_AUTHORITY_KEY,
    LOWERED_PHASE_PROGRAM_KEY,
    ROLE_SESSION_KEY,
    TURN_CONTINUATION_KEY,
    PROMPT_TURN_KEY,
    TURN_EXECUTION_KEY,
    TURN_OUTCOME_KEY,
    TURN_TRANSITION_KEY,
)
