#[derive(Debug, Clone, PartialEq, Eq)]
pub enum BaselineLsmExecutionAdmissionDenial {
    StrategyInvariant(crate::strategy::StrategyDenial),
    CanonicalKeyRequired,
    MemtableDoesNotFollowSortedRuns,
    SortedRunsNotCanonical,
    ReplayTailNotCanonical,
    ReplayBindingMismatch,
    TombstoneRecordRequired,
    ValueRecordRequired,
    OutputGenerationOverflow,
    OutputPublicationMismatch,
    ManifestPublicationRequired,
    ManifestDoesNotCoverCompaction,
    ManifestMembershipMismatch,
    PersistedMembershipAmbiguous,
    PersistedMembershipIncomplete,
    PersistedMembershipStale,
    PersistedIndexIo,
    PhysicalTargetEpochRequired,
    DurableRecordBindingMismatch,
    RecordKeyScopeMismatch,
    PhysicalPublicationBindingMismatch,
    SelectedOperationKeyMismatch,
}
