mod coplanar_overlap;
mod local_frame_certificate;
mod plane_projection;
mod polygon_winding;
mod precision_certification;
mod predicate_authority;
mod predicate_consumption;
mod segment_contact_classification;
mod signed_area_degeneracy;
