[package]
name = "forge-ui-theme"
edition.workspace = true
version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
forge-ui-types = { workspace = true }
egui      = { workspace = true }
egui-wgpu = { workspace = true }
wgpu      = { workspace = true }
bytemuck  = { version = "1", features = ["derive"] }
