pub(super) const GRAPH_READ_ACCESS_PLAN_ADOPTION_FIXTURES: &[(&str, &str)] = &[
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_one_boundary/rejects_raw_closeout_digest.rs",
        "WorthGraphReadAccessDeclarationMilestoneEightSeed",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_one_boundary/rejects_raw_read_family_digest.rs",
        "WorthGraphReadAccessDeclarationMilestoneEightSeed",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_one_boundary/rejects_raw_requirement_row_digest.rs",
        "WorthGraphReadAccessDeclarationMilestoneEightSeed",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_one_boundary/rejects_raw_query_read_receipt.rs",
        "WorthGraphReadAccessDeclarationMilestoneEightSeed",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_one_boundary/rejects_raw_plan_consumption.rs",
        "WorthGraphReadAccessDeclarationMilestoneEightSeed",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_one_boundary/rejects_pre_closeout_product.rs",
        "WorthGraphReadAccessDeclarationMilestoneEightSeed",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_one_boundary/closeout_struct_literal.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_one_boundary/inventory_row_struct_literal.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_one_boundary/inventory_struct_literal.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_two_boundary/closeout_struct_literal.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_two_boundary/adoption_attempt_struct_literal.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_two_boundary/posture_report_struct_literal.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_two_boundary/posture_row_struct_literal.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_two_boundary/rejects_raw_query_admission_as_seed.rs",
        "WorthGraphReadAccessPlanAdoptionPhaseOneCloseout",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_two_boundary/rejects_raw_query_receipt_as_seed.rs",
        "WorthGraphReadAccessPlanAdoptionPhaseOneCloseout",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_three_boundary/struct_literals/closeout_struct_literal.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_three_boundary/struct_literals/resolved_posture_struct_literal.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_three_boundary/struct_literals/cap_ledger_row_struct_literal.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_three_boundary/struct_literals/cap_report_struct_literal.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_three_boundary/struct_literals/family_count_struct_literal.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_three_boundary/struct_literals/phase_four_seed_struct_literal.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_three_boundary/closeout_input/rejects_raw_query_posture_as_closeout_input.rs",
        "WorthGraphReadAccessPlanAdoptionPhaseTwoCloseout",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_three_boundary/closeout_input/rejects_raw_query_denial_as_closeout_input.rs",
        "WorthGraphReadAccessPlanAdoptionPhaseTwoCloseout",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_three_boundary/closeout_input/rejects_raw_digest_as_closeout_input.rs",
        "WorthGraphReadAccessPlanAdoptionPhaseTwoCloseout",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_three_boundary/closeout_input/raw_resolved_posture_vec.rs",
        "WorthGraphReadAccessPlanAdoptionPhaseTwoCloseout",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_four_boundary/closeout_input/raw_phase_three_digest.rs",
        "WorthGraphReadAccessPhaseFourSeed",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_four_boundary/closeout_input/raw_resolved_posture.rs",
        "WorthGraphReadAccessPhaseFourSeed",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_four_boundary/closeout_input/raw_query_plan.rs",
        "WorthGraphReadAccessPhaseFourSeed",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_four_boundary/struct_literals/closeout_struct_literal.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_four_boundary/struct_literals/selected_slice_struct_literal.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_four_boundary/struct_literals/plan_projection_struct_literal.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_four_boundary/struct_literals/receipt_projection_struct_literal.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_four_boundary/struct_literals/phase_five_seed_struct_literal.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_five_boundary/closeout_input/raw_query_receipt_as_seed.rs",
        "WorthGraphReadAccessFirstVerticalSliceSeed",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_five_boundary/struct_literals/closeout_struct_literal.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_five_boundary/struct_literals/posture_projection_struct_literal.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_five_boundary/struct_literals/phase_six_seed_struct_literal.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_seven_boundary/closeout_input/raw_query_receipt_as_seed.rs",
        "WorthGraphReadAccessExecutionReceiptAccountingPhaseSevenSeed",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_seven_boundary/struct_literals/closeout_struct_literal.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_seven_boundary/struct_literals/deletion_proof_row_struct_literal.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_seven_boundary/struct_literals/capped_residue_row_struct_literal.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_seven_boundary/struct_literals/source_firewall_report_struct_literal.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_seven_boundary/struct_literals/source_firewall_region_row_struct_literal.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_seven_boundary/struct_literals/source_firewall_violation_struct_literal.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_seven_boundary/struct_literals/phase_eight_seed_struct_literal.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_eight_boundary/closeout_input/raw_query_receipt_as_seed.rs",
        "WorthGraphReadAccessHardDeletionPhaseEightSeed",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_eight_boundary/closeout_input/raw_query_admitted_plan_as_seed.rs",
        "WorthGraphReadAccessHardDeletionPhaseEightSeed",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_eight_boundary/closeout_input/raw_query_plan_consumption_as_seed.rs",
        "WorthGraphReadAccessHardDeletionPhaseEightSeed",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_eight_boundary/closeout_input/local_summary_as_seed.rs",
        "WorthGraphReadAccessHardDeletionPhaseEightSeed",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_eight_boundary/closeout_input/raw_closeout_digest_as_seed.rs",
        "WorthGraphReadAccessHardDeletionPhaseEightSeed",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_eight_boundary/struct_literals/closeout_struct_literal.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_eight_boundary/struct_literals/milestone_nine_seed_struct_literal.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_eight_boundary/struct_literals/receipt_export_struct_literal.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_eight_boundary/struct_literals/posture_export_struct_literal.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_eight_boundary/struct_literals/closeout_counters_struct_literal.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_eight_boundary/struct_literals/deletion_export_struct_literal.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_eight_boundary/struct_literals/residue_export_struct_literal.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_plan_adoption/phase_eight_boundary/struct_literals/source_firewall_export_struct_literal.rs",
        "private",
    ),
];
