pub(super) const GRAPH_READ_ACCESS_DECLARATION_FIXTURES: &[(&str, &str)] = &[
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_declarations/phase_one_boundary/rejects_raw_milestone_seven_seed.rs",
        "WorthGraphReadAccessMilestoneSixCloseout",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_declarations/phase_one_boundary/rejects_raw_declaration_candidates.rs",
        "WorthGraphReadAccessMilestoneSixCloseout",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_declarations/phase_one_boundary/rejects_raw_capability_gaps.rs",
        "WorthGraphReadAccessMilestoneSixCloseout",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_declarations/phase_one_boundary/rejects_raw_deletion_rows.rs",
        "WorthGraphReadAccessMilestoneSixCloseout",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_declarations/phase_one_boundary/rejects_raw_phase_one_counters.rs",
        "WorthGraphReadAccessMilestoneSixCloseout",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_declarations/phase_two_boundary/rejects_raw_declaration_candidates.rs",
        "WorthGraphReadAccessDeclarationPhaseOneCloseout",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_declarations/phase_two_boundary/rejects_catalog_direct_construction.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_declarations/phase_two_boundary/rejects_catalog_key_construction.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_declarations/phase_two_boundary/rejects_catalog_record_construction.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_declarations/phase_two_boundary/rejects_phase_three_seed_construction.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_declarations/phase_three_boundary/rejects_raw_topology_label_authority.rs",
        "From<&str>",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_declarations/phase_three_boundary/rejects_raw_spatial_label_authority.rs",
        "From<&str>",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_declarations/phase_three_boundary/rejects_copied_digest_authority.rs",
        "From<String>",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_declarations/phase_three_boundary/rejects_lowered_authority_struct_literal.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_declarations/phase_three_boundary/rejects_lowered_record_struct_literal.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_declarations/phase_four_boundary/rejects_raw_catalog_records.rs",
        "WorthGraphReadAccessDeclarationPhaseTwoCloseout",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_declarations/phase_four_boundary/rejects_local_requirement_rows.rs",
        "From<Vec",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_declarations/phase_four_boundary/rejects_requirement_set_struct_literal.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_declarations/phase_four_boundary/rejects_receipt_summary_as_requirement_evidence.rs",
        "From<ForgeQueryGraphReadAccessReceiptSummary>",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_declarations/phase_six_boundary/rejects_raw_deletion_rows.rs",
        "WorthGraphReadAccessDeclarationPhaseSixSeed",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_declarations/phase_six_boundary/rejects_residue_struct_literals.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_declarations/phase_six_boundary/rejects_deletion_ledger_report_struct_literal.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_declarations/phase_six_boundary/rejects_source_firewall_report_struct_literal.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_declarations/phase_six_boundary/rejects_phase_seven_seed_constructor.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_declarations/phase_six_boundary/rejects_local_declaration_authority.rs",
        "From<Vec",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_declarations/phase_six_boundary/rejects_local_requirement_rows.rs",
        "From<Vec",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_declarations/phase_seven_boundary/rejects_closeout_literal.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_declarations/phase_seven_boundary/rejects_milestone_eight_seed_literal.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_declarations/phase_seven_boundary/rejects_read_family_identity_literal.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_declarations/phase_seven_boundary/rejects_requirement_row_literal.rs",
        "private",
    ),
    (
        "src/certification/public_facade_contracts/compile_fail/graph_read_access_declarations/phase_seven_boundary/rejects_raw_receipt_closeout.rs",
        "WorthGraphReadAccessDeclarationPhaseSevenSeed",
    ),
];
