use super::{WorthQueryLowerRuntimePublicSurfaceKind, WorthQueryLowerRuntimePublicSurfaceRow};
use crate::lower_runtime_routing::WorthQueryLowerRuntimeSeamKey;

pub(super) const PUBLIC_SURFACE_ROWS: &[WorthQueryLowerRuntimePublicSurfaceRow] = &[
    WorthQueryLowerRuntimePublicSurfaceRow::new(
        WorthQueryLowerRuntimeSeamKey::RuntimeBackendBoundaryModules,
        "WorthQueryRuntime backend boundary modules",
        "crates/worth-query/src/runtime/backend/*",
        WorthQueryLowerRuntimePublicSurfaceKind::RuntimeBackendBoundary,
        "canonical backend boundary hub for live declaration, source, preview, write, signal, activation, and intent adapter contracts",
    ),
    WorthQueryLowerRuntimePublicSurfaceRow::new(
        WorthQueryLowerRuntimeSeamKey::ComposeRead,
        "WorthQueryWorkspace::compose_read(...)",
        "crates/worth-query/src/runtime/workspace_queries.rs",
        WorthQueryLowerRuntimePublicSurfaceKind::PublicFacade,
        "read-family intent execution",
    ),
    WorthQueryLowerRuntimePublicSurfaceRow::new(
        WorthQueryLowerRuntimeSeamKey::ComposeReadWithInvariantPack,
        "WorthQueryWorkspace::compose_read_with_invariant_pack(...)",
        "crates/worth-query/src/runtime/workspace_queries.rs",
        WorthQueryLowerRuntimePublicSurfaceKind::PublicFacade,
        "read-family intent execution after invariant admission",
    ),
    WorthQueryLowerRuntimePublicSurfaceRow::new(
        WorthQueryLowerRuntimeSeamKey::ExecuteReadFamily,
        "WorthQueryWorkspace::execute_read_family(...)",
        "crates/worth-query/src/runtime/workspace_queries.rs",
        WorthQueryLowerRuntimePublicSurfaceKind::PublicFacade,
        "read-family intent execution",
    ),
    WorthQueryLowerRuntimePublicSurfaceRow::new(
        WorthQueryLowerRuntimeSeamKey::ExecuteReadFamilyInBasisContext,
        "WorthQueryWorkspace::execute_read_family_in_basis_context(...)",
        "crates/worth-query/src/runtime/workspace_queries.rs",
        WorthQueryLowerRuntimePublicSurfaceKind::PublicFacade,
        "basis-context read-family intent execution",
    ),
    WorthQueryLowerRuntimePublicSurfaceRow::new(
        WorthQueryLowerRuntimeSeamKey::ExecuteRuntimeCurrentReadGraph,
        "execute_runtime_current_read_graph(...)",
        "crates/worth-query/src/runtime/read_composition_runtime.rs",
        WorthQueryLowerRuntimePublicSurfaceKind::InternalRouteComposer,
        "current read-family route execution",
    ),
    WorthQueryLowerRuntimePublicSurfaceRow::new(
        WorthQueryLowerRuntimeSeamKey::ExecuteRuntimeBasisContextReadGraph,
        "execute_runtime_basis_context_read_graph(...)",
        "crates/worth-query/src/runtime/read_composition_runtime.rs",
        WorthQueryLowerRuntimePublicSurfaceKind::InternalRouteComposer,
        "basis-context read-family route execution",
    ),
    WorthQueryLowerRuntimePublicSurfaceRow::new(
        WorthQueryLowerRuntimeSeamKey::PublicLiveViewDeclaration,
        "WorthQueryWorkspace::live_view(...)",
        "crates/worth-query/src/runtime/workspace.rs",
        WorthQueryLowerRuntimePublicSurfaceKind::PublicFacade,
        "workspace live declaration routed through runtime declaration and installation",
    ),
    WorthQueryLowerRuntimePublicSurfaceRow::new(
        WorthQueryLowerRuntimeSeamKey::PublicLiveViewDeclaration,
        "WorthQueryWorkspace::live_view_request(...)",
        "crates/worth-query/src/runtime/workspace.rs",
        WorthQueryLowerRuntimePublicSurfaceKind::PublicFacade,
        "workspace live declaration routed through runtime declaration and installation",
    ),
    WorthQueryLowerRuntimePublicSurfaceRow::new(
        WorthQueryLowerRuntimeSeamKey::PublicLiveViewDeclaration,
        "WorthQueryRuntime::declare_live_view(...)",
        "crates/worth-query/src/runtime/runtime_declarations.rs",
        WorthQueryLowerRuntimePublicSurfaceKind::PublicFacade,
        "live declaration receipt plus installation route",
    ),
    WorthQueryLowerRuntimePublicSurfaceRow::new(
        WorthQueryLowerRuntimeSeamKey::WriteAuthorityBackendExecution,
        "WorthQueryWorkspace::write(...)",
        "crates/worth-query/src/runtime/workspace.rs",
        WorthQueryLowerRuntimePublicSurfaceKind::PublicFacade,
        "authoritative mutation intent execution through write-authority routing",
    ),
    WorthQueryLowerRuntimePublicSurfaceRow::new(
        WorthQueryLowerRuntimeSeamKey::WriteAuthorityBackendExecution,
        "WorthQueryWorkspace::insert(...)",
        "crates/worth-query/src/runtime/workspace.rs",
        WorthQueryLowerRuntimePublicSurfaceKind::PublicFacade,
        "authoritative mutation intent execution through write-authority routing",
    ),
    WorthQueryLowerRuntimePublicSurfaceRow::new(
        WorthQueryLowerRuntimeSeamKey::WriteAuthorityBackendExecution,
        "WorthQueryWorkspace::update(...)",
        "crates/worth-query/src/runtime/workspace.rs",
        WorthQueryLowerRuntimePublicSurfaceKind::PublicFacade,
        "authoritative mutation intent execution through write-authority routing",
    ),
    WorthQueryLowerRuntimePublicSurfaceRow::new(
        WorthQueryLowerRuntimeSeamKey::WriteAuthorityBackendExecution,
        "WorthQueryWorkspace::update_existing(...)",
        "crates/worth-query/src/runtime/workspace.rs",
        WorthQueryLowerRuntimePublicSurfaceKind::PublicFacade,
        "authoritative mutation intent execution after existing-truth binding admission",
    ),
    WorthQueryLowerRuntimePublicSurfaceRow::new(
        WorthQueryLowerRuntimeSeamKey::WriteAuthorityBackendExecution,
        "WorthQueryWorkspace::assert_existing(...)",
        "crates/worth-query/src/runtime/workspace.rs",
        WorthQueryLowerRuntimePublicSurfaceKind::PublicFacade,
        "authoritative mutation intent execution after existing-truth binding admission",
    ),
    WorthQueryLowerRuntimePublicSurfaceRow::new(
        WorthQueryLowerRuntimeSeamKey::WriteAuthorityBackendExecution,
        "WorthQueryWorkspace::verify_existing(...)",
        "crates/worth-query/src/runtime/workspace.rs",
        WorthQueryLowerRuntimePublicSurfaceKind::PublicFacade,
        "authoritative mutation intent execution after existing-truth binding admission",
    ),
    WorthQueryLowerRuntimePublicSurfaceRow::new(
        WorthQueryLowerRuntimeSeamKey::WriteAuthorityBackendExecution,
        "WorthQueryWorkspace::update_existing_verified(...)",
        "crates/worth-query/src/runtime/workspace.rs",
        WorthQueryLowerRuntimePublicSurfaceKind::PublicFacade,
        "authoritative mutation intent execution after backend-verified existing-truth admission",
    ),
    WorthQueryLowerRuntimePublicSurfaceRow::new(
        WorthQueryLowerRuntimeSeamKey::WriteAuthorityBackendExecution,
        "WorthQueryWorkspace::delete(...)",
        "crates/worth-query/src/runtime/workspace.rs",
        WorthQueryLowerRuntimePublicSurfaceKind::PublicFacade,
        "authoritative mutation intent execution through write-authority routing",
    ),
    WorthQueryLowerRuntimePublicSurfaceRow::new(
        WorthQueryLowerRuntimeSeamKey::WriteAuthorityBackendExecution,
        "WorthQueryWorkspace::delete_with(...)",
        "crates/worth-query/src/runtime/workspace.rs",
        WorthQueryLowerRuntimePublicSurfaceKind::PublicFacade,
        "authoritative mutation intent execution through write-authority routing",
    ),
    WorthQueryLowerRuntimePublicSurfaceRow::new(
        WorthQueryLowerRuntimeSeamKey::WriteAuthorityBackendExecution,
        "WorthQueryWorkspace::delete_existing(...)",
        "crates/worth-query/src/runtime/workspace.rs",
        WorthQueryLowerRuntimePublicSurfaceKind::PublicFacade,
        "authoritative mutation intent execution after existing-truth binding admission",
    ),
    WorthQueryLowerRuntimePublicSurfaceRow::new(
        WorthQueryLowerRuntimeSeamKey::WriteAuthorityBackendExecution,
        "WorthQueryWorkspace::delete_existing_with(...)",
        "crates/worth-query/src/runtime/workspace.rs",
        WorthQueryLowerRuntimePublicSurfaceKind::PublicFacade,
        "authoritative mutation intent execution after existing-truth binding admission",
    ),
    WorthQueryLowerRuntimePublicSurfaceRow::new(
        WorthQueryLowerRuntimeSeamKey::WriteAuthorityBackendExecution,
        "WorthQueryWorkspace::delete_existing_verified(...)",
        "crates/worth-query/src/runtime/workspace.rs",
        WorthQueryLowerRuntimePublicSurfaceKind::PublicFacade,
        "authoritative mutation intent execution after backend-verified existing-truth admission",
    ),
    WorthQueryLowerRuntimePublicSurfaceRow::new(
        WorthQueryLowerRuntimeSeamKey::WriteAuthorityBackendExecution,
        "WorthQueryRuntime::write(...)",
        "crates/worth-query/src/runtime/runtime_writes.rs",
        WorthQueryLowerRuntimePublicSurfaceKind::PublicFacade,
        "authoritative mutation intent execution through write-authority routing",
    ),
    WorthQueryLowerRuntimePublicSurfaceRow::new(
        WorthQueryLowerRuntimeSeamKey::WriteAuthorityBackendExecution,
        "WorthQueryRuntime::write_batch(...)",
        "crates/worth-query/src/runtime/runtime_batch_write_entrypoints.rs",
        WorthQueryLowerRuntimePublicSurfaceKind::PublicFacade,
        "authoritative batch mutation intent execution through write-authority routing",
    ),
    WorthQueryLowerRuntimePublicSurfaceRow::new(
        WorthQueryLowerRuntimeSeamKey::WriteAuthorityBackendExecution,
        "WorthQueryWorkspace::batch(...)",
        "crates/worth-query/src/runtime/workspace.rs",
        WorthQueryLowerRuntimePublicSurfaceKind::PublicFacade,
        "authoritative batch mutation intent execution through write-authority routing",
    ),
    WorthQueryLowerRuntimePublicSurfaceRow::new(
        WorthQueryLowerRuntimeSeamKey::SignalInvalidationRouting,
        "WorthQueryRuntime::execute_authoritative_write_command_direct(...)",
        "crates/worth-query/src/runtime/runtime_writes.rs",
        WorthQueryLowerRuntimePublicSurfaceKind::InternalRouteComposer,
        "mutation receipt routing through signal invalidation boundary receipts",
    ),
    WorthQueryLowerRuntimePublicSurfaceRow::new(
        WorthQueryLowerRuntimeSeamKey::SignalInvalidationRouting,
        "WorthQueryRuntime::execute_authoritative_write_batch_direct(...)",
        "crates/worth-query/src/runtime/runtime_batch_writes.rs",
        WorthQueryLowerRuntimePublicSurfaceKind::InternalRouteComposer,
        "batch mutation receipt routing through signal invalidation boundary receipts",
    ),
    WorthQueryLowerRuntimePublicSurfaceRow::new(
        WorthQueryLowerRuntimeSeamKey::RuntimeLiveInstallationOrchestration,
        "WorthQueryRuntime::install_live_subscription_for_request(...)",
        "crates/worth-query/src/runtime/runtime_sessions.rs",
        WorthQueryLowerRuntimePublicSurfaceKind::InternalRouteComposer,
        "subscription declaration, lowering, admission, and activation route",
    ),
    WorthQueryLowerRuntimePublicSurfaceRow::new(
        WorthQueryLowerRuntimeSeamKey::SubscriptionContinuity,
        "basis-lifecycle bridge continuity readmission",
        "crates/worth-query/src/basis_lifecycle/lower_runtime/mod.rs",
        WorthQueryLowerRuntimePublicSurfaceKind::InternalRouteComposer,
        "continuity evidence is readmitted through lower-runtime basis binding instead of a side-door runtime lane",
    ),
    WorthQueryLowerRuntimePublicSurfaceRow::new(
        WorthQueryLowerRuntimeSeamKey::BasisReadmissionFromTruthViewEvidence,
        "basis readmission from truth-view evidence",
        "crates/worth-query/src/basis_lifecycle/lower_runtime/mod.rs",
        WorthQueryLowerRuntimePublicSurfaceKind::InternalRouteComposer,
        "truth-view evidence is readmitted through lower-runtime basis binding",
    ),
    WorthQueryLowerRuntimePublicSurfaceRow::new(
        WorthQueryLowerRuntimeSeamKey::BasisReadmissionFromSubscriptionEvidence,
        "basis readmission from subscription evidence",
        "crates/worth-query/src/basis_lifecycle/lower_runtime/mod.rs",
        WorthQueryLowerRuntimePublicSurfaceKind::InternalRouteComposer,
        "subscription evidence is readmitted through lower-runtime basis binding",
    ),
    WorthQueryLowerRuntimePublicSurfaceRow::new(
        WorthQueryLowerRuntimeSeamKey::HistoricalBridgeLowering,
        "historical bridge policy lowering adapter",
        "crates/worth-query/src/historical/bridge_lowering.rs",
        WorthQueryLowerRuntimePublicSurfaceKind::AllowedBoundaryAdapter,
        "historical lowering remains a declared runtime-bridge adapter rather than an untracked direct import site",
    ),
    WorthQueryLowerRuntimePublicSurfaceRow::new(
        WorthQueryLowerRuntimeSeamKey::EffectBackedRelationalMutation,
        "effect-backed relational mutation execution",
        "crates/worth-query/src/effect_lifecycle/execution.rs",
        WorthQueryLowerRuntimePublicSurfaceKind::AllowedBoundaryAdapter,
        "effect execution stays routed through the admitted relational execution lane",
    ),
    WorthQueryLowerRuntimePublicSurfaceRow::new(
        WorthQueryLowerRuntimeSeamKey::EffectBackedRelationalMerge,
        "effect-backed relational merge execution",
        "crates/worth-query/src/effect_lifecycle/execution.rs",
        WorthQueryLowerRuntimePublicSurfaceKind::AllowedBoundaryAdapter,
        "effect merge execution stays routed through the admitted relational execution lane",
    ),
    WorthQueryLowerRuntimePublicSurfaceRow::new(
        WorthQueryLowerRuntimeSeamKey::EffectBackedBridgeWriteback,
        "effect-backed bridge writeback adapter",
        "crates/worth-query/src/effect_lifecycle/execution_bridge.rs",
        WorthQueryLowerRuntimePublicSurfaceKind::AllowedBoundaryAdapter,
        "bridge writeback remains a declared bridge adapter over the admitted writeback contract",
    ),
    WorthQueryLowerRuntimePublicSurfaceRow::new(
        WorthQueryLowerRuntimeSeamKey::RuntimeIntentAuthorityAdapter,
        "runtime intent authority adapter",
        "crates/worth-query/src/runtime/backend/intent_authority.rs",
        WorthQueryLowerRuntimePublicSurfaceKind::AllowedBoundaryAdapter,
        "intent authority adapter remains confined to the backend boundary over admitted runtime bridge and relational authority",
    ),
    WorthQueryLowerRuntimePublicSurfaceRow::new(
        WorthQueryLowerRuntimeSeamKey::IntentRuntimeExecution,
        "installed intent authority backend execution",
        "crates/worth-query/src/runtime/backend/intent_authority.rs",
        WorthQueryLowerRuntimePublicSurfaceKind::AllowedBoundaryAdapter,
        "intent execution remains confined to the backend authority seam",
    ),
    WorthQueryLowerRuntimePublicSurfaceRow::new(
        WorthQueryLowerRuntimeSeamKey::ProjectionSourceIntakeFromQueryReceipts,
        "projection source intake from Query receipts",
        "crates/worth-query/src/projection_consumption/source/mod.rs",
        WorthQueryLowerRuntimePublicSurfaceKind::AllowedBoundaryAdapter,
        "projection source intake remains a declared Query boundary adapter over Query-owned authoritative receipts",
    ),
    WorthQueryLowerRuntimePublicSurfaceRow::new(
        WorthQueryLowerRuntimeSeamKey::ProjectionSourceIntakeFromRelationalArtifacts,
        "projection source intake from relational artifacts",
        "crates/worth-query/src/projection_consumption/source/mod.rs",
        WorthQueryLowerRuntimePublicSurfaceKind::AllowedBoundaryAdapter,
        "projection source intake remains a declared Query boundary adapter over relational authoritative artifacts",
    ),
    WorthQueryLowerRuntimePublicSurfaceRow::new(
        WorthQueryLowerRuntimeSeamKey::ProjectionSourceIntakeFromBridgeArtifacts,
        "projection source intake from bridge artifacts",
        "crates/worth-query/src/projection_consumption/source/mod.rs",
        WorthQueryLowerRuntimePublicSurfaceKind::AllowedBoundaryAdapter,
        "projection source intake remains a declared Query boundary adapter over bridge authoritative artifacts",
    ),
    WorthQueryLowerRuntimePublicSurfaceRow::new(
        WorthQueryLowerRuntimeSeamKey::CausalBridgeMaterialization,
        "causal bridge materialization adapter",
        "crates/worth-query/src/runtime/inspection/causal/builder_bridge.rs",
        WorthQueryLowerRuntimePublicSurfaceKind::AllowedBoundaryAdapter,
        "causal inspection bridge materialization remains a declared Query boundary adapter",
    ),
    WorthQueryLowerRuntimePublicSurfaceRow::new(
        WorthQueryLowerRuntimeSeamKey::FrontierEvidenceIntake,
        "frontier signal evidence adapter",
        "crates/worth-query/src/frontier_signal_adapter.rs",
        WorthQueryLowerRuntimePublicSurfaceKind::AllowedBoundaryAdapter,
        "frontier evidence intake remains a declared Query boundary adapter over signal facade receipts",
    ),
];
