use crate::harness::live_certification::LiveCertificationRow;

pub(super) fn assert_canonical_locality_expectation(row: &LiveCertificationRow, row_name: &str) {
    match row_name {
        "region-live-convergence" => {
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .locality_region_match_count(),
                1
            );
            assert_eq!(row.control_lane.counter_snapshot.live_patch_count(), 1);
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .live_patch_field_delta_count(),
                1
            );
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .locality_work_avoided_by_region_narrowing_count(),
                1
            );
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .stream_contract_admission_count(),
                0
            );
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .locality_widening_denial_count(),
                0
            );
        }
        "off-region-suppression-parity" => {
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .locality_off_region_suppression_count(),
                1
            );
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .locality_irrelevant_broad_control_count(),
                1
            );
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .live_suppressed_update_count(),
                1
            );
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .locality_work_avoided_vs_broad_control_count(),
                1
            );
            assert_eq!(row.control_lane.counter_snapshot.live_patch_count(), 0);
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .stream_contract_admission_count(),
                0
            );
        }
        "collection-partition-hit" => {
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .locality_partition_match_count(),
                1
            );
            assert_eq!(row.control_lane.counter_snapshot.live_patch_count(), 1);
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .live_patch_field_delta_count(),
                1
            );
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .stream_contract_admission_count(),
                0
            );
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .locality_widening_denial_count(),
                0
            );
        }
        "bounded-materialization-region-hit" => {
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .locality_region_match_count(),
                1
            );
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .live_materialization_patch_count(),
                1
            );
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .live_work_avoided_by_scope_proof_count(),
                1
            );
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .stream_contract_admission_count(),
                0
            );
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .locality_widening_denial_count(),
                0
            );
        }
        "detail-region-single-peer-widening" => {
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .locality_region_match_count(),
                1
            );
            assert_eq!(row.control_lane.counter_snapshot.live_patch_count(), 1);
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .locality_widening_admission_count(),
                1
            );
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .locality_widening_denial_count(),
                0
            );
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .stream_contract_admission_count(),
                0
            );
        }
        "broad-vs-region-narrowing-control" => {
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .locality_region_match_count(),
                0
            );
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .locality_work_avoided_by_region_narrowing_count(),
                0
            );
            assert_eq!(
                row.hostile_lane
                    .counter_snapshot
                    .locality_region_match_count(),
                1
            );
            assert_eq!(
                row.hostile_lane
                    .counter_snapshot
                    .locality_work_avoided_by_region_narrowing_count(),
                1
            );
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .stream_contract_admission_count(),
                0
            );
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .locality_widening_denial_count(),
                0
            );
        }
        "locality-breadth-budget-enforcement" => {
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .locality_region_match_count(),
                1
            );
            assert_eq!(row.control_lane.counter_snapshot.live_patch_count(), 1);
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .locality_breadth_budget_cross_count(),
                0
            );
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .stream_contract_admission_count(),
                0
            );
        }
        "locality-work-avoided-counter-parity" => {
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .locality_off_region_suppression_count(),
                1
            );
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .locality_work_avoided_by_region_narrowing_count(),
                1
            );
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .locality_work_avoided_vs_broad_control_count(),
                1
            );
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .stream_contract_admission_count(),
                0
            );
        }
        _ => panic!("missing canonical row expectation handler for {row_name}"),
    }
}
