use crate::harness::live_certification::LiveCertificationRow;

pub(super) fn assert_canonical_stream_expectation(row: &LiveCertificationRow, row_name: &str) {
    match row_name {
        "cdc-stream-lowered-parity" => {
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .stream_contract_admission_count(),
                1
            );
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .stream_lowered_delivery_count(),
                1
            );
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .stream_lowered_delivery_width(),
                2
            );
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .locality_widening_denial_count(),
                0
            );
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .stream_member_width_budget_cross_count(),
                0
            );
        }
        "stream-contract-delivery-parity" => {
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .stream_contract_admission_count(),
                1
            );
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .stream_lowered_delivery_count(),
                1
            );
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .stream_lowered_delivery_width(),
                1
            );
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .locality_widening_denial_count(),
                0
            );
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .stream_member_width_budget_cross_count(),
                0
            );
        }
        "stream-member-width-budget-enforcement" => {
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .stream_contract_admission_count(),
                1
            );
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .stream_lowered_delivery_count(),
                1
            );
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .stream_lowered_delivery_width(),
                2
            );
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .stream_member_width_budget_cross_count(),
                0
            );
            assert_eq!(
                row.control_lane
                    .counter_snapshot
                    .locality_widening_denial_count(),
                0
            );
        }
        _ => panic!("missing canonical row expectation handler for {row_name}"),
    }
}
