use crate::brep::topology_graph::{
    TopologyBody, TopologyFace, TopologyLoop, TopologyLump, TopologyModel, TopologyRegion,
    TopologyShell, TopologyView,
};

use super::primitives::*;

pub(crate) fn tetrahedral_closed_shell_view() -> TopologyView {
    let model_id = entity(200);
    let body_id = entity(201);
    let lump_id = entity(202);
    let region_id = entity(203);
    let shell_id = entity(204);

    let vertices = [entity(210), entity(211), entity(212), entity(213)];
    let edges_ids = [
        entity(220),
        entity(221),
        entity(222),
        entity(223),
        entity(224),
        entity(225),
    ];
    let face_ids = [entity(230), entity(231), entity(232), entity(233)];
    let loop_ids = [entity(240), entity(241), entity(242), entity(243)];
    let half_edge_ids = [
        entity(250),
        entity(251),
        entity(252),
        entity(253),
        entity(254),
        entity(255),
        entity(256),
        entity(257),
        entity(258),
        entity(259),
        entity(260),
        entity(261),
    ];

    TopologyView {
        models: vec![TopologyModel {
            entity_id: model_id,
            label: "model".into(),
            body_ids: vec![body_id],
        }],
        bodies: vec![TopologyBody {
            entity_id: body_id,
            label: "body".into(),
            model_id: Some(model_id),
            lump_ids: vec![lump_id],
        }],
        lumps: vec![TopologyLump {
            entity_id: lump_id,
            label: "lump".into(),
            body_id: Some(body_id),
            region_ids: vec![region_id],
        }],
        regions: vec![TopologyRegion {
            entity_id: region_id,
            label: "region".into(),
            lump_id: Some(lump_id),
            shell_ids: vec![shell_id],
        }],
        shells: vec![TopologyShell {
            entity_id: shell_id,
            label: "tetra".into(),
            region_id: Some(region_id),
            face_ids: face_ids.to_vec(),
        }],
        faces: vec![
            TopologyFace {
                entity_id: face_ids[0],
                label: "f012".into(),
                shell_id: Some(shell_id),
                outer_loop_id: Some(loop_ids[0]),
                inner_loop_ids: vec![],
                boundary_half_edge_ids: vec![half_edge_ids[0], half_edge_ids[1], half_edge_ids[2]],
            },
            TopologyFace {
                entity_id: face_ids[1],
                label: "f013".into(),
                shell_id: Some(shell_id),
                outer_loop_id: Some(loop_ids[1]),
                inner_loop_ids: vec![],
                boundary_half_edge_ids: vec![half_edge_ids[3], half_edge_ids[4], half_edge_ids[5]],
            },
            TopologyFace {
                entity_id: face_ids[2],
                label: "f123".into(),
                shell_id: Some(shell_id),
                outer_loop_id: Some(loop_ids[2]),
                inner_loop_ids: vec![],
                boundary_half_edge_ids: vec![half_edge_ids[6], half_edge_ids[7], half_edge_ids[8]],
            },
            TopologyFace {
                entity_id: face_ids[3],
                label: "f023".into(),
                shell_id: Some(shell_id),
                outer_loop_id: Some(loop_ids[3]),
                inner_loop_ids: vec![],
                boundary_half_edge_ids: vec![
                    half_edge_ids[9],
                    half_edge_ids[10],
                    half_edge_ids[11],
                ],
            },
        ],
        loops: vec![
            TopologyLoop {
                entity_id: loop_ids[0],
                label: "l012".into(),
                face_ids: vec![face_ids[0]],
                half_edge_ids: vec![half_edge_ids[0], half_edge_ids[1], half_edge_ids[2]],
            },
            TopologyLoop {
                entity_id: loop_ids[1],
                label: "l013".into(),
                face_ids: vec![face_ids[1]],
                half_edge_ids: vec![half_edge_ids[3], half_edge_ids[4], half_edge_ids[5]],
            },
            TopologyLoop {
                entity_id: loop_ids[2],
                label: "l123".into(),
                face_ids: vec![face_ids[2]],
                half_edge_ids: vec![half_edge_ids[6], half_edge_ids[7], half_edge_ids[8]],
            },
            TopologyLoop {
                entity_id: loop_ids[3],
                label: "l023".into(),
                face_ids: vec![face_ids[3]],
                half_edge_ids: vec![half_edge_ids[9], half_edge_ids[10], half_edge_ids[11]],
            },
        ],
        wires: vec![],
        half_edges: vec![
            half_edge_with_links(
                half_edge_ids[0],
                "he01",
                Some(loop_ids[0]),
                None,
                Some(half_edge_ids[1]),
                Some(half_edge_ids[2]),
                Some(half_edge_ids[5]),
                Some(edges_ids[0]),
                Some(vertices[0]),
                Some(vertices[1]),
                Some(face_ids[0]),
            ),
            half_edge_with_links(
                half_edge_ids[1],
                "he12",
                Some(loop_ids[0]),
                None,
                Some(half_edge_ids[2]),
                Some(half_edge_ids[0]),
                Some(half_edge_ids[8]),
                Some(edges_ids[1]),
                Some(vertices[1]),
                Some(vertices[2]),
                Some(face_ids[0]),
            ),
            half_edge_with_links(
                half_edge_ids[2],
                "he20",
                Some(loop_ids[0]),
                None,
                Some(half_edge_ids[0]),
                Some(half_edge_ids[1]),
                Some(half_edge_ids[10]),
                Some(edges_ids[2]),
                Some(vertices[2]),
                Some(vertices[0]),
                Some(face_ids[0]),
            ),
            half_edge_with_links(
                half_edge_ids[3],
                "he03",
                Some(loop_ids[1]),
                None,
                Some(half_edge_ids[4]),
                Some(half_edge_ids[5]),
                Some(half_edge_ids[11]),
                Some(edges_ids[3]),
                Some(vertices[0]),
                Some(vertices[3]),
                Some(face_ids[1]),
            ),
            half_edge_with_links(
                half_edge_ids[4],
                "he31",
                Some(loop_ids[1]),
                None,
                Some(half_edge_ids[5]),
                Some(half_edge_ids[3]),
                Some(half_edge_ids[7]),
                Some(edges_ids[4]),
                Some(vertices[3]),
                Some(vertices[1]),
                Some(face_ids[1]),
            ),
            half_edge_with_links(
                half_edge_ids[5],
                "he10",
                Some(loop_ids[1]),
                None,
                Some(half_edge_ids[3]),
                Some(half_edge_ids[4]),
                Some(half_edge_ids[0]),
                Some(edges_ids[0]),
                Some(vertices[1]),
                Some(vertices[0]),
                Some(face_ids[1]),
            ),
            half_edge_with_links(
                half_edge_ids[6],
                "he23",
                Some(loop_ids[2]),
                None,
                Some(half_edge_ids[7]),
                Some(half_edge_ids[8]),
                Some(half_edge_ids[9]),
                Some(edges_ids[5]),
                Some(vertices[2]),
                Some(vertices[3]),
                Some(face_ids[2]),
            ),
            half_edge_with_links(
                half_edge_ids[7],
                "he31b",
                Some(loop_ids[2]),
                None,
                Some(half_edge_ids[8]),
                Some(half_edge_ids[6]),
                Some(half_edge_ids[4]),
                Some(edges_ids[4]),
                Some(vertices[3]),
                Some(vertices[1]),
                Some(face_ids[2]),
            ),
            half_edge_with_links(
                half_edge_ids[8],
                "he12b",
                Some(loop_ids[2]),
                None,
                Some(half_edge_ids[6]),
                Some(half_edge_ids[7]),
                Some(half_edge_ids[1]),
                Some(edges_ids[1]),
                Some(vertices[1]),
                Some(vertices[2]),
                Some(face_ids[2]),
            ),
            half_edge_with_links(
                half_edge_ids[9],
                "he32",
                Some(loop_ids[3]),
                None,
                Some(half_edge_ids[10]),
                Some(half_edge_ids[11]),
                Some(half_edge_ids[6]),
                Some(edges_ids[5]),
                Some(vertices[3]),
                Some(vertices[2]),
                Some(face_ids[3]),
            ),
            half_edge_with_links(
                half_edge_ids[10],
                "he20b",
                Some(loop_ids[3]),
                None,
                Some(half_edge_ids[11]),
                Some(half_edge_ids[9]),
                Some(half_edge_ids[2]),
                Some(edges_ids[2]),
                Some(vertices[2]),
                Some(vertices[0]),
                Some(face_ids[3]),
            ),
            half_edge_with_links(
                half_edge_ids[11],
                "he02",
                Some(loop_ids[3]),
                None,
                Some(half_edge_ids[9]),
                Some(half_edge_ids[10]),
                Some(half_edge_ids[3]),
                Some(edges_ids[3]),
                Some(vertices[0]),
                Some(vertices[3]),
                Some(face_ids[3]),
            ),
        ],
        edges: vec![
            edge("e01", edges_ids[0]),
            edge("e12", edges_ids[1]),
            edge("e20", edges_ids[2]),
            edge("e03", edges_ids[3]),
            edge("e31", edges_ids[4]),
            edge("e23", edges_ids[5]),
        ],
        vertices: vec![
            vertex("v0", vertices[0]),
            vertex("v1", vertices[1]),
            vertex("v2", vertices[2]),
            vertex("v3", vertices[3]),
        ],
    }
}
