pub use crate::authoring::{
    AspectFieldSelector, AuthoredBundleError, AuthoredBundleFailureClass, AuthoredResultShapeField,
    AuthoringError, AuthoringFailureClass, CollectionAuthoredQuery, CollectionAuthoredResultShape,
    CollectionQueryBuilder, CollectionResultShapeBuilder, DetailAuthoredQuery,
    DetailAuthoredResultShape, DetailQueryBuilder, DetailResultShapeBuilder, EqualityPredicate,
    GuidedAuthoringPath, IntegerComparisonOperator, IntegerComparisonPredicate, OrderingDirection,
    OrderingSelector, PredicateSelector, QueryFamily, RelationName, ResultShapeFamily,
    RootEntityKey, ScalarPredicateValue, TraversalSelector,
};
pub use crate::authorized_projection::{
    runtime_backed_authorized_projection_support_profile, AuthorizedProjectionArtifact,
    AuthorizedProjectionCounters, AuthorizedProjectionError, AuthorizedProjectionFailureClass,
    AuthorizedProjectionIdentity, AuthorizedProjectionSupportProfile,
    AuthorizedProjectionSupportStatus, AuthorizedProjectionSurface, MaskedProjectionArtifact,
    PolicyAspectMask, PolicyFieldInfluenceSet, PolicyInfluenceEntry, PolicyInfluencePurpose,
    PolicyInfluenceSet, PolicyMaskSnapshot, ProjectionVisibility,
};
pub use crate::basis::{
    preflight_execution_basis, resolve_runtime_current_snapshot_basis, resolve_snapshot_basis,
    snapshot_resolution_report, BasisAuthorityFamily, BasisPreflightError, BasisResolutionError,
    BasisResolutionMode, ExecutionBasisIntent, ExecutionPreflightBundle, ResolvedBasisProof,
    ResolvedSnapshotBasis, ResolvedSnapshotIdentity, SnapshotLineageClass,
    SnapshotResolutionReport,
};
pub use crate::basis_lifecycle::{
    adapt_branch_admission_to_lifecycle, adapt_causal_inspection_evidence_to_lifecycle,
    adapt_historical_materialization_to_lifecycle, adapt_preview_admission_to_lifecycle,
    adapt_query_basis_context_to_lifecycle, adapt_subscription_basis_posture_to_lifecycle,
    admit_basis_capability, basis_lifecycle, basis_lifecycle_adapter_shape_contract_digest,
    basis_lifecycle_dx_certification_digest, basis_lifecycle_migration_audit,
    basis_lifecycle_migration_audit_digest, basis_lifecycle_phase_artifact_manifest_digest,
    basis_lifecycle_phase_manifest, basis_lifecycle_phase_progression_digest,
    basis_lifecycle_proof_shape_audit, basis_lifecycle_proof_shape_audit_digest,
    basis_lifecycle_public_boundary_audit, basis_lifecycle_public_boundary_audit_digest,
    basis_lifecycle_reuse_matrix, basis_lifecycle_reuse_matrix_digest,
    basis_lifecycle_signal_authority_digest, basis_lifecycle_support_matrix,
    basis_lifecycle_typestate_transition_digest, certify_basis_lifecycle,
    certify_basis_lifecycle_performance_slopes, discover_basis_lifecycle_support,
    emit_certification_basis_receipt, emit_inspection_basis_receipt,
    emit_materialization_basis_receipt, emit_mutation_preparation_basis_receipt,
    emit_observation_basis_receipt, emit_preview_closeout_basis_receipt, emit_replay_basis_receipt,
    emit_subscription_activation_basis_receipt, emit_subscription_declaration_basis_receipt,
    envelope_basis_use, evaluate_basis_certification_eligibility,
    evaluate_basis_inspection_advisory_eligibility, evaluate_basis_inspection_eligibility,
    evaluate_basis_materialization_eligibility, evaluate_basis_mutation_preparation_eligibility,
    evaluate_basis_observation_eligibility, evaluate_basis_preview_closeout_eligibility,
    evaluate_basis_replay_eligibility, evaluate_basis_subscription_activation_eligibility,
    evaluate_basis_subscription_declaration_eligibility, normalize_raw_basis_intent,
    readmit_lower_runtime_evidence, scope_basis_for_certification, scope_basis_for_inspection,
    scope_basis_for_materialization, scope_basis_for_mutation_preparation,
    scope_basis_for_observation, scope_basis_for_preview_closeout, scope_basis_for_replay,
    scope_basis_for_subscription_activation, scope_basis_for_subscription_declaration,
    AdmittedBasisCapability, AdvisoryBasisEligibility, BasisAuthorityPosture, BasisEligibility,
    BasisEligibilityCounters, BasisEligibilityDecisionTrace, BasisEligibilityDenialCause,
    BasisFamily, BasisIntentDenial, BasisIntentDenialKind, BasisLifecycleAdapterError,
    BasisLifecycleAdapterOutcome, BasisLifecycleAdapterProof, BasisLifecycleCertificationBundle,
    BasisLifecycleCertificationLane, BasisLifecycleCertificationOutputDigest,
    BasisLifecycleCertificationOutputPosture, BasisLifecycleCertificationRow,
    BasisLifecycleIntentBuilder, BasisLifecycleIntentDraft, BasisLifecycleMigrationAudit,
    BasisLifecycleMigrationAuditRow, BasisLifecycleMigrationCounters,
    BasisLifecycleMigrationPosture, BasisLifecycleMigrationSurface,
    BasisLifecyclePerformanceSlopeReport, BasisLifecyclePhaseArtifact, BasisLifecyclePhaseManifest,
    BasisLifecyclePhaseManifestRow, BasisLifecyclePolicyIntentDraft, BasisLifecyclePosture,
    BasisLifecycleProofShapeAudit, BasisLifecycleProofShapeAuditRow,
    BasisLifecycleProofShapeEnforcement, BasisLifecycleProofShapeViolation,
    BasisLifecyclePublicBoundaryAudit, BasisLifecyclePublicBoundaryAuditRow,
    BasisLifecyclePublicBoundarySurface, BasisLifecycleReuseMatrix, BasisLifecycleReuseMatrixRow,
    BasisLifecycleReuseSurface, BasisLifecycleSlopeDigest, BasisLifecycleSlopeFamily,
    BasisLifecycleSupportDiscovery, BasisLifecycleSupportMatrix, BasisLifecycleSupportRow,
    BasisNextTransition, BasisOperationLane, BasisScopePosture, BasisSupportPosture,
    BasisUseReceipt, BasisUseReceiptKind, BasisVisibilityPosture, CertificationLaneWitness,
    DeniedBasisCapability, DeniedBasisCapabilityKind, InspectionAdvisoryBasisPath,
    InspectionLaneWitness, LowerRuntimeBasisEvidence, LowerRuntimeBoundBasis,
    LowerRuntimeEvidenceAuthority, MaterializationLaneWitness,
    MutationPreparationBasisAdmissionPath, MutationPreparationLaneWitness, NormalizedBasisIntent,
    ObservationBasisAdmissionPath, ObservationBasisReceiptPath, ObservationBasisUsePath,
    ObservationLaneWitness, PreviewCloseoutLaneWitness, RawBasisIntent, ReplayLaneWitness,
    ScopedBasisProof, ScopedCertificationBasis, ScopedInspectionBasis, ScopedMaterializationBasis,
    ScopedMutationPreparationBasis, ScopedObservationBasis, ScopedPreviewCloseoutBasis,
    ScopedReplayBasis, ScopedSubscriptionActivationBasis, ScopedSubscriptionDeclarationBasis,
    SelfDescribingBasisEnvelope, SubscriptionActivationLaneWitness,
    SubscriptionDeclarationLaneWitness,
};
pub use crate::binding::{
    derive_binding_requirements, resolve_bindings, BindingError, BindingFailureClass,
    BindingRequirement, BindingRequirements, BindingResolution, BindingResolutionError,
    BoundBinding, BoundBindings, IdentityBindingDescriptor, NonIdentityBindingMetadata,
    NonIdentityBindingMetadataKey, QueryBindingDescriptor, QueryBindingSlot, QueryBindingSubject,
};
pub use crate::canonicalization::{
    canonicalize_request, CanonicalOrderingEntry, CanonicalPredicateEntry,
    CanonicalPredicateFamily, CanonicalProjectionEntry, CanonicalQueryArtifact,
    CanonicalQueryBundle, CanonicalResultField, CanonicalResultShapeArtifact,
    CanonicalTraversalEntry, CanonicalizationFailureClass, QueryCanonicalizationError,
};
pub use crate::collection::{
    AggregateFunctionFamily, AggregateGroupingShape, AggregateInputBreadth, AggregateShapeArtifact,
    CollectionOrderingBasis, CollectionOrderingDirection, CollectionPlanBundle,
    CollectionPlanningContext, CollectionResultFamily, CollectionWindowPolicy,
    CursorAdvanceContract, CursorBoundaryDigest, DerivedFieldComputationClass,
    DerivedFieldPlanArtifact, MaterializationBreadthClass, OpaquePageCursor, OrderingKeyPath,
    OrderingTieBreakContract, PostReadShapingPlan, RollupEdgeClass, RollupShapeArtifact,
    StableOrderingContract, TraversalBoundContract, TraversalDepthLimit, TraversalEdgeClass,
};
pub use crate::composition::{
    runtime_backed_query_composition_support_profile, BasisScopeEvidence,
    ComposedCanonicalQueryBundle, CompositionCounters, CompositionDigest, CompositionReport,
    ExpandedComposedIntent, ExpandedScopeArtifact, GuidedCompositionPath,
    QueryCompositionAdmissionFailureClass, QueryCompositionComplexityStatus,
    QueryCompositionDeferredScopeMarker, QueryCompositionError, QueryCompositionFamily,
    QueryCompositionSupportProfile, QueryScopeDescriptor, QueryTemplateDescriptor, ScopeFamily,
    ScopeLineageDigest, TemplateBindingDigest, TemplateBindingSet, TemplateFamily,
    TemplateInstantiationArtifact, TemplateParameterSlot, TemplateParameterSlotKind,
};
pub use crate::correspondence::{
    resolve_correspondence_evidence, AdvisoryStructuralAmbiguous, AdvisoryStructuralUnique,
    CorrespondenceAmbiguityEnvelope, CorrespondenceCandidateSet, CorrespondenceComplexityContract,
    CorrespondenceCostPosture, CorrespondenceCounterSnapshot, CorrespondenceDenied,
    CorrespondenceDisagreementEnvelope, CorrespondenceEvaluationError,
    CorrespondenceEvaluationFailureClass, CorrespondenceEvaluationRequest,
    CorrespondenceEvidenceResolved, CorrespondenceOutcome, CorrespondencePerformanceStatusMarker,
    CorrespondenceVocabularyReport, LineageContinuity, LineageStructuralDisagreement,
    StructuralCandidateBudget, StructuralCandidateDiscoveryPlan,
    StructuralCandidateOrderingContract, UniqueStructuralCorrespondenceWitness,
};
pub use crate::correspondence_history::{
    compose_correspondence_historical_envelope, compose_historical_admission_denied_envelope,
    compose_historical_path_denied_envelope, CorrespondenceHistoricalAmbiguityEnvelope,
    CorrespondenceHistoricalDeniedEnvelope, CorrespondenceHistoricalDisagreementEnvelope,
    CorrespondenceHistoricalEnvelope, CorrespondenceHistoricalSuccessEnvelope,
    HistoricalPathAdmissionDeniedEnvelope, HistoricalPathDeniedEnvelope,
    MetadataPreservingHistoricalResultView,
};
pub use crate::correspondence_history_parity::{
    build_correspondence_historical_parity_bundle, CorrespondenceHistoricalParityBundle,
    CorrespondenceHistoricalParityBundleError, CorrespondenceHistoricalParityVariant,
};
pub use crate::declarative_live::{
    declare_branch_compare_from_live_sessions, declare_live_query_session,
    declare_runtime_live_query_session, declare_writeback_from_live_session,
    DeclarativeBranchCompareArtifact, DeclarativeBranchCompareChangeFamily,
    DeclarativeBranchCompareFieldDelta, DeclarativeBranchCompareIdentityClass,
    DeclarativeBranchCompareInputRow, DeclarativeBranchCompareRow, DeclarativeBranchCompareValue,
    DeclarativeEqualityFilter, DeclarativeIntegerComparisonFilter, DeclarativeLiveQueryError,
    DeclarativeLiveQueryRequest, DeclarativeLiveQuerySession, DeclarativeLiveViewShape,
    DeclarativeOrderingField, DeclarativePredicateFilter, DeclarativePresenceFilter,
    DeclarativePresenceFilterKind, DeclarativeProjectionField, DeclarativeSetMembershipFilter,
    DeclarativeStringContainsFilter, DeclarativeWritebackArtifact, DeclarativeWritebackChange,
    DeclarativeWritebackIntent, DeclarativeWritebackValue,
};
pub use crate::diagnostics::{
    CanonicalizationCounters, CanonicalizationReport, CanonicalizationWarning,
    CompatibilityEvidence, IdentityFreezeEvidence, NormalizationEvent,
};
pub use crate::effect_lifecycle::{
    admit_effect_batch_components, admit_effect_intent, certify_effect_execution_pipeline,
    discover_effect_lifecycle_support, effect_batch, effect_lifecycle_family_inventory,
    effect_lifecycle_family_row_for_key, effect_lifecycle_public_surface_inventory,
    effect_lifecycle_support_matrix, effect_lifecycle_support_row_matches_inventory,
    effect_lifecycle_supported_basis_families, evaluate_effect_eligibility,
    execute_lowered_effect_plan, lower_authority_scoped_effect_plan, normalize_raw_effect_intent,
    scope_admitted_effect_plan, AdmittedEffectBatch, AdmittedEffectIntent,
    AdvisoryEffectEligibility, AuthorityScopedEffectPlan, BridgeExecutionOracle,
    DeferredEffectEligibility, DeniedEffectEligibility, DeniedEffectEligibilityKind,
    EffectArtifactPolicy, EffectAuthoringBasis, EffectAuthorityLane, EffectAuthorityOwner,
    EffectBatchAdmissionDenial, EffectBatchAdmissionDenialKind, EffectBatchExecutionDenial,
    EffectBatchExecutionDenialKind, EffectBatchIntentDraft, EffectBatchIntentDraftWithBasis,
    EffectConflictFootprint, EffectDeferredNeighborFamily, EffectDeferredResiduePosture,
    EffectDeferredSupportContract, EffectDiagnosticsMaterialization, EffectDiagnosticsRequest,
    EffectEligibility, EffectEligibilityDecisionTrace, EffectEligibilityOutcome,
    EffectEnvelopePrimaryResult, EffectEnvelopeSourceRefs, EffectExecutionAuthority,
    EffectExecutionCertificationBundle, EffectExecutionCertificationLane,
    EffectExecutionCertificationOutputDigest, EffectExecutionCertificationRow,
    EffectExecutionDenial, EffectExecutionDenialKind, EffectExecutionOracleError,
    EffectExecutionOracleErrorKind, EffectExecutionOracleVerification,
    EffectExecutionOracleVerificationKind, EffectExecutionReceipt, EffectFamily,
    EffectIntentDenial, EffectIntentDenialKind, EffectInvariantScope, EffectLifecycleCounters,
    EffectLifecycleFamilyInventory, EffectLifecycleFamilyInventoryRow, EffectLifecycleFamilyKey,
    EffectLifecyclePublicSurfaceInventory, EffectLifecyclePublicSurfaceRow,
    EffectLifecycleSupportDiscovery, EffectLifecycleSupportMatrix, EffectLifecycleSupportRow,
    EffectLoweredArtifactKind, EffectLoweringDenial, EffectLoweringDenialKind,
    EffectOperationInput, EffectPermittedLoweringFamily, EffectPolicyPosture, EffectPreviewPosture,
    EffectPublicSurfaceAvailability, EffectPublicSurfaceKind, EffectReceiptArtifactKind,
    EffectReceiptDecisionTrace, EffectReceiptIntegrityMarkers, EffectReceiptTargetEvidence,
    EffectReceiptTransitionKind, EffectReceiptTransitionPosture, EffectReceiptTransitionRule,
    EffectReceiptTransitionRules, EffectStrategyIdentityTarget, EffectSupportCause,
    EffectSupportPosture, ExecutedEffectAuthorityArtifact, ExecutedEffectBatchPlan,
    ExecutedEffectPlan, LoweredEffectBatchExecutionArtifact, LoweredEffectBatchExecutionPlan,
    LoweredEffectExecutionArtifact, LoweredEffectExecutionPlan,
    LoweredRelationalMutationBatchExecutionArtifact, NormalizedEffectIntent, RawEffectIntent,
    RebindRequiredEffectEligibility, RelationalExecutionOracle, SelfDescribingEffectEnvelope,
};
#[cfg(test)]
pub use crate::execution::{execute_parallel_admission_route, execute_serial_fallback_route};
pub use crate::execution::{
    execute_preflight_bundle, ExecutionCounters, ExecutionError, ExecutionFailureClass,
    ExecutionReport, ExecutionResultEnvelope,
};
#[cfg(not(test))]
pub use crate::frontier_planning::FrontierSurfaceDigest;
#[cfg(test)]
#[allow(unused_imports)]
pub use crate::frontier_planning::{
    BoundedMaterializationFrontierPreflight, FrontierAwarePlan, FrontierBreadthPrediction,
    FrontierBundleRoutePlanningError, FrontierComplexityContract, FrontierCounterSnapshot,
    FrontierDisjointnessClass, FrontierParityBundle, FrontierParityBundleError,
    FrontierPerformanceStatus, FrontierPlanningCounters, FrontierPlanningReport,
    FrontierPostureDigest, FrontierPredictionDriftOutcome, FrontierPreflightAdmissionError,
    FrontierRouteCounters, FrontierRoutePlanningError, FrontierRouteReport, FrontierSurfaceDigest,
    OrderedCollectionFrontierPreflight, ParallelAdmissionDecision, ParallelAdmissionRoute,
    ParallelAdmissionRouteSet, PlannedRouteFamily, SerialFallbackBundleRoutes,
    SerialFallbackReason, SerialFallbackRoute,
};
pub use crate::frontier_signal_adapter::{
    SignalAdmissionEvidenceError, SignalFrontierSurfaceEvidence,
};
pub use crate::historical::{
    admit_historical_evaluation_path, materialization_metadata_from_resolved,
    resolve_historical_materialization_path, AdmittedHistoricalPathClass,
    HistoricalCapabilityDescriptor, HistoricalCounterSnapshot, HistoricalEvaluationAdmission,
    HistoricalEvaluationError, HistoricalEvaluationFailureClass, HistoricalEvaluationRequest,
    HistoricalMaterializationDescriptor, HistoricalMaterializationPathMetadata,
    HistoricalPathAdmitted, HistoricalPathCompatibilityOutcome, HistoricalPathComplexityContract,
    HistoricalPathCostPosture, HistoricalPathRequested, HistoricalPathResolved,
    HistoricalPathReuseDescriptor, HistoricalPathSubstitutionDenied,
    HistoricalPathVocabularyReport, HistoricalPerformanceStatusMarker,
    HistoricalReconstructionBudget, HistoricalReplaySpanBudget, PerformancePredictionDriftOutcome,
    ReplayTailReuseEligibility, RequestedHistoricalPathClass, ResolvedHistoricalPathClass,
    RetainedStateReuseEligibility,
};
pub use crate::identity::{
    BasisDigest, BindingFulfillmentDigest, CanonicalEquivalence, CanonicalQueryDigest,
    CanonicalResultShapeDigest, CollectionPlanDigest, CorrespondenceCostPostureDigest,
    CorrespondenceOutcomeDigest, CounterSnapshotDigest, FailureDigest, HistoricalCostPostureDigest,
    HistoricalPathClassDigest, LineageDigest, PlanDigest, ResultDigest, SchemaBasisDigest,
    ValidatedQueryDigest, ValidatedResultShapeDigest,
};
pub use crate::identity_authority::QueryExternalIdentityToken;
pub use crate::identity_evolution::{
    admit_identity_evolution_query, compare_identity_evolution_denial_classification,
    compare_identity_evolution_denial_replay, compare_identity_evolution_result_classification,
    compare_identity_evolution_result_replay, execute_admitted_identity_evolution_query,
    runtime_backed_direct_identity_evolution_support_profile, AdmittedIdentityEvolutionQuery,
    AdvisoryIdentityCandidateSet, BranchLocalityClass, CorrespondenceIdentityComparison,
    IdentityComparisonIntent, IdentityEvolutionAdmissionError,
    IdentityEvolutionAdmissionFailureClass, IdentityEvolutionAmbiguityBundle,
    IdentityEvolutionBudgetClass, IdentityEvolutionCertificationDenialEvidence,
    IdentityEvolutionCertificationEvidence, IdentityEvolutionCertificationResultEvidence,
    IdentityEvolutionComparisonBasisFamily, IdentityEvolutionComplexityContract,
    IdentityEvolutionComplexityReport, IdentityEvolutionComplexityStatus,
    IdentityEvolutionCostClass, IdentityEvolutionCounterSnapshot,
    IdentityEvolutionDeferredScopeMarker, IdentityEvolutionDeniedBundle,
    IdentityEvolutionExecutionArtifact, IdentityEvolutionExecutionCounters,
    IdentityEvolutionExecutionFamily, IdentityEvolutionIdentityBreakBundle,
    IdentityEvolutionMetadata, IdentityEvolutionOutcomeFamily,
    IdentityEvolutionPredictionDriftOutcome, IdentityEvolutionPredictionReport,
    IdentityEvolutionQueryContext, IdentityEvolutionQueryFamily, IdentityEvolutionReplayArtifact,
    IdentityEvolutionReplayParityClass, IdentityEvolutionResultBundle,
    IdentityEvolutionSupportProfile, InspectorIdentityArtifact, InspectorIdentityClassification,
    InspectorIdentityDigest, LineageTraversalDescriptor, LineageTraversalFamily,
    PluralIdentitySuccessorSet, PromotionOrMergeAuthorityState, SingularIdentityContinuityResult,
};
pub use crate::intent_admission::{
    forge_query_basis_observation_intent, forge_query_projection_consumption_intent,
    ForgeQueryBasisObservationAdmittedIntent, ForgeQueryBasisObservationIntentAuthoring,
    ForgeQueryBasisObservationIntentReview, ForgeQueryProjectionConsumptionAdmittedIntent,
    ForgeQueryProjectionConsumptionIntentAuthoring, ForgeQueryProjectionConsumptionIntentReview,
};
pub use crate::live::{
    admit_region_scoped_live_plan, build_milestone_five_live_artifact, execute_live_change,
    execute_region_scoped_live_change, lower_region_scoped_execution_to_stream_contract,
    promote_preflight_bundle_to_live, replay_live_sequence, AdmittedStreamConsumerContract,
    BoundedMaterializationLiveOutcome, BoundedMaterializationPatch,
    BoundedMaterializationPatchKind, BridgeChangeSummary, BridgeFieldDelta, BridgeLocalitySlice,
    BridgeRelationDelta, BridgeSliceCategory, ChangeRelevance, CoalescingDecision,
    CollectionMembershipChange, CollectionOrderingChange, DeliveryContractLowering,
    DeliveryContractReplayRecord, DeliveryLocalityOutcome, DetailLiveOutcome, DetailPatch,
    IrrelevantChangeClass, LiveBoundedMaterializationPatchError, LiveCertificationLane,
    LiveCertificationRejectionLane, LiveChangeOrdinal, LiveChangeSequenceId, LiveCoalescingError,
    LiveCollectionPatchError, LiveDetailPatchError, LiveExecutionEnvelope, LiveExecutionError,
    LiveExecutionReport, LiveExpectedRejectionError, LivePatchDigest, LivePatchEnvelope,
    LivePatchPayload, LivePolicyCounters, LiveProgressBasis, LiveProgressError,
    LivePromotionDescriptor, LivePromotionError, LiveQueryFamily, LiveQueryPlan, LiveRefreshError,
    LiveReplayBundle, LiveReplayDigest, LiveReplayError, LiveReplayRun, LiveReplayStepInput,
    LiveStartBasis, LiveSubscriptionDigest, LocalityAdmissionClass, LocalityAwareRelevanceContract,
    LocalityBreadthBudget, LocalityCostPosture, LocalityMaintenanceClass, LocalityMatchClass,
    LocalityMatchKind, LocalityPerformanceStatus, LocalityPredicateContract,
    LocalityScopeAdmission, LocalityScopeDigest, LocalityScopeKind, LocalitySemanticBasis,
    LocalityWideningBudget, LocalityWideningDecision, LocalityWideningPolicy,
    MaterializationScopeChange, MaterializationScopeTransition, MembershipTransition,
    MilestoneFiveLiveAdapter, MilestoneFiveLiveArtifact, OrderedCollectionLiveOutcome,
    OrderedCollectionPatch, OrderedCollectionPatchKind, OrderingFieldDelta, PartitionSliceMatch,
    PatchWidthAssessment, PatchWidthResolution, ProjectionFieldDelta, QueryDeliveryContract,
    QueryFieldKey, QueryRelevanceContract, RefreshAdmissionClass, RefreshAdmissionMatrix,
    RefreshFallback, RegionScopedExecutionReport, RegionScopedLiveCounters, RegionScopedLiveError,
    RegionScopedLiveExecutionEnvelope, RegionScopedLivePlan, RegionScopedPlanningReport,
    RegionScopedReplayBundle, RegionScopedSubscriptionIdentity, RegionSliceMatch,
    RelevantChangeClass, StreamConsumerShape, StreamContractDigest, StreamContractRequest,
    StreamLoweredDeliveryContract, StreamLoweringAdmissionClass, StreamLoweringCostPosture,
    StreamMemberProjection, StreamMemberWidthBudget, StreamWindowCompatibility,
    StreamWindowWidthBudget, SuppressionDecision, SuppressionReason,
};
pub use crate::live_performance::{
    CoalescingAdmissionClass, DebtPerformance, ForbiddenPerformance, IncrementalMaintenanceClass,
    IncrementalPatchEligibility, LiveMaintenanceComplexityContract, LiveMaintenanceCostClass,
    LiveMaintenanceWorkUnit, LivePerformanceReport, PatchWidthBudget, PatchWidthPolicy,
    PatchWidthUnit, PerformanceStatus, PerformanceStatusMarker, RefreshAdmissionStatus,
    RefreshCostClass, VerifiedPerformance,
};
pub use crate::memory_workspace::{
    admit_authored_entity_token, admit_external_commit_token, admit_external_snapshot_token,
    ForgeQueryAspect, ForgeQueryCommitIdentity, ForgeQueryEntity, ForgeQueryEntityIdentity,
    ForgeQueryLivePatch, ForgeQueryLiveViewHandle, ForgeQueryMemoryWorkspace,
    ForgeQueryMutationDelta, ForgeQueryMutationKind, ForgeQueryMutationReceipt,
    ForgeQuerySnapshotIdentity, ForgeQueryWorkspaceError,
};
pub use crate::projection_consumption::{
    certify_projection_consumption_closeout_core, declare_projection_consumption,
    discover_projection_consumption_support, evaluate_projection_consumption_eligibility,
    projection_consumption_family_inventory, projection_consumption_phase_progression_digest,
    projection_consumption_proof_shape_audit, projection_consumption_public_boundary_audit,
    projection_consumption_support_matrix, AdmittedProjectionConsumption,
    BoundProjectionFactFamily, CompletedProjectionFactConsumption,
    ConsumedContinuityAuthorityIdentity, ConsumedEffectContinuityFact, ConsumedEntityIdentityFact,
    ConsumedFieldValueFact, ConsumedMembershipFact, ConsumedProjectionFactSet,
    ConsumedRelationEndpointFact, ConsumedSourceReferenceFact, ConsumedTargetIdentityFact,
    ConsumedViewLocalIdentityFact, DeferredProjectionConsumption,
    DeferredProjectionConsumptionReason, DeniedProjectionConsumption,
    MaterializedProjectionContract, ProjectMaterializedFacts,
    ProjectionConsumptionAuthoringSurface, ProjectionConsumptionBindingContext,
    ProjectionConsumptionCertificationBundle, ProjectionConsumptionCertificationCounterSnapshot,
    ProjectionConsumptionCertificationLane, ProjectionConsumptionCertificationRow,
    ProjectionConsumptionCertifiedSourceSurface, ProjectionConsumptionDeclaration,
    ProjectionConsumptionDeclarationBuilder, ProjectionConsumptionDeclarationError,
    ProjectionConsumptionDeferredNeighborFamily, ProjectionConsumptionDenialReason,
    ProjectionConsumptionEligibility, ProjectionConsumptionEligibilityCounters,
    ProjectionConsumptionEligibilityTrace, ProjectionConsumptionEnvelopeSourceRefs,
    ProjectionConsumptionFamilyInventory, ProjectionConsumptionFamilyInventoryRow,
    ProjectionConsumptionProofShapeAudit, ProjectionConsumptionProofShapeAuditRow,
    ProjectionConsumptionProofShapeEnforcement, ProjectionConsumptionProofShapeViolation,
    ProjectionConsumptionPublicBoundaryAudit, ProjectionConsumptionPublicBoundaryAuditRow,
    ProjectionConsumptionPublicBoundarySurface, ProjectionConsumptionReceipt,
    ProjectionConsumptionSource, ProjectionConsumptionSupportMatrix,
    ProjectionConsumptionSupportMatrixRow, ProjectionConsumptionSupportPosture,
    ProjectionConsumptionSupportReport, ProjectionConsumptionSupportRow,
    ProjectionConsumptionTransitionKind, ProjectionConsumptionTransitionPosture,
    ProjectionConsumptionTransitionRule, ProjectionConsumptionTransitionRules,
    ProjectionConsumptionWarningKind, ProjectionConsumptionWarnings,
    ProjectionContractSourcePosture, ProjectionContractSupportPosture,
    ProjectionFactConsumptionAttempt, ProjectionFactConsumptionPathError,
    ProjectionFactExtractionCounters, ProjectionFactExtractionError, ProjectionFactKind,
    ProjectionFactRequest, ProjectionSourceFamily, ProjectionSourceReferenceIdentity,
    SelfDescribingProjectionConsumptionEnvelope, SourceMismatchedProjectionConsumption,
};
pub use forge_runtime_bridge::facade::RelationalBridgeRecordIdentityParts;
