pub(super) fn topology_operator_phase_seventeen_audit_sources(
) -> [(&'static str, &'static str, &'static str); 32] {
    [
        source(
            "topology.local-rewrites.mod",
            "crates/worth-topo/src/topology_operators/local_rewrites/mod.rs",
            include_str!("../../local_rewrites/mod.rs"),
        ),
        source(
            "topology.local-rewrites.boundary-wiring.mod",
            "crates/worth-topo/src/topology_operators/local_rewrites/boundary_wiring/mod.rs",
            include_str!("../../local_rewrites/boundary_wiring/mod.rs"),
        ),
        source(
            "topology.local-rewrites.boundary-wiring.adjacency-support",
            "crates/worth-topo/src/topology_operators/local_rewrites/boundary_wiring/adjacency_support.rs",
            include_str!("../../local_rewrites/boundary_wiring/adjacency_support.rs"),
        ),
        source(
            "topology.local-rewrites.boundary-wiring.composed-successor-program",
            "crates/worth-topo/src/topology_operators/local_rewrites/boundary_wiring/composed_successor_program.rs",
            include_str!("../../local_rewrites/boundary_wiring/composed_successor_program.rs"),
        ),
        source(
            "topology.local-rewrites.boundary-wiring.membership",
            "crates/worth-topo/src/topology_operators/local_rewrites/boundary_wiring/membership.rs",
            include_str!("../../local_rewrites/boundary_wiring/membership.rs"),
        ),
        source(
            "topology.local-rewrites.boundary-wiring.relation-update",
            "crates/worth-topo/src/topology_operators/local_rewrites/boundary_wiring/relation_update.rs",
            include_str!("../../local_rewrites/boundary_wiring/relation_update.rs"),
        ),
        source(
            "topology.local-rewrites.boundary-wiring.successor-admission",
            "crates/worth-topo/src/topology_operators/local_rewrites/boundary_wiring/successor_admission.rs",
            include_str!("../../local_rewrites/boundary_wiring/successor_admission.rs"),
        ),
        source(
            "topology.local-rewrites.entity-lifecycle.mod",
            "crates/worth-topo/src/topology_operators/local_rewrites/entity_lifecycle/mod.rs",
            include_str!("../../local_rewrites/entity_lifecycle/mod.rs"),
        ),
        source(
            "topology.local-rewrites.entity-lifecycle.relation-create",
            "crates/worth-topo/src/topology_operators/local_rewrites/entity_lifecycle/relation_create.rs",
            include_str!("../../local_rewrites/entity_lifecycle/relation_create.rs"),
        ),
        source(
            "topology.local-rewrites.radial-cycles.mod",
            "crates/worth-topo/src/topology_operators/local_rewrites/radial_cycles/mod.rs",
            include_str!("../../local_rewrites/radial_cycles/mod.rs"),
        ),
        source(
            "topology.local-rewrites.radial-cycles.splice-adjacency",
            "crates/worth-topo/src/topology_operators/local_rewrites/radial_cycles/splice_adjacency.rs",
            include_str!("../../local_rewrites/radial_cycles/splice_adjacency.rs"),
        ),
        source(
            "topology.local-rewrites.sheet-wire-laminar.mod",
            "crates/worth-topo/src/topology_operators/local_rewrites/sheet_wire_laminar/mod.rs",
            include_str!("../../local_rewrites/sheet_wire_laminar/mod.rs"),
        ),
        source(
            "topology.local-rewrites.sheet-wire-laminar.membership-admission",
            "crates/worth-topo/src/topology_operators/local_rewrites/sheet_wire_laminar/membership_admission.rs",
            include_str!("../../local_rewrites/sheet_wire_laminar/membership_admission.rs"),
        ),
        source(
            "topology.local-rewrites.sheet-wire-laminar.shell-face-rehome-support",
            "crates/worth-topo/src/topology_operators/local_rewrites/sheet_wire_laminar/shell_face_rehome_support.rs",
            include_str!("../../local_rewrites/sheet_wire_laminar/shell_face_rehome_support.rs"),
        ),
        source(
            "topology.local-rewrites.sheet-wire-laminar.wire-rehome-support",
            "crates/worth-topo/src/topology_operators/local_rewrites/sheet_wire_laminar/wire_rehome_support.rs",
            include_str!("../../local_rewrites/sheet_wire_laminar/wire_rehome_support.rs"),
        ),
        source(
            "topology.local-rewrites.sheet-wire-laminar.membership-programs.mod",
            "crates/worth-topo/src/topology_operators/local_rewrites/sheet_wire_laminar/membership_programs/mod.rs",
            include_str!("../../local_rewrites/sheet_wire_laminar/membership_programs/mod.rs"),
        ),
        source(
            "topology.local-rewrites.sheet-wire-laminar.face-inner-loop-program",
            "crates/worth-topo/src/topology_operators/local_rewrites/sheet_wire_laminar/membership_programs/face_inner_loop_program.rs",
            include_str!("../../local_rewrites/sheet_wire_laminar/membership_programs/face_inner_loop_program.rs"),
        ),
        source(
            "topology.local-rewrites.sheet-wire-laminar.shared",
            "crates/worth-topo/src/topology_operators/local_rewrites/sheet_wire_laminar/membership_programs/shared.rs",
            include_str!("../../local_rewrites/sheet_wire_laminar/membership_programs/shared.rs"),
        ),
        source(
            "topology.local-rewrites.sheet-wire-laminar.shell-membership-program",
            "crates/worth-topo/src/topology_operators/local_rewrites/sheet_wire_laminar/membership_programs/shell_membership_program.rs",
            include_str!("../../local_rewrites/sheet_wire_laminar/membership_programs/shell_membership_program.rs"),
        ),
        source(
            "topology.local-rewrites.sheet-wire-laminar.shell-split-program",
            "crates/worth-topo/src/topology_operators/local_rewrites/sheet_wire_laminar/membership_programs/shell_split_program.rs",
            include_str!("../../local_rewrites/sheet_wire_laminar/membership_programs/shell_split_program.rs"),
        ),
        source(
            "topology.local-rewrites.sheet-wire-laminar.wire-membership-program",
            "crates/worth-topo/src/topology_operators/local_rewrites/sheet_wire_laminar/membership_programs/wire_membership_program.rs",
            include_str!("../../local_rewrites/sheet_wire_laminar/membership_programs/wire_membership_program.rs"),
        ),
        source(
            "topology.validation.reference-integrity.mod",
            "crates/worth-topo/src/validation/reference_integrity/mod.rs",
            include_str!("../../../validation/reference_integrity/mod.rs"),
        ),
        source(
            "topology.validation.reference-integrity.loop-wiring",
            "crates/worth-topo/src/validation/reference_integrity/loop_wiring.rs",
            include_str!("../../../validation/reference_integrity/loop_wiring.rs"),
        ),
        source(
            "topology.validation.reference-integrity.naming",
            "crates/worth-topo/src/validation/reference_integrity/naming.rs",
            include_str!("../../../validation/reference_integrity/naming.rs"),
        ),
        source(
            "topology.validation.reference-integrity.ownership",
            "crates/worth-topo/src/validation/reference_integrity/ownership.rs",
            include_str!("../../../validation/reference_integrity/ownership.rs"),
        ),
        source(
            "topology.validation.reference-integrity.radial-rings",
            "crates/worth-topo/src/validation/reference_integrity/radial_rings.rs",
            include_str!("../../../validation/reference_integrity/radial_rings.rs"),
        ),
        source(
            "topology.validation.reference-integrity.shared",
            "crates/worth-topo/src/validation/reference_integrity/shared.rs",
            include_str!("../../../validation/reference_integrity/shared.rs"),
        ),
        source(
            "topology.validation.reference-integrity.shared-queries",
            "crates/worth-topo/src/validation/reference_integrity/shared_queries.rs",
            include_str!("../../../validation/reference_integrity/shared_queries.rs"),
        ),
        source(
            "topology.validation.reference-integrity.shell-closure",
            "crates/worth-topo/src/validation/reference_integrity/shell_closure.rs",
            include_str!("../../../validation/reference_integrity/shell_closure.rs"),
        ),
        source(
            "topology.validation.reference-integrity.vertex-disks",
            "crates/worth-topo/src/validation/reference_integrity/vertex_disks.rs",
            include_str!("../../../validation/reference_integrity/vertex_disks.rs"),
        ),
        source(
            "topology.validation.reference-integrity.wire-connectivity",
            "crates/worth-topo/src/validation/reference_integrity/wire_connectivity.rs",
            include_str!("../../../validation/reference_integrity/wire_connectivity.rs"),
        ),
        source(
            "topology.runtime-support",
            "crates/worth-topo/src/runtime_support.rs",
            include_str!("../../../runtime_support.rs"),
        ),
    ]
}

const fn source(
    label: &'static str,
    path: &'static str,
    contents: &'static str,
) -> (&'static str, &'static str, &'static str) {
    (label, path, contents)
}
