use super::classification::EdgeSplitValidatorRuntimeLane;

pub(super) const REQUIRED_PHASE_1_VALIDATOR_LANES: &[(
    &str,
    EdgeSplitValidatorRuntimeLane,
    bool,
)] = &[
    (
        "ValidateSplitOperatorQueryProgression",
        EdgeSplitValidatorRuntimeLane::TopologyDeclarationReview,
        true,
    ),
    (
        "ValidateSplitValidatorRuntimeRegistration",
        EdgeSplitValidatorRuntimeLane::QueryGraphInvariantPack,
        true,
    ),
    (
        "ValidateSplitNameSurvival",
        EdgeSplitValidatorRuntimeLane::QueryGraphInvariantPack,
        true,
    ),
    (
        "ValidateSplitPersistentNameUniqueness",
        EdgeSplitValidatorRuntimeLane::QueryGraphInvariantPack,
        true,
    ),
    (
        "ValidateSplitSelectorResolutionDeterminism",
        EdgeSplitValidatorRuntimeLane::QueryGraphInvariantPack,
        true,
    ),
    (
        "RejectDanglingSplitNameReference",
        EdgeSplitValidatorRuntimeLane::QueryGraphInvariantPack,
        true,
    ),
    (
        "RejectSplitNameFromGeometryOrDisplayString",
        EdgeSplitValidatorRuntimeLane::QueryGraphInvariantPack,
        true,
    ),
    (
        "RejectAmbiguousSplitIdentityEvolution",
        EdgeSplitValidatorRuntimeLane::QueryGraphInvariantPack,
        true,
    ),
    (
        "ValidateEdgeSplitDecisionLogCoverage",
        EdgeSplitValidatorRuntimeLane::QueryGraphInvariantPack,
        true,
    ),
    (
        "ValidateEdgeSplitFailureLocalizationConsistency",
        EdgeSplitValidatorRuntimeLane::QueryGraphInvariantPack,
        true,
    ),
    (
        "ValidateEdgeSplitDiagnosticsDoNotMutateOperationalDigest",
        EdgeSplitValidatorRuntimeLane::QueryGraphInvariantPack,
        true,
    ),
    (
        "ValidateSplitLedgerReceiptChain",
        EdgeSplitValidatorRuntimeLane::QueryGraphInvariantPack,
        true,
    ),
    (
        "RejectSplitLedgerMissingValidationReceipt",
        EdgeSplitValidatorRuntimeLane::QueryGraphInvariantPack,
        true,
    ),
    (
        "RejectSplitLedgerMissingPersistentNamingReceipt",
        EdgeSplitValidatorRuntimeLane::QueryGraphInvariantPack,
        true,
    ),
    (
        "RejectSplitLedgerMissingDecisionLogReceipt",
        EdgeSplitValidatorRuntimeLane::QueryGraphInvariantPack,
        true,
    ),
    (
        "RejectSplitLedgerForeignProductLineage",
        EdgeSplitValidatorRuntimeLane::QueryGraphInvariantPack,
        true,
    ),
    (
        "ValidatePlanarBooleanReplayParity",
        EdgeSplitValidatorRuntimeLane::QueryGraphInvariantPack,
        true,
    ),
    (
        "ValidatePlanarBooleanCheckpointParity",
        EdgeSplitValidatorRuntimeLane::QueryGraphInvariantPack,
        true,
    ),
    (
        "ValidateJournalReplayExactness",
        EdgeSplitValidatorRuntimeLane::QueryGraphInvariantPack,
        true,
    ),
    (
        "RejectSyntheticSplitLedgerConstruction",
        EdgeSplitValidatorRuntimeLane::QueryGraphInvariantPack,
        true,
    ),
    (
        "RejectRawEventVectorSplitConsumption",
        EdgeSplitValidatorRuntimeLane::QueryGraphInvariantPack,
        true,
    ),
    (
        "RejectHandFilledSplitEvidenceRows",
        EdgeSplitValidatorRuntimeLane::QueryGraphInvariantPack,
        true,
    ),
    (
        "RejectCoordinateOnlySplitVertices",
        EdgeSplitValidatorRuntimeLane::QueryGraphInvariantPack,
        true,
    ),
    (
        "FenceLoopReconstructionToSplitLedgerReceipt",
        EdgeSplitValidatorRuntimeLane::QueryGraphInvariantPack,
        true,
    ),
    (
        "ValidateEdgeSplitMetabossCandidateIndexProof",
        EdgeSplitValidatorRuntimeLane::QueryGraphInvariantPack,
        true,
    ),
    (
        "ValidateEdgeSplitMetabossLedgerAndReplayProof",
        EdgeSplitValidatorRuntimeLane::QueryGraphInvariantPack,
        true,
    ),
    (
        "ValidateEdgeSplitSummumBonumCloseout",
        EdgeSplitValidatorRuntimeLane::QueryGraphInvariantPack,
        true,
    ),
    (
        "RejectCrossProductCandidateDiscoveryAsCloseoutProof",
        EdgeSplitValidatorRuntimeLane::QueryGraphInvariantPack,
        true,
    ),
    (
        "RejectSyntheticMetabossCloseoutProofBundle",
        EdgeSplitValidatorRuntimeLane::QueryGraphInvariantPack,
        true,
    ),
];
