use super::classification::{EdgeSplitOperatorClassification, EdgeSplitRequiredQuerySurface};

pub(super) const REQUIRED_PHASE_1_OPERATOR_LANES: &[(
    &str,
    EdgeSplitOperatorClassification,
    EdgeSplitRequiredQuerySurface,
)] = &[
    (
        "RegisterEdgeSplitOperatorDeclarationFamily",
        EdgeSplitOperatorClassification::TopologyDeclarationFamily,
        EdgeSplitRequiredQuerySurface::TopologyDeclarationEntry,
    ),
    (
        "RegisterEdgeSplitGroupedOperatorFamily",
        EdgeSplitOperatorClassification::TopologyGroupedDeclarationFamily,
        EdgeSplitRequiredQuerySurface::TopologyGroupedDeclaration,
    ),
    (
        "RegisterEdgeSplitContributionWorkflow",
        EdgeSplitOperatorClassification::TopologyContributionWorkflow,
        EdgeSplitRequiredQuerySurface::TopologyContributionWorkflow,
    ),
    (
        "RegisterEdgeSplitGraphInvariantPack",
        EdgeSplitOperatorClassification::QueryGraphCompositionProgram,
        EdgeSplitRequiredQuerySurface::QueryInvariantRegistration,
    ),
    (
        "MapSplitLedgerToTopologyOperatorDeclarations",
        EdgeSplitOperatorClassification::QueryGraphCompositionProgram,
        EdgeSplitRequiredQuerySurface::QueryGraphComposition,
    ),
    (
        "ClassifyPreparedVsAuthoritativeSplitOperator",
        EdgeSplitOperatorClassification::PreparedSpatialOnly,
        EdgeSplitRequiredQuerySurface::None,
    ),
    (
        "ValidateSplitOperatorQueryProgression",
        EdgeSplitOperatorClassification::TopologyDeclarationFamily,
        EdgeSplitRequiredQuerySurface::TopologyDeclarationEntry,
    ),
    (
        "ValidateSplitValidatorRuntimeRegistration",
        EdgeSplitOperatorClassification::QueryGraphCompositionProgram,
        EdgeSplitRequiredQuerySurface::QueryInvariantRegistration,
    ),
    (
        "BuildSplitPersistentNamingMap",
        EdgeSplitOperatorClassification::QueryGraphCompositionProgram,
        EdgeSplitRequiredQuerySurface::QueryGraphComposition,
    ),
    (
        "BuildSplitPersistentNamingSeeds",
        EdgeSplitOperatorClassification::QueryGraphCompositionProgram,
        EdgeSplitRequiredQuerySurface::QueryGraphComposition,
    ),
    (
        "AdmitSplitIdentityEvolutionQuery",
        EdgeSplitOperatorClassification::QueryGraphCompositionProgram,
        EdgeSplitRequiredQuerySurface::QueryGraphComposition,
    ),
    (
        "BindSplitPersistentNamesToQueryLineage",
        EdgeSplitOperatorClassification::QueryGraphCompositionProgram,
        EdgeSplitRequiredQuerySurface::QueryGraphComposition,
    ),
    (
        "PropagatePersistentNamesThroughSplit",
        EdgeSplitOperatorClassification::TopologyContributionWorkflow,
        EdgeSplitRequiredQuerySurface::TopologyContributionWorkflow,
    ),
    (
        "RecordSplitEntityParentage",
        EdgeSplitOperatorClassification::TopologyContributionWorkflow,
        EdgeSplitRequiredQuerySurface::TopologyContributionWorkflow,
    ),
    (
        "ForkSplitEntityLineage",
        EdgeSplitOperatorClassification::TopologyContributionWorkflow,
        EdgeSplitRequiredQuerySurface::TopologyContributionWorkflow,
    ),
    (
        "ExtractSplitStableSubshapeSignatures",
        EdgeSplitOperatorClassification::PreparedSpatialOnly,
        EdgeSplitRequiredQuerySurface::None,
    ),
    (
        "ResolveSplitNameConflictsAfterBoolean",
        EdgeSplitOperatorClassification::QueryGraphCompositionProgram,
        EdgeSplitRequiredQuerySurface::QueryInvariantRegistration,
    ),
    (
        "ValidateSplitNameSurvival",
        EdgeSplitOperatorClassification::QueryGraphCompositionProgram,
        EdgeSplitRequiredQuerySurface::QueryInvariantRegistration,
    ),
    (
        "ValidateSplitPersistentNameUniqueness",
        EdgeSplitOperatorClassification::QueryGraphCompositionProgram,
        EdgeSplitRequiredQuerySurface::QueryInvariantRegistration,
    ),
    (
        "ValidateSplitSelectorResolutionDeterminism",
        EdgeSplitOperatorClassification::QueryGraphCompositionProgram,
        EdgeSplitRequiredQuerySurface::QueryInvariantRegistration,
    ),
    (
        "RejectDanglingSplitNameReference",
        EdgeSplitOperatorClassification::QueryGraphCompositionProgram,
        EdgeSplitRequiredQuerySurface::QueryInvariantRegistration,
    ),
    (
        "RejectSplitNameFromGeometryOrDisplayString",
        EdgeSplitOperatorClassification::QueryGraphCompositionProgram,
        EdgeSplitRequiredQuerySurface::QueryInvariantRegistration,
    ),
    (
        "RejectAmbiguousSplitIdentityEvolution",
        EdgeSplitOperatorClassification::QueryGraphCompositionProgram,
        EdgeSplitRequiredQuerySurface::QueryInvariantRegistration,
    ),
    (
        "RecordEdgeSplitDecisionLog",
        EdgeSplitOperatorClassification::QueryGraphCompositionProgram,
        EdgeSplitRequiredQuerySurface::QueryGraphComposition,
    ),
    (
        "LocalizePlanarBooleanFailure",
        EdgeSplitOperatorClassification::QueryGraphCompositionProgram,
        EdgeSplitRequiredQuerySurface::QueryGraphComposition,
    ),
    (
        "BuildStructuredEdgeSplitFailureReport",
        EdgeSplitOperatorClassification::QueryGraphCompositionProgram,
        EdgeSplitRequiredQuerySurface::QueryGraphComposition,
    ),
    (
        "AssemblePlanarBooleanSplitEdgeChainLedger",
        EdgeSplitOperatorClassification::QueryGraphCompositionProgram,
        EdgeSplitRequiredQuerySurface::QueryGraphComposition,
    ),
    (
        "BuildSplitEdgeChain",
        EdgeSplitOperatorClassification::QueryGraphCompositionProgram,
        EdgeSplitRequiredQuerySurface::QueryGraphComposition,
    ),
    (
        "BuildSplitLedgerReceipt",
        EdgeSplitOperatorClassification::QueryGraphCompositionProgram,
        EdgeSplitRequiredQuerySurface::QueryGraphComposition,
    ),
    (
        "CanonicalizeSplitLedgerOrdering",
        EdgeSplitOperatorClassification::QueryGraphCompositionProgram,
        EdgeSplitRequiredQuerySurface::QueryGraphComposition,
    ),
    (
        "ValidateSplitLedgerReceiptChain",
        EdgeSplitOperatorClassification::QueryGraphCompositionProgram,
        EdgeSplitRequiredQuerySurface::QueryGraphComposition,
    ),
    (
        "ReplayPlanarBooleanEdgeSplit",
        EdgeSplitOperatorClassification::QueryGraphCompositionProgram,
        EdgeSplitRequiredQuerySurface::QueryGraphComposition,
    ),
    (
        "CompareEdgeSplitReplayParity",
        EdgeSplitOperatorClassification::QueryGraphCompositionProgram,
        EdgeSplitRequiredQuerySurface::QueryGraphComposition,
    ),
    (
        "CompareEdgeSplitCheckpointParity",
        EdgeSplitOperatorClassification::QueryGraphCompositionProgram,
        EdgeSplitRequiredQuerySurface::QueryGraphComposition,
    ),
    (
        "CanonicalizeReversedEdgeSenseSplit",
        EdgeSplitOperatorClassification::PreparedSpatialOnly,
        EdgeSplitRequiredQuerySurface::None,
    ),
    (
        "RejectSyntheticSplitLedgerConstruction",
        EdgeSplitOperatorClassification::QueryGraphCompositionProgram,
        EdgeSplitRequiredQuerySurface::QueryInvariantRegistration,
    ),
    (
        "RejectRawEventVectorSplitConsumption",
        EdgeSplitOperatorClassification::QueryGraphCompositionProgram,
        EdgeSplitRequiredQuerySurface::QueryInvariantRegistration,
    ),
    (
        "RejectHandFilledSplitEvidenceRows",
        EdgeSplitOperatorClassification::QueryGraphCompositionProgram,
        EdgeSplitRequiredQuerySurface::QueryInvariantRegistration,
    ),
    (
        "RejectCoordinateOnlySplitVertices",
        EdgeSplitOperatorClassification::QueryGraphCompositionProgram,
        EdgeSplitRequiredQuerySurface::QueryInvariantRegistration,
    ),
    (
        "FenceLoopReconstructionToSplitLedgerReceipt",
        EdgeSplitOperatorClassification::QueryGraphCompositionProgram,
        EdgeSplitRequiredQuerySurface::QueryGraphComposition,
    ),
    (
        "CertifyPlanarBooleanEdgeSplittingMetaboss",
        EdgeSplitOperatorClassification::QueryGraphCompositionProgram,
        EdgeSplitRequiredQuerySurface::QueryGraphComposition,
    ),
    (
        "BuildEdgeSplitMetabossWorkloadRecipe",
        EdgeSplitOperatorClassification::QueryGraphCompositionProgram,
        EdgeSplitRequiredQuerySurface::QueryGraphComposition,
    ),
    (
        "EmitEdgeSplitMetabossProofBundle",
        EdgeSplitOperatorClassification::QueryGraphCompositionProgram,
        EdgeSplitRequiredQuerySurface::QueryGraphComposition,
    ),
    (
        "ValidateEdgeSplitSummumBonumCloseout",
        EdgeSplitOperatorClassification::QueryGraphCompositionProgram,
        EdgeSplitRequiredQuerySurface::QueryInvariantRegistration,
    ),
    (
        "RegisterMilestone7_3CloseoutRows",
        EdgeSplitOperatorClassification::QueryGraphCompositionProgram,
        EdgeSplitRequiredQuerySurface::QueryInvariantRegistration,
    ),
    (
        "EmitPlanarBooleanOutcome",
        EdgeSplitOperatorClassification::TopologyDeclarationFamily,
        EdgeSplitRequiredQuerySurface::TopologyDeclarationEntry,
    ),
];
