use super::classification::{
    PlanarBooleanLoopOperatorClassification as Class,
    PlanarBooleanLoopRequiredQuerySurface as Surface,
};

pub(super) const REQUIRED_PHASE_2_OPERATOR_LANES: &[(&str, Class, Surface)] = &[
    (
        "ConsumePlanarBooleanSplitEdgeChainLedger",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "DeclarePlanarBooleanLoopReconstruction",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "AdmitPlanarBooleanLoopReconstruction",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "BindLoopReconstructionToSplitLedgerReceipt",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "RejectSyntheticLoopReconstructionEntry",
        Class::QueryGraphCompositionProgram,
        Surface::QueryInvariantRegistration,
    ),
    (
        "RegisterLoopReconstructionOperatorDeclarationFamily",
        Class::TopologyDeclarationFamily,
        Surface::TopologyDeclarationEntry,
    ),
    (
        "RegisterLoopReconstructionGroupedOperatorFamily",
        Class::TopologyGroupedDeclarationFamily,
        Surface::TopologyGroupedDeclaration,
    ),
    (
        "RegisterLoopReconstructionContributionWorkflow",
        Class::TopologyContributionWorkflow,
        Surface::TopologyContributionWorkflow,
    ),
    (
        "RegisterLoopReconstructionGraphInvariantPack",
        Class::QueryGraphCompositionProgram,
        Surface::QueryInvariantRegistration,
    ),
    (
        "ValidateLoopOperatorQueryProgression",
        Class::TopologyDeclarationFamily,
        Surface::TopologyDeclarationEntry,
    ),
    (
        "ValidateLoopValidatorRuntimeRegistration",
        Class::QueryGraphCompositionProgram,
        Surface::QueryInvariantRegistration,
    ),
    (
        "RecoverBooleanLoopSourceCarriers",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "BindFragmentToSourceLoop",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "BuildLoopFragmentContinuationIndex",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "CanonicalizeLoopContinuationOrder",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "AdmitLoopContinuationPolicy",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "ClassifyLoopContinuationAmbiguity",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "EmitLoopContinuationOutcome",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "SelectCanonicalLoopSeeds",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "AssembleClosedWalkCandidates",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "ClassifyWalkOutcome",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "PromoteClosedWalkToLoopCandidate",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "RejectLoopCandidateBeforeIdentity",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "BuildReconstructedLoop",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "BuildBornLoopFromImprintNeighborhood",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "PartitionLoopIslands",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "SplitSourceLoopIntoReconstructedIslands",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "PreserveLoopRoleFromSource",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "ClassifyLoopRoleOutcome",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "ClassifyLoopContainmentEvidencePosture",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "RecordLoopContainmentEvidence",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "ClassifyDegenerateLoopOutcome",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "RejectCollapsedLoopBeforeLedger",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "RejectTinyCardinalityLoopBeforeLedger",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "RejectUnsupportedSelfTouchingLoopOutcome",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "MintBooleanLoopIdentity",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "PropagatePersistentNamesThroughLoopReconstruction",
        Class::TopologyContributionWorkflow,
        Surface::TopologyContributionWorkflow,
    ),
    (
        "RecordLoopEntityParentage",
        Class::TopologyContributionWorkflow,
        Surface::TopologyContributionWorkflow,
    ),
    (
        "ForkLoopEntityLineage",
        Class::TopologyContributionWorkflow,
        Surface::TopologyContributionWorkflow,
    ),
    (
        "SplitLoop",
        Class::TopologyDeclarationFamily,
        Surface::TopologyDeclarationEntry,
    ),
    (
        "CreateLoop",
        Class::TopologyDeclarationFamily,
        Surface::TopologyDeclarationEntry,
    ),
    (
        "DestroyLoop",
        Class::TopologyDeclarationFamily,
        Surface::TopologyDeclarationEntry,
    ),
    (
        "AttachLoop",
        Class::TopologyDeclarationFamily,
        Surface::TopologyDeclarationEntry,
    ),
    (
        "DetachLoop",
        Class::TopologyDeclarationFamily,
        Surface::TopologyDeclarationEntry,
    ),
    (
        "PromoteInnerLoop",
        Class::TopologyDeclarationFamily,
        Surface::TopologyDeclarationEntry,
    ),
    (
        "DemoteOuterLoop",
        Class::TopologyDeclarationFamily,
        Surface::TopologyDeclarationEntry,
    ),
    (
        "SetLoopContainment",
        Class::TopologyDeclarationFamily,
        Surface::TopologyDeclarationEntry,
    ),
    (
        "RecordLoopReconstructionDecisionLog",
        Class::QueryGraphCompositionProgram,
        Surface::QueryGraphComposition,
    ),
    (
        "LocalizeLoopReconstructionFailure",
        Class::QueryGraphCompositionProgram,
        Surface::QueryGraphComposition,
    ),
    (
        "BuildStructuredLoopReconstructionFailureReport",
        Class::QueryGraphCompositionProgram,
        Surface::QueryGraphComposition,
    ),
    (
        "AssemblePlanarBooleanLoopReconstructionLedger",
        Class::QueryGraphCompositionProgram,
        Surface::QueryGraphComposition,
    ),
    (
        "BuildLoopReconstructionLedgerReceipt",
        Class::QueryGraphCompositionProgram,
        Surface::QueryGraphComposition,
    ),
    (
        "FenceOverlapExtractionToLoopLedgerReceipt",
        Class::QueryGraphCompositionProgram,
        Surface::QueryGraphComposition,
    ),
    (
        "RequireBooleanLoopReconstructionEvidence",
        Class::QueryGraphCompositionProgram,
        Surface::QueryGraphComposition,
    ),
    (
        "RegisterBooleanLoopReconstructionStageRequirement",
        Class::QueryGraphCompositionProgram,
        Surface::QueryInvariantRegistration,
    ),
    (
        "ReplayPlanarBooleanLoopReconstruction",
        Class::QueryGraphCompositionProgram,
        Surface::QueryGraphComposition,
    ),
    (
        "CompareLoopReconstructionReplayParity",
        Class::QueryGraphCompositionProgram,
        Surface::QueryGraphComposition,
    ),
    (
        "CompareLoopReconstructionCheckpointParity",
        Class::QueryGraphCompositionProgram,
        Surface::QueryGraphComposition,
    ),
    (
        "RejectUnindexedLoopFragment",
        Class::QueryGraphCompositionProgram,
        Surface::QueryInvariantRegistration,
    ),
    (
        "RejectSyntheticLoopLedgerConstruction",
        Class::QueryGraphCompositionProgram,
        Surface::QueryInvariantRegistration,
    ),
];
