use super::classification::PlanarBooleanLoopValidatorRuntimeLane as Lane;

pub(super) const REQUIRED_PHASE_2_VALIDATOR_LANES: &[(&str, Lane, bool)] = &[
    (
        "ValidatePlanarBooleanSplitLedgerConsumption",
        Lane::QueryGraphInvariantPack,
        true,
    ),
    (
        "ValidateLoopReceiptEnvelopeConsistency",
        Lane::QueryGraphInvariantPack,
        true,
    ),
    (
        "ValidateLoopLedgerReceiptChain",
        Lane::QueryGraphInvariantPack,
        true,
    ),
    (
        "RejectLoopLedgerMissingDecisionLogReceipt",
        Lane::QueryGraphInvariantPack,
        true,
    ),
    (
        "RejectLoopLedgerMissingPersistentNamingReceipt",
        Lane::QueryGraphInvariantPack,
        true,
    ),
    (
        "RejectLoopLedgerForeignProductLineage",
        Lane::QueryGraphInvariantPack,
        true,
    ),
    (
        "ValidateLoopCarrierCoverage",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateFragmentMembershipCoverage",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateLoopContinuationIndexCoverage",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateNoDanglingLoopFragmentReferences",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateCanonicalContinuationOrderingStable",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateNoNPlusOneLoopContinuationDiscovery",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateLoopContinuationOutcomeConsistency",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateLoopAmbiguityClassificationConsistency",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateCanonicalLoopSeedSelection",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateClosedWalkFragmentConsumption",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateWalkClosure",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateWalkOutcomeLocalization",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateClosedWalkPromotionBoundary",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateDeniedLoopCandidateLocalization",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateClosedIsNotAutomaticallyAdmittedLoop",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateBornLoopAttributionCoverage",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateLoopIslandPartitionConsistency",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateSourceLoopSplitAttributionConsistency",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateInnerOuterLoopFlagsConsistent",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateLoopRoleOutcomeConsistency",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateLoopContainmentEvidencePostureConsistency",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateDegenerateLoopPolicyConsistency",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateLoopHasMinimumCardinality",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateNoUnexpectedZeroAreaLoops",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateLoopIdentityCanonicality",
        Lane::QueryGraphInvariantPack,
        true,
    ),
    (
        "ValidatePersistentNameUniqueness",
        Lane::QueryGraphInvariantPack,
        true,
    ),
    (
        "ValidateNameSurvivalThroughLoopReconstruction",
        Lane::QueryGraphInvariantPack,
        true,
    ),
    (
        "ValidateNoDanglingNameReferences",
        Lane::QueryGraphInvariantPack,
        true,
    ),
    (
        "ValidateLoopDecisionLogCoverage",
        Lane::QueryGraphInvariantPack,
        true,
    ),
    (
        "ValidateLoopFailureLocalizationConsistency",
        Lane::QueryGraphInvariantPack,
        true,
    ),
    (
        "ValidateCanonicalOrderingStable",
        Lane::QueryGraphInvariantPack,
        true,
    ),
    (
        "ValidateHashStabilityAcrossRuns",
        Lane::QueryGraphInvariantPack,
        true,
    ),
    (
        "ValidateTieBreakerCoverage",
        Lane::QueryGraphInvariantPack,
        true,
    ),
    (
        "ValidatePlanarBooleanLoopReplayParity",
        Lane::QueryGraphInvariantPack,
        true,
    ),
    (
        "ValidatePlanarBooleanLoopCheckpointParity",
        Lane::QueryGraphInvariantPack,
        true,
    ),
    (
        "ValidateLoopOperatorQueryProgression",
        Lane::TopologyDeclarationReview,
        true,
    ),
    (
        "ValidateLoopValidatorRuntimeRegistration",
        Lane::QueryGraphInvariantPack,
        true,
    ),
    (
        "ValidateLoopGraphInvariantPackRegistration",
        Lane::QueryGraphInvariantPack,
        true,
    ),
    (
        "ValidatePreparedSpatialLoopProductsCannotMutateTopologyTruth",
        Lane::QueryGraphInvariantPack,
        true,
    ),
    (
        "ValidateTopologyDeclarationFamilyCanonicalEntries",
        Lane::TopologyDeclarationReview,
        true,
    ),
];
