//! Superseded entry points historically owned by the legacy root crate.

use super::super::{
    LegacyAccessPathBypass as Bypass, LegacySurfaceInventoryRow, LegacySurfaceStage as Stage,
};
use super::row::superseded_legacy_root as row;

pub(super) const ROWS: &[LegacySurfaceInventoryRow] = &[
    row("ForgeStore", Stage::ExecutionFacade, Bypass::Execution),
    row(
        "ForgeStoreBuilder",
        Stage::DeclarationFacade,
        Bypass::Declaration,
    ),
    row(
        "ForgeStore::plan_aspect_layout_read",
        Stage::SelectionFacade,
        Bypass::Selection,
    ),
    row(
        "ForgeStore::admit_structural_block_reuse",
        Stage::AdmissionFacade,
        Bypass::Admission,
    ),
    row(
        "ForgeStore::freeze_chunk_model",
        Stage::ExecutionFacade,
        Bypass::Execution,
    ),
    row(
        "ForgeStore::admit_milestone_7_independent_layout_reference",
        Stage::AdmissionFacade,
        Bypass::Admission,
    ),
    row(
        "ForgeStore::admit_milestone_9_physical_chunk_reference",
        Stage::AdmissionFacade,
        Bypass::Admission,
    ),
    row(
        "ForgeStore::prepare_milestone_6_layout_support",
        Stage::ReadinessFacade,
        Bypass::Readiness,
    ),
    row(
        "ForgeStore::prepare_milestone_6_layout_support_with_policy",
        Stage::ReadinessFacade,
        Bypass::Readiness,
    ),
    row(
        "ForgeStore::materialize_milestone_6_layout_support",
        Stage::ExecutionFacade,
        Bypass::Execution,
    ),
    row(
        "ForgeStore::fetch_milestone_6_layout_support",
        Stage::ExecutionFacade,
        Bypass::Execution,
    ),
    row(
        "ForgeStore::execute_aspect_layout_read",
        Stage::ExecutionFacade,
        Bypass::Execution,
    ),
    row(
        "ForgeStore::read_aspect_layout_control_truth",
        Stage::ExecutionFacade,
        Bypass::Execution,
    ),
    row(
        "ForgeStore::execute_aspect_layout_read_in_lane",
        Stage::ExecutionFacade,
        Bypass::Execution,
    ),
    row(
        "ForgeStore::execute_aspect_layout_read_in_lane_with_policy",
        Stage::ExecutionFacade,
        Bypass::Execution,
    ),
    row(
        "ForgeStore::execute_dedup_backed_read",
        Stage::ExecutionFacade,
        Bypass::Execution,
    ),
    row(
        "ForgeStore::execute_dedup_backed_read_in_lane",
        Stage::ExecutionFacade,
        Bypass::Execution,
    ),
    row(
        "ForgeStore::execute_dedup_backed_read_in_lane_with_policy",
        Stage::ExecutionFacade,
        Bypass::Execution,
    ),
    row(
        "ForgeStore::structural_block_lookup",
        Stage::ExecutionFacade,
        Bypass::Execution,
    ),
    row(
        "ForgeStore::export_milestone_6_chunk_model",
        Stage::ExecutionFacade,
        Bypass::Execution,
    ),
    row(
        "ForgeStore::export_milestone_6_chunk_model_in_lane",
        Stage::ExecutionFacade,
        Bypass::Execution,
    ),
    row(
        "ForgeStore::export_milestone_6_chunk_model_in_lane_with_policy",
        Stage::ExecutionFacade,
        Bypass::Execution,
    ),
    row(
        "ForgeStore::rebuild_milestone_6_derived_artifacts_from_materializations",
        Stage::ExecutionFacade,
        Bypass::Execution,
    ),
    row(
        "ForgeStore::rebuild_milestone_6_derived_artifacts_from_authority",
        Stage::ExecutionFacade,
        Bypass::Execution,
    ),
];
