pub use crate::aspects::{
    admit_authoritative_record_aspect_state, aspects, classify_aspect_contract_evolution,
    validate_aspect_value, AbsenceLaw, AspectContract, AspectContractFrontDoor,
    AspectContractIdentityStep, AspectContractRevision, AspectContractRevisionStep,
    AspectContractShapeStep, AspectEquivalenceBasis, AspectEvolutionClassified,
    AspectEvolutionClassifiedContractArtifact, AspectEvolutionClassifiedContracts,
    AspectEvolutionKind, AspectEvolutionPolicy, AspectEvolutionVerdict,
    AspectFrontDoorConstructionDenial, AspectIdentity, AspectKey, AspectMask, AspectMaskContract,
    AspectMaskContractFrontDoor, AspectPatchFrontDoor, AspectShape, AspectValidationFrontDoor,
    AspectValidationInputStep, AspectVocabularyFrontDoor, AspectsFrontDoor,
    AuthoritativePatchApplicationDenial, AuthoritativePatchConstructionDenial,
    AuthoritativeRecordAspectPatch, AuthoritativeRecordAspectState,
    AuthoritativeRecordAspectStateAdmitted, AuthoritativeRecordAspectStateArtifact,
    AuthoritativeStateAdmissionDenial, AuthoritativeStateFrontDoor, CanonicalAspectStateMap,
    CanonicalFieldPath, ContractValidatedAspectArtifact, ContractValidatedAspectValue,
    ContractValidatedAspectValueView, ContractValidationDenial, ContractValidationInput,
    DiagnosticMask, DiagnosticMaskFrontDoor, FieldDeclaration, FieldKey, FieldLevelAspectPatch,
    FieldLevelPatchBuilder, FieldRequirement, MaskAdmissibilityDenial, MutationMask,
    MutationMaskFrontDoor, OpaqueAspectType, ProjectionMask, ProjectionMaskFrontDoor,
    ReferenceAspectType, StructAspectShape, StructAspectValue, StructAspectValueConstructionDenial,
    StructFieldBuilder, StructFieldsFrontDoor, StructValueBuilder, WholeAspectPatchBuilder,
};
pub use crate::boundary::{
    certify_milestone1_production_test_readiness, declared_foundational_boundary,
    milestone1_compatibility_debt_inventory, milestone1_migration_readiness_report,
    milestone1_proof_seed_inventory, milestone1_public_api_inventory,
    require_milestone1_production_test_readiness, FoundationalBoundaryArtifact,
    FoundationalBoundaryDeclaration, FoundationalBoundaryDeclared, Milestone1CompatibilityDebt,
    Milestone1MigrationReadinessReport, Milestone1ProductionReadinessAuthority,
    Milestone1ProductionReadinessCertified, Milestone1ProductionReadinessScope,
    Milestone1ProductionTestReady, Milestone1ProductionTestReadyArtifact, Milestone1ProofSeed,
    Milestone1PublicApiSurface,
};
pub use crate::boundary_artifacts::{
    admit_authoritative_current_boundary_surface, admit_current_basis_boundary_artifact,
    admit_current_basis_boundary_bundle, admit_planned_work_boundary_artifact,
    admit_same_family_boundary_artifact, boundary_artifact_category_definitions,
    boundary_artifact_category_of, boundary_artifact_surface_definition,
    boundary_receipt_category_of, boundary_receipt_definition, boundary_report_category_of,
    boundary_report_definition, boundary_role_definitions, boundary_summary_category_of,
    boundary_summary_definition, bridge_current_basis_boundary_artifact_trust_boundary,
    bridge_current_basis_boundary_bundle_trust_boundary,
    certify_foundational_boundary_artifact_milestone4_production_test_readiness,
    claim_derived_projection_boundary_surface, claim_planned_work_boundary_surface,
    claim_receipt_evidence_boundary_surface, claim_support_only_boundary_surface,
    derive_same_family_boundary_identity, evaluate_boundary_role_claim_legality,
    evaluate_boundary_surface_disposition_legality,
    evaluate_planned_work_reserved_authority_transition_legality,
    evaluate_same_family_reserved_authority_transition_legality,
    foundational_boundary_artifact_milestone4_readiness_report,
    foundational_boundary_authority_admission, foundational_boundary_canonical_basis_entries,
    foundational_boundary_current_basis_authority, foundational_boundary_current_basis_proof_lane,
    foundational_boundary_current_basis_readmission_authority,
    materialize_authoritative_boundary_surface, materialize_descriptive_boundary_surface,
    plan_artifact_boundary_bundle, plan_authoritative_boundary_materialization,
    plan_descriptive_boundary_materialization,
    prepare_materialized_boundary_artifact_for_canonical_basis,
    prepare_materialized_boundary_bundle_for_canonical_basis,
    prepare_same_family_boundary_artifact_for_canonical_basis,
    readmit_current_basis_boundary_artifact_after_boundary,
    readmit_current_basis_boundary_bundle_after_boundary,
    require_foundational_boundary_artifact_milestone4_production_test_readiness, ArtifactCategory,
    AuthoritativeCurrentRole, BoundaryBridgedCurrentBasisBoundaryArtifact,
    BoundaryBridgedCurrentBasisBoundaryBundle, CurrentBasisBoundaryArtifact,
    CurrentBasisBoundaryArtifactPhase, CurrentBasisBoundaryBundle, DerivedProjectionRole,
    FoundationalAuthoritativeBoundaryClaim, FoundationalBoundaryArtifactCategory,
    FoundationalBoundaryArtifactCertifiedSurface,
    FoundationalBoundaryArtifactCertifiedSurfaceEvidence,
    FoundationalBoundaryArtifactCompileFailBoundary, FoundationalBoundaryArtifactForgeProofApi,
    FoundationalBoundaryArtifactForgeProofForbiddenSurface,
    FoundationalBoundaryArtifactForgeProofSurface, FoundationalBoundaryArtifactMilestone4PhaseGate,
    FoundationalBoundaryArtifactPhaseGateEvidence,
    FoundationalBoundaryArtifactProductionReadinessAuthority,
    FoundationalBoundaryArtifactProductionReadinessCertified,
    FoundationalBoundaryArtifactProductionReadinessReport,
    FoundationalBoundaryArtifactProductionReadinessScope,
    FoundationalBoundaryArtifactProductionTestReady,
    FoundationalBoundaryArtifactProductionTestReadyArtifact,
    FoundationalBoundaryArtifactResidualDebt, FoundationalBoundaryArtifactRole,
    FoundationalBoundaryArtifactRuntimeAssumption,
    FoundationalBoundaryArtifactRuntimeNonAssumption, FoundationalBoundaryArtifactSurface,
    FoundationalBoundaryArtifactSyntheticRuntimePressure, FoundationalBoundaryAttachmentPoint,
    FoundationalBoundaryAuthorityAdmission, FoundationalBoundaryAuthorityAdmissionBasis,
    FoundationalBoundaryAuthorityAdmitted, FoundationalBoundaryAvailability,
    FoundationalBoundaryBundleMaterializationCost, FoundationalBoundaryBundleMaterializationDenial,
    FoundationalBoundaryBundlePlanningDenial, FoundationalBoundaryCategoryConstructionDenial,
    FoundationalBoundaryCategoryDefinition, FoundationalBoundaryCategoryMarker,
    FoundationalBoundaryCategorySurface, FoundationalBoundaryCurrentBasisAuthority,
    FoundationalBoundaryCurrentBasisCertified, FoundationalBoundaryCurrentBasisProofLane,
    FoundationalBoundaryCurrentBasisReadmissionAuthority, FoundationalBoundaryDecisionCause,
    FoundationalBoundaryDecisionSubject, FoundationalBoundaryDeliveryClass,
    FoundationalBoundaryMaterializationAttachment, FoundationalBoundaryMaterializationBundle,
    FoundationalBoundaryMaterializationBundlePlan, FoundationalBoundaryMaterializationCost,
    FoundationalBoundaryMaterializationDecisionRow, FoundationalBoundaryMaterializationDenial,
    FoundationalBoundaryMaterializationInput, FoundationalBoundaryMaterializationPlan,
    FoundationalBoundaryMaterializationSeam, FoundationalBoundaryMaterializationSource,
    FoundationalBoundaryPlanningDenial, FoundationalBoundaryReceiptSurface,
    FoundationalBoundaryReportSurface, FoundationalBoundaryRoleClaim,
    FoundationalBoundaryRoleClaimDenial, FoundationalBoundaryRoleDefinition,
    FoundationalBoundaryRoleMarker, FoundationalBoundarySummarySurface,
    FoundationalBoundarySurfaceDisposition, FoundationalBoundarySurfaceDispositionDenial,
    FoundationalBoundarySurfaceDispositionLegality, FoundationalDerivedProjectionBoundaryClaim,
    FoundationalMaterializedBoundaryArtifact, FoundationalPlannedWorkBoundaryArtifact,
    FoundationalPlannedWorkBoundaryArtifactDenial, FoundationalPlannedWorkBoundaryClaim,
    FoundationalReceiptEvidenceBoundaryClaim, FoundationalReservedAuthorityTransitionDenial,
    FoundationalReservedAuthorityTransitionKind, FoundationalSameFamilyBoundaryArtifact,
    FoundationalSameFamilyBoundaryArtifactDenial, FoundationalSameFamilyBoundaryFamily,
    FoundationalSameFamilyBoundaryFamilyDenial, FoundationalSameFamilyBoundaryIdentity,
    FoundationalSupportOnlyBoundaryClaim, PlannedWorkRole, ReceiptCategory, ReceiptEvidenceRole,
    ReportCategory, SummaryCategory, SupportOnlyRole,
};
pub use crate::canonicalization::{
    admit_canonical_bundle_digest_derivation, admit_canonical_export_digest_derivation,
    admit_canonical_sequence_digest_derivation, aspect_contract_digest_preparation_basis,
    aspect_mask_digest_preparation_basis, aspect_patch_digest_preparation_basis,
    aspect_state_digest_preparation_basis, bridge_canonical_export_trust_boundary,
    canonical_milestone2_production_readiness_report, canonicalization,
    certify_canonical_milestone2_production_readiness, compare_canonical_basis,
    compare_canonical_exports, derive_canonical_digest,
    diagnostic_mask_locator_canonical_basis_entries, identity_canonical_basis_entries,
    locator_canonical_basis_entries, mutation_mask_locator_canonical_basis_entries,
    prepare_aspect_contract_for_canonical_basis, prepare_aspect_contract_for_digest,
    prepare_aspect_mask_for_canonical_basis, prepare_aspect_mask_for_digest,
    prepare_aspect_patch_for_canonical_basis, prepare_aspect_patch_for_digest,
    prepare_aspect_state_for_canonical_basis, prepare_aspect_state_for_digest,
    prepare_canonical_basis_bundle, prepare_canonical_basis_sequence, prepare_canonical_comparison,
    prepare_canonical_export_bundle, prepare_identity_for_canonical_basis,
    prepare_locator_for_canonical_basis, projection_mask_locator_canonical_basis_entries,
    readmit_canonical_export_after_boundary, require_canonical_production_test_readiness,
    BoundaryBridgedCanonicalExportArtifact, CanonicalBasisBundle, CanonicalBasisConstructionDenial,
    CanonicalBasisDomain, CanonicalBasisEntry, CanonicalBasisEntryId, CanonicalBasisEntryKind,
    CanonicalBasisFrontDoor, CanonicalBasisLocus, CanonicalBasisReadinessProofs,
    CanonicalBasisReady, CanonicalBasisReadyArtifact, CanonicalBasisSequence, CanonicalBasisValue,
    CanonicalBasisVersionStep, CanonicalBundleReadinessProofs, CanonicalBundleReady,
    CanonicalBundleReadyArtifact, CanonicalCertifiedSurface, CanonicalCertifiedSurfaceEvidence,
    CanonicalComparisonBasisStep, CanonicalComparisonFrontDoor, CanonicalComparisonInput,
    CanonicalComparisonOutcome, CanonicalComparisonReadinessProofs, CanonicalComparisonReady,
    CanonicalComparisonReadyArtifact, CanonicalComparisonRightStep, CanonicalCompileFailBoundary,
    CanonicalCostCounterEvidence, CanonicalDerivedDigest, CanonicalDigestAlgorithmId,
    CanonicalDigestAlgorithmMetadata, CanonicalDigestAlgorithmSlot, CanonicalDigestAspectShapeKind,
    CanonicalDigestBasisBundle, CanonicalDigestBasisSequence, CanonicalDigestDebt,
    CanonicalDigestDerivationDenial, CanonicalDigestDerivationInput,
    CanonicalDigestDerivationReadinessProofs, CanonicalDigestDerivationReady,
    CanonicalDigestDerivationReadyArtifact, CanonicalDigestFrontDoor, CanonicalDigestInputDomain,
    CanonicalDigestInputEvidence, CanonicalDigestInputId, CanonicalDigestInputShape,
    CanonicalDigestInputShapeBound, CanonicalDigestMaskMode, CanonicalDigestMetadata,
    CanonicalDigestOutputShape, CanonicalDigestPreparationEntry, CanonicalDigestValue,
    CanonicalDomainBundleDigestAlgorithmSlot, CanonicalDomainBundleDigestInput,
    CanonicalDomainCoherence, CanonicalEquivalenceBasis, CanonicalEquivalenceBasisDeclared,
    CanonicalEquivalentBasis, CanonicalExportBasisBundle, CanonicalExportBasisSequence,
    CanonicalExportBasisStep, CanonicalExportBundle, CanonicalExportBundleDigestAlgorithmSlot,
    CanonicalExportBundleDigestInput, CanonicalExportComparisonOutcome, CanonicalExportDebt,
    CanonicalExportFrontDoor, CanonicalExportHarnessSeed, CanonicalExportManifest,
    CanonicalExportManifestBound, CanonicalExportManifestMismatch,
    CanonicalExportManifestMismatchKind, CanonicalExportManifestRow, CanonicalExportNameStep,
    CanonicalExportReadinessProofs, CanonicalExportReadmissionAuthority, CanonicalExportReady,
    CanonicalExportReadyArtifact, CanonicalExportShapeStep, CanonicalFixtureManifestEvidence,
    CanonicalFloatWidth, CanonicalGoldenArtifactEvidence, CanonicalHarnessExpansionPoint,
    CanonicalIdentityInput, CanonicalIntegerWidth, CanonicalLocatorInput,
    CanonicalMilestone2PhaseGate, CanonicalMismatchBasis, CanonicalMismatchKind,
    CanonicalMismatchLociBound, CanonicalPhaseGateEvidence, CanonicalProducerShape,
    CanonicalProductionReadinessAuthority, CanonicalProductionReadinessCertified,
    CanonicalProductionReadinessReport, CanonicalProductionReadinessScope,
    CanonicalProductionTestReady, CanonicalProductionTestReadyArtifact, CanonicalPropertySeed,
    CanonicalPropertySeedEvidence, CanonicalReadinessFrontDoor, CanonicalResidualDebt,
    CanonicalRuleVersionBound, CanonicalRuntimeAssumption, CanonicalRuntimeNonAssumption,
    CanonicalSingleSequenceDigestAlgorithmSlot, CanonicalSingleSequenceDigestInput,
    CanonicalSyntheticRuntimePressure, CanonicalizationCost, CanonicalizationCostObserved,
    CanonicalizationFrontDoor, CanonicalizationRuleVersion, DigestPreparationMaskMode,
    DigestPreparationReady, DigestPreparationReadyAspectContract,
    DigestPreparationReadyAspectContractArtifact, DigestPreparationReadyAspectMask,
    DigestPreparationReadyAspectMaskArtifact, DigestPreparationReadyAspectPatch,
    DigestPreparationReadyAspectPatchArtifact, DigestPreparationReadyAspectState,
    DigestPreparationReadyAspectStateArtifact, Milestone2DigestReadinessNote,
};
pub use crate::compatibility::{
    compatibility, lower_json_aspect_value, lower_json_record_aspect_state, CompatibilityFrontDoor,
    JsonCompatibilityAspectInput, JsonCompatibilityFrontDoor, JsonCompatibilityLoweringDeferred,
    JsonCompatibilityLoweringDenial, JsonCompatibilityLoweringFailure,
    JsonCompatibilityLoweringOutcome, JsonCompatibilityLoweringStale,
    JsonCompatibilityRebindRequired,
};
pub use crate::diagnostics::{
    bridge_certified_diagnostic_bundle_trust_boundary, certify_current_basis_diagnostic_bundle,
    certify_diagnostic_bundle_with_source_basis,
    certify_foundational_diagnostic_milestone6_production_test_readiness,
    compare_diagnostic_explanation_bundles, compare_diagnostic_support_reports,
    diagnostic_artifact_kind_definitions, diagnostic_comparison_bundle_definition,
    diagnostic_explanation_bundle_definition, diagnostic_failure_bundle_definition,
    diagnostic_report_definition, diagnostic_summary_definition,
    diagnostic_support_report_definition, evaluate_diagnostic_materialization_legality,
    foundational_comparison_bundle_artifact_kind,
    foundational_diagnostic_boundary_artifact_subject,
    foundational_diagnostic_branch_candidate_subject,
    foundational_diagnostic_branch_discard_subject,
    foundational_diagnostic_canonical_basis_entries,
    foundational_diagnostic_certified_attachment_authority,
    foundational_diagnostic_certified_readmission_authority, foundational_diagnostic_code,
    foundational_diagnostic_commit_receipt_subject,
    foundational_diagnostic_committed_authority_subject,
    foundational_diagnostic_locator_boundary_artifact, foundational_diagnostic_locator_mismatch,
    foundational_diagnostic_locator_source, foundational_diagnostic_locator_transition,
    foundational_diagnostic_merge_verdict_subject,
    foundational_diagnostic_milestone6_readiness_report, foundational_diagnostic_scope,
    foundational_explanation_bundle_artifact_kind, foundational_failure_bundle_artifact_kind,
    foundational_report_artifact_kind, foundational_summary_artifact_kind,
    foundational_support_report_artifact_kind, materialize_diagnostic_explanation_bundle,
    materialize_diagnostic_support_report, plan_diagnostic_explanation_bundle,
    plan_diagnostic_support_report, prepare_diagnostic_explanation_bundle_for_canonical_basis,
    prepare_diagnostic_support_report_for_canonical_basis,
    readmit_certified_diagnostic_bundle_after_boundary,
    require_foundational_diagnostic_milestone6_production_test_readiness,
    sort_foundational_diagnostic_rows, BoundaryBridgedCertifiedDiagnosticBundle,
    FoundationalCertifiedDiagnosticBundle, FoundationalCertifiedDiagnosticPayload,
    FoundationalCertifiedDiagnosticProvenanceHook, FoundationalCertifiedDiagnosticSource,
    FoundationalCertifiedDiagnosticSourceKind, FoundationalComparisonBundleArtifactKind,
    FoundationalDiagnosticAbsenceCause, FoundationalDiagnosticAdoptionShapedFollowthrough,
    FoundationalDiagnosticArtifactKind, FoundationalDiagnosticArtifactKindDefinition,
    FoundationalDiagnosticArtifactKindMarker, FoundationalDiagnosticAssemblyDebt,
    FoundationalDiagnosticAssemblyDebtClass, FoundationalDiagnosticAvailability,
    FoundationalDiagnosticBreachClass, FoundationalDiagnosticCanonicalGoldenArtifact,
    FoundationalDiagnosticCanonicalGoldenArtifactEvidence, FoundationalDiagnosticCertified,
    FoundationalDiagnosticCertifiedAttachmentAuthority,
    FoundationalDiagnosticCertifiedAttachmentDenial, FoundationalDiagnosticCertifiedCoverageClass,
    FoundationalDiagnosticCertifiedCoverageDenial, FoundationalDiagnosticCertifiedPhase,
    FoundationalDiagnosticCertifiedReadmissionAuthority, FoundationalDiagnosticCertifiedSurface,
    FoundationalDiagnosticCertifiedSurfaceEvidence, FoundationalDiagnosticCodeId,
    FoundationalDiagnosticComparisonBundle, FoundationalDiagnosticComparisonDenial,
    FoundationalDiagnosticComparisonRow, FoundationalDiagnosticCompileFailBoundary,
    FoundationalDiagnosticCompileFailEvidence, FoundationalDiagnosticCounterSnapshot,
    FoundationalDiagnosticCoverageFamilyStatus, FoundationalDiagnosticCoverageMatrix,
    FoundationalDiagnosticDecisionRow, FoundationalDiagnosticDeliveryClass,
    FoundationalDiagnosticDenialClass, FoundationalDiagnosticEvidencePosture,
    FoundationalDiagnosticExplanationBundle, FoundationalDiagnosticExplanationInput,
    FoundationalDiagnosticFailureRow, FoundationalDiagnosticForgeProofApi,
    FoundationalDiagnosticForgeProofApiEvidence, FoundationalDiagnosticForgeProofForbiddenSurface,
    FoundationalDiagnosticForgeProofSurface, FoundationalDiagnosticGapClass,
    FoundationalDiagnosticGapClosurePosture, FoundationalDiagnosticGapTarget,
    FoundationalDiagnosticHarnessExpansionEvidence, FoundationalDiagnosticHarnessExpansionPoint,
    FoundationalDiagnosticLocalityClaim, FoundationalDiagnosticLocator,
    FoundationalDiagnosticMaterializationDenial,
    FoundationalDiagnosticMaterializationLegalityDenial, FoundationalDiagnosticMaterializationPlan,
    FoundationalDiagnosticMilestone6PhaseGate, FoundationalDiagnosticNamedGap,
    FoundationalDiagnosticOutcomeKind, FoundationalDiagnosticPartiality,
    FoundationalDiagnosticPhaseGateEvidence, FoundationalDiagnosticPrimitiveConstructionDenial,
    FoundationalDiagnosticProductionReadinessAuthority,
    FoundationalDiagnosticProductionReadinessCertified,
    FoundationalDiagnosticProductionReadinessReport,
    FoundationalDiagnosticProductionReadinessScope, FoundationalDiagnosticProductionTestReady,
    FoundationalDiagnosticProductionTestReadyArtifact, FoundationalDiagnosticPropertySeed,
    FoundationalDiagnosticPropertySeedEvidence, FoundationalDiagnosticProvenanceReadyRow,
    FoundationalDiagnosticResidualDebt, FoundationalDiagnosticRow, FoundationalDiagnosticRowFamily,
    FoundationalDiagnosticRuntimeAdoptionFailurePressure, FoundationalDiagnosticRuntimeAssumption,
    FoundationalDiagnosticRuntimeNonAssumption, FoundationalDiagnosticScopeId,
    FoundationalDiagnosticSemanticLabelSet, FoundationalDiagnosticSeverity,
    FoundationalDiagnosticSubject, FoundationalDiagnosticSupportClaimStrength,
    FoundationalDiagnosticSupportEvidencePosture, FoundationalDiagnosticSupportInput,
    FoundationalDiagnosticSupportReport, FoundationalDiagnosticSupportRow,
    FoundationalDiagnosticSurfaceAvailability, FoundationalDiagnosticSyntheticPressureEvidence,
    FoundationalDiagnosticSyntheticRuntimePressure, FoundationalDiagnosticWidenedFalloutPosture,
    FoundationalExplanationBundleArtifactKind, FoundationalFailureBundleArtifactKind,
    FoundationalReportArtifactKind, FoundationalSummaryArtifactKind,
    FoundationalSupportReportArtifactKind,
};
pub use crate::identities::{
    BoundaryArtifactId, BoundaryEpoch, BoundaryHandle, CanonicalDigestId, EquivalenceBasisId,
};
pub use crate::locators::{
    AspectContractLocator, AspectFieldLocator, AspectLocator, AspectMaskLocator,
    AspectValueLocator, BoundaryArtifactField, BoundaryArtifactLocator, BoundaryMismatchLocator,
    BoundarySourceLocator, FoundationalBranchCandidateLocator, FoundationalCommitParentageLocator,
    FoundationalCommittedDeltaLocator, FoundationalMergeConflictLocator,
    FoundationalTransitionLocator, LocatorAuthority,
};
pub use crate::profiles::{
    admit_requested_foundational_profile, attach_boundary_profiled_artifact,
    attach_proof_bearing_profiled_artifact, attach_support_profiled_artifact,
    boundary_artifact_surface_inventory,
    bridge_evidence_backed_proof_bearing_artifact_trust_boundary,
    bridge_production_certified_proof_bearing_artifact_trust_boundary,
    certify_evidence_backed_proof_bearing_artifact,
    certify_foundational_profile_milestone3_production_test_readiness,
    certify_production_certified_proof_bearing_artifact,
    classify_foundational_profile_compatibility, compare_foundational_profile_identities,
    compare_foundational_profiles, derive_foundational_profile_identity,
    foundational_profile_applicability, foundational_profile_canonical_basis_entries,
    foundational_profile_certification_authority, foundational_profile_certification_proof_lane,
    foundational_profile_certification_readmission_authority,
    foundational_profile_milestone3_readiness_report, foundational_profile_progression_authority,
    materialize_admitted_foundational_profile, plan_foundational_profile_materialization,
    plan_foundational_profile_materialization_with_elision,
    plan_selected_foundational_profile_materialization,
    prepare_admitted_foundational_profile_for_canonical_basis, profiles,
    proof_bearing_artifact_surface_inventory,
    readmit_evidence_backed_proof_bearing_artifact_after_boundary,
    readmit_production_certified_proof_bearing_artifact_after_boundary,
    request_foundational_profile_set,
    require_foundational_profile_milestone3_production_test_readiness,
    support_artifact_surface_inventory, AdmissionReadinessProfile,
    AdmittedFoundationalProfileArtifact, AdmittedFoundationalProfilePhase,
    AdmittedFoundationalProfileSet, BoundaryArtifactTarget,
    BoundaryBridgedEvidenceBackedCertifiedProofBearingArtifact,
    BoundaryBridgedProductionCertifiedProofBearingArtifact, BoundaryProfiledArtifact,
    CertificationPostureProfile, CompatibilityPostureProfile, DiagnosticRichnessProfile,
    EvidenceBackedCertifiedProofBearingArtifact, FoundationalDescriptiveElisionProfile,
    FoundationalDescriptiveSurface, FoundationalMaterializationCost,
    FoundationalMaterializationPlanningDenial, FoundationalProfileApplicability,
    FoundationalProfileAttachmentDenial, FoundationalProfileAttachmentFrontDoor,
    FoundationalProfileAttachmentOutcome, FoundationalProfileAttachmentTargetKind,
    FoundationalProfileAttachmentTargetMarker, FoundationalProfileCertificationAuthority,
    FoundationalProfileCertificationDenial, FoundationalProfileCertificationFrontDoor,
    FoundationalProfileCertificationOutcome, FoundationalProfileCertificationProofLane,
    FoundationalProfileCertificationReadmissionAuthority, FoundationalProfileCertifiedSurface,
    FoundationalProfileCertifiedSurfaceEvidence, FoundationalProfileCompatibilityClass,
    FoundationalProfileCompileFailBoundary, FoundationalProfileCompositionDenial,
    FoundationalProfileDecisionKind, FoundationalProfileDifferenceReport,
    FoundationalProfileFamily, FoundationalProfileForgeProofApi,
    FoundationalProfileForgeProofForbiddenSurface, FoundationalProfileForgeProofSurface,
    FoundationalProfileFrontDoorConstructionDenial, FoundationalProfileFrontDoorFamily,
    FoundationalProfileIdentity, FoundationalProfileIdentityDenial,
    FoundationalProfileMaterializationFrontDoor, FoundationalProfileMaterializationPlan,
    FoundationalProfileMilestone3PhaseGate, FoundationalProfileNarrowingKind,
    FoundationalProfileNarrowingRecord, FoundationalProfilePhaseGateEvidence,
    FoundationalProfileProductionReadinessAuthority,
    FoundationalProfileProductionReadinessCertified, FoundationalProfileProductionReadinessReport,
    FoundationalProfileProductionReadinessScope, FoundationalProfileProductionTestReady,
    FoundationalProfileProductionTestReadyArtifact, FoundationalProfileProgressionAuthority,
    FoundationalProfileProgressionDeferred, FoundationalProfileProgressionDenial,
    FoundationalProfileProgressionFailure, FoundationalProfileProgressionFrontDoor,
    FoundationalProfileProgressionOutcome, FoundationalProfileProgressionRebindRequired,
    FoundationalProfileProgressionStale, FoundationalProfileResidualDebt,
    FoundationalProfileRuntimeAssumption, FoundationalProfileRuntimeNonAssumption,
    FoundationalProfileSet, FoundationalProfileSetFrontDoor, FoundationalProfileSetInput,
    FoundationalProfileSyntheticRuntimePressure, FoundationalProfiledArtifact,
    FoundationalSurfaceAbsenceCause, FoundationalSurfaceAvailabilityDecision,
    FoundationalTargetSurfaceInventory, MaterializedBoundaryArtifactStep,
    MaterializedFoundationalProfileArtifact, MaterializedFoundationalProfilePhase,
    MaterializedFoundationalProfileSet, MaterializedProofBearingArtifactStep,
    MaterializedSupportArtifactStep, ProductionCertifiedProofBearingArtifact, ProfilesFrontDoor,
    ProofBearingArtifactTarget, ProofBearingProfiledArtifact, RequestedFoundationalProfileArtifact,
    RequestedFoundationalProfilePhase, RequestedFoundationalProfileSet, RetentionDeliveryProfile,
    SupportArtifactTarget, SupportPostureProfile, SupportProfiledArtifact,
};
pub use crate::transitions::{
    admit_current_basis_commit_receipt, admit_current_basis_committed_authority,
    attach_boundary_profiled_branch_candidate, attach_boundary_profiled_staged_branch,
    attach_proof_bearing_profiled_commit_receipt,
    attach_proof_bearing_profiled_committed_authority, attach_support_profiled_merge_verdict,
    bridge_current_basis_commit_receipt_trust_boundary,
    bridge_current_basis_committed_authority_trust_boundary,
    certify_foundational_transition_milestone5_production_test_readiness,
    foundational_branch_candidate, foundational_branch_local_state_definitions,
    foundational_commit_receipt_issuance, foundational_committed_authority_admission,
    foundational_merge, foundational_transition_canonical_basis_entries,
    foundational_transition_current_basis_authority,
    foundational_transition_current_basis_readmission_authority,
    foundational_transition_milestone5_readiness_report,
    prepare_branch_candidate_for_canonical_basis, prepare_commit_receipt_for_canonical_basis,
    prepare_committed_authority_for_canonical_basis, prepare_merge_verdict_for_canonical_basis,
    prepare_staged_branch_for_canonical_basis, readmit_current_basis_commit_receipt_after_boundary,
    readmit_current_basis_committed_authority_after_boundary,
    require_foundational_transition_milestone5_production_test_readiness,
    BoundaryBridgedCurrentBasisCommitReceiptArtifact,
    BoundaryBridgedCurrentBasisCommittedAuthorityArtifact, CurrentBasisCommitReceiptArtifact,
    CurrentBasisCommittedAuthorityArtifact, CurrentBasisTransitionPhase,
    FoundationalAuthorityTransitionClass, FoundationalAuthorityTransitionDenial,
    FoundationalAuthorityTransitionOutcomeKind, FoundationalBranchBasisDrift,
    FoundationalBranchBasisDriftKind, FoundationalBranchCandidateArtifact,
    FoundationalBranchCandidateBuilder, FoundationalBranchCandidateId,
    FoundationalBranchCloseoutCause, FoundationalBranchComparisonBasis,
    FoundationalBranchDiscardReceipt, FoundationalBranchForkBasis,
    FoundationalBranchForkObservationBasis, FoundationalBranchId,
    FoundationalBranchIdConstructionDenial, FoundationalBranchLocalConstructionDenial,
    FoundationalBranchLocalStateDefinition, FoundationalBranchLocalStateKind,
    FoundationalBranchObservationBasis, FoundationalCommitDeltaSummary, FoundationalCommitId,
    FoundationalCommitParentBasis, FoundationalCommitParentage, FoundationalCommitReceiptArtifact,
    FoundationalCommitReceiptIdentity, FoundationalCommitReceiptIssuance,
    FoundationalCommitReceiptIssuanceBasis, FoundationalCommitReceiptIssuanceDenial,
    FoundationalCommitReceiptPhase, FoundationalCommittedAuthorityAdmission,
    FoundationalCommittedAuthorityAdmissionBasis, FoundationalCommittedAuthorityArtifact,
    FoundationalCommittedAuthorityConstructionDenial, FoundationalCommittedAuthorityInput,
    FoundationalCommittedAuthorityPhase, FoundationalCommittedDeltaLocus,
    FoundationalMergeAdmissionDeferred, FoundationalMergeAdmissionDenial,
    FoundationalMergeAdmissionFailure, FoundationalMergeAdmissionOutcome,
    FoundationalMergeAdmissionRebindRequired, FoundationalMergeAncestryBasis,
    FoundationalMergeBaseSelectionBasis, FoundationalMergeBasis, FoundationalMergeBuilder,
    FoundationalMergeCandidate, FoundationalMergeConflictLocus,
    FoundationalMergeConstructionDenial, FoundationalMergeIntent,
    FoundationalMergeStructuralSummary, FoundationalMergeVerdict, FoundationalMergeVerdictKind,
    FoundationalNoOpCause, FoundationalNonAuthoritativeResidueReport,
    FoundationalStagedBranchArtifact, FoundationalStrategyBasis, FoundationalTransitionBasisFamily,
    FoundationalTransitionBasisIdentity, FoundationalTransitionBasisVersion,
    FoundationalTransitionBundle, FoundationalTransitionBundleBuilder,
    FoundationalTransitionBundleMaterializationCost, FoundationalTransitionCertifiedSurface,
    FoundationalTransitionCertifiedSurfaceEvidence, FoundationalTransitionCompileFailBoundary,
    FoundationalTransitionCompileFailEvidence, FoundationalTransitionCorrespondenceBasis,
    FoundationalTransitionCurrentBasisAuthority,
    FoundationalTransitionCurrentBasisReadmissionAuthority, FoundationalTransitionForgeProofApi,
    FoundationalTransitionForgeProofApiEvidence, FoundationalTransitionForgeProofForbiddenSurface,
    FoundationalTransitionForgeProofSurface, FoundationalTransitionIssuanceCause,
    FoundationalTransitionMilestone5PhaseGate, FoundationalTransitionPhaseGateEvidence,
    FoundationalTransitionProductionReadinessAuthority,
    FoundationalTransitionProductionReadinessCertified,
    FoundationalTransitionProductionReadinessReport,
    FoundationalTransitionProductionReadinessScope, FoundationalTransitionProductionTestReady,
    FoundationalTransitionProductionTestReadyArtifact, FoundationalTransitionProvenanceRow,
    FoundationalTransitionRemapBasis, FoundationalTransitionResidualDebt,
    FoundationalTransitionRuntimeAssumption, FoundationalTransitionRuntimeNonAssumption,
    FoundationalTransitionStrategyContractBasis, FoundationalTransitionStrategyDescriptorDigest,
    FoundationalTransitionStrategyFamily, FoundationalTransitionStrategyId,
    FoundationalTransitionStrategyIdentity, FoundationalTransitionStrategyOwnershipClass,
    FoundationalTransitionStrategySemanticName, FoundationalTransitionStrategyVersion,
    FoundationalTransitionSyntheticPressureEvidence,
    FoundationalTransitionSyntheticRuntimePressure,
};
pub use crate::values::{
    AspectValue, CanonicalBigInt, CanonicalDate, CanonicalDecimal, CanonicalF32, CanonicalF64,
    CanonicalRational, CanonicalString, CanonicalTime, CanonicalTimestamp, CanonicalTimestampTz,
    ContentRefId, EntityId, Generation, InternedString, LocalSlot, PartitionId, ScalarAspectType,
    Symbol,
};

/// A named implementation home that Milestone 1 expects to remain distinct.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ResponsibilityArea {
    name: &'static str,
    owns: &'static str,
    does_not_own: &'static str,
}

impl ResponsibilityArea {
    pub const fn new(name: &'static str, owns: &'static str, does_not_own: &'static str) -> Self {
        Self {
            name,
            owns,
            does_not_own,
        }
    }

    pub const fn name(&self) -> &'static str {
        self.name
    }

    pub const fn owns(&self) -> &'static str {
        self.owns
    }

    pub const fn does_not_own(&self) -> &'static str {
        self.does_not_own
    }
}

/// Responsibility topology exposed for Phase 1 certification.
pub fn foundational_responsibilities() -> [ResponsibilityArea; 10] {
    [
        crate::values::responsibility(),
        crate::aspects::responsibility(),
        crate::identities::responsibility(),
        crate::locators::responsibility(),
        crate::compatibility::responsibility(),
        crate::canonicalization::responsibility(),
        crate::profiles::responsibility(),
        crate::boundary_artifacts::responsibility(),
        crate::transitions::responsibility(),
        crate::diagnostics::responsibility(),
    ]
}
