use super::*;

#[test]
fn runtime_floor_certification_bundle_assembles_phase_six_foundation_artifacts() {
    let bundle = certify_intent_admission_runtime_floor();

    assert_eq!(
        bundle.family_inventory().rows(),
        forge_query_intent_admission_family_inventory().rows()
    );
    assert_eq!(
        bundle.coverage_inventory().rows(),
        forge_query_intent_admission_coverage_inventory().rows()
    );
    assert_eq!(
        bundle.support_matrix().rows(),
        forge_query_intent_admission_support_matrix().rows()
    );
    assert_eq!(
        bundle.public_boundary_audit().compile_fail_targets(),
        forge_query_intent_admission_compile_fail_targets()
    );
    assert_eq!(
        bundle.public_boundary_audit().golden_transcripts(),
        forge_query_intent_admission_golden_transcripts()
    );
    assert_eq!(
        bundle.output_digest("intent_golden_transcript_digest"),
        Some(bundle.public_boundary_audit().golden_transcript_digest())
    );
    assert_eq!(
        bundle.output_digest("compile_fail_boundary_digest"),
        Some(
            bundle
                .public_boundary_audit()
                .compile_fail_boundary_digest()
        )
    );
    assert_eq!(
        bundle.output_digest("decision_phase_progression_digest"),
        Some(
            bundle
                .proof_shape_audit()
                .decision_phase_progression_digest()
        )
    );
    assert_eq!(
        bundle.output_digest("decision_proof_shape_digest"),
        Some(bundle.proof_shape_audit().decision_proof_shape_digest())
    );
    assert_eq!(
        bundle.output_digest("intent_topology_audit_digest"),
        Some(bundle.topology_audit().topology_digest())
    );
    assert_eq!(
        bundle.output_digest("representative_family_coverage_digest"),
        Some(
            bundle
                .representative_family_report()
                .representative_family_coverage_digest()
        )
    );
    assert_eq!(
        bundle.output_digest("query_digest"),
        bundle
            .representative_output_report()
            .digest_for("query_digest")
    );
    assert_eq!(
        bundle.output_digest("failure_digest"),
        bundle
            .representative_output_report()
            .digest_for("failure_digest")
    );
    assert_eq!(
        bundle.output_digest("crate_doc_example_digest"),
        Some(bundle.doc_example_report().crate_doc_example_digest())
    );
    assert_eq!(
        bundle.output_digest("decision_oracle_digest"),
        Some(bundle.oracle_report().oracle_digest())
    );
    assert_eq!(
        bundle.output_digest("legacy_delegation_parity_digest"),
        Some(
            bundle
                .legacy_parity_report()
                .legacy_delegation_parity_digest()
        )
    );
    assert_eq!(
        bundle.output_digest("decision_support_traceability_digest"),
        Some(
            bundle
                .support_traceability_report()
                .decision_support_traceability_digest()
        )
    );
    assert_eq!(
        bundle.output_digest("counter_snapshot"),
        Some(bundle.counter_snapshot().digest())
    );
    assert_eq!(
        bundle.output_digest("seeded_sequence_digest"),
        Some(bundle.seeded_report().seeded_sequence_digest())
    );
    assert_eq!(
        bundle.output_digest("seed_replay_digest"),
        Some(bundle.seeded_report().seed_replay_digest())
    );
    assert_eq!(
        bundle.output_digest("seed_generator_class_digest"),
        Some(bundle.seeded_report().seed_generator_class_digest())
    );
    assert!(!bundle.certification_bundle_digest().is_empty());
}
