use super::catalog_row::row;
use super::classification::{
    CompiledProductReuseAuthorityKind as AuthorityKind,
    CompiledProductReuseDisposition as Disposition, CompiledProductReuseOwner as Owner,
    CompiledProductReuseReplacementPhase as Phase,
    CompiledProductReuseSemanticCategory as Category,
    CompiledProductReuseSemanticDistinction as Distinction,
};
use super::row::{
    CompiledProductReuseInventoryRow, CompiledProductReuseSurfaceIdentity as Surface,
};
use super::source_scan::CompiledProductReuseScanPattern as Pattern;

pub(super) fn spatial_rows() -> Vec<CompiledProductReuseInventoryRow> {
    vec![
        row(
            Surface::ReuseEvidenceLookupIndexProduct,
            "crates/worth-spatial/src/workload_platform/evidence_lookup_index_product/construction.rs",
            "reuse_evidence_lookup_index_product",
            "EvidenceLookupIndexProduct",
            Category::OrdinaryReuse,
            Distinction::CompiledProductIdentity,
            AuthorityKind::LocalDigestReuseKey,
            Disposition::Migrate,
            Owner::WorthSpatial,
            Phase::PhaseNineReuseDecision,
            "evidence lookup index reuse is still decided inside the product constructor",
            "typed reuse decision product replaces product-local reuse admission",
            true,
            false,
            None,
            Pattern::ReuseIdentifier,
            None,
        ),
        row(
            Surface::IndexProductDigest,
            "crates/worth-spatial/src/workload_platform/evidence_lookup_index_product/identity.rs",
            "index_product_digest",
            "EvidenceLookupIndexProduct::index_product_digest",
            Category::PseudoReuse,
            Distinction::CompiledProductIdentity,
            AuthorityKind::RowCountShortcut,
            Disposition::Migrate,
            Owner::WorthSpatial,
            Phase::PhaseTwoSharedVocabulary,
            "evidence lookup identity still bakes basis-row and reuse counters into a crate-local digest recipe",
            "shared compiled-product identity vocabulary replaces index-local digest authorship",
            true,
            false,
            None,
            Pattern::RowCountShortcutLine,
            None,
        ),
        row(
            Surface::ReplayParityReportFromRetainedProjectionMatch,
            "crates/worth-spatial/src/workload_platform/retained_replay_workload/replay_parity.rs",
            "ReplayParityReport::from_retained_projection_match",
            "ReplayParityReport",
            Category::ParityShortcut,
            Distinction::Equivalence,
            AuthorityKind::RetainedParityHelper,
            Disposition::Migrate,
            Owner::WorthSpatial,
            Phase::PhaseTwelveSpatialConsumerCutover,
            "retained replay parity still claims semantic agreement from a local parity helper",
            "retained replay consumers must consume selected equivalence and reuse products",
            true,
            false,
            None,
            Pattern::ParityIdentifier,
            None,
        ),
        row(
            Surface::ReplayParityReportRowCount,
            "crates/worth-spatial/src/workload_platform/retained_replay_workload/replay_parity.rs",
            "ReplayParityReport::row_count",
            "ReplayParityReport row count",
            Category::ParityShortcut,
            Distinction::Compatibility,
            AuthorityKind::RowCountShortcut,
            Disposition::Delete,
            Owner::WorthSpatial,
            Phase::PhaseFifteenFirewallDeletion,
            "row-count parity is residue folklore, not reuse authority",
            "source firewall rejects row-count reuse shortcuts once the new lane lands",
            false,
            true,
            Some(1),
            Pattern::RowCountShortcutLine,
            None,
        ),
        row(
            Surface::RetainedArtifactCaptureReceiptFromArtifacts,
            "crates/worth-spatial/src/workload_platform/retained_replay_workload/retained_workload.rs",
            "RetainedArtifactCaptureReceipt::from_artifacts",
            "RetainedArtifactCaptureReceipt",
            Category::RetainedProductCarryForward,
            Distinction::CompiledProductIdentity,
            AuthorityKind::RetainedCarryForwardHelper,
            Disposition::Migrate,
            Owner::WorthSpatial,
            Phase::PhaseFourSpatialFamilyCatalog,
            "retained capture identity is still minted by a retained-workload helper",
            "spatial compiled-product families own retained-product identity declarations",
            true,
            false,
            None,
            Pattern::RetainedFolkloreIdentifier,
            None,
        ),
        row(
            Surface::ReplayWorkloadWithCapturedRetainedWorkload,
            "crates/worth-spatial/src/workload_platform/retained_replay_workload/replay_workload.rs",
            "ReplayWorkload::with_captured_retained_workload",
            "ReplayWorkload retained-artifact carry-forward",
            Category::RetainedProductCarryForward,
            Distinction::Compatibility,
            AuthorityKind::RetainedCarryForwardHelper,
            Disposition::Migrate,
            Owner::WorthSpatial,
            Phase::PhaseTwelveSpatialConsumerCutover,
            "replay workload still carries retained artifacts forward through workload-local helpers",
            "retained replay cutover consumes declared compiled-product products instead of local carry-forward",
            true,
            false,
            None,
            Pattern::RetainedFolkloreIdentifier,
            None,
        ),
        row(
            Surface::ReplayCaptureReceipt,
            "crates/worth-spatial/src/workload_platform/retained_replay_workload/replay_workload.rs",
            "replay_capture_receipt",
            "RetainedArtifactCaptureReceipt fallback",
            Category::RetainedProductCarryForward,
            Distinction::AuthorityTruth,
            AuthorityKind::RetainedCarryForwardHelper,
            Disposition::Migrate,
            Owner::WorthSpatial,
            Phase::PhaseNineReuseDecision,
            "retained replay still self-heals missing capture receipts locally",
            "reuse denial product replaces helper-local capture receipt fallback",
            true,
            false,
            None,
            Pattern::RetainedFolkloreIdentifier,
            None,
        ),
        row(
            Surface::CurrentEvidenceLookupPublicCloseout,
            "crates/worth-spatial/src/workload_platform/evidence_lookup_public_closeout/current_source.rs",
            "current_evidence_lookup_public_closeout",
            "EvidenceLookupPublicCloseout",
            Category::PseudoReuse,
            Distinction::AuthorityTruth,
            AuthorityKind::CloseoutConsumerReusePressure,
            Disposition::Migrate,
            Owner::WorthSpatial,
            Phase::PhaseThirteenPublicReadModelCutover,
            "public closeout still binds evidence lookup proof before the compiled-product lane exists",
            "public closeout must consume reuse decisions rather than local product proof",
            false,
            false,
            Some(1),
            Pattern::CloseoutConsumerIdentifier,
            None,
        ),
        row(
            Surface::CurrentEvidenceLookupPublicCloseoutAssemblyInput,
            "crates/worth-spatial/src/workload_platform/evidence_lookup_public_closeout/current_source.rs",
            "current_evidence_lookup_public_closeout_assembly_input",
            "EvidenceLookupPublicCloseoutAssemblyInput",
            Category::PseudoReuse,
            Distinction::AuthorityTruth,
            AuthorityKind::CloseoutConsumerReusePressure,
            Disposition::CertificationOnly,
            Owner::WorthSpatial,
            Phase::NotReplacedCertificationOnly,
            "assembly input remains closeout-only aggregation support and must not survive as ordinary compiled-product authority",
            "retain only as certification/public-closeout support while the cutover removes direct assembly from reuse proof",
            false,
            true,
            Some(1),
            Pattern::CloseoutConsumerIdentifier,
            None,
        ),
    ]
}
