use super::catalog_row::row;
use super::classification::{
    CompiledProductReuseAuthorityKind as AuthorityKind,
    CompiledProductReuseDisposition as Disposition, CompiledProductReuseOwner as Owner,
    CompiledProductReuseReplacementPhase as Phase,
    CompiledProductReuseSemanticCategory as Category,
    CompiledProductReuseSemanticDistinction as Distinction,
};
use super::row::{
    CompiledProductReuseInventoryRow, CompiledProductReuseSurfaceIdentity as Surface,
};
use super::source_scan::CompiledProductReuseScanPattern as Pattern;

pub(super) fn kernel_rows() -> Vec<CompiledProductReuseInventoryRow> {
    vec![
        row(
            Surface::LookupConsumedWorkloadCompositionAdmit,
            "crates/worth-kernel/src/workload_composition/worth_workload/lookup_consumed_workload/mod.rs",
            "LookupConsumedWorkloadComposition::admit",
            "LookupConsumedWorkloadComposition",
            Category::PseudoReuse,
            Distinction::AuthorityTruth,
            AuthorityKind::CloseoutConsumerReusePressure,
            Disposition::Migrate,
            Owner::WorthKernel,
            Phase::PhaseFiveKernelDependencyMatrix,
            "workload composition still carries lookup-consumed workload authority through a local handoff consumer",
            "kernel cutover matrix must bind lookup-consumed consumers to the compiled-product lane",
            true,
            false,
            None,
            Pattern::LookupConsumerIdentifier,
            None,
        ),
        row(
            Surface::WorthWorkloadAdmitLookupConsumedWorkload,
            "crates/worth-kernel/src/workload_composition/worth_workload/lookup_consumed_workload/mod.rs",
            "WorthWorkload::admit_lookup_consumed_workload",
            "WorthWorkload ordinary consumer admission",
            Category::PseudoReuse,
            Distinction::AuthorityTruth,
            AuthorityKind::CloseoutConsumerReusePressure,
            Disposition::Migrate,
            Owner::WorthKernel,
            Phase::PhaseFiveKernelDependencyMatrix,
            "workload entry still treats lookup-consumed reuse pressure as local composition detail",
            "kernel dependency matrix names this ordinary consumer cluster explicitly",
            true,
            false,
            None,
            Pattern::LookupConsumerIdentifier,
            None,
        ),
        row(
            Surface::WorthWorkloadAdmitLookupConsumedBatchExecutionCluster,
            "crates/worth-kernel/src/workload_composition/worth_workload/ordinary_consumer_sweep/lookup_consumed_cluster.rs",
            "WorthWorkload::admit_lookup_consumed_batch_execution_cluster",
            "WorthWorkload lookup-consumed batch execution admission",
            Category::RetainedProductCarryForward,
            Distinction::Compatibility,
            AuthorityKind::RetainedCarryForwardHelper,
            Disposition::Migrate,
            Owner::WorthKernel,
            Phase::PhaseFiveKernelDependencyMatrix,
            "lookup-consumed batch execution still hides lookup admission and retained replay carry-forward inside one local cluster surface",
            "kernel dependency matrix must split this batch execution consumer into exact lookup and retained-replay clusters",
            true,
            false,
            None,
            Pattern::LookupConsumerIdentifier,
            None,
        ),
        row(
            Surface::CurrentWorthWorkloadOrdinaryConsumerCutover,
            "crates/worth-kernel/src/workload_composition/worth_workload/ordinary_consumer_sweep/current_cutover.rs",
            "current_worth_workload_ordinary_consumer_cutover",
            "WorthWorkloadOrdinaryConsumerCutover",
            Category::PseudoReuse,
            Distinction::AuthorityTruth,
            AuthorityKind::CloseoutConsumerReusePressure,
            Disposition::Migrate,
            Owner::WorthKernel,
            Phase::PhaseFiveKernelDependencyMatrix,
            "ordinary consumer cutover still tracks current reuse pressure through conflict-era closeout products",
            "kernel dependency matrix names the compiled-product consumer clusters explicitly",
            false,
            false,
            Some(1),
            Pattern::CloseoutConsumerIdentifier,
            None,
        ),
        row(
            Surface::ReplayUndoPublicCloseoutReadModelProjection,
            "crates/worth-kernel/src/replay_undo_consumer_cutover/public_closeout/inventory_classification.rs",
            "ReplayUndoPublicCloseoutInventoryRow::from_inventory",
            "ReplayUndo public closeout read-model projection",
            Category::PseudoReuse,
            Distinction::AuthorityTruth,
            AuthorityKind::PublicReadModelReuseDescriptor,
            Disposition::Migrate,
            Owner::WorthKernel,
            Phase::PhaseFiveKernelDependencyMatrix,
            "replay/undo public closeout still lowers one public read-model projection without a kernel cutover cluster declaration",
            "kernel dependency matrix must name the replay/undo public read-model consumer and bind it to one Query projection lane",
            false,
            false,
            Some(1),
            Pattern::PublicReadModelReuseLine,
            None,
        ),
        row(
            Surface::CurrentWorthTouchedGraphConflictPublicCloseout,
            "crates/worth-kernel/src/workload_composition/public_closeout/public_closeout.rs",
            "current_worth_touched_graph_conflict_public_closeout",
            "WorthTouchedGraphConflictPublicCloseout",
            Category::PseudoReuse,
            Distinction::AuthorityTruth,
            AuthorityKind::CloseoutConsumerReusePressure,
            Disposition::Migrate,
            Owner::WorthKernel,
            Phase::PhaseThirteenPublicReadModelCutover,
            "kernel public closeout still closes conflict-era proof before compiled-product reuse proof exists",
            "public closeout must route through the new compiled-product lane",
            false,
            false,
            Some(1),
            Pattern::CloseoutConsumerIdentifier,
            None,
        ),
        row(
            Surface::KernelConflictPublicCloseoutBoundaryTraceability,
            "crates/worth-kernel/src/workload_composition/public_closeout/public_closeout.rs",
            "current_worth_touched_graph_conflict_public_closeout",
            "WorthTouchedGraphConflictPublicCloseout Query boundary traceability",
            Category::PseudoReuse,
            Distinction::AuthorityTruth,
            AuthorityKind::PublicReadModelReuseDescriptor,
            Disposition::Migrate,
            Owner::WorthKernel,
            Phase::PhaseFiveKernelDependencyMatrix,
            "kernel public closeout still carries Query boundary traceability as local boundary prose on the same closeout surface",
            "kernel dependency matrix must name this Query-backed boundary consumer explicitly",
            false,
            false,
            Some(1),
            Pattern::CloseoutConsumerIdentifier,
            None,
        ),
        row(
            Surface::CurrentWorthTouchedGraphConflictMilestoneFourteenSeed,
            "crates/worth-kernel/src/workload_composition/public_closeout/public_closeout.rs",
            "current_worth_touched_graph_conflict_milestone_fourteen_seed",
            "WorthTouchedGraphConflictMilestoneFourteenSeed",
            Category::PseudoReuse,
            Distinction::AuthorityTruth,
            AuthorityKind::CloseoutConsumerReusePressure,
            Disposition::Cap,
            Owner::WorthKernel,
            Phase::PhaseThirteenPublicReadModelCutover,
            "current seed assembly still reflects conflict closeout rather than compiled-product closeout",
            "Milestone 14 closeout seed replaces this conflict-era staging surface",
            false,
            false,
            Some(1),
            Pattern::CloseoutConsumerIdentifier,
            None,
        ),
    ]
}
