use super::catalog_row::row;
use super::classification::{
    CompiledProductReuseAuthorityKind as AuthorityKind,
    CompiledProductReuseDisposition as Disposition, CompiledProductReuseOwner as Owner,
    CompiledProductReuseReplacementPhase as Phase,
    CompiledProductReuseSemanticCategory as Category,
    CompiledProductReuseSemanticDistinction as Distinction,
};
use super::row::{
    CompiledProductReuseInventoryRow, CompiledProductReuseSurfaceIdentity as Surface,
};
use super::source_scan::CompiledProductReuseScanPattern as Pattern;

pub(super) fn topo_rows() -> Vec<CompiledProductReuseInventoryRow> {
    vec![
        row(
            Surface::BuildDerivedEquivalenceContract,
            "crates/worth-topo/src/derived_topology/compiled_product_consumer_cutover/topology_derived_cluster/admitted_contract.rs",
            "build_derived_equivalence_contract",
            "DerivedEquivalenceContractReport",
            Category::LocalEquivalenceHelper,
            Distinction::Equivalence,
            AuthorityKind::LocalEquivalenceDigestComparison,
            Disposition::Migrate,
            Owner::WorthTopo,
            Phase::PhaseEightSelectedEquivalenceFamily,
            "topology read diagnostics still author family-local equivalence payloads",
            "selected equivalence family owns topology-equivalence lowering",
            true,
            false,
            None,
            Pattern::EquivalenceIdentifier,
            None,
        ),
        row(
            Surface::BuildDerivedEquivalenceContractReport,
            "crates/worth-topo/src/derived_topology/compiled_product_consumer_cutover/topology_derived_cluster/admitted_contract.rs",
            "build_derived_equivalence_contract_report",
            "DerivedEquivalenceContractReport",
            Category::LocalEquivalenceHelper,
            Distinction::CompiledProductIdentity,
            AuthorityKind::LocalEquivalenceDigestComparison,
            Disposition::Migrate,
            Owner::WorthTopo,
            Phase::PhaseTwoSharedVocabulary,
            "topology report constructor still defines compiled-product identity locally",
            "shared compiled-product identity vocabulary replaces projection-local identity assembly",
            true,
            false,
            None,
            Pattern::EquivalenceIdentifier,
            None,
        ),
        row(
            Surface::CompareDerivedEquivalenceContracts,
            "crates/worth-topo/src/derived_topology/compiled_product_consumer_cutover/topology_derived_cluster/reuse_decision_contract.rs",
            "compare_derived_equivalence_contracts",
            "DerivedParityComparisonReport::equivalent_derived_meaning",
            Category::LocalEquivalenceHelper,
            Distinction::Equivalence,
            AuthorityKind::RenderedShapeEquality,
            Disposition::Migrate,
            Owner::WorthTopo,
            Phase::PhaseEightSelectedEquivalenceFamily,
            "topology parity still claims equivalence from local digest-matching and rendered-shape coincidence",
            "selected equivalence family lowers the comparison basis once",
            true,
            false,
            None,
            Pattern::EquivalenceIdentifier,
            Some(Pattern::RenderedShapeEqualityLine),
        ),
        row(
            Surface::DerivedInvalidationPlannedDispositionFromUpdatePosture,
            "crates/worth-topo/src/derived_topology/invalidation_plan/selection/row/selected.rs",
            "DerivedInvalidationPlannedDisposition::from_update_posture",
            "DerivedTopologyUpdatePosture::BoundedRebuildRequired",
            Category::RebuildSuppression,
            Distinction::Compatibility,
            AuthorityKind::BoundedRebuildPosture,
            Disposition::Migrate,
            Owner::WorthTopo,
            Phase::PhaseThreeTopologyFamilyCatalog,
            "topology invalidation still suppresses ordinary incremental reuse through a local bounded-rebuild mapping",
            "topology family catalog and shared compiled-product lane must own rebuild-vs-incremental authority together",
            true,
            false,
            None,
            Pattern::RebuildSuppressionLine,
            None,
        ),
        row(
            Surface::HistoricalPathReuseDescriptorRetainedReuse,
            "crates/worth-topo/src/projection/runtime_boundary/read_execution/basis_context.rs",
            "HistoricalEvaluationRequest::retained_snapshot(... HistoricalPathReuseDescriptor::retained_reuse())",
            "historical read basis reuse descriptor",
            Category::PseudoReuse,
            Distinction::Compatibility,
            AuthorityKind::PublicReadModelReuseDescriptor,
            Disposition::Migrate,
            Owner::ForgeQuery,
            Phase::PhaseThirteenPublicReadModelCutover,
            "public historical read-model path still declares retained reuse outside the compiled-product lane",
            "query-backed public/read-model consumer cutover consumes typed reuse products",
            false,
            false,
            Some(1),
            Pattern::PublicReadModelReuseLine,
            None,
        ),
        row(
            Surface::HistoricalCapabilityDescriptorRetainedReuse,
            "crates/worth-topo/src/projection/runtime_boundary/read_execution/basis_context.rs",
            "HistoricalCapabilityDescriptor::retained_snapshot(... HistoricalPathReuseDescriptor::retained_reuse())",
            "historical read capability reuse descriptor",
            Category::PseudoReuse,
            Distinction::Compatibility,
            AuthorityKind::PublicReadModelReuseDescriptor,
            Disposition::QueryGap,
            Owner::ForgeQuery,
            Phase::BlockedOnQueryCapability,
            "public historical read-model capability still declares retained reuse before Query owns a compiled-product-aware historical capability lane",
            "replace once Forge Query lowers historical retained reuse through a declared boundary-envelope capability surface",
            false,
            false,
            Some(1),
            Pattern::PublicReadModelReuseLine,
            None,
        ),
    ]
}
