#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ComplexityStatus {
    Verified,
    Debt,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ComplexityContract {
    pub id: &'static str,
    pub function_path: &'static str,
    pub declared_time_complexity: &'static str,
    pub budget_summary: &'static str,
    pub status: ComplexityStatus,
    pub proof_tests: &'static [&'static str],
}

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct RuntimeComplexityCounters {
    pub full_state_clones: usize,
    pub partitions_cloned: usize,
    pub entity_slots_cloned: usize,
    pub relation_slots_cloned: usize,
    pub partitions_touched_by_commit: usize,
    pub entity_slots_touched_by_commit: usize,
    pub relation_slots_touched_by_commit: usize,
    pub relation_identity_candidates_scanned: usize,
    pub visibility_entity_slot_scans: usize,
    pub visibility_relation_slot_scans: usize,
    pub visible_entity_records_materialized: usize,
    pub visible_relation_records_materialized: usize,
    pub invariant_entity_slot_scans: usize,
    pub invariant_relation_slot_scans: usize,
    pub invariant_entity_records_materialized: usize,
    pub invariant_relation_records_materialized: usize,
    pub snapshot_pin_adjustments: usize,
    pub snapshot_pin_full_rebuilds: usize,
    pub retention_entity_slots_scanned: usize,
    pub retention_relation_slots_scanned: usize,
    pub live_entity_history_entries_trimmed: usize,
    pub live_relation_history_entries_trimmed: usize,
    pub forward_adjacency_updates: usize,
    pub reverse_adjacency_updates: usize,
}

pub const COMPLEXITY_CONTRACTS: &[ComplexityContract] = &[
    ComplexityContract {
        id: "runtime.partition_local_commit",
        function_path: "logic/runtime/transaction.rs::RelationalTransaction::commit",
        declared_time_complexity: "O(touched_partitions + changed_records + touched_partition_clone_on_write)",
        budget_summary: "Commit/apply must report the number of partitions touched so partition-aware IDs do not degrade into global work by accident.",
        status: ComplexityStatus::Verified,
        proof_tests: &["tests::complexity_contracts::complexity_budget_partition_local_commit_reports_touched_partitions"],
    },
    ComplexityContract {
        id: "runtime.slot_local_mutation_journal",
        function_path: "logic/runtime/apply.rs::{apply_plan_to_staged_state,delete_entity_with_cascade,delete_relation}",
        declared_time_complexity: "O(touched_entity_slots + touched_relation_slots + adjacency_deltas)",
        budget_summary: "Commit-time mutation tracking must remain slot-local so structural validation can avoid rescanning untouched slots.",
        status: ComplexityStatus::Verified,
        proof_tests: &["tests::complexity_contracts::complexity_budget_mutation_structural_invariants_are_touched_slot_bounded"],
    },
    ComplexityContract {
        id: "runtime.current_state.clone",
        function_path: "logic/runtime/mod.rs::current_state",
        declared_time_complexity: "O(1)",
        budget_summary: "Current-state staging must remain a sparse overlay wrapper, not a deep clone of all partitions and slots.",
        status: ComplexityStatus::Verified,
        proof_tests: &["tests::complexity_contracts::complexity_contract_current_state_clone_is_declared_and_measured"],
    },
    ComplexityContract {
        id: "runtime.snapshot_pin_maintenance",
        function_path: "logic/runtime/mod.rs::{snapshot,release_snapshot,pin_entity,unpin_entity,pin_relation,unpin_relation}",
        declared_time_complexity: "O(snapshot_delta_records)",
        budget_summary: "Commit and release paths must not rebuild all pin counters from live snapshots.",
        status: ComplexityStatus::Verified,
        proof_tests: &["tests::complexity_contracts::complexity_budget_snapshot_pin_maintenance_is_incremental"],
    },
    ComplexityContract {
        id: "runtime.relation_identity_validation",
        function_path: "logic/runtime/merge.rs::validate_relation_creation",
        declared_time_complexity: "O(out_degree(source) + same_batch_relation_creates)",
        budget_summary: "Duplicate relation identity checks must avoid full partition relation scans by using adjacency-local candidates and deterministic same-batch keys.",
        status: ComplexityStatus::Verified,
        proof_tests: &["tests::complexity_contracts::complexity_budget_relation_identity_validation_avoids_partition_scan"],
    },
    ComplexityContract {
        id: "runtime.unique_entity_invariant_lookup",
        function_path: "logic/runtime/invariants.rs::run_invariants_for_state",
        declared_time_complexity: "O(touched_entities + unique_lookup_hits)",
        budget_summary: "Unique-field invariant checks should use touched entities plus the maintained lookup index instead of broad visible-entity scans when the changed set is known.",
        status: ComplexityStatus::Verified,
        proof_tests: &[
            "tests::complexity_contracts::complexity_budget_unique_entity_invariant_uses_changed_set_lookup",
            "tests::complexity_contracts::complexity_budget_commit_boundary_unique_invariant_uses_merged_plan_lookup",
        ],
    },
    ComplexityContract {
        id: "runtime.visible_entities.scan",
        function_path: "logic/runtime/read.rs::visible_entities_from_state",
        declared_time_complexity: "O(entity_slots)",
        budget_summary: "Visibility scans must report slot-scan cost explicitly; no hidden mutation is allowed.",
        status: ComplexityStatus::Verified,
        proof_tests: &["tests::complexity_contracts::complexity_contract_visibility_scans_are_explicitly_measured"],
    },
    ComplexityContract {
        id: "runtime.visible_relations.scan",
        function_path: "logic/runtime/read.rs::visible_relations_from_state",
        declared_time_complexity: "O(relation_slots)",
        budget_summary: "Relation visibility scans must report slot-scan cost explicitly; no hidden mutation is allowed.",
        status: ComplexityStatus::Verified,
        proof_tests: &["tests::complexity_contracts::complexity_contract_visibility_scans_are_explicitly_measured"],
    },
    ComplexityContract {
        id: "runtime.retention.pass",
        function_path: "logic/runtime/mod.rs::run_retention_pass",
        declared_time_complexity: "O(chunks_with_retained_records + reclaim_batch_size + changed_live_history)",
        budget_summary: "Retention scans should stay chunk-filtered and live-history trimming must remain touched-record bounded.",
        status: ComplexityStatus::Verified,
        proof_tests: &["tests::complexity_contracts::complexity_budget_live_history_trimming_is_touched_record_bounded"],
    },
    ComplexityContract {
        id: "runtime.relation_adjacency.lookup",
        function_path: "logic/runtime/mod.rs::{outgoing_relations_for_entity,incoming_relations_for_entity}",
        declared_time_complexity: "O(out_degree) / O(in_degree)",
        budget_summary: "Forward and reverse relation traversal must not require full relation scans.",
        status: ComplexityStatus::Verified,
        proof_tests: &["tests::complexity_contracts::complexity_budget_bidirectional_adjacency_avoids_relation_scans"],
    },
    ComplexityContract {
        id: "runtime.invariant.materialization",
        function_path: "logic/runtime/invariants.rs::run_invariants_for_state",
        declared_time_complexity: "O(entity_slots + relation_slots) today, moving toward changed-set/index-assisted checks",
        budget_summary: "Invariant materialization cost must be measured explicitly so full-state checks cannot hide.",
        status: ComplexityStatus::Debt,
        proof_tests: &["tests::complexity_contracts::complexity_contract_invariant_materialization_is_declared_and_measured"],
    },
];
