mod arbitration;
mod closeout;
pub(crate) mod continuity;
mod corpus;
mod motion;
pub(crate) mod preview;
pub(crate) mod profile;
mod realization;

pub use arbitration::{
    prepare_primitive_chosen_intent_resolution_report,
    prepare_primitive_construction_intent_arbitration_hostility_suite_report,
    prepare_primitive_construction_intent_arbitration_report_bundle,
    prepare_primitive_construction_preserved_intent_resolution_report,
    prepare_primitive_intent_arbitration_policy_report,
    prepare_primitive_intent_conflict_dx_surface_report,
    PrimitiveConstructionChosenIntentResolutionAuthority,
    PrimitiveConstructionChosenIntentResolutionCase,
    PrimitiveConstructionChosenIntentResolutionReport,
    PrimitiveConstructionChosenIntentResolutionReportError,
    PrimitiveConstructionChosenIntentResolutionRow,
    PrimitiveConstructionIntentArbitrationBundleCase,
    PrimitiveConstructionIntentArbitrationConflictClass,
    PrimitiveConstructionIntentArbitrationDxSurface,
    PrimitiveConstructionIntentArbitrationDxSurfaceReport,
    PrimitiveConstructionIntentArbitrationDxSurfaceRow,
    PrimitiveConstructionIntentArbitrationHostilitySuiteReport,
    PrimitiveConstructionIntentArbitrationPolicyCase,
    PrimitiveConstructionIntentArbitrationPolicyReport,
    PrimitiveConstructionIntentArbitrationPolicyReportError,
    PrimitiveConstructionIntentArbitrationPolicyRow,
    PrimitiveConstructionIntentArbitrationReportBundleError,
    PrimitiveConstructionObservedIntentRelation,
    PrimitiveConstructionPreservedIntentResolutionCase,
    PrimitiveConstructionPreservedIntentResolutionReport,
    PrimitiveConstructionPreservedIntentResolutionReportError,
    PrimitiveConstructionPreservedIntentResolutionRow, PrimitiveConstructionPreservedIntentTruth,
    PrimitiveConstructionVerifiedIntentArbitrationReportBundle,
};
pub use closeout::{
    prepare_primitive_construction_milestone_four_kernel_closeout_evidence_report,
    prepare_primitive_construction_phase_five_boundary_closeout_report,
    prepare_primitive_construction_phase_five_six_closeout_report,
    PrimitiveConstructionMilestoneFourKernelCloseoutEvidenceReport,
    PrimitiveConstructionMilestoneFourKernelCloseoutEvidenceReportError,
    PrimitiveConstructionMilestoneFourKernelCloseoutVerificationFailure,
    PrimitiveConstructionMilestoneFourKernelCloseoutVerificationMismatch,
    PrimitiveConstructionPhaseFiveBoundaryCloseoutKind,
    PrimitiveConstructionPhaseFiveBoundaryCloseoutReport,
    PrimitiveConstructionPhaseFiveBoundaryCloseoutRow,
    PrimitiveConstructionPhaseFiveSixCloseoutReport,
    PrimitiveConstructionPhaseFiveSixCloseoutReportError,
    PrimitiveConstructionPhaseFiveSixCloseoutVerificationFailure,
    PrimitiveConstructionPhaseFiveSixCloseoutVerificationMismatch,
};
pub use continuity::{
    prepare_primitive_construction_continuity_hostility_suite_report,
    prepare_primitive_construction_continuity_surface_report, PrimitiveConstructionContinuityCase,
    PrimitiveConstructionContinuityHostilitySuiteReport,
    PrimitiveConstructionContinuityResolutionSource, PrimitiveConstructionContinuityRow,
    PrimitiveConstructionContinuitySurfaceReport,
    PrimitiveConstructionContinuitySurfaceReportError,
};
pub use corpus::{
    prepare_primitive_construction_compound_adversarial_siege_report,
    prepare_primitive_construction_compound_exhaustion_witness_parity_report,
    prepare_primitive_construction_compound_grazing_boundary_report,
    prepare_primitive_construction_compound_milestone_closeout_report,
    prepare_primitive_construction_compound_motion_parity_report,
    prepare_primitive_construction_compound_ordering_parity_report,
    prepare_primitive_construction_compound_parity_report,
    prepare_primitive_construction_corpus_replay_siege,
    prepare_primitive_construction_family_boundary_drift_report,
    prepare_primitive_construction_family_boundary_report,
    prepare_primitive_construction_simplex_realization_exhaustion_witness_report,
    prepare_primitive_construction_simplex_realization_strategy_ladder_report,
    PrimitiveConstructionCompoundAdversarialSiegeError,
    PrimitiveConstructionCompoundAdversarialSiegeReport,
    PrimitiveConstructionCompoundAuthoringOrderRow,
    PrimitiveConstructionCompoundExhaustionWitnessParityReport,
    PrimitiveConstructionCompoundExhaustionWitnessParityRow,
    PrimitiveConstructionCompoundGrazingBoundaryReport,
    PrimitiveConstructionCompoundGrazingBoundaryRow, PrimitiveConstructionCompoundGrazingKind,
    PrimitiveConstructionCompoundMilestoneCloseoutReport, PrimitiveConstructionCompoundMotionKind,
    PrimitiveConstructionCompoundMotionParityReport, PrimitiveConstructionCompoundMotionParityRow,
    PrimitiveConstructionCompoundOrderLaneReport,
    PrimitiveConstructionCompoundOrderingParityReport,
    PrimitiveConstructionCompoundOrderingScenarioRow,
    PrimitiveConstructionCompoundParityCanonicalTruth, PrimitiveConstructionCompoundParityReport,
    PrimitiveConstructionCompoundParityVerificationFailure,
    PrimitiveConstructionCompoundParityVerificationMismatch, PrimitiveConstructionCompoundRow,
    PrimitiveConstructionCompoundRowClass, PrimitiveConstructionCompoundTopologyClass,
    PrimitiveConstructionCompoundWorkloadFamily, PrimitiveConstructionCorpusAuthoringOrderRow,
    PrimitiveConstructionCorpusOutcomeDisposition, PrimitiveConstructionCorpusParameterRole,
    PrimitiveConstructionCorpusRejectionWitnessRow, PrimitiveConstructionCorpusReplaySiegeError,
    PrimitiveConstructionCorpusReplaySiegeReport, PrimitiveConstructionCorpusReplaySiegeRow,
    PrimitiveConstructionFamilyBoundaryDriftReport, PrimitiveConstructionFamilyBoundaryDriftRow,
    PrimitiveConstructionFamilyBoundaryLowerLayerWitnessSummary,
    PrimitiveConstructionFamilyBoundaryReport, PrimitiveConstructionFamilyBoundaryReportError,
    PrimitiveConstructionFamilyBoundaryRow, PrimitiveConstructionFamilyBoundaryTransitionClass,
    PrimitiveConstructionSimplexExhaustionWitnessRow,
    PrimitiveConstructionSimplexQuerySurfaceStatus,
    PrimitiveConstructionSimplexRealizationExhaustionWitnessReport,
    PrimitiveConstructionSimplexRealizationLadderReportError,
    PrimitiveConstructionSimplexRealizationLadderRow,
    PrimitiveConstructionSimplexRealizationStrategyLadderReport,
};
pub use motion::{
    prepare_primitive_construction_motion_dx_surface_report,
    prepare_primitive_construction_motion_resolution_policy_report,
    prepare_primitive_construction_move_motion_report_bundle,
    prepare_primitive_construction_move_witness_resolution_report,
    prepare_primitive_construction_move_witness_resolution_report_with_catalog,
    prepare_primitive_construction_points_toward_motion_report_bundle,
    prepare_primitive_construction_points_toward_motion_report_bundle_with_catalog,
    prepare_primitive_construction_points_toward_witness_resolution_report,
    prepare_primitive_construction_points_toward_witness_resolution_report_with_catalog,
    prepare_primitive_construction_reorient_motion_report_bundle,
    prepare_primitive_construction_reorient_motion_report_bundle_with_catalog,
    prepare_primitive_construction_reorient_witness_resolution_report,
    prepare_primitive_construction_reorient_witness_resolution_report_with_catalog,
    prepare_primitive_construction_rotate_motion_report_bundle_with_catalog,
    prepare_primitive_construction_rotate_witness_resolution_report,
    prepare_primitive_construction_rotate_witness_resolution_report_with_catalog,
    PrimitiveConstructionMotionDxSurface, PrimitiveConstructionMotionDxSurfaceReport,
    PrimitiveConstructionMotionDxSurfaceReportError, PrimitiveConstructionMotionDxSurfaceRow,
    PrimitiveConstructionMotionReportBundleError, PrimitiveConstructionMotionResolutionPolicyCase,
    PrimitiveConstructionMotionResolutionPolicyReport,
    PrimitiveConstructionMotionResolutionPolicyReportError,
    PrimitiveConstructionMotionResolutionPolicyRow,
    PrimitiveConstructionMotionWitnessResolutionFailureKind,
    PrimitiveConstructionMotionWitnessResolutionKind,
    PrimitiveConstructionMotionWitnessResolutionReport,
    PrimitiveConstructionMotionWitnessResolutionStatus,
    PrimitiveConstructionRequestedMotionWitness, PrimitiveConstructionResolvedMotionWitness,
    PrimitiveConstructionVerifiedMotionReportBundle,
};
pub use preview::{
    prepare_primitive_construction_preview_hostility_suite_report,
    prepare_primitive_construction_preview_surface_report, PrimitiveConstructionPreviewCase,
    PrimitiveConstructionPreviewHostilitySuiteReport, PrimitiveConstructionPreviewRow,
    PrimitiveConstructionPreviewSurfaceReport, PrimitiveConstructionPreviewSurfaceReportError,
};
pub use profile::{
    prepare_primitive_construction_policy_pressure_delta_report,
    prepare_primitive_construction_policy_pressure_report,
    prepare_primitive_construction_policy_profile_report,
    prepare_primitive_construction_preview_continuity_hostility_suite_report,
    PrimitiveConstructionPolicyPressureCase, PrimitiveConstructionPolicyPressureDeltaCase,
    PrimitiveConstructionPolicyPressureDeltaReport,
    PrimitiveConstructionPolicyPressureDeltaReportError,
    PrimitiveConstructionPolicyPressureDeltaRow, PrimitiveConstructionPolicyPressureRow,
    PrimitiveConstructionPolicyPressureSetup, PrimitiveConstructionPolicyPressureSurfaceReport,
    PrimitiveConstructionPolicyPressureSurfaceReportError, PrimitiveConstructionPolicyProfileCase,
    PrimitiveConstructionPolicyProfileRow, PrimitiveConstructionPolicyProfileSurfaceReport,
    PrimitiveConstructionPreviewContinuityHostilityCase,
    PrimitiveConstructionPreviewContinuityHostilityRow,
    PrimitiveConstructionPreviewContinuityHostilitySuiteError,
    PrimitiveConstructionPreviewContinuityHostilitySuiteReport,
};
pub use realization::{
    prepare_primitive_construction_conditioning_witness_report,
    prepare_primitive_construction_realization_exhaustion_report,
    prepare_primitive_construction_realization_exhaustion_witness_report,
    prepare_primitive_construction_realization_report_bundle,
    prepare_primitive_construction_realization_strategy_report,
    prepare_primitive_construction_stability_class_report,
    PrimitiveConstructionConditioningWitnessReport,
    PrimitiveConstructionRealizationExhaustionReport,
    PrimitiveConstructionRealizationExhaustionStatus,
    PrimitiveConstructionRealizationExhaustionWitnessReport,
    PrimitiveConstructionRealizationExhaustionWitnessRow,
    PrimitiveConstructionRealizationReportBundle, PrimitiveConstructionRealizationStrategyReport,
    PrimitiveConstructionStabilityClassReport,
};

#[cfg(test)]
mod milestone_four_kernel_closeout_tests;
#[cfg(test)]
mod phase_five_boundary_closeout_tests;
#[cfg(test)]
mod phase_five_six_closeout_tests;
