mod application_attempt;
mod application_query;
mod authorization;
pub(in crate::domain_computation::primary_graph) mod fixture;
mod graph_obligation_admission;
mod hostile_resolution;
mod invariant_projection;
pub(in crate::domain_computation::primary_graph) mod live_delivery_support;
mod session_fact_substitution;
mod successful_resolution;
mod typed_bootstrap;
