pub(in crate::domain_computation::primary_graph) mod application_attempt;
mod application_outcome_identity;
mod application_query;
mod authorization;
pub(in crate::domain_computation::primary_graph) mod fault_controller;
pub(in crate::domain_computation) mod fixture;
mod hostile_resolution;
mod invariant_projection;
pub(in crate::domain_computation::primary_graph) mod live_delivery_support;
mod successful_resolution;
mod typed_bootstrap;
