use super::*;

pub(in crate::runtime::tests) fn compose_authoritative_intent_receipt_inspection_identity(
    inspection: &WorthQueryIntentReceiptInspection,
) -> WorthQueryEvidenceIdentity {
    WorthQueryEvidenceIdentity::compose(WorthQueryEvidenceScope::IntentReceiptInspection)
        .field_shape(
            WorthQueryEvidenceTag::new("intent_name"),
            inspection.intent_name(),
        )
        .field_shape(
            WorthQueryEvidenceTag::new("execution_kind"),
            inspection.execution_kind().as_str(),
        )
        .field_value(
            WorthQueryEvidenceTag::new("strategy_identity"),
            inspection.strategy_identity(),
        )
        .field_shape(
            WorthQueryEvidenceTag::new("strategy_version"),
            inspection.strategy_version(),
        )
        .field_value(
            WorthQueryEvidenceTag::new("strategy_descriptor_digest"),
            inspection.strategy_descriptor_digest(),
        )
        .field_value(
            WorthQueryEvidenceTag::new("canonical_input_digest"),
            inspection.canonical_input_digest(),
        )
        .field_value(
            WorthQueryEvidenceTag::new("outcome_digest"),
            inspection.outcome_digest(),
        )
        .optional_identity(
            WorthQueryEvidenceTag::new("produced_mutation_digest"),
            inspection.produced_mutation_digest(),
        )
        .field_value_sequence(
            WorthQueryEvidenceTag::new("invariant_evidence"),
            inspection.invariant_evidence().iter().map(String::as_str),
        )
        .field_shape(
            WorthQueryEvidenceTag::new("source_lane"),
            inspection.source_lane().as_str(),
        )
        .field_shape(
            WorthQueryEvidenceTag::new("target_lane"),
            inspection.target_lane().as_str(),
        )
        .field_evidence_identity(
            WorthQueryEvidenceTag::new("commit_evidence_identity"),
            &inspection.commit_identity().evidence_identity(),
        )
        .field_evidence_identity(
            WorthQueryEvidenceTag::new("snapshot_evidence_identity"),
            &inspection.snapshot_identity().evidence_identity(),
        )
        .field_evidence_identity(
            WorthQueryEvidenceTag::new("receipt_identity"),
            inspection.receipt_identity(),
        )
        .field_evidence_identity(
            WorthQueryEvidenceTag::new("delivery_counter_identity"),
            inspection.delivery_counters().counter_identity(),
        )
        .seal()
}

pub(in crate::runtime::tests) fn compose_effect_intent_receipt_inspection_identity(
    inspection: &WorthQueryEffectIntentReceiptInspection,
) -> WorthQueryEvidenceIdentity {
    WorthQueryEvidenceIdentity::compose(WorthQueryEvidenceScope::EffectIntentReceiptInspection)
        .field_shape(
            WorthQueryEvidenceTag::new("effect_name"),
            inspection.effect_name(),
        )
        .field_evidence_identity(
            WorthQueryEvidenceTag::new("trigger_commit_evidence_identity"),
            inspection.trigger_commit_evidence_identity(),
        )
        .field_shape(
            WorthQueryEvidenceTag::new("trigger_source_kind"),
            inspection.trigger_source_kind().as_str(),
        )
        .field_value(
            WorthQueryEvidenceTag::new("pending_intent_target"),
            inspection.pending_intent_target(),
        )
        .field_shape(
            WorthQueryEvidenceTag::new("source_lane"),
            inspection.source_lane().as_str(),
        )
        .field_shape(
            WorthQueryEvidenceTag::new("target_lane"),
            inspection.target_lane().as_str(),
        )
        .field_shape(
            WorthQueryEvidenceTag::new("effect_policy"),
            inspection.effect_policy().as_str(),
        )
        .field_evidence_identity(
            WorthQueryEvidenceTag::new("phase_identity"),
            inspection.phase_identity(),
        )
        .field_evidence_identity(
            WorthQueryEvidenceTag::new("intent_receipt_identity"),
            inspection.intent_receipt_identity(),
        )
        .field_evidence_identity(
            WorthQueryEvidenceTag::new("receipt_identity"),
            inspection.receipt_identity(),
        )
        .field_evidence_identity(
            WorthQueryEvidenceTag::new("feedback_graph_identity"),
            inspection.feedback_graph().graph_identity(),
        )
        .seal()
}
