use std::collections::BTreeSet;

pub(super) fn expected_exports() -> [(&'static str, BTreeSet<String>); 6] {
    [
        ("facade/mod.rs", names(FACADE_EXPORTS)),
        ("query/mod.rs", names(QUERY_EXPORTS)),
        ("target/mod.rs", names(TARGET_EXPORTS)),
        ("scope/mod.rs", names(SCOPE_EXPORTS)),
        ("receipt/mod.rs", names(RECEIPT_EXPORTS)),
        ("posture/mod.rs", names(POSTURE_EXPORTS)),
    ]
}

fn names(values: &[&str]) -> BTreeSet<String> {
    values.iter().map(|value| (*value).to_owned()).collect()
}

const FACADE_EXPORTS: &[&str] = &[
    "RUNTIME_INSPECTION_SCOPE_INVENTORY",
    "UiInspectionScopeInventory",
];

const QUERY_EXPORTS: &[&str] = &[
    "SealedPixelArtifactPolicy",
    "UiAllocationPlanningQuestion",
    "UiEvidenceBudget",
    "UiEvidenceLinkKind",
    "UiEvidenceRichness",
    "UiGeometryOnly",
    "UiInspectionAspectRelevanceDetail",
    "UiInspectionEvidenceSource",
    "UiInspectionObligationRelevanceDetail",
    "UiInspectionQuery",
    "UiInspectionRelevance",
    "UiInspectionRelevanceAdmission",
    "UiInspectionRelevanceOutcome",
    "UiInspectionTargetClass",
    "UiPixelsOptional",
    "UiPixelsRequired",
    "UiRelevanceFamily",
    "UiRelevanceFilter",
    "UiVisualArtifactPolicy",
    "UiVisualCaptureCancellation",
    "UiVisualCaptureDeadline",
    "UiVisualInspectionAudience",
    "UiVisualInspectionByteBudget",
    "UiVisualInspectionCapacity",
    "UiVisualInspectionDisclosure",
    "UiVisualInspectionPolicy",
    "UiVisualInspectionPolicyDenial",
    "UiVisualInspectionRegionCapacity",
    "UiVisualPixelRedaction",
    "UiVisualSnapshotRequest",
];

const TARGET_EXPORTS: &[&str] = &[
    "UiAuthoredSourceProvenanceRef",
    "UiInspectionAspectName",
    "UiInspectionDeclarationIdentity",
    "UiInspectionTarget",
    "UiSourceArtifactGeneration",
    "UiSourceArtifactIdentity",
];

const SCOPE_EXPORTS: &[&str] = &["UiInspectionScope"];

const RECEIPT_EXPORTS: &[&str] = &[
    "UiClientPhysicalPixel",
    "UiClientPhysicalRect",
    "UiHitTestRegionIndexIdentity",
    "UiHostSurfaceLogicalPoint",
    "UiInspectionAiHarnessLane",
    "UiInspectionClosedSemanticLane",
    "UiInspectionCloseoutGuarantee",
    "UiInspectionCloseoutNonGoal",
    "UiInspectionCloseoutReport",
    "UiInspectionClosureReport",
    "UiInspectionCostLane",
    "UiInspectionCostReceipt",
    "UiInspectionDerivedIndexLane",
    "UiInspectionMeasurementBasisInput",
    "UiInspectionMeasurementBasisPosture",
    "UiInspectionMeasurementBasisSource",
    "UiInspectionMeasurementChildIntrinsicSource",
    "UiInspectionMeasurementDenialPosture",
    "UiInspectionMeasurementDependencyLineageEntry",
    "UiInspectionMeasurementDependencyLineageKind",
    "UiInspectionMeasurementEvidenceCategory",
    "UiInspectionMeasurementEvidenceSlot",
    "UiInspectionMeasurementEvidenceView",
    "UiInspectionMeasurementEvidenceViewInput",
    "UiInspectionMeasurementFailureSource",
    "UiInspectionMeasurementGenerationCompatibility",
    "UiInspectionMeasurementNeighborhoodClassHint",
    "UiInspectionMeasurementOwnershipPosture",
    "UiInspectionMeasurementQueryFactFamily",
    "UiInspectionMeasurementQueryUnsupportedReason",
    "UiInspectionQueryWorldCompatibilityFailure",
    "UiInspectionRefLifecycleLane",
    "UiInspectionScopeSupportRow",
    "UiInspectionSliceLane",
    "UiInspectionSupportReport",
    "UiNativeScreenPhysicalPixel",
    "UiRebindDecisionDisposition",
    "UiRebindDecisionIndex",
    "UiRebindDecisionIndexDenial",
    "UiRebindDecisionKey",
    "UiRebindDecisionLookup",
    "UiRebindDecisionRecord",
    "UiRebindDecisionRecordInput",
    "UiRebindDecisionStopPoint",
    "UiRebindStructuralCost",
    "UiViewportLogicalPoint",
    "UiVisualAuthoredProvenance",
    "UiVisualComparisonPixelPolicy",
    "UiVisualContributorStack",
    "UiVisualCoordinateDenial",
    "UiVisualCoordinateObservation",
    "UiVisualCoordinateObservationInput",
    "UiVisualCoordinateOrientation",
    "UiVisualCoordinateRounding",
    "UiVisualDeclarationRef",
    "UiVisualDerivedPixelArtifactInput",
    "UiVisualEvidenceRef",
    "UiVisualGraphNodeRef",
    "UiVisualHitTestOutcome",
    "UiVisualHitTestTarget",
    "UiVisualIdentityContinuity",
    "UiVisualIdentityTrace",
    "UiVisualIdentityTraceInput",
    "UiVisualInspectionCostLane",
    "UiVisualInspectionCostReceipt",
    "UiVisualMountedNodeRef",
    "UiVisualNativePixelArtifactInput",
    "UiVisualOverlayDenial",
    "UiVisualPixelArtifact",
    "UiVisualPixelArtifactValidity",
    "UiVisualPixelCaptureSource",
    "UiVisualPixelColorSpace",
    "UiVisualPixelFormat",
    "UiVisualPixelRetentionDisposition",
    "UiVisualPointAdjudication",
    "UiVisualQueryBudget",
    "UiVisualRegionAdjudication",
    "UiVisualRegionCompleteness",
    "UiVisualRegionIntersection",
    "UiVisualSnapshotAffinity",
    "UiVisualSnapshotArtifactPosture",
    "UiVisualSnapshotComparison",
    "UiVisualSnapshotComparisonBudget",
    "UiVisualSnapshotComparisonBudgetDenial",
    "UiVisualSnapshotComparisonCost",
    "UiVisualSnapshotComparisonDenial",
    "UiVisualSnapshotComparisonDenialKind",
    "UiVisualSnapshotComparisonExpiry",
    "UiVisualSnapshotComparisonIncompatibility",
    "UiVisualSnapshotComparisonInput",
    "UiVisualSnapshotComparisonOmission",
    "UiVisualSnapshotComparisonOutcome",
    "UiVisualSnapshotDenial",
    "UiVisualSnapshotEvidence",
    "UiVisualSnapshotEvidenceInput",
    "UiVisualSnapshotIndeterminate",
    "UiVisualSnapshotOmission",
    "UiVisualSnapshotRelation",
    "UiVisualSnapshotSuperseded",
    "UiVisualVisibleContributor",
    "UiVisualVisibleOutcome",
    "UiVisibleRegionIndexIdentity",
];

const POSTURE_EXPORTS: &[&str] = &[
    "UiInspectionAdmissionPosture",
    "UiInspectionDeferredPosture",
    "UiInspectionDiagnosticOnlyPosture",
    "UiInspectionMilestoneExpectation",
    "UiInspectionPosture",
    "UiInspectionSupportPosture",
    "UiInspectionSupportReason",
    "UiInspectionSupportStatus",
    "UiInspectionSupportWorld",
    "UiInspectionUnsupportedPosture",
    "UiInspectionWrongWorldPosture",
];
