use super::registry::{
    PREDICATE, PREDICATE_EXPORTS, PREDICATE_OPERAND, SCHEMA_EXPORTS, SCHEMA_FIELD,
};
use super::registry_helpers::{contract_projection, unvalidated};
use super::WorthQueryNativeValueAuthorityRow as Row;

pub(super) const ROWS: &[Row] = &[
    unvalidated(
        "WorthQueryPredicateOperand",
        PREDICATE_OPERAND,
        PREDICATE_EXPORTS,
        &["predicate authoring", "templates", "canonical scalar sets"],
        "phase-27-native-predicate-operands",
    ),
    unvalidated(
        "NativeComparisonPredicate",
        PREDICATE,
        &[
            "src/facade/exports_foundation.rs",
            "src/facade/exports_read.rs",
            "src/facade/exports_history.rs",
            "src/facade/exports_comparison.rs",
        ],
        &["native comparison predicate authoring"],
        "phase-27-native-predicate-operands",
    ),
    unvalidated(
        "DeclarativeNativeComparisonFilter",
        "src/declarative_live.rs",
        &["src/facade/exports_foundation.rs"],
        &["declarative live native comparison authoring"],
        "phase-27-native-predicate-operands",
    ),
    contract_projection(
        "identity_anchor",
        "src/runtime/read_composition_row_selection.rs",
        &[],
        &["runtime identity predicate extraction"],
        "phase-27-native-predicate-operands",
    ),
    unvalidated(
        "CanonicalScalarSet",
        "src/canonicalization/artifacts/scalar_set.rs",
        &[],
        &["predicate canonicalization"],
        "phase-27-native-predicate-operands",
    ),
    unvalidated(
        "EqualityPredicate",
        PREDICATE,
        PREDICATE_EXPORTS,
        &["equality predicate authoring"],
        "phase-27-native-predicate-operands",
    ),
    unvalidated(
        "SetMembershipPredicate",
        PREDICATE,
        PREDICATE_EXPORTS,
        &["membership predicate authoring"],
        "phase-27-native-predicate-operands",
    ),
    unvalidated(
        "CanonicalPredicateOperand",
        "src/canonicalization/artifacts/entries.rs",
        &[],
        &["predicate canonicalization"],
        "phase-27-native-predicate-operands",
    ),
    unvalidated(
        "DeclarativeEqualityFilter",
        "src/declarative_live.rs",
        &["src/facade/exports_foundation.rs"],
        &["declarative live predicate authoring"],
        "phase-27-native-predicate-operands",
    ),
    unvalidated(
        "DeclarativeSetMembershipFilter",
        "src/declarative_live.rs",
        &["src/facade/exports_foundation.rs"],
        &["declarative live predicate authoring"],
        "phase-27-native-predicate-operands",
    ),
    contract_projection(
        "SchemaFieldView",
        SCHEMA_FIELD,
        SCHEMA_EXPORTS,
        &["schema views", "operator admission"],
        "phase-27-contract-derived-schema",
    ),
    contract_projection(
        "WorthQueryAdmittedBooleanPredicateLeaf",
        "src/runtime/graph_read_access/boolean_expression/evidence.rs",
        &["src/facade/exports_runtime.rs"],
        &["graph-read predicate evidence"],
        "phase-27-native-predicate-operands",
    ),
    contract_projection(
        "WorthQueryAdmittedGraphReadProjectionField",
        "src/runtime/graph_read_access/schema_reference_evidence/admitted_reference_rows.rs",
        &["src/facade/exports_runtime.rs"],
        &["graph-read projection admission"],
        "phase-27-contract-derived-schema",
    ),
    contract_projection(
        "WorthQueryAdmittedGraphReadPredicateField",
        "src/runtime/graph_read_access/schema_reference_evidence/admitted_reference_rows.rs",
        &["src/facade/exports_runtime.rs"],
        &["graph-read predicate admission"],
        "phase-27-contract-derived-schema",
    ),
    contract_projection(
        "WorthQueryAdmittedGraphReadOrderingField",
        "src/runtime/graph_read_access/schema_reference_evidence/admitted_reference_rows.rs",
        &["src/facade/exports_runtime.rs"],
        &["graph-read ordering admission"],
        "phase-27-contract-derived-schema",
    ),
    contract_projection(
        "WorthQueryBooleanPredicateSelectivityRow",
        "src/runtime/graph_read_access/selectivity_shape/row.rs",
        &["src/facade/exports_runtime.rs"],
        &["graph-read selectivity planning"],
        "phase-27-native-predicate-operands",
    ),
    contract_projection(
        "ValidatedProjectionEntry",
        "src/validation/artifacts/entries.rs",
        &["src/facade/exports_runtime_products.rs"],
        &["projection validation"],
        "phase-27-contract-derived-schema",
    ),
    contract_projection(
        "ValidatedResultShapeBinding",
        "src/validation/artifacts/entries.rs",
        &["src/facade/exports_runtime_products.rs"],
        &["result-shape validation"],
        "phase-27-contract-derived-schema",
    ),
    contract_projection(
        "ValidatedPredicateEntry",
        "src/validation/artifacts/entries.rs",
        &["src/facade/exports_runtime_products.rs"],
        &["predicate validation"],
        "phase-27-native-predicate-operands",
    ),
    contract_projection(
        "ValidatedOrderingEntry",
        "src/validation/artifacts/entries.rs",
        &["src/facade/exports_runtime_products.rs"],
        &["ordering validation"],
        "phase-27-contract-derived-schema",
    ),
];
