use super::registry::{CONSUMED_FACTS, CONSUMED_FIELD_VALUE, LIVE_SURFACE};
use super::registry_helpers::{misleading, proof};
use super::{
    WorthQueryNativeValueAuthorityClass as Class, WorthQueryNativeValueAuthorityRow as Row,
    WorthQueryNativeValueDisposition as Disposition,
};

pub(super) const ROWS: &[Row] = &[
    Row::new(
        "ConsumedFieldValueFact",
        CONSUMED_FIELD_VALUE,
        &[
            "src/facade/exports_foundation.rs",
            "src/facade/exports_read.rs",
        ],
        &["projection consumption", "ordinary refinement"],
        Class::ProofBearingCarrier,
        Disposition::PreserveScalarAndStruct,
        "phase-28-native-result-consumption",
    ),
    Row::new(
        "ConsumedNativeValueView",
        "src/projection_consumption/consumed/native_value.rs",
        &[
            "src/facade/exports_foundation.rs",
            "src/facade/exports_read.rs",
        ],
        &["projection consumption", "ordinary refinement"],
        Class::ProofBearingCarrier,
        Disposition::PreserveScalarAndStruct,
        "phase-28-native-result-consumption",
    ),
    proof(
        "ConsumedMembershipFact",
        CONSUMED_FACTS,
        &["src/facade/exports_foundation.rs"],
        &["projection membership consumption"],
        "phase-28-native-result-consumption",
    ),
    proof(
        "ConsumedRelationEndpointFact",
        CONSUMED_FACTS,
        &["src/facade/exports_foundation.rs"],
        &["projection relation consumption"],
        "phase-28-native-result-consumption",
    ),
    Row::new(
        "WorthQueryRetainedMaterializedRow",
        "src/runtime/surface/retained_materialized_row.rs",
        &["src/facade/exports_runtime_core.rs"],
        &["retained result materialization"],
        Class::ScalarOnlyBridge,
        Disposition::PreserveScalarAndStruct,
        "phase-28-native-result-consumption",
    ),
    Row::new(
        "WorthQueryRetainedValueView",
        "src/runtime/surface/retained_materialized_row.rs",
        &["src/facade/exports_runtime_core.rs"],
        &["borrowed retained scalar or struct inspection"],
        Class::ProofBearingCarrier,
        Disposition::PreserveScalarAndStruct,
        "phase-28-native-result-consumption",
    ),
    proof(
        "WorthQueryRetainedScalarAlignmentFact",
        "src/runtime/surface/retained_scalar_alignment.rs",
        &["src/facade/exports_runtime_core.rs"],
        &["explicit scalar alignment"],
        "phase-28-native-result-consumption",
    ),
    proof(
        "WorthQueryRetainedScalarFieldFact",
        "src/runtime/surface/retained_scalar_facts.rs",
        &["src/facade/exports_runtime_core.rs"],
        &["explicit scalar projection"],
        "phase-28-native-result-consumption",
    ),
    misleading(
        "WorthQueryLiveView",
        LIVE_SURFACE,
        &["src/facade/exports_runtime_core.rs"],
        &["live result handle"],
    ),
    misleading(
        "WorthQueryDerivedViewHandle",
        "src/runtime/computed/surface.rs",
        &["src/facade/exports_runtime.rs"],
        &["derived result handle"],
    ),
    misleading(
        "WorthQueryManagedLiveHandle",
        "src/ordinary/live/handle.rs",
        &["src/facade/exports_live_capability.rs"],
        &["ordinary managed live handle"],
    ),
    misleading(
        "WorthQueryManagedLiveContinuation",
        "src/ordinary/live/continuation/checkpoint.rs",
        &["src/facade/exports_live_capability.rs"],
        &["ordinary managed live continuation"],
    ),
    Row::new(
        "WorthQueryUnrefinedLiveShape",
        LIVE_SURFACE,
        &["src/facade/exports_runtime_core.rs"],
        &["live views", "derived views", "computed views"],
        Class::RoleMarker,
        Disposition::PreserveRoleMarker,
        "phase-28-native-result-consumption",
    ),
    Row::new(
        "extract_bridge_row_set_facts",
        "src/projection_consumption/extraction/row_like.rs",
        &[],
        &["bridge materialization"],
        Class::ContractCapabilityProjection,
        Disposition::PreserveScalarAndStruct,
        "phase-28-native-result-consumption",
    ),
];
