//! Compatibility re-exports for callers that still import from `worth_ui::facade`.
//!
//! Prefer the named facade submodules such as `app`, `inspection`, `diagnostics`,
//! `dsl`, `host`, `registry`, and `support` for new code.
pub use crate::facade::app::{WorthUiApp, WorthUiAppBuilder, WorthUiBuilder};
pub use crate::facade::diagnostics::{
    CapabilityDiagnosticCode, CapabilityDiagnosticRichness, CapabilityDiagnosticSeverity,
    CapabilityRegistrationDiagnostic, CapabilityRegistrationReport, CapabilitySnapshot,
    CapabilitySnapshotDigest, CapabilitySnapshotIndex, RegisteredCapabilitySet,
    SnapshotFamilyIndex, SnapshotFreezeReport, SnapshotLookupCounters, SnapshotLookupReport,
    SnapshotMetrics, SnapshotReferenceValidationReport, SnapshotReferenceViolation,
    SnapshotReferenceViolationKind,
};
pub use crate::facade::graph::{
    project_aspect_evidence_ref, project_aspect_evidence_refs, UiAspectEvidenceLane,
    UiAspectEvidenceRefProjection, UiAspectEvidenceSubjectKind, UiGraphNodeIdentity,
    UiMountedReceiptIdentity,
};
pub use crate::facade::host::{
    WorthUiHostAdapter, WorthUiHostCapability, WorthUiHostCapabilityPosture,
    WorthUiHostCapabilityReport, WorthUiHostContract,
};
pub use crate::facade::inspection::{
    UiEvidenceAuthorityArtifactIdentity, UiEvidenceAuthorityBinding, UiEvidenceAuthorityGeneration,
    UiEvidenceAuthorityKind, UiEvidenceBudget, UiEvidenceExpansion, UiEvidenceExpansionOutcome,
    UiEvidenceFamily, UiEvidenceFamilySummary, UiEvidenceHandle, UiEvidenceIdentity,
    UiEvidenceLinkKind, UiEvidenceMaterializationPosture, UiEvidenceMaterializedDetail,
    UiEvidenceRef, UiEvidenceRetentionPosture, UiEvidenceRichness, UiEvidenceSlice,
    UiEvidenceSliceOmission, UiEvidenceSliceRef, UiInspectionAdmissionHostCapability,
    UiInspectionAdmissionPosture, UiInspectionAdmissionQueryBasis,
    UiInspectionAdmissionStaleEvidence, UiInspectionAiHarness, UiInspectionAiHarnessLane,
    UiInspectionClosedSemanticLane, UiInspectionCloseoutGuarantee, UiInspectionCloseoutNonGoal,
    UiInspectionCloseoutReport, UiInspectionClosureReport, UiInspectionCostLane,
    UiInspectionCostReceipt, UiInspectionDeferredPosture, UiInspectionDerivedIndexLane,
    UiInspectionDiagnosticOnlyPosture, UiInspectionEvidenceSource,
    UiInspectionForeignEvidenceCitation, UiInspectionForeignEvidenceRef,
    UiInspectionMeasurementBasisInput, UiInspectionMeasurementBasisPosture,
    UiInspectionMeasurementBasisSource, UiInspectionMeasurementDenialPosture,
    UiInspectionMeasurementDependencyLineageEntry, UiInspectionMeasurementDependencyLineageKind,
    UiInspectionMeasurementEvidenceCategory, UiInspectionMeasurementEvidenceSlot,
    UiInspectionMeasurementEvidenceView, UiInspectionMeasurementFailureSource,
    UiInspectionMeasurementGenerationCompatibility, UiInspectionMeasurementNeighborhoodClassHint,
    UiInspectionMeasurementOwnershipPosture, UiInspectionMilestoneExpectation,
    UiInspectionObligationDecision, UiInspectionObligationDenialPosture,
    UiInspectionObligationDispatchPosture, UiInspectionObligationEvidenceReceipt,
    UiInspectionObligationFamily, UiInspectionObligationLegalityReason,
    UiInspectionObligationNonSelectionReason, UiInspectionObligationReasonProjection,
    UiInspectionObligationRelevanceDetail, UiInspectionObligationSelectionReason,
    UiInspectionObligationVerdictClass, UiInspectionObligationVerdictPosture, UiInspectionPosture,
    UiInspectionQuery, UiInspectionQueryForeignEvidenceArtifactKind,
    UiInspectionQueryForeignEvidenceCitation, UiInspectionQueryForeignEvidenceKind,
    UiInspectionQueryForeignEvidenceRef, UiInspectionReceipt, UiInspectionRefLifecycleLane,
    UiInspectionRelevance, UiInspectionRelevanceAdmission, UiInspectionRelevanceOutcome,
    UiInspectionScope, UiInspectionScopeSupportRow, UiInspectionSliceLane,
    UiInspectionSupportPosture, UiInspectionSupportReason, UiInspectionSupportReport,
    UiInspectionSupportRowSchemaKind, UiInspectionSupportStatus, UiInspectionSupportWorld,
    UiInspectionTarget, UiInspectionTargetClass, UiInspectionTouchAspectPosture,
    UiInspectionTouchOriginClass, UiInspectionTouchRuntimeLane, UiInspectionTouchTargetClass,
    UiInspectionUnsupportedPosture, UiInspectionWrongWorldPosture,
    UiMeasurementInspectionEvidenceBundle, UiRelevanceFamily, UiRelevanceFilter,
};
pub use crate::facade::registry::{
    CommandCategory, CommandDescriptor, CommandId, CommandProjectionCommandReference,
    CommandProjectionDescriptor, CommandProjectionGrouping, CommandProjectionIconLabelPolicy,
    CommandProjectionId, CommandProjectionKey, CommandProjectionMeaningOverride,
    CommandProjectionMosaicScope, CommandProjectionOrdering, CommandProjectionOverflowBehavior,
    CommandProjectionReadinessDisplayPolicy, CommandProjectionShortcutVisibility,
    CommandProjectionSurface, CommandReadinessBinding, CommandReadinessStatus,
    CommandRuntimeIntentBinding, ComponentAccessibilitySupport, ComponentChildPolicy,
    ComponentDescriptor, ComponentExecutionLane, ComponentFocusSupport, ComponentId,
    ComponentPropSchema, ComponentStateOwnership, FrozenCommandCapabilities,
    FrozenCommandProjectionCapabilities, FrozenCommandProjectionEntry, FrozenComponentCapabilities,
    FrozenIconCapabilities, FrozenIconEntry, FrozenMosaicPlacementCapabilities,
    FrozenMosaicRegionCapabilities, FrozenMosaicSizingCapabilities, FrozenMosaicStateCapabilities,
    FrozenMosaicStateSlotEntry, FrozenNativeCapabilities, FrozenNativeCapabilityEntry,
    FrozenPluginSlotCapabilities, FrozenPluginSlotEntry,
    FrozenRuntimeOutcomeProjectionCapabilities, FrozenRuntimeOutcomeProjectionEntry,
    FrozenSettingCapabilities, FrozenSettingEntry, FrozenSurfaceCapabilities,
    FrozenTaskPresentationCapabilities, FrozenTaskPresentationEntry, FrozenThemeTokenCapabilities,
    FrozenThemeTokenEntry, FrozenViewBindingCapabilities, FrozenViewBindingEntry,
    IconAccessibilityPosture, IconColorSupport, IconDescriptor, IconFamily, IconId, IconKey,
    IconSizeSupport, IconSourceDescriptor, IconSourceKind, IconThemePosture, MeasurementConstraint,
    MeasurementValue, MosaicChildRule, MosaicClippingPosture, MosaicFocusScopeKind,
    MosaicHitTestPosture, MosaicMeasurementAuthority, MosaicOverflowBehavior,
    MosaicParentGrowthBehavior, MosaicPlacementAction, MosaicPlacementConflictBehavior,
    MosaicPlacementEligibility, MosaicPlacementPersistence, MosaicPlacementPolicyDescriptor,
    MosaicPlacementPolicyId, MosaicPlacementReloadReconciliation, MosaicPlacementSource,
    MosaicPlacementSupport, MosaicPlacementTarget, MosaicRegionKindDescriptor, MosaicRegionKindId,
    MosaicRegionPersistence, MosaicRegionRole, MosaicResizePermission, MosaicScrollOwnership,
    MosaicSizingBehavior, MosaicSizingContractDescriptor, MosaicSizingContractId, MosaicSizingKind,
    MosaicSizingPersistence, MosaicStableIdentityBehavior, MosaicStateOwnerIdentity,
    MosaicStateOwnerScopeId, MosaicStatePersistencePolicy, MosaicStateReconciliationKey,
    MosaicStateReplacementRule, MosaicStateSlotDescriptor, MosaicStateSlotId, MosaicStateSlotKind,
    MosaicStateTruthPosture, MosaicViewportConstraint, NamedMeasurementDefinition,
    NamedMeasurementToken, NativeCapabilityDescriptor, NativeCapabilityFamily, NativeCapabilityId,
    NativeCapabilityKey, NativePlatformPosture, NativeShellAuthorityClaim,
    PlatformInternalCapability, PluginCapabilityPermission, PluginContributionFamily,
    PluginSlotContributionReference, PluginSlotDescriptor, PluginSlotDiagnostics,
    PluginSlotGlobalMutationHook, PluginSlotId, PluginSlotKey, PluginSlotOrdering,
    PluginSlotSupportPosture, QueryDenialPresentation, RawColorOutsideTokenDefinition,
    RawIconAssetReference, RawLayoutMeasurementForDiagnostics, RawLayoutMeasurementKind,
    RuntimeOutcomeAffordance, RuntimeOutcomeDenialPosture, RuntimeOutcomeFamily,
    RuntimeOutcomePresentation, RuntimeOutcomeProjectionDescriptor, RuntimeOutcomeProjectionId,
    RuntimeOutcomeProjectionKey, RuntimeOutcomeRecoveryPosture, RuntimeOutcomeSourceReference,
    RuntimeOutcomeTone, SettingDefaultPosture, SettingDefaultValue, SettingDescriptor,
    SettingEditorHint, SettingId, SettingKey, SettingMigrationPosture, SettingOwnershipMetadata,
    SettingScope, SettingValidationPosture, SettingValueSchema, SurfaceDescriptor, SurfaceId,
    SurfaceKind, SurfacePlacementClass, SurfaceStateClass, TaskPresentationCancellationPosture,
    TaskPresentationDescriptor, TaskPresentationFailurePosture, TaskPresentationFamily,
    TaskPresentationId, TaskPresentationKey, TaskPresentationLifecyclePosture,
    TaskPresentationProjectionEligibility, TaskPresentationRuntimeAuthorityPosture,
    ThemeColorValue, ThemeColorValueError, ThemeTokenAlias, ThemeTokenDescriptor, ThemeTokenFamily,
    ThemeTokenId, ThemeTokenKey, ThemeTokenSource, ThemeTokenValue, ViewBindingDescriptor,
    ViewBindingFamily, ViewBindingId, VisibleStateBindingDeclaration, WorthUiViewBindingIdentity,
};
pub use worth_ui_runtime::facade::entry::CapabilityRegistrationBuilder;
pub use worth_ui_runtime::facade::inspection_bridge::{
    classify_inspection_dispatch, InspectionDispatchLane,
};
pub use worth_ui_runtime::facade::runtime_handoff::{
    UiActivatedScrollOwner, UiActivatedScrollProjectionTarget, WorthUiActivationLaneInput,
    WorthUiExecutionLaneInput, WorthUiPlanningLaneInput, WorthUiReplacementLoweringReady,
};
pub use worth_ui_runtime::facade::runtime_handoff::{
    WorthUiActiveRuntimeObservation, WorthUiRuntime, WorthUiRuntimeDiagnostic,
    WorthUiRuntimeDiagnosticCode, WorthUiRuntimeDiagnosticCounters, WorthUiRuntimeDiagnosticFamily,
    WorthUiRuntimeDiagnosticPolicy, WorthUiRuntimeDiagnosticReport,
    WorthUiRuntimeDiagnosticRequest, WorthUiRuntimeDiagnostics, WorthUiRuntimeFrameEpoch,
    WorthUiRuntimeHandle, WorthUiRuntimeLaunch, WorthUiRuntimeLaunchDenial,
    WorthUiRuntimeLifecycle, WorthUiRuntimeShutdownReceipt,
};
