//! Mounted identity and native-surface binding facade.

pub use worth_ui_runtime::facade::mounted::{
    UiHeadlessMountedResourceHandle, UiHostPresentationCompletionToken,
    UiHostPresentationCostInput, UiHostPresentationCostOverflow, UiHostPresentationCostReport,
    UiHostPresentationReconciliation, UiHostSurfaceBaselineReceipt,
    UiHostSurfaceCancellationOutcome, UiHostSurfaceIdentity, UiHostSurfaceInFlightCompletion,
    UiHostSurfacePresentationDenial, UiHostSurfacePresentationMode,
    UiHostSurfacePresentationOutcome, UiMountCostReport, UiMountIncarnation, UiMountNamedCounters,
    UiMountWorkClass, UiMountedAccessibilityProjection, UiMountedAllocationBasis,
    UiMountedAllocationProjection, UiMountedCanonicalBox, UiMountedCanonicalBoxInput,
    UiMountedClipProjection, UiMountedClipReference, UiMountedClipRow, UiMountedClipTable,
    UiMountedCompletedEffects, UiMountedCoordinateSpace, UiMountedDiagnosticProjection,
    UiMountedDiagnosticReference, UiMountedEffectFamily, UiMountedFrameCanonicalCore,
    UiMountedFrameDelta, UiMountedFrameExecutionPosture, UiMountedFrameIdentity,
    UiMountedFrameIdentityView, UiMountedFrameIntegrity, UiMountedFrameManifest,
    UiMountedFrameOutcome, UiMountedFramePreparationDenial, UiMountedFramePublicationReceipt,
    UiMountedFrameReceipt, UiMountedFrameRequest, UiMountedFrameRetentionBudget,
    UiMountedFrameRetentionDenial, UiMountedFrameRetentionRejection, UiMountedFrameReuse,
    UiMountedFrameReuseComparator, UiMountedFrameReuseContract, UiMountedFrameReuseDependency,
    UiMountedFrameReuseMintingStage, UiMountedFrameReuseWitness, UiMountedGeometryDenial,
    UiMountedGeometryPosture, UiMountedGraphNodeHandle, UiMountedGraphWorldIdentity,
    UiMountedIdentityBasis, UiMountedIdentityDenial, UiMountedIdentityView,
    UiMountedIndeterminateFrame, UiMountedInstanceIdentity, UiMountedInstanceIdentityView,
    UiMountedLaneParticipation, UiMountedLayerProjection, UiMountedLayerReference,
    UiMountedLayerRow, UiMountedLayerTable, UiMountedMotionProjection, UiMountedNodeProjectionView,
    UiMountedNodeReceipt, UiMountedNodeReceiptIdentity, UiMountedOmissionReason,
    UiMountedPaintBatchReference, UiMountedPaintBatchRow, UiMountedPaintBatchTable,
    UiMountedPaintPrimitiveKind, UiMountedPaintProjection, UiMountedParticipation,
    UiMountedParticipationFact, UiMountedParticipationStatus, UiMountedPresentationAdmission,
    UiMountedPresentationAdmissionDenial, UiMountedPresentationAdmissionRejection,
    UiMountedPresentationAttempt, UiMountedPresentationAttemptIdentity,
    UiMountedPresentationCompletionDenial, UiMountedPresentationInFlight,
    UiMountedPresentationOutcome, UiMountedPresentationReceipt,
    UiMountedPresentationShutdownAttempt, UiMountedPresentationShutdownDisposition,
    UiMountedPresentationShutdownReport, UiMountedPresentationWitness, UiMountedPresentedFrame,
    UiMountedPreviewProjection, UiMountedProjectionAudience, UiMountedProjectionDenial,
    UiMountedProjectionFrame, UiMountedProjectionView, UiMountedPublicationLeaseDenial,
    UiMountedRealtimeBatchReference, UiMountedRealtimeBatchRow, UiMountedRealtimeBatchTable,
    UiMountedRejectedFrame, UiMountedResourceEntry, UiMountedResourceKind,
    UiMountedResourceReference, UiMountedResourceTable, UiMountedRetentionClass,
    UiMountedRetentionClassBudget, UiMountedSpatialBatchReference, UiMountedSpatialBatchRow,
    UiMountedSpatialBatchTable, UiMountedSurfaceBindingRequirement,
    UiMountedSurfacePresentationCompletion, UiMountedSurfacePresentationReceipt,
    UiMountedSurfacePresentationRejection, UiMountedSurfaceReceipt,
    UiMountedSurfaceReconciliationBinding, UiMountedTableProjectionStatus,
    UiMountedTransformProjection, UiPreparedMountedFrame, UiPresentationDeadline,
    UiPresentationIndeterminateReport, UiProjectedMountedFrameCandidate,
    UiRequiredLaneContribution, UiRequiredLaneContributionStatus, UiSemanticSurfaceIdentity,
    UiSurfaceBindingCoordinatePosture, UiSurfaceBindingGeneration, UiSurfaceBindingIdentityView,
    UiSurfaceBindingProfile, WorthUiHeadlessMountedResourceCache,
    WorthUiMountedResourceCacheDenial,
};
