#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum WorthQueryCompatibilityDenialKind {
    NativeContractMismatched,
    NativeContractUnsupported,
    NativeMaskMismatched,
    NativeMaskUnsupported,
    NativeProducerShape,
    PortableOperationContract,
    PortableConditionalMismatched,
    PortableConditionalUnsupported,
    RuntimeAuthority,
    DomainInstallation,
    DomainRebindAuthority,
    InstallationGeneration,
    InstallationFreshness,
    BasisMismatched,
    BasisUnsupported,
    BasisLifecycle,
    GraphAuthority,
    RequiredDomainAuthority,
    ConditionalLoweringSet,
    ConditionalLowering,
    RelationshipRule,
}
