#[derive(Debug)]
pub enum WorthUiAllocationCatalogActivationDenial {
    InitialCatalogAlreadyEstablished,
    InitialGraphAuthorityMismatch,
    InitialNeighborhood(crate::graph::UiAllocationNeighborhoodDenial),
    InitialCatalogPlanning(crate::runtime::UiAllocationActivationCatalogDenial),
    InitialReceiptCommit(Box<crate::runtime::UiAllocationReceiptCommitOutcome>),
    Preparation(WorthUiAllocationCatalogPreparationStage),
    AllocationDelta(crate::runtime::UiAllocationCatalogDeltaClosureDenial),
    PlanInput(crate::runtime::WorthUiPlanLoweringDenial),
    CandidateGraphAuthority,
    CandidateArtifactAuthority,
    AllocationProjection,
    MissingQueryPosture,
    UnexpectedQueryPosture,
    QueryDefinitionNotInstalled,
    ForeignQueryInstalledAuthority,
    QuerySuccession(worth_ui_query_binding::WorthUiQueryBindingSuccessionDenial),
    RegionalDeltaDuplicateCandidateRegion,
    HandleAllocation,
    Freshness(crate::runtime::UiAllocationFreshnessConsumptionDenial),
    TopologyAssembly(crate::runtime::WorthUiPlanTopologyDenial),
    ExecutionPlanAuthorityMismatch,
    OrdinaryPlan(crate::runtime::WorthUiOrdinaryLanePlanDenial),
    VirtualizedPlan(crate::runtime::WorthUiVirtualizedDataPlanDenial),
    CanvasSpatialPlan(crate::runtime::WorthUiCanvasSpatialPlanDenial),
    RealtimeOverlayPlan(crate::runtime::WorthUiHudPlanDenial),
    ExecutableEquivalence(crate::runtime::WorthUiExecutablePlanEquivalenceDenial),
    CertificationBoundary(&'static str),
    Attempt(Box<crate::runtime::UiCommittedAllocationActivationDenial>),
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum WorthUiAllocationCatalogPreparationStage {
    PlanningAdmission,
    CatalogPlanning,
    ReceiptRecomputePending,
    ReceiptCatalogBindingCardinalityMismatch,
    ReceiptCatalogBindingIdentityMismatch,
    ReceiptCatalogActivationAuthority,
    ReceiptCandidatePlanningDenied,
    ReceiptReuseDenied,
    ReceiptAuthorityCounterExhausted,
    ReceiptEvidenceCounterExhausted,
    UnexpectedCommittedReceipt,
}
