pub use crate::inspection::visual_snapshot::{
    UiClearedVisualOverlayReceipt, UiClientRegionVisualTarget, UiCurrentPresentedSurfaceTarget,
    UiMountedNodeVisualTarget, UiPendingVisualCapture, UiPendingVisualOverlay,
    UiPublishedVisualOverlay, UiRetainedPresentedSurfaceTarget, UiSnapshotClientPixel,
    UiSnapshotClientRegion, UiUnbudgetedVisualSnapshotComparisonRequest,
    UiVisualCancellationPosture, UiVisualCancellationReceipt, UiVisualCapturePoll,
    UiVisualCaptureShutdownReport, UiVisualCoordinateScope, UiVisualGeometryGrant,
    UiVisualGrantLifetime, UiVisualGrantScope, UiVisualGrantSurfaceScope,
    UiVisualOverlayClearFailure, UiVisualOverlayGrant, UiVisualOverlayIdentity,
    UiVisualOverlayPublicationFailure, UiVisualOverlayShutdownReport, UiVisualOverlayTarget,
    UiVisualPixelCaptureGrant, UiVisualSnapshotComparisonGrant, UiVisualSnapshotComparisonRequest,
    UiVisualSnapshotDisposalReceipt, UiVisualSnapshotIdentity, UiVisualSnapshotOutcome,
    UiVisualSnapshotReceipt, UiVisualSnapshotRelationDenial, UiVisualTarget,
    WorthUiVisualInspectionAuthority,
};
