pub(crate) struct OwnedPrivateSurface {
    source_path: &'static str,
    surface_name: &'static str,
}

impl OwnedPrivateSurface {
    const fn new(source_path: &'static str, surface_name: &'static str) -> Self {
        Self {
            source_path,
            surface_name,
        }
    }
}

const PHASE_TWELVE_OWNED_PRIVATE_SURFACES: &[OwnedPrivateSurface] = &[
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/projected_overlap_faces/authority.rs", "bridge_authority_digest"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/projected_overlap_faces/bundle.rs", "require_candidate_pairs_match_context"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/projected_overlap_faces/bundle.rs", "extraction_bundle_digest"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/projected_overlap_faces/certified_face.rs", "certify_overlap_face"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/projected_overlap_faces/certified_face.rs", "certified_loop"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/projected_overlap_faces/certified_face.rs", "project_point"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/projected_overlap_faces/certified_pair.rs", "CertifiedProjectedOverlapCandidatePair::extract_with_second_face"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/projected_overlap_faces/certified_set.rs", "certified_face_set_digest"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/projected_overlap_faces/certified_set.rs", "certified_candidate_pairs"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/projected_overlap_faces/face_set.rs", "boundary_loops_by_owner"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/projected_overlap_faces/face_set.rs", "face_geometry_from_projected_boundary"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/overlap_edge_chains/construction.rs", "build_chain"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/overlap_edge_chains/construction.rs", "member_from_fragment"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/overlap_edge_chains/construction.rs", "boundary_role"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/overlap_edge_chains/construction.rs", "canonical_strings"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/overlap_edge_chains/construction.rs", "canonical_source_senses"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/overlap_edge_chains/construction.rs", "CounterBuild"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/overlap_edge_chains/construction.rs", "CounterBuild::new"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/overlap_edge_chains/construction.rs", "CounterBuild::record_chain"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/overlap_edge_chains/construction.rs", "CounterBuild::finish"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/overlap_edge_chains/identity.rs", "boundary_role_name"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/overlap_edge_chains/identity.rs", "posture_name"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/overlap_edge_chains/indexed_inputs.rs", "reject_mismatched_fragment_authority"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/overlap_edge_chains/indexed_inputs.rs", "fragment_overlaps_subdivision"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/overlap_edge_chains/indexed_inputs.rs", "canonicalize_fragment_members"),
    OwnedPrivateSurface::new("crates/worth-topo/src/derived_topology/invalidation_plan/migrated_products/traversal_views/closeout.rs", "non_traversal_placeholder_execution_count"),
    OwnedPrivateSurface::new("crates/worth-topo/src/derived_topology/invalidation_plan/migrated_products/traversal_views/closeout.rs", "traversal_views_row"),
    OwnedPrivateSurface::new("crates/worth-topo/src/derived_topology/invalidation_plan/migrated_products/traversal_views/closeout.rs", "closeout_digest"),
    OwnedPrivateSurface::new("crates/worth-topo/src/derived_topology/invalidation_plan/migrated_products/traversal_views/executor.rs", "fmt::Display for TraversalViewsMigrationError::fmt"),
    OwnedPrivateSurface::new("crates/worth-topo/src/derived_topology/invalidation_plan/migrated_products/traversal_views/executor.rs", "DerivedInvalidationProductExecutor for TraversalViewsDerivedProductExecutor::execute_selected_row"),
    OwnedPrivateSurface::new("crates/worth-topo/src/derived_topology/invalidation_plan/migrated_products/traversal_views/old_authority_residue.rs", "TraversalViewsOldAuthorityResidue::new"),
    OwnedPrivateSurface::new("crates/worth-topo/src/derived_topology/invalidation_plan/migrated_products/traversal_views/output.rs", "TraversalViewsProductRow::from_source_row"),
    OwnedPrivateSurface::new("crates/worth-topo/src/derived_topology/invalidation_plan/migrated_products/traversal_views/read_stage/receipt.rs", "touched_closure_traversal_bound"),
    OwnedPrivateSurface::new("crates/worth-topo/src/derived_topology/invalidation_plan/migrated_products/traversal_views/read_stage/source.rs", "available_traversal_source_rows_from_topology"),
    OwnedPrivateSurface::new("crates/worth-topo/src/derived_topology/invalidation_plan/migrated_products/traversal_views/read_stage/source.rs", "touched_traversal_anchor_entity_set"),
    OwnedPrivateSurface::new("crates/worth-topo/src/derived_topology/invalidation_plan/migrated_products/traversal_views/read_stage/source.rs", "traversal_read_source_digest"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/evidence_lookup_source_firewall/counters.rs", "EvidenceLookupSourceFirewallCounters::count_row"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/evidence_lookup_source_firewall/counters.rs", "EvidenceLookupSourceFirewallCounters::count_exception"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/evidence_lookup_source_firewall/report.rs", "report_from_snapshot"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/evidence_lookup_source_firewall/report.rs", "build_row"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/evidence_lookup_source_firewall/report.rs", "outcome_for_rows"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/evidence_lookup_source_firewall/report.rs", "firewall_digest"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/evidence_lookup_source_firewall/report.rs", "exception_summaries"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/evidence_lookup_source_firewall/scan_roots.rs", "SourceFirewallScanRoot"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/evidence_lookup_source_firewall/scan_roots.rs", "collect_records_below"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/evidence_lookup_source_firewall/scan_roots.rs", "rust_files_below"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/evidence_lookup_source_firewall/scan_roots.rs", "workspace_relative_path"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/evidence_lookup_source_firewall/scan_roots.rs", "workspace_root"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/evidence_lookup_source_firewall/scan_roots.rs", "looks_like_test_support_path"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/evidence_lookup_source_firewall/scan_roots.rs", "production_root"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/evidence_lookup_source_firewall/semantic_shape.rs", "push_match_if"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/evidence_lookup_source_firewall/semantic_shape.rs", "is_public_lookup_vocabulary_path"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/evidence_lookup_source_firewall/semantic_shape.rs", "is_receipt_lookup_surface_path"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/evidence_lookup_source_firewall/semantic_shape.rs", "is_raw_row_surface_path"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/evidence_lookup_source_firewall/semantic_shape.rs", "is_query_lookup_bridge_path"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/evidence_lookup_source_firewall/semantic_shape.rs", "is_copied_digest_surface_path"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/evidence_lookup_source_firewall/semantic_shape.rs", "is_kernel_lookup_residue_path"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/evidence_lookup_source_firewall/semantic_shape.rs", "mentions_public_evidence_row_surface"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/evidence_lookup_source_firewall/semantic_shape.rs", "mentions_raw_evidence_vector_access"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/evidence_lookup_source_firewall/semantic_shape.rs", "mentions_broad_receipt_scan"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/evidence_lookup_source_firewall/semantic_shape.rs", "mentions_stage_local_nearby_lookup"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/evidence_lookup_source_firewall/semantic_shape.rs", "mentions_copied_digest_lookup"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/evidence_lookup_source_firewall/semantic_shape.rs", "mentions_query_lookup_product_substitution"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/evidence_lookup_source_firewall/semantic_shape.rs", "mentions_kernel_stage_local_lookup"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/evidence_lookup_source_firewall/semantic_shape.rs", "contains_all"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/evidence_lookup_source_firewall/semantic_shape.rs", "contains_any"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/replay_undo_semantic_graph/undo_family_execution/rollback_admission.rs", "From<SpatialReplaySemanticGraphAdmissionError> for SpatialUndoFamilyExecutionError::from"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/replay_undo_semantic_graph/undo_family_execution/rollback_admission.rs", "From<SpatialUndoPlanError> for SpatialUndoFamilyExecutionError::from"),
    OwnedPrivateSurface::new("crates/worth-topo/src/replay_undo_semantic_graph/undo_family_execution/rollback_admission.rs", "From<TopologyUndoSemanticGraphAdmissionError> for TopologyUndoFamilyExecutionError::from"),
    OwnedPrivateSurface::new("crates/worth-topo/src/replay_undo_semantic_graph/undo_family_execution/rollback_admission.rs", "From<TopologyUndoPlanError> for TopologyUndoFamilyExecutionError::from"),
    OwnedPrivateSurface::new("crates/worth-kernel/src/workload_composition/conflict_input/spatial.rs", "SpatialConflictRoute"),
    OwnedPrivateSurface::new("crates/worth-kernel/src/workload_composition/conflict_input/spatial.rs", "conflict_vocabulary_error"),
    OwnedPrivateSurface::new("crates/worth-kernel/src/workload_composition/conflict_input/spatial.rs", "conflict_lookup_route_denial"),
    OwnedPrivateSurface::new("crates/worth-kernel/src/workload_composition/conflict_input/topology.rs", "TopologyConflictRoute"),
    OwnedPrivateSurface::new("crates/worth-kernel/src/workload_composition/conflict_input/topology.rs", "topology_participants"),
    OwnedPrivateSurface::new("crates/worth-kernel/src/workload_composition/conflict_input/topology.rs", "conflict_vocabulary_error"),
    OwnedPrivateSurface::new("crates/worth-kernel/src/workload_composition/worth_workload/lookup_consumed_workload/mod.rs", "LookupConsumedWorkloadComposition::require_resolution_product"),
    OwnedPrivateSurface::new("crates/worth-kernel/src/workload_composition/worth_workload/lookup_consumed_workload/reuse_resolution_denial.rs", "mismatch_locus_name"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/high_valence_singularity/singularity_workload.rs", "HighValenceSingularityWorkload::required_topology_neighborhood"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/high_valence_singularity/singularity_workload.rs", "HighValenceSingularityWorkload::require_admitted_valence"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/high_valence_singularity/singularity_workload.rs", "HighValenceSingularityWorkload::require_rebuild_motion_compatibility"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/high_valence_singularity/singularity_workload.rs", "HighValenceSingularityWorkload::require_predicate_certification"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/high_valence_singularity/singularity_workload.rs", "HighValenceSingularityWorkload::require_singularity_policy"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/high_valence_singularity/singularity_workload.rs", "HighValenceSingularityWorkload::require_evidence_integrity"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/high_valence_singularity/singularity_workload.rs", "HighValenceSingularityWorkload::singularity_counters"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/high_valence_singularity/singularity_workload.rs", "HighValenceSingularityWorkload::local_rebuild_evidence_digest"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/high_valence_singularity/singularity_workload.rs", "HighValenceSingularityWorkload::stage_counters"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/high_valence_singularity/singularity_workload.rs", "HighValenceSingularityWorkload::receipt_backed_stage_row"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/high_valence_singularity/singularity_workload.rs", "HighValenceSingularityWorkload::workload_identity"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/duplicate_split_normalization/contradiction_basis.rs", "SameParameterPointAuthority"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/duplicate_split_normalization/contradiction_basis.rs", "SameParameterPointAuthority::from_entry"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/duplicate_split_normalization/contradiction_basis.rs", "PointSplitCompatibilityBasis"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/duplicate_split_normalization/contradiction_basis.rs", "PointSplitCompatibilityBasis::from_entry"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/duplicate_split_normalization/normalization.rs", "normalized_schedule_from_ordered_schedule"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/duplicate_split_normalization/normalization.rs", "normalized_cuts_from_grouping"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/duplicate_split_normalization/normalization.rs", "CounterBuild"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/duplicate_split_normalization/normalization.rs", "CounterBuild::record_grouping"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/duplicate_split_normalization/normalization.rs", "CounterBuild::record_normalized_cuts"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/duplicate_split_normalization/normalization.rs", "CounterBuild::finish"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/duplicate_split_normalization/normalized_cut_builder.rs", "reject_contradictory_duplicate_group"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/duplicate_split_normalization/normalized_cut_builder.rs", "canonical_values"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/duplicate_split_normalization/normalized_cut_builder.rs", "canonical_multiset_values"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/duplicate_split_normalization/normalized_cut_builder.rs", "normalized_endpoint_authority"),
    OwnedPrivateSurface::new("crates/worth-spatial/src/workload_platform/planar_boolean_edge_splitting/duplicate_split_normalization/normalized_cut_builder.rs", "single_authority_value"),
];

pub(crate) fn phase_twelve_private_surface_is_owned(source_path: &str, surface_name: &str) -> bool {
    let normalized_source_path = source_path.replace('\\', "/");
    PHASE_TWELVE_OWNED_PRIVATE_SURFACES.iter().any(|surface| {
        surface.surface_name == surface_name
            && (normalized_source_path == surface.source_path
                || normalized_source_path.ends_with(surface.source_path))
    })
}
