use super::{record_layout_observation, LayoutOwnerObservationLedger};

impl LayoutOwnerObservationLedger {
    record_layout_observation!(
        record_catalog_root_materialization,
        CatalogRootMaterialization,
        forge_store_layout_indexes::materialization::CatalogRootMaterializationAdmissionCaseId,
        as_str
    );
    record_layout_observation!(
        record_btree_publication_materialization,
        BTreePublicationMaterialization,
        forge_store_layout_indexes::materialization::BTreePublicationMaterializationAdmissionCaseId,
        as_str
    );
    record_layout_observation!(
        record_btree_lookup_materialization,
        BTreeLookupMaterialization,
        forge_store_layout_indexes::materialization::BTreeLookupMaterializationAdmissionCaseId,
        as_str
    );
    record_layout_observation!(
        record_btree_replay_materialization,
        BTreeReplayMaterialization,
        forge_store_layout_indexes::materialization::BTreeReplayMaterializationAdmissionCaseId,
        as_str
    );
    record_layout_observation!(
        record_lsm_lookup_materialization,
        LsmLookupMaterialization,
        forge_store_layout_indexes::materialization::LsmLookupMaterializationAdmissionCaseId,
        as_str
    );
    record_layout_observation!(
        record_lsm_publication_materialization,
        LsmPublicationMaterialization,
        forge_store_layout_indexes::materialization::LsmPublicationMaterializationAdmissionCaseId,
        as_str
    );
    record_layout_observation!(
        record_lsm_replay_materialization,
        LsmReplayMaterialization,
        forge_store_layout_indexes::materialization::LsmReplayMaterializationAdmissionCaseId,
        as_str
    );
    record_layout_observation!(
        record_imported_blob_materialization,
        ImportedBlobMaterialization,
        forge_store_layout_indexes::materialization::ImportedBlobMaterializationAdmissionCaseId,
        as_str
    );
    record_layout_observation!(
        record_restored_artifact_materialization,
        RestoredArtifactMaterialization,
        forge_store_layout_indexes::materialization::RestoredArtifactMaterializationAdmissionCaseId,
        as_str
    );
}
