use super::classification::PlanarBooleanOverlapValidatorRuntimeLane as Lane;

pub(super) const REQUIRED_PHASE_2_VALIDATOR_LANES: &[(&str, Lane, bool)] = &[
    (
        "ValidatePlanarBooleanLoopLedgerConsumption",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateOverlapRegionReceiptEnvelopeConsistency",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateOverlapRegionLedgerReceiptChain",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "RejectOverlapRegionLedgerMissingDecisionLogReceipt",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "RejectOverlapRegionLedgerMissingPersistentNamingReceipt",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "RejectOverlapRegionLedgerForeignProductLineage",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateOverlapParticipationCoverage",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateOverlapChainLineageCoverage",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateLoopIslandOverlapBindingConsistency",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateNoDanglingOverlapParticipationReferences",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateCanonicalOverlapAdjacencyOrderingStable",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateNoNPlusOneOverlapNeighborhoodDiscovery",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateCoplanarOverlapArrangementConstruction",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateOverlapArrangementCellCoverage",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateOverlapCellContainmentConsistency",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateOverlapCellWindingFieldConsistency",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateOverlapIslandExtractionConsistency",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateBoundaryContactComponentPartition",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateAreaOverlapComponentPartition",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateSharedBoundaryContactClassificationConsistency",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateSharedAreaAdmissionConsistency",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateBoundaryOnlyIsNotAdmittedAreaRegion",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateMixedBoundaryAreaLocalization",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateOppositeSenseOverlapWindingNormalization",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateOverlapRegionCanonicalWindingConsistency",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateOverlapRegionPromotionBoundary",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateBoundaryOnlyOverlapLocalization",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateCoplanarOverlapRegionExtraction",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateOverlapRegionIdentityCanonicality",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidatePersistentNameUniqueness",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateNameSurvivalThroughOverlapRegionExtraction",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateNoDanglingNameReferences",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateOverlapRegionDecisionLogCoverage",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateOverlapRegionFailureLocalizationConsistency",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateCanonicalOrderingStable",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateHashStabilityAcrossRuns",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidateTieBreakerCoverage",
        Lane::SpatialPreparedProductValidation,
        false,
    ),
    (
        "ValidatePlanarBooleanOverlapRegionReplayParity",
        Lane::QueryGraphInvariantPack,
        true,
    ),
    (
        "ValidatePlanarBooleanOverlapRegionCheckpointParity",
        Lane::QueryGraphInvariantPack,
        true,
    ),
    (
        "ValidateOverlapRegionValidatorRuntimeRegistration",
        Lane::QueryGraphInvariantPack,
        true,
    ),
    (
        "ValidateOverlapRegionGraphInvariantPackRegistration",
        Lane::QueryGraphInvariantPack,
        true,
    ),
    (
        "ValidatePreparedSpatialOverlapProductsCannotMutateTopologyTruth",
        Lane::QueryGraphInvariantPack,
        true,
    ),
];
