use super::classification::{
    PlanarBooleanOverlapOperatorClassification as Class,
    PlanarBooleanOverlapRequiredQuerySurface as Surface,
};

pub(super) const REQUIRED_PHASE_2_OPERATOR_LANES: &[(&str, Class, Surface)] = &[
    (
        "ConsumePlanarBooleanLoopReconstructionLedger",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "DeclarePlanarBooleanOverlapRegionExtraction",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "AdmitPlanarBooleanOverlapRegionExtraction",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "BindOverlapExtractionToLoopLedgerReceipt",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "RecoverLoopOverlapParticipation",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "BindOverlapChainToLoopIslands",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "BuildOverlapRegionAdjacencyIndex",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "CanonicalizeOverlapAdjacencyOrder",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "BuildCoplanarOverlapArrangementGraph",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "BuildOverlapArrangementCellSet",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "BuildOverlapCellContainmentMap",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "BuildOverlapCellWindingField",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    ("ExtractOverlapIslands", Class::PreparedSpatialOnly, Surface::None),
    (
        "PartitionBoundaryContactComponents",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "PartitionAreaOverlapComponents",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "ClassifySharedBoundaryContact",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "BuildPureBoundaryOnlyOutcome",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    ("AdmitSharedAreaOverlap", Class::PreparedSpatialOnly, Surface::None),
    (
        "RejectBoundaryOnlyContactAsAreaRegion",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "RejectMixedBoundaryAreaWithoutCellClosure",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "NormalizeOppositeSenseOverlapWinding",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "PromoteOverlapRegionCandidate",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "RejectOverlapRegionCandidateBeforeIdentity",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "BuildOverlapRegionCanonicalWinding",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "CanonicalizeOverlapRegionBoundary",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "MintBooleanOverlapRegionIdentity",
        Class::PreparedSpatialOnly,
        Surface::None,
    ),
    (
        "PropagatePersistentNamesThroughOverlapRegionExtraction",
        Class::TopologyContributionWorkflow,
        Surface::TopologyContributionWorkflow,
    ),
    (
        "RecordOverlapRegionEntityParentage",
        Class::TopologyContributionWorkflow,
        Surface::TopologyContributionWorkflow,
    ),
    (
        "ForkOverlapRegionEntityLineage",
        Class::TopologyContributionWorkflow,
        Surface::TopologyContributionWorkflow,
    ),
    (
        "RegisterOverlapRegionGraphInvariantPack",
        Class::QueryGraphCompositionProgram,
        Surface::QueryInvariantRegistration,
    ),
    (
        "RecordOverlapRegionDecisionLog",
        Class::QueryGraphCompositionProgram,
        Surface::QueryGraphComposition,
    ),
    (
        "LocalizeOverlapRegionExtractionFailure",
        Class::QueryGraphCompositionProgram,
        Surface::QueryGraphComposition,
    ),
    (
        "BuildStructuredOverlapRegionFailureReport",
        Class::QueryGraphCompositionProgram,
        Surface::QueryGraphComposition,
    ),
    (
        "AssemblePlanarBooleanOverlapRegionLedger",
        Class::QueryGraphCompositionProgram,
        Surface::QueryGraphComposition,
    ),
    (
        "BuildOverlapRegionLedgerReceipt",
        Class::QueryGraphCompositionProgram,
        Surface::QueryGraphComposition,
    ),
    (
        "RequireBooleanOverlapRegionEvidence",
        Class::QueryGraphCompositionProgram,
        Surface::QueryGraphComposition,
    ),
    (
        "RegisterBooleanOverlapRegionStageRequirement",
        Class::QueryGraphCompositionProgram,
        Surface::QueryInvariantRegistration,
    ),
    (
        "ReplayPlanarBooleanOverlapRegionExtraction",
        Class::QueryGraphCompositionProgram,
        Surface::QueryGraphComposition,
    ),
    (
        "CompareOverlapRegionReplayParity",
        Class::QueryGraphCompositionProgram,
        Surface::QueryGraphComposition,
    ),
    (
        "CompareOverlapRegionCheckpointParity",
        Class::QueryGraphCompositionProgram,
        Surface::QueryGraphComposition,
    ),
    (
        "RejectSyntheticOverlapRegionEntry",
        Class::QueryGraphCompositionProgram,
        Surface::QueryInvariantRegistration,
    ),
    (
        "RejectUnindexedOverlapParticipation",
        Class::QueryGraphCompositionProgram,
        Surface::QueryInvariantRegistration,
    ),
    (
        "FenceFragmentClassificationToOverlapRegionLedgerReceipt",
        Class::QueryGraphCompositionProgram,
        Surface::QueryInvariantRegistration,
    ),
    (
        "ValidateOverlapRegionValidatorRuntimeRegistration",
        Class::QueryGraphCompositionProgram,
        Surface::QueryInvariantRegistration,
    ),
    (
        "RejectSyntheticOverlapRegionLedgerConstruction",
        Class::QueryGraphCompositionProgram,
        Surface::QueryInvariantRegistration,
    ),
];
