//! Public API boundary for topology.

pub use crate::brep::topology_graph::{
    TopologyBody, TopologyEdge, TopologyFace, TopologyHalfEdge, TopologyLoop, TopologyLump,
    TopologyModel, TopologyRegion, TopologyShell, TopologyVertex, TopologyView, TopologyWire,
};
pub use crate::certification::support::parity::{
    build_derived_equivalence_contract, compare_derived_equivalence_contracts,
    digest_derived_validation_report, digest_interpreted_topology_view,
    digest_materialized_topology_view, DerivedEquivalenceContractReport,
    DerivedParityComparisonReport,
};
pub use crate::certification::{
    certify_milestone_one_branch_local_primitive_scenarios, certify_milestone_one_closeout,
    certify_milestone_one_default_primitive_corpus, certify_milestone_one_primitive_corpus,
    certify_milestone_one_primitive_scenarios, certify_milestone_one_read_basis_traced,
    certify_milestone_three_ambiguous_local_rewire_continuity,
    certify_milestone_three_bowtie_adjacent_rewire,
    certify_milestone_three_broken_radial_localization,
    certify_milestone_three_cancellation_chain_parity, certify_milestone_three_closeout,
    certify_milestone_three_hostile_suite, certify_milestone_three_split_collapse_churn,
    certify_milestone_two_closeout, certify_milestone_two_default_derived_corpus,
    certify_milestone_two_read_basis_traced, certify_milestone_two_verified_topology_commit_traced,
    certify_verified_topology_commit_traced, milestone_one_closeout_requirements,
    milestone_one_closeout_suite_definition, milestone_three_closeout_requirements,
    milestone_three_closeout_suite_definition, milestone_two_closeout_requirements,
    milestone_two_closeout_suite_definition, AdmittedRangeSweepReport, AdmittedRangeSweepRow,
    BranchLocalTopologyReport, BridgeFamilyCoverageReport, BridgeFamilyCoverageRow,
    BridgeProofReport, CertificationBridgeExpectation, CertificationCanonicalRow,
    CertificationParityRow, CertificationRejectionRow, CertificationRequiredOutput,
    CertificationSuiteDefinition, CertificationSuiteRequirements,
    CertificationValidatorExpectation, DerivedEquivalenceContractAggregateReport,
    DerivedEquivalenceContractAggregateRow, DerivedFallbackAggregateReport,
    DerivedFallbackAggregateRow, DerivedFamilyCoverageMatrix, DerivedFamilyCoverageRow,
    DerivedFamilyParityMatrix, DerivedFamilyParityRow, DerivedInvalidationAggregateReport,
    DerivedInvalidationAggregateRow, DerivedRebuildAggregateReport, DerivedRebuildAggregateRow,
    DerivedValidatorCoverageReport, DerivedValidatorCoverageRow, DeterministicDigest,
    FailureLocalityReport, FailureLocalityRow, IllegalTopologyRejectionCaseReport,
    IllegalTopologyRejectionReport, MilestoneOneBranchLocalAggregateReport,
    MilestoneOneCertificationError, MilestoneOneCertificationHarness,
    MilestoneOneCertificationReport, MilestoneOneCloseoutReport, MilestoneOneCounters,
    MilestoneOneRejectionClassReport, MilestoneOneRejectionClassRow,
    MilestoneOneReplayAggregateReport, MilestoneOneValidationAggregateReport,
    MilestoneOneValidationAggregateRow, MilestoneOneValidatorCoverageReport,
    MilestoneOneValidatorCoverageRow, MilestoneThreeAmbiguousLocalRewireWitness,
    MilestoneThreeBowtieAdjacentWitness, MilestoneThreeBrokenRadialWitness,
    MilestoneThreeChangedScopeCoverageRow, MilestoneThreeDerivedRegionCoverageRow,
    MilestoneThreeDeterminismRuleKind, MilestoneThreeDeterminismRuleRow,
    MilestoneThreeEditBranchLocalParityRow, MilestoneThreeEditBreadthCounterRow,
    MilestoneThreeEditFalloutBreadthRow, MilestoneThreeEditFalloutClass,
    MilestoneThreeEditReplayParityReport, MilestoneThreeEditReplayParityRow,
    MilestoneThreeEditReplayStepRow, MilestoneThreeEditedTopologyQueryTraversalRow,
    MilestoneThreeEditedTopologyQueryTraversalView, MilestoneThreeFailureLocalityRow,
    MilestoneThreeHostileCertificationCategory, MilestoneThreeHostileCertificationCategoryRow,
    MilestoneThreeHostileCertificationStatus, MilestoneThreeHostileCoverageRow,
    MilestoneThreeHostileFamilyCoverageRow, MilestoneThreeHostileNamingDistributionRow,
    MilestoneThreeHostileOutcomeClass, MilestoneThreeHostileRejectionDistributionRow,
    MilestoneThreeHostileScenario, MilestoneThreeHostileScenarioReport,
    MilestoneThreeHostileSuiteReport, MilestoneThreeNamingContinuityMatrixRow,
    MilestoneThreePrimitiveFamilyClosureRow, MilestoneThreeRejectedEditScopeReportRow,
    MilestoneThreeReturnGateBlockerRow, MilestoneThreeSideQuestBlockerRow,
    MilestoneThreeSideQuestCloseoutReport, MilestoneThreeSideQuestContractRow,
    MilestoneThreeSplitCollapseChurnWitness, MilestoneThreeTopologyEditDigestRow,
    MilestoneThreeValidatorFamily, MilestoneThreeValidatorFamilyCoverageRow,
    MilestoneTwoBranchLocalParityReport, MilestoneTwoCloseoutReport, MilestoneTwoCounters,
    MilestoneTwoDerivedCorpusReport, MilestoneTwoDerivedReadReport, MilestoneTwoReplayParityReport,
    NamingAttachmentAggregateReport, NamingAttachmentAggregateRow, NamingAttachmentReport,
    NamingAttachmentRow, PrimitiveCorpusCaseReport, PrimitiveCorpusCoverageEntry,
    PrimitiveCorpusCoverageMatrix, PrimitiveCorpusParityEntry, PrimitiveCorpusParityReport,
    PrimitiveCorpusRejectedCaseReport, PrimitiveCorpusReport, PrimitiveFamilyCoverageEntry,
    PrimitiveFamilyCoverageMatrix, PrimitiveRejectionReport, ReplayParityReport,
    ReplayParityStatus, TopologyCertificationError, TopologyLocalizationAggregateEntityRow,
    TopologyLocalizationAggregateRelationRow, TopologyLocalizationAggregateReport,
    TopologyLocalizationEntityRow, TopologyLocalizationRelationRow, TopologyLocalizationReport,
    TracedMilestoneOneCertificationReport, TracedMilestoneTwoDerivedReadReport,
};
pub use crate::derived_topology::materialized_graph::{
    MaterializationBreadthReport, MaterializationFallbackClass, MaterializationReport,
    MaterializedTopologyView, TopologyMaterializationError, TopologyMaterializer,
};
pub use crate::derived_topology::traversal_views::{
    build_topology_read_artifact, certify_topology_view, interpret_topology_view,
    BoundaryInterpretationSummary, InterpretationReport, InterpretedTopologyView,
    RadialInterpretationSummary, ShellInterpretation, TopologyInterpretationSet,
    TopologyInterpreter, WireInterpretation,
};
pub use crate::projection::diagnostic_surfaces::{
    build_derived_fallback_report, build_derived_invalidation_report,
    build_derived_read_diagnostics, build_derived_rebuild_report, DerivedFallbackReport,
    DerivedInvalidationReport, DerivedInvalidationTargetRow, DerivedReadDiagnostics,
    DerivedRebuildReport,
};
pub use crate::projection::runtime_boundary::bridge::{
    build_milestone_one_bridge, milestone_one_bridge_aspect_registrations,
    milestone_one_bridge_mapping_registrations,
};
pub use crate::projection::runtime_boundary::query_assembly::{
    TopologyQueryAppliedIntent, TopologyQueryApplyError, TopologyQueryAssembly,
    TopologyQuerySnapshot,
};
pub use crate::projection::runtime_boundary::query_runtime::{
    topology_runtime, TopologyQueryEditFamilySupportStatus, TopologyQueryEditLane,
    TopologyQueryEditLaneExecutionShape, TopologyQueryEditLaneSupportStatus,
    TopologyQueryReadFamilySupportStatus, TopologyRuntimeAdapters, TopologyRuntimeCloseout,
    TopologyRuntimeCloseoutFamily, TopologyRuntimeCloseoutRow, TopologyRuntimeCloseoutStatus,
    TopologyRuntimeEditFamilySupportRow, TopologyRuntimeEditLaneSupportRow, TopologyRuntimeFailure,
    TopologyRuntimePostureCapability, TopologyRuntimePostureRow, TopologyRuntimePostureStatus,
    TopologyRuntimeReadFamilySupportRow, TopologyRuntimeSupport,
};
pub use crate::projection::{
    declare_persistent_name_live_view, declare_topology_diagnostics_surface,
    declare_topology_entity_live_view, declare_topology_equivalence_contract_surface,
    declare_topology_interpreted_surface, declare_topology_materialized_surface,
    declare_topology_relation_live_view, declare_topology_validation_surface,
    derived_read_diagnostics_from_query_rows, equivalence_contract_from_diagnostics_rows,
    interpreted_topology_from_materialized_rows, naming_attachment_report_from_query_rows,
    persistent_name_live_view_declaration, topology_diagnostics_computed_declaration,
    topology_entity_live_view_declaration, topology_equivalence_contract_computed_declaration,
    topology_interpreted_computed_declaration, topology_materialized_computed_declaration,
    topology_relation_live_view_declaration, topology_validation_computed_declaration,
    validation_report_from_query_rows, TopologyDiagnosticsMaintainer, TopologyDomainQuery,
    TopologyDomainQueryAggregateReport, TopologyDomainQueryCloseoutReport,
    TopologyDomainQueryCloseoutRow, TopologyDomainQueryCloseoutStatus, TopologyDomainQueryDebtRow,
    TopologyDomainQueryError, TopologyDomainQueryErrorKind,
    TopologyDomainQueryExecutionAggregateRow, TopologyDomainQueryExecutionEngine,
    TopologyDomainQueryFallbackPosture, TopologyDomainQueryFamilyAggregateRow,
    TopologyDomainQueryLoweringPosture, TopologyDomainQueryParityAggregateReport,
    TopologyDomainQueryParityAggregateRow, TopologyDomainQueryParityKind,
    TopologyDomainQueryPhaseThreeBlocker, TopologyDomainQueryPhaseThreeBlockerRow,
    TopologyDomainQueryPhaseThreeBlockerStatus, TopologyDomainQueryProofReport,
    TopologyDomainQueryRelationshipProofPosture, TopologyDomainQueryRequestFamily,
    TopologyDomainQueryRequestReport, TopologyEquivalenceContractMaintainer,
    TopologyHalfEdgeRadialNeighborhoodView, TopologyHalfEdgeSharedVertexNeighborhoodView,
    TopologyInterpretedMaintainer, TopologyLocalRewireNeighborhoodView, TopologyLoopCycleView,
    TopologyMaterializedMaintainer, TopologyNoNPlusOneContract, TopologyNoNPlusOneContractRow,
    TopologyNoNPlusOneContractStatus, TopologyQueryMutationEvidence, TopologyQuerySurfaceError,
    TopologyValidationMaintainer,
};
pub use crate::topology_operators::{
    BoundaryMembershipKind, LoopEndpointKind, LoopSuccessorKind, NamingEditContinuityMatrix,
    RejectedEditScopeReport, RejectedEditScopeRow, ShellOrWireMembershipKind,
    TopologyDerivedRegion, TopologyEditAction, TopologyEditApplicationMode, TopologyEditBatch,
    TopologyEditChangedScope, TopologyEditContract, TopologyEditDigest, TopologyEditFamily,
    TopologyEditNamingOutcome, TopologyEditNamingReport, TopologyEditNamingRow,
    TopologyEditNamingScope, TopologyEditRejectionClass, TopologyOperatorExecution,
    TopologyOperatorExecutionError,
};
pub use crate::validation::reference_integrity::{
    build_milestone_one_runtime, configure_milestone_one_runtime_builder,
    milestone_one_runtime_builder, milestone_one_runtime_invariants, MilestoneOneRuntimeSetupError,
};
pub use crate::validation::{
    topology_validation_report, validate_interpreted_topology, validate_materialized_topology,
    validate_named_topology_truth, validate_topology_view, DerivedTopologyValidationReport,
    TopologyValidationError, TopologyValidationInputClass, TopologyValidationPhase,
    TopologyValidationReport, TopologyValidationRow, TopologyValidator,
};
